import MGAP4D.Constructive.Gap3320
import MGAP4D.Constructive.Eigenvector
import MGAP4D.Constructive.PlaquetteWitness
import MGAP4D.Constructive.FinalTheorem
import MGAP4D.Constructive.ObservableSpectralWeightBridge
import MGAP4D.Constructive.ObservableSpectralWeightPreReleaseBridge
import MGAP4D.Constructive.ObservableSpectralWeightClosure
