import MGAP4D.MathlibAnalytic.CompactPositiveSpectralSupportLogGeneratorResolventDerivativeRatioParameterMonotonicity
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory Set Module End Filter
open scoped InnerProductSpace LinearPMap Topology BigOperators

noncomputable section

set_option maxHeartbeats 3000000
set_option synthInstance.maxHeartbeats 200000

universe u

/-- A nontrivial scalar multiple cannot cancel a vector against a genuinely
non-collinear companion. -/
theorem real_smul_sub_ne_zero_of_not_smul
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (x y : E) (a d : ℝ) (ha : a ≠ 0)
    (hnot : ∀ r : ℝ, y ≠ r • x) :
    a • y - d • x ≠ 0 := by
  intro hz
  apply hnot (d / a)
  have hxy : a • y = d • x := sub_eq_zero.mp hz
  calc
    y = a⁻¹ • (a • y) := by simp [smul_smul, ha]
    _ = a⁻¹ • (d • x) := by rw [hxy]
    _ = (a⁻¹ * d) • x := by rw [smul_smul]
    _ = (d / a) • x := by rw [div_eq_mul_inv, mul_comm]

/-- Strict real Cauchy--Schwarz in squared form under non-collinearity. -/
theorem real_inner_sq_lt_inner_self_mul_of_not_smul
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (x : E) (hx : x ≠ 0) (y : E)
    (hnot : ∀ r : ℝ, y ≠ r • x) :
    (inner ℝ y x) ^ 2 < inner ℝ x x * inner ℝ y y := by
  let a := inner ℝ x x
  let d := inner ℝ y x
  have ha : 0 < a := by
    simpa [a] using (real_inner_self_pos.mpr hx)
  let z := a • y - d • x
  have hz : z ≠ 0 := by
    exact real_smul_sub_ne_zero_of_not_smul x y a d ha.ne' hnot
  have hzpos : 0 < inner ℝ z z := real_inner_self_pos.mpr hz
  dsimp [z] at hzpos
  simp only [inner_sub_left, inner_sub_right,
    real_inner_smul_left, real_inner_smul_right] at hzpos
  rw [real_inner_comm x y] at hzpos
  change d ^ 2 < a * inner ℝ y y
  dsimp [a, d] at hzpos ⊢
  nlinarith

/-- Strict weighted Cauchy--Schwarz for the positive bilinear form generated by
a strictly positive self-adjoint bounded operator. -/
theorem realContinuousLinearMap_weighted_inner_sq_lt
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →L[ℝ] E) (hself : IsSelfAdjoint A)
    (hpos : ∀ z : E, z ≠ 0 → 0 < inner ℝ (A z) z)
    (x : E) (hx : x ≠ 0) (y : E)
    (hnot : ∀ r : ℝ, y ≠ r • x) :
    (inner ℝ (A x) y) ^ 2 < inner ℝ (A x) x * inner ℝ (A y) y := by
  have hsymm : A.toLinearMap.IsSymmetric :=
    (ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric).mp hself
  let a := inner ℝ (A x) x
  let d := inner ℝ (A x) y
  have ha : 0 < a := by simpa [a] using hpos x hx
  have hsymm_yx : inner ℝ (A y) x = d := by
    calc
      inner ℝ (A y) x = inner ℝ y (A x) := hsymm y x
      _ = inner ℝ (A x) y := real_inner_comm _ _
      _ = d := rfl
  let z := a • y - d • x
  have hz : z ≠ 0 := by
    exact real_smul_sub_ne_zero_of_not_smul x y a d ha.ne' hnot
  have hzpos : 0 < inner ℝ (A z) z := hpos z hz
  dsimp [z] at hzpos
  simp only [map_sub, map_smul, inner_sub_left, inner_sub_right,
    real_inner_smul_left, real_inner_smul_right] at hzpos
  rw [hsymm_yx] at hzpos
  change d ^ 2 < a * inner ℝ (A y) y
  dsimp [a, d] at hzpos ⊢
  nlinarith

/-- Injectivity transports failure of the eigenvector relation from `u` to
`A u`. -/
theorem realContinuousLinearMap_not_smul_propagate
    {E : Type u} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A : E →L[ℝ] E) (hinj : Function.Injective A)
    (u : E) (hnot : ∀ r : ℝ, A u ≠ r • u) :
    ∀ r : ℝ, A (A u) ≠ r • A u := by
  intro r hr
  apply hnot r
  apply hinj
  simpa using hr

/-- Away from an eigenvector, every positive self-adjoint power moment is
strictly log-convex.  The same two parity base cases as the non-strict theorem
close the whole hierarchy, because injectivity propagates non-collinearity. -/
theorem realContinuousLinearMap_pow_inner_strictLogConvex_of_not_eigenvector
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →L[ℝ] E) (hself : IsSelfAdjoint A) (hinj : Function.Injective A)
    (hpos : ∀ z : E, z ≠ 0 → 0 < inner ℝ (A z) z)
    (n : ℕ) (u : E) (hu : u ≠ 0)
    (hnot : ∀ r : ℝ, A u ≠ r • u) :
    (inner ℝ ((A ^ (n + 1)) u) u) ^ 2 <
      inner ℝ ((A ^ n) u) u * inner ℝ ((A ^ (n + 2)) u) u := by
  induction n using Nat.strong_induction_on generalizing u with
  | h n ih =>
      rcases n with _ | n
      · have hs := real_inner_sq_lt_inner_self_mul_of_not_smul u hu (A u) hnot
        have hshift := realContinuousLinearMap_pow_inner_shift_two A hself 0 u
        simp at hshift
        simpa [hshift] using hs
      · rcases n with _ | k
        · have hw :=
            realContinuousLinearMap_weighted_inner_sq_lt
              A hself hpos u hu (A u) hnot
          have hshift0 := realContinuousLinearMap_pow_inner_shift_two A hself 0 u
          have hshift1 := realContinuousLinearMap_pow_inner_shift_two A hself 1 u
          simp at hshift0 hshift1
          simpa [hshift0, hshift1] using hw
        · have hAu : A u ≠ 0 := by
            intro hzero
            apply hu
            apply hinj
            simpa using hzero
          have hnotAu : ∀ r : ℝ, A (A u) ≠ r • A u :=
            realContinuousLinearMap_not_smul_propagate A hinj u hnot
          have hind := ih k (by omega) (A u) hAu hnotAu
          have hs0 := realContinuousLinearMap_pow_inner_shift_two A hself k u
          have hs1 := realContinuousLinearMap_pow_inner_shift_two A hself (k + 1) u
          have hs2 := realContinuousLinearMap_pow_inner_shift_two A hself (k + 2) u
          rw [show k + 2 + 1 = (k + 1) + 2 by omega, hs1,
            show k + 2 + 2 = (k + 2) + 2 by omega, hs2, hs0]
          exact hind

/-- Strict log-convexity of coercively generated ambient resolvent moments for
a state that is not an eigenvector of the bounded resolvent at the chosen
spectral parameter. -/
theorem realLinearPMapAmbientResolventFamily_pow_inner_strictLogConvex_of_not_eigenvector
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →ₗ.[ℝ] E) (c : ℝ) (hc : 0 < c)
    (hNorm : ∀ x : A.domain, c * ‖(x : E)‖ ≤ ‖A x‖)
    (hKer : ∀ x : A.domain, A x = 0 → x = 0)
    (hSurj : Function.Surjective A.toFun) (hSelf : IsSelfAdjoint A)
    (hQuad : ∀ x : A.domain, c * ‖(x : E)‖ ^ 2 ≤ inner ℝ (A x) (x : E))
    (lambda : ℝ) (hlambda : |lambda| < c) (n : ℕ) (u : E) (hu : u ≠ 0)
    (hnot : ∀ r : ℝ,
      realLinearPMapAmbientResolventFamily_of_norm_lower_bound
        A c hc hNorm hKer hSurj lambda u ≠ r • u) :
    let F := realLinearPMapAmbientResolventFamily_of_norm_lower_bound
      A c hc hNorm hKer hSurj lambda
    (inner ℝ ((F ^ (n + 1)) u) u) ^ 2 <
      inner ℝ ((F ^ n) u) u * inner ℝ ((F ^ (n + 2)) u) u := by
  dsimp only
  exact
    realContinuousLinearMap_pow_inner_strictLogConvex_of_not_eigenvector
      (realLinearPMapAmbientResolventFamily_of_norm_lower_bound
        A c hc hNorm hKer hSurj lambda)
      (realLinearPMapAmbientResolventFamily_isSelfAdjoint_of_isSelfAdjoint
        A c hc hNorm hKer hSurj hSelf lambda hlambda)
      (realLinearPMapAmbientResolventFamily_injective
        A c hc hNorm hKer hSurj lambda hlambda)
      (fun y hy =>
        realLinearPMapAmbientResolventFamily_inner_pos_of_quadratic_lower_bound
          A c hc hNorm hKer hSurj hQuad lambda hlambda y hy)
      n u hu hnot

/-- Strict factorial-normalized Turán inequality away from a resolvent
eigenvector. -/
theorem realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_turan_strict
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →ₗ.[ℝ] E) (c : ℝ) (hc : 0 < c)
    (hNorm : ∀ x : A.domain, c * ‖(x : E)‖ ≤ ‖A x‖)
    (hKer : ∀ x : A.domain, A x = 0 → x = 0)
    (hSurj : Function.Surjective A.toFun) (hSelf : IsSelfAdjoint A)
    (hQuad : ∀ x : A.domain, c * ‖(x : E)‖ ^ 2 ≤ inner ℝ (A x) (x : E))
    (u : E) (hu : u ≠ 0) (n : ℕ) (lambda : ℝ) (hlambda : |lambda| < c)
    (hnot : ∀ r : ℝ,
      realLinearPMapAmbientResolventFamily_of_norm_lower_bound
        A c hc hNorm hKer hSurj lambda u ≠ r • u) :
    (n + 2 : ℝ) *
        (iteratedDeriv (n + 1)
          (realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u) lambda) ^ 2 <
      (n + 1 : ℝ) *
        iteratedDeriv n
          (realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u) lambda *
        iteratedDeriv (n + 2)
          (realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u) lambda := by
  let F := realLinearPMapAmbientResolventFamily_of_norm_lower_bound
    A c hc hNorm hKer hSurj lambda
  have hm :=
    realLinearPMapAmbientResolventFamily_pow_inner_strictLogConvex_of_not_eigenvector
      A c hc hNorm hKer hSurj hSelf hQuad lambda hlambda (n + 1) u hu hnot
  dsimp only at hm
  rw [realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_eq_factorial
      A c hc hNorm hKer hSurj u n lambda hlambda,
    realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_eq_factorial
      A c hc hNorm hKer hSurj u (n + 1) lambda hlambda,
    realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_eq_factorial
      A c hc hNorm hKer hSurj u (n + 2) lambda hlambda]
  change
    (n + 2 : ℝ) *
        (((n + 1).factorial : ℝ) * inner ℝ ((F ^ (n + 2)) u) u) ^ 2 <
      (n + 1 : ℝ) *
        ((n.factorial : ℝ) * inner ℝ ((F ^ (n + 1)) u) u) *
        (((n + 2).factorial : ℝ) * inner ℝ ((F ^ (n + 3)) u) u)
  have hcoef : 0 < (n + 2 : ℝ) * (((n + 1).factorial : ℝ) ^ 2) := by positivity
  have hmul := mul_lt_mul_of_pos_left hm hcoef
  norm_num [Nat.factorial_succ] at hmul ⊢
  ring_nf at hmul ⊢
  exact hmul

/-- Consecutive normalized derivative ratios are strictly ordered whenever the
state is not a resolvent eigenvector. -/
theorem realLinearPMapAmbientResolventQuadraticAmplitude_derivativeRatio_strict_mono
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →ₗ.[ℝ] E) (c : ℝ) (hc : 0 < c)
    (hNorm : ∀ x : A.domain, c * ‖(x : E)‖ ≤ ‖A x‖)
    (hKer : ∀ x : A.domain, A x = 0 → x = 0)
    (hSurj : Function.Surjective A.toFun) (hSelf : IsSelfAdjoint A)
    (hQuad : ∀ x : A.domain, c * ‖(x : E)‖ ^ 2 ≤ inner ℝ (A x) (x : E))
    (u : E) (hu : u ≠ 0) (n : ℕ) (lambda : ℝ) (hlambda : |lambda| < c)
    (hnot : ∀ r : ℝ,
      realLinearPMapAmbientResolventFamily_of_norm_lower_bound
        A c hc hNorm hKer hSurj lambda u ≠ r • u) :
    let q := realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u
    iteratedDeriv (n + 1) q lambda /
        ((n + 1 : ℝ) * iteratedDeriv n q lambda) <
      iteratedDeriv (n + 2) q lambda /
        ((n + 2 : ℝ) * iteratedDeriv (n + 1) q lambda) := by
  let q := realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u
  change iteratedDeriv (n + 1) q lambda /
      ((n + 1 : ℝ) * iteratedDeriv n q lambda) <
    iteratedDeriv (n + 2) q lambda /
      ((n + 2 : ℝ) * iteratedDeriv (n + 1) q lambda)
  have hn : 0 < iteratedDeriv n q lambda := by
    simpa [q] using
      (realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_pos
        A c hc hNorm hKer hSurj hSelf hQuad u hu n lambda hlambda)
  have hn1 : 0 < iteratedDeriv (n + 1) q lambda := by
    simpa [q] using
      (realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_pos
        A c hc hNorm hKer hSurj hSelf hQuad u hu (n + 1) lambda hlambda)
  have hden0 : 0 < (n + 1 : ℝ) * iteratedDeriv n q lambda := by positivity
  have hden1 : 0 < (n + 2 : ℝ) * iteratedDeriv (n + 1) q lambda := by positivity
  rw [div_lt_div_iff₀ hden0 hden1]
  have hturan :=
    realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_turan_strict
      A c hc hNorm hKer hSurj hSelf hQuad u hu n lambda hlambda hnot
  change
    iteratedDeriv (n + 1) q lambda *
        ((n + 2 : ℝ) * iteratedDeriv (n + 1) q lambda) <
      iteratedDeriv (n + 2) q lambda *
        ((n + 1 : ℝ) * iteratedDeriv n q lambda)
  nlinarith

/-- The normalized derivative-ratio sequence is strictly monotone in order
away from a resolvent eigenvector. -/
theorem realLinearPMapAmbientResolventQuadraticAmplitude_derivativeRatio_strictMono
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →ₗ.[ℝ] E) (c : ℝ) (hc : 0 < c)
    (hNorm : ∀ x : A.domain, c * ‖(x : E)‖ ≤ ‖A x‖)
    (hKer : ∀ x : A.domain, A x = 0 → x = 0)
    (hSurj : Function.Surjective A.toFun) (hSelf : IsSelfAdjoint A)
    (hQuad : ∀ x : A.domain, c * ‖(x : E)‖ ^ 2 ≤ inner ℝ (A x) (x : E))
    (u : E) (hu : u ≠ 0) (lambda : ℝ) (hlambda : |lambda| < c)
    (hnot : ∀ r : ℝ,
      realLinearPMapAmbientResolventFamily_of_norm_lower_bound
        A c hc hNorm hKer hSurj lambda u ≠ r • u) :
    let q := realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u
    StrictMono (fun n : ℕ =>
      iteratedDeriv (n + 1) q lambda /
        ((n + 1 : ℝ) * iteratedDeriv n q lambda)) := by
  dsimp only
  apply strictMono_nat_of_lt_succ
  intro n
  have h :=
    realLinearPMapAmbientResolventQuadraticAmplitude_derivativeRatio_strict_mono
      A c hc hNorm hKer hSurj hSelf hQuad u hu n lambda hlambda hnot
  convert h using 1 <;> norm_num <;> ring

/-- Equality of two distinct normalized derivative-ratio levels is rigid: it
forces the state to be an eigenvector of the bounded resolvent. -/
theorem realLinearPMapAmbientResolventQuadraticAmplitude_derivativeRatio_eq_imp_resolvent_eigenvector
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →ₗ.[ℝ] E) (c : ℝ) (hc : 0 < c)
    (hNorm : ∀ x : A.domain, c * ‖(x : E)‖ ≤ ‖A x‖)
    (hKer : ∀ x : A.domain, A x = 0 → x = 0)
    (hSurj : Function.Surjective A.toFun) (hSelf : IsSelfAdjoint A)
    (hQuad : ∀ x : A.domain, c * ‖(x : E)‖ ^ 2 ≤ inner ℝ (A x) (x : E))
    (u : E) (hu : u ≠ 0) (lambda : ℝ) (hlambda : |lambda| < c)
    {n m : ℕ} (hnm : n < m)
    (heq :
      let q := realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u
      iteratedDeriv (n + 1) q lambda /
          ((n + 1 : ℝ) * iteratedDeriv n q lambda) =
        iteratedDeriv (m + 1) q lambda /
          ((m + 1 : ℝ) * iteratedDeriv m q lambda)) :
    ∃ r : ℝ,
      realLinearPMapAmbientResolventFamily_of_norm_lower_bound
        A c hc hNorm hKer hSurj lambda u = r • u := by
  by_contra hnone
  have hnot : ∀ r : ℝ,
      realLinearPMapAmbientResolventFamily_of_norm_lower_bound
        A c hc hNorm hKer hSurj lambda u ≠ r • u := by
    intro r hr
    exact hnone ⟨r, hr⟩
  have hstrict :=
    realLinearPMapAmbientResolventQuadraticAmplitude_derivativeRatio_strictMono
      A c hc hNorm hKer hSurj hSelf hQuad u hu lambda hlambda hnot
  have hlt := hstrict hnm
  dsimp only at heq
  exact hlt.ne heq

end

end MathlibAnalytic
end MGAP4D
