import MGAP4D.MathlibAnalytic.CompactOrientedGaugeWilsonSingleLinkCanonicalCoordinates

namespace MGAP4D
namespace MathlibAnalytic

#check CompactOrientedGaugeWilsonSystem.replaceLink
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoltzmannFactor
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkPartitionFunction
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalMeasure
#check continuous_compact_oriented_singleLinkConditionalMeasure_isProbabilityMeasure
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalKernel
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathKernel
#check continuous_compact_oriented_lintegral_singleLinkHeatBathKernel
#check continuous_compact_oriented_singleLinkHeatBathKernel_idempotent
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathProjection
#check continuous_compact_oriented_singleLinkHeatBathProjection_idempotent
#check continuous_compact_oriented_singleLink_density_detailedBalance
#check CompactOrientedGaugeWilsonSystem.singleLinkCoordinatesMeasurableEquiv
#check CompactOrientedGaugeWilsonSystem.canonicalSingleLinkCoordinatesMeasurableEquiv
#check compact_oriented_canonicalSingleLinkCoordinates_measurePreserving
#check compact_oriented_canonicalSingleLinkCoordinates_replaceLink

end MathlibAnalytic
end MGAP4D
