import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonHeatBathJointIntegralSymmetry

namespace MGAP4D
namespace MathlibAnalytic

#check CompactOrientedGaugeWilsonSystem.replaceLink
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoltzmannFactor
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkPartitionFunction
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalMeasure
#check continuous_compact_oriented_singleLinkConditionalMeasure_isProbabilityMeasure
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalKernel
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathKernel
#check continuous_compact_oriented_lintegral_singleLinkHeatBathKernel
#check continuous_compact_oriented_singleLinkHeatBathKernel_idempotent
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathProjection
#check continuous_compact_oriented_singleLinkHeatBathProjection_idempotent
#check continuous_compact_oriented_singleLink_density_detailedBalance
#check CompactOrientedGaugeWilsonSystem.singleLinkCoordinatesMeasurableEquiv
#check compact_oriented_canonicalSingleLinkCoordinates_measurePreserving
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathTransitionLIntegral
#check continuous_compact_oriented_singleLinkHeatBathTransitionLIntegral_eq_jointFubini
#check continuous_compact_oriented_lintegral_swap_old_new
#check continuous_compact_oriented_singleLinkHeatBathTransitionLIntegral_symm
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathJointMeasure
#check continuous_compact_oriented_map_swap_singleLinkHeatBathJointMeasure
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathJointSwapMeasurePreserving
#check continuous_compact_oriented_integral_singleLinkHeatBathJointMeasure_symm

end MathlibAnalytic
end MGAP4D
