import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonHeatBathHamiltonianKernelIdentification

namespace MGAP4D
namespace MathlibAnalytic

#check CompactOrientedGaugeWilsonSystem.replaceLink
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalMeasure
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalKernel
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathKernel
#check continuous_compact_oriented_singleLinkHeatBathKernel_idempotent
#check continuous_compact_oriented_singleLinkHeatBathTransitionLIntegral_symm
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathJointMeasure
#check continuous_compact_oriented_map_swap_singleLinkHeatBathJointMeasure
#check continuous_compact_oriented_singleLinkHeatBathKernel_stationary
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathProjectionL2
#check continuous_compact_oriented_singleLinkHeatBathProjectionL2_inner_symm
#check continuous_compact_oriented_singleLinkHeatBathProjectionL2_idempotent
#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkHeatBathFluctuationL2
#check continuous_compact_oriented_singleLinkHeatBathFluctuationL2_quadraticForm
#check ContinuousCompactOrientedGaugeWilsonSystem.heatBathHamiltonianL2
#check continuous_compact_oriented_heatBathHamiltonianL2_quadraticForm
#check ContinuousCompactOrientedGaugeWilsonSystem.gibbsVacuumL2
#check continuous_compact_oriented_heatBathHamiltonianL2_vacuum
#check continuous_compact_oriented_singleLinkHeatBathProjection_ae_eq_condExpL2
#check continuous_compact_oriented_singleLinkHeatBathProjectionL2_toLp_eq
#check continuous_compact_oriented_singleLinkHeatBathFluctuationL2_toLp_eq
#check continuous_compact_oriented_heatBathHamiltonianL2_boundedObservable_quadraticForm
#check ContinuousCompactOrientedGaugeWilsonSystem.HeatBathPoincareL2
#check continuous_compact_oriented_heatBathHamiltonianL2_gap_on_vacuumOrthogonal
#check continuous_compact_oriented_heatBathHamiltonianL2_kernel_eq_vacuum_on_orthogonal
#check continuous_compact_oriented_heatBathHamiltonianL2_eq_inner_smul_vacuum_of_eq_zero
#check continuous_compact_oriented_heatBathHamiltonianL2_eq_zero_iff_eq_inner_smul_vacuum

end MathlibAnalytic
end MGAP4D
