import MGAP4D.MathlibAnalytic.CompactPositiveSpectralSupportLogGeneratorResolventAllOrderShapeHierarchy
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory Set Module End Filter
open scoped InnerProductSpace LinearPMap Topology BigOperators

noncomputable section

set_option maxHeartbeats 3000000
set_option synthInstance.maxHeartbeats 200000

universe u

/-- Two-step moment shift for a self-adjoint bounded real-Hilbert operator:
`⟨A^(n+2)u,u⟩ = ⟨A^n(Au),Au⟩`.  This is the parity-free recursion behind
the resolvent moment hierarchy. -/
theorem realContinuousLinearMap_pow_inner_shift_two
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →L[ℝ] E) (hself : IsSelfAdjoint A) (n : ℕ) (u : E) :
    inner ℝ ((A ^ (n + 2)) u) u = inner ℝ ((A ^ n) (A u)) (A u) := by
  have hsymm : A.toLinearMap.IsSymmetric :=
    (ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric).mp hself
  have hpow : A ^ (n + 2) = A * (A ^ n) * A := by
    calc
      A ^ (n + 2) = A ^ (n + 1) * A := by
        simpa [Nat.add_assoc] using pow_succ A (n + 1)
      _ = (A * A ^ n) * A := by
        rw [show n + 1 = 1 + n by omega, pow_add, pow_one]
  rw [hpow]
  change inner ℝ (A ((A ^ n) (A u))) u = inner ℝ ((A ^ n) (A u)) (A u)
  exact hsymm ((A ^ n) (A u)) u

/-- Cauchy--Schwarz for the positive bilinear form generated by a strictly
positive self-adjoint bounded operator.  Positivity of the first diagonal
entry removes all degeneracy from the usual quadratic-discriminant proof. -/
theorem realContinuousLinearMap_weighted_inner_sq_le
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →L[ℝ] E) (hself : IsSelfAdjoint A)
    (hpos : ∀ z : E, z ≠ 0 → 0 < inner ℝ (A z) z)
    (x : E) (hx : x ≠ 0) (y : E) :
    (inner ℝ (A x) y) ^ 2 ≤ inner ℝ (A x) x * inner ℝ (A y) y := by
  have hsymm : A.toLinearMap.IsSymmetric :=
    (ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric).mp hself
  let a := inner ℝ (A x) x
  let d := inner ℝ (A x) y
  have ha : 0 < a := by simpa [a] using hpos x hx
  have hsymm_yx : inner ℝ (A y) x = d := by
    calc
      inner ℝ (A y) x = inner ℝ y (A x) := hsymm y x
      _ = inner ℝ (A x) y := real_inner_comm _ _
      _ = d := rfl
  let z := a • y - d • x
  have hz : 0 ≤ inner ℝ (A z) z := by
    by_cases hzero : z = 0
    · simp [hzero]
    · exact (hpos z hzero).le
  dsimp [z] at hz
  simp only [map_sub, map_smul, inner_sub_left, inner_sub_right,
    real_inner_smul_left, real_inner_smul_right] at hz
  rw [hsymm_yx] at hz
  change d ^ 2 ≤ a * inner ℝ (A y) y
  dsimp [a, d] at hz ⊢
  nlinarith

/-- The positive self-adjoint moment sequence `m_n = ⟨A^n u,u⟩` is
log-convex.  The proof has only two base cases: ordinary Cauchy--Schwarz for
`n = 0`, weighted Cauchy--Schwarz for `n = 1`, and the self-adjoint two-step
shift reduces every higher index to one of those parity classes. -/
theorem realContinuousLinearMap_pow_inner_logConvex
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →L[ℝ] E) (hself : IsSelfAdjoint A) (hinj : Function.Injective A)
    (hpos : ∀ z : E, z ≠ 0 → 0 < inner ℝ (A z) z)
    (n : ℕ) (u : E) (hu : u ≠ 0) :
    (inner ℝ ((A ^ (n + 1)) u) u) ^ 2 ≤
      inner ℝ ((A ^ n) u) u * inner ℝ ((A ^ (n + 2)) u) u := by
  induction n using Nat.strong_induction_on generalizing u with
  | h n ih =>
      rcases n with _ | n
      · have hcs := abs_real_inner_le_norm (A u) u
        have hsq :
            (inner ℝ (A u) u) ^ 2 ≤ (‖A u‖ * ‖u‖) ^ 2 := by
          apply (sq_le_sq).2
          simpa [abs_of_nonneg (mul_nonneg (norm_nonneg _) (norm_nonneg _))] using hcs
        have hshift := realContinuousLinearMap_pow_inner_shift_two A hself 0 u
        simp at hshift
        simp [hshift, real_inner_self_eq_norm_sq, mul_pow] at hsq ⊢
        nlinarith
      · rcases n with _ | k
        · have hw :=
            realContinuousLinearMap_weighted_inner_sq_le A hself hpos u hu (A u)
          have hshift0 := realContinuousLinearMap_pow_inner_shift_two A hself 0 u
          have hshift1 := realContinuousLinearMap_pow_inner_shift_two A hself 1 u
          simp at hshift0 hshift1
          simpa [hshift0, hshift1] using hw
        · have hAu : A u ≠ 0 := by
            intro hzero
            apply hu
            apply hinj
            simpa using hzero
          have hind := ih k (by omega) (A u) hAu
          have hs0 := realContinuousLinearMap_pow_inner_shift_two A hself k u
          have hs1 := realContinuousLinearMap_pow_inner_shift_two A hself (k + 1) u
          have hs2 := realContinuousLinearMap_pow_inner_shift_two A hself (k + 2) u
          rw [show k + 2 + 1 = (k + 1) + 2 by omega, hs1,
            show k + 2 + 2 = (k + 2) + 2 by omega, hs2, hs0]
          exact hind

/-- Log-convexity of the coercively generated ambient resolvent moments on the
full symmetric gap. -/
theorem realLinearPMapAmbientResolventFamily_pow_inner_logConvex
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →ₗ.[ℝ] E) (c : ℝ) (hc : 0 < c)
    (hNorm : ∀ x : A.domain, c * ‖(x : E)‖ ≤ ‖A x‖)
    (hKer : ∀ x : A.domain, A x = 0 → x = 0) (hSurj : Function.Surjective A.toFun)
    (hSelf : IsSelfAdjoint A)
    (hQuad : ∀ x : A.domain, c * ‖(x : E)‖ ^ 2 ≤ inner ℝ (A x) (x : E))
    (lambda : ℝ) (hlambda : |lambda| < c) (n : ℕ) (u : E) (hu : u ≠ 0) :
    let F := realLinearPMapAmbientResolventFamily_of_norm_lower_bound A c hc hNorm hKer hSurj lambda
    (inner ℝ ((F ^ (n + 1)) u) u) ^ 2 ≤
      inner ℝ ((F ^ n) u) u * inner ℝ ((F ^ (n + 2)) u) u := by
  dsimp only
  exact
    realContinuousLinearMap_pow_inner_logConvex
      (realLinearPMapAmbientResolventFamily_of_norm_lower_bound
        A c hc hNorm hKer hSurj lambda)
      (realLinearPMapAmbientResolventFamily_isSelfAdjoint_of_isSelfAdjoint
        A c hc hNorm hKer hSurj hSelf lambda hlambda)
      (realLinearPMapAmbientResolventFamily_injective
        A c hc hNorm hKer hSurj lambda hlambda)
      (fun y hy =>
        realLinearPMapAmbientResolventFamily_inner_pos_of_quadratic_lower_bound
          A c hc hNorm hKer hSurj hQuad lambda hlambda y hy)
      n u hu

/-- Factorial-normalized Turán inequality for every derivative order of a
nonzero support-resolvent quadratic amplitude:
`(n+2) (q^(n+1))^2 ≤ (n+1) q^n q^(n+2)` throughout the full coercive gap. -/
theorem realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_turan
    {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (A : E →ₗ.[ℝ] E) (c : ℝ) (hc : 0 < c)
    (hNorm : ∀ x : A.domain, c * ‖(x : E)‖ ≤ ‖A x‖)
    (hKer : ∀ x : A.domain, A x = 0 → x = 0) (hSurj : Function.Surjective A.toFun)
    (hSelf : IsSelfAdjoint A)
    (hQuad : ∀ x : A.domain, c * ‖(x : E)‖ ^ 2 ≤ inner ℝ (A x) (x : E))
    (u : E) (hu : u ≠ 0) (n : ℕ) (lambda : ℝ) (hlambda : |lambda| < c) :
    (n + 2 : ℝ) *
        (iteratedDeriv (n + 1)
          (realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u) lambda) ^ 2 ≤
      (n + 1 : ℝ) *
        iteratedDeriv n
          (realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u) lambda *
        iteratedDeriv (n + 2)
          (realLinearPMapAmbientResolventQuadraticAmplitude A c hc hNorm hKer hSurj u) lambda := by
  let F := realLinearPMapAmbientResolventFamily_of_norm_lower_bound
    A c hc hNorm hKer hSurj lambda
  have hm :=
    realLinearPMapAmbientResolventFamily_pow_inner_logConvex
      A c hc hNorm hKer hSurj hSelf hQuad lambda hlambda (n + 1) u hu
  dsimp only at hm
  rw [realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_eq_factorial
      A c hc hNorm hKer hSurj u n lambda hlambda,
    realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_eq_factorial
      A c hc hNorm hKer hSurj u (n + 1) lambda hlambda,
    realLinearPMapAmbientResolventQuadraticAmplitude_iteratedDeriv_eq_factorial
      A c hc hNorm hKer hSurj u (n + 2) lambda hlambda]
  change
    (n + 2 : ℝ) *
        (((n + 1).factorial : ℝ) * inner ℝ ((F ^ (n + 2)) u) u) ^ 2 ≤
      (n + 1 : ℝ) *
        ((n.factorial : ℝ) * inner ℝ ((F ^ (n + 1)) u) u) *
        (((n + 2).factorial : ℝ) * inner ℝ ((F ^ (n + 3)) u) u)
  have hcoef : 0 ≤ (n + 2 : ℝ) * (((n + 1).factorial : ℝ) ^ 2) := by positivity
  have hmul := mul_le_mul_of_nonneg_left hm hcoef
  norm_num [Nat.factorial_succ] at hmul ⊢
  ring_nf at hmul ⊢
  exact hmul

end

end MathlibAnalytic
end MGAP4D
