import MGAP4D.MathlibAnalytic.ConcreteAnalyticSpineL2R2DenseDiagonalDomainLinearPMapSelfAdjoint
import MGAP4D.MathlibAnalytic.ConcreteAnalyticSpineL2R2AdjointGraphCandidateStructure

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators ENNReal lp

noncomputable section

/-- Explicit point-spectrum candidate generated by the diagonal weights `n + 1`. -/
def concreteL2R2DiagonalPointSpectrum : Set ℝ :=
  Set.range concreteL2R2DiagonalWeight

/-- The lowest diagonal weight is exactly one. -/
theorem concrete_l2_r2_diagonal_weight_zero_eq_one :
    concreteL2R2DiagonalWeight 0 = 1 := by
  norm_num [concreteL2R2DiagonalWeight]

/-- Every diagonal weight is bounded below by one. -/
theorem concrete_l2_r2_diagonal_weight_ge_one (n : ℕ) :
    1 ≤ concreteL2R2DiagonalWeight n := by
  have hn : (0 : ℝ) ≤ (n : ℝ) := by
    positivity
  simpa [concreteL2R2DiagonalWeight] using add_le_add_right hn 1

/-- One belongs to the explicit diagonal point-spectrum candidate. -/
theorem concrete_l2_r2_one_mem_diagonal_point_spectrum :
    (1 : ℝ) ∈ concreteL2R2DiagonalPointSpectrum := by
  refine ⟨0, ?_⟩
  exact concrete_l2_r2_diagonal_weight_zero_eq_one

/-- Every explicit diagonal point-spectrum value is at least one. -/
theorem concrete_l2_r2_diagonal_point_spectrum_lower_bound
    {lam : ℝ}
    (hlam : lam ∈ concreteL2R2DiagonalPointSpectrum) :
    1 ≤ lam := by
  rcases hlam with ⟨n, rfl⟩
  exact concrete_l2_r2_diagonal_weight_ge_one n

/-- One is the least element of the explicit diagonal point-spectrum candidate. -/
theorem concrete_l2_r2_diagonal_point_spectrum_isLeast_one :
    IsLeast concreteL2R2DiagonalPointSpectrum (1 : ℝ) := by
  exact ⟨
    concrete_l2_r2_one_mem_diagonal_point_spectrum,
    fun _ hlam => concrete_l2_r2_diagonal_point_spectrum_lower_bound hlam⟩

/-- The explicit diagonal point-spectrum candidate contains no zero energy. -/
theorem concrete_l2_r2_zero_not_mem_diagonal_point_spectrum :
    (0 : ℝ) ∉ concreteL2R2DiagonalPointSpectrum := by
  intro hzero
  have hLower : (1 : ℝ) ≤ 0 :=
    concrete_l2_r2_diagonal_point_spectrum_lower_bound hzero
  norm_num at hLower

/-- Every coordinate unit is a normalized eigenvector of the completed diagonal
graph-defined operator with eigenvalue `n + 1`. -/
theorem concrete_l2_r2_coordinate_unit_normalized_eigenpair (n : ℕ) :
    (concreteL2MathlibUnit n,
        concreteL2R2DiagonalWeight n • concreteL2MathlibUnit n) ∈
      concreteL2R2CompletedDiagonalGraphDefinedOperator.graphCarrier ∧
    ‖concreteL2MathlibUnit n‖ = 1 := by
  exact ⟨
    concrete_l2_r2_completed_diagonal_unit_graph_mem n,
    concrete_l2_mathlib_unit_norm_eq_one n⟩

/-- Every explicit diagonal eigenvalue is strictly positive. -/
theorem concrete_l2_r2_diagonal_point_spectrum_positive
    {lam : ℝ}
    (hlam : lam ∈ concreteL2R2DiagonalPointSpectrum) :
    0 < lam := by
  exact lt_of_lt_of_le zero_lt_one
    (concrete_l2_r2_diagonal_point_spectrum_lower_bound hlam)

/-- The actual Mathlib self-adjoint diagonal `LinearPMap` is accompanied by an
explicit normalized eigenpair family whose eigenvalue set has least element one. -/
theorem concrete_l2_r2_self_adjoint_diagonal_has_point_spectrum_lower_edge_one :
    IsSelfAdjoint concreteL2R2DenseDiagonalDomainLinearPMap ∧
    IsLeast concreteL2R2DiagonalPointSpectrum (1 : ℝ) ∧
    (∀ n : ℕ,
      (concreteL2MathlibUnit n,
          concreteL2R2DiagonalWeight n • concreteL2MathlibUnit n) ∈
        concreteL2R2CompletedDiagonalGraphDefinedOperator.graphCarrier ∧
      ‖concreteL2MathlibUnit n‖ = 1) := by
  exact ⟨
    concrete_l2_r2_dense_diagonal_domain_linear_pmap_isSelfAdjoint,
    concrete_l2_r2_diagonal_point_spectrum_isLeast_one,
    concrete_l2_r2_coordinate_unit_normalized_eigenpair⟩

end

end MathlibAnalytic
end MGAP4D
