import MGAP4D.MathlibAnalytic.ConcreteAnalyticSpineL2R2FiniteCoordinateCombinationsInDomain

namespace MGAP4D
namespace MathlibAnalytic

open scoped ENNReal lp

noncomputable section

/-- The coordinate-unit set inside the Mathlib completed real `ℓ²` carrier. -/
def concreteL2R2CoordinateUnitSet : Set ConcreteL2R1HilbertCarrier :=
  Set.range fun k : ℕ => (concreteL2MathlibUnit k : ConcreteL2R1HilbertCarrier)

/-- The algebraic submodule generated by the coordinate units.  This is a
Mathlib-native normalization of the finite-coordinate-combination lane: it uses
`Submodule.span` rather than an ad hoc notion of finite support. -/
def concreteL2R2FiniteCoordinateSubmodule : Submodule ℝ ConcreteL2R1HilbertCarrier :=
  Submodule.span ℝ concreteL2R2CoordinateUnitSet

/-- Each coordinate unit belongs to the coordinate-unit span. -/
theorem concrete_l2_r2_mathlib_unit_mem_finite_coordinate_submodule (k : ℕ) :
    (concreteL2MathlibUnit k : ConcreteL2R1HilbertCarrier) ∈
      concreteL2R2FiniteCoordinateSubmodule := by
  unfold concreteL2R2FiniteCoordinateSubmodule concreteL2R2CoordinateUnitSet
  exact Submodule.subset_span ⟨k, rfl⟩

/-- Every explicitly written finite coordinate combination belongs to the
Mathlib `Submodule.span` of the coordinate units. -/
theorem concrete_l2_r2_finite_coordinate_combination_mem_submodule
    (s : Finset ℕ) (a : ℕ → ℝ) :
    concreteL2R2FiniteCoordinateCombination s a ∈
      concreteL2R2FiniteCoordinateSubmodule := by
  classical
  unfold concreteL2R2FiniteCoordinateCombination
  exact concreteL2R2FiniteCoordinateSubmodule.sum_mem fun k _hk =>
    concreteL2R2FiniteCoordinateSubmodule.smul_mem (a k)
      (concrete_l2_r2_mathlib_unit_mem_finite_coordinate_submodule k)

/-- Finite coordinate combinations lie both in the Mathlib coordinate span and
in the R2 diagonal-domain candidate.  This is still a finite algebraic-core
statement only; it is not a density theorem and not a graph-core theorem. -/
def concreteL2R2FiniteCoordinateSubmoduleDomainAdapter : Prop :=
  ∀ (s : Finset ℕ) (a : ℕ → ℝ),
    concreteL2R2FiniteCoordinateCombination s a ∈
      concreteL2R2FiniteCoordinateSubmodule ∧
    ConcreteL2R2DiagonalDomainCandidate
      (concreteL2R2FiniteCoordinateCombination s a)

/-- Adapter theorem for finite-coordinate combinations in the coordinate span
and in the R2 diagonal-domain candidate. -/
theorem concrete_l2_r2_finite_coordinate_submodule_domain_adapter_ready :
    concreteL2R2FiniteCoordinateSubmoduleDomainAdapter := by
  intro s a
  exact And.intro
    (concrete_l2_r2_finite_coordinate_combination_mem_submodule s a)
    (concrete_l2_r2_diagonal_domain_candidate_finite_coordinate_combination s a)

/-- R2 finite-coordinate-submodule surface.  This is the first Mathlib-native
algebraic-span bridge for the R2 diagonal lane. -/
structure ConcreteL2R2FiniteCoordinateSubmoduleSurface where
  finiteCoordinateCombinationsReady :
    concreteAnalyticSpineL2R2FiniteCoordinateCombinationsInDomainSurfaceReady
  coordinateUnitSet : Set ConcreteL2R1HilbertCarrier
  coordinateSubmodule : Submodule ℝ ConcreteL2R1HilbertCarrier
  finiteCombinationSubmoduleAndDomainLaw :
    concreteL2R2FiniteCoordinateSubmoduleDomainAdapter
  boundaryNotDenseDomainTheorem : Prop
  boundaryNotGraphNormCoreTheorem : Prop
  boundaryNotClosedOperatorTheorem : Prop
  boundaryNotSelfAdjointness : Prop
  boundaryNotSpectralTheoremApplication : Prop
  boundaryNotPVMConstruction : Prop

/-- Concrete R2 finite-coordinate-submodule surface. -/
def concreteL2R2FiniteCoordinateSubmoduleSurface :
    ConcreteL2R2FiniteCoordinateSubmoduleSurface :=
  { finiteCoordinateCombinationsReady :=
      concrete_analytic_spine_l2_r2_finite_coordinate_combinations_in_domain_surface_ready
    coordinateUnitSet := concreteL2R2CoordinateUnitSet
    coordinateSubmodule := concreteL2R2FiniteCoordinateSubmodule
    finiteCombinationSubmoduleAndDomainLaw :=
      concrete_l2_r2_finite_coordinate_submodule_domain_adapter_ready
    boundaryNotDenseDomainTheorem := True
    boundaryNotGraphNormCoreTheorem := True
    boundaryNotClosedOperatorTheorem := True
    boundaryNotSelfAdjointness := True
    boundaryNotSpectralTheoremApplication := True
    boundaryNotPVMConstruction := True }

/-- R2 finite-coordinate-submodule readiness. -/
def concreteAnalyticSpineL2R2FiniteCoordinateSubmoduleSurfaceReady : Prop :=
  concreteAnalyticSpineL2R2FiniteCoordinateCombinationsInDomainSurfaceReady ∧
  concreteL2R2FiniteCoordinateSubmoduleDomainAdapter ∧
  concreteL2R2FiniteCoordinateSubmoduleSurface.boundaryNotDenseDomainTheorem ∧
  concreteL2R2FiniteCoordinateSubmoduleSurface.boundaryNotGraphNormCoreTheorem ∧
  concreteL2R2FiniteCoordinateSubmoduleSurface.boundaryNotClosedOperatorTheorem ∧
  concreteL2R2FiniteCoordinateSubmoduleSurface.boundaryNotSelfAdjointness ∧
  concreteL2R2FiniteCoordinateSubmoduleSurface.boundaryNotSpectralTheoremApplication ∧
  concreteL2R2FiniteCoordinateSubmoduleSurface.boundaryNotPVMConstruction

/-- Readiness theorem for the R2 finite-coordinate-submodule surface. -/
theorem concrete_analytic_spine_l2_r2_finite_coordinate_submodule_surface_ready :
    concreteAnalyticSpineL2R2FiniteCoordinateSubmoduleSurfaceReady := by
  unfold concreteAnalyticSpineL2R2FiniteCoordinateSubmoduleSurfaceReady
  exact And.intro
    concrete_analytic_spine_l2_r2_finite_coordinate_combinations_in_domain_surface_ready <|
      And.intro
        concrete_l2_r2_finite_coordinate_submodule_domain_adapter_ready <|
        And.intro trivial <| And.intro trivial <| And.intro trivial <|
          And.intro trivial <| And.intro trivial trivial

/-- Boundary marker for the R2 finite-coordinate-submodule surface. -/
def concreteAnalyticSpineL2R2FiniteCoordinateSubmoduleHardResidualBoundaryHeld : Prop :=
  concreteAnalyticSpineL2R2FiniteCoordinateSubmoduleSurfaceReady

/-- Boundary theorem for the R2 finite-coordinate-submodule surface. -/
theorem concrete_analytic_spine_l2_r2_finite_coordinate_submodule_hard_residual_boundary_held :
    concreteAnalyticSpineL2R2FiniteCoordinateSubmoduleHardResidualBoundaryHeld := by
  exact concrete_analytic_spine_l2_r2_finite_coordinate_submodule_surface_ready

end

end MathlibAnalytic
end MGAP4D
