import MGAP4D.MathlibAnalytic.ConcreteAnalyticSpineL2MathlibFinTwoUnitRangeCoordinateUltimateFacade

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators ENNReal lp

noncomputable section

/-- The three-element coordinate-unit family generated by three selected indices. -/
def concreteL2MathlibFinThreeUnitFamily (a b c : ℕ) :
    Fin 3 → lp (fun _ : ℕ => ℝ) 2
  | 0 => concreteL2MathlibUnit a
  | 1 => concreteL2MathlibUnit b
  | 2 => concreteL2MathlibUnit c

/-- The first element of the three-element coordinate-unit family. -/
theorem concrete_l2_mathlib_fin_three_unit_family_zero (a b c : ℕ) :
    concreteL2MathlibFinThreeUnitFamily a b c 0 = concreteL2MathlibUnit a := by
  rfl

/-- The second element of the three-element coordinate-unit family. -/
theorem concrete_l2_mathlib_fin_three_unit_family_one (a b c : ℕ) :
    concreteL2MathlibFinThreeUnitFamily a b c 1 = concreteL2MathlibUnit b := by
  rfl

/-- The third element of the three-element coordinate-unit family. -/
theorem concrete_l2_mathlib_fin_three_unit_family_two (a b c : ℕ) :
    concreteL2MathlibFinThreeUnitFamily a b c 2 = concreteL2MathlibUnit c := by
  rfl

/-- Pairwise distinct selected indices give pairwise distinct entries in the
three-element coordinate-unit family. -/
theorem concrete_l2_mathlib_fin_three_unit_family_pairwise_distinct_entries
    {a b c : ℕ} (hab : a ≠ b) (hac : a ≠ c) (hbc : b ≠ c) :
    concreteL2MathlibFinThreeUnitFamily a b c 0 ≠
        concreteL2MathlibFinThreeUnitFamily a b c 1 ∧
      concreteL2MathlibFinThreeUnitFamily a b c 0 ≠
        concreteL2MathlibFinThreeUnitFamily a b c 2 ∧
      concreteL2MathlibFinThreeUnitFamily a b c 1 ≠
        concreteL2MathlibFinThreeUnitFamily a b c 2 := by
  exact ⟨
    by simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_of_ne hab,
    by simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_of_ne hac,
    by simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_of_ne hbc⟩

/-- The three-element coordinate-unit family is injective when the selected
indices are pairwise distinct. -/
theorem concrete_l2_mathlib_fin_three_unit_family_injective
    {a b c : ℕ} (hab : a ≠ b) (hac : a ≠ c) (hbc : b ≠ c) :
    Function.Injective (concreteL2MathlibFinThreeUnitFamily a b c) := by
  intro i j hij
  fin_cases i <;> fin_cases j
  · rfl
  · exfalso
    exact (by simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_of_ne hab) hij
  · exfalso
    exact (by simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_of_ne hac) hij
  · exfalso
    exact (by simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_of_ne hab.symm) hij
  · rfl
  · exfalso
    exact (by simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_of_ne hbc) hij
  · exfalso
    exact (by simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_of_ne hac.symm) hij
  · exfalso
    exact (by simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_of_ne hbc.symm) hij
  · rfl

/-- Each entry of the three-element coordinate-unit family is nonzero. -/
theorem concrete_l2_mathlib_fin_three_unit_family_ne_zero
    (a b c : ℕ) (i : Fin 3) :
    concreteL2MathlibFinThreeUnitFamily a b c i ≠ 0 := by
  fin_cases i
  · simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_zero a
  · simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_zero b
  · simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_ne_zero c

/-- Each entry of the three-element coordinate-unit family has norm one. -/
theorem concrete_l2_mathlib_fin_three_unit_family_norm_eq_one
    (a b c : ℕ) (i : Fin 3) :
    ‖concreteL2MathlibFinThreeUnitFamily a b c i‖ = 1 := by
  fin_cases i
  · simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_norm_eq_one a
  · simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_norm_eq_one b
  · simpa [concreteL2MathlibFinThreeUnitFamily] using
      concrete_l2_mathlib_unit_norm_eq_one c

/-- Adapter predicate for the three-element coordinate-unit family layer. -/
def concreteL2MathlibFinThreeUnitFamilyAdapter : Prop :=
  ∀ {a b c : ℕ}, a ≠ b → a ≠ c → b ≠ c →
    Function.Injective (concreteL2MathlibFinThreeUnitFamily a b c) ∧
    (∀ i : Fin 3, concreteL2MathlibFinThreeUnitFamily a b c i ≠ 0) ∧
    (∀ i : Fin 3, ‖concreteL2MathlibFinThreeUnitFamily a b c i‖ = 1)

/-- Three-element coordinate-unit family adapter theorem. -/
theorem concrete_l2_mathlib_fin_three_unit_family_adapter_ready :
    concreteL2MathlibFinThreeUnitFamilyAdapter := by
  intro a b c hab hac hbc
  exact ⟨
    concrete_l2_mathlib_fin_three_unit_family_injective hab hac hbc,
    concrete_l2_mathlib_fin_three_unit_family_ne_zero a b c,
    concrete_l2_mathlib_fin_three_unit_family_norm_eq_one a b c⟩

/-- Surface for the `Fin 3` coordinate-unit family in Mathlib completed
`ℓ²(ℕ, ℝ)`.

This is the first post-`Fin 2` carrier leaf: it packages three selected coordinate
units as a `Fin 3` family and proves injectivity, nonzero entries, and norm-one
entries under pairwise distinct index assumptions.  It deliberately does not yet
claim three-unit linear independence, general finite-family linear independence,
a basis theorem, dense span, finite-support-domain equivalence, or any operator
or spectral theorem. -/
structure ConcreteL2MathlibFinThreeUnitFamilySurface where
  twoUnitUltimateFacadeReady :
    ∀ {k n : ℕ}, k ≠ n →
      concreteL2MathlibFinTwoUnitRangeCoordinateUltimateSurfaceReady k n
  finThreeFamilyAdapter : concreteL2MathlibFinThreeUnitFamilyAdapter
  boundaryNotThreeUnitLinearIndependence : Prop
  boundaryNotGeneralFiniteFamilyLinearIndependence : Prop
  boundaryNotBasisTheorem : Prop
  boundaryNotDenseSpanTheorem : Prop
  boundaryNotFiniteSupportDomainEquivalence : Prop
  boundaryNotUnboundedOperatorDomainTheorem : Prop
  boundaryNotSelfAdjointness : Prop
  boundaryNotPVMConstruction : Prop
  boundaryNotSpectralAtomTheorem : Prop

/-- Concrete `Fin 3` coordinate-unit family surface. -/
def concreteL2MathlibFinThreeUnitFamilySurface :
    ConcreteL2MathlibFinThreeUnitFamilySurface :=
  { twoUnitUltimateFacadeReady := by
      intro k n hkn
      exact concrete_l2_mathlib_fin_two_unit_range_coordinate_ultimate_surface_ready hkn
    finThreeFamilyAdapter := concrete_l2_mathlib_fin_three_unit_family_adapter_ready
    boundaryNotThreeUnitLinearIndependence := True
    boundaryNotGeneralFiniteFamilyLinearIndependence := True
    boundaryNotBasisTheorem := True
    boundaryNotDenseSpanTheorem := True
    boundaryNotFiniteSupportDomainEquivalence := True
    boundaryNotUnboundedOperatorDomainTheorem := True
    boundaryNotSelfAdjointness := True
    boundaryNotPVMConstruction := True
    boundaryNotSpectralAtomTheorem := True }

/-- Readiness for the `Fin 3` coordinate-unit family surface. -/
def concreteAnalyticSpineL2MathlibFinThreeUnitFamilySurfaceReady : Prop :=
  concreteL2MathlibFinThreeUnitFamilyAdapter ∧
  concreteL2MathlibFinThreeUnitFamilySurface.boundaryNotThreeUnitLinearIndependence ∧
  concreteL2MathlibFinThreeUnitFamilySurface.boundaryNotGeneralFiniteFamilyLinearIndependence ∧
  concreteL2MathlibFinThreeUnitFamilySurface.boundaryNotBasisTheorem ∧
  concreteL2MathlibFinThreeUnitFamilySurface.boundaryNotDenseSpanTheorem ∧
  concreteL2MathlibFinThreeUnitFamilySurface.boundaryNotFiniteSupportDomainEquivalence ∧
  concreteL2MathlibFinThreeUnitFamilySurface.boundaryNotUnboundedOperatorDomainTheorem ∧
  concreteL2MathlibFinThreeUnitFamilySurface.boundaryNotSelfAdjointness ∧
  concreteL2MathlibFinThreeUnitFamilySurface.boundaryNotPVMConstruction ∧
  concreteL2MathlibFinThreeUnitFamilySurface.boundaryNotSpectralAtomTheorem

/-- Readiness theorem for the `Fin 3` coordinate-unit family surface. -/
theorem concrete_analytic_spine_l2_mathlib_fin_three_unit_family_surface_ready :
    concreteAnalyticSpineL2MathlibFinThreeUnitFamilySurfaceReady := by
  unfold concreteAnalyticSpineL2MathlibFinThreeUnitFamilySurfaceReady
  exact And.intro
    concrete_l2_mathlib_fin_three_unit_family_adapter_ready <|
      And.intro trivial <| And.intro trivial <| And.intro trivial <|
        And.intro trivial <| And.intro trivial <| And.intro trivial <|
          And.intro trivial <| And.intro trivial trivial

/-- Boundary marker for the `Fin 3` coordinate-unit family surface. -/
def concreteAnalyticSpineL2MathlibFinThreeUnitFamilyHardResidualBoundaryHeld : Prop :=
  concreteAnalyticSpineL2MathlibFinThreeUnitFamilySurfaceReady

/-- Boundary theorem for the `Fin 3` coordinate-unit family surface. -/
theorem concrete_analytic_spine_l2_mathlib_fin_three_unit_family_hard_residual_boundary_held :
    concreteAnalyticSpineL2MathlibFinThreeUnitFamilyHardResidualBoundaryHeld := by
  exact concrete_analytic_spine_l2_mathlib_fin_three_unit_family_surface_ready

end

end MathlibAnalytic
end MGAP4D
