import MGAP4D.MathlibAnalytic.ConcreteAnalyticSpineL2MathlibFinTwoUnitSynthesisLinearMap

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators ENNReal lp

noncomputable section

/-- The range of the two-unit synthesis linear map. -/
def concreteL2MathlibFinTwoUnitSynthesisRange (k n : ℕ) :
    Submodule ℝ (lp (fun _ : ℕ => ℝ) 2) :=
  LinearMap.range (concreteL2MathlibFinTwoUnitSynthesisLinearMap k n)

/-- Every synthesized vector lies in the range of the synthesis linear map. -/
theorem concrete_l2_mathlib_fin_two_unit_synthesis_mem_range
    (k n : ℕ) (c : Fin 2 → ℝ) :
    concreteL2MathlibFinTwoUnitSynthesisLinearMap k n c ∈
      concreteL2MathlibFinTwoUnitSynthesisRange k n := by
  exact ⟨c, rfl⟩

/-- Membership in the synthesis range is exactly existence of a `Fin 2`
coefficient function whose synthesis gives the vector. -/
theorem concrete_l2_mathlib_fin_two_unit_mem_range_iff
    (k n : ℕ) (v : lp (fun _ : ℕ => ℝ) 2) :
    v ∈ concreteL2MathlibFinTwoUnitSynthesisRange k n ↔
      ∃ c : Fin 2 → ℝ,
        concreteL2MathlibFinTwoUnitSynthesisLinearMap k n c = v := by
  rfl

/-- The first coordinate unit is in the synthesis range. -/
theorem concrete_l2_mathlib_fin_two_unit_first_mem_range
    (k n : ℕ) :
    concreteL2MathlibUnit k ∈ concreteL2MathlibFinTwoUnitSynthesisRange k n := by
  refine ⟨fun i : Fin 2 => if i = 0 then (1 : ℝ) else 0, ?_⟩
  rw [concrete_l2_mathlib_fin_two_unit_synthesis_linear_map_apply_eq_sum]
  rw [Fin.sum_univ_two]
  simp [concreteL2MathlibFinTwoUnitFamily]

/-- The second coordinate unit is in the synthesis range. -/
theorem concrete_l2_mathlib_fin_two_unit_second_mem_range
    (k n : ℕ) :
    concreteL2MathlibUnit n ∈ concreteL2MathlibFinTwoUnitSynthesisRange k n := by
  refine ⟨fun i : Fin 2 => if i = 1 then (1 : ℝ) else 0, ?_⟩
  rw [concrete_l2_mathlib_fin_two_unit_synthesis_linear_map_apply_eq_sum]
  rw [Fin.sum_univ_two]
  simp [concreteL2MathlibFinTwoUnitFamily]

/-- The range contains a nonzero vector: the first selected coordinate unit. -/
theorem concrete_l2_mathlib_fin_two_unit_range_nontrivial_witness
    (k n : ℕ) :
    ∃ v : lp (fun _ : ℕ => ℝ) 2,
      v ∈ concreteL2MathlibFinTwoUnitSynthesisRange k n ∧ v ≠ 0 := by
  exact ⟨
    concreteL2MathlibUnit k,
    concrete_l2_mathlib_fin_two_unit_first_mem_range k n,
    concrete_l2_mathlib_unit_ne_zero k⟩

/-- Distinct selected coordinate units give two distinct vectors in the synthesis
range. -/
theorem concrete_l2_mathlib_fin_two_unit_range_contains_distinct_units
    {k n : ℕ} (hkn : k ≠ n) :
    ∃ v w : lp (fun _ : ℕ => ℝ) 2,
      v ∈ concreteL2MathlibFinTwoUnitSynthesisRange k n ∧
      w ∈ concreteL2MathlibFinTwoUnitSynthesisRange k n ∧
      v ≠ w := by
  exact ⟨
    concreteL2MathlibUnit k,
    concreteL2MathlibUnit n,
    concrete_l2_mathlib_fin_two_unit_first_mem_range k n,
    concrete_l2_mathlib_fin_two_unit_second_mem_range k n,
    concrete_l2_mathlib_unit_ne_of_ne hkn⟩

/-- Adapter predicate for the two-unit synthesis range layer. -/
def concreteL2MathlibFinTwoUnitSynthesisRangeAdapter : Prop :=
  (∀ k n : ℕ, ∃ v : lp (fun _ : ℕ => ℝ) 2,
    v ∈ concreteL2MathlibFinTwoUnitSynthesisRange k n ∧ v ≠ 0) ∧
  (∀ {k n : ℕ}, k ≠ n → ∃ v w : lp (fun _ : ℕ => ℝ) 2,
    v ∈ concreteL2MathlibFinTwoUnitSynthesisRange k n ∧
    w ∈ concreteL2MathlibFinTwoUnitSynthesisRange k n ∧
    v ≠ w)

/-- Adapter theorem for the two-unit synthesis range layer. -/
theorem concrete_l2_mathlib_fin_two_unit_synthesis_range_adapter_ready :
    concreteL2MathlibFinTwoUnitSynthesisRangeAdapter := by
  exact ⟨
    by intro k n; exact concrete_l2_mathlib_fin_two_unit_range_nontrivial_witness k n,
    by intro k n hkn; exact concrete_l2_mathlib_fin_two_unit_range_contains_distinct_units hkn⟩

/-- Surface for the range of the `Fin 2` coordinate-unit synthesis linear map.

This layer names the two-dimensional candidate submodule generated by the two
selected coordinate units and proves the basic range witnesses needed before any
future isomorphism or finite-dimensionality layer.  It deliberately does not
claim a basis theorem, dimension theorem, dense-span theorem, or general
finite-family result. -/
structure ConcreteL2MathlibFinTwoUnitSynthesisRangeSurface where
  synthesisLinearMapReady : concreteAnalyticSpineL2MathlibFinTwoUnitSynthesisLinearMapSurfaceReady
  rangeAdapter : concreteL2MathlibFinTwoUnitSynthesisRangeAdapter
  boundaryNotRangeEquivTheorem : Prop
  boundaryNotFiniteDimensionalTheorem : Prop
  boundaryNotGeneralFiniteFamilyLinearIndependence : Prop
  boundaryNotBasisTheorem : Prop
  boundaryNotDenseSpanTheorem : Prop
  boundaryNotFiniteSupportDomainEquivalence : Prop
  boundaryNotUnboundedOperatorDomainTheorem : Prop
  boundaryNotSelfAdjointness : Prop
  boundaryNotPVMConstruction : Prop
  boundaryNotSpectralAtomTheorem : Prop

/-- Concrete range surface for the two-unit synthesis linear map. -/
def concreteL2MathlibFinTwoUnitSynthesisRangeSurface :
    ConcreteL2MathlibFinTwoUnitSynthesisRangeSurface :=
  { synthesisLinearMapReady :=
      concrete_analytic_spine_l2_mathlib_fin_two_unit_synthesis_linear_map_surface_ready
    rangeAdapter := concrete_l2_mathlib_fin_two_unit_synthesis_range_adapter_ready
    boundaryNotRangeEquivTheorem := True
    boundaryNotFiniteDimensionalTheorem := True
    boundaryNotGeneralFiniteFamilyLinearIndependence := True
    boundaryNotBasisTheorem := True
    boundaryNotDenseSpanTheorem := True
    boundaryNotFiniteSupportDomainEquivalence := True
    boundaryNotUnboundedOperatorDomainTheorem := True
    boundaryNotSelfAdjointness := True
    boundaryNotPVMConstruction := True
    boundaryNotSpectralAtomTheorem := True }

/-- Readiness for the two-unit synthesis range surface. -/
def concreteAnalyticSpineL2MathlibFinTwoUnitSynthesisRangeSurfaceReady : Prop :=
  concreteAnalyticSpineL2MathlibFinTwoUnitSynthesisLinearMapSurfaceReady ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeAdapter ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotRangeEquivTheorem ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotFiniteDimensionalTheorem ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotGeneralFiniteFamilyLinearIndependence ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotBasisTheorem ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotDenseSpanTheorem ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotFiniteSupportDomainEquivalence ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotUnboundedOperatorDomainTheorem ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotSelfAdjointness ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotPVMConstruction ∧
  concreteL2MathlibFinTwoUnitSynthesisRangeSurface.boundaryNotSpectralAtomTheorem

/-- Readiness theorem for the two-unit synthesis range surface. -/
theorem concrete_analytic_spine_l2_mathlib_fin_two_unit_synthesis_range_surface_ready :
    concreteAnalyticSpineL2MathlibFinTwoUnitSynthesisRangeSurfaceReady := by
  unfold concreteAnalyticSpineL2MathlibFinTwoUnitSynthesisRangeSurfaceReady
  exact And.intro
    concrete_analytic_spine_l2_mathlib_fin_two_unit_synthesis_linear_map_surface_ready <|
      And.intro concrete_l2_mathlib_fin_two_unit_synthesis_range_adapter_ready <|
        And.intro trivial <| And.intro trivial <| And.intro trivial <|
          And.intro trivial <| And.intro trivial <| And.intro trivial <|
            And.intro trivial <| And.intro trivial <| And.intro trivial trivial

/-- Boundary marker for the two-unit synthesis range surface. -/
def concreteAnalyticSpineL2MathlibFinTwoUnitSynthesisRangeHardResidualBoundaryHeld : Prop :=
  concreteAnalyticSpineL2MathlibFinTwoUnitSynthesisRangeSurfaceReady

/-- Boundary theorem for the two-unit synthesis range surface. -/
theorem concrete_analytic_spine_l2_mathlib_fin_two_unit_synthesis_range_hard_residual_boundary_held :
    concreteAnalyticSpineL2MathlibFinTwoUnitSynthesisRangeHardResidualBoundaryHeld := by
  exact concrete_analytic_spine_l2_mathlib_fin_two_unit_synthesis_range_surface_ready

end

end MathlibAnalytic
end MGAP4D
