import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonUniformDobrushinSpectrumL2

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- The whole open half-line below the uniform Dobrushin gap belongs to the
real resolvent set at every finite-volume family index. -/
theorem continuous_compact_oriented_uniformDobrushin_Iio_subset_resolventSet
    {ι : Type*}
    (U : ContinuousCompactOrientedGaugeWilsonUniformDobrushinFamilyData ι)
    (i : ι) :
    Set.Iio (continuousCompactOrientedUniformDobrushinGap U) ⊆
      resolventSet ℝ
        (U.system i).heatBathHamiltonianVacuumOrthogonalL2 := by
  intro lambda hlambda
  exact continuous_compact_oriented_uniformDobrushin_mem_resolventSet
    U i hlambda

/-- The vacuum-orthogonal spectrum is disjoint from the open half-line below
the uniform Dobrushin gap. -/
theorem continuous_compact_oriented_uniformDobrushin_spectrum_inter_Iio_eq_empty
    {ι : Type*}
    (U : ContinuousCompactOrientedGaugeWilsonUniformDobrushinFamilyData ι)
    (i : ι) :
    spectrum ℝ (U.system i).heatBathHamiltonianVacuumOrthogonalL2 ∩
        Set.Iio (continuousCompactOrientedUniformDobrushinGap U) = ∅ := by
  apply Set.eq_empty_iff_forall_not_mem.mpr
  intro lambda hlambda
  exact
    (continuous_compact_oriented_uniformDobrushin_not_mem_spectrum
      U i hlambda.2) hlambda.1

/-- Proof-relevant finite-volume spectral-gap certificate for an indexed
compact Wilson family.  Downstream limit arguments may consume this package
without unfolding the Dobrushin construction. -/
structure
    ContinuousCompactOrientedGaugeWilsonUniformSpectralGapCertificateL2
    {ι : Type*}
    (U : ContinuousCompactOrientedGaugeWilsonUniformDobrushinFamilyData ι) where
  gap_pos : 0 < continuousCompactOrientedUniformDobrushinGap U
  resolventBelow : ∀ (i : ι) {lambda : ℝ},
    lambda < continuousCompactOrientedUniformDobrushinGap U →
      lambda ∈ resolventSet ℝ
        (U.system i).heatBathHamiltonianVacuumOrthogonalL2
  spectrumLower : ∀ i : ι,
    spectrum ℝ (U.system i).heatBathHamiltonianVacuumOrthogonalL2 ⊆
      Set.Ici (continuousCompactOrientedUniformDobrushinGap U)
  resolventNorm : ∀ (i : ι) {lambda : ℝ}
      (hlambda : lambda < continuousCompactOrientedUniformDobrushinGap U),
    ‖U.uniformResolventL2 i hlambda‖ ≤
      (continuousCompactOrientedUniformDobrushinGap U - lambda)⁻¹

/-- Canonical uniform spectral-gap certificate generated by the compact Wilson
Dobrushin family data. -/
noncomputable def
    ContinuousCompactOrientedGaugeWilsonUniformDobrushinFamilyData.spectralGapCertificateL2
    {ι : Type*}
    (U : ContinuousCompactOrientedGaugeWilsonUniformDobrushinFamilyData ι) :
    ContinuousCompactOrientedGaugeWilsonUniformSpectralGapCertificateL2 U :=
  { gap_pos := continuous_compact_oriented_uniformDobrushinGap_pos U
    resolventBelow := fun i _ hlambda =>
      continuous_compact_oriented_uniformDobrushin_mem_resolventSet
        U i hlambda
    spectrumLower := fun i =>
      continuous_compact_oriented_uniformDobrushin_spectrum_subset_Ici U i
    resolventNorm := fun i _ hlambda =>
      continuous_compact_oriented_uniformResolventL2_norm_le
        U i hlambda }

/-- Every spectral value in every member of the family is bounded below by the
one positive scale-independent gap carried by the canonical certificate. -/
theorem continuous_compact_oriented_uniformSpectralGapCertificate_lower_bound
    {ι : Type*}
    (U : ContinuousCompactOrientedGaugeWilsonUniformDobrushinFamilyData ι)
    (i : ι)
    {lambda : ℝ}
    (hlambda : lambda ∈
      spectrum ℝ (U.system i).heatBathHamiltonianVacuumOrthogonalL2) :
    continuousCompactOrientedUniformDobrushinGap U ≤ lambda :=
  U.spectralGapCertificateL2.spectrumLower i hlambda

end

end MathlibAnalytic
end MGAP4D
