import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonHybridTargetTrajectoryGibbsEndpointEnergyBCF
import MGAP4D.MathlibAnalytic.PeriodicHypercubicSpecialUnitaryNativeConditionalPairReferenceBCF
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory ProbabilityTheory Finset Preorder Function
open scoped ProbabilityTheory BigOperators

noncomputable section

/-- Reconstruct the two full endpoint configurations from the first and last
values of the complete target trajectory for one fixed original pair. -/
def ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (z : C.base.Configuration × C.base.Configuration)
    (x : (i : Finset.Iic (Fintype.card C.base.geometry.Edge)) → C.base.Gauge) :
    C.base.Configuration × C.base.Configuration :=
  (C.base.replaceLink z.1 target
      (x ⟨0, Finset.mem_Iic.2 (Nat.zero_le _)⟩),
    C.base.replaceLink z.2 target
      (x ⟨Fintype.card C.base.geometry.Edge, Finset.mem_Iic.2 le_rfl⟩))

/-- Fixed-pair endpoint reconstruction is continuous. -/
theorem continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap_continuous
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (z : C.base.Configuration × C.base.Configuration) :
    Continuous
      (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap
        target z) := by
  have hZero : Continuous
      (fun x : (i : Finset.Iic (Fintype.card C.base.geometry.Edge)) → C.base.Gauge =>
        x ⟨0, Finset.mem_Iic.2 (Nat.zero_le _)⟩) :=
    continuous_apply _
  have hLast : Continuous
      (fun x : (i : Finset.Iic (Fintype.card C.base.geometry.Edge)) → C.base.Gauge =>
        x ⟨Fintype.card C.base.geometry.Edge, Finset.mem_Iic.2 le_rfl⟩) :=
    continuous_apply _
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap
  exact
    ((continuous_compact_oriented_replaceLink C z.1 target).comp hZero).prodMk
      ((continuous_compact_oriented_replaceLink C z.2 target).comp hLast)

/-- Endpoint configuration-pair law generated by one fixed original pair. -/
noncomputable def
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (z : C.base.Configuration × C.base.Configuration) :
    Measure (C.base.Configuration × C.base.Configuration) :=
  Measure.map
    (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap
      target z)
    (C.independentPairHybridTargetTrajectoryMeasure z.1 z.2 target
      (Fintype.card C.base.geometry.Edge))

instance continuousCompactOriented_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure_isProbability
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (z : C.base.Configuration × C.base.Configuration) :
    IsProbabilityMeasure
      (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure
        target z) := by
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure
  exact Measure.isProbabilityMeasure_map
    (continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap_continuous
      C target z).measurable.aemeasurable

/-- The first fixed-pair endpoint marginal is the exact heat-bath update law of
its left original configuration. -/
theorem continuous_compact_oriented_map_fst_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (z : C.base.Configuration × C.base.Configuration) :
    Measure.map Prod.fst
        (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure
          target z) =
      C.singleLinkHeatBathKernel target z.1 := by
  let n := Fintype.card C.base.geometry.Edge
  let evalZero : ((i : Finset.Iic n) → C.base.Gauge) → C.base.Gauge :=
    fun x => x ⟨0, Finset.mem_Iic.2 (Nat.zero_le n)⟩
  have hEvalZero : Measurable evalZero := measurable_pi_apply _
  have hReplace : Measurable
      (fun g : C.base.Gauge => C.base.replaceLink z.1 target g) :=
    (continuous_compact_oriented_replaceLink C z.1 target).measurable
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure
  rw [Measure.map_map measurable_fst
    (continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap_continuous
      C target z).measurable]
  change Measure.map
      ((fun g : C.base.Gauge => C.base.replaceLink z.1 target g) ∘ evalZero)
      (C.independentPairHybridTargetTrajectoryMeasure z.1 z.2 target n) = _
  rw [← Measure.map_map hReplace hEvalZero]
  rw [show Measure.map evalZero
        (C.independentPairHybridTargetTrajectoryMeasure z.1 z.2 target n) =
      C.singleLinkConditionalMeasure z.1 target by
        simpa [n, evalZero,
          continuous_compact_oriented_independentPairHybridConfiguration_zero]
          using
            continuous_compact_oriented_map_coordinate_independentPairHybridTargetTrajectoryMeasure
              C z.1 z.2 target 0 n (Nat.zero_le n)]
  rw [continuous_compact_oriented_singleLinkHeatBathKernel_apply]

/-- The second fixed-pair endpoint marginal is the exact heat-bath update law of
its right original configuration. -/
theorem continuous_compact_oriented_map_snd_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (z : C.base.Configuration × C.base.Configuration) :
    Measure.map Prod.snd
        (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure
          target z) =
      C.singleLinkHeatBathKernel target z.2 := by
  let n := Fintype.card C.base.geometry.Edge
  let evalLast : ((i : Finset.Iic n) → C.base.Gauge) → C.base.Gauge :=
    fun x => x ⟨n, Finset.mem_Iic.2 le_rfl⟩
  have hEvalLast : Measurable evalLast := measurable_pi_apply _
  have hReplace : Measurable
      (fun g : C.base.Gauge => C.base.replaceLink z.2 target g) :=
    (continuous_compact_oriented_replaceLink C z.2 target).measurable
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMeasure
  rw [Measure.map_map measurable_snd
    (continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap_continuous
      C target z).measurable]
  change Measure.map
      ((fun g : C.base.Gauge => C.base.replaceLink z.2 target g) ∘ evalLast)
      (C.independentPairHybridTargetTrajectoryMeasure z.1 z.2 target n) = _
  rw [← Measure.map_map hReplace hEvalLast]
  rw [show Measure.map evalLast
        (C.independentPairHybridTargetTrajectoryMeasure z.1 z.2 target n) =
      C.singleLinkConditionalMeasure z.2 target by
        simpa [n, evalLast,
          continuous_compact_oriented_independentPairHybridConfiguration_card]
          using
            continuous_compact_oriented_map_last_independentPairHybridTargetTrajectoryMeasure
              C z.1 z.2 target n]
  rw [continuous_compact_oriented_singleLinkHeatBathKernel_apply]

/-- Endpoint reconstruction on the complete joint Gibbs-pair/trajectory carrier. -/
def ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (w : (C.base.Configuration × C.base.Configuration) ×
      ((i : Finset.Iic (Fintype.card C.base.geometry.Edge)) → C.base.Gauge)) :
    C.base.Configuration × C.base.Configuration :=
  C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap
    target w.1 w.2

/-- Joint endpoint reconstruction is continuous. -/
theorem continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap_continuous
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge) :
    Continuous
      (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap
        target) := by
  let n := Fintype.card C.base.geometry.Edge
  have hA : Continuous
      (fun w : (C.base.Configuration × C.base.Configuration) ×
          ((i : Finset.Iic n) → C.base.Gauge) => w.1.1) :=
    continuous_fst.comp continuous_fst
  have hB : Continuous
      (fun w : (C.base.Configuration × C.base.Configuration) ×
          ((i : Finset.Iic n) → C.base.Gauge) => w.1.2) :=
    continuous_snd.comp continuous_fst
  have hZero : Continuous
      (fun w : (C.base.Configuration × C.base.Configuration) ×
          ((i : Finset.Iic n) → C.base.Gauge) =>
        w.2 ⟨0, Finset.mem_Iic.2 (Nat.zero_le n)⟩) :=
    (continuous_apply _).comp continuous_snd
  have hLast : Continuous
      (fun w : (C.base.Configuration × C.base.Configuration) ×
          ((i : Finset.Iic n) → C.base.Gauge) =>
        w.2 ⟨n, Finset.mem_Iic.2 le_rfl⟩) :=
    (continuous_apply _).comp continuous_snd
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap
  exact
    ((continuous_compact_oriented_replaceLink_uncurry C target).comp
      (hA.prodMk hZero)).prodMk
      ((continuous_compact_oriented_replaceLink_uncurry C target).comp
        (hB.prodMk hLast))

/-- Global endpoint coupling obtained by averaging the complete target trajectory
over two independent Gibbs configurations. -/
noncomputable def
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMeasure
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge) :
    Measure (C.base.Configuration × C.base.Configuration) :=
  Measure.map
    (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap
      target)
    (C.independentPairHybridTargetTrajectoryJointMeasure target
      (Fintype.card C.base.geometry.Edge))

instance continuousCompactOriented_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMeasure_isProbability
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge) :
    IsProbabilityMeasure
      (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMeasure
        target) := by
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMeasure
  exact Measure.isProbabilityMeasure_map
    (continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap_continuous
      C target).measurable.aemeasurable

/-- At complete canonical length, trajectory endpoint transport is the observable
difference on the reconstructed endpoint pair. -/
theorem continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointTransportBCF_eq_endpointConfigurationPair
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (w : (C.base.Configuration × C.base.Configuration) ×
      ((i : Finset.Iic (Fintype.card C.base.geometry.Edge)) → C.base.Gauge)) :
    C.independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointTransportBCF
        target O (Fintype.card C.base.geometry.Edge) w =
      O (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap
          target w).1 -
        O (C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap
          target w).2 := by
  let n := Fintype.card C.base.geometry.Edge
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointTransportBCF
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectorySourceBackgroundEndpointTransportBCF
  rw [
    continuous_compact_oriented_independentPairHybridTargetTrajectorySourceBackgroundInsertedObservableValueBCF_of_le
      C (fun r => C.independentPairHybridConfiguration w.1.1 w.1.2 r)
      target O n 0 (Nat.zero_le n) w.2,
    continuous_compact_oriented_independentPairHybridTargetTrajectorySourceBackgroundInsertedObservableValueBCF_of_le
      C (fun r => C.independentPairHybridConfiguration w.1.1 w.1.2 r)
      target O n n le_rfl w.2]
  simp [n,
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap,
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairFiberMap,
    continuous_compact_oriented_independentPairHybridConfiguration_zero,
    continuous_compact_oriented_independentPairHybridConfiguration_card]

/-- Full-rank joint endpoint energy is exactly squared observable transport under
the endpoint configuration-pair coupling. -/
theorem continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointJointEnergyBCF_eq_endpointConfigurationPairMeasure
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ) :
    C.independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointJointEnergyBCF
        target O (Fintype.card C.base.geometry.Edge) =
      ∫ y : C.base.Configuration × C.base.Configuration,
        (O y.1 - O y.2) ^ 2
        ∂C.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMeasure
          target := by
  have hSquare : StronglyMeasurable
      (fun y : C.base.Configuration × C.base.Configuration =>
        (O y.1 - O y.2) ^ 2) :=
    (((O.continuous.comp continuous_fst).sub
      (O.continuous.comp continuous_snd)).pow 2).stronglyMeasurable
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointJointEnergyBCF
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMeasure
  rw [MeasureTheory.integral_map
    (continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalEndpointConfigurationPairMap_continuous
      C target).measurable.aemeasurable
    hSquare.aestronglyMeasurable]
  apply integral_congr_ae
  exact Filter.Eventually.of_forall fun w => by
    unfold
      ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointIntegrandBCF
    rw [continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointTransportBCF_eq_endpointConfigurationPair
      C target O w]

/-- Endpoint-coupling transport energy is nonnegative. -/
theorem continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointJointEnergyBCF_nonneg
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ) :
    0 ≤ C.independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointJointEnergyBCF
        target O (Fintype.card C.base.geometry.Edge) := by
  rw [continuous_compact_oriented_independentPairHybridTargetTrajectoryCanonicalSourceBackgroundEndpointJointEnergyBCF_eq_endpointConfigurationPairMeasure]
  exact integral_nonneg fun _ => sq_nonneg _

end

end MathlibAnalytic
end MGAP4D
