import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonConditionalOverlapRMSInfluenceEnergy

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalResidualProductCouplingMeasure
#check continuous_compact_oriented_map_fst_singleLinkConditionalResidualProductCouplingMeasure
#check continuous_compact_oriented_map_snd_singleLinkConditionalResidualProductCouplingMeasure
#check continuous_compact_oriented_singleLinkConditionalOverlapCouplingMeasure_eq_diagonal_add_residualProduct
#check continuous_compact_oriented_singleLinkConditionalOverlapCoupling_centeredSquare_lintegral_le_two_residual
#check continuous_compact_oriented_singleLinkConditionalResidualMeasure_centeredSquare_sum_lintegral_le_coefficient
#check continuous_compact_oriented_singleLinkConditionalOverlapCoupling_centeredSquare_lintegral_le_two_mul_coefficient
#check continuous_compact_oriented_singleLinkConditionalOverlapCoupling_centeredSquare_lintegral_le_two_mul_compactHaarOscillationInfluence

end

end MGAP4D.MathlibAnalytic
