import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonHybridTargetTrajectoryPeriodicHypercubicBetaZeroRandomScanSpectralConvergenceL2
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory Set

noncomputable section

set_option maxRecDepth 8192

variable {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℝ V]

/-- Scalar multiplication by a fixed vector, bundled as a real linear map. -/
noncomputable def realVectorLineLinearMapL2
    (omega : V) :
    ℝ →ₗ[ℝ] V where
  toFun a := a • omega
  map_add' a b := by
    simp [add_smul]
  map_smul' c a := by
    simp [smul_smul]

/-- The real line generated by a fixed vector. -/
noncomputable def realVectorLineSubmoduleL2
    (omega : V) :
    Submodule ℝ V :=
  LinearMap.range (realVectorLineLinearMapL2 omega)

/-- For a unit vector, membership in its real line is equivalent to the exact
rank-one inner-product formula. -/
theorem mem_realVectorLineSubmoduleL2_iff_eq_inner_smul_of_norm_eq_one
    (omega f : V)
    (hOmega : ‖omega‖ = 1) :
    f ∈ realVectorLineSubmoduleL2 omega ↔
      f = inner ℝ omega f • omega := by
  constructor
  · rintro ⟨a, rfl⟩
    have hInner : inner ℝ omega (a • omega) = a := by
      simp [real_inner_smul_right, real_inner_self_eq_norm_sq, hOmega]
    rw [hInner]
  · intro hf
    refine ⟨inner ℝ omega f, ?_⟩
    change inner ℝ omega f • omega = f
    exact hf.symm

/-- The normalized Gibbs-vacuum line in the actual side-three periodic
`SU(2)`, beta-zero Gibbs `L²` space. -/
noncomputable def periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 :
    Submodule ℝ
      (Lp ℝ 2 periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem.gibbsMeasure) :=
  realVectorLineSubmoduleL2
    periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem.gibbsVacuumL2

/-- Membership in the actual Gibbs-vacuum line is exactly the normalized
rank-one inner-product formula. -/
theorem periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_mem_vacuumLineL2_iff
    (f : Lp ℝ 2 periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem.gibbsMeasure) :
    f ∈ periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 ↔
      f =
        inner ℝ
            periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem.gibbsVacuumL2
            f •
          periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem.gibbsVacuumL2 := by
  simpa [periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2] using
    (mem_realVectorLineSubmoduleL2_iff_eq_inner_smul_of_norm_eq_one
      periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem.gibbsVacuumL2
      f
      (continuous_compact_oriented_gibbsVacuumL2_norm
        periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem))

/-- The actual beta-zero heat-bath cardinality-zero eigenspace is precisely the
normalized Gibbs-vacuum line. -/
theorem periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_vacuumLineL2_eq_heatBathCardinalityEigenspaceL2_zero :
    periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 =
      periodicHypercubicThreeSpecialUnitaryTwoBetaZeroHeatBathCardinalityEigenspaceL2
        0 := by
  ext f
  rw [periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_mem_vacuumLineL2_iff]
  rw [periodicHypercubicThreeSpecialUnitaryTwoBetaZeroHeatBathCardinalityEigenspaceL2,
    Module.End.mem_genEigenspace_one]
  simpa using
    (periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_heatBathHamiltonianL2_eq_zero_iff_eq_inner_smul_vacuum
      f).symm

/-- The stationary cardinality-zero eigenspace of the actual beta-zero
random-scan operator is precisely the normalized Gibbs-vacuum line. -/
theorem periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_vacuumLineL2_eq_randomScanCardinalityEigenspaceL2_zero :
    periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 =
      periodicHypercubicThreeSpecialUnitaryTwoBetaZeroRandomScanCardinalityEigenspaceL2
        0 := by
  calc
    periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 =
        periodicHypercubicThreeSpecialUnitaryTwoBetaZeroHeatBathCardinalityEigenspaceL2
          0 :=
      periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_vacuumLineL2_eq_heatBathCardinalityEigenspaceL2_zero
    _ =
        periodicHypercubicThreeSpecialUnitaryTwoBetaZeroRandomScanCardinalityEigenspaceL2
          0 :=
      (periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_randomScanCardinalityEigenspaceL2_eq_heatBathCardinalityEigenspaceL2
        0).symm

/-- The range of the cardinality-zero spectral projector is exactly the
normalized Gibbs-vacuum line. -/
theorem periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_range_fluctuationCardinalityProjectorL2_zero_eq_vacuumLineL2 :
    LinearMap.range
        (periodicHypercubicThreeSpecialUnitaryTwoBetaZeroFluctuationCardinalityProjectorL2
          0).toLinearMap =
      periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 := by
  calc
    LinearMap.range
        (periodicHypercubicThreeSpecialUnitaryTwoBetaZeroFluctuationCardinalityProjectorL2
          0).toLinearMap =
        periodicHypercubicThreeSpecialUnitaryTwoBetaZeroRandomScanCardinalityEigenspaceL2
          0 :=
      periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_range_fluctuationCardinalityProjectorL2_eq_randomScanCardinalityEigenspaceL2
        0 (by omega)
    _ = periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 :=
      periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_vacuumLineL2_eq_randomScanCardinalityEigenspaceL2_zero.symm

/-- The cardinality-zero joint-sector sum is exactly the normalized
Gibbs-vacuum line. -/
theorem periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_fluctuationCardinalityJointSectorSumSubmoduleL2_zero_eq_vacuumLineL2 :
    periodicHypercubicThreeSpecialUnitaryTwoBetaZeroFluctuationCardinalityJointSectorSumSubmoduleL2
        0 =
      periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 := by
  calc
    periodicHypercubicThreeSpecialUnitaryTwoBetaZeroFluctuationCardinalityJointSectorSumSubmoduleL2
        0 =
        periodicHypercubicThreeSpecialUnitaryTwoBetaZeroRandomScanCardinalityEigenspaceL2
          0 :=
      periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_fluctuationCardinalityJointSectorSumSubmoduleL2_eq_randomScanCardinalityEigenspaceL2
        0 (by omega)
    _ = periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 :=
      periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_vacuumLineL2_eq_randomScanCardinalityEigenspaceL2_zero.symm

/-- Compact receipt identifying every cardinality-zero stationary-sector surface
with the normalized Gibbs-vacuum line. -/
def periodicHypercubicThreeSpecialUnitaryTwoBetaZeroRandomScanVacuumSectorL2Receipt :
    Prop :=
  periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 =
      periodicHypercubicThreeSpecialUnitaryTwoBetaZeroHeatBathCardinalityEigenspaceL2
        0 ∧
    periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 =
      periodicHypercubicThreeSpecialUnitaryTwoBetaZeroRandomScanCardinalityEigenspaceL2
        0 ∧
    LinearMap.range
        (periodicHypercubicThreeSpecialUnitaryTwoBetaZeroFluctuationCardinalityProjectorL2
          0).toLinearMap =
      periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2 ∧
    periodicHypercubicThreeSpecialUnitaryTwoBetaZeroFluctuationCardinalityJointSectorSumSubmoduleL2
        0 =
      periodicHypercubicThreeSpecialUnitaryTwoBetaZeroVacuumLineL2

/-- The actual beta-zero random-scan vacuum-sector identification receipt is
proved. -/
theorem periodicHypercubicThreeSpecialUnitaryTwoBetaZeroRandomScanVacuumSectorL2Receipt_proved :
    periodicHypercubicThreeSpecialUnitaryTwoBetaZeroRandomScanVacuumSectorL2Receipt := by
  exact ⟨
    periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_vacuumLineL2_eq_heatBathCardinalityEigenspaceL2_zero,
    periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_vacuumLineL2_eq_randomScanCardinalityEigenspaceL2_zero,
    periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_range_fluctuationCardinalityProjectorL2_zero_eq_vacuumLineL2,
    periodicHypercubicThreeSpecialUnitaryTwoEndpointSystem_betaZero_fluctuationCardinalityJointSectorSumSubmoduleL2_zero_eq_vacuumLineL2⟩

end

end MathlibAnalytic
end MGAP4D
