import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonFiniteHeatBathScheduleInfluenceKernel
import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonDobrushinIterateRightConvolution
import Mathlib.Tactic

/-!
# Degree refinement of the exact finite heat-bath schedule influence kernel

The exact schedule kernel records all influence propagation generated by a
prescribed finite ordered heat-bath update list.  To compare that schedule with
the unrestricted degree-`d` influence iterates without introducing binomial or
path-multiplicity losses, we first separate the schedule contribution by the
number of influence edges used.

Degree zero is the identity contribution before any influence edge is appended.
For `target :: targets`, the tail acts first.  At a source distinct from
`target`, a degree-`d+1` contribution is the sum of

* tail contributions already of degree `d+1`, and
* one new terminal edge `target → source` times a tail contribution of degree
  `d` ending at `target`.

At the updated target itself every degree is killed.  This file proves the
resulting degree kernel is nonnegative for a nonnegative influence matrix and
has finite degree support: degrees strictly larger than the schedule length
vanish identically.

This is finite Dobrushin/path bookkeeping only.  The summation back to the exact
schedule kernel and the ordered-subsequence comparison with unrestricted walks
are deliberately left to subsequent additive layers.  No covariance decay,
infinite Neumann series, continuum clustering, positive physical mass, OS
Hamiltonian gap, or uniform continuum Dobrushin threshold is asserted here.
-/

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- Degree-`d` part of the exact influence propagation generated by one finite
ordered heat-bath update schedule. -/
noncomputable def finiteHeatBathScheduleInfluenceDegree
    {α : Type*}
    (influence : α → α → ℝ) :
    List α → ℕ → α → α → ℝ
  | [], 0, initial, source => by
      classical
      exact if initial = source then 1 else 0
  | [], _ + 1, _, _ => 0
  | target :: targets, 0, initial, source => by
      classical
      exact
        if source = target then 0
        else finiteHeatBathScheduleInfluenceDegree influence targets 0 initial source
  | target :: targets, d + 1, initial, source => by
      classical
      exact
        if source = target then 0
        else
          finiteHeatBathScheduleInfluenceDegree influence targets (d + 1) initial source +
            influence target source *
              finiteHeatBathScheduleInfluenceDegree influence targets d initial target

@[simp] theorem finiteHeatBathScheduleInfluenceDegree_nil_zero
    {α : Type*}
    [DecidableEq α]
    (influence : α → α → ℝ)
    (initial source : α) :
    finiteHeatBathScheduleInfluenceDegree influence [] 0 initial source =
      if initial = source then 1 else 0 := by
  by_cases h : initial = source <;>
    simp [finiteHeatBathScheduleInfluenceDegree, h]

@[simp] theorem finiteHeatBathScheduleInfluenceDegree_nil_succ
    {α : Type*}
    (influence : α → α → ℝ)
    (d : ℕ)
    (initial source : α) :
    finiteHeatBathScheduleInfluenceDegree influence [] (d + 1) initial source = 0 := by
  rfl

@[simp] theorem finiteHeatBathScheduleInfluenceDegree_cons_zero
    {α : Type*}
    [DecidableEq α]
    (influence : α → α → ℝ)
    (target : α)
    (targets : List α)
    (initial source : α) :
    finiteHeatBathScheduleInfluenceDegree influence (target :: targets) 0 initial source =
      if source = target then 0
      else finiteHeatBathScheduleInfluenceDegree influence targets 0 initial source := by
  by_cases h : source = target <;>
    simp [finiteHeatBathScheduleInfluenceDegree, h]

@[simp] theorem finiteHeatBathScheduleInfluenceDegree_cons_succ
    {α : Type*}
    [DecidableEq α]
    (influence : α → α → ℝ)
    (target : α)
    (targets : List α)
    (d : ℕ)
    (initial source : α) :
    finiteHeatBathScheduleInfluenceDegree influence (target :: targets) (d + 1)
        initial source =
      if source = target then 0
      else
        finiteHeatBathScheduleInfluenceDegree influence targets (d + 1) initial source +
          influence target source *
            finiteHeatBathScheduleInfluenceDegree influence targets d initial target := by
  by_cases h : source = target <;>
    simp [finiteHeatBathScheduleInfluenceDegree, h]

/-- Nonnegative influence entries give nonnegative contributions at every
schedule degree. -/
theorem finiteHeatBathScheduleInfluenceDegree_nonneg
    {α : Type*}
    [DecidableEq α]
    (influence : α → α → ℝ)
    (hInfluence : ∀ target source : α, 0 ≤ influence target source) :
    ∀ (targets : List α) (d : ℕ) (initial source : α),
      0 ≤ finiteHeatBathScheduleInfluenceDegree influence targets d initial source := by
  intro targets
  induction targets with
  | nil =>
      intro d initial source
      cases d with
      | zero =>
          by_cases h : initial = source <;>
            simp [finiteHeatBathScheduleInfluenceDegree, h]
      | succ d =>
          simp [finiteHeatBathScheduleInfluenceDegree]
  | cons target targets ih =>
      intro d initial source
      cases d with
      | zero =>
          by_cases h : source = target
          · simp [finiteHeatBathScheduleInfluenceDegree, h]
          · simpa [finiteHeatBathScheduleInfluenceDegree, h] using ih 0 initial source
      | succ d =>
          by_cases h : source = target
          · simp [finiteHeatBathScheduleInfluenceDegree, h]
          · simp only [finiteHeatBathScheduleInfluenceDegree_cons_succ, h, if_false]
            exact
              add_nonneg
                (ih (d + 1) initial source)
                (mul_nonneg (hInfluence target source) (ih d initial target))

/-- A schedule of length `L` cannot generate a contribution using more than
`L` influence edges. -/
theorem finiteHeatBathScheduleInfluenceDegree_eq_zero_of_length_lt
    {α : Type*}
    [DecidableEq α]
    (influence : α → α → ℝ) :
    ∀ (targets : List α) (d : ℕ) (initial source : α),
      targets.length < d →
        finiteHeatBathScheduleInfluenceDegree influence targets d initial source = 0 := by
  intro targets
  induction targets with
  | nil =>
      intro d initial source hlen
      cases d with
      | zero => omega
      | succ d => simp [finiteHeatBathScheduleInfluenceDegree]
  | cons target targets ih =>
      intro d initial source hlen
      cases d with
      | zero => omega
      | succ d =>
          by_cases h : source = target
          · simp [finiteHeatBathScheduleInfluenceDegree, h]
          · have htail : targets.length < d := by
              simpa using hlen
            have htailSucc : targets.length < d + 1 := by
              omega
            simp [finiteHeatBathScheduleInfluenceDegree, h,
              ih (d + 1) initial source htailSucc,
              ih d initial target htail]

end

end MathlibAnalytic
end MGAP4D
