import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonHybridBoundaryResamplingIntegratedEnergyBCF
import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonConditionalPairVarianceBCF
import Mathlib.Probability.Kernel.Composition.IntegralCompProd
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory ProbabilityTheory
open scoped ProbabilityTheory

noncomputable section

/-- The canonical hybrid pre-step off-target boundary law is a probability
measure. -/
instance continuousCompactOriented_independentPairHybridOffTargetBoundaryMeasure_isProbability
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge) :
    IsProbabilityMeasure
      (C.independentPairHybridOffTargetBoundaryMeasure target) := by
  letI : IsProbabilityMeasure C.gibbsMeasure :=
    continuous_compact_oriented_gibbsMeasure_isProbabilityMeasure C
  letI : IsProbabilityMeasure
      (C.independentPairHybridPreEndpointMeasure target) := by
    unfold
      ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridPreEndpointMeasure
    exact Measure.isProbabilityMeasure_map
      (continuous_compact_oriented_independentPairHybridPreEndpointMap_measurable
        C target).aemeasurable
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridOffTargetBoundaryMeasure
  exact Measure.isProbabilityMeasure_map
    (continuous_compact_oriented_offTargetBoundaryMap_measurable
      C target).aemeasurable

/-- Squared observable difference generated by one common off-target boundary and
two target-link values. -/
def ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (z : C.OffTargetBoundary target ×
      (C.base.Gauge × C.base.Gauge)) : ℝ :=
  (O (C.base.replaceLink
        (C.offTargetBoundarySection target z.1) target z.2.1) -
    O (C.base.replaceLink
        (C.offTargetBoundarySection target z.1) target z.2.2)) ^ 2

/-- The boundary conditional-pair difference integrand is continuous. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_continuous
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ) :
    Continuous
      (C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF target O) := by
  have hBoundary : Continuous
      (fun z : C.OffTargetBoundary target ×
        (C.base.Gauge × C.base.Gauge) =>
        C.offTargetBoundarySection target z.1) :=
    (continuous_compact_oriented_offTargetBoundarySection_continuous
      C target).comp continuous_fst
  have hFirstTarget : Continuous
      (fun z : C.OffTargetBoundary target ×
        (C.base.Gauge × C.base.Gauge) => z.2.1) :=
    (continuous_fst : Continuous
      (fun z : C.base.Gauge × C.base.Gauge => z.1)).comp continuous_snd
  have hSecondTarget : Continuous
      (fun z : C.OffTargetBoundary target ×
        (C.base.Gauge × C.base.Gauge) => z.2.2) :=
    (continuous_snd : Continuous
      (fun z : C.base.Gauge × C.base.Gauge => z.2)).comp continuous_snd
  have hFirstConfiguration : Continuous
      (fun z : C.OffTargetBoundary target ×
        (C.base.Gauge × C.base.Gauge) =>
        C.base.replaceLink
          (C.offTargetBoundarySection target z.1) target z.2.1) :=
    (continuous_compact_oriented_replaceLink_prod_hybridEndpoint
      C target).comp (hBoundary.prodMk hFirstTarget)
  have hSecondConfiguration : Continuous
      (fun z : C.OffTargetBoundary target ×
        (C.base.Gauge × C.base.Gauge) =>
        C.base.replaceLink
          (C.offTargetBoundarySection target z.1) target z.2.2) :=
    (continuous_compact_oriented_replaceLink_prod_hybridEndpoint
      C target).comp (hBoundary.prodMk hSecondTarget)
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
  exact
    ((O.continuous.comp hFirstConfiguration).sub
      (O.continuous.comp hSecondConfiguration)).pow 2

/-- The boundary conditional-pair integrand is nonnegative. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_nonneg
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (z : C.OffTargetBoundary target ×
      (C.base.Gauge × C.base.Gauge)) :
    0 ≤ C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF target O z := by
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
  exact sq_nonneg _

/-- The squared conditional-pair difference is uniformly bounded by four times
the squared bounded-continuous norm. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_abs_le
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (z : C.OffTargetBoundary target ×
      (C.base.Gauge × C.base.Gauge)) :
    |C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF target O z| ≤
      (2 * ‖O‖) ^ 2 := by
  let A := C.base.replaceLink
    (C.offTargetBoundarySection target z.1) target z.2.1
  let B := C.base.replaceLink
    (C.offTargetBoundarySection target z.1) target z.2.2
  have hA : |O A| ≤ ‖O‖ := by
    simpa [Real.norm_eq_abs] using O.norm_coe_le_norm A
  have hB : |O B| ≤ ‖O‖ := by
    simpa [Real.norm_eq_abs] using O.norm_coe_le_norm B
  have hDiff : |O A - O B| ≤ 2 * ‖O‖ := by
    calc
      |O A - O B| ≤ |O A| + |O B| := abs_sub _ _
      _ ≤ ‖O‖ + ‖O‖ := add_le_add hA hB
      _ = 2 * ‖O‖ := (two_mul ‖O‖).symm
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
  change |(O A - O B) ^ 2| ≤ (2 * ‖O‖) ^ 2
  rw [abs_pow]
  nlinarith [abs_nonneg (O A - O B), norm_nonneg O]

/-- The common-boundary conditional-pair integrand is integrable after mixing any
probability boundary law through the exact conditional-pair kernel. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_integrable_compProd
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (μ : Measure (C.OffTargetBoundary target))
    [IsProbabilityMeasure μ] :
    Integrable
      (C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF target O)
      (μ ⊗ₘ C.singleLinkBoundaryConditionalPairKernel target) := by
  letI : IsProbabilityMeasure
      (μ ⊗ₘ C.singleLinkBoundaryConditionalPairKernel target) := by
    infer_instance
  apply continuous_compact_oriented_integrable_of_uniform_bound
    (μ ⊗ₘ C.singleLinkBoundaryConditionalPairKernel target)
    (C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF target O)
    (continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_continuous
      C target O).stronglyMeasurable
    ((2 * ‖O‖) ^ 2)
  intro z
  exact
    continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_abs_le
      C target O z

/-- Boundary-indexed native conditional independent-pair observable energy. -/
def ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (boundary : C.OffTargetBoundary target) : ℝ :=
  ∫ pair : C.base.Gauge × C.base.Gauge,
    C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
      target O (boundary, pair)
    ∂C.singleLinkBoundaryConditionalPairKernel target boundary

/-- The boundary-indexed conditional-pair energy is strongly measurable as a
function of the common boundary. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_stronglyMeasurable
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ) :
    StronglyMeasurable
      (C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
        target O) := by
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
  exact
    (continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_continuous
      C target O).stronglyMeasurable.integral_kernel_prod_right'

/-- The boundary-indexed conditional-pair energy is nonnegative. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_nonneg
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (boundary : C.OffTargetBoundary target) :
    0 ≤ C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
      target O boundary := by
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
  exact integral_nonneg fun pair =>
    continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_nonneg
      C target O (boundary, pair)

/-- The boundary-indexed energy inherits the uniform squared observable bound. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_le
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (boundary : C.OffTargetBoundary target) :
    C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
        target O boundary ≤
      (2 * ‖O‖) ^ 2 := by
  letI : IsProbabilityMeasure
      (C.singleLinkBoundaryConditionalPairMeasure target boundary) :=
    continuous_compact_oriented_singleLinkBoundaryConditionalPairMeasure_isProbabilityMeasure
      C target boundary
  have hIntegrable : Integrable
      (fun pair : C.base.Gauge × C.base.Gauge =>
        C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
          target O (boundary, pair))
      (C.singleLinkBoundaryConditionalPairMeasure target boundary) := by
    apply continuous_compact_oriented_integrable_of_uniform_bound
      (C.singleLinkBoundaryConditionalPairMeasure target boundary)
      (fun pair : C.base.Gauge × C.base.Gauge =>
        C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
          target O (boundary, pair))
      ((continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_continuous
        C target O).comp
        ((continuous_const : Continuous
          (fun _ : C.base.Gauge × C.base.Gauge => boundary)).prodMk
          continuous_id)).stronglyMeasurable
      ((2 * ‖O‖) ^ 2)
    intro pair
    exact
      continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_abs_le
        C target O (boundary, pair)
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
  rw [continuous_compact_oriented_singleLinkBoundaryConditionalPairKernel_apply]
  calc
    (∫ pair,
        C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
          target O (boundary, pair)
        ∂C.singleLinkBoundaryConditionalPairMeasure target boundary) ≤
      ∫ _pair : C.base.Gauge × C.base.Gauge,
        (2 * ‖O‖) ^ 2
        ∂C.singleLinkBoundaryConditionalPairMeasure target boundary := by
      apply integral_mono hIntegrable (integrable_const _)
      intro pair
      exact le_trans (le_abs_self _)
        (continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_abs_le
          C target O (boundary, pair))
    _ = (2 * ‖O‖) ^ 2 := by simp

/-- The boundary-indexed energy is uniformly absolutely bounded. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_abs_le
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (boundary : C.OffTargetBoundary target) :
    |C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
      target O boundary| ≤ (2 * ‖O‖) ^ 2 := by
  rw [abs_of_nonneg
    (continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_nonneg
      C target O boundary)]
  exact
    continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_le
      C target O boundary

/-- The boundary-indexed energy is integrable under every probability boundary
law. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_integrable
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (μ : Measure (C.OffTargetBoundary target))
    [IsProbabilityMeasure μ] :
    Integrable
      (C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
        target O) μ := by
  apply continuous_compact_oriented_integrable_of_uniform_bound
    μ
    (C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
      target O)
    (continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_stronglyMeasurable
      C target O)
    ((2 * ‖O‖) ^ 2)
  intro boundary
  exact
    continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_abs_le
      C target O boundary

/-- At the canonical section of a boundary, the boundary-indexed energy is exactly
the existing configuration-indexed native conditional-pair energy. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_eq_section
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (boundary : C.OffTargetBoundary target) :
    C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
        target O boundary =
      C.singleLinkConditionalIndependentPairDifferenceEnergyBCF
        target O (C.offTargetBoundarySection target boundary) := by
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
  rw [continuous_compact_oriented_singleLinkBoundaryConditionalPairKernel_apply]
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalPairMeasure
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalMeasure
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalIndependentPairDifferenceEnergyBCF
  rfl

/-- Replacing the omitted link after canonically extending a configuration's
boundary recovers the same one-link replacement of the original configuration. -/
theorem continuous_compact_oriented_replaceLink_offTargetBoundarySection_map
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (A : C.base.Configuration)
    (g : C.base.Gauge) :
    C.base.replaceLink
        (C.offTargetBoundarySection target
          (C.offTargetBoundaryMap target A)) target g =
      C.base.replaceLink A target g := by
  funext source
  by_cases hsource : source = target
  · subst source
    simp [CompactOrientedGaugeWilsonSystem.replaceLink]
  · simp
      [CompactOrientedGaugeWilsonSystem.replaceLink,
        ContinuousCompactOrientedGaugeWilsonSystem.offTargetBoundarySection,
        ContinuousCompactOrientedGaugeWilsonSystem.offTargetBoundaryMap,
        hsource]

/-- Restricting a full background to its boundary and evaluating the boundary
energy recovers the existing configuration-indexed native conditional-pair
energy exactly. -/
theorem continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_offTargetBoundaryMap
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (A : C.base.Configuration) :
    C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
        target O (C.offTargetBoundaryMap target A) =
      C.singleLinkConditionalIndependentPairDifferenceEnergyBCF target O A := by
  rw [continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_eq_section]
  unfold
    ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalIndependentPairDifferenceEnergyBCF
  rw [← continuous_compact_oriented_singleLinkBoundaryConditionalMeasure_offTargetBoundaryMap
    C target A]
  apply integral_congr_ae
  filter_upwards [] with pair
  rw [continuous_compact_oriented_replaceLink_offTargetBoundarySection_map
      C target A pair.1,
    continuous_compact_oriented_replaceLink_offTargetBoundarySection_map
      C target A pair.2]

/-- The hybrid-boundary central term is exactly the boundary average of the
native conditional independent-pair fiber energy. -/
theorem continuous_compact_oriented_independentPairHybridBoundaryResampledConditionalPairEnergyBCF_eq_boundaryIntegral
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ) :
    C.independentPairHybridBoundaryResampledConditionalPairEnergyBCF target O =
      ∫ boundary,
        C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
          target O boundary
        ∂C.independentPairHybridOffTargetBoundaryMeasure target := by
  have hConfigurationIntegrand : StronglyMeasurable
      (fun y : C.base.Configuration × C.base.Configuration =>
        (O y.2 - O y.1) ^ 2) :=
    (((O.continuous.comp continuous_snd).sub
      (O.continuous.comp continuous_fst)).pow 2).stronglyMeasurable
  have hJointIntegrable : Integrable
      (C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF target O)
      (C.independentPairHybridOffTargetBoundaryMeasure target ⊗ₘ
        C.singleLinkBoundaryConditionalPairKernel target) :=
    continuous_compact_oriented_singleLinkBoundaryConditionalPairDifferenceIntegrandBCF_integrable_compProd
      C target O (C.independentPairHybridOffTargetBoundaryMeasure target)
  calc
    C.independentPairHybridBoundaryResampledConditionalPairEnergyBCF target O =
        ∫ z,
          (O (C.offTargetBoundaryTargetPairConfigurationPairMap target z).2 -
            O (C.offTargetBoundaryTargetPairConfigurationPairMap target z).1) ^ 2
          ∂C.independentPairHybridBoundaryDrivenTargetPairMeasure target := by
      unfold
        ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridBoundaryResampledConditionalPairEnergyBCF
        ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridBoundaryResampledConfigurationPairMeasure
      exact MeasureTheory.integral_map
        (continuous_compact_oriented_offTargetBoundaryTargetPairConfigurationPairMap_measurable
          C target).aemeasurable
        hConfigurationIntegrand.aestronglyMeasurable
    _ = ∫ z,
        C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF target O z
        ∂C.independentPairHybridBoundaryDrivenTargetPairMeasure target := by
      apply integral_congr_ae
      filter_upwards [] with z
      unfold
        ContinuousCompactOrientedGaugeWilsonSystem.offTargetBoundaryTargetPairConfigurationPairMap
        ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalPairConfigurationMap
        ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF
      ring
    _ = ∫ z,
        C.singleLinkBoundaryConditionalPairDifferenceIntegrandBCF target O z
        ∂(C.independentPairHybridOffTargetBoundaryMeasure target ⊗ₘ
          C.singleLinkBoundaryConditionalPairKernel target) := by
      unfold
        ContinuousCompactOrientedGaugeWilsonSystem.independentPairHybridBoundaryDrivenTargetPairMeasure
        ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryTargetPairKernel
      rw [← Measure.compProd_eq_comp_prod]
    _ = ∫ boundary,
        C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
          target O boundary
        ∂C.independentPairHybridOffTargetBoundaryMeasure target := by
      simpa
        [ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF]
        using Measure.integral_compProd hJointIntegrable

/-- The existing Gibbs-averaged native local pair energy is the same fiber-energy
function averaged against the genuine Gibbs boundary law. -/
theorem continuous_compact_oriented_integral_singleLinkConditionalIndependentPairDifferenceEnergyBCF_eq_boundaryIntegral
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ) :
    (∫ A,
        C.singleLinkConditionalIndependentPairDifferenceEnergyBCF target O A
        ∂C.gibbsMeasure) =
      ∫ boundary,
        C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
          target O boundary
        ∂C.gibbsOffTargetBoundaryMeasure target := by
  have hFiberStrong :=
    continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_stronglyMeasurable
      C target O
  calc
    (∫ A,
        C.singleLinkConditionalIndependentPairDifferenceEnergyBCF target O A
        ∂C.gibbsMeasure) =
      ∫ A,
        C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
          target O (C.offTargetBoundaryMap target A)
        ∂C.gibbsMeasure := by
      apply integral_congr_ae
      filter_upwards [] with A
      exact
        (continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_offTargetBoundaryMap
          C target O A).symm
    _ = ∫ boundary,
        C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
          target O boundary
        ∂C.gibbsOffTargetBoundaryMeasure target := by
      unfold
        ContinuousCompactOrientedGaugeWilsonSystem.gibbsOffTargetBoundaryMeasure
      symm
      exact MeasureTheory.integral_map
        (continuous_compact_oriented_offTargetBoundaryMap_measurable
          C target).aemeasurable
        hFiberStrong.aestronglyMeasurable

/-- If the hybrid pre-boundary law equals the genuine Gibbs boundary law, then
the hybrid-boundary central term is exactly the existing Gibbs-averaged native
local conditional-pair energy. -/
theorem continuous_compact_oriented_independentPairHybridBoundaryResampledConditionalPairEnergyBCF_eq_native_of_boundaryMeasure_eq
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (hBoundary :
      C.independentPairHybridOffTargetBoundaryMeasure target =
        C.gibbsOffTargetBoundaryMeasure target) :
    C.independentPairHybridBoundaryResampledConditionalPairEnergyBCF target O =
      ∫ A,
        C.singleLinkConditionalIndependentPairDifferenceEnergyBCF target O A
        ∂C.gibbsMeasure := by
  rw [continuous_compact_oriented_independentPairHybridBoundaryResampledConditionalPairEnergyBCF_eq_boundaryIntegral,
    hBoundary]
  exact
    (continuous_compact_oriented_integral_singleLinkConditionalIndependentPairDifferenceEnergyBCF_eq_boundaryIntegral
      C target O).symm

/-- Any uniform squared fiber majorant controls the hybrid-boundary central term.
This theorem requires the majorant explicitly and makes no inference from the
Radon--Nikodym formula alone. -/
theorem continuous_compact_oriented_independentPairHybridBoundaryResampledConditionalPairEnergyBCF_le_sq_of_fiber_le
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (target : C.base.geometry.Edge)
    (O : BoundedContinuousFunction C.base.Configuration ℝ)
    (q : ℝ)
    (hq : ∀ boundary : C.OffTargetBoundary target,
      C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
        target O boundary ≤ q ^ 2) :
    C.independentPairHybridBoundaryResampledConditionalPairEnergyBCF target O ≤
      q ^ 2 := by
  letI : IsProbabilityMeasure
      (C.independentPairHybridOffTargetBoundaryMeasure target) :=
    continuousCompactOriented_independentPairHybridOffTargetBoundaryMeasure_isProbability
      C target
  rw [continuous_compact_oriented_independentPairHybridBoundaryResampledConditionalPairEnergyBCF_eq_boundaryIntegral]
  have hFiberIntegrable :=
    continuous_compact_oriented_singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF_integrable
      C target O (C.independentPairHybridOffTargetBoundaryMeasure target)
  calc
    (∫ boundary,
        C.singleLinkBoundaryConditionalIndependentPairDifferenceEnergyBCF
          target O boundary
        ∂C.independentPairHybridOffTargetBoundaryMeasure target) ≤
      ∫ _boundary : C.OffTargetBoundary target, q ^ 2
        ∂C.independentPairHybridOffTargetBoundaryMeasure target := by
      exact integral_mono hFiberIntegrable (integrable_const _) hq
    _ = q ^ 2 := by simp

end

end MathlibAnalytic
end MGAP4D
