import MGAP4D.MathlibAnalytic.ContinuousLinearMapFiniteDimensionalRealResolventLinearResponseCore
import MGAP4D.MathlibAnalytic.ContinuousLinearMapFiniteDimensionalRealResolventLinearResponseTransfer
import MGAP4D.MathlibAnalytic.ContinuousLinearMapFiniteDimensionalRealResolventTraceResponse
import MGAP4D.MathlibAnalytic.ContinuousLinearMapOpenResolventTaylorFiniteDimensionalCompressionRealResolventLinearResponseCompact
import MGAP4D.MathlibAnalytic.ContinuousLinearMapOpenResolventTaylorFiniteDimensionalCompressionRealResolventLinearResponseCompactRectangular
import MGAP4D.MathlibAnalytic.ContinuousLinearMapOpenResolventTaylorFiniteDimensionalCompressionRealResolventLinearResponseClosedBox
import MGAP4D.MathlibAnalytic.ContinuousLinearMapOpenResolventTaylorFiniteDimensionalCompressionRealResolventLinearResponseClosedBoxDiagonal
import MGAP4D.MathlibAnalytic.ContinuousLinearMapOpenResolventTaylorFiniteDimensionalCompressionRealResolventTraceResponseCompact
import MGAP4D.MathlibAnalytic.ContinuousLinearMapOpenResolventTaylorFiniteDimensionalCompressionRealResolventTraceResponseClosedBox
import MGAP4D.MathlibAnalytic.ContinuousLinearMapOpenResolventTaylorFiniteDimensionalCompressionRealResolventTraceResponseClosedBoxDiagonal

/-!
# Finite-dimensional real-resolvent linear spectral response package

Aggregate root for arbitrary continuous-linear spectral responses and their
basis-independent trace specialization.  The package includes Hermite response
coefficients and jets, exact Newton-Hermite interpolation and remainder
identities, finite observable-family transfer, compact and finite-rectangular
uniform convergence, complete closed-box joint nets, and diagonal no-rate
convergence after arbitrary finite-dimensional compression.
-/
