import MGAP4D.MathlibAnalytic.ContinuousLinearMapFiniteDimensionalRealResolventFiniteParameterDerivative
import Mathlib.Analysis.Analytic.IteratedFDeriv
import Mathlib.Analysis.Calculus.ContDiff.FTaylorSeries

#check HasFPowerSeriesAt.comp_add
#check HasFPowerSeriesAt.comp_sub
#check HasFPowerSeriesAt.compContinuousLinearMap
#check FormalMultilinearSeries.compContinuousLinearMap_apply
#check ContinuousLinearMap.iteratedFDeriv_comp_right
#check iteratedFDeriv_comp_add
#check iteratedFDeriv_comp_sub
#check ContinuousMultilinearMap.compContinuousLinearMap_apply
