import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonDobrushinMatrix

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators

noncomputable section

/-- Sharp one-link conditional-TV majorant generated by a local-action
oscillation radius. -/
def continuousCompactOrientedGaugeWilsonConditionalTVMajorant
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (omega : ℝ) : ℝ :=
  (Real.exp (C.base.beta * omega) - 1) /
    (Real.exp (C.base.beta * omega) + 1)

/-- The sparse compact oriented influence profile supported on active physical
plaquette neighbors. -/
noncomputable def continuousCompactOrientedGaugeWilsonDobrushinInfluence
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (omega : ℝ)
    (target source : C.base.geometry.Edge) : ℝ := by
  classical
  exact if source ∈ C.base.activePlaquetteNeighbors target then
    continuousCompactOrientedGaugeWilsonConditionalTVMajorant C omega
  else 0

/-- The sharp compact conditional-TV majorant is nonnegative for nonnegative
local-action oscillation. -/
theorem continuous_compact_oriented_conditionalTVMajorant_nonneg
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (omega : ℝ)
    (hOmega : 0 ≤ omega) :
    0 ≤ continuousCompactOrientedGaugeWilsonConditionalTVMajorant C omega := by
  unfold continuousCompactOrientedGaugeWilsonConditionalTVMajorant
  have hR : 0 ≤ C.base.beta * omega :=
    mul_nonneg C.base.beta_nonneg hOmega
  exact div_nonneg
    (sub_nonneg.mpr (Real.one_le_exp hR))
    (by positivity)

/-- Exact row sum of the sparse compact oriented influence profile. -/
theorem continuous_compact_oriented_dobrushinInfluence_rowSum_eq
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (omega : ℝ)
    (target : C.base.geometry.Edge) :
    (∑ source : C.base.geometry.Edge,
        continuousCompactOrientedGaugeWilsonDobrushinInfluence
          C omega target source) =
      (C.base.activePlaquetteNeighbors target).card *
        continuousCompactOrientedGaugeWilsonConditionalTVMajorant C omega := by
  classical
  let s := C.base.activePlaquetteNeighbors target
  let q := continuousCompactOrientedGaugeWilsonConditionalTVMajorant C omega
  change (∑ source : C.base.geometry.Edge,
      if source ∈ s then q else 0) = (s.card : ℝ) * q
  rw [← Finset.sum_filter]
  have hFilter :
      (Finset.univ.filter fun source : C.base.geometry.Edge => source ∈ s) = s := by
    ext source
    simp
  rw [hFilter]
  simp [nsmul_eq_mul]

end
end MathlibAnalytic
end MGAP4D
