import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonConditionalResidualWeightedInfluence

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check HaarLikelihoodRatioInfluence.residual_pair_sum_eq_abs_sub
#check HaarLikelihoodRatioInfluence.residual_pair_sum_le_coefficient_mul_add
#check continuous_compact_oriented_singleLinkConditionalRightResidualDensity_eq_ofReal
#check continuous_compact_oriented_singleLinkConditionalResidualDensity_sum_le_coefficient_mul_conditionalDensity_sum
#check continuous_compact_oriented_singleLinkConditionalResidualDensity_weighted_lintegral_le_coefficient
#check continuous_compact_oriented_singleLinkConditionalResidualDensity_weighted_lintegral_le_compactHaarOscillationInfluence
#check continuous_compact_oriented_singleLinkConditionalResidualDensity_centeredSquare_lintegral_le_compactHaarOscillationInfluence

end

end MGAP4D.MathlibAnalytic
