import MGAP4D.MathlibAnalytic.DistinguishedVectorHilbertBasis
import Mathlib.SetTheory.Cardinal.Order
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

universe u v

/-- A lifted cardinal inequality between types in possibly different universes
canonically supplies an embedding.  This is the direct computational content of
Mathlib's `Cardinal.lift_mk_le'`. -/
noncomputable def embeddingOfLiftedCardinalLE
    {α : Type u} {β : Type v}
    (h : Cardinal.lift.{v} #α ≤ Cardinal.lift.{u} #β) :
    α ↪ β :=
  Classical.choice (Cardinal.lift_mk_le'.mp h)

/-- Hilbert-dimension comparison for two distinguished unit vectors, stated on
the noncomputably selected Hilbert-basis index types generated by
`distinguishedVectorHilbertBasis`.

The lifts make the statement universe-polymorphic.  No basis, embedding, or
linear map is stored here: this is only the cardinal inequality saying that the
source Hilbert dimension does not exceed the target Hilbert dimension. -/
def DistinguishedVectorHilbertDimensionLE
    {H : Type u} {K : Type v}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup K] [InnerProductSpace ℝ K] [CompleteSpace K]
    (x : H) (hx : ‖x‖ = 1)
    (y : K) (hy : ‖y‖ = 1) : Prop :=
  Cardinal.lift.{v}
      #(distinguishedVectorHilbertBasis x hx).Index ≤
    Cardinal.lift.{u}
      #(distinguishedVectorHilbertBasis y hy).Index

/-- A Hilbert-dimension inequality between two real Hilbert spaces with
specified unit vectors theorem-generates a genuine linear isometric embedding
which preserves those vectors exactly.

The proof is the short Mathlib chain

`Cardinal.lift_mk_le' → Function.Embedding → distinguished-vector Hilbert isometry`.
-/
noncomputable def distinguishedVectorLinearIsometryOfDimensionLE
    {H : Type u} {K : Type v}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup K] [InnerProductSpace ℝ K] [CompleteSpace K]
    (x : H) (hx : ‖x‖ = 1)
    (y : K) (hy : ‖y‖ = 1)
    (hDim : DistinguishedVectorHilbertDimensionLE x hx y hy) :
    H →ₗᵢ[ℝ] K :=
  distinguishedVectorLinearIsometryOfIndexEmbedding
    x hx y hy
    (embeddingOfLiftedCardinalLE hDim)

/-- The cardinally generated Hilbert isometry preserves the distinguished unit
vector exactly. -/
@[simp] theorem distinguishedVectorLinearIsometryOfDimensionLE_apply
    {H : Type u} {K : Type v}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup K] [InnerProductSpace ℝ K] [CompleteSpace K]
    (x : H) (hx : ‖x‖ = 1)
    (y : K) (hy : ‖y‖ = 1)
    (hDim : DistinguishedVectorHilbertDimensionLE x hx y hy) :
    distinguishedVectorLinearIsometryOfDimensionLE x hx y hy hDim x = y := by
  exact distinguishedVectorLinearIsometryOfIndexEmbedding_apply
    x hx y hy (embeddingOfLiftedCardinalLE hDim)

end

end MathlibAnalytic
end MGAP4D
