import MGAP4D.MathlibAnalytic.WightmanOSSpectralIntegralPVMIdentificationNecessity
import MGAP4D.MathlibAnalytic.EuclideanYangMillsOSPhysicalSpectralIntegralSpecialization

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- Turn a generic real spectral integral on the exported reconstructed model into
its actual OS physical-Hilbert specialization. -/
def EuclideanYangMillsOSPhysicalSpectralIntegral.ofRealSpectralIntegral
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    {M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S}
    (I : ExplicitWightmanOSRealSpectralIntegral M.toExplicitModel) :
    EuclideanYangMillsOSPhysicalSpectralIntegral M where
  integral := I.integral
  indicator_integral_eq_projection := I.indicator_integral_eq_projection
  eigenvector_integral_evaluation := I.eigenvector_integral_evaluation

/-- The intrinsic self-adjoint spectral resolution attached by `C` to the actual
OS physical reconstructed Hamiltonian.  Its self-adjointness argument is supplied
by the reconstructed model itself. -/
def euclideanYangMillsOSPhysicalIntrinsicSpectralResolution
    (C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor)
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    (M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S) :
    ExplicitWightmanOSSelfAdjointSpectralResolution M.toExplicitModel :=
  C.construct M.toExplicitModel M.toExplicitModel.hamiltonianSelfAdjoint

/-- Exact actual-model compatibility obligation: the PVM generated by the
intrinsic self-adjoint spectral resolution agrees, on every measurable set, with
the PVM stored in the actual OS physical reconstructed model. -/
def EuclideanYangMillsOSPhysicalHasMeasurableSpectralPVMIdentification
    (C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor)
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    (M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S) : Prop :=
  (euclideanYangMillsOSPhysicalIntrinsicSpectralResolution C M).HasMeasurablePVMIdentification

/-- Measurable PVM identification is sufficient to construct spectral integration
on the actual OS physical-Hilbert reconstructed model. -/
def euclideanYangMillsOSPhysicalSpectralIntegralOfMeasurablePVMIdentification
    (C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor)
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    (M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S)
    (hIdent :
      EuclideanYangMillsOSPhysicalHasMeasurableSpectralPVMIdentification C M) :
    EuclideanYangMillsOSPhysicalSpectralIntegral M :=
  EuclideanYangMillsOSPhysicalSpectralIntegral.ofRealSpectralIntegral
    ((euclideanYangMillsOSPhysicalIntrinsicSpectralResolution C M).toRealSpectralIntegralOfMeasurablePVMIdentification
      hIdent)

/-- Actual-model necessity: an actual OS physical spectral integral preserving the
intrinsic spectral-theorem integral forces measurable identification of the
generated and stored PVMs. -/
theorem euclidean_yang_mills_os_physical_measurable_spectralPVM_identification_of_same_integral
    (C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor)
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    (M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S)
    (I : EuclideanYangMillsOSPhysicalSpectralIntegral M)
    (hSameIntegral :
      ∀ (f : ℝ → ℝ), ∀ ψ : M.toExplicitModel.H,
        (euclideanYangMillsOSPhysicalIntrinsicSpectralResolution C M).integral f ψ =
          I.integral f ψ) :
    EuclideanYangMillsOSPhysicalHasMeasurableSpectralPVMIdentification C M := by
  exact
    (euclideanYangMillsOSPhysicalIntrinsicSpectralResolution C M).measurablePVMIdentification_of_realSpectralIntegral_same_integral
      I.toRealSpectralIntegral hSameIntegral

/-- Exact actual-model characterization: an actual OS physical spectral integral
with the intrinsic integral exists if and only if the generated PVM and the stored
actual-model PVM agree on every measurable spectral set. -/
theorem euclidean_yang_mills_os_physical_exists_spectralIntegral_same_integral_iff_measurablePVMIdentification
    (C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor)
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    (M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S) :
    (∃ I : EuclideanYangMillsOSPhysicalSpectralIntegral M,
      ∀ (f : ℝ → ℝ), ∀ ψ : M.toExplicitModel.H,
        (euclideanYangMillsOSPhysicalIntrinsicSpectralResolution C M).integral f ψ =
          I.integral f ψ) ↔
      EuclideanYangMillsOSPhysicalHasMeasurableSpectralPVMIdentification C M := by
  constructor
  · rintro ⟨I, hSameIntegral⟩
    exact
      euclidean_yang_mills_os_physical_measurable_spectralPVM_identification_of_same_integral
        C M I hSameIntegral
  · intro hIdent
    refine ⟨
      euclideanYangMillsOSPhysicalSpectralIntegralOfMeasurablePVMIdentification
        C M hIdent,
      ?_⟩
    intro f ψ
    rfl

/-- One measurable projection disagreement on the actual OS physical model rules
out every actual spectral integral that preserves the intrinsic self-adjoint
spectral-theorem integral. -/
theorem euclidean_yang_mills_os_physical_no_spectralIntegral_same_integral_of_projection_disagreement
    (C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor)
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    (M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S)
    {s : Set ℝ} (hs : MeasurableSet s) {ψ : M.toExplicitModel.H}
    (hDisagree :
      (euclideanYangMillsOSPhysicalIntrinsicSpectralResolution C M).spectralPVM.projection s ψ ≠
        M.toExplicitModel.spectralPVM.projection s ψ) :
    ¬ ∃ I : EuclideanYangMillsOSPhysicalSpectralIntegral M,
      ∀ (f : ℝ → ℝ), ∀ x : M.toExplicitModel.H,
        (euclideanYangMillsOSPhysicalIntrinsicSpectralResolution C M).integral f x =
          I.integral f x := by
  intro hExists
  rcases hExists with ⟨I, hSameIntegral⟩
  apply hDisagree
  exact
    (euclidean_yang_mills_os_physical_measurable_spectralPVM_identification_of_same_integral
      C M I hSameIntegral) s hs ψ

/-- Model-local certificate carrying exactly the compatibility proof needed to
turn a self-adjoint spectral resolution into actual OS physical spectral
integration. -/
structure EuclideanYangMillsOSPhysicalMeasurableSpectralPVMIdentificationCertificate
    (C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor)
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    (M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S) where
  identified :
    EuclideanYangMillsOSPhysicalHasMeasurableSpectralPVMIdentification C M

/-- The model-local PVM identification certificate produces the actual OS
physical spectral integral. -/
def EuclideanYangMillsOSPhysicalMeasurableSpectralPVMIdentificationCertificate.toSpectralIntegral
    {C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor}
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    {M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S}
    (X : EuclideanYangMillsOSPhysicalMeasurableSpectralPVMIdentificationCertificate C M) :
    EuclideanYangMillsOSPhysicalSpectralIntegral M :=
  euclideanYangMillsOSPhysicalSpectralIntegralOfMeasurablePVMIdentification
    C M X.identified

/-- The identified actual spectral resolution yields the ambient measurable-set
indicator evaluation law. -/
theorem euclidean_yang_mills_os_physical_ambient_indicator_evaluation_of_measurablePVMIdentification
    {C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor}
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    (M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S)
    (X : EuclideanYangMillsOSPhysicalMeasurableSpectralPVMIdentificationCertificate C M) :
    ExplicitWightmanOSAmbientEigenvectorIndicatorEvaluationLaw M.toExplicitModel := by
  exact
    euclidean_yang_mills_os_physical_ambient_indicator_evaluation_of_spectralIntegral
      M X.toSpectralIntegral

/-- Together with the scalar-measure quadratic law, the identified actual
spectral resolution yields canonical singleton eigenprojection compatibility. -/
theorem euclidean_yang_mills_os_physical_canonical_eigenprojection_law_of_measurablePVMIdentification
    {C : ExplicitWightmanOSSelfAdjointSpectralResolutionConstructor}
    {S : EuclideanYangMillsContinuumMeasureConstructionSpine}
    (M : EuclideanYangMillsOSPhysicalHilbertReconstructedModel S)
    (X : EuclideanYangMillsOSPhysicalMeasurableSpectralPVMIdentificationCertificate C M)
    (P : ExplicitWightmanOSCountablyAdditivePVMScalarMeasure M.toExplicitModel)
    (hQuadratic :
      ExplicitWightmanOSScalarMeasureENNRealQuadraticLaw M.toExplicitModel P) :
    ExplicitWightmanOSCanonicalEigenprojectionLaw M.toExplicitModel := by
  exact
    euclidean_yang_mills_os_physical_canonical_eigenprojection_law_of_spectralIntegral
      M P hQuadratic X.toSpectralIntegral

end

end MathlibAnalytic
end MGAP4D
