import MGAP4D.MathlibAnalytic.FilterKuratowskiSingletonConvergence
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open Filter Set Topology

universe u v

namespace FilterSet

variable {ι : Type u} {X : Type v} [TopologicalSpace X]

/-- A point belongs to the Kuratowski inner limit of a singleton-valued net
exactly when the generating net converges to that point. -/
theorem tendsto_iff_mem_kuratowskiInnerLimit_singleton
    {l : Filter ι} {f : ι → X} {x : X} :
    Tendsto f l (nhds x) ↔
      x ∈ kuratowskiInnerLimit l (fun i => {f i}) := by
  constructor
  · intro hf
    exact mem_kuratowskiInnerLimit_of_tendsto_of_eventually_mem hf
      (Eventually.of_forall fun i => by simp)
  · intro hx
    rw [tendsto_def]
    intro U hU
    filter_upwards [hx U hU] with i hi
    rcases hi with ⟨y, hy, hyU⟩
    have hyEq : y = f i := by
      simpa only [Set.mem_singleton_iff] using hy
    simpa only [hyEq] using hyU

/-- In a Hausdorff space over a nontrivial filter, convergence of a net is
equivalent to both Kuratowski limits of its singleton family being the limit
singleton. -/
theorem tendsto_iff_kuratowskiLimits_singleton
    [T2Space X] (l : Filter ι) [NeBot l] {f : ι → X} {x : X} :
    Tendsto f l (nhds x) ↔
      kuratowskiInnerLimit l (fun i => {f i}) = {x} ∧
      kuratowskiOuterLimit l (fun i => {f i}) = {x} := by
  constructor
  · exact kuratowskiLimits_singleton_of_tendsto l
  · intro h
    rw [tendsto_iff_mem_kuratowskiInnerLimit_singleton]
    rw [h.1]
    simp

/-- If a set-valued net is eventually the singleton family generated by `f`,
then its two singleton Kuratowski limits are equivalent to convergence of `f`. -/
theorem tendsto_iff_kuratowskiLimits_eq_singleton_of_eventuallyEq
    [T2Space X] (l : Filter ι) [NeBot l]
    {s : ι → Set X} {f : ι → X} {x : X}
    (hs : s =ᶠ[l] fun i => {f i}) :
    Tendsto f l (nhds x) ↔
      kuratowskiInnerLimit l s = {x} ∧
      kuratowskiOuterLimit l s = {x} := by
  have hInner := kuratowskiInnerLimit_congr_of_eventuallyEq hs
  have hOuter := kuratowskiOuterLimit_congr_of_eventuallyEq hs
  rw [hInner, hOuter]
  exact tendsto_iff_kuratowskiLimits_singleton l

end FilterSet

end MathlibAnalytic
end MGAP4D
