import MGAP4D.MathlibAnalytic.FilterKuratowskiInnerLimit
import MGAP4D.MathlibAnalytic.FilterKuratowskiOuterLimitSubnet
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open Filter Set Topology

universe u v

namespace FilterSet

variable {ι : Type u} {X : Type v} [TopologicalSpace X]

/-- Kuratowski inner limits are unchanged by eventual pointwise equality of
set-valued maps. -/
theorem kuratowskiInnerLimit_congr_of_eventuallyEq
    {l : Filter ι} {s t : ι → Set X} (hst : s =ᶠ[l] t) :
    kuratowskiInnerLimit l s = kuratowskiInnerLimit l t := by
  ext x
  constructor
  · intro hx U hU
    filter_upwards [hx U hU, hst] with i hi hEq
    rcases hi with ⟨y, hys, hyU⟩
    exact ⟨y, by simpa [hEq] using hys, hyU⟩
  · intro hx U hU
    filter_upwards [hx U hU, hst] with i hi hEq
    rcases hi with ⟨y, hyt, hyU⟩
    exact ⟨y, by simpa [hEq] using hyt, hyU⟩

/-- Kuratowski outer limits are unchanged by eventual pointwise equality of
set-valued maps. -/
theorem kuratowskiOuterLimit_congr_of_eventuallyEq
    {l : Filter ι} {s t : ι → Set X} (hst : s =ᶠ[l] t) :
    kuratowskiOuterLimit l s = kuratowskiOuterLimit l t := by
  rw [kuratowskiOuterLimit_eq_convergentSelectionOuterLimit,
    kuratowskiOuterLimit_eq_convergentSelectionOuterLimit]
  ext x
  constructor
  · rintro ⟨p, hp, hIndex, hPoint, hMem⟩
    refine ⟨p, hp, hIndex, hPoint, ?_⟩
    filter_upwards [hMem, hIndex.eventually hst] with z hz hEq
    simpa [hEq] using hz
  · rintro ⟨p, hp, hIndex, hPoint, hMem⟩
    refine ⟨p, hp, hIndex, hPoint, ?_⟩
    filter_upwards [hMem, hIndex.eventually hst] with z hz hEq
    simpa [hEq] using hz

/-- In a Hausdorff space, singleton sets generated by a convergent net have
both Kuratowski limits equal to the singleton limit point. -/
theorem kuratowskiLimits_singleton_of_tendsto
    [T2Space X] (l : Filter ι) [NeBot l] {f : ι → X} {x : X}
    (hf : Tendsto f l (nhds x)) :
    kuratowskiInnerLimit l (fun i => {f i}) = {x} ∧
      kuratowskiOuterLimit l (fun i => {f i}) = {x} := by
  have hxInner : x ∈ kuratowskiInnerLimit l (fun i => {f i}) :=
    mem_kuratowskiInnerLimit_of_tendsto_of_eventually_mem hf
      (Eventually.of_forall fun i => by simp)
  have hInnerOuter :=
    kuratowskiInnerLimit_subset_kuratowskiOuterLimit l (fun i => {f i})
  have hOuterSubset : kuratowskiOuterLimit l (fun i => {f i}) ⊆ {x} := by
    intro y hy
    rw [kuratowskiOuterLimit_eq_convergentSelectionOuterLimit] at hy
    rcases hy with ⟨p, hp, hIndex, hPoint, hMem⟩
    letI : NeBot p := hp
    have hFx : Tendsto (fun z : ι × X => f z.1) p (nhds x) :=
      hf.comp hIndex
    have hEq :
        (fun z : ι × X => f z.1) =ᶠ[p] (fun z : ι × X => z.2) := by
      filter_upwards [hMem] with z hz
      have hzEq : z.2 = f z.1 := by
        simpa only [Set.mem_singleton_iff] using hz
      exact hzEq.symm
    have hPointX : Tendsto (fun z : ι × X => z.2) p (nhds x) :=
      hFx.congr' hEq
    exact Set.mem_singleton_iff.2 (tendsto_nhds_unique hPoint hPointX)
  have hxOuter : x ∈ kuratowskiOuterLimit l (fun i => {f i}) :=
    hInnerOuter hxInner
  refine ⟨?_, ?_⟩
  · apply Set.Subset.antisymm
    · intro y hy
      exact hOuterSubset (hInnerOuter hy)
    · exact Set.singleton_subset_iff.2 hxInner
  · exact Set.Subset.antisymm hOuterSubset (Set.singleton_subset_iff.2 hxOuter)

end FilterSet

end MathlibAnalytic
end MGAP4D
