import MGAP4D.MathlibAnalytic.OrthonormalDiagonalHamiltonianSemigroupOperatorConstantInputWeakMatrixElementConvergenceFullGap
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapConstructedRealSpectralHamiltonianSemigroupOperatorConstantInputWeakMatrixElementConvergenceFullGap
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorConstantInputWeakMatrixElementConvergenceFullGap

namespace MGAP4D
namespace MathlibAnalytic

#check continuousLinearMap_tendsto_inner_sub_apply_zero_of_tendsto

#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_weakMatrixElement_tendsto_zero_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_weakMatrixElement_tendsto_zero_fullGap_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_weakMatrixElement_tendsto_zero_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_weakMatrixElement_tendsto_zero_fullGap_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_weakMatrixElement_tendsto_zero_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_weakMatrixElement_tendsto_zero_fullGap_right

end MathlibAnalytic
end MGAP4D
