import MGAP4D.MathlibAnalytic.FiniteLatticeWilsonCanonicalRandomScanVariationContraction

namespace MGAP4D
namespace MathlibAnalytic

#check finite_lattice_canonicalCenteredVariationProfile_variation
#check FiniteLatticeWilsonSystem.canonicalRandomScanHeatBathSweepVariationBound
#check finite_lattice_canonicalRandomScanHeatBathSweepVariationBound_variation
#check finite_lattice_canonical_randomScanHeatBathSweep_difference_abs_le
#check finite_lattice_canonical_randomScanHeatBathSweep_canonicalVariation_le_updatedVariation
#check finite_lattice_canonical_randomScanHeatBathSweep_totalVariation_le_rate_mul
#check finite_lattice_canonical_randomScanHeatBathSweep_actualTotalVariation_le_rate_mul

end MathlibAnalytic
end MGAP4D
