import MGAP4D.MathlibAnalytic.FiniteZ2TensorProductUniformPoincareTransfer
import MGAP4D.MathlibAnalytic.FiniteSurjectiveGroupHomFiberMultiplicity
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators InnerProduct

noncomputable section

/-- Pairing with the already-established constant-one boundary vector is the
ordinary finite coordinate sum. -/
theorem finiteBoundaryConstantOne_inner
    {α : Type} [Fintype α]
    (f : FiniteBoundaryHilbert α) :
    inner ℝ (finiteBoundaryConstantOne (α := α)) f =
      ∑ x : α, f x := by
  rw [PiLp.inner_apply]
  simp [finiteBoundaryConstantOne]

/-- The all-ones finite kernel is exactly the rank-one operator generated by
the constant-one vector. -/
theorem finiteKernelOperator_one_eq_rankOne
    {α : Type} [Fintype α] :
    finiteKernelOperator (fun _ _ : α => (1 : ℝ)) =
      ((InnerProductSpace.rankOne ℝ)
        (finiteBoundaryConstantOne (α := α)))
        (finiteBoundaryConstantOne (α := α)) := by
  apply ContinuousLinearMap.ext
  intro f
  ext y
  rw [finiteKernelOperator_apply, InnerProductSpace.rankOne_apply]
  change
    (∑ x : α, (1 : ℝ) * f x) =
      inner ℝ (finiteBoundaryConstantOne (α := α)) f * (1 : ℝ)
  rw [finiteBoundaryConstantOne_inner]
  simp

/-- Exact operator norm of the all-ones kernel on a finite Euclidean carrier. -/
theorem finiteKernelOperator_one_norm
    {α : Type} [Fintype α] :
    ‖finiteKernelOperator (fun _ _ : α => (1 : ℝ))‖ =
      (Fintype.card α : ℝ) := by
  rw [finiteKernelOperator_one_eq_rankOne, InnerProductSpace.norm_rankOne]
  rw [← real_inner_self_eq_norm_mul_norm]
  rw [finiteBoundaryConstantOne_inner]
  simp [finiteBoundaryConstantOne]

/-- Op-norm normalization of the all-ones kernel is the uniform averaging
operator. -/
theorem finiteKernelNormalizedOperator_one_apply
    {α : Type} [Fintype α]
    (f : FiniteBoundaryHilbert α)
    (y : α) :
    finiteKernelNormalizedOperator (fun _ _ : α => (1 : ℝ)) f y =
      (Fintype.card α : ℝ)⁻¹ * ∑ x : α, f x := by
  unfold finiteKernelNormalizedOperator
  rw [ContinuousLinearMap.smul_apply]
  change
    ‖finiteKernelOperator (fun _ _ : α => (1 : ℝ))‖⁻¹ *
        finiteKernelOperator (fun _ _ : α => (1 : ℝ)) f y =
      (Fintype.card α : ℝ)⁻¹ * ∑ x : α, f x
  rw [finiteKernelOperator_one_norm, finiteKernelOperator_apply]
  simp

/-- Summing a target coefficient after a surjective finite group homomorphism
introduces exactly the kernel cardinality. -/
theorem finiteSurjectiveGroupHom_sum_comp
    {G H : Type}
    [Group G]
    [Group H]
    [Fintype G]
    [Fintype H]
    (φ : G →* H)
    (hφ : Function.Surjective φ)
    (w : H → ℝ) :
    (∑ x : G, w (φ x)) =
      (Fintype.card φ.ker : ℝ) * ∑ y : H, w y := by
  classical
  let E := finiteSurjectiveGroupHomEquivKerProd φ hφ
  calc
    (∑ x : G, w (φ x)) =
        ∑ ky : φ.ker × H, w ky.2 := by
      exact Fintype.sum_equiv E _ _ (fun x => by rfl)
    _ = ∑ _k : φ.ker, ∑ y : H, w y := by
      rw [Fintype.sum_prod_type]
    _ = (Fintype.card φ.ker : ℝ) * ∑ y : H, w y := by
      simp

/-- Uniform finite averaging commutes exactly with pullback along every
surjective finite group homomorphism.  The fibre multiplicity cancels against
the total configuration cardinality. -/
theorem finiteSurjectiveGroupHom_uniformAverage_comp
    {G H : Type}
    [Group G]
    [Group H]
    [Fintype G]
    [Fintype H]
    (φ : G →* H)
    (hφ : Function.Surjective φ)
    (w : H → ℝ) :
    (Fintype.card G : ℝ)⁻¹ * (∑ x : G, w (φ x)) =
      (Fintype.card H : ℝ)⁻¹ * ∑ y : H, w y := by
  rw [finiteSurjectiveGroupHom_sum_comp φ hφ w]
  have hcardNat := finiteSurjectiveGroupHom_card_eq_card_ker_mul_card φ hφ
  have hcardReal :
      (Fintype.card G : ℝ) =
        (Fintype.card φ.ker : ℝ) * (Fintype.card H : ℝ) := by
    exact_mod_cast hcardNat
  have hker : (Fintype.card φ.ker : ℝ) ≠ 0 := by
    exact_mod_cast Fintype.card_ne_zero
  have hH : (Fintype.card H : ℝ) ≠ 0 := by
    exact_mod_cast Fintype.card_ne_zero
  rw [hcardReal]
  field_simp [hker, hH]

end

end MathlibAnalytic
end MGAP4D
