import MGAP4D.MathlibAnalytic.FiniteEvenFourTorusZ2CanonicalGaugeInstantiation
import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsExplicitCanonicalGaugeSingleLinkHeatBathSpine

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-!
Connect the concrete finite even-four-torus `Z₂` family directly to the
single-link heat-bath Poincare exact-gap continuum spine.
-/

section ConcreteHeatBath

variable
  (H : ℕ → ℕ)
  (β energyIdentity energyNontrivial latticeSpacing volumeScale : ℕ → ℝ)
  (hβ : ∀ n, 0 ≤ β n)
  (hEnergyIdentity : ∀ n, 0 ≤ energyIdentity n)
  (hEnergyNontrivial : ∀ n, 0 ≤ energyNontrivial n)
  (geometricEnergy : ∀ n,
    FiniteEvenFourTorusWilsonGeometricEnergyData
      (H n) (β n) (energyIdentity n) (energyNontrivial n)
      (hβ n) (hEnergyIdentity n) (hEnergyNontrivial n))
  (finiteVolumeEuclideanCovariant : Prop)
  (finiteVolumeEuclideanCovariant_proof : finiteVolumeEuclideanCovariant)

/-- The concrete single-link heat-bath datum generates the coercive datum for
the canonical `Z₂` even-four-torus realization. -/
noncomputable def finiteEvenFourTorusZ2CanonicalGaugeSingleLinkHeatBathCoerciveData
    (n : ℕ)
    (D : FiniteWilsonGibbsSingleSourceSingleLinkHeatBathOSLimitData
      (finiteEvenFourTorusZ2CanonicalGaugeRealization
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof n)) :
    FiniteWilsonGibbsSingleSourceCoerciveTransferOrbitOSLimitData
      (finiteEvenFourTorusZ2CanonicalGaugeRealization
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof n) :=
  finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathCoerciveData
    (finiteEvenFourTorusZ2AutomaticApproximationFamily
      H β energyIdentity energyNontrivial latticeSpacing volumeScale
      hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
      finiteVolumeEuclideanCovariant
      finiteVolumeEuclideanCovariant_proof)
    n D

/-- The concrete even-four-torus canonical interaction survives in the
continuum law generated by the single-link heat-bath Poincare assembly. -/
theorem finiteEvenFourTorusZ2CanonicalGauge_singleLinkHeatBath_interaction_passes_to_continuum
    (n : ℕ)
    (D : FiniteWilsonGibbsSingleSourceSingleLinkHeatBathOSLimitData
      (finiteEvenFourTorusZ2CanonicalGaugeRealization
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof n)) :
    finiteWilsonAutomaticContinuumCylinderConnectedCorrelation
        (finiteEvenFourTorusZ2CanonicalGaugeRealization
          H β energyIdentity energyNontrivial latticeSpacing volumeScale
          hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
          finiteVolumeEuclideanCovariant
          finiteVolumeEuclideanCovariant_proof n)
        (finiteWilsonExplicitCanonicalGaugeCoerciveAutomaticOSLimitData
          (finiteEvenFourTorusZ2AutomaticApproximationFamily
            H β energyIdentity energyNontrivial latticeSpacing volumeScale
            hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
            finiteVolumeEuclideanCovariant
            finiteVolumeEuclideanCovariant_proof)
          n
          (finiteEvenFourTorusZ2CanonicalGaugeSingleLinkHeatBathCoerciveData
            H β energyIdentity energyNontrivial latticeSpacing volumeScale
            hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
            finiteVolumeEuclideanCovariant
            finiteVolumeEuclideanCovariant_proof n D))
        (finiteEvenFourTorusZ2CanonicalGaugeInteractionWitness
          H β energyIdentity energyNontrivial latticeSpacing volumeScale
          hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
          finiteVolumeEuclideanCovariant
          finiteVolumeEuclideanCovariant_proof n).support
        (finiteEvenFourTorusZ2CanonicalGaugeInteractionWitness
          H β energyIdentity energyNontrivial latticeSpacing volumeScale
          hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
          finiteVolumeEuclideanCovariant
          finiteVolumeEuclideanCovariant_proof n).leftObservable
        (finiteEvenFourTorusZ2CanonicalGaugeInteractionWitness
          H β energyIdentity energyNontrivial latticeSpacing volumeScale
          hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
          finiteVolumeEuclideanCovariant
          finiteVolumeEuclideanCovariant_proof n).rightObservable ≠ 0 := by
  letI : Nonempty
      ((finiteEvenFourTorusZ2AutomaticApproximationFamily
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof).system n).Edge :=
    finiteEvenFourTorusZ2AutomaticApproximationFamily_edge_nonempty
      H β energyIdentity energyNontrivial latticeSpacing volumeScale
      hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
      finiteVolumeEuclideanCovariant
      finiteVolumeEuclideanCovariant_proof n
  exact
    finite_wilson_explicit_canonical_gauge_singleLinkHeatBath_interaction_passes_to_continuum
      (finiteEvenFourTorusZ2AutomaticApproximationFamily
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof)
      n D

/-- Single-link heat-bath data construct the reduced exact-gap continuum spine
for the concrete `Z₂` even-four-torus family. -/
noncomputable def finiteEvenFourTorusZ2CanonicalGaugeSingleLinkHeatBathExactGapConstructionSpine
    (n : ℕ)
    (D : FiniteWilsonGibbsSingleSourceSingleLinkHeatBathOSLimitData
      (finiteEvenFourTorusZ2CanonicalGaugeRealization
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof n))
    (measureBridge : EuclideanYangMillsMeasureToOSWightmanBridge)
    (measureBridge_identified :
      measureBridge.measure =
        (finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathContinuumConstruction
          (finiteEvenFourTorusZ2AutomaticApproximationFamily
            H β energyIdentity energyNontrivial latticeSpacing volumeScale
            hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
            finiteVolumeEuclideanCovariant
            finiteVolumeEuclideanCovariant_proof)
          n D).toMeasurePackage)
    (definitionBridge : OSWightmanExactGapDefinitionBridge)
    (definitionBridge_uses_measure_axioms :
      definitionBridge.spine.axioms = measureBridge.axioms) :
    EuclideanYangMillsContinuumMeasureExactGapConstructionSpine := by
  letI : Nonempty
      ((finiteEvenFourTorusZ2AutomaticApproximationFamily
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof).system n).Edge :=
    finiteEvenFourTorusZ2AutomaticApproximationFamily_edge_nonempty
      H β energyIdentity energyNontrivial latticeSpacing volumeScale
      hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
      finiteVolumeEuclideanCovariant
      finiteVolumeEuclideanCovariant_proof n
  exact
    finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathExactGapConstructionSpine
      (finiteEvenFourTorusZ2AutomaticApproximationFamily
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof)
      n D measureBridge measureBridge_identified definitionBridge
      definitionBridge_uses_measure_axioms

/-- The concrete even-four-torus single-link heat-bath construction reaches the
Hamiltonian mass-gap theorem and exact non-vacuum spectral threshold. -/
theorem finiteEvenFourTorusZ2CanonicalGauge_singleLinkHeatBath_mass_gap
    (n : ℕ)
    (D : FiniteWilsonGibbsSingleSourceSingleLinkHeatBathOSLimitData
      (finiteEvenFourTorusZ2CanonicalGaugeRealization
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof n))
    (measureBridge : EuclideanYangMillsMeasureToOSWightmanBridge)
    (measureBridge_identified :
      measureBridge.measure =
        (finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathContinuumConstruction
          (finiteEvenFourTorusZ2AutomaticApproximationFamily
            H β energyIdentity energyNontrivial latticeSpacing volumeScale
            hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
            finiteVolumeEuclideanCovariant
            finiteVolumeEuclideanCovariant_proof)
          n D).toMeasurePackage)
    (definitionBridge : OSWightmanExactGapDefinitionBridge)
    (definitionBridge_uses_measure_axioms :
      definitionBridge.spine.axioms = measureBridge.axioms) :
    let C :=
      (finiteEvenFourTorusZ2CanonicalGaugeSingleLinkHeatBathExactGapConstructionSpine
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof n D measureBridge
        measureBridge_identified definitionBridge
        definitionBridge_uses_measure_axioms).toConstructionSpine.toUnconditionalTarget
    C.toPipeline.definitionBridge.spine.model.hasMassGap ∧
      0 < exactGapValueReal ∧
      exactGapValueReal = sInf C.toPipeline.nonVacuumHamiltonianSpectrum := by
  letI : Nonempty
      ((finiteEvenFourTorusZ2AutomaticApproximationFamily
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof).system n).Edge :=
    finiteEvenFourTorusZ2AutomaticApproximationFamily_edge_nonempty
      H β energyIdentity energyNontrivial latticeSpacing volumeScale
      hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
      finiteVolumeEuclideanCovariant
      finiteVolumeEuclideanCovariant_proof n
  exact
    finite_wilson_explicit_canonical_gauge_singleLinkHeatBath_mass_gap
      (finiteEvenFourTorusZ2AutomaticApproximationFamily
        H β energyIdentity energyNontrivial latticeSpacing volumeScale
        hβ hEnergyIdentity hEnergyNontrivial geometricEnergy
        finiteVolumeEuclideanCovariant
        finiteVolumeEuclideanCovariant_proof)
      n D measureBridge measureBridge_identified definitionBridge
      definitionBridge_uses_measure_axioms

end ConcreteHeatBath

end

end MathlibAnalytic
end MGAP4D