import MGAP4D.MathlibAnalytic.FiniteOSGramKernelProductClosure

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators

noncomputable section

/-- Right multiplication by a fixed group element as an explicit equivalence. -/
def finiteGroupRightMulEquiv
    (G : Type) [Group G] (a : G) : G ≃ G where
  toFun := fun x => x * a
  invFun := fun x => x * a⁻¹
  left_inv := by
    intro x
    simp [mul_assoc]
  right_inv := by
    intro x
    simp [mul_assoc]

/-- Finite-group autocorrelation of a real function. -/
def finiteGroupAutocorrelation
    (G : Type) [Group G] [Fintype G]
    (ψ : G → ℝ) (g : G) : ℝ :=
  ∑ h : G, ψ h * ψ (h * g)

/-- The translation-invariant kernel associated with a finite-group
autocorrelation has an explicit Gram decomposition. -/
theorem finite_group_autocorrelation_kernel_decomposition
    (G : Type) [Group G] [Fintype G]
    (ψ : G → ℝ) (x y : G) :
    finiteGroupAutocorrelation G ψ (x⁻¹ * y) =
      ∑ h : G, (1 : ℝ) * ψ (h * x) * ψ (h * y) := by
  classical
  unfold finiteGroupAutocorrelation
  refine Fintype.sum_equiv (finiteGroupRightMulEquiv G x⁻¹) _ _ ?_
  intro h
  simp [finiteGroupRightMulEquiv, mul_assoc]

/-- The autocorrelation kernel `K(x,y)=w(x⁻¹y)` as a finite nonnegative Gram
kernel. -/
def finiteGroupAutocorrelationGramKernel
    (G : Type) [Group G] [Fintype G]
    (ψ : G → ℝ) :
    FiniteOSGramKernelOn G :=
  { Feature := G
    kernel := fun x y => finiteGroupAutocorrelation G ψ (x⁻¹ * y)
    coefficient := fun _ => 1
    coefficient_nonneg := fun _ => zero_le_one
    feature := fun h x => ψ (h * x)
    kernel_decomposition :=
      finite_group_autocorrelation_kernel_decomposition G ψ }

/-- Every finite-group autocorrelation kernel is OS reflection positive. -/
theorem finite_group_autocorrelation_reflectionPositive
    (G : Type) [Group G] [Fintype G]
    (ψ : G → ℝ) :
    FiniteOSReflectionPositive
      (finiteGroupAutocorrelationGramKernel G ψ).toCertificate :=
  finite_os_gram_certificate_reflectionPositive
    (finiteGroupAutocorrelationGramKernel G ψ).toCertificate

/-- A single-plaquette Boltzmann weight has a finite convolution-square
factorization when it is the autocorrelation of a real function. -/
def HasFiniteGroupPlaquetteConvolutionSquare
    (L : FiniteLatticeWilsonSystem) : Prop :=
  ∃ ψ : L.Gauge → ℝ,
    ∀ g : L.Gauge,
      Real.exp (-L.beta * L.plaquetteEnergy g) =
        finiteGroupAutocorrelation L.Gauge ψ g

/-- Choose a factorizing square root from a convolution-square certificate. -/
noncomputable def finiteGroupPlaquetteSquareRoot
    (L : FiniteLatticeWilsonSystem)
    (hSquare : HasFiniteGroupPlaquetteConvolutionSquare L) :
    L.Gauge → ℝ :=
  Classical.choose hSquare

/-- The chosen square root realizes the plaquette Boltzmann weight. -/
theorem finiteGroupPlaquetteSquareRoot_spec
    (L : FiniteLatticeWilsonSystem)
    (hSquare : HasFiniteGroupPlaquetteConvolutionSquare L)
    (g : L.Gauge) :
    Real.exp (-L.beta * L.plaquetteEnergy g) =
      finiteGroupAutocorrelation L.Gauge
        (finiteGroupPlaquetteSquareRoot L hSquare) g :=
  Classical.choose_spec hSquare g

/-- The single crossing-plaquette Wilson kernel generated by a convolution
square. -/
def finiteGroupSinglePlaquetteWilsonGramKernel
    (L : FiniteLatticeWilsonSystem)
    (hSquare : HasFiniteGroupPlaquetteConvolutionSquare L) :
    FiniteOSGramKernelOn L.Gauge :=
  { Feature := L.Gauge
    kernel := fun x y =>
      Real.exp (-L.beta * L.plaquetteEnergy (x⁻¹ * y))
    coefficient := fun _ => 1
    coefficient_nonneg := fun _ => zero_le_one
    feature := fun h x =>
      finiteGroupPlaquetteSquareRoot L hSquare (h * x)
    kernel_decomposition := by
      intro x y
      rw [finiteGroupPlaquetteSquareRoot_spec L hSquare]
      exact finite_group_autocorrelation_kernel_decomposition
        L.Gauge (finiteGroupPlaquetteSquareRoot L hSquare) x y }

/-- A finite-group single crossing plaquette is OS reflection positive whenever
its Boltzmann weight admits the displayed convolution-square factorization. -/
theorem finite_group_single_plaquette_wilson_reflectionPositive
    (L : FiniteLatticeWilsonSystem)
    (hSquare : HasFiniteGroupPlaquetteConvolutionSquare L) :
    FiniteOSReflectionPositive
      (finiteGroupSinglePlaquetteWilsonGramKernel L hSquare).toCertificate :=
  finite_os_gram_certificate_reflectionPositive
    (finiteGroupSinglePlaquetteWilsonGramKernel L hSquare).toCertificate

/-- A finite list of single-plaquette convolution-square kernels gives a
reflection-positive crossing kernel. -/
theorem finite_group_crossing_plaquette_list_reflectionPositive
    (L : FiniteLatticeWilsonSystem)
    (hSquares : List (HasFiniteGroupPlaquetteConvolutionSquare L)) :
    FiniteOSReflectionPositive
      (FiniteOSGramKernelOn.listProduct
        (hSquares.map fun hSquare =>
          finiteGroupSinglePlaquetteWilsonGramKernel L hSquare)).toCertificate :=
  finite_os_gram_kernel_listProduct_reflectionPositive _

/-- Including arbitrary same-side factors preserves the reflection positivity
of the finite product of crossing plaquettes. -/
theorem finite_group_wilson_crossing_with_halfspace_factor_reflectionPositive
    (L : FiniteLatticeWilsonSystem)
    (hSquares : List (HasFiniteGroupPlaquetteConvolutionSquare L))
    (a : L.Gauge → ℝ) :
    FiniteOSReflectionPositive
      ((FiniteOSGramKernelOn.listProduct
        (hSquares.map fun hSquare =>
          finiteGroupSinglePlaquetteWilsonGramKernel L hSquare)).sandwich a)
        .toCertificate :=
  finite_os_crossing_product_with_halfspace_factor_reflectionPositive _ a

end

end MathlibAnalytic
end MGAP4D
