import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorConstantInputMatrixElementSteadyStateDifferenceFullGapSettlingTime

namespace MGAP4D
namespace MathlibAnalytic

#check continuousLinearMap_abs_inner_apply_sub_inner_apply_eq_abs_inner_sub_apply
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_fullGap_right

end MathlibAnalytic
end MGAP4D
