import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsSingleSourceVacuumPoincareOSLimitAssembly

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

variable {W : FiniteWilsonOSAutomaticApproximationFamily}
  {F : EuclideanYangMillsProjectiveCylinderFamily}
  {L : EuclideanYangMillsProjectiveLimitMeasure F}
  (D : FiniteWilsonOSAutomaticVacuumPoincareAnalyticLimitConstructionData W F L)

noncomputable def finite_wilson_vacuum_poincare_os_data_compile_smoke :
    FiniteWilsonOSAutomaticVacuumOrthogonalDerivedInvarianceAnalyticLimitConstructionData W F L :=
  D.toVacuumOrthogonalDerivedInvarianceAnalyticData

theorem finite_wilson_vacuum_poincare_four_properties_compile_smoke :
    D.toVacuumOrthogonalDerivedInvarianceAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.reflectionLimit.ContinuumReflectionPositive ∧
      D.toVacuumOrthogonalDerivedInvarianceAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.euclideanLimit.toEuclideanInvarianceLimitData.ContinuumEuclideanInvariant ∧
      D.toVacuumOrthogonalDerivedInvarianceAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.clusterLimit.toClusterLimitData.ContinuumClusterProperty ∧
      D.toVacuumOrthogonalDerivedInvarianceAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.regularityLimit.toRegularityLimitData.ContinuumRegularity :=
  finite_wilson_os_vacuum_poincare_four_limit_properties D

theorem finite_wilson_vacuum_poincare_assembly_bound_compile_smoke
    (O : D.clusterPoincare.Observable) (r : ℕ) :
    ‖D.clusterPoincare.continuumConnectedCorrelation O r‖ ≤
      D.clusterPoincare.decayAmplitude O * exactGapClusterContractionRatio ^ r :=
  finite_wilson_os_vacuum_poincare_continuum_bound D O r

theorem finite_wilson_vacuum_poincare_package_ready_compile_smoke :
    D.toVacuumOrthogonalDerivedInvarianceAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.toProjectiveLimitTransferData.toContinuumConstruction.toMeasurePackage.ready :=
  finite_wilson_os_vacuum_poincare_measure_package_ready D

end

end MathlibAnalytic
end MGAP4D
