import MGAP4D.MathlibAnalytic.Z2PeriodicHypercubicOrientedFiniteHamiltonianGap
import MGAP4D.MathlibAnalytic.FiniteOrientedLatticeWilsonCanonicalDobrushinLocalMajorant

namespace MGAP4D
namespace MathlibAnalytic

#check finite_oriented_singleLinkConditionalPMF_eq_of_agreeOffLink
#check finite_oriented_canonicalDobrushinInfluence_eq_zero_of_not_mem_active
#check FiniteOrientedLatticeWilsonSystem.canonicalDobrushinRowSum
#check FiniteOrientedLatticeWilsonSystem.canonicalDobrushinCoefficient
#check finite_oriented_canonicalDobrushinCoefficient_lt_one_of_localMajorant
#check finite_oriented_targetLocalAction_sub_sourceReplace_eq_sum_shared
#check finite_oriented_canonicalDobrushinCoefficient_le_of_sharedPlaquetteEnergy
#check z2PeriodicHypercubicOriented_canonicalDobrushinCoefficient_le
#check z2PeriodicHypercubicOriented_canonicalDobrushinCoefficient_lt_one_of_beta_lt
#check finite_oriented_unsignedProxy_wilsonAction_eq
#check FiniteOrientedLatticeWilsonDobrushinMatrixData.toUnsignedProxy
#check finite_oriented_unsignedProxy_dobrushinScaled_hamiltonian_gap
#check z2PeriodicHypercubicOriented_heatBath_poincare
#check z2PeriodicHypercubicOriented_finiteHamiltonian_gap

end MathlibAnalytic
end MGAP4D
