import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsFiniteSupportExtraction

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-!
Derive pointwise separation from a concrete link-readout realization.

A finite Wilson configuration is a function from physical links to the gauge
carrier.  Suppose every physical link is assigned a Euclidean observation point
and the observation at that point admits a decoder recovering the corresponding
link variable.  Two unequal configurations then differ on one link, and the
associated observation point separates their global observations.
-/

/-- A global observation family which reads every physical Wilson link through
an assigned Euclidean point and a linkwise decoder. -/
structure FiniteWilsonGibbsLinkReadout
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (R : FiniteWilsonGibbsSingleSourceProjectiveRealization W) where
  linkPoint : (W.system R.sourceScale).Edge → EuclideanFourSpace
  decode :
    ∀ e : (W.system R.sourceScale).Edge,
      R.fieldValue (linkPoint e) → (W.system R.sourceScale).Gauge
  decode_globalObserve :
    ∀ (A : (W.system R.sourceScale).Configuration)
      (e : (W.system R.sourceScale).Edge),
      decode e (R.globalObserve A (linkPoint e)) = A e

/-- Unequal finite Wilson configurations differ on at least one physical link. -/
theorem finite_wilson_configuration_exists_link_ne
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    {A B : (W.system R.sourceScale).Configuration}
    (hAB : A ≠ B) :
    ∃ e : (W.system R.sourceScale).Edge, A e ≠ B e := by
  by_contra h
  apply hAB
  funext e
  by_contra he
  exact h ⟨e, he⟩

/-- A readable link whose values differ forces the corresponding global
observation coordinates to differ. -/
theorem FiniteWilsonGibbsLinkReadout.globalObserve_ne_at_linkPoint
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    (D : FiniteWilsonGibbsLinkReadout R)
    {A B : (W.system R.sourceScale).Configuration}
    (e : (W.system R.sourceScale).Edge)
    (he : A e ≠ B e) :
    R.globalObserve A (D.linkPoint e) ≠
      R.globalObserve B (D.linkPoint e) := by
  intro hObs
  apply he
  calc
    A e = D.decode e (R.globalObserve A (D.linkPoint e)) :=
      (D.decode_globalObserve A e).symm
    _ = D.decode e (R.globalObserve B (D.linkPoint e)) :=
      congrArg (D.decode e) hObs
    _ = B e := D.decode_globalObserve B e

/-- Concrete link readout proves pointwise separation of all unequal finite
Wilson configurations. -/
def FiniteWilsonGibbsLinkReadout.toGlobalPointSeparation
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    (D : FiniteWilsonGibbsLinkReadout R) :
    FiniteWilsonGibbsGlobalPointSeparation R where
  separates := by
    intro A B hAB
    obtain ⟨e, he⟩ := finite_wilson_configuration_exists_link_ne hAB
    exact ⟨D.linkPoint e, D.globalObserve_ne_at_linkPoint e he⟩

/-- Since the physical link type is finite, link readout canonically generates
one finite separating observation support. -/
noncomputable def FiniteWilsonGibbsLinkReadout.toFiniteCoordinateSelector
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    (D : FiniteWilsonGibbsLinkReadout R) :
    FiniteWilsonGibbsFiniteCoordinateSelector R :=
  D.toGlobalPointSeparation.toFiniteCoordinateSelector

/-- Link readout proves faithfulness of the complete global observation map. -/
def FiniteWilsonGibbsLinkReadout.toFaithfulGlobalObservation
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    (D : FiniteWilsonGibbsLinkReadout R) :
    FiniteWilsonGibbsFaithfulGlobalObservation R :=
  D.toGlobalPointSeparation.toFaithfulGlobalObservation

/-- A concrete readable finite-link observation generates the finite cylinder
interaction witness. -/
noncomputable def FiniteWilsonGibbsLinkReadout.toInteractionWitness
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    [Nontrivial (W.system R.sourceScale).Configuration]
    [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]
    (D : FiniteWilsonGibbsLinkReadout R) :
    FiniteWilsonGibbsCylinderInteractionWitness R :=
  D.toGlobalPointSeparation.toInteractionWitness

/-- The interaction witness generated by concrete link readout survives in the
continuum connected correlation. -/
theorem finite_wilson_link_readout_interaction_passes_to_continuum
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (R : FiniteWilsonGibbsSingleSourceProjectiveRealization W)
    [Nontrivial (W.system R.sourceScale).Configuration]
    [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]
    (L : FiniteWilsonGibbsSingleSourceExactGapOSLimitData R)
    (D : FiniteWilsonGibbsLinkReadout R) :
    finiteWilsonContinuumCylinderConnectedCorrelation R L
      D.toInteractionWitness.support
      D.toInteractionWitness.leftObservable
      D.toInteractionWitness.rightObservable ≠ 0 := by
  exact finite_wilson_global_point_separation_interaction_passes_to_continuum
    R L D.toGlobalPointSeparation

/-- Concrete link readout reaches the exact-threshold spectral endpoint. -/
theorem
    FiniteWilsonGibbsConcreteAnalyticFrontierCore.linkReadout_exactThresholdSeparation
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    [Nontrivial (W.system R.sourceScale).Configuration]
    [∀ x, Fintype (R.fieldValue x)]
    [∀ x, Countable (R.fieldValue x)]
    [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]
    (C : FiniteWilsonGibbsConcreteAnalyticFrontierCore R)
    (D : FiniteWilsonGibbsLinkReadout R) :
    euclideanYangMillsCompleteConstructionDirectBounded_exactThresholdSeparationProp
      (C.toExactGapConstructionSpineOfGlobalObservationSeparation
        D.toFiniteCoordinateSelector.toGlobalObservationSeparation).toConstructionSpine := by
  exact C.globalPointSeparation_exactThresholdSeparation
    D.toGlobalPointSeparation

end

end MathlibAnalytic
end MGAP4D
