import MGAP4D.MathlibAnalytic.LinearMarkovFinitePathCylinderMoment
import MGAP4D.MathlibAnalytic.FiniteWilsonRandomScanFinitePathPMF
import MGAP4D.MathlibAnalytic.FiniteWilsonRandomScanCylinderMoment
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators ENNReal

noncomputable section

/-- Product-cylinder expectation under the honest arbitrary finite Wilson
random-scan path PMF. -/
def FiniteLatticeWilsonSystem.randomScanFinitePathProductMoment
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (fs : Fin (n + 1) → L.Configuration → ℝ) : ℝ :=
  finitePMFExpectationReal
    (L.randomScanFinitePathPMF n)
    (linearMarkovFinitePathProduct fs)

/-- The transition expectation linear map generated by the actual finite Wilson
random-scan PMF is exactly the previously constructed heat-bath sweep linear
map. -/
theorem finite_lattice_randomScanTransitionExpectationLinearMap_eq
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge] :
    finitePMFTransitionExpectationLinearMap L.randomScanTransitionPMF =
      L.randomScanHeatBathSweepLinearMap := by
  ext f A
  change
    finitePMFExpectationReal (L.randomScanTransitionPMF A) f =
      L.randomScanHeatBathSweepLinearMap f A
  rw [finite_lattice_randomScanHeatBathSweepLinearMap_apply]
  exact finite_lattice_randomScanTransitionPMF_expectation L A f

/-- The honest finite Wilson path PMF and the previously constructed backward
random-scan cylinder recursion give exactly the same moment for every finite
product cylinder. -/
theorem finite_lattice_randomScanFinitePathProductMoment_eq_cylinderMoment
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (fs : Fin (n + 1) → L.Configuration → ℝ) :
    L.randomScanFinitePathProductMoment n fs =
      L.randomScanCylinderMoment (List.ofFn fs) := by
  rw [FiniteLatticeWilsonSystem.randomScanFinitePathProductMoment,
    FiniteLatticeWilsonSystem.randomScanFinitePathPMF]
  rw [linearMarkovFinitePathPMF_product_expectation_eq_cylinderMoment]
  rw [finite_lattice_randomScanTransitionExpectationLinearMap_eq L]
  unfold FiniteLatticeWilsonSystem.randomScanCylinderMoment
    linearMarkovCylinderMoment
  rw [finite_lattice_finitePMFExpectationReal_gibbsPMF]

/-- Consequently, appending an unobserved terminal coordinate to the honest
path-PMF product cylinder leaves its moment unchanged. -/
theorem finite_lattice_randomScanFinitePathProductMoment_succ_one
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (fs : Fin (n + 1) → L.Configuration → ℝ) :
    L.randomScanFinitePathProductMoment (n + 1)
        (Fin.snoc fs (fun _ : L.Configuration => (1 : ℝ))) =
      L.randomScanFinitePathProductMoment n fs := by
  rw [finite_lattice_randomScanFinitePathProductMoment_eq_cylinderMoment,
    finite_lattice_randomScanFinitePathProductMoment_eq_cylinderMoment]
  have hList :
      List.ofFn (Fin.snoc fs (fun _ : L.Configuration => (1 : ℝ))) =
        List.ofFn fs ++ [fun _ : L.Configuration => (1 : ℝ)] := by
    rw [List.ofFn_succ']
    simp
  rw [hList]
  exact finite_lattice_randomScanCylinderMoment_append_one L (List.ofFn fs)

end

end MathlibAnalytic
end MGAP4D
