import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsSingleSourceModeDiagonalFreePositiveInteractionOSLimitAssembly

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

variable {W : FiniteWilsonOSAutomaticApproximationFamily}
  {F : EuclideanYangMillsProjectiveCylinderFamily}
  {L : EuclideanYangMillsProjectiveLimitMeasure F}
  (D : FiniteWilsonOSAutomaticModeDiagonalFreePositiveInteractionAnalyticLimitConstructionData W F L)

noncomputable def finite_wilson_mode_diagonal_free_positive_analytic_data_compile_smoke :
    FiniteWilsonOSAutomaticFreePositiveInteractionAnalyticLimitConstructionData W F L :=
  D.toFreePositiveInteractionAnalyticData

theorem finite_wilson_mode_diagonal_free_positive_four_properties_compile_smoke :
    D.toFreePositiveInteractionAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.reflectionLimit.ContinuumReflectionPositive ∧
      D.toFreePositiveInteractionAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.euclideanLimit.toEuclideanInvarianceLimitData.ContinuumEuclideanInvariant ∧
      D.toFreePositiveInteractionAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.clusterLimit.toClusterLimitData.ContinuumClusterProperty ∧
      D.toFreePositiveInteractionAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.regularityLimit.toRegularityLimitData.ContinuumRegularity :=
  finite_wilson_os_mode_diagonal_free_positive_interaction_four_limit_properties D

theorem finite_wilson_mode_diagonal_free_positive_assembly_bound_compile_smoke
    (O : D.clusterModeDiagonalFreePositive.Observable) (r : ℕ) :
    ‖D.clusterModeDiagonalFreePositive.continuumConnectedCorrelation O r‖ ≤
      D.clusterModeDiagonalFreePositive.decayAmplitude O *
        exactGapClusterContractionRatio ^ r :=
  finite_wilson_os_mode_diagonal_free_positive_interaction_continuum_bound D O r

theorem finite_wilson_mode_diagonal_free_positive_package_ready_compile_smoke :
    D.toFreePositiveInteractionAnalyticData.toCoerciveTransferOrbitAnalyticData.toConstructedTransferOrbitAnalyticData.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.toProjectiveLimitTransferData.toContinuumConstruction.toMeasurePackage.ready :=
  finite_wilson_os_mode_diagonal_free_positive_interaction_continuum_measure_package_ready D

end

end MathlibAnalytic
end MGAP4D
