import MGAP4D.MathlibAnalytic.FiniteLatticeWilsonCanonicalCenteredVariation

namespace MGAP4D
namespace MathlibAnalytic

#check FiniteLatticeWilsonSystem.linkFiberRangeValues
#check finite_lattice_linkFiberRangeValues_nonempty
#check FiniteLatticeWilsonSystem.canonicalLinkVariation
#check finite_lattice_fiberObservableRange_le_canonicalLinkVariation
#check finite_lattice_canonicalLinkVariation_nonneg
#check finite_lattice_replaceLink_current
#check finite_lattice_replaceLink_of_agreeOffLink
#check finite_lattice_observable_difference_abs_le_canonicalLinkVariation
#check finite_lattice_fiberObservable_abs_sub_center_le_half_canonicalLinkVariation
#check FiniteLatticeWilsonSystem.canonicalCenteredVariationProfile

end MathlibAnalytic
end MGAP4D
