import MGAP4D.MathlibAnalytic.OrthonormalDiagonalHamiltonianSemigroupOperatorConstantInputPairwiseForwardUniquenessFullGap
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapConstructedRealSpectralHamiltonianSemigroupOperatorConstantInputPairwiseForwardUniquenessFullGap
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorConstantInputPairwiseForwardUniquenessFullGap

namespace MGAP4D
namespace MathlibAnalytic

#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_pairwise_exponentialContraction_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_pairwise_exponentialContraction_fullGap_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_eq_of_sameInitial_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_eq_of_sameInitial_fullGap_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_pairwise_exponentialContraction_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_pairwise_exponentialContraction_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_eq_of_sameInitial_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_eq_of_sameInitial_fullGap_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_pairwise_exponentialContraction_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_pairwise_exponentialContraction_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_eq_of_sameInitial_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_eq_of_sameInitial_fullGap_right

end MathlibAnalytic
end MGAP4D
