import MGAP4D.MathlibAnalytic.OrthonormalDiagonalHamiltonianSemigroupOperatorConstantInputFullGapAsymptoticConvergence
import MGAP4D.MathlibAnalytic.OrthonormalDiagonalHamiltonianSemigroupOperatorConstantInputFullGapEquilibriumForwardInvariance
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapConstructedRealSpectralHamiltonianSemigroupOperatorConstantInputFullGapAsymptoticConvergence
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapConstructedRealSpectralHamiltonianSemigroupOperatorConstantInputFullGapEquilibriumForwardInvariance
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorConstantInputFullGapAsymptoticConvergence
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorConstantInputFullGapEquilibriumForwardInvariance

namespace MGAP4D
namespace MathlibAnalytic

#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_tendsto_steadyState_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_tendsto_steadyState_fullGap_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_eq_steadyState_of_initial_eq_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_eq_steadyState_of_initial_eq_fullGap_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_tendsto_steadyState_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_tendsto_steadyState_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_eq_steadyState_of_initial_eq_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_eq_steadyState_of_initial_eq_fullGap_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_tendsto_steadyState_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_tendsto_steadyState_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_eq_steadyState_of_initial_eq_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_eq_steadyState_of_initial_eq_fullGap_right

end MathlibAnalytic
end MGAP4D
