import MGAP4D.MathlibAnalytic.FiniteGibbsExpectationBetaDerivative
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators

noncomputable section

namespace FiniteGibbsExpectationBetaDerivative

variable {Omega : Type*} [Fintype Omega] [Nonempty Omega]

/-- Covariance of two observables under a Gibbs law generated by a third,
fixed action. -/
def covarianceUnder
    (F G S : Omega -> Real) (beta : Real) : Real :=
  expectation (fun omega => F omega * G omega) S beta -
    expectation F S beta * expectation G S beta

/-- The derivative covariance is the special case where the second observable
is the Gibbs action itself. -/
theorem covariance_eq_covarianceUnder
    (F S : Omega -> Real) (beta : Real) :
    covariance F S beta = covarianceUnder F S S beta :=
  rfl

/-- Gibbs expectation preserves zero. -/
theorem expectation_zero
    (S : Omega -> Real) (beta : Real) :
    expectation (fun _ => 0) S beta = 0 := by
  simp [expectation, weightedSum]

/-- Gibbs expectation is additive in the observable. -/
theorem expectation_add
    (F G S : Omega -> Real) (beta : Real) :
    expectation (fun omega => F omega + G omega) S beta =
      expectation F S beta + expectation G S beta := by
  unfold expectation weightedSum
  rw [show
      (Finset.univ.sum fun omega : Omega =>
        (F omega + G omega) * boltzmannWeight S beta omega) =
      (Finset.univ.sum fun omega : Omega =>
        F omega * boltzmannWeight S beta omega) +
      (Finset.univ.sum fun omega : Omega =>
        G omega * boltzmannWeight S beta omega) by
        rw [<- Finset.sum_add_distrib]
        apply Finset.sum_congr rfl
        intro omega _homega
        ring]
  ring

/-- Gibbs expectation commutes with a finite sum of observables. -/
theorem expectation_finset_sum
    {I : Type*} (s : Finset I)
    (H : I -> Omega -> Real) (S : Omega -> Real) (beta : Real) :
    expectation (fun omega => Finset.sum s fun i => H i omega) S beta =
      Finset.sum s fun i => expectation (H i) S beta := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [expectation_zero]
  | @insert a s ha ih =>
      rw [show
          (fun omega => Finset.sum (insert a s) fun i => H i omega) =
          (fun omega => H a omega + Finset.sum s fun i => H i omega) by
            funext omega
            simp [ha]]
      rw [expectation_add, ih, Finset.sum_insert ha]

/-- Covariance under a fixed Gibbs action vanishes on the zero observable. -/
theorem covarianceUnder_zero_right
    (F S : Omega -> Real) (beta : Real) :
    covarianceUnder F (fun _ => 0) S beta = 0 := by
  simp [covarianceUnder, expectation_zero]

/-- Covariance is additive in its second observable when the Gibbs action is
held fixed. -/
theorem covarianceUnder_add_right
    (F G H S : Omega -> Real) (beta : Real) :
    covarianceUnder F (fun omega => G omega + H omega) S beta =
      covarianceUnder F G S beta + covarianceUnder F H S beta := by
  unfold covarianceUnder
  rw [show
      (fun omega => F omega * (G omega + H omega)) =
      (fun omega => F omega * G omega + F omega * H omega) by
        funext omega
        ring]
  rw [expectation_add, expectation_add]
  ring

/-- Covariance under a fixed Gibbs action commutes with finite sums in its
second observable. -/
theorem covarianceUnder_finset_sum_right
    {I : Type*} (s : Finset I)
    (F : Omega -> Real) (G : I -> Omega -> Real)
    (S : Omega -> Real) (beta : Real) :
    covarianceUnder F (fun omega => Finset.sum s fun i => G i omega) S beta =
      Finset.sum s fun i => covarianceUnder F (G i) S beta := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [covarianceUnder_zero_right]
  | @insert a s ha ih =>
      rw [show
          (fun omega => Finset.sum (insert a s) fun i => G i omega) =
          (fun omega => G a omega + Finset.sum s fun i => G i omega) by
            funext omega
            simp [ha]]
      rw [covarianceUnder_add_right, ih, Finset.sum_insert ha]

/-- If the Gibbs action is a finite sum of local terms, its derivative
covariance is the corresponding finite sum of local covariances. -/
theorem covariance_eq_finset_sum_covarianceUnder
    {I : Type*} (s : Finset I)
    (F S : Omega -> Real) (term : I -> Omega -> Real)
    (beta : Real)
    (hS : S = fun omega => Finset.sum s fun i => term i omega) :
    covariance F S beta =
      Finset.sum s fun i => covarianceUnder F (term i) S beta := by
  calc
    covariance F S beta = covarianceUnder F S S beta :=
      covariance_eq_covarianceUnder F S beta
    _ = covarianceUnder F
        (fun omega => Finset.sum s fun i => term i omega) S beta :=
      congrArg (fun G => covarianceUnder F G S beta) hS
    _ = Finset.sum s fun i => covarianceUnder F (term i) S beta :=
      covarianceUnder_finset_sum_right s F term S beta

/-- Absolute covariance with a finite-sum action is bounded by the sum of the
absolute local covariances. -/
theorem abs_covariance_le_sum_abs_covarianceUnder
    {I : Type*} (s : Finset I)
    (F S : Omega -> Real) (term : I -> Omega -> Real)
    (beta : Real)
    (hS : S = fun omega => Finset.sum s fun i => term i omega) :
    abs (covariance F S beta) <=
      Finset.sum s fun i => abs (covarianceUnder F (term i) S beta) := by
  classical
  rw [covariance_eq_finset_sum_covarianceUnder s F S term beta hS]
  clear hS
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      rw [Finset.sum_insert ha, Finset.sum_insert ha]
      calc
        abs (covarianceUnder F (term a) S beta +
            Finset.sum s fun i => covarianceUnder F (term i) S beta) <=
            abs (covarianceUnder F (term a) S beta) +
              abs (Finset.sum s fun i => covarianceUnder F (term i) S beta) :=
          abs_add_le _ _
        _ <= abs (covarianceUnder F (term a) S beta) +
              Finset.sum s fun i => abs (covarianceUnder F (term i) S beta) :=
          add_le_add (le_refl _) ih

end FiniteGibbsExpectationBetaDerivative

end

end MathlibAnalytic
end MGAP4D
