import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorConstantInputSteadyStateMatrixElementConvergenceFullGap

namespace MGAP4D
namespace MathlibAnalytic

#check continuousLinearMap_tendsto_inner_apply_of_tendsto
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_matrixElement_tendsto_steadyState_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_matrixElement_tendsto_steadyState_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_tendsto_steadyState_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_tendsto_steadyState_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_tendsto_steadyState_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_tendsto_steadyState_fullGap_right

end MathlibAnalytic
end MGAP4D
