import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsSingleSourceConstructedHamiltonianTransferOSLimitAssembly

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

variable {W : FiniteWilsonOSAutomaticApproximationFamily}
  {F : EuclideanYangMillsProjectiveCylinderFamily}
  {L : EuclideanYangMillsProjectiveLimitMeasure F}
  (D : FiniteWilsonOSAutomaticConstructedHamiltonianTransferAnalyticLimitConstructionData W F L)

noncomputable def finite_wilson_constructed_hamiltonian_analytic_data_compile_smoke :
    FiniteWilsonOSAutomaticHamiltonianEigenactionAnalyticLimitConstructionData W F L :=
  D.toHamiltonianEigenactionAnalyticData

theorem finite_wilson_constructed_hamiltonian_four_properties_compile_smoke :
    D.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.reflectionLimit.ContinuumReflectionPositive ∧
      D.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.euclideanLimit.toEuclideanInvarianceLimitData.ContinuumEuclideanInvariant ∧
      D.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.clusterLimit.toClusterLimitData.ContinuumClusterProperty ∧
      D.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.regularityLimit.toRegularityLimitData.ContinuumRegularity :=
  finite_wilson_os_constructed_hamiltonian_transfer_four_limit_properties D

theorem finite_wilson_constructed_hamiltonian_assembly_continuum_bound_compile_smoke
    (O : D.clusterConstructed.Observable) (r : ℕ) :
    ‖D.clusterConstructed.continuumConnectedCorrelation O r‖ ≤
      D.clusterConstructed.decayAmplitude O *
        exactGapClusterContractionRatio ^ r :=
  finite_wilson_os_constructed_hamiltonian_transfer_continuum_bound D O r

theorem finite_wilson_constructed_hamiltonian_package_ready_compile_smoke :
    D.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.toProjectiveLimitTransferData.toContinuumConstruction.toMeasurePackage.ready :=
  finite_wilson_os_constructed_hamiltonian_transfer_continuum_measure_package_ready D

end

end MathlibAnalytic
end MGAP4D
