import Mathlib.Analysis.InnerProductSpace.Spectrum
import MGAP4D.MathlibAnalytic.SymmetricEigenvalueLowerBound
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators InnerProduct

noncomputable section

/-- A finite-dimensional real symmetric operator that is positive in quadratic
form and contractive in norm.  This is the generic analytic input needed for
the nonzero spectral-support Hamiltonian construction. -/
structure FiniteDimensionalSymmetricPositiveContractionData
    (E : Type*)
    [NormedAddCommGroup E]
    [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] where
  operator : E →L[ℝ] E
  symmetric : operator.toLinearMap.IsSymmetric
  quadratic_nonneg : ∀ x : E, 0 ≤ inner ℝ (operator x) x
  norm_apply_le : ∀ x : E, ‖operator x‖ ≤ ‖x‖

namespace FiniteDimensionalSymmetricPositiveContractionData

variable
    {E : Type*}
    [NormedAddCommGroup E]
    [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E]

/-- The Mathlib spectral dimension of the finite transfer-state Hilbert space. -/
def dimension
    (D : FiniteDimensionalSymmetricPositiveContractionData E) : ℕ :=
  Module.finrank ℝ E

variable (D : FiniteDimensionalSymmetricPositiveContractionData E)

/-- The canonical Mathlib orthonormal eigenbasis of the symmetric transfer. -/
noncomputable def eigenbasis :
    OrthonormalBasis (Fin D.dimension) ℝ E :=
  D.symmetric.eigenvectorBasis (by rfl)

/-- The ordered real eigenvalues generated by Mathlib's finite-dimensional
spectral theorem. -/
noncomputable def eigenvalue (i : Fin D.dimension) : ℝ :=
  D.symmetric.eigenvalues (by rfl) i

/-- The canonical basis is orthonormal. -/
theorem eigenbasis_orthonormal :
    Orthonormal ℝ D.eigenbasis :=
  D.eigenbasis.orthonormal

/-- Every canonical basis vector is an eigenvector of the transfer. -/
theorem operator_apply_eigenbasis (i : Fin D.dimension) :
    D.operator (D.eigenbasis i) =
      D.eigenvalue i • D.eigenbasis i := by
  exact D.symmetric.apply_eigenvectorBasis (by rfl) i

/-- Positivity of the quadratic form forces every transfer eigenvalue to be
nonnegative. -/
theorem eigenvalue_nonneg (i : Fin D.dimension) :
    0 ≤ D.eigenvalue i := by
  apply symmetric_eigenvalue_ge_of_quadratic_form_lower_bound
    D.symmetric (by rfl) 0
  intro x
  simpa using D.quadratic_nonneg x

/-- Contractivity forces every nonnegative transfer eigenvalue to be at most
one. -/
theorem eigenvalue_le_one (i : Fin D.dimension) :
    D.eigenvalue i ≤ 1 := by
  have hcontract := D.norm_apply_le (D.eigenbasis i)
  have hbasis : ‖D.eigenbasis i‖ = 1 := by simp
  rw [D.operator_apply_eigenbasis i, norm_smul, hbasis, mul_one] at hcontract
  simpa [Real.norm_eq_abs, abs_of_nonneg (D.eigenvalue_nonneg i)] using hcontract

/-- Every finite transfer eigenvalue lies in the closed unit interval. -/
theorem eigenvalue_mem_unitInterval (i : Fin D.dimension) :
    D.eigenvalue i ∈ Set.Icc (0 : ℝ) 1 :=
  ⟨D.eigenvalue_nonneg i, D.eigenvalue_le_one i⟩

/-- The positive spectral support consists exactly of the nonzero eigenmodes
of the positive transfer. -/
def PositiveSpectralIndex : Type :=
  {i : Fin D.dimension // 0 < D.eigenvalue i}

noncomputable instance positiveSpectralIndexFintype :
    Fintype D.PositiveSpectralIndex := by
  classical
  infer_instance

noncomputable instance positiveSpectralIndexDecidableEq :
    DecidableEq D.PositiveSpectralIndex :=
  Classical.decEq _

/-- Euclidean Hilbert space of positive spectral coordinates. -/
abbrev PositiveSpectralSpace : Type :=
  EuclideanSpace ℝ D.PositiveSpectralIndex

/-- Transfer eigenvalue attached to a positive spectral coordinate. -/
def positiveEigenvalue (i : D.PositiveSpectralIndex) : ℝ :=
  D.eigenvalue i.1

/-- Every support eigenvalue is strictly positive. -/
theorem positiveEigenvalue_pos (i : D.PositiveSpectralIndex) :
    0 < D.positiveEigenvalue i :=
  i.2

/-- Every support eigenvalue remains at most one. -/
theorem positiveEigenvalue_le_one (i : D.PositiveSpectralIndex) :
    D.positiveEigenvalue i ≤ 1 :=
  D.eigenvalue_le_one i.1

/-- Diagonal transfer on the nonzero spectral support. -/
noncomputable def positiveSpectralTransfer :
    D.PositiveSpectralSpace →L[ℝ] D.PositiveSpectralSpace :=
  LinearMap.toContinuousLinearMap
    { toFun := fun x =>
        WithLp.toLp 2 (fun i => D.positiveEigenvalue i * x i)
      map_add' := by
        intro x y
        ext i
        simp [mul_add]
      map_smul' := by
        intro c x
        ext i
        change
          D.positiveEigenvalue i * (c * x i) =
            c * (D.positiveEigenvalue i * x i)
        ring }

@[simp] theorem positiveSpectralTransfer_apply
    (x : D.PositiveSpectralSpace)
    (i : D.PositiveSpectralIndex) :
    D.positiveSpectralTransfer x i =
      D.positiveEigenvalue i * x i := by
  rfl

/-- Natural-time powers of the positive-support transfer, written directly in
its diagonal spectral coordinates. -/
noncomputable def positiveSpectralSemigroup (n : ℕ) :
    D.PositiveSpectralSpace →L[ℝ] D.PositiveSpectralSpace :=
  LinearMap.toContinuousLinearMap
    { toFun := fun x =>
        WithLp.toLp 2 (fun i => (D.positiveEigenvalue i) ^ n * x i)
      map_add' := by
        intro x y
        ext i
        simp [mul_add]
      map_smul' := by
        intro c x
        ext i
        change
          (D.positiveEigenvalue i) ^ n * (c * x i) =
            c * ((D.positiveEigenvalue i) ^ n * x i)
        ring }

@[simp] theorem positiveSpectralSemigroup_apply
    (n : ℕ)
    (x : D.PositiveSpectralSpace)
    (i : D.PositiveSpectralIndex) :
    D.positiveSpectralSemigroup n x i =
      (D.positiveEigenvalue i) ^ n * x i := by
  rfl

/-- Zero natural time is the identity on the support space. -/
theorem positiveSpectralSemigroup_zero :
    D.positiveSpectralSemigroup 0 = 1 := by
  apply ContinuousLinearMap.ext
  intro x
  ext i
  simp

/-- One natural time step is the positive-support transfer. -/
theorem positiveSpectralSemigroup_one :
    D.positiveSpectralSemigroup 1 = D.positiveSpectralTransfer := by
  apply ContinuousLinearMap.ext
  intro x
  ext i
  simp

/-- Additive natural time is composition on the positive spectral support. -/
theorem positiveSpectralSemigroup_add (m n : ℕ) :
    D.positiveSpectralSemigroup (m + n) =
      (D.positiveSpectralSemigroup m).comp
        (D.positiveSpectralSemigroup n) := by
  apply ContinuousLinearMap.ext
  intro x
  ext i
  simp [pow_add, mul_assoc]

end FiniteDimensionalSymmetricPositiveContractionData

end

end MathlibAnalytic
end MGAP4D
