import MGAP4D.MathlibAnalytic.FiniteWilsonOSOneLayerTransferFormPackage
import Mathlib.Analysis.InnerProductSpace.Completion
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

namespace FiniteWilsonOSReflectionPositivityCertificate

variable {L : FiniteLatticeWilsonSystem}

/-- An opaque copy of the finite positive-half observable space.  The opaque
carrier prevents Mathlib from inheriting the ambient pointwise Euclidean norm:
its seminorm and inner product are instead generated by the Wilson OS kernel. -/
structure OneLayerCarrier
    (P : FiniteWilsonOSReflectionPositivityCertificate L) where
  observable : P.reflectionData.PositiveConfiguration → ℝ

protected def OneLayerCarrier.zero
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    P.OneLayerCarrier where
  observable := 0

protected def OneLayerCarrier.add
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (F G : P.OneLayerCarrier) : P.OneLayerCarrier where
  observable := F.observable + G.observable

protected def OneLayerCarrier.neg
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (F : P.OneLayerCarrier) : P.OneLayerCarrier where
  observable := -F.observable

protected def OneLayerCarrier.sub
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (F G : P.OneLayerCarrier) : P.OneLayerCarrier where
  observable := F.observable - G.observable

protected def OneLayerCarrier.nsmul
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (n : ℕ) (F : P.OneLayerCarrier) : P.OneLayerCarrier where
  observable := n • F.observable

protected def OneLayerCarrier.zsmul
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (n : ℤ) (F : P.OneLayerCarrier) : P.OneLayerCarrier where
  observable := n • F.observable

protected def OneLayerCarrier.smul
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (r : ℝ) (F : P.OneLayerCarrier) : P.OneLayerCarrier where
  observable := r • F.observable

/-- Observable projection is injective because the carrier has no additional
data beyond its positive-half observable. -/
theorem OneLayerCarrier.observable_injective
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    Function.Injective (@OneLayerCarrier.observable L P) := by
  intro F G h
  cases F
  cases G
  cases h
  rfl

instance oneLayerCarrierAddCommGroup
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    AddCommGroup P.OneLayerCarrier := by
  letI : Zero P.OneLayerCarrier := ⟨OneLayerCarrier.zero P⟩
  letI : Add P.OneLayerCarrier := ⟨OneLayerCarrier.add⟩
  letI : Neg P.OneLayerCarrier := ⟨OneLayerCarrier.neg⟩
  letI : Sub P.OneLayerCarrier := ⟨OneLayerCarrier.sub⟩
  letI : SMul ℕ P.OneLayerCarrier := ⟨OneLayerCarrier.nsmul⟩
  letI : SMul ℤ P.OneLayerCarrier := ⟨OneLayerCarrier.zsmul⟩
  refine Function.Injective.addCommGroup OneLayerCarrier.observable
    (OneLayerCarrier.observable_injective P) ?_ ?_ ?_ ?_ ?_ ?_
  · rfl
  · intro F G
    rfl
  · intro F
    rfl
  · intro F G
    rfl
  · intro F n
    rfl
  · intro F n
    rfl

instance oneLayerCarrierRealSMul
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    SMul ℝ P.OneLayerCarrier :=
  ⟨OneLayerCarrier.smul⟩

instance oneLayerCarrierModule
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    Module ℝ P.OneLayerCarrier := by
  refine Function.Injective.module ℝ
    ⟨⟨OneLayerCarrier.observable, ?_⟩, ?_⟩
    (OneLayerCarrier.observable_injective P) ?_
  · rfl
  · intro F G
    rfl
  · intro r F
    rfl

@[simp] theorem OneLayerCarrier.observable_zero
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    (0 : P.OneLayerCarrier).observable = 0 := rfl

@[simp] theorem OneLayerCarrier.observable_add
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (F G : P.OneLayerCarrier) :
    (F + G).observable = F.observable + G.observable := rfl

@[simp] theorem OneLayerCarrier.observable_neg
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (F : P.OneLayerCarrier) :
    (-F).observable = -F.observable := rfl

@[simp] theorem OneLayerCarrier.observable_sub
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (F G : P.OneLayerCarrier) :
    (F - G).observable = F.observable - G.observable := rfl

@[simp] theorem OneLayerCarrier.observable_nsmul
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (n : ℕ) (F : P.OneLayerCarrier) :
    (n • F).observable = n • F.observable := rfl

@[simp] theorem OneLayerCarrier.observable_zsmul
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (n : ℤ) (F : P.OneLayerCarrier) :
    (n • F).observable = n • F.observable := rfl

@[simp] theorem OneLayerCarrier.observable_smul
    {P : FiniteWilsonOSReflectionPositivityCertificate L}
    (r : ℝ) (F : P.OneLayerCarrier) :
    (r • F).observable = r • F.observable := rfl

/-- The Wilson one-layer positive semidefinite form as a Mathlib pre-inner-
product core. -/
@[reducible] noncomputable def oneLayerCore
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    PreInnerProductSpace.Core ℝ P.OneLayerCarrier where
  inner F G :=
    P.reflectionData.wilsonOneLayerTransferForm F.observable G.observable
  conj_inner_symm F G := by
    change
      P.reflectionData.wilsonOneLayerTransferForm G.observable F.observable =
        P.reflectionData.wilsonOneLayerTransferForm F.observable G.observable
    exact finite_lattice_wilson_os_oneLayerTransferForm_symmetric
      P.reflectionData G.observable F.observable
  re_inner_nonneg F :=
    finite_lattice_wilson_os_oneLayerTransferForm_nonneg
      P.reflectionData P.gramBridge F.observable
  add_left F G H := by
    change
      P.reflectionData.wilsonOneLayerTransferForm
          (F.observable + G.observable) H.observable =
        P.reflectionData.wilsonOneLayerTransferForm F.observable H.observable +
          P.reflectionData.wilsonOneLayerTransferForm G.observable H.observable
    exact finite_lattice_wilson_os_oneLayerTransferForm_add_left
      P.reflectionData F.observable G.observable H.observable
  smul_left F G r := by
    change
      P.reflectionData.wilsonOneLayerTransferForm
          (r • F.observable) G.observable =
        r * P.reflectionData.wilsonOneLayerTransferForm F.observable G.observable
    exact finite_lattice_wilson_os_oneLayerTransferForm_smul_left
      P.reflectionData r F.observable G.observable

noncomputable instance oneLayerCarrierSeminormedAddCommGroup
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    SeminormedAddCommGroup P.OneLayerCarrier :=
  InnerProductSpace.Core.toSeminormedAddCommGroup (c := P.oneLayerCore)

noncomputable instance oneLayerCarrierInnerProductSpace
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    InnerProductSpace ℝ P.OneLayerCarrier :=
  InnerProductSpace.ofCore P.oneLayerCore

/-- The carrier inner product is definitionally the geometric Wilson one-layer
OS form. -/
@[simp] theorem inner_eq_wilsonOneLayerTransferForm
    (P : FiniteWilsonOSReflectionPositivityCertificate L)
    (F G : P.OneLayerCarrier) :
    inner ℝ F G =
      P.reflectionData.wilsonOneLayerTransferForm F.observable G.observable := by
  rfl

/-- The OS-null vectors form a real linear subspace. -/
def oneLayerNullSubmodule
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    Submodule ℝ P.OneLayerCarrier where
  carrier := {F | ‖F‖ = 0}
  zero_mem' := norm_zero
  add_mem' := by
    intro F G hF hG
    apply le_antisymm
    · calc
        ‖F + G‖ ≤ ‖F‖ + ‖G‖ := norm_add_le F G
        _ = 0 := by rw [hF, hG]; simp
    · exact norm_nonneg _
  smul_mem' := by
    intro r F hF
    change ‖r • F‖ = 0
    rw [norm_smul, hF, mul_zero]

@[simp] theorem mem_oneLayerNullSubmodule
    (P : FiniteWilsonOSReflectionPositivityCertificate L)
    (F : P.OneLayerCarrier) :
    F ∈ P.oneLayerNullSubmodule ↔ ‖F‖ = 0 :=
  Iff.rfl

/-- Nullity is exactly vanishing of the Wilson one-layer quadratic form. -/
theorem mem_oneLayerNullSubmodule_iff_form_eq_zero
    (P : FiniteWilsonOSReflectionPositivityCertificate L)
    (F : P.OneLayerCarrier) :
    F ∈ P.oneLayerNullSubmodule ↔
      P.reflectionData.wilsonOneLayerTransferForm
        F.observable F.observable = 0 := by
  rw [P.mem_oneLayerNullSubmodule]
  constructor
  · intro hF
    calc
      P.reflectionData.wilsonOneLayerTransferForm
          F.observable F.observable = inner ℝ F F := by
            rw [P.inner_eq_wilsonOneLayerTransferForm]
      _ = ‖F‖ ^ 2 := real_inner_self_eq_norm_sq F
      _ = 0 := by rw [hF]; simp
  · intro hF
    have hsq : ‖F‖ ^ 2 = 0 := by
      rw [← real_inner_self_eq_norm_sq F,
        P.inner_eq_wilsonOneLayerTransferForm]
      exact hF
    exact sq_eq_zero_iff.mp hsq

/-- The separated finite Wilson one-layer OS pre-Hilbert carrier. -/
abbrev OneLayerSeparated
    (P : FiniteWilsonOSReflectionPositivityCertificate L) : Type :=
  SeparationQuotient P.OneLayerCarrier

/-- The completed finite Wilson geometric one-layer OS Hilbert carrier. -/
def OneLayerHilbert
    (P : FiniteWilsonOSReflectionPositivityCertificate L) : Type :=
  UniformSpace.Completion P.OneLayerSeparated

noncomputable instance oneLayerHilbertNormedAddCommGroup
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    NormedAddCommGroup P.OneLayerHilbert := by
  change NormedAddCommGroup (UniformSpace.Completion P.OneLayerSeparated)
  exact UniformSpace.Completion.instNormedAddCommGroup P.OneLayerSeparated

noncomputable instance oneLayerHilbertInnerProductSpace
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    InnerProductSpace ℝ P.OneLayerHilbert := by
  change InnerProductSpace ℝ (UniformSpace.Completion P.OneLayerSeparated)
  exact UniformSpace.Completion.innerProductSpace

noncomputable instance oneLayerHilbertCompleteSpace
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    CompleteSpace P.OneLayerHilbert := by
  change CompleteSpace (UniformSpace.Completion P.OneLayerSeparated)
  exact UniformSpace.Completion.completeSpace P.OneLayerSeparated

/-- The separated class of an opaque positive-half observable. -/
def oneLayerClass
    (P : FiniteWilsonOSReflectionPositivityCertificate L)
    (F : P.OneLayerCarrier) : P.OneLayerSeparated :=
  SeparationQuotient.mk F

/-- The dense completed Hilbert vector represented by an opaque observable. -/
def oneLayerState
    (P : FiniteWilsonOSReflectionPositivityCertificate L)
    (F : P.OneLayerCarrier) : P.OneLayerHilbert := by
  change UniformSpace.Completion P.OneLayerSeparated
  exact (P.oneLayerClass F : UniformSpace.Completion P.OneLayerSeparated)

/-- The separated quotient is dense in the completed geometric carrier. -/
theorem oneLayerSeparated_dense_in_hilbert
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    DenseRange
      (fun x : P.OneLayerSeparated =>
        (x : UniformSpace.Completion P.OneLayerSeparated)) :=
  UniformSpace.Completion.denseRange_coe

@[simp] theorem inner_oneLayerState_oneLayerState
    (P : FiniteWilsonOSReflectionPositivityCertificate L)
    (F G : P.OneLayerCarrier) :
    inner ℝ (P.oneLayerState F) (P.oneLayerState G) = inner ℝ F G := by
  change inner ℝ
      ((P.oneLayerClass F : UniformSpace.Completion P.OneLayerSeparated))
      ((P.oneLayerClass G : UniformSpace.Completion P.OneLayerSeparated)) =
    inner ℝ F G
  rw [UniformSpace.Completion.inner_coe]
  change inner ℝ (SeparationQuotient.mk F) (SeparationQuotient.mk G) =
    inner ℝ F G
  exact SeparationQuotient.inner_mk_mk F G

/-- Canonical linear projection to the separated one-layer OS quotient. -/
def oneLayerClassLinearMap
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    P.OneLayerCarrier →ₗ[ℝ] P.OneLayerSeparated where
  toFun := P.oneLayerClass
  map_add' := by
    intro F G
    exact SeparationQuotient.mk_add F G
  map_smul' := by
    intro r F
    exact SeparationQuotient.mk_smul r F

/-- Dense represented-state map from opaque observables to the completed
geometric OS Hilbert space. -/
noncomputable def oneLayerStateLinearMap
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    P.OneLayerCarrier →ₗ[ℝ] P.OneLayerHilbert := by
  change P.OneLayerCarrier →ₗ[ℝ]
    UniformSpace.Completion P.OneLayerSeparated
  exact
    (UniformSpace.Completion.toComplₗᵢ
      (𝕜 := ℝ) (E := P.OneLayerSeparated)).toLinearMap.comp
        P.oneLayerClassLinearMap

@[simp] theorem oneLayerStateLinearMap_apply
    (P : FiniteWilsonOSReflectionPositivityCertificate L)
    (F : P.OneLayerCarrier) :
    P.oneLayerStateLinearMap F = P.oneLayerState F := by
  change
    ((P.oneLayerClass F : P.OneLayerSeparated) :
      UniformSpace.Completion P.OneLayerSeparated) =
    ((P.oneLayerClass F : P.OneLayerSeparated) :
      UniformSpace.Completion P.OneLayerSeparated)
  rfl

/-- Opaque observables represent a dense linear family. -/
theorem oneLayerStateLinearMap_denseRange
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    DenseRange P.oneLayerStateLinearMap := by
  intro x
  exact closure_mono
    (by
      rintro y ⟨q, rfl⟩
      rcases SeparationQuotient.surjective_mk q with ⟨F, rfl⟩
      refine ⟨F, ?_⟩
      exact P.oneLayerStateLinearMap_apply F)
    (P.oneLayerSeparated_dense_in_hilbert x)

/-- Linear wrapping of raw positive-half functions into the opaque OS carrier. -/
def oneLayerCarrierOfObservableLinearMap
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    (P.reflectionData.PositiveConfiguration → ℝ) →ₗ[ℝ]
      P.OneLayerCarrier where
  toFun := fun F => ⟨F⟩
  map_add' := by
    intro F G
    rfl
  map_smul' := by
    intro r F
    rfl

/-- The completed raw-observable embedding used by geometric transfer matrix
elements. -/
noncomputable def oneLayerObservableEmbedding
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    (P.reflectionData.PositiveConfiguration → ℝ) →ₗ[ℝ]
      P.OneLayerHilbert :=
  P.oneLayerStateLinearMap.comp P.oneLayerCarrierOfObservableLinearMap

@[simp] theorem oneLayerObservableEmbedding_apply
    (P : FiniteWilsonOSReflectionPositivityCertificate L)
    (F : P.reflectionData.PositiveConfiguration → ℝ) :
    P.oneLayerObservableEmbedding F = P.oneLayerState ⟨F⟩ := by
  rfl

/-- Raw positive-half observables have dense image in the completed geometric
OS Hilbert carrier. -/
theorem oneLayerObservableEmbedding_denseRange
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    DenseRange P.oneLayerObservableEmbedding := by
  intro x
  exact closure_mono
    (by
      rintro y ⟨q, rfl⟩
      rcases SeparationQuotient.surjective_mk q with ⟨F, rfl⟩
      refine ⟨F.observable, ?_⟩
      rfl)
    (P.oneLayerSeparated_dense_in_hilbert x)

/-- The completed observable embedding reproduces the Wilson geometric
one-layer form exactly as its Hilbert inner product. -/
@[simp] theorem inner_oneLayerObservableEmbedding
    (P : FiniteWilsonOSReflectionPositivityCertificate L)
    (F G : P.reflectionData.PositiveConfiguration → ℝ) :
    inner ℝ (P.oneLayerObservableEmbedding F)
        (P.oneLayerObservableEmbedding G) =
      P.reflectionData.wilsonOneLayerTransferForm F G := by
  rw [P.oneLayerObservableEmbedding_apply,
    P.oneLayerObservableEmbedding_apply,
    P.inner_oneLayerState_oneLayerState,
    P.inner_eq_wilsonOneLayerTransferForm]

/-- Public completion receipt: quotienting the exact OS null space and then
completing gives a real Hilbert space with a dense observable embedding whose
inner product is the Wilson one-layer form. -/
theorem finiteWilsonOSOneLayerHilbertCompletionPackage
    (P : FiniteWilsonOSReflectionPositivityCertificate L) :
    DenseRange P.oneLayerObservableEmbedding ∧
      (∀ F G : P.reflectionData.PositiveConfiguration → ℝ,
        inner ℝ (P.oneLayerObservableEmbedding F)
            (P.oneLayerObservableEmbedding G) =
          P.reflectionData.wilsonOneLayerTransferForm F G) := by
  exact ⟨P.oneLayerObservableEmbedding_denseRange,
    P.inner_oneLayerObservableEmbedding⟩

end FiniteWilsonOSReflectionPositivityCertificate

end

end MathlibAnalytic
end MGAP4D
