import MGAP4D.MathlibAnalytic.FinitePositiveWeightCrossRatioInfluenceEntries
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- Canonical full-`L¹` influence generated by a nonnegative logarithmic
cross-ratio radius.  Analytically this is `2 * tanh (radius / 2)`, but the
exponential quotient is the normalization-stable form used by the finite
positive-weight API. -/
noncomputable def finitePositiveWeightCrossRatioInfluenceTransform
    (radius : ℝ) : ℝ :=
  2 * ((Real.exp radius - 1) / (Real.exp radius + 1))

@[simp] theorem finitePositiveWeightCrossRatioInfluenceTransform_zero :
    finitePositiveWeightCrossRatioInfluenceTransform 0 = 0 := by
  norm_num [finitePositiveWeightCrossRatioInfluenceTransform]

/-- The cross-ratio influence transform is nonnegative on nonnegative radii. -/
theorem finitePositiveWeightCrossRatioInfluenceTransform_nonneg
    (radius : ℝ)
    (hRadius : 0 ≤ radius) :
    0 ≤ finitePositiveWeightCrossRatioInfluenceTransform radius := by
  unfold finitePositiveWeightCrossRatioInfluenceTransform
  exact mul_nonneg (by norm_num)
    (expLikelihoodRatioTotalVariationBound_nonneg radius hRadius)

/-- Every finite logarithmic radius produces full-`L¹` influence strictly
below the trivial value two. -/
theorem finitePositiveWeightCrossRatioInfluenceTransform_lt_two
    (radius : ℝ) :
    finitePositiveWeightCrossRatioInfluenceTransform radius < 2 := by
  unfold finitePositiveWeightCrossRatioInfluenceTransform
  have h := expLikelihoodRatioTotalVariationBound_lt_one radius
  nlinarith

/-- Monotonicity of the radius-to-influence transform. -/
theorem finitePositiveWeightCrossRatioInfluenceTransform_mono
    {a b : ℝ}
    (hab : a ≤ b) :
    finitePositiveWeightCrossRatioInfluenceTransform a ≤
      finitePositiveWeightCrossRatioInfluenceTransform b := by
  have hExp : Real.exp a ≤ Real.exp b := Real.exp_le_exp.mpr hab
  have hDenA : 0 < Real.exp a + 1 := by positivity
  have hDenB : 0 < Real.exp b + 1 := by positivity
  have hFraction :
      (Real.exp a - 1) / (Real.exp a + 1) ≤
        (Real.exp b - 1) / (Real.exp b + 1) := by
    apply (div_le_div_iff₀ hDenA hDenB).2
    nlinarith
  unfold finitePositiveWeightCrossRatioInfluenceTransform
  nlinarith

/-- The influence transform is subadditive on nonnegative logarithmic radii.
This is the algebraic `tanh` addition inequality, proved directly in the
exponential quotient coordinates used by the repository. -/
theorem finitePositiveWeightCrossRatioInfluenceTransform_add_le
    (a b : ℝ)
    (ha : 0 ≤ a)
    (hb : 0 ≤ b) :
    finitePositiveWeightCrossRatioInfluenceTransform (a + b) ≤
      finitePositiveWeightCrossRatioInfluenceTransform a +
        finitePositiveWeightCrossRatioInfluenceTransform b := by
  let x : ℝ := Real.exp a
  let y : ℝ := Real.exp b
  have hx : 1 ≤ x := by
    simpa [x] using (Real.exp_le_exp.mpr ha)
  have hy : 1 ≤ y := by
    simpa [y] using (Real.exp_le_exp.mpr hb)
  have hxPos : 0 < x + 1 := by
    dsimp [x]
    positivity
  have hyPos : 0 < y + 1 := by
    dsimp [y]
    positivity
  have hxy : 1 ≤ x * y := by
    nlinarith [mul_nonneg (sub_nonneg.mpr hx) (sub_nonneg.mpr hy)]
  have hxyPos : 0 < x * y + 1 := by linarith
  have hNumerator :
      0 ≤ (x - 1) * (y - 1) * (x * y - 1) :=
    mul_nonneg
      (mul_nonneg (sub_nonneg.mpr hx) (sub_nonneg.mpr hy))
      (sub_nonneg.mpr hxy)
  have hDenominator :
      0 < (x + 1) * (y + 1) * (x * y + 1) :=
    mul_pos (mul_pos hxPos hyPos) hxyPos
  have hIdentity :
      (x - 1) / (x + 1) + (y - 1) / (y + 1) -
          (x * y - 1) / (x * y + 1) =
        ((x - 1) * (y - 1) * (x * y - 1)) /
          ((x + 1) * (y + 1) * (x * y + 1)) := by
    field_simp [ne_of_gt hxPos, ne_of_gt hyPos, ne_of_gt hxyPos]
    ring
  have hDifferenceNonneg :
      0 ≤
        (x - 1) / (x + 1) + (y - 1) / (y + 1) -
          (x * y - 1) / (x * y + 1) := by
    rw [hIdentity]
    exact div_nonneg hNumerator (le_of_lt hDenominator)
  unfold finitePositiveWeightCrossRatioInfluenceTransform
  rw [Real.exp_add]
  change
    2 * ((x * y - 1) / (x * y + 1)) ≤
      2 * ((x - 1) / (x + 1)) +
        2 * ((y - 1) / (y + 1))
  nlinarith

/-- Two equal nonnegative local radii contribute at most twice the one-factor
influence. -/
theorem finitePositiveWeightCrossRatioInfluenceTransform_two_mul_le
    (radius : ℝ)
    (hRadius : 0 ≤ radius) :
    finitePositiveWeightCrossRatioInfluenceTransform (2 * radius) ≤
      2 * finitePositiveWeightCrossRatioInfluenceTransform radius := by
  have h :=
    finitePositiveWeightCrossRatioInfluenceTransform_add_le
      radius radius hRadius hRadius
  convert h using 1 <;> ring

/-- Exact elementary form of the transform on a logarithmic residual
coefficient. -/
theorem finitePositiveWeightCrossRatioInfluenceTransform_log_one_add
    (x : ℝ)
    (hx : 0 ≤ x) :
    finitePositiveWeightCrossRatioInfluenceTransform (Real.log (1 + x)) =
      2 * (x / (x + 2)) := by
  have hPos : 0 < 1 + x := by linarith
  unfold finitePositiveWeightCrossRatioInfluenceTransform
  rw [Real.exp_log hPos]
  congr 1
  · ring
  · ring

/-- A logarithmic multiplicative residual contributes at most its underlying
nonnegative additive error.  This is the key linearization used to avoid a
volume multiplier in source-summed recursive rows. -/
theorem finitePositiveWeightCrossRatioInfluenceTransform_log_one_add_le
    (x : ℝ)
    (hx : 0 ≤ x) :
    finitePositiveWeightCrossRatioInfluenceTransform (Real.log (1 + x)) ≤ x := by
  rw [finitePositiveWeightCrossRatioInfluenceTransform_log_one_add x hx]
  have hDen : 0 < x + 2 := by linarith
  rw [← mul_div_assoc]
  apply (div_le_iff₀ hDen).2
  nlinarith [sq_nonneg x]

/-- Entrywise influence is exactly the transform of the declared radius away
from the diagonal. -/
theorem finitePositiveWeightCrossRatioEntryInfluence_eq_transform
    {ι G : Type}
    [DecidableEq ι]
    [Fintype ι]
    [Fintype G]
    {weight : (ι → G) → ℝ}
    (D : FinitePositiveWeightCrossRatioInfluenceEntryData weight)
    (target source : ι) :
    finitePositiveWeightCrossRatioEntryInfluence D target source =
      if target = source then 0 else
        finitePositiveWeightCrossRatioInfluenceTransform
          (D.radius target source) := by
  rfl

end

end MathlibAnalytic
end MGAP4D
