import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapClusterRate

namespace MGAP4D
namespace MathlibAnalytic

open Filter

noncomputable section

/-- Finite Wilson connected correlations controlled by an initial estimate and
one exact-gap contraction step.

This is strictly weaker input than an all-distance geometric bound: the latter
is generated by induction. -/
structure FiniteWilsonOSAutomaticExactGapStepContractionData
    (W : FiniteWilsonOSAutomaticApproximationFamily) where
  Observable : Type
  scale : ℕ → W.index
  leftObservable :
    (n : ℕ) → Observable → (W.system (scale n)).Configuration → ℝ
  rightObservable :
    (n : ℕ) → Observable → ℕ → (W.system (scale n)).Configuration → ℝ
  continuumConnectedCorrelation : Observable → ℕ → ℝ
  decayAmplitude : Observable → ℝ
  decayAmplitude_nonneg : ∀ O : Observable, 0 ≤ decayAmplitude O
  pointwiseConvergence :
    ∀ (O : Observable) (r : ℕ),
      Tendsto
        (fun n : ℕ =>
          (W.system (scale n)).gibbsConnectedCorrelation
            (leftObservable n O) (rightObservable n O r))
        atTop (nhds (continuumConnectedCorrelation O r))
  initialBound :
    ∀ (n : ℕ) (O : Observable),
      ‖(W.system (scale n)).gibbsConnectedCorrelation
          (leftObservable n O) (rightObservable n O 0)‖ ≤
        decayAmplitude O
  oneStepContraction :
    ∀ (n : ℕ) (O : Observable) (r : ℕ),
      ‖(W.system (scale n)).gibbsConnectedCorrelation
          (leftObservable n O) (rightObservable n O (Nat.succ r))‖ ≤
        exactGapClusterContractionRatio *
          ‖(W.system (scale n)).gibbsConnectedCorrelation
            (leftObservable n O) (rightObservable n O r)‖

/-- Iterating the one-step contraction gives the full exact-gap geometric
finite-volume estimate. -/
theorem finite_wilson_exact_gap_bound_of_step_contraction
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapStepContractionData W)
    (n : ℕ) (O : D.Observable) (r : ℕ) :
    ‖(W.system (D.scale n)).gibbsConnectedCorrelation
        (D.leftObservable n O) (D.rightObservable n O r)‖ ≤
      D.decayAmplitude O * exactGapClusterContractionRatio ^ r := by
  induction r with
  | zero =>
      simpa using D.initialBound n O
  | succ r ihr =>
      calc
        ‖(W.system (D.scale n)).gibbsConnectedCorrelation
            (D.leftObservable n O) (D.rightObservable n O (Nat.succ r))‖ ≤
            exactGapClusterContractionRatio *
              ‖(W.system (D.scale n)).gibbsConnectedCorrelation
                (D.leftObservable n O) (D.rightObservable n O r)‖ :=
          D.oneStepContraction n O r
        _ ≤ exactGapClusterContractionRatio *
              (D.decayAmplitude O * exactGapClusterContractionRatio ^ r) :=
          mul_le_mul_of_nonneg_left ihr
            exact_gap_cluster_contraction_ratio_nonneg
        _ = D.decayAmplitude O *
              exactGapClusterContractionRatio ^ Nat.succ r := by
          rw [pow_succ]
          ring

/-- Convert initial and one-step estimates into the exact-gap cluster package. -/
noncomputable def
    FiniteWilsonOSAutomaticExactGapStepContractionData.toExactGapClusterData
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapStepContractionData W) :
    FiniteWilsonOSAutomaticExactGapClusterData W :=
  { Observable := D.Observable
    scale := D.scale
    leftObservable := D.leftObservable
    rightObservable := D.rightObservable
    continuumConnectedCorrelation := D.continuumConnectedCorrelation
    decayAmplitude := D.decayAmplitude
    decayAmplitude_nonneg := D.decayAmplitude_nonneg
    pointwiseConvergence := D.pointwiseConvergence
    uniformExactGapBound :=
      finite_wilson_exact_gap_bound_of_step_contraction D }

/-- Initial control plus one-step exact-gap contraction implies continuum
clustering. -/
theorem finite_wilson_exact_gap_step_contraction_passes_to_limit
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapStepContractionData W) :
    D.toExactGapClusterData.toUniformGeometricClusterData.toClusterLimitData.toClusterLimitData.ContinuumClusterProperty :=
  finite_wilson_exact_gap_cluster_passes_to_limit D.toExactGapClusterData

/-- The continuum connected correlation inherits the iterated exact-gap bound. -/
theorem finite_wilson_exact_gap_step_contraction_continuum_bound
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapStepContractionData W)
    (O : D.Observable) (r : ℕ) :
    ‖D.continuumConnectedCorrelation O r‖ ≤
      D.decayAmplitude O * exactGapClusterContractionRatio ^ r :=
  finite_wilson_exact_gap_cluster_continuum_bound
    D.toExactGapClusterData O r

end

end MathlibAnalytic
end MGAP4D
