import MGAP4D.MathlibAnalytic.FiniteLatticeWilsonCanonicalCenteredVariationProfile

namespace MGAP4D
namespace MathlibAnalytic

#check FiniteLatticeWilsonSystem.fiberObservableRanges
#check finite_lattice_fiberObservableRanges_nonempty
#check FiniteLatticeWilsonSystem.canonicalLinkVariation
#check finite_lattice_fiberObservableRange_le_canonicalLinkVariation
#check finite_lattice_canonicalLinkVariation_nonneg
#check finite_lattice_replaceLink_current
#check finite_lattice_replaceLink_right_of_agreeOffLink
#check finite_lattice_canonicalLinkVariation_difference_abs_le
#check finite_lattice_fiberObservable_abs_sub_center_le_half_canonicalVariation
#check FiniteLatticeWilsonSystem.canonicalCenteredVariationProfile

end MathlibAnalytic
end MGAP4D
