import MGAP4D.MathlibAnalytic.FiniteLatticeWilsonActionLocalDecomposition
import MGAP4D.MathlibAnalytic.FiniteLatticeWilsonConditionalPlaquetteSupport
import MGAP4D.MathlibAnalytic.FiniteLatticeWilsonExactPlaquetteDobrushinProfile
import MGAP4D.MathlibAnalytic.FiniteWilsonExactPlaquetteDobrushinFamilyGap
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapExactPlaquetteTransferOrbitContraction

namespace MGAP4D
namespace MathlibAnalytic

#check FiniteLatticeWilsonSystem.targetRemotePlaquetteAction
#check finite_lattice_wilsonAction_eq_targetLocal_add_targetRemote
#check finite_lattice_targetRemotePlaquetteAction_replaceLink
#check finite_lattice_wilsonAction_replaceLink_eq_local_add_remote
#check finite_lattice_singleLinkConditionalPMF_eq_targetLocal
#check finite_lattice_singleLinkConditionalPMF_eq_of_not_plaquetteNeighbor
#check finite_lattice_singleLinkConditionalTotalVariation_eq_zero_of_not_plaquetteNeighbor
#check finite_lattice_canonicalDobrushinInfluence_eq_zero_of_not_plaquetteNeighbor
#check FiniteLatticeWilsonSystem.canonicalPlaquetteDegree
#check FiniteLatticeWilsonSystem.canonicalPlaquetteLocalInfluenceBound
#check finite_lattice_canonicalDobrushinCoefficient_le_exactPlaquetteProduct
#check finite_lattice_canonicalDobrushinCoefficient_lt_one_of_exactPlaquetteProfile
#check FiniteWilsonExactPlaquetteDobrushinFamilyData
#check finite_wilson_exact_plaquette_dobrushin_family_hamiltonian_gap
#check finite_wilson_exact_gap_bound_of_exact_plaquette_profile
#check finite_wilson_exact_gap_exact_plaquette_continuum_bound

end MathlibAnalytic
end MGAP4D
