import MGAP4D.MathlibAnalytic.OrthonormalDiagonalHamiltonianSemigroupOperatorConstantInputExponentialTrackingEnvelopeFullGapSettlingTime
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapConstructedRealSpectralHamiltonianSemigroupOperatorConstantInputExponentialTrackingEnvelopeFullGapSettlingTime
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorConstantInputExponentialTrackingEnvelopeFullGapSettlingTime

open MGAP4D MathlibAnalytic

#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_exponentialTrackingEnvelope_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_exponentialTrackingEnvelope_fullGap_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_norm_sub_le_epsilon_after_exponentialTrackingEnvelope_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_norm_sub_le_epsilon_after_exponentialTrackingEnvelope_fullGap_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_exponentialTrackingEnvelope_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_exponentialTrackingEnvelope_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_norm_sub_le_epsilon_after_exponentialTrackingEnvelope_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_norm_sub_le_epsilon_after_exponentialTrackingEnvelope_fullGap_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_exponentialTrackingEnvelope_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_exponentialTrackingEnvelope_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_norm_sub_le_epsilon_after_exponentialTrackingEnvelope_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_norm_sub_le_epsilon_after_exponentialTrackingEnvelope_fullGap_right
