import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorDuhamelZeroInputNormConvergence

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_norm_zero_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_norm_zero_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_norm_zero_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_norm_zero_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_norm_zero_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_norm_zero_right

end

end MathlibAnalytic
end MGAP4D
