import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsSingleSourceCountableSkeletonOSPropertyTransfer
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticReflectionLimitTransfer

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory

noncomputable section

/-- The projective-limit analytic transfer package with the reflection-limit
component removed.

This separates the three still model-dependent analytic inputs—Euclidean
invariance, clustering, and regularity—from reflection positivity.  A concrete
finite Wilson reflection sequence can then supply the missing component without
re-assuming finite-volume positivity. -/
structure EuclideanYangMillsProjectiveLimitAnalyticTransferCore
    (F : EuclideanYangMillsProjectiveCylinderFamily)
    (L : EuclideanYangMillsProjectiveLimitMeasure F) where
  gaugeGroup : Type
  [gaugeGroupGroup : Group gaugeGroup]
  [gaugeGroupTopology : TopologicalSpace gaugeGroup]
  [gaugeGroupCompact : CompactSpace gaugeGroup]
  [gaugeGroupNontrivial : Nontrivial gaugeGroup]
  [gaugeAction : MulAction gaugeGroup F.Configuration]
  gaugeActionMeasurable :
    ∀ g : gaugeGroup, Measurable (fun A : F.Configuration => g • A)
  gaugeInvariant :
    ∀ g : gaugeGroup,
      L.continuumMeasure.map (fun A : F.Configuration => g • A) =
        L.continuumMeasure
  fieldAlgebra : Type
  schwingerFunctions : ℕ → Type
  euclideanLimit : EuclideanYangMillsEuclideanInvarianceLimitData
  symmetric : Prop
  symmetric_proof : symmetric
  clusterLimit : EuclideanYangMillsClusterLimitData
  regularityLimit : EuclideanYangMillsRegularityLimitData

attribute [instance]
  EuclideanYangMillsProjectiveLimitAnalyticTransferCore.gaugeGroupGroup
  EuclideanYangMillsProjectiveLimitAnalyticTransferCore.gaugeGroupTopology
  EuclideanYangMillsProjectiveLimitAnalyticTransferCore.gaugeGroupCompact
  EuclideanYangMillsProjectiveLimitAnalyticTransferCore.gaugeGroupNontrivial
  EuclideanYangMillsProjectiveLimitAnalyticTransferCore.gaugeAction

/-- Insert a reflection-limit datum into the remaining projective-limit
analytic data. -/
noncomputable def
    EuclideanYangMillsProjectiveLimitAnalyticTransferCore.withReflectionLimit
    {F : EuclideanYangMillsProjectiveCylinderFamily}
    {L : EuclideanYangMillsProjectiveLimitMeasure F}
    (C : EuclideanYangMillsProjectiveLimitAnalyticTransferCore F L)
    (D : EuclideanYangMillsReflectionPositivityLimitData) :
    EuclideanYangMillsProjectiveLimitAnalyticTransferData F L :=
  { gaugeGroup := C.gaugeGroup
    gaugeGroupGroup := C.gaugeGroupGroup
    gaugeGroupTopology := C.gaugeGroupTopology
    gaugeGroupCompact := C.gaugeGroupCompact
    gaugeGroupNontrivial := C.gaugeGroupNontrivial
    gaugeAction := C.gaugeAction
    gaugeActionMeasurable := C.gaugeActionMeasurable
    gaugeInvariant := C.gaugeInvariant
    fieldAlgebra := C.fieldAlgebra
    schwingerFunctions := C.schwingerFunctions
    reflectionLimit := D
    euclideanLimit := C.euclideanLimit
    symmetric := C.symmetric
    symmetric_proof := C.symmetric_proof
    clusterLimit := C.clusterLimit
    regularityLimit := C.regularityLimit }

@[simp] theorem
    EuclideanYangMillsProjectiveLimitAnalyticTransferCore.withReflectionLimit_reflectionLimit
    {F : EuclideanYangMillsProjectiveCylinderFamily}
    {L : EuclideanYangMillsProjectiveLimitMeasure F}
    (C : EuclideanYangMillsProjectiveLimitAnalyticTransferCore F L)
    (D : EuclideanYangMillsReflectionPositivityLimitData) :
    (C.withReflectionLimit D).reflectionLimit = D := by
  rfl

/-- Complete a projective-limit analytic transfer package using actual finite
Wilson reflection forms.  Finite reflection positivity is generated by the
Wilson Gram/character certificate; only convergence of the forms is supplied
by `D`. -/
noncomputable def
    EuclideanYangMillsProjectiveLimitAnalyticTransferCore.withAutomaticWilsonReflection
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {F : EuclideanYangMillsProjectiveCylinderFamily}
    {L : EuclideanYangMillsProjectiveLimitMeasure F}
    (C : EuclideanYangMillsProjectiveLimitAnalyticTransferCore F L)
    (D : FiniteWilsonOSAutomaticReflectionLimitData W) :
    EuclideanYangMillsProjectiveLimitAnalyticTransferData F L :=
  C.withReflectionLimit D.toReflectionPositivityLimitData

/-- The inserted Wilson reflection component is continuum reflection positive
by the finite Gram theorem and pointwise convergence. -/
theorem
    EuclideanYangMillsProjectiveLimitAnalyticTransferCore.automaticWilsonReflectionPositive
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {F : EuclideanYangMillsProjectiveCylinderFamily}
    {L : EuclideanYangMillsProjectiveLimitMeasure F}
    (C : EuclideanYangMillsProjectiveLimitAnalyticTransferCore F L)
    (D : FiniteWilsonOSAutomaticReflectionLimitData W) :
    (C.withAutomaticWilsonReflection D).reflectionLimit.
      ContinuumReflectionPositive := by
  change D.toReflectionPositivityLimitData.ContinuumReflectionPositive
  exact euclidean_yang_mills_reflection_positivity_passes_to_limit
    D.toReflectionPositivityLimitData

variable {W : FiniteWilsonOSAutomaticApproximationFamily}
  (R : FiniteWilsonGibbsSingleSourceProjectiveRealization W)
  [∀ x, Fintype (R.fieldValue x)]
  [∀ x, Countable (R.fieldValue x)]
  [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]

/-- All projective-limit analytic inputs for the explicit Wilson law except the
reflection-limit component. -/
abbrev FiniteWilsonGibbsSingleSourceRemainingOSAnalyticTransferData :=
  EuclideanYangMillsProjectiveLimitAnalyticTransferCore
    R.toProjectiveRealization.toProjectiveCylinderFamily
    R.projectiveLimitMeasure

/-- Assemble the complete Wilson projective-limit transfer package by inserting
an automatic finite-Wilson reflection-limit datum into the remaining analytic
inputs. -/
noncomputable def
    FiniteWilsonGibbsSingleSourceProjectiveRealization.osAnalyticTransferDataOfAutomaticReflection
    (C : FiniteWilsonGibbsSingleSourceRemainingOSAnalyticTransferData R)
    (D : FiniteWilsonOSAutomaticReflectionLimitData W) :
    FiniteWilsonGibbsSingleSourceOSPropertyTransferData R :=
  C.withAutomaticWilsonReflection D

@[simp] theorem finite_wilson_single_source_automatic_transfer_reflectionLimit
    (C : FiniteWilsonGibbsSingleSourceRemainingOSAnalyticTransferData R)
    (D : FiniteWilsonOSAutomaticReflectionLimitData W) :
    (R.osAnalyticTransferDataOfAutomaticReflection C D).reflectionLimit =
      D.toReflectionPositivityLimitData := by
  rfl

/-- The explicit common-source Wilson construction is OS/Wightman-ready once
Euclidean invariance, symmetry, clustering, and regularity data are supplied;
reflection positivity is generated from the finite Wilson sequence. -/
theorem finite_wilson_single_source_explicit_os_ready_of_automatic_reflection
    (C : FiniteWilsonGibbsSingleSourceRemainingOSAnalyticTransferData R)
    (D : FiniteWilsonOSAutomaticReflectionLimitData W) :
    (R.explicitOSContinuumConstruction
      (R.osAnalyticTransferDataOfAutomaticReflection C D)).toMeasurePackage.ready :=
  finite_wilson_single_source_explicit_os_ready R
    (R.osAnalyticTransferDataOfAutomaticReflection C D)

variable {κ : Type*} [Countable κ] [Nonempty κ]
  {β : κ → Type*} [∀ k, MeasurableSpace (β k)]
  [∀ k, StandardBorelSpace (β k)]

/-- The explicit, standard-Borel, compact-tightness, and countable-skeleton
continuum routes are simultaneously OS/Wightman-ready with reflection
positivity supplied automatically from finite Wilson Gram data. -/
theorem finite_wilson_single_source_four_os_routes_ready_of_automatic_reflection
    (S : EuclideanYangMillsCountableSkeletonData
      R.toProjectiveRealization.toProjectiveCylinderFamily κ β)
    (C : FiniteWilsonGibbsSingleSourceRemainingOSAnalyticTransferData R)
    (D : FiniteWilsonOSAutomaticReflectionLimitData W) :
    (R.explicitOSContinuumConstruction
        (R.osAnalyticTransferDataOfAutomaticReflection C D)).toMeasurePackage.ready ∧
      (R.standardBorelOSContinuumConstruction
        (R.osAnalyticTransferDataOfAutomaticReflection C D)).toMeasurePackage.ready ∧
      (R.compactTightOSContinuumConstruction
        (R.osAnalyticTransferDataOfAutomaticReflection C D)).toMeasurePackage.ready ∧
      (R.countableSkeletonOSContinuumConstruction S
        (R.osAnalyticTransferDataOfAutomaticReflection C D)).toMeasurePackage.ready :=
  finite_wilson_single_source_four_os_routes_ready R S
    (R.osAnalyticTransferDataOfAutomaticReflection C D)

/-- All four automatically assembled analytic constructions still use exactly
the explicit common-source Wilson continuum law. -/
theorem
    finite_wilson_single_source_four_os_route_measures_eq_explicit_of_automatic_reflection
    (S : EuclideanYangMillsCountableSkeletonData
      R.toProjectiveRealization.toProjectiveCylinderFamily κ β)
    (C : FiniteWilsonGibbsSingleSourceRemainingOSAnalyticTransferData R)
    (D : FiniteWilsonOSAutomaticReflectionLimitData W) :
    (R.explicitOSContinuumConstruction
        (R.osAnalyticTransferDataOfAutomaticReflection C D)).limit.continuumMeasure =
        R.continuumMeasure ∧
      (R.standardBorelOSContinuumConstruction
        (R.osAnalyticTransferDataOfAutomaticReflection C D)).limit.continuumMeasure =
        R.continuumMeasure ∧
      (R.compactTightOSContinuumConstruction
        (R.osAnalyticTransferDataOfAutomaticReflection C D)).limit.continuumMeasure =
        R.continuumMeasure ∧
      (R.countableSkeletonOSContinuumConstruction S
        (R.osAnalyticTransferDataOfAutomaticReflection C D)).limit.continuumMeasure =
        R.continuumMeasure :=
  finite_wilson_single_source_four_os_route_measures_eq_explicit R S
    (R.osAnalyticTransferDataOfAutomaticReflection C D)

end

end MathlibAnalytic
end MGAP4D
