import MGAP4D.MathlibAnalytic.FiniteLatticeWilsonCanonicalVariationDefiniteness

namespace MGAP4D
namespace MathlibAnalytic

#check FiniteLatticeWilsonSystem.configurationPatch
#check finite_lattice_configurationPatch_empty
#check finite_lattice_configurationPatch_univ
#check finite_lattice_configurationPatch_agreeOffLink_insert

end MathlibAnalytic
end MGAP4D
