import MGAP4D.MathlibAnalytic.FiniteWilsonRandomScanTwoSidedIntegerPathOSForm
import MGAP4D.MathlibAnalytic.LinearMarkovTwoSidedIntegerPathOSPreHilbert

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- The actual finite Wilson Gibbs-stationary random-scan chain as generic
full-path temporal OS pre-Hilbert data. -/
noncomputable def FiniteLatticeWilsonSystem.randomScanTwoSidedIntegerPathOSPreHilbertData
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge] :
    LinearMarkovTwoSidedIntegerPathOSPreHilbertData L.Configuration where
  initial := L.gibbsPMF
  transition := L.randomScanTransitionPMF
  detailedBalance := finite_lattice_randomScanDetailedBalanceReal L

/-- The datum-dependent carrier of actual finite Wilson positive-time cylinder
observables before null separation. -/
abbrev FiniteLatticeWilsonSystem.RandomScanTwoSidedIntegerPathOSCarrier
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge] :=
  L.randomScanTwoSidedIntegerPathOSPreHilbertData.Carrier

/-- The separated real pre-Hilbert space generated by the actual finite Wilson
Gibbs random-scan two-sided path law. -/
abbrev FiniteLatticeWilsonSystem.RandomScanTwoSidedIntegerPathOSPreHilbert
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge] :=
  L.randomScanTwoSidedIntegerPathOSPreHilbertData.Separated

/-- The separated OS vector represented by an actual finite Wilson positive-time
cylinder observable. -/
def FiniteLatticeWilsonSystem.randomScanTwoSidedIntegerPathOSClass
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (F : linearMarkovPositiveTimeCylinderSubalgebra
      (Ω := L.Configuration)) :
    L.RandomScanTwoSidedIntegerPathOSPreHilbert :=
  L.randomScanTwoSidedIntegerPathOSPreHilbertData.observableClass F

/-- The pre-Hilbert inner product of actual Wilson OS classes is exactly the full
path-space random-scan OS form. -/
@[simp] theorem FiniteLatticeWilsonSystem.inner_randomScanTwoSidedIntegerPathOSClass
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (F G : linearMarkovPositiveTimeCylinderSubalgebra
      (Ω := L.Configuration)) :
    inner ℝ
        (L.randomScanTwoSidedIntegerPathOSClass F)
        (L.randomScanTwoSidedIntegerPathOSClass G) =
      L.randomScanTwoSidedIntegerPathOSForm F G := by
  change
    linearMarkovTwoSidedIntegerPathOSForm
        L.gibbsPMF L.randomScanTransitionPMF
          (finite_lattice_randomScanDetailedBalanceReal L) F G =
      L.randomScanTwoSidedIntegerPathOSForm F G
  rfl

/-- An actual Wilson positive-time cylinder observable represents zero in the
pre-Hilbert quotient exactly when it belongs to the actual Wilson OS null
submodule. -/
@[simp] theorem FiniteLatticeWilsonSystem.randomScanTwoSidedIntegerPathOSClass_eq_zero_iff
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (F : linearMarkovPositiveTimeCylinderSubalgebra
      (Ω := L.Configuration)) :
    L.randomScanTwoSidedIntegerPathOSClass F = 0 ↔
      F ∈ L.randomScanTwoSidedIntegerPathOSNull := by
  change
    L.randomScanTwoSidedIntegerPathOSPreHilbertData.observableClass F = 0 ↔
      F ∈ L.randomScanTwoSidedIntegerPathOSNull
  simpa [FiniteLatticeWilsonSystem.randomScanTwoSidedIntegerPathOSNull,
    FiniteLatticeWilsonSystem.randomScanTwoSidedIntegerPathOSPreHilbertData] using
    L.randomScanTwoSidedIntegerPathOSPreHilbertData.observableClass_eq_zero_iff F

/-- Two actual finite Wilson positive-time observables represent the same
pre-Hilbert vector exactly when their difference is OS null. -/
theorem FiniteLatticeWilsonSystem.randomScanTwoSidedIntegerPathOSClass_eq_class_iff
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (F G : linearMarkovPositiveTimeCylinderSubalgebra
      (Ω := L.Configuration)) :
    L.randomScanTwoSidedIntegerPathOSClass F =
        L.randomScanTwoSidedIntegerPathOSClass G ↔
      F - G ∈ L.randomScanTwoSidedIntegerPathOSNull := by
  change
    L.randomScanTwoSidedIntegerPathOSPreHilbertData.observableClass F =
        L.randomScanTwoSidedIntegerPathOSPreHilbertData.observableClass G ↔
      F - G ∈ L.randomScanTwoSidedIntegerPathOSNull
  simpa [FiniteLatticeWilsonSystem.randomScanTwoSidedIntegerPathOSNull,
    FiniteLatticeWilsonSystem.randomScanTwoSidedIntegerPathOSPreHilbertData] using
    L.randomScanTwoSidedIntegerPathOSPreHilbertData
      .observableClass_eq_observableClass_iff F G

/-- The actual finite Wilson temporal OS quotient is positive definite. -/
theorem FiniteLatticeWilsonSystem.randomScanTwoSidedIntegerPathOSPreHilbert_inner_self_eq_zero_iff
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (x : L.RandomScanTwoSidedIntegerPathOSPreHilbert) :
    inner ℝ x x = 0 ↔ x = 0 :=
  L.randomScanTwoSidedIntegerPathOSPreHilbertData
    .separated_inner_self_eq_zero_iff x

end

end MathlibAnalytic
end MGAP4D
