import MGAP4D.MathlibAnalytic.LinearMarkovPositiveTimeOSGram
import MGAP4D.MathlibAnalytic.FiniteWilsonRandomScanPositiveTimeCylinderAlgebra
import MGAP4D.MathlibAnalytic.FiniteWilsonOSReflectionPositivity
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators ENNReal

noncomputable section

/-- The conditional finite strictly-positive-time future law of the actual
finite Wilson random-scan chain given the time-zero configuration. -/
abbrev FiniteLatticeWilsonSystem.randomScanPositiveTimeFuturePMF
    (L : FiniteLatticeWilsonSystem)
    (n : ℕ)
    (boundary : L.Configuration) :
    PMF (LinearMarkovPositiveTimeFuturePath L.Configuration n) :=
  linearMarkovPositiveTimeFuturePMF L.randomScanTransitionPMF n boundary

/-- The concrete finite Wilson doubled-future OS kernel. -/
abbrev FiniteLatticeWilsonSystem.randomScanPositiveTimeOSKernel
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ) :
    LinearMarkovPositiveTimeFuturePath L.Configuration n →
      LinearMarkovPositiveTimeFuturePath L.Configuration n → ℝ :=
  linearMarkovPositiveTimeOSKernel
    L.gibbsPMF L.randomScanTransitionPMF n

/-- The concrete finite Wilson positive-time OS bilinear form. -/
abbrev FiniteLatticeWilsonSystem.randomScanPositiveTimeOSForm
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ) :
    (LinearMarkovPositiveTimeFuturePath L.Configuration n → ℝ) →
      (LinearMarkovPositiveTimeFuturePath L.Configuration n → ℝ) → ℝ :=
  linearMarkovPositiveTimeOSForm
    L.gibbsPMF L.randomScanTransitionPMF n

/-- The actual finite Wilson temporal OS kernel packaged in the repository's
existing reusable finite Gram-certificate interface.  The feature index is the
time-zero boundary configuration, and the feature value is the conditional
future probability. -/
def FiniteLatticeWilsonSystem.randomScanPositiveTimeOSGramCertificate
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ) :
    FiniteOSReflectionGramCertificate where
  PositiveConfiguration :=
    LinearMarkovPositiveTimeFuturePath L.Configuration n
  Feature := L.Configuration
  kernel := L.randomScanPositiveTimeOSKernel n
  coefficient := fun boundary => (L.gibbsPMF boundary).toReal
  coefficient_nonneg := fun _boundary => ENNReal.toReal_nonneg
  feature := fun boundary future =>
    linearMarkovPositiveTimeFutureProbabilityReal
      L.randomScanTransitionPMF n boundary future
  kernel_decomposition := by
    intro left right
    rfl

/-- The reflection form of the generic finite Gram certificate is definitionally
the concrete Wilson doubled-future OS quadratic form. -/
theorem finite_lattice_randomScanPositiveTimeOSGramCertificate_reflectionForm_eq
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (F : LinearMarkovPositiveTimeFuturePath L.Configuration n → ℝ) :
    (L.randomScanPositiveTimeOSGramCertificate n).reflectionForm F =
      L.randomScanPositiveTimeOSForm n F F := by
  rfl

/-- The actual finite Wilson random-scan doubled-future time reflection is
positive for every finite-future observable.  This is theorem-generated by the
same reusable Gram-certificate engine as the finite spatial Wilson OS layer. -/
theorem finite_lattice_randomScanPositiveTimeOSForm_nonneg
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (F : LinearMarkovPositiveTimeFuturePath L.Configuration n → ℝ) :
    0 ≤ L.randomScanPositiveTimeOSForm n F F := by
  rw [← finite_lattice_randomScanPositiveTimeOSGramCertificate_reflectionForm_eq]
  exact finite_os_reflectionForm_nonneg
    (L.randomScanPositiveTimeOSGramCertificate n) F

/-- The actual finite Wilson temporal OS form is symmetric. -/
theorem finite_lattice_randomScanPositiveTimeOSForm_symmetric
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (F G : LinearMarkovPositiveTimeFuturePath L.Configuration n → ℝ) :
    L.randomScanPositiveTimeOSForm n F G =
      L.randomScanPositiveTimeOSForm n G F :=
  linearMarkovPositiveTimeOSForm_symmetric
    L.gibbsPMF L.randomScanTransitionPMF n F G

/-- The boundary amplitude of a positive-time Wilson product cylinder. -/
def FiniteLatticeWilsonSystem.randomScanPositiveTimeBoundaryCylinderAmplitude
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (fs : Fin (n + 1) → L.Configuration → ℝ)
    (boundary : L.Configuration) : ℝ :=
  linearMarkovCylinderMoment
    (finitePMFExpectationReal (L.randomScanTransitionPMF boundary))
    (finitePMFTransitionExpectationLinearMap L.randomScanTransitionPMF)
    (List.ofFn fs)

/-- The boundary amplitude begins with the already constructed random-scan
heat-bath observable operator. -/
theorem finite_lattice_randomScanPositiveTimeBoundaryCylinderAmplitude_eq_sweep
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (fs : Fin (n + 1) → L.Configuration → ℝ)
    (boundary : L.Configuration) :
    L.randomScanPositiveTimeBoundaryCylinderAmplitude n fs boundary =
      linearMarkovCylinderMoment
        (fun f => L.randomScanHeatBathSweep f boundary)
        (finitePMFTransitionExpectationLinearMap L.randomScanTransitionPMF)
        (List.ofFn fs) := by
  unfold FiniteLatticeWilsonSystem.randomScanPositiveTimeBoundaryCylinderAmplitude
  congr 1
  funext f
  exact finite_lattice_randomScanTransitionPMF_expectation L boundary f

/-- The temporal OS quadratic form of an actual finite Wilson positive-time
product cylinder is the Gibbs expectation of the square of its boundary
cylinder amplitude. -/
theorem finite_lattice_randomScanPositiveTimeOSForm_product_eq_gibbs_boundary_sq
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (fs : Fin (n + 1) → L.Configuration → ℝ) :
    L.randomScanPositiveTimeOSForm n
        (linearMarkovFinitePathProduct fs)
        (linearMarkovFinitePathProduct fs) =
      L.gibbsExpectationReal
        (fun boundary =>
          (L.randomScanPositiveTimeBoundaryCylinderAmplitude
            n fs boundary) ^ 2) := by
  unfold FiniteLatticeWilsonSystem.randomScanPositiveTimeOSForm
  rw [linearMarkovPositiveTimeOSForm_product_eq_boundaryMoment_sq]
  rw [finite_lattice_finitePMFExpectationReal_gibbsPMF]
  rfl

/-- Every concrete finite Wilson positive-time product cylinder therefore has a
nonnegative temporal OS quadratic expectation. -/
theorem finite_lattice_randomScanPositiveTimeOSForm_product_nonneg
    (L : FiniteLatticeWilsonSystem)
    [Nonempty L.Edge]
    (n : ℕ)
    (fs : Fin (n + 1) → L.Configuration → ℝ) :
    0 ≤ L.randomScanPositiveTimeOSForm n
      (linearMarkovFinitePathProduct fs)
      (linearMarkovFinitePathProduct fs) :=
  finite_lattice_randomScanPositiveTimeOSForm_nonneg
    L n (linearMarkovFinitePathProduct fs)

end

end MathlibAnalytic
end MGAP4D
