import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorDuhamelVanishingInputAsymptoticStability

namespace MGAP4D
namespace MathlibAnalytic

#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_norm_zero_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_norm_zero_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_zero_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_zero_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_apply_zero_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_apply_zero_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_vanishingInput_eventually_uniform_unitBall_zero_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_vanishingInput_eventually_uniform_unitBall_zero_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_norm_zero_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_norm_zero_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_zero_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_zero_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_apply_zero_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_apply_zero_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_eventually_uniform_unitBall_zero_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_eventually_uniform_unitBall_zero_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_norm_zero_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_norm_zero_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_zero_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_zero_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_apply_zero_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_tendsto_apply_zero_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_eventually_uniform_unitBall_zero_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_vanishingInput_eventually_uniform_unitBall_zero_right

end MathlibAnalytic
end MGAP4D
