import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsGlobalObservationConcreteFrontierAssembly

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-!
Generate the global-observation separation input from a faithful observation map.

The previous frontier asks for two finite Wilson source configurations whose
full observations differ.  For a nontrivial source configuration space, that
separation is automatic as soon as the global observation map is injective.
This file isolates precisely that remaining observation-faithfulness obligation
and propagates it through the concrete interaction and exact-gap continuum
frontier.
-/

/-- The fixed-source global Wilson observation loses no source configuration
information. -/
structure FiniteWilsonGibbsFaithfulGlobalObservation
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (R : FiniteWilsonGibbsSingleSourceProjectiveRealization W) where
  injective_globalObserve : Function.Injective R.globalObserve

/-- A faithful global observation on a nontrivial finite Wilson configuration
space canonically supplies two globally separated source configurations. -/
noncomputable def
    FiniteWilsonGibbsFaithfulGlobalObservation.toGlobalObservationSeparation
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    [Nontrivial (W.system R.sourceScale).Configuration]
    (F : FiniteWilsonGibbsFaithfulGlobalObservation R) :
    FiniteWilsonGibbsGlobalObservationSeparation R := by
  classical
  let hex : ∃ A B : (W.system R.sourceScale).Configuration, A ≠ B :=
    exists_pair_ne (W.system R.sourceScale).Configuration
  let A := Classical.choose hex
  let B := Classical.choose (Classical.choose_spec hex)
  have hAB : A ≠ B := Classical.choose_spec (Classical.choose_spec hex)
  exact
    { sourceLeft := A
      sourceRight := B
      globalObserve_ne := fun h => hAB (F.injective_globalObserve h) }

/-- Faithfulness and source nontriviality generate a nondegenerate singleton
cylinder event. -/
noncomputable def
    FiniteWilsonGibbsFaithfulGlobalObservation.toNondegenerateEvent
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    [Nontrivial (W.system R.sourceScale).Configuration]
    [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]
    (F : FiniteWilsonGibbsFaithfulGlobalObservation R) :
    FiniteWilsonGibbsCylinderNondegenerateEvent R :=
  F.toGlobalObservationSeparation.toNondegenerateEvent

/-- Faithfulness and source nontriviality generate the finite-cylinder
interaction witness used by the continuum frontier. -/
noncomputable def
    FiniteWilsonGibbsFaithfulGlobalObservation.toInteractionWitness
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    [Nontrivial (W.system R.sourceScale).Configuration]
    [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]
    (F : FiniteWilsonGibbsFaithfulGlobalObservation R) :
    FiniteWilsonGibbsCylinderInteractionWitness R :=
  F.toGlobalObservationSeparation.toInteractionWitness

/-- The interaction generated by a faithful global observation survives as a
nonzero continuum connected correlation. -/
theorem finite_wilson_faithful_global_observation_interaction_passes_to_continuum
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (R : FiniteWilsonGibbsSingleSourceProjectiveRealization W)
    [Nontrivial (W.system R.sourceScale).Configuration]
    [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]
    (D : FiniteWilsonGibbsSingleSourceExactGapOSLimitData R)
    (F : FiniteWilsonGibbsFaithfulGlobalObservation R) :
    finiteWilsonContinuumCylinderConnectedCorrelation R D
      F.toInteractionWitness.support
      F.toInteractionWitness.leftObservable
      F.toInteractionWitness.rightObservable ≠ 0 := by
  exact finite_wilson_global_observation_interaction_passes_to_continuum
    R D F.toGlobalObservationSeparation

/-- Build the concrete exact-gap continuum assembly directly from global
observation faithfulness and source nontriviality. -/
noncomputable def
    FiniteWilsonGibbsConcreteAnalyticFrontierCore.toExactGapContinuumAssemblyOfFaithfulGlobalObservation
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    [Nontrivial (W.system R.sourceScale).Configuration]
    [∀ x, Fintype (R.fieldValue x)]
    [∀ x, Countable (R.fieldValue x)]
    [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]
    (C : FiniteWilsonGibbsConcreteAnalyticFrontierCore R)
    (F : FiniteWilsonGibbsFaithfulGlobalObservation R) :
    FiniteWilsonGibbsSingleSourceExactGapContinuumAssembly R :=
  C.toExactGapContinuumAssemblyOfGlobalObservationSeparation
    F.toGlobalObservationSeparation

/-- Faithful observation supplies the five OS properties, concrete Schwinger
construction and limit, and continuum interaction theorem in one package. -/
theorem
    FiniteWilsonGibbsConcreteAnalyticFrontierCore.faithfulGlobalObservation_complete_frontier_package
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    [Nontrivial (W.system R.sourceScale).Configuration]
    [∀ x, Fintype (R.fieldValue x)]
    [∀ x, Countable (R.fieldValue x)]
    [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]
    (C : FiniteWilsonGibbsConcreteAnalyticFrontierCore R)
    (F : FiniteWilsonGibbsFaithfulGlobalObservation R) :
    FiniteWilsonExactGapOSFiveLimitProperties C.limitData ∧
      (C.toExactGapContinuumAssemblyOfFaithfulGlobalObservation F).interactingContinuumLimitConstructed ∧
      (C.toExactGapContinuumAssemblyOfFaithfulGlobalObservation F).gaugeInvariantSchwingerFunctionsConstructed ∧
      (C.toExactGapContinuumAssemblyOfFaithfulGlobalObservation F).schwingerFunctionsAreContinuumLimits := by
  exact C.globalObservation_complete_frontier_package
    F.toGlobalObservationSeparation

/-- Faithful observation retains the exact-threshold spectral separation
endpoint of the reduced construction spine. -/
theorem
    FiniteWilsonGibbsConcreteAnalyticFrontierCore.faithfulGlobalObservation_exactThresholdSeparation
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {R : FiniteWilsonGibbsSingleSourceProjectiveRealization W}
    [Nontrivial (W.system R.sourceScale).Configuration]
    [∀ x, Fintype (R.fieldValue x)]
    [∀ x, Countable (R.fieldValue x)]
    [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]
    (C : FiniteWilsonGibbsConcreteAnalyticFrontierCore R)
    (F : FiniteWilsonGibbsFaithfulGlobalObservation R) :
    euclideanYangMillsCompleteConstructionDirectBounded_exactThresholdSeparationProp
      (C.toExactGapConstructionSpineOfGlobalObservationSeparation
        F.toGlobalObservationSeparation).toConstructionSpine := by
  exact C.globalObservation_exactThresholdSeparation
    F.toGlobalObservationSeparation

end

end MathlibAnalytic
end MGAP4D