import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorDuhamelZeroInputSettlingTime

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

#check exp_neg_mul_mul_le_of_log_div_div_le
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_exp_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_exp_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_epsilon_after_settlingTime_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_epsilon_after_settlingTime_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_exp_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_exp_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_epsilon_after_settlingTime_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_epsilon_after_settlingTime_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_exp_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_exp_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_epsilon_after_settlingTime_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_norm_le_epsilon_after_settlingTime_right

end

end MathlibAnalytic
end MGAP4D
