import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorCommonInputPairwiseFullGapBundle

namespace MGAP4D
namespace MathlibAnalytic

#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_exponentialContraction_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_exponentialContraction_fullGap_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_norm_sub_le_epsilon_after_exponentialContraction_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_norm_sub_le_epsilon_after_exponentialContraction_fullGap_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_pointwise_exponentialContraction_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_pointwise_exponentialContraction_fullGap_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_exponentialContraction_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_exponentialContraction_fullGap_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_unitBall_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_pairwise_unitBall_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_eq_of_sameInitial_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_commonInput_eq_of_sameInitial_fullGap_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_exponentialContraction_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_exponentialContraction_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_norm_sub_le_epsilon_after_exponentialContraction_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_norm_sub_le_epsilon_after_exponentialContraction_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_pointwise_exponentialContraction_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_pointwise_exponentialContraction_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_exponentialContraction_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_exponentialContraction_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_unitBall_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_unitBall_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_eq_of_sameInitial_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_commonInput_eq_of_sameInitial_fullGap_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_exponentialContraction_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_exponentialContraction_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_norm_sub_le_epsilon_after_exponentialContraction_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_norm_sub_le_epsilon_after_exponentialContraction_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_pointwise_exponentialContraction_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_pointwise_exponentialContraction_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_exponentialContraction_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_exponentialContraction_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_unitBall_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_pairwise_unitBall_matrixElement_abs_le_epsilon_after_exponentialContraction_fullGap_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_eq_of_sameInitial_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_commonInput_eq_of_sameInitial_fullGap_right

end MathlibAnalytic
end MGAP4D
