import MGAP4D.MathlibAnalytic.OrthonormalDiagonalHamiltonianSemigroupOperatorConstantInputMatrixElementExponentialTrackingFullGap
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapConstructedRealSpectralHamiltonianSemigroupOperatorConstantInputMatrixElementExponentialTrackingFullGap
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorConstantInputMatrixElementExponentialTrackingFullGap

namespace MGAP4D
namespace MathlibAnalytic

#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_matrixElement_exponentialTracking_fullGap_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_constantInput_matrixElement_exponentialTracking_fullGap_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_exponentialTracking_fullGap_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_exponentialTracking_fullGap_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_exponentialTracking_fullGap_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_constantInput_matrixElement_exponentialTracking_fullGap_right

end MathlibAnalytic
end MGAP4D
