import MGAP4D.MathlibAnalytic.FinitePositiveWeightConditionalCrossRatioInfluence
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators

noncomputable section

/-- Entrywise cross-ratio data for a positive finite product weight, without
assuming a strict global row-sum certificate.  This separates the local
conditional-influence construction from the later fixed-point closure. -/
structure FinitePositiveWeightCrossRatioInfluenceEntryData
    {ι G : Type}
    [DecidableEq ι]
    [Fintype ι]
    [Fintype G]
    (weight : (ι → G) → ℝ) where
  radius : ι → ι → ℝ
  radius_nonneg : ∀ target source : ι, 0 ≤ radius target source
  crossRatioBound :
    ∀ (target source : ι) (A B : ι → G),
      target ≠ source →
      FiniteProductAgreeOff A B source →
        FinitePositiveWeightSingleSiteCrossRatioBound
          weight A B target (Real.exp (radius target source))

/-- Full-`L¹` influence entry generated by entrywise cross-ratio data. -/
noncomputable def finitePositiveWeightCrossRatioEntryInfluence
    {ι G : Type}
    [DecidableEq ι]
    [Fintype ι]
    [Fintype G]
    {weight : (ι → G) → ℝ}
    (D : FinitePositiveWeightCrossRatioInfluenceEntryData weight)
    (target source : ι) : ℝ :=
  if target = source then 0 else
    2 * ((Real.exp (D.radius target source) - 1) /
      (Real.exp (D.radius target source) + 1))

/-- Every entrywise cross-ratio influence is nonnegative. -/
theorem finitePositiveWeightCrossRatioEntryInfluence_nonneg
    {ι G : Type}
    [DecidableEq ι]
    [Fintype ι]
    [Fintype G]
    {weight : (ι → G) → ℝ}
    (D : FinitePositiveWeightCrossRatioInfluenceEntryData weight)
    (target source : ι) :
    0 ≤ finitePositiveWeightCrossRatioEntryInfluence D target source := by
  by_cases hEq : target = source
  · simp [finitePositiveWeightCrossRatioEntryInfluence, hEq]
  · rw [finitePositiveWeightCrossRatioEntryInfluence, if_neg hEq]
    exact mul_nonneg (by norm_num)
      (expLikelihoodRatioTotalVariationBound_nonneg
        (D.radius target source) (D.radius_nonneg target source))

/-- Diagonal entrywise influence is exactly zero. -/
theorem finitePositiveWeightCrossRatioEntryInfluence_diagonal
    {ι G : Type}
    [DecidableEq ι]
    [Fintype ι]
    [Fintype G]
    {weight : (ι → G) → ℝ}
    (D : FinitePositiveWeightCrossRatioInfluenceEntryData weight)
    (target : ι) :
    finitePositiveWeightCrossRatioEntryInfluence D target target = 0 := by
  simp [finitePositiveWeightCrossRatioEntryInfluence]

/-- Entrywise cross-ratio data bounds every exact one-source conditional
change, before any row-sum or strict-contraction assertion is made. -/
theorem finitePositiveWeightSingleSiteConditionalL1_le_crossRatioEntryInfluence
    {ι G : Type}
    [DecidableEq ι]
    [Fintype ι]
    [Fintype G]
    [Nonempty G]
    (weight : (ι → G) → ℝ)
    (hweight : ∀ A : ι → G, 0 < weight A)
    (D : FinitePositiveWeightCrossRatioInfluenceEntryData weight)
    (target source : ι)
    (A B : ι → G)
    (hAgree : FiniteProductAgreeOff A B source) :
    finitePositiveWeightSingleSiteConditionalL1 weight A B target ≤
      finitePositiveWeightCrossRatioEntryInfluence D target source := by
  by_cases hEq : target = source
  · subst source
    rw [finitePositiveWeightSingleSiteConditionalL1_eq_zero_of_agreeOff
      weight A B target hAgree,
      finitePositiveWeightCrossRatioEntryInfluence_diagonal]
  · rw [finitePositiveWeightCrossRatioEntryInfluence, if_neg hEq]
    apply finitePositiveWeightSingleSiteConditionalL1_le_of_crossRatio
      weight hweight A B target (Real.exp (D.radius target source))
    · simpa using
        (Real.exp_le_exp.mpr (D.radius_nonneg target source))
    · exact D.crossRatioBound target source A B hEq hAgree

/-- Row sum of the entrywise cross-ratio influence. -/
noncomputable def finitePositiveWeightCrossRatioEntryRowSum
    {ι G : Type}
    [DecidableEq ι]
    [Fintype ι]
    [Fintype G]
    {weight : (ι → G) → ℝ}
    (D : FinitePositiveWeightCrossRatioInfluenceEntryData weight)
    (target : ι) : ℝ :=
  ∑ source : ι,
    finitePositiveWeightCrossRatioEntryInfluence D target source

/-- An external strict row-sum certificate upgrades entrywise cross-ratio data
to the generic Dobrushin `L¹` matrix used by random-scan contraction. -/
noncomputable def
    FinitePositiveWeightCrossRatioInfluenceEntryData.toDobrushinL1MatrixData
    {ι G : Type}
    [DecidableEq ι]
    [Fintype ι]
    [Fintype G]
    [Nonempty G]
    {weight : (ι → G) → ℝ}
    (D : FinitePositiveWeightCrossRatioInfluenceEntryData weight)
    (hweight : ∀ A : ι → G, 0 < weight A)
    (coefficient : ℝ)
    (hCoefficientNonneg : 0 ≤ coefficient)
    (hRowSum :
      ∀ target : ι,
        finitePositiveWeightCrossRatioEntryRowSum D target ≤ coefficient)
    (hCoefficientLtOne : coefficient < 1) :
    FinitePositiveWeightDobrushinL1MatrixData weight :=
  { influence := finitePositiveWeightCrossRatioEntryInfluence D
    influence_nonneg :=
      finitePositiveWeightCrossRatioEntryInfluence_nonneg D
    influence_diagonal_zero :=
      finitePositiveWeightCrossRatioEntryInfluence_diagonal D
    conditionalL1_le := fun target source A B hAgree =>
      finitePositiveWeightSingleSiteConditionalL1_le_crossRatioEntryInfluence
        weight hweight D target source A B hAgree
    coefficient := coefficient
    coefficient_nonneg := hCoefficientNonneg
    rowSum_le_coefficient := by
      intro target
      simpa [finitePositiveWeightCrossRatioEntryRowSum] using hRowSum target
    coefficient_lt_one := hCoefficientLtOne }

end

end MathlibAnalytic
end MGAP4D
