import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorDuhamelUniformForcingPracticalSettlingTime

namespace MGAP4D
namespace MathlibAnalytic

#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_uniformForcing_norm_le_ultimateBall_after_settlingTime_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_uniformForcing_norm_le_ultimateBall_after_settlingTime_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_uniformForcing_norm_le_ultimateBall_after_settlingTime_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_uniformForcing_norm_le_ultimateBall_after_settlingTime_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_uniformForcing_norm_le_ultimateBall_after_settlingTime_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_uniformForcing_norm_le_ultimateBall_after_settlingTime_right

end MathlibAnalytic
end MGAP4D
