import MGAP4D.MathlibAnalytic.FiniteOrientedLatticeWilsonSingleLinkHeatBathFluctuationEnergy

namespace MGAP4D
namespace MathlibAnalytic

#check FiniteOrientedLatticeWilsonSystem.boltzmannWeight
#check FiniteOrientedLatticeWilsonSystem.partitionFunction
#check FiniteOrientedLatticeWilsonSystem.gibbsPMF
#check finite_oriented_gibbsPMF_gaugeInvariant
#check FiniteOrientedLatticeWilsonSystem.gibbsMeasure
#check FiniteOrientedLatticeWilsonSystem.gibbsExpectationReal
#check FiniteOrientedLatticeWilsonSystem.gibbsVarianceReal
#check finite_oriented_singleLinkHeatBath_detailedBalance_real
#check FiniteOrientedLatticeWilsonSystem.singleLinkHeatBathProjectionLinearMap
#check finite_oriented_singleLinkHeatBathProjectionLinearMap_idempotent
#check finite_oriented_singleLinkHeatBath_gibbsPairing_projection_symm
#check FiniteOrientedLatticeWilsonSystem.singleLinkHeatBathFluctuationLinearMap
#check finite_oriented_singleLinkHeatBathFluctuationLinearMap_idempotent
#check finite_oriented_singleLinkConditionalVariance_eq_fluctuationEnergy
#check FiniteOrientedLatticeWilsonSystem.singleLinkHeatBathDirichletForm
#check FiniteOrientedLatticeWilsonSystem.ExactGapSingleLinkHeatBathPoincare

end MathlibAnalytic
end MGAP4D
