import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorDuhamelAsymptoticallyConstantInputMatrixElementUniformHalfMinSimplifiedBundle

namespace MGAP4D
namespace MathlibAnalytic

#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_pointwise_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_pointwise_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_unitBall_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_unitBall_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_pointwise_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_pointwise_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_unitBall_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_unitBall_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_pointwise_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_pointwise_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_unitBall_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_asymptoticallyConstantInput_unitBall_matrixElement_sub_steadyState_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right

end MathlibAnalytic
end MGAP4D
