import MGAP4D.MathlibAnalytic.FiniteOrientedWilsonNativeHamiltonianGap

namespace MGAP4D
namespace MathlibAnalytic

#check FiniteOrientedLatticeWilsonSystem.boltzmannWeight
#check FiniteOrientedLatticeWilsonSystem.partitionFunction
#check FiniteOrientedLatticeWilsonSystem.gibbsPMF
#check finite_oriented_gibbsPMF_gaugeInvariant
#check FiniteOrientedLatticeWilsonSystem.gibbsMeasure
#check FiniteOrientedLatticeWilsonSystem.gibbsExpectationReal
#check FiniteOrientedLatticeWilsonSystem.gibbsVarianceReal
#check finite_oriented_singleLinkHeatBath_detailedBalance_real
#check FiniteOrientedLatticeWilsonSystem.singleLinkHeatBathProjectionLinearMap
#check finite_oriented_singleLinkHeatBathProjectionLinearMap_idempotent
#check finite_oriented_singleLinkHeatBath_gibbsPairing_projection_symm
#check FiniteOrientedLatticeWilsonSystem.singleLinkHeatBathFluctuationLinearMap
#check finite_oriented_singleLinkHeatBathFluctuationLinearMap_idempotent
#check finite_oriented_singleLinkConditionalVariance_eq_fluctuationEnergy
#check finite_oriented_singleLinkHeatBath_gibbsPairing_pythagorean
#check FiniteOrientedLatticeWilsonSystem.singleLinkHeatBathHamiltonianObservable
#check finite_oriented_singleLinkHeatBathHamiltonianObservable_quadraticForm
#check FiniteOrientedLatticeWilsonSystem.GibbsHilbertSpace
#check FiniteOrientedLatticeWilsonSystem.gibbsHilbertLinearEquiv
#check FiniteOrientedLatticeWilsonSystem.gibbsHeatBathHamiltonianLinearMap
#check finite_oriented_gibbsHeatBathHamiltonianLinearMap_isSymmetric
#check finite_oriented_gibbsHeatBathHamiltonianLinearMap_vacuum
#check finite_oriented_gibbsHeatBathHamiltonianLinearMap_quadraticForm
#check finiteOrientedWilsonNativeHeatBathHamiltonianGapData
#check finite_oriented_native_hamiltonian_gap_on_vacuumOrthogonal
#check finite_oriented_native_restricted_eigenvalues_ge_exactGap

end MathlibAnalytic
end MGAP4D
