import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorExponentiallyCloseInputsRobustPairwiseUniformHalfMinSimplifiedBundle

namespace MGAP4D
namespace MathlibAnalytic

#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_norm_sub_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_norm_sub_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_pointwise_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_pointwise_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_unitBall_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_unitBall_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_norm_sub_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_norm_sub_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_pointwise_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_pointwise_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_unitBall_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_unitBall_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_norm_sub_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_norm_sub_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_pointwise_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_pointwise_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_unitBall_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_exponentiallyCloseInputs_pairwise_unitBall_matrixElement_sub_abs_le_epsilon_after_exponentialTracking_uniform_halfMin_simplified_right

end MathlibAnalytic
end MGAP4D
