import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorInputProfilePairwiseConvolutionSharpFiniteHorizonBundle

namespace MGAP4D
namespace MathlibAnalytic

#check intervalIntegral_exp_memory_mul_const_eq_finiteHorizonGain
#check intervalIntegral_exp_memory_norm_sub_le_finiteHorizonGain

#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_convolution_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_convolution_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_pointwise_convolution_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_pointwise_convolution_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_convolution_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_convolution_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_sub_convolution_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_sub_convolution_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_unitBall_matrixElement_sub_convolution_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_inputProfile_pairwise_unitBall_matrixElement_sub_convolution_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_sharp_finiteHorizon_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_sharp_finiteHorizon_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_equalInitial_sharp_finiteHorizon_gain_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_equalInitial_sharp_finiteHorizon_gain_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_convolution_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_convolution_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_pointwise_convolution_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_pointwise_convolution_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_convolution_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_convolution_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_sub_convolution_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_sub_convolution_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_unitBall_matrixElement_sub_convolution_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_unitBall_matrixElement_sub_convolution_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_sharp_finiteHorizon_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_sharp_finiteHorizon_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_equalInitial_sharp_finiteHorizon_gain_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_equalInitial_sharp_finiteHorizon_gain_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_convolution_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_convolution_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_pointwise_convolution_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_pointwise_convolution_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_convolution_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_convolution_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_sub_convolution_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_matrixElement_sub_convolution_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_unitBall_matrixElement_sub_convolution_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_inputProfile_pairwise_unitBall_matrixElement_sub_convolution_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_sharp_finiteHorizon_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_sharp_finiteHorizon_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_equalInitial_sharp_finiteHorizon_gain_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_equalInitial_sharp_finiteHorizon_gain_right

end MathlibAnalytic
end MGAP4D