import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsExplicitCanonicalGaugeMeasureOSWightmanBridge

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-!
Construct the reduced exact-gap definition bridge directly from a ready
Euclidean measure bridge and an attained exact-gap spectral core.
-/

/-- A ready Euclidean measure bridge and an exact-gap spectral core construct
`OSWightmanExactGapDefinitionBridge` directly.

The reduced reconstruction spine, its axiom readiness, and its axiom
identification are generated here rather than supplied as a completed bridge. -/
def euclideanYangMillsMeasureExactGapDefinitionBridge
    (E : EuclideanYangMillsMeasureToOSWightmanBridge)
    (hMeasure : E.measure.ready)
    (C : FourDimensionalYangMillsExactGapSpectralCore)
    (core_uses_measure_axioms : C.osWightman = E.axioms)
    (hamiltonianSelfAdjoint : C.hamiltonianSelfAdjoint)
    (spectralPVM_detects_energySpectrum :
      ∀ energy : ℝ, energy ∈ C.energySpectrum →
        ∃ ψ : C.H, ψ ∈ C.spectralPVM ({energy} : Set ℝ))
    (vacuumSpectralPoint :
      C.vacuum ∈ C.spectralPVM ({0} : Set ℝ)) :
    OSWightmanExactGapDefinitionBridge where
  spine :=
    { axioms := E.axioms
      spectralCore := C
      core_uses_axioms := core_uses_measure_axioms
      axioms_ready :=
        euclidean_yang_mills_measure_to_os_wightman_ready E hMeasure }
  hamiltonianSelfAdjoint_proof := hamiltonianSelfAdjoint
  spectralPVM_detects_energySpectrum := spectralPVM_detects_energySpectrum
  vacuumSpectralPoint := vacuumSpectralPoint

@[simp]
theorem euclideanYangMillsMeasureExactGapDefinitionBridge_axioms
    (E : EuclideanYangMillsMeasureToOSWightmanBridge)
    (hMeasure : E.measure.ready)
    (C : FourDimensionalYangMillsExactGapSpectralCore)
    (core_uses_measure_axioms : C.osWightman = E.axioms)
    (hamiltonianSelfAdjoint : C.hamiltonianSelfAdjoint)
    (spectralPVM_detects_energySpectrum :
      ∀ energy : ℝ, energy ∈ C.energySpectrum →
        ∃ ψ : C.H, ψ ∈ C.spectralPVM ({energy} : Set ℝ))
    (vacuumSpectralPoint :
      C.vacuum ∈ C.spectralPVM ({0} : Set ℝ)) :
    (euclideanYangMillsMeasureExactGapDefinitionBridge E hMeasure C
      core_uses_measure_axioms hamiltonianSelfAdjoint
      spectralPVM_detects_energySpectrum vacuumSpectralPoint).spine.axioms =
        E.axioms :=
  rfl

section SingleLinkHeatBath

variable
  (W : FiniteWilsonOSAutomaticApproximationFamily)
  (s : W.index)
  (D : FiniteWilsonGibbsSingleSourceSingleLinkHeatBathOSLimitData
    (finiteWilsonExplicitCanonicalGaugeRealization W s))

/-- The continuum measure package generated by the explicit canonical
single-link heat-bath route. -/
abbrev FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathMeasurePackage :=
  (finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathContinuumConstruction
    W s D).toMeasurePackage

/-- The explicit canonical single-link heat-bath measure package is ready. -/
theorem finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBath_measure_ready :
    (FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathMeasurePackage W s D).ready := by
  exact finite_wilson_explicit_canonical_gauge_coercive_os_limit_ready W s
    (finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathCoerciveData W s D)

variable
  (wightmanLocality wightmanCovariance wightmanSpectrumCondition : Prop)
  (wightmanLocality_from_measure :
    (FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathMeasurePackage
      W s D).ready → wightmanLocality)
  (wightmanCovariance_from_measure :
    (FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathMeasurePackage
      W s D).ready → wightmanCovariance)
  (wightmanSpectrumCondition_from_measure :
    (FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathMeasurePackage
      W s D).ready → wightmanSpectrumCondition)

/-- The canonical measure bridge used by the spectral-core constructor. -/
abbrev FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathCanonicalMeasureBridge :=
  finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathMeasureBridge W s D
    wightmanLocality wightmanCovariance wightmanSpectrumCondition
    wightmanLocality_from_measure wightmanCovariance_from_measure
    wightmanSpectrumCondition_from_measure

variable
  (C : FourDimensionalYangMillsExactGapSpectralCore)
  (core_uses_measure_axioms :
    C.osWightman =
      (FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathCanonicalMeasureBridge
        W s D wightmanLocality wightmanCovariance
        wightmanSpectrumCondition wightmanLocality_from_measure
        wightmanCovariance_from_measure
        wightmanSpectrumCondition_from_measure).axioms)
  (hamiltonianSelfAdjoint : C.hamiltonianSelfAdjoint)
  (spectralPVM_detects_energySpectrum :
    ∀ energy : ℝ, energy ∈ C.energySpectrum →
      ∃ ψ : C.H, ψ ∈ C.spectralPVM ({energy} : Set ℝ))
  (vacuumSpectralPoint :
    C.vacuum ∈ C.spectralPVM ({0} : Set ℝ))

/-- The explicit canonical single-link heat-bath route constructs its reduced
exact-gap definition bridge from the spectral core. -/
def finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathExactGapDefinitionBridge :
    OSWightmanExactGapDefinitionBridge :=
  euclideanYangMillsMeasureExactGapDefinitionBridge
    (FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathCanonicalMeasureBridge
      W s D wightmanLocality wightmanCovariance
      wightmanSpectrumCondition wightmanLocality_from_measure
      wightmanCovariance_from_measure
      wightmanSpectrumCondition_from_measure)
    (finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBath_measure_ready W s D)
    C core_uses_measure_axioms hamiltonianSelfAdjoint
    spectralPVM_detects_energySpectrum vacuumSpectralPoint

@[simp]
theorem finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathExactGapDefinitionBridge_axioms :
    (finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathExactGapDefinitionBridge
      W s D wightmanLocality wightmanCovariance
      wightmanSpectrumCondition wightmanLocality_from_measure
      wightmanCovariance_from_measure wightmanSpectrumCondition_from_measure
      C core_uses_measure_axioms hamiltonianSelfAdjoint
      spectralPVM_detects_energySpectrum vacuumSpectralPoint).spine.axioms =
        (FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathCanonicalMeasureBridge
          W s D wightmanLocality wightmanCovariance
          wightmanSpectrumCondition wightmanLocality_from_measure
          wightmanCovariance_from_measure
          wightmanSpectrumCondition_from_measure).axioms :=
  rfl

variable [Nonempty (W.system s).Edge]

/-- The full reduced exact-gap continuum spine with both bridge objects
constructed from the measure package and the exact-gap spectral core. -/
noncomputable def
    finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathExactGapConstructionSpineOfSpectralCore :
    EuclideanYangMillsContinuumMeasureExactGapConstructionSpine :=
  finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathExactGapConstructionSpineOfReconstruction
    W s D wightmanLocality wightmanCovariance
    wightmanSpectrumCondition wightmanLocality_from_measure
    wightmanCovariance_from_measure wightmanSpectrumCondition_from_measure
    (finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathExactGapDefinitionBridge
      W s D wightmanLocality wightmanCovariance
      wightmanSpectrumCondition wightmanLocality_from_measure
      wightmanCovariance_from_measure wightmanSpectrumCondition_from_measure
      C core_uses_measure_axioms hamiltonianSelfAdjoint
      spectralPVM_detects_energySpectrum vacuumSpectralPoint)
    rfl

/-- The spectral-core-driven single-link heat-bath endpoint. -/
abbrev FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathSpectralCoreMassGapProp : Prop :=
  let construction :=
    finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathExactGapConstructionSpineOfSpectralCore
      W s D wightmanLocality wightmanCovariance
      wightmanSpectrumCondition wightmanLocality_from_measure
      wightmanCovariance_from_measure wightmanSpectrumCondition_from_measure
      C core_uses_measure_axioms hamiltonianSelfAdjoint
      spectralPVM_detects_energySpectrum vacuumSpectralPoint
  let target := construction.toConstructionSpine.toUnconditionalTarget
  target.toPipeline.definitionBridge.spine.model.hasMassGap ∧
    0 < exactGapValueReal ∧
    exactGapValueReal = sInf target.toPipeline.nonVacuumHamiltonianSpectrum

/-- The canonical measure and exact-gap definition bridges generated from the
spectral core reach the Hamiltonian mass-gap and exact-threshold theorem. -/
theorem
    finite_wilson_explicit_canonical_gauge_singleLinkHeatBath_mass_gap_of_spectralCore :
    FiniteWilsonExplicitCanonicalGaugeSingleLinkHeatBathSpectralCoreMassGapProp
      W s D wightmanLocality wightmanCovariance
      wightmanSpectrumCondition wightmanLocality_from_measure
      wightmanCovariance_from_measure wightmanSpectrumCondition_from_measure
      C core_uses_measure_axioms hamiltonianSelfAdjoint
      spectralPVM_detects_energySpectrum vacuumSpectralPoint := by
  exact
    finite_wilson_explicit_canonical_gauge_singleLinkHeatBath_mass_gap_of_reconstruction
      W s D wightmanLocality wightmanCovariance
      wightmanSpectrumCondition wightmanLocality_from_measure
      wightmanCovariance_from_measure wightmanSpectrumCondition_from_measure
      (finiteWilsonExplicitCanonicalGaugeSingleLinkHeatBathExactGapDefinitionBridge
        W s D wightmanLocality wightmanCovariance
        wightmanSpectrumCondition wightmanLocality_from_measure
        wightmanCovariance_from_measure wightmanSpectrumCondition_from_measure
        C core_uses_measure_axioms hamiltonianSelfAdjoint
        spectralPVM_detects_energySpectrum vacuumSpectralPoint)
      rfl

end SingleLinkHeatBath

end

end MathlibAnalytic
end MGAP4D
