import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorDuhamelUniformForcingLongTimeISS

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

#check tendsto_sub_mul_atTop_atTop
#check tendsto_exp_neg_sub_mul_atTop_zero
#check limsup_norm_le_of_eventually_le_exp_transient
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_uniformForcing_limsup_norm_le_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_uniformForcing_limsup_norm_le_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_uniformForcing_limsup_norm_le_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_uniformForcing_limsup_norm_le_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_uniformForcing_limsup_norm_le_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_uniformForcing_limsup_norm_le_right

end

end MathlibAnalytic
end MGAP4D
