import MGAP4D.MathlibAnalytic.FiniteDimensionalSymmetricPositiveContractionSpectrum
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped InnerProduct

noncomputable section

namespace FiniteDimensionalSymmetricPositiveContractionData

variable
    {E : Type*}
    [NormedAddCommGroup E]
    [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E]
    (D : FiniteDimensionalSymmetricPositiveContractionData E)

/-- Spectral energy on the nonzero transfer support.  The logarithm is taken
only where the transfer eigenvalue is strictly positive. -/
def positiveSpectralEnergy (i : D.PositiveSpectralIndex) : ℝ :=
  -Real.log (D.positiveEigenvalue i)

/-- Every positive-support energy is nonnegative because its transfer
eigenvalue lies in `(0, 1]`. -/
theorem positiveSpectralEnergy_nonneg
    (i : D.PositiveSpectralIndex) :
    0 ≤ D.positiveSpectralEnergy i := by
  unfold positiveSpectralEnergy
  exact neg_nonneg.mpr
    (Real.log_nonpos (D.positiveEigenvalue_pos i)
      (D.positiveEigenvalue_le_one i))

/-- Hamiltonian diagonalized in the positive transfer spectral coordinates. -/
noncomputable def positiveSpectralHamiltonian :
    D.PositiveSpectralSpace →L[ℝ] D.PositiveSpectralSpace :=
  LinearMap.toContinuousLinearMap
    { toFun := fun x i => D.positiveSpectralEnergy i * x i
      map_add' := by
        intro x y
        ext i
        simp [mul_add]
      map_smul' := by
        intro c x
        ext i
        simp [mul_assoc] }

@[simp] theorem positiveSpectralHamiltonian_apply
    (x : D.PositiveSpectralSpace)
    (i : D.PositiveSpectralIndex) :
    D.positiveSpectralHamiltonian x i =
      D.positiveSpectralEnergy i * x i :=
  rfl

/-- On every positive spectral mode, exponentiating minus the support energy
recovers the exact transfer eigenvalue. -/
theorem exp_neg_positiveSpectralEnergy
    (i : D.PositiveSpectralIndex) :
    Real.exp (-D.positiveSpectralEnergy i) =
      D.positiveEigenvalue i := by
  unfold positiveSpectralEnergy
  rw [neg_neg, Real.exp_log (D.positiveEigenvalue_pos i)]

/-- The positive-support transfer is exactly the modewise exponential of the
negative support Hamiltonian. -/
theorem positiveSpectralTransfer_eq_exp_neg_energy_apply
    (x : D.PositiveSpectralSpace)
    (i : D.PositiveSpectralIndex) :
    D.positiveSpectralTransfer x i =
      Real.exp (-D.positiveSpectralEnergy i) * x i := by
  rw [D.positiveSpectralTransfer_apply,
    D.exp_neg_positiveSpectralEnergy]

/-- Every natural-time support transfer is generated by the support
Hamiltonian through the exact discrete spectral weight `exp(-E)^n`. -/
theorem positiveSpectralSemigroup_eq_exp_neg_energy_pow_apply
    (n : ℕ)
    (x : D.PositiveSpectralSpace)
    (i : D.PositiveSpectralIndex) :
    D.positiveSpectralSemigroup n x i =
      (Real.exp (-D.positiveSpectralEnergy i)) ^ n * x i := by
  rw [D.positiveSpectralSemigroup_apply,
    D.exp_neg_positiveSpectralEnergy]

/-- The support Hamiltonian is positive in quadratic form. -/
theorem positiveSpectralHamiltonian_quadratic_nonneg
    (x : D.PositiveSpectralSpace) :
    0 ≤ inner ℝ (D.positiveSpectralHamiltonian x) x := by
  rw [PiLp.inner_apply]
  apply Finset.sum_nonneg
  intro i _hi
  change 0 ≤ x i * (D.positiveSpectralEnergy i * x i)
  nlinarith [D.positiveSpectralEnergy_nonneg i, sq_nonneg (x i)]

/-- The support Hamiltonian is symmetric. -/
theorem positiveSpectralHamiltonian_isSymmetric :
    D.positiveSpectralHamiltonian.toLinearMap.IsSymmetric := by
  intro x y
  rw [PiLp.inner_apply, PiLp.inner_apply]
  apply Finset.sum_congr rfl
  intro i _hi
  change
    y i * (D.positiveSpectralEnergy i * x i) =
      x i * (D.positiveSpectralEnergy i * y i)
  ring

/-- The positive-support transfer is symmetric. -/
theorem positiveSpectralTransfer_isSymmetric :
    D.positiveSpectralTransfer.toLinearMap.IsSymmetric := by
  intro x y
  rw [PiLp.inner_apply, PiLp.inner_apply]
  apply Finset.sum_congr rfl
  intro i _hi
  change
    y i * (D.positiveEigenvalue i * x i) =
      x i * (D.positiveEigenvalue i * y i)
  ring

/-- The positive-support transfer is positive in quadratic form. -/
theorem positiveSpectralTransfer_quadratic_nonneg
    (x : D.PositiveSpectralSpace) :
    0 ≤ inner ℝ (D.positiveSpectralTransfer x) x := by
  rw [PiLp.inner_apply]
  apply Finset.sum_nonneg
  intro i _hi
  change 0 ≤ x i * (D.positiveEigenvalue i * x i)
  nlinarith [le_of_lt (D.positiveEigenvalue_pos i), sq_nonneg (x i)]

end FiniteDimensionalSymmetricPositiveContractionData

end

end MathlibAnalytic
end MGAP4D
