import MGAP4D.MathlibAnalytic.FiniteLatticeWilsonActionLocalDecomposition

namespace MGAP4D
namespace MathlibAnalytic

#check FiniteLatticeWilsonSystem.targetRemotePlaquetteAction
#check finite_lattice_wilsonAction_eq_targetLocal_add_targetRemote
#check finite_lattice_replaceLink_boundary_eq_of_not_touches_target
#check finite_lattice_plaquetteHolonomy_replaceLink_eq_of_not_touches_target
#check finite_lattice_targetRemotePlaquetteAction_replaceLink_eq
#check finite_lattice_targetRemotePlaquetteAction_replaceLink
#check finite_lattice_wilsonAction_replaceLink_eq_local_add_remote

end MathlibAnalytic
end MGAP4D
