import MGAP4D.MathlibAnalytic.FiniteLatticeWilsonCanonicalTotalVariationDefiniteness

namespace MGAP4D
namespace MathlibAnalytic

#check FiniteLatticeWilsonSystem.canonicalTotalVariation
#check finite_lattice_canonicalTotalVariation_nonneg
#check finite_lattice_canonicalLinkVariation_const_eq_zero
#check finite_lattice_canonicalTotalVariation_const_eq_zero
#check finite_lattice_all_canonicalLinkVariations_eq_zero_of_total_eq_zero
#check finite_lattice_canonicalTotalVariation_eq_zero_iff_const
#check finite_lattice_centered_observable_eq_zero_of_canonicalTotalVariation_eq_zero

end MathlibAnalytic
end MGAP4D
