import MGAP4D.MathlibAnalytic.FiniteWilsonOSReflectionPositivity

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators

noncomputable section

/-- Transporting a positive-time observable across the configuration equivalence
identifies the Wilson reflection form with the Gram reflection form.

Thus the previously explicit `FiniteLatticeWilsonOSGramBridge` is not an
independent mathematical assumption: it follows from the finite equivalence of
half-lattice configuration types together with pointwise agreement of the two
kernels. -/
theorem finite_lattice_wilson_os_reflectionForm_eq_gram_transport
    {L : FiniteLatticeWilsonSystem}
    (R : FiniteLatticeWilsonOSReflectionCertificate L)
    (F : R.PositiveConfiguration → ℝ) :
    R.wilsonReflectionForm F =
      R.gram.reflectionForm
        (fun z => F (R.positiveConfigurationEquiv.symm z)) := by
  classical
  unfold FiniteLatticeWilsonOSReflectionCertificate.wilsonReflectionForm
    FiniteOSReflectionGramCertificate.reflectionForm
  refine Fintype.sum_equiv R.positiveConfigurationEquiv _ _ ?_
  intro x
  simp only [R.positiveConfigurationEquiv.symm_apply_apply]
  refine Fintype.sum_equiv R.positiveConfigurationEquiv _ _ ?_
  intro y
  simp only [R.positiveConfigurationEquiv.symm_apply_apply]
  rw [R.gram_kernel_agrees x y]

/-- Canonical Gram bridge generated by the configuration equivalence and kernel
agreement already stored in the Wilson reflection certificate. -/
def FiniteLatticeWilsonOSReflectionCertificate.automaticGramBridge
    {L : FiniteLatticeWilsonSystem}
    (R : FiniteLatticeWilsonOSReflectionCertificate L) :
    FiniteLatticeWilsonOSGramBridge R :=
  { transportObservable :=
      fun F z => F (R.positiveConfigurationEquiv.symm z)
    reflectionForm_eq :=
      finite_lattice_wilson_os_reflectionForm_eq_gram_transport R }

/-- The reflection certificate alone now proves Wilson OS positivity; no
separate bridge argument is required. -/
theorem finite_lattice_wilson_os_reflection_positive_of_certificate
    {L : FiniteLatticeWilsonSystem}
    (R : FiniteLatticeWilsonOSReflectionCertificate L) :
    FiniteLatticeWilsonOSReflectionPositive R :=
  finite_lattice_wilson_os_gram_bridge_closes_reflectionPositivity
    R R.automaticGramBridge

/-- Build the audit-visible finite-volume OS certificate directly from the
reflection data. -/
def finiteWilsonOSReflectionPositivityCertificateOfReflectionData
    (L : FiniteLatticeWilsonSystem)
    (R : FiniteLatticeWilsonOSReflectionCertificate L) :
    FiniteWilsonOSReflectionPositivityCertificate L :=
  finiteWilsonOSReflectionPositivityCertificate L R R.automaticGramBridge

end

end MathlibAnalytic
end MGAP4D
