import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapConstructedTransferOrbitContraction

namespace MGAP4D
namespace MathlibAnalytic

open Filter

noncomputable section

/-- A single-scale exact-identification route.

The same finite Wilson Gibbs system is used at every sequence index, and the
continuum connected correlation is defined to be that fixed finite connected
correlation.  Consequently the pointwise convergence field is generated by
`Tendsto` of a constant sequence.  This is an exact common-source
identification, not a nontrivial lattice-spacing scaling limit. -/
structure FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData
    (W : FiniteWilsonOSAutomaticApproximationFamily) where
  Observable : Type
  StateSpace : Type
  [stateNormedAddCommGroup : NormedAddCommGroup StateSpace]
  [stateInnerProductSpace : InnerProductSpace ℝ StateSpace]
  [stateFiniteDimensional : FiniteDimensional ℝ StateSpace]
  StateDimension : ℕ
  stateFinrank : Module.finrank ℝ StateSpace = StateDimension
  sourceScale : W.index
  leftObservable :
    Observable → (W.system sourceScale).Configuration → ℝ
  rightObservable :
    Observable → ℕ → (W.system sourceScale).Configuration → ℝ
  decayAmplitude : Observable → ℝ
  hamiltonian : StateSpace →ₗ[ℝ] StateSpace
  hamiltonianSymmetric : hamiltonian.IsSymmetric
  hamiltonianEigenvalues_ge_exactGap :
    ∀ i : Fin StateDimension,
      exactGapValueReal ≤
        hamiltonianSymmetric.eigenvalues stateFinrank i
  initialCorrelationState : Observable → StateSpace
  correlationReadout : Observable → StateSpace →L[ℝ] ℝ
  connectedCorrelation_representation :
    ∀ (O : Observable) (r : ℕ),
      (W.system sourceScale).gibbsConnectedCorrelation
          (leftObservable O) (rightObservable O r) =
        correlationReadout O
          (continuousLinearMapOrbit
            (orthonormalDiagonalOperator
              (hamiltonianSymmetric.eigenvectorBasis stateFinrank)
              (fun i =>
                Real.exp
                  (-(hamiltonianSymmetric.eigenvalues stateFinrank i))))
            (initialCorrelationState O) r)
  readoutInitialStateBound :
    ∀ O : Observable,
      ‖correlationReadout O‖ * ‖initialCorrelationState O‖ ≤
        decayAmplitude O

attribute [instance]
  FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData.stateNormedAddCommGroup
  FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData.stateInnerProductSpace
  FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData.stateFiniteDimensional

/-- The continuum correlation in the exact single-scale route is definitionally
the fixed finite Wilson connected correlation. -/
noncomputable def
    FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData.continuumConnectedCorrelation
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData W)
    (O : D.Observable) (r : ℕ) : ℝ :=
  (W.system D.sourceScale).gibbsConnectedCorrelation
    (D.leftObservable O) (D.rightObservable O r)

/-- The single-scale correlation sequence converges because it is constant.
This theorem does not assert a nontrivial UV or infinite-volume scaling limit. -/
theorem finite_wilson_single_scale_pointwise_convergence
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData W)
    (O : D.Observable) (r : ℕ) :
    Tendsto
      (fun _ : ℕ =>
        (W.system D.sourceScale).gibbsConnectedCorrelation
          (D.leftObservable O) (D.rightObservable O r))
      atTop (nhds (D.continuumConnectedCorrelation O r)) := by
  exact tendsto_const_nhds

/-- Convert the exact single-scale identification to the general transfer-orbit
route.  The scale sequence, Hamiltonian data, state, readout, and finite
correlations are constant in the sequence index. -/
noncomputable def
    FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData.toConstructedTransferOrbitData
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData W) :
    FiniteWilsonOSAutomaticExactGapConstructedTransferOrbitContractionData W :=
  { Observable := D.Observable
    StateSpace := D.StateSpace
    stateNormedAddCommGroup := D.stateNormedAddCommGroup
    stateInnerProductSpace := D.stateInnerProductSpace
    stateFiniteDimensional := D.stateFiniteDimensional
    StateDimension := D.StateDimension
    stateFinrank := D.stateFinrank
    scale := fun _ => D.sourceScale
    leftObservable := fun _ => D.leftObservable
    rightObservable := fun _ => D.rightObservable
    continuumConnectedCorrelation := D.continuumConnectedCorrelation
    decayAmplitude := D.decayAmplitude
    hamiltonian := fun _ => D.hamiltonian
    hamiltonianSymmetric := fun _ => D.hamiltonianSymmetric
    hamiltonianEigenvalues_ge_exactGap := fun _ =>
      D.hamiltonianEigenvalues_ge_exactGap
    initialCorrelationState := fun _ => D.initialCorrelationState
    correlationReadout := fun _ => D.correlationReadout
    connectedCorrelation_representation := by
      intro n O r
      exact D.connectedCorrelation_representation O r
    readoutInitialStateBound := by
      intro n O
      exact D.readoutInitialStateBound O
    pointwiseConvergence := by
      intro O r
      exact finite_wilson_single_scale_pointwise_convergence D O r }

/-- The exact single-scale identification inherits finite-volume exact-gap
decay from the constructed Hamiltonian transfer orbit. -/
theorem finite_wilson_exact_gap_bound_of_single_scale_transfer_orbit
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData W)
    (O : D.Observable) (r : ℕ) :
    ‖(W.system D.sourceScale).gibbsConnectedCorrelation
        (D.leftObservable O) (D.rightObservable O r)‖ ≤
      D.decayAmplitude O * exactGapClusterContractionRatio ^ r :=
  finite_wilson_exact_gap_bound_of_constructed_transfer_orbit
    D.toConstructedTransferOrbitData 0 O r

/-- The exact single-scale continuum correlation satisfies the inherited
exact-gap estimate without an independent pointwise convergence input. -/
theorem finite_wilson_exact_gap_single_scale_continuum_bound
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData W)
    (O : D.Observable) (r : ℕ) :
    ‖D.continuumConnectedCorrelation O r‖ ≤
      D.decayAmplitude O * exactGapClusterContractionRatio ^ r :=
  finite_wilson_exact_gap_constructed_transfer_orbit_continuum_bound
    D.toConstructedTransferOrbitData O r

/-- Exact single-scale identification yields the continuum cluster property in
this fixed-source route. -/
theorem finite_wilson_exact_gap_single_scale_passes_to_limit
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapSingleScaleTransferOrbitContractionData W) :
    D.toConstructedTransferOrbitData.toConstructedHamiltonianTransferData.toHamiltonianEigenactionData.toFiniteDimensionalHamiltonianData.toOrthonormalEigenbasisData.toFiniteSpectralData.toPositiveRayleighData.toSymmetricRayleighData.toHilbertMatrixData.toTransferOperatorData.toExactGapClusterData.toUniformGeometricClusterData.toClusterLimitData.toClusterLimitData.ContinuumClusterProperty :=
  finite_wilson_exact_gap_constructed_transfer_orbit_passes_to_limit
    D.toConstructedTransferOrbitData

end

end MathlibAnalytic
end MGAP4D
