import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsSingleSourceCountableSkeletonOSPropertyTransfer
import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticRegularityLimitTransfer

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory

noncomputable section

/-- Concrete analytic input package for a finite Wilson approximation family.

Reflection positivity and finite-volume Euclidean invariance are generated by
finite Wilson theorems.  The genuinely analytic inputs are convergence of the
finite observables, a decaying volume-uniform connected-correlation envelope,
and a volume-uniform Schwinger regularity estimate. -/
structure FiniteWilsonOSAutomaticAnalyticLimitConstructionData
    (W : FiniteWilsonOSAutomaticApproximationFamily)
    (F : EuclideanYangMillsProjectiveCylinderFamily)
    (L : EuclideanYangMillsProjectiveLimitMeasure F) where
  gaugeGroup : Type
  [gaugeGroupGroup : Group gaugeGroup]
  [gaugeGroupTopology : TopologicalSpace gaugeGroup]
  [gaugeGroupCompact : CompactSpace gaugeGroup]
  [gaugeGroupNontrivial : Nontrivial gaugeGroup]
  [gaugeAction : MulAction gaugeGroup F.Configuration]
  gaugeActionMeasurable :
    ∀ g : gaugeGroup, Measurable (fun A : F.Configuration => g • A)
  gaugeInvariant :
    ∀ g : gaugeGroup,
      L.continuumMeasure.map (fun A : F.Configuration => g • A) =
        L.continuumMeasure
  fieldAlgebra : Type
  schwingerFunctions : ℕ → Type
  symmetric : Prop
  symmetric_proof : symmetric
  reflectionLimit : FiniteWilsonOSAutomaticReflectionLimitData W
  euclideanLimit : FiniteWilsonOSAutomaticEuclideanLimitData W
  clusterLimit : FiniteWilsonOSAutomaticClusterLimitData W
  regularityLimit : FiniteWilsonOSAutomaticRegularityLimitData W

attribute [instance]
  FiniteWilsonOSAutomaticAnalyticLimitConstructionData.gaugeGroupGroup
  FiniteWilsonOSAutomaticAnalyticLimitConstructionData.gaugeGroupTopology
  FiniteWilsonOSAutomaticAnalyticLimitConstructionData.gaugeGroupCompact
  FiniteWilsonOSAutomaticAnalyticLimitConstructionData.gaugeGroupNontrivial
  FiniteWilsonOSAutomaticAnalyticLimitConstructionData.gaugeAction

/-- Assemble the generic projective-limit transfer record from concrete finite
Wilson limit data. -/
noncomputable def
    FiniteWilsonOSAutomaticAnalyticLimitConstructionData.toProjectiveLimitTransferData
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {F : EuclideanYangMillsProjectiveCylinderFamily}
    {L : EuclideanYangMillsProjectiveLimitMeasure F}
    (D : FiniteWilsonOSAutomaticAnalyticLimitConstructionData W F L) :
    EuclideanYangMillsProjectiveLimitAnalyticTransferData F L :=
  { gaugeGroup := D.gaugeGroup
    gaugeGroupGroup := D.gaugeGroupGroup
    gaugeGroupTopology := D.gaugeGroupTopology
    gaugeGroupCompact := D.gaugeGroupCompact
    gaugeGroupNontrivial := D.gaugeGroupNontrivial
    gaugeAction := D.gaugeAction
    gaugeActionMeasurable := D.gaugeActionMeasurable
    gaugeInvariant := D.gaugeInvariant
    fieldAlgebra := D.fieldAlgebra
    schwingerFunctions := D.schwingerFunctions
    reflectionLimit := D.reflectionLimit.toReflectionPositivityLimitData
    euclideanLimit := D.euclideanLimit.toEuclideanInvarianceLimitData
    symmetric := D.symmetric
    symmetric_proof := D.symmetric_proof
    clusterLimit := D.clusterLimit.toClusterLimitData
    regularityLimit := D.regularityLimit.toRegularityLimitData }

/-- The four limiting OS properties obtained from the concrete finite Wilson
analytic package. -/
theorem finite_wilson_os_automatic_four_limit_properties
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {F : EuclideanYangMillsProjectiveCylinderFamily}
    {L : EuclideanYangMillsProjectiveLimitMeasure F}
    (D : FiniteWilsonOSAutomaticAnalyticLimitConstructionData W F L) :
    D.reflectionLimit.ContinuumReflectionPositive ∧
      D.euclideanLimit.toEuclideanInvarianceLimitData.ContinuumEuclideanInvariant ∧
      D.clusterLimit.toClusterLimitData.ContinuumClusterProperty ∧
      D.regularityLimit.toRegularityLimitData.ContinuumRegularity :=
  ⟨finite_wilson_os_automatic_reflection_positivity_passes_to_limit
      D.reflectionLimit,
    finite_wilson_os_automatic_euclidean_invariance_passes_to_limit
      D.euclideanLimit,
    finite_wilson_os_automatic_cluster_property_passes_to_limit D.clusterLimit,
    finite_wilson_os_automatic_regularity_passes_to_limit D.regularityLimit⟩

/-- The continuum construction assembled from concrete finite Wilson limit data
is ready for the OS/Wightman measure bridge. -/
theorem finite_wilson_os_automatic_continuum_measure_package_ready
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {F : EuclideanYangMillsProjectiveCylinderFamily}
    {L : EuclideanYangMillsProjectiveLimitMeasure F}
    (D : FiniteWilsonOSAutomaticAnalyticLimitConstructionData W F L) :
    D.toProjectiveLimitTransferData.toContinuumConstruction.toMeasurePackage.ready :=
  euclidean_yang_mills_projective_limit_transferred_measure_package_ready
    D.toProjectiveLimitTransferData

variable {W : FiniteWilsonOSAutomaticApproximationFamily}
  (R : FiniteWilsonGibbsSingleSourceProjectiveRealization W)
  [∀ x, Fintype (R.fieldValue x)]
  [∀ x, Countable (R.fieldValue x)]
  [∀ x, DiscreteMeasurableSpace (R.fieldValue x)]

/-- Concrete finite Wilson analytic completion data for the explicit
single-source projective-limit law. -/
abbrev FiniteWilsonGibbsSingleSourceAutomaticOSLimitData :=
  FiniteWilsonOSAutomaticAnalyticLimitConstructionData W
    R.toProjectiveRealization.toProjectiveCylinderFamily
    R.projectiveLimitMeasure

/-- The complete analytic transfer record for the explicit Wilson law. -/
noncomputable def
    FiniteWilsonGibbsSingleSourceProjectiveRealization.automaticOSLimitTransferData
    (D : FiniteWilsonGibbsSingleSourceAutomaticOSLimitData R) :
    FiniteWilsonGibbsSingleSourceOSPropertyTransferData R :=
  D.toProjectiveLimitTransferData

/-- The explicit common-source Wilson continuum law is OS/Wightman-ready once
the concrete convergence and uniform-estimate package is supplied. -/
theorem finite_wilson_single_source_automatic_os_limit_ready
    (D : FiniteWilsonGibbsSingleSourceAutomaticOSLimitData R) :
    (R.explicitOSContinuumConstruction
      (R.automaticOSLimitTransferData D)).toMeasurePackage.ready :=
  finite_wilson_single_source_explicit_os_ready R
    (R.automaticOSLimitTransferData D)

variable {κ : Type*} [Countable κ] [Nonempty κ]
  {β : κ → Type*} [∀ k, MeasurableSpace (β k)]
  [∀ k, StandardBorelSpace (β k)]

/-- Explicit, standard-Borel, compact-tightness, and countable-skeleton
constructions are simultaneously OS/Wightman-ready. -/
theorem finite_wilson_single_source_automatic_four_routes_ready
    (S : EuclideanYangMillsCountableSkeletonData
      R.toProjectiveRealization.toProjectiveCylinderFamily κ β)
    (D : FiniteWilsonGibbsSingleSourceAutomaticOSLimitData R) :
    (R.explicitOSContinuumConstruction
        (R.automaticOSLimitTransferData D)).toMeasurePackage.ready ∧
      (R.standardBorelOSContinuumConstruction
        (R.automaticOSLimitTransferData D)).toMeasurePackage.ready ∧
      (R.compactTightOSContinuumConstruction
        (R.automaticOSLimitTransferData D)).toMeasurePackage.ready ∧
      (R.countableSkeletonOSContinuumConstruction S
        (R.automaticOSLimitTransferData D)).toMeasurePackage.ready :=
  finite_wilson_single_source_four_os_routes_ready R S
    (R.automaticOSLimitTransferData D)

/-- All four constructions use exactly the explicit finite Wilson
`globalObserve` pushforward law. -/
theorem finite_wilson_single_source_automatic_four_route_measures_eq_explicit
    (S : EuclideanYangMillsCountableSkeletonData
      R.toProjectiveRealization.toProjectiveCylinderFamily κ β)
    (D : FiniteWilsonGibbsSingleSourceAutomaticOSLimitData R) :
    (R.explicitOSContinuumConstruction
        (R.automaticOSLimitTransferData D)).limit.continuumMeasure =
        R.continuumMeasure ∧
      (R.standardBorelOSContinuumConstruction
        (R.automaticOSLimitTransferData D)).limit.continuumMeasure =
        R.continuumMeasure ∧
      (R.compactTightOSContinuumConstruction
        (R.automaticOSLimitTransferData D)).limit.continuumMeasure =
        R.continuumMeasure ∧
      (R.countableSkeletonOSContinuumConstruction S
        (R.automaticOSLimitTransferData D)).limit.continuumMeasure =
        R.continuumMeasure :=
  finite_wilson_single_source_four_os_route_measures_eq_explicit R S
    (R.automaticOSLimitTransferData D)

end

end MathlibAnalytic
end MGAP4D
