import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorDuhamelZeroInputOperatorStrongConvergence

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

#check tendsto_zero_of_tendsto_norm_zero
#check continuousLinearMap_tendsto_apply_zero_of_tendsto_zero
#check continuousLinearMap_eventually_uniform_unitBall_zero_of_tendsto_zero
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_zero_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_zero_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_apply_zero_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_apply_zero_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_eventually_uniform_unitBall_zero_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_duhamel_zeroInput_eventually_uniform_unitBall_zero_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_zero_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_zero_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_apply_zero_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_apply_zero_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_eventually_uniform_unitBall_zero_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_eventually_uniform_unitBall_zero_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_zero_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_zero_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_apply_zero_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_tendsto_apply_zero_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_eventually_uniform_unitBall_zero_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_duhamel_zeroInput_eventually_uniform_unitBall_zero_right

end

end MathlibAnalytic
end MGAP4D
