import MGAP4D.MathlibAnalytic.FiniteOrientedWilsonCanonicalHeatBathHamiltonianObservable

namespace MGAP4D
namespace MathlibAnalytic

#check FiniteOrientedLatticeWilsonSystem.boltzmannWeight
#check FiniteOrientedLatticeWilsonSystem.partitionFunction
#check FiniteOrientedLatticeWilsonSystem.gibbsPMF
#check finite_oriented_gibbsPMF_gaugeInvariant
#check FiniteOrientedLatticeWilsonSystem.gibbsMeasure
#check FiniteOrientedLatticeWilsonSystem.gibbsExpectationReal
#check FiniteOrientedLatticeWilsonSystem.gibbsVarianceReal
#check finite_oriented_singleLinkHeatBath_detailedBalance_real
#check FiniteOrientedLatticeWilsonSystem.singleLinkHeatBathProjectionLinearMap
#check finite_oriented_singleLinkHeatBathProjectionLinearMap_idempotent
#check finite_oriented_singleLinkHeatBath_gibbsPairing_projection_symm
#check FiniteOrientedLatticeWilsonSystem.singleLinkHeatBathFluctuationLinearMap
#check finite_oriented_singleLinkHeatBathFluctuationLinearMap_idempotent
#check finite_oriented_singleLinkConditionalVariance_eq_fluctuationEnergy
#check finite_oriented_singleLinkHeatBath_gibbsPairing_pythagorean
#check FiniteOrientedLatticeWilsonSystem.singleLinkHeatBathHamiltonianObservable
#check finite_oriented_singleLinkHeatBathHamiltonianObservable_gibbsPairing_symm
#check finite_oriented_singleLinkHeatBathHamiltonianObservable_quadraticForm
#check finite_oriented_singleLinkHeatBathHamiltonianObservable_nonneg
#check finite_oriented_singleLinkHeatBathHamiltonianObservable_one
#check FiniteOrientedLatticeWilsonSystem.ExactGapSingleLinkHeatBathPoincare

end MathlibAnalytic
end MGAP4D
