import MGAP4D.MathlibAnalytic.FiniteWilsonGibbsSingleSourceConstructedTransferOrbitOSLimitAssembly

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

variable {W : FiniteWilsonOSAutomaticApproximationFamily}
  {F : EuclideanYangMillsProjectiveCylinderFamily}
  {L : EuclideanYangMillsProjectiveLimitMeasure F}
  (D : FiniteWilsonOSAutomaticConstructedTransferOrbitAnalyticLimitConstructionData W F L)

noncomputable def finite_wilson_constructed_transfer_orbit_analytic_data_compile_smoke :
    FiniteWilsonOSAutomaticConstructedHamiltonianTransferAnalyticLimitConstructionData W F L :=
  D.toConstructedHamiltonianTransferAnalyticData

theorem finite_wilson_constructed_transfer_orbit_four_properties_compile_smoke :
    D.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.reflectionLimit.ContinuumReflectionPositive ∧
      D.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.euclideanLimit.toEuclideanInvarianceLimitData.ContinuumEuclideanInvariant ∧
      D.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.clusterLimit.toClusterLimitData.ContinuumClusterProperty ∧
      D.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.regularityLimit.toRegularityLimitData.ContinuumRegularity :=
  finite_wilson_os_constructed_transfer_orbit_four_limit_properties D

theorem finite_wilson_constructed_transfer_orbit_assembly_continuum_bound_compile_smoke
    (O : D.clusterOrbit.Observable) (r : ℕ) :
    ‖D.clusterOrbit.continuumConnectedCorrelation O r‖ ≤
      D.clusterOrbit.decayAmplitude O * exactGapClusterContractionRatio ^ r :=
  finite_wilson_os_constructed_transfer_orbit_continuum_bound D O r

theorem finite_wilson_constructed_transfer_orbit_package_ready_compile_smoke :
    D.toConstructedHamiltonianTransferAnalyticData.toHamiltonianEigenactionAnalyticData.toFiniteDimensionalHamiltonianAnalyticData.toOrthonormalEigenbasisAnalyticData.toFiniteSpectralAnalyticData.toPositiveRayleighAnalyticData.toSymmetricRayleighAnalyticData.toTransferAnalyticData.toAutomaticData.toProjectiveLimitTransferData.toContinuumConstruction.toMeasurePackage.ready :=
  finite_wilson_os_constructed_transfer_orbit_continuum_measure_package_ready D

end

end MathlibAnalytic
end MGAP4D
