import MGAP4D.MathlibAnalytic.OrthonormalExponentialOperator
import MGAP4D.MathlibAnalytic.FiniteWilsonFiniteDimensionalHamiltonianConfluentSpectralWitness

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- The continuous-time exponential operator generated by the finite-dimensional
symmetric Wilson Hamiltonian. -/
noncomputable def
    FiniteWilsonOSAutomaticExactGapFiniteDimensionalHamiltonianContractionData.hamiltonianExponentialOperator
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (D : FiniteWilsonOSAutomaticExactGapFiniteDimensionalHamiltonianContractionData W)
    (n : ℕ) (t : NNReal) : D.StateSpace →L[ℝ] D.StateSpace :=
  LinearMap.IsSymmetric.exponentialOperator
    (D.hamiltonianSymmetric n) D.stateFinrank (t : ℝ)

/-- Every selected finite Wilson Hamiltonian eigenvector has the expected
`exp (-E t)` action under the generated continuous-time exponential operator. -/
theorem finite_wilson_hamiltonianExponentialOperator_apply_spectralVector
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {α : Type*}
    [DecidableEq α]
    (D : FiniteWilsonOSAutomaticExactGapFiniteDimensionalHamiltonianContractionData W)
    (n : ℕ)
    (value : α → ℝ)
    (nodes : Finset α)
    (orderCap : ℕ)
    (R : FiniteWilsonFiniteDimensionalHamiltonianConfluentSpectralWitnessData
      D n value nodes orderCap)
    (t : NNReal)
    (k : R.SpectralIndex) :
    D.hamiltonianExponentialOperator n t (R.spectralVector k) =
      Real.exp (-R.spectralValue k * (t : ℝ)) • R.spectralVector k := by
  change
    LinearMap.IsSymmetric.exponentialOperator
        (D.hamiltonianSymmetric n) D.stateFinrank (t : ℝ)
        ((D.hamiltonianSymmetric n).eigenvectorBasis D.stateFinrank k.1) =
      Real.exp
          (-((D.hamiltonianSymmetric n).eigenvalues D.stateFinrank k.1) *
            (t : ℝ)) •
        (D.hamiltonianSymmetric n).eigenvectorBasis D.stateFinrank k.1
  exact
    LinearMap.IsSymmetric.exponentialOperator_apply_eigenvectorBasis
      (D.hamiltonianSymmetric n) D.stateFinrank (t : ℝ) k.1

end

end MathlibAnalytic
end MGAP4D
