import MGAP4D.MathlibAnalytic.FiniteWilsonOSAutomaticExactGapVacuumOrthogonalRealSpectralHamiltonianSemigroupOperatorBoundedInputDifferencePairwiseInputToStateBundle

namespace MGAP4D
namespace MathlibAnalytic

#check intervalIntegral_exp_memory_mul_le_inputFloor
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_inputToState_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_inputToState_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_norm_sub_le_floor_add_epsilon_after_inputToState_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_norm_sub_le_floor_add_epsilon_after_inputToState_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_pointwise_inputToState_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_pointwise_inputToState_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_inputToState_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_inputToState_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_inputToState_bound_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_inputToState_bound_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_le_floor_add_epsilon_after_inputToState_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_le_floor_add_epsilon_after_inputToState_right
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_unitBall_matrixElement_sub_le_floor_add_epsilon_after_inputToState_left
#check orthonormalDiagonalHamiltonianSemigroup_operator_boundedInputDifference_pairwise_unitBall_matrixElement_sub_le_floor_add_epsilon_after_inputToState_right

#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_inputToState_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_inputToState_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_norm_sub_le_floor_add_epsilon_after_inputToState_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_norm_sub_le_floor_add_epsilon_after_inputToState_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_pointwise_inputToState_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_pointwise_inputToState_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_inputToState_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_inputToState_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_inputToState_bound_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_inputToState_bound_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_le_floor_add_epsilon_after_inputToState_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_le_floor_add_epsilon_after_inputToState_right
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_unitBall_matrixElement_sub_le_floor_add_epsilon_after_inputToState_left
#check finite_wilson_constructed_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_unitBall_matrixElement_sub_le_floor_add_epsilon_after_inputToState_right

#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_inputToState_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_inputToState_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_norm_sub_le_floor_add_epsilon_after_inputToState_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_norm_sub_le_floor_add_epsilon_after_inputToState_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_pointwise_inputToState_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_pointwise_inputToState_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_inputToState_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_inputToState_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_inputToState_bound_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_inputToState_bound_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_le_floor_add_epsilon_after_inputToState_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_matrixElement_sub_le_floor_add_epsilon_after_inputToState_right
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_unitBall_matrixElement_sub_le_floor_add_epsilon_after_inputToState_left
#check finite_wilson_vacuum_orthogonal_real_spectral_hamiltonianSemigroup_operator_boundedInputDifference_pairwise_unitBall_matrixElement_sub_le_floor_add_epsilon_after_inputToState_right

end MathlibAnalytic
end MGAP4D
