import MGAP4D.MathlibAnalytic.LinearMarkovInfinitePathCylinderIntegral
import MGAP4D.MathlibAnalytic.LinearMarkovInfinitePathShiftInvariance
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory
open scoped BigOperators ENNReal

noncomputable section

/-- A one-coordinate observable supported at the strictly positive natural time
`time + 1`. -/
def linearMarkovPositiveTimeCoordinate
    {Ω : Type*}
    (time : ℕ)
    (f : Ω → ℝ) :
    (ℕ → Ω) → ℝ :=
  fun path => f (path (time + 1))

/-- The set of all one-coordinate observables at strictly positive natural times. -/
def linearMarkovPositiveTimeCoordinateSet
    {Ω : Type*} :
    Set ((ℕ → Ω) → ℝ) :=
  { F | ∃ time f, F = linearMarkovPositiveTimeCoordinate time f }

/-- The real algebra of finite positive-time cylinder observables on natural-time
path space.  It is generated by arbitrary real observables of coordinates
`path 1`, `path 2`, and so on. -/
def linearMarkovPositiveTimeCylinderSubalgebra
    {Ω : Type*} :
    Subalgebra ℝ ((ℕ → Ω) → ℝ) :=
  Algebra.adjoin ℝ (linearMarkovPositiveTimeCoordinateSet (Ω := Ω))

/-- Every strictly positive one-coordinate observable belongs to the positive-time
cylinder algebra. -/
theorem linearMarkovPositiveTimeCoordinate_mem
    {Ω : Type*}
    (time : ℕ)
    (f : Ω → ℝ) :
    linearMarkovPositiveTimeCoordinate time f ∈
      linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω) :=
  Algebra.subset_adjoin ⟨time, f, rfl⟩

/-- Pull back real path observables along the one-step left shift. -/
def linearMarkovPathShiftPullbackAlgHom
    {Ω : Type*} :
    ((ℕ → Ω) → ℝ) →ₐ[ℝ] ((ℕ → Ω) → ℝ) where
  toFun := fun F => F ∘ linearMarkovPathShift
  map_one' := rfl
  map_mul' := by
    intro F G
    rfl
  map_zero' := rfl
  map_add' := by
    intro F G
    rfl
  commutes' := by
    intro r
    rfl

/-- Shift pullback advances every positive coordinate generator by one time step. -/
@[simp]
theorem linearMarkovPathShiftPullbackAlgHom_positiveTimeCoordinate
    {Ω : Type*}
    (time : ℕ)
    (f : Ω → ℝ) :
    linearMarkovPathShiftPullbackAlgHom
        (linearMarkovPositiveTimeCoordinate time f) =
      linearMarkovPositiveTimeCoordinate (time + 1) f := by
  funext path
  rfl

/-- The one-step left shift preserves the positive-time cylinder algebra. -/
theorem linearMarkovPositiveTimeCylinderSubalgebra_shift_closed
    {Ω : Type*}
    {F : (ℕ → Ω) → ℝ}
    (hF : F ∈ linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)) :
    linearMarkovPathShiftPullbackAlgHom F ∈
      linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω) := by
  change F ∈
    (linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)).comap
      linearMarkovPathShiftPullbackAlgHom
  apply (Algebra.adjoin_le (S :=
    (linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)).comap
      linearMarkovPathShiftPullbackAlgHom))
  intro G hG
  rcases hG with ⟨time, f, rfl⟩
  change linearMarkovPathShiftPullbackAlgHom
      (linearMarkovPositiveTimeCoordinate time f) ∈
    linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)
  rw [linearMarkovPathShiftPullbackAlgHom_positiveTimeCoordinate]
  exact linearMarkovPositiveTimeCoordinate_mem (time + 1) f

/-- The concrete one-step positive-time translation endomorphism. -/
def linearMarkovPositiveTimeShiftAlgHom
    {Ω : Type*} :
    linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω) →ₐ[ℝ]
      linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω) where
  toFun := fun F =>
    ⟨linearMarkovPathShiftPullbackAlgHom F.1,
      linearMarkovPositiveTimeCylinderSubalgebra_shift_closed F.2⟩
  map_one' := rfl
  map_mul' := by
    intro F G
    rfl
  map_zero' := rfl
  map_add' := by
    intro F G
    rfl
  commutes' := by
    intro r
    rfl

@[simp]
theorem linearMarkovPositiveTimeShiftAlgHom_apply
    {Ω : Type*}
    (F : linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)) :
    ((linearMarkovPositiveTimeShiftAlgHom F :
      linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)) :
        (ℕ → Ω) → ℝ) =
      F.1 ∘ linearMarkovPathShift :=
  rfl

/-- Every generator of the positive-time cylinder algebra is measurable on a
finite discrete state space. -/
theorem measurable_linearMarkovPositiveTimeCoordinate
    {Ω : Type*} [Fintype Ω]
    [MeasurableSpace Ω] [DiscreteMeasurableSpace Ω]
    (time : ℕ)
    (f : Ω → ℝ) :
    Measurable (linearMarkovPositiveTimeCoordinate time f) := by
  exact (measurable_of_finite f).comp (measurable_pi_apply (time + 1))

/-- Every element of the generated positive-time cylinder algebra is measurable. -/
theorem measurable_of_mem_linearMarkovPositiveTimeCylinderSubalgebra
    {Ω : Type*} [Fintype Ω]
    [MeasurableSpace Ω] [DiscreteMeasurableSpace Ω]
    {F : (ℕ → Ω) → ℝ}
    (hF : F ∈ linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)) :
    Measurable F := by
  exact Algebra.adjoin_induction
    (p := fun G _ => Measurable G)
    (fun G hG => by
      rcases hG with ⟨time, f, rfl⟩
      exact measurable_linearMarkovPositiveTimeCoordinate time f)
    (fun _ => measurable_const)
    (fun _ _ _ _ hG hH => hG.add hH)
    (fun _ _ _ _ hG hH => hG.mul hH)
    hF

/-- Subtype form of measurability for positive-time cylinder observables. -/
theorem measurable_linearMarkovPositiveTimeCylinder
    {Ω : Type*} [Fintype Ω]
    [MeasurableSpace Ω] [DiscreteMeasurableSpace Ω]
    (F : linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)) :
    Measurable (F : (ℕ → Ω) → ℝ) :=
  measurable_of_mem_linearMarkovPositiveTimeCylinderSubalgebra F.2

/-- A finite product cylinder supported at the consecutive positive times
`1, ..., n + 1`. -/
def linearMarkovPositiveTimePathProduct
    {Ω : Type*}
    {n : ℕ}
    (fs : Fin (n + 1) → Ω → ℝ) :
    (ℕ → Ω) → ℝ :=
  ∏ i : Fin (n + 1),
    linearMarkovPositiveTimeCoordinate i.1 (fs i)

/-- Positive-time products are exactly ordinary initial product cylinders pulled
back along the left shift. -/
theorem linearMarkovPositiveTimePathProduct_eq_shiftPullback
    {Ω : Type*}
    {n : ℕ}
    (fs : Fin (n + 1) → Ω → ℝ) :
    linearMarkovPositiveTimePathProduct fs =
      linearMarkovPathShiftPullbackAlgHom
        (linearMarkovInfinitePathProduct fs) := by
  funext path
  simp [linearMarkovPositiveTimePathProduct,
    linearMarkovPositiveTimeCoordinate,
    linearMarkovPathShiftPullbackAlgHom,
    linearMarkovInfinitePathProduct,
    linearMarkovPathShift]

/-- Every consecutive positive-time product cylinder belongs to the generated
positive-time algebra. -/
theorem linearMarkovPositiveTimePathProduct_mem
    {Ω : Type*}
    {n : ℕ}
    (fs : Fin (n + 1) → Ω → ℝ) :
    linearMarkovPositiveTimePathProduct fs ∈
      linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω) := by
  classical
  unfold linearMarkovPositiveTimePathProduct
  exact Subalgebra.prod_mem _ fun i _ =>
    linearMarkovPositiveTimeCoordinate_mem i.1 (fs i)

/-- Integration is invariant under one-step shift pullback for every strongly
measurable observable of a stationary finite-state Markov path law. -/
theorem linearMarkovInfinitePathMeasure_integral_shiftPullback_of_expectation_stationary
    {Ω : Type*} [Fintype Ω]
    [MeasurableSpace Ω] [DiscreteMeasurableSpace Ω]
    (initial : PMF Ω)
    (transition : Ω → PMF Ω)
    (hstationary : ∀ f : Ω → ℝ,
      finitePMFExpectationReal initial
          (fun x => finitePMFExpectationReal (transition x) f) =
        finitePMFExpectationReal initial f)
    (F : (ℕ → Ω) → ℝ)
    (hF : StronglyMeasurable F) :
    (∫ path, linearMarkovPathShiftPullbackAlgHom F path
      ∂linearMarkovInfinitePathMeasure initial transition) =
      ∫ path, F path
        ∂linearMarkovInfinitePathMeasure initial transition := by
  calc
    (∫ path, linearMarkovPathShiftPullbackAlgHom F path
      ∂linearMarkovInfinitePathMeasure initial transition) =
        ∫ path, F path
          ∂(linearMarkovInfinitePathMeasure initial transition).map
            linearMarkovPathShift := by
              symm
              exact MeasureTheory.integral_map_of_stronglyMeasurable
                measurable_linearMarkovPathShift hF
    _ = ∫ path, F path
        ∂linearMarkovInfinitePathMeasure initial transition := by
          rw [linearMarkovInfinitePathMeasure_map_shift_of_expectation_stationary
            initial transition hstationary]

/-- The stationary path expectation is preserved by the concrete positive-time
translation endomorphism. -/
theorem linearMarkovPositiveTimeCylinder_integral_shift
    {Ω : Type*} [Fintype Ω]
    [MeasurableSpace Ω] [DiscreteMeasurableSpace Ω]
    (initial : PMF Ω)
    (transition : Ω → PMF Ω)
    (hstationary : ∀ f : Ω → ℝ,
      finitePMFExpectationReal initial
          (fun x => finitePMFExpectationReal (transition x) f) =
        finitePMFExpectationReal initial f)
    (F : linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)) :
    (∫ path,
        (linearMarkovPositiveTimeShiftAlgHom F :
          linearMarkovPositiveTimeCylinderSubalgebra (Ω := Ω)) path
      ∂linearMarkovInfinitePathMeasure initial transition) =
      ∫ path, F path
        ∂linearMarkovInfinitePathMeasure initial transition := by
  exact linearMarkovInfinitePathMeasure_integral_shiftPullback_of_expectation_stationary
    initial transition hstationary F
    (measurable_linearMarkovPositiveTimeCylinder F).stronglyMeasurable

/-- Every consecutive positive-time product has the same expectation as the
corresponding initial product, hence the same backward cylinder moment. -/
theorem linearMarkovInfinitePathMeasure_positiveTime_cylinder_integral
    {Ω : Type*} [Fintype Ω]
    [MeasurableSpace Ω] [DiscreteMeasurableSpace Ω]
    (initial : PMF Ω)
    (transition : Ω → PMF Ω)
    (hstationary : ∀ f : Ω → ℝ,
      finitePMFExpectationReal initial
          (fun x => finitePMFExpectationReal (transition x) f) =
        finitePMFExpectationReal initial f)
    (n : ℕ)
    (fs : Fin (n + 1) → Ω → ℝ) :
    (∫ path, linearMarkovPositiveTimePathProduct fs path
      ∂linearMarkovInfinitePathMeasure initial transition) =
      linearMarkovCylinderMoment
        (finitePMFExpectationReal initial)
        (finitePMFTransitionExpectationLinearMap transition)
        (List.ofFn fs) := by
  rw [linearMarkovPositiveTimePathProduct_eq_shiftPullback]
  rw [linearMarkovInfinitePathMeasure_integral_shiftPullback_of_expectation_stationary
    initial transition hstationary]
  · exact linearMarkovInfinitePathMeasure_cylinder_integral
      initial transition n fs
  · rw [linearMarkovInfinitePathProduct_eq_comp_finPrefix]
    exact (stronglyMeasurable_linearMarkovFinitePathProduct n fs).comp_measurable
      (measurable_linearMarkovInfinitePathFinPrefix n)

end

end MathlibAnalytic
end MGAP4D
