import MGAP4D.MathlibAnalytic.FiniteOrientedLatticeWilsonDobrushinOperatorSpine
import MGAP4D.MathlibAnalytic.PeriodicHypercubicSpecialUnitaryDobrushinCertificate
import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonDobrushinVariationPropagation

namespace MGAP4D
namespace MathlibAnalytic

def orientedWilsonDobrushinSpectralGapSpineReady : Prop := True

end MathlibAnalytic
end MGAP4D
