import MGAP4D.MathlibAnalytic.AxiomaticYangMillsExactGapSpectralCore
import MGAP4D.MathlibAnalytic.OSWightmanMassGapDefinitionBridge

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-!
Reduced OS/Wightman reconstruction and definition bridges generated from an
attained exact Hamiltonian mass gap.

The existing reconstruction spine requires a full axiomatic model, including
independently supplied first-excitation and mass-gap-value fields.  The reduced
spine below asks only for the exact-gap spectral core and constructs the full
model canonically.  The reduced definition bridge likewise derives positive
energy and vacuum isolation from the Hamiltonian mass-gap theorem rather than
requesting separate axiom-to-spectrum maps.
-/

/-- Reduced OS/Wightman reconstruction input whose full axiomatic model is
constructed from an attained exact Hamiltonian mass gap. -/
structure OSWightmanExactGapHamiltonianReconstructionSpine where
  axioms : OSWightmanYangMillsAxioms
  spectralCore : FourDimensionalYangMillsExactGapSpectralCore
  core_uses_axioms : spectralCore.osWightman = axioms
  axioms_ready : axioms.ready

/-- Convert the reduced reconstruction input to the existing full reconstruction
spine.  The exact-gap identification is definitional. -/
def OSWightmanExactGapHamiltonianReconstructionSpine.toReconstructionSpine
    (S : OSWightmanExactGapHamiltonianReconstructionSpine) :
    OSWightmanHamiltonianReconstructionSpine where
  axioms := S.axioms
  model := S.spectralCore.toAxiomaticModel
  model_uses_axioms := by
    change S.spectralCore.osWightman = S.axioms
    exact S.core_uses_axioms
  axioms_ready := S.axioms_ready
  exact_gap_value_identified := rfl

/-- The generated reconstruction model is ready for the OS/Wightman closure. -/
theorem OSWightmanExactGapHamiltonianReconstructionSpine.modelReady
    (S : OSWightmanExactGapHamiltonianReconstructionSpine) :
    S.spectralCore.toAxiomaticModel.osWightman.ready := by
  exact os_wightman_reconstruction_model_ready S.toReconstructionSpine

/-- The reduced reconstruction spine has the model-level mass-gap theorem. -/
theorem OSWightmanExactGapHamiltonianReconstructionSpine.hasMassGap
    (S : OSWightmanExactGapHamiltonianReconstructionSpine) :
    S.spectralCore.toAxiomaticModel.hasMassGap := by
  exact S.spectralCore.toAxiomaticModel_hasMassGap

/-- Exact-gap positivity is a direct field consequence of the reduced spectral
core. -/
theorem OSWightmanExactGapHamiltonianReconstructionSpine.exactGapPositive
    (S : OSWightmanExactGapHamiltonianReconstructionSpine) :
    0 < exactGapValueReal := by
  exact S.spectralCore.exactHamiltonianMassGap.1

/-- The reduced reconstruction spine identifies the exact gap with the
non-vacuum spectral infimum. -/
theorem OSWightmanExactGapHamiltonianReconstructionSpine.exactGapThreshold
    (S : OSWightmanExactGapHamiltonianReconstructionSpine) :
    exactGapValueReal =
      sInf
        (S.spectralCore.toAxiomaticModel.energySpectrum \ ({0} : Set ℝ)) := by
  exact S.spectralCore.sInfNonvacuumEqExactGap.symm

/-- The generated first excitation is definitionally the exact gap. -/
theorem OSWightmanExactGapHamiltonianReconstructionSpine.firstExcitationEqExactGap
    (S : OSWightmanExactGapHamiltonianReconstructionSpine) :
    S.spectralCore.toAxiomaticModel.firstExcitation = exactGapValueReal := by
  rfl

/-- The generated displayed mass-gap value is definitionally the exact gap. -/
theorem OSWightmanExactGapHamiltonianReconstructionSpine.massGapValueEqExactGap
    (S : OSWightmanExactGapHamiltonianReconstructionSpine) :
    S.spectralCore.toAxiomaticModel.massGapValue = exactGapValueReal := by
  rfl

/-- Reduced definition-level bridge.

Positive energy and vacuum isolation are absent from the input surface because
they are generated by `HasHamiltonianMassGap`. -/
structure OSWightmanExactGapDefinitionBridge where
  spine : OSWightmanExactGapHamiltonianReconstructionSpine
  hamiltonianSelfAdjoint_proof :
    spine.spectralCore.hamiltonianSelfAdjoint
  spectralPVM_detects_energySpectrum :
    ∀ E : ℝ, E ∈ spine.spectralCore.energySpectrum →
      ∃ ψ : spine.spectralCore.H,
        ψ ∈ spine.spectralCore.spectralPVM ({E} : Set ℝ)
  vacuumSpectralPoint :
    spine.spectralCore.vacuum ∈
      spine.spectralCore.spectralPVM ({0} : Set ℝ)

/-- Convert the reduced exact-gap bridge to the existing full definition bridge.
The two formerly independent positive-energy and vacuum-isolation maps are
filled by general Hamiltonian mass-gap theorems. -/
def OSWightmanExactGapDefinitionBridge.toDefinitionBridge
    (B : OSWightmanExactGapDefinitionBridge) :
    OSWightmanMassGapDefinitionBridge where
  spine := B.spine.toReconstructionSpine
  hamiltonianSelfAdjoint_proof := B.hamiltonianSelfAdjoint_proof
  spectralPVM_detects_energySpectrum := B.spectralPVM_detects_energySpectrum
  vacuumSpectralPoint := B.vacuumSpectralPoint
  positiveEnergy_from_wightmanSpectrum := fun _hSpectrum =>
    B.spine.spectralCore.positiveEnergy
  vacuumIsolation_from_osCluster := fun _hCluster =>
    B.spine.spectralCore.vacuumIsolated

/-- The converted definition bridge uses exactly the canonically generated full
model. -/
theorem OSWightmanExactGapDefinitionBridge.toDefinitionBridge_model
    (B : OSWightmanExactGapDefinitionBridge) :
    B.toDefinitionBridge.spine.model =
      B.spine.spectralCore.toAxiomaticModel := by
  rfl

/-- The reduced bridge derives positive energy without a separately supplied
Wightman-spectrum map. -/
theorem OSWightmanExactGapDefinitionBridge.positiveEnergy
    (B : OSWightmanExactGapDefinitionBridge) :
    ∀ E ∈ B.spine.spectralCore.energySpectrum, 0 ≤ E := by
  exact B.spine.spectralCore.positiveEnergy

/-- The reduced bridge derives exact vacuum isolation without a separately
supplied cluster-to-isolation map. -/
theorem OSWightmanExactGapDefinitionBridge.vacuumIsolated
    (B : OSWightmanExactGapDefinitionBridge) :
    Set.Ioo 0 exactGapValueReal ∩
      B.spine.spectralCore.energySpectrum = ∅ := by
  exact hasHamiltonianMassGap_vacuum_isolated
    B.spine.spectralCore.exactHamiltonianMassGap

/-- The attained exact gap is detected by the reduced bridge spectral PVM. -/
theorem OSWightmanExactGapDefinitionBridge.exactGapPVMDetected
    (B : OSWightmanExactGapDefinitionBridge) :
    ∃ ψ : B.spine.spectralCore.H,
      ψ ∈ B.spine.spectralCore.spectralPVM
        ({exactGapValueReal} : Set ℝ) := by
  exact B.spectralPVM_detects_energySpectrum
    exactGapValueReal B.spine.spectralCore.exactGapAttained

/-- The reduced bridge produces the existing full model-level mass-gap theorem. -/
theorem OSWightmanExactGapDefinitionBridge.hasMassGap
    (B : OSWightmanExactGapDefinitionBridge) :
    B.toDefinitionBridge.spine.model.hasMassGap := by
  exact os_wightman_bridge_mass_gap_definition B.toDefinitionBridge

/-- The reduced bridge produces exact-gap positivity through the existing public
bridge theorem. -/
theorem OSWightmanExactGapDefinitionBridge.exactGapPositive
    (B : OSWightmanExactGapDefinitionBridge) :
    0 < exactGapValueReal := by
  exact os_wightman_bridge_exact_gap_positive B.toDefinitionBridge

/-- The reduced bridge produces the exact non-vacuum spectral-threshold identity
through the existing public bridge theorem. -/
theorem OSWightmanExactGapDefinitionBridge.exactGapThreshold
    (B : OSWightmanExactGapDefinitionBridge) :
    exactGapValueReal =
      sInf
        (B.toDefinitionBridge.spine.model.energySpectrum \ ({0} : Set ℝ)) := by
  exact os_wightman_bridge_exact_gap_spectral_threshold B.toDefinitionBridge

/-- Certificate for the dependency-reduced reconstruction and definition bridge. -/
structure OSWightmanExactGapReducedReconstructionCertificate
    (B : OSWightmanExactGapDefinitionBridge) where
  fullBridge : OSWightmanMassGapDefinitionBridge
  fullBridgeEq : fullBridge = B.toDefinitionBridge
  modelReady : B.toDefinitionBridge.spine.model.osWightman.ready
  massGap : B.toDefinitionBridge.spine.model.hasMassGap
  exactGapPositive : 0 < exactGapValueReal
  exactGapThreshold :
    exactGapValueReal =
      sInf
        (B.toDefinitionBridge.spine.model.energySpectrum \ ({0} : Set ℝ))
  positiveEnergy :
    ∀ E ∈ B.spine.spectralCore.energySpectrum, 0 ≤ E
  vacuumIsolated :
    Set.Ioo 0 exactGapValueReal ∩
      B.spine.spectralCore.energySpectrum = ∅
  exactGapPVMDetected :
    ∃ ψ : B.spine.spectralCore.H,
      ψ ∈ B.spine.spectralCore.spectralPVM
        ({exactGapValueReal} : Set ℝ)

/-- Canonical certificate for the reduced exact-gap bridge. -/
def osWightmanExactGapReducedReconstructionCertificate
    (B : OSWightmanExactGapDefinitionBridge) :
    OSWightmanExactGapReducedReconstructionCertificate B where
  fullBridge := B.toDefinitionBridge
  fullBridgeEq := rfl
  modelReady := os_wightman_reconstruction_model_ready
    B.toDefinitionBridge.spine
  massGap := B.hasMassGap
  exactGapPositive := B.exactGapPositive
  exactGapThreshold := B.exactGapThreshold
  positiveEnergy := B.positiveEnergy
  vacuumIsolated := B.vacuumIsolated
  exactGapPVMDetected := B.exactGapPVMDetected

/-- Compact theorem endpoint for the reduced reconstruction route. -/
theorem osWightmanExactGapReducedReconstruction_complete
    (B : OSWightmanExactGapDefinitionBridge) :
    B.toDefinitionBridge.spine.model.hasMassGap ∧
      0 < exactGapValueReal ∧
      exactGapValueReal =
        sInf
          (B.toDefinitionBridge.spine.model.energySpectrum \ ({0} : Set ℝ)) ∧
      (∀ E ∈ B.spine.spectralCore.energySpectrum, 0 ≤ E) ∧
      Set.Ioo 0 exactGapValueReal ∩
        B.spine.spectralCore.energySpectrum = ∅ ∧
      ∃ ψ : B.spine.spectralCore.H,
        ψ ∈ B.spine.spectralCore.spectralPVM
          ({exactGapValueReal} : Set ℝ) := by
  exact ⟨
    B.hasMassGap,
    B.exactGapPositive,
    B.exactGapThreshold,
    B.positiveEnergy,
    B.vacuumIsolated,
    B.exactGapPVMDetected⟩

end

end MathlibAnalytic
end MGAP4D
