import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointKernelSectionMeasurePresentation

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumSquareMeasure
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabVacuumMeasure_eq_continuousVacuumSquareMeasure
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointFixedLeftContinuousMeasure
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointMeasure_eq_fixedLeftContinuousMeasure

end MGAP4D.MathlibAnalytic
