import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenWilsonGibbsBoundaryOpenHalfProductL2
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSApproximatingBoundaryL2TransferGap
import MGAP4D.MathlibAnalytic.RealL2HilbertSchmidtRectangularKernelOperator
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory
open scoped InnerProductSpace

noncomputable section

local instance boundaryHilbertSchmidtAnalysisSideLengthNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance boundaryHilbertSchmidtAnalysisSpecialUnitaryIsTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance boundaryHilbertSchmidtAnalysisSpecialUnitaryCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance boundaryHilbertSchmidtAnalysisSpecialUnitarySecondCountableTopology (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance boundaryHilbertSchmidtAnalysisSpecialUnitaryMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance boundaryHilbertSchmidtAnalysisSpecialUnitaryBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- The actual positive-open-half compact-Haar `L²` Hilbert space. -/
abbrev PeriodicHypercubicEvenSpecialUnitaryOpenHalfL2
    (H N : ℕ) : Type :=
  Lp ℝ 2 (periodicHypercubicEvenOpenHalfHaarMeasure H N)

/-- Canonical real Hilbert--Schmidt analysis operator generated by the actual
compact-Haar Wilson boundary/open-half product feature

`Φ(b,x) = sqrt ρ(b,x,θx)`.

No analysis map and no mass scale are postulated.  The bounded operator is
constructed from the theorem-generated product-`L²` kernel by the generic
Fréchet--Riesz/Hilbert--Schmidt machinery. -/
noncomputable def periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
    (H N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ) (hbeta : 0 ≤ beta) :
    PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 H N →L[ℝ]
      PeriodicHypercubicEvenSpecialUnitaryOpenHalfL2 H N := by
  let boundaryMeasure := periodicHypercubicEvenBoundaryHaarMeasure H N
  let halfMeasure := periodicHypercubicEvenOpenHalfHaarMeasure H N
  letI : IsFiniteMeasure boundaryMeasure := by
    dsimp [boundaryMeasure, periodicHypercubicEvenBoundaryHaarMeasure,
      FiniteInvolutiveEdgeOrbitPartition.boundaryPiMeasure]
    infer_instance
  letI : IsFiniteMeasure halfMeasure := by
    dsimp [halfMeasure, periodicHypercubicEvenOpenHalfHaarMeasure,
      FiniteInvolutiveEdgeOrbitPartition.openHalfPiMeasure]
    infer_instance
  exact
    realL2HilbertSchmidtRectangularKernelOperator
      (μ := boundaryMeasure)
      (ν := halfMeasure)
      (periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2
        H N hN beta hbeta)

/-- Exact matrix coefficient of the actual Wilson Hilbert--Schmidt analysis
operator. -/
theorem periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis_inner
    (H N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ) (hbeta : 0 ≤ beta)
    (f : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 H N)
    (g : PeriodicHypercubicEvenSpecialUnitaryOpenHalfL2 H N) :
    inner ℝ
        (periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
          H N hN beta hbeta f) g =
      realL2HilbertSchmidtKernelPairing
        (periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2
          H N hN beta hbeta)
        f g := by
  let boundaryMeasure := periodicHypercubicEvenBoundaryHaarMeasure H N
  let halfMeasure := periodicHypercubicEvenOpenHalfHaarMeasure H N
  letI : IsFiniteMeasure boundaryMeasure := by
    dsimp [boundaryMeasure, periodicHypercubicEvenBoundaryHaarMeasure,
      FiniteInvolutiveEdgeOrbitPartition.boundaryPiMeasure]
    infer_instance
  letI : IsFiniteMeasure halfMeasure := by
    dsimp [halfMeasure, periodicHypercubicEvenOpenHalfHaarMeasure,
      FiniteInvolutiveEdgeOrbitPartition.openHalfPiMeasure]
    infer_instance
  exact
    realL2HilbertSchmidtRectangularKernelOperator_inner
      (μ := boundaryMeasure)
      (ν := halfMeasure)
      (periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2
        H N hN beta hbeta)
      f g

/-- The actual Wilson analysis operator norm is bounded by the explicit
boundary/open-half product-`L²` kernel norm. -/
theorem periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis_norm_le
    (H N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ) (hbeta : 0 ≤ beta) :
    ‖periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
        H N hN beta hbeta‖ ≤
      ‖periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2
        H N hN beta hbeta‖ := by
  let boundaryMeasure := periodicHypercubicEvenBoundaryHaarMeasure H N
  let halfMeasure := periodicHypercubicEvenOpenHalfHaarMeasure H N
  letI : IsFiniteMeasure boundaryMeasure := by
    dsimp [boundaryMeasure, periodicHypercubicEvenBoundaryHaarMeasure,
      FiniteInvolutiveEdgeOrbitPartition.boundaryPiMeasure]
    infer_instance
  letI : IsFiniteMeasure halfMeasure := by
    dsimp [halfMeasure, periodicHypercubicEvenOpenHalfHaarMeasure,
      FiniteInvolutiveEdgeOrbitPartition.openHalfPiMeasure]
    infer_instance
  exact
    realL2HilbertSchmidtRectangularKernelOperator_norm_le
      (μ := boundaryMeasure)
      (ν := halfMeasure)
      (periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2
        H N hN beta hbeta)

/-- Squared operator norm bound written directly as the actual compact-Haar
integral of the squared Wilson product feature. -/
theorem periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis_norm_sq_le_integral
    (H N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ) (hbeta : 0 ≤ beta) :
    ‖periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
        H N hN beta hbeta‖ ^ 2 ≤
      ∫ p,
        ‖periodicHypercubicEvenBoundaryCompletedPositiveGramFeature
          H N hN beta hbeta p.1 p.2‖ ^ 2
        ∂(periodicHypercubicEvenBoundaryOpenHalfHaarMeasure H N) := by
  have h := periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis_norm_le
    H N hN beta hbeta
  have hnonneg :
      0 ≤ ‖periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
        H N hN beta hbeta‖ := norm_nonneg _
  have hk :
      0 ≤ ‖periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2
        H N hN beta hbeta‖ := norm_nonneg _
  rw [← periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2_norm_sq
    H N hN beta hbeta]
  nlinarith

end

end MathlibAnalytic
end MGAP4D
