import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointStageResidualPathLoss

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweep_canonicalPrefix_stageResidual_normalized_sq_sum_eq_sweepPathLoss
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweep_canonicalPrefix_stageResidual_sq_sum_eq_six_mul_sweepPathLoss
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweep_canonicalPrefix_stageResidual_sq_sum_le_six_mul_residualEnergy
#check exists_periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweep_linkIndexedRepresentatives_fullResponseL2Sum_vacuum_lintegral_le_responseResidualCoefficient_mul_sixSweepPathLoss_ofReal

end MGAP4D.MathlibAnalytic
