import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourcePairSweepStageResponseEnergy

namespace MGAP4D.MathlibAnalytic

#check exists_periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweep_linkIndexedRepresentatives_canonicalFiberVariance_sum_le_localProfile_sq_sum_ofReal
#check exists_periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweep_linkIndexedRepresentatives_responseAmplitude_vacuum_lintegral_le_responseResidualCoefficient_mul_localProfile_sq_sum_ofReal

end MGAP4D.MathlibAnalytic
