import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointOneLinkCanonicalFiberVarianceKernelSectionResidual

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkCanonicalFiberVarianceFunctional_eq_joint_canonicalFiberMean_residual_lintegral
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkCanonicalFiberVarianceFunctional_eq_vacuum_kernelSection_canonicalFiberMean_residual_lintegral
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLink_vacuum_kernelSection_canonicalFiberMean_residual_lintegral_le_condExpL2_residual_norm_sq

end MGAP4D.MathlibAnalytic
