import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenPrimaryBoundaryPhysicalFloorRationalScalarFactorialOSHilbertDirectLimitRegularYosidaStrongConvergence
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Normed.Ring.Lemmas
import Mathlib.Tactic

/-!
# Bounded Yosida exponential semigroups on the same-root regular OS Hilbert sector

For each dyadic bounded Yosida Hamiltonian `Hₙ = H_{2^n}`, the Banach algebra of continuous
linear endomorphisms of the regular Hilbert sector admits the ordinary exponential.  We therefore
construct

`Eₙ(t) = exp (t • (-Hₙ))`.

This layer records the exact exponential semigroup law, operator-norm continuity, and the
Banach-algebra derivative

`Eₙ'(t) = Eₙ(t) * (-Hₙ)`.

The construction is then restricted from real time to `NNReal`.  No spectral functional calculus
and no identification with the original OS semigroup is used here.
-/

namespace MGAP4D
namespace MathlibAnalytic

open Filter Set Topology NormedSpace
open scoped InnerProductSpace LinearPMap

noncomputable section

namespace PrimaryScalarFixedSlotOSPreHilbertData

variable {H : ℕ → ℕ}
variable {N : ℕ} {hN : 0 < N}
variable [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
variable {beta : ℕ → ℝ} {hbeta : ∀ n, 0 ≤ beta n}
variable {L :
  PeriodicHypercubicEvenPrimarySpatialPhysicalFloorRationalScalarPlaquettePathProkhorovSubsequenceLimit
    H N hN beta hbeta
    periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing}

/- Pin only the topological-ring proposition locally.  The canonical `ContinuousLinearMap`
operator-norm `NormedRing` instance must remain untouched so that the existing additive and
real-scalar module structures stay definitionally aligned. -/
local instance regularOperatorIsTopologicalRing
    {K : Type*} [NormedAddCommGroup K] [NormedSpace ℝ K] :
    IsTopologicalRing (K →L[ℝ] K) :=
  NonUnitalSeminormedRing.toIsTopologicalRing

/-- Generic Banach-algebra semigroup law for the exponential scalar line through one bounded
real endomorphism.  The commutation goal is created by `exp_add_of_commute` itself, so its
multiplication instance is exactly the one used by the Banach-algebra theorem. -/
private theorem continuousLinearEndomorphism_exp_smul_add
    {K : Type*} [NormedAddCommGroup K] [NormedSpace ℝ K] [CompleteSpace K]
    (A : K →L[ℝ] K) (s t : ℝ) :
    NormedSpace.exp ((s + t) • A) =
      NormedSpace.exp (s • A) * NormedSpace.exp (t • A) := by
  letI : NormedAlgebra ℚ (K →L[ℝ] K) :=
    NormedAlgebra.restrictScalars ℚ ℝ (K →L[ℝ] K)
  rw [add_smul]
  apply NormedSpace.exp_add_of_commute
  change (s • A) * (t • A) = (t • A) * (s • A)
  ext x
  change s • A (t • A x) = t • A (s • A x)
  rw [A.map_smul, A.map_smul, smul_smul, smul_smul, mul_comm s t]

/-- Generic Banach-algebra derivative for the exponential of a bounded real endomorphism.
Keeping this helper independent of the large same-root dependent carrier prevents expensive
unification when it is specialized below. -/
private theorem continuousLinearEndomorphism_exp_smul_hasDerivAt
    {K : Type*} [NormedAddCommGroup K] [NormedSpace ℝ K] [CompleteSpace K]
    (A : K →L[ℝ] K) (t : ℝ) :
    HasDerivAt
      (fun r : ℝ => NormedSpace.exp (r • A))
      (NormedSpace.exp (t • A) * A) t := by
  exact hasDerivAt_exp_smul_const
    (𝕂 := ℝ) (𝔸 := K →L[ℝ] K) A t

/-- Generic operator-norm continuity of the exponential scalar line.  Keeping the projection from
`HasDerivAt` to `ContinuousAt` at this generic level avoids expensive dependent-type unification
when the result is specialized to the same-root regular carrier. -/
private theorem continuousLinearEndomorphism_exp_smul_continuous
    {K : Type*} [NormedAddCommGroup K] [NormedSpace ℝ K] [CompleteSpace K]
    (A : K →L[ℝ] K) :
    Continuous (fun t : ℝ => NormedSpace.exp (t • A)) := by
  rw [continuous_iff_continuousAt]
  intro t
  exact (continuousLinearEndomorphism_exp_smul_hasDerivAt A t).continuousAt

/-- The bounded negative dyadic Yosida generator `-H_{2^n}`. -/
noncomputable def fixedSlotHilbertDirectLimitRegularNegativeDyadicYosidaHamiltonian
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) :
    P.fixedSlotHilbertDirectLimitRegularSubspace →L[ℝ]
      P.fixedSlotHilbertDirectLimitRegularSubspace :=
  - P.fixedSlotHilbertDirectLimitRegularDyadicYosidaHamiltonian n

/-- Real-time bounded exponential generated by the negative dyadic Yosida Hamiltonian. -/
noncomputable def fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) (t : ℝ) :
    P.fixedSlotHilbertDirectLimitRegularSubspace →L[ℝ]
      P.fixedSlotHilbertDirectLimitRegularSubspace :=
  NormedSpace.exp
    (t • P.fixedSlotHilbertDirectLimitRegularNegativeDyadicYosidaHamiltonian n)

@[simp] theorem fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal_zero
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) :
    P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal n 0 = 1 := by
  let A :
      P.fixedSlotHilbertDirectLimitRegularSubspace →L[ℝ]
        P.fixedSlotHilbertDirectLimitRegularSubspace :=
    P.fixedSlotHilbertDirectLimitRegularNegativeDyadicYosidaHamiltonian n
  change NormedSpace.exp ((0 : ℝ) • A) = 1
  have hz : (0 : ℝ) • A = 0 := zero_smul ℝ A
  rw [hz]
  exact NormedSpace.exp_zero

/-- The bounded Yosida exponential has the exact additive real-time semigroup law. -/
theorem fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal_add
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) (s t : ℝ) :
    P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal n (s + t) =
      P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal n s *
        P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal n t := by
  letI : CompleteSpace P.fixedSlotHilbertDirectLimitRegularSubspace :=
    P.fixedSlotHilbertDirectLimitRegularSubspace_completeSpace
  let A :
      P.fixedSlotHilbertDirectLimitRegularSubspace →L[ℝ]
        P.fixedSlotHilbertDirectLimitRegularSubspace :=
    P.fixedSlotHilbertDirectLimitRegularNegativeDyadicYosidaHamiltonian n
  change
    NormedSpace.exp ((s + t) • A) =
      NormedSpace.exp (s • A) * NormedSpace.exp (t • A)
  exact continuousLinearEndomorphism_exp_smul_add A s t

/-- Banach-algebra derivative of the real-time bounded Yosida exponential. -/
theorem fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal_hasDerivAt
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) (t : ℝ) :
    HasDerivAt
      (fun r : ℝ => P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal n r)
      (P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal n t *
        P.fixedSlotHilbertDirectLimitRegularNegativeDyadicYosidaHamiltonian n)
      t := by
  let K := P.fixedSlotHilbertDirectLimitRegularSubspace
  letI : CompleteSpace K :=
    P.fixedSlotHilbertDirectLimitRegularSubspace_completeSpace
  let A : K →L[ℝ] K :=
    P.fixedSlotHilbertDirectLimitRegularNegativeDyadicYosidaHamiltonian n
  have hA : HasDerivAt
      (fun r : ℝ => NormedSpace.exp (r • A))
      (NormedSpace.exp (t • A) * A) t :=
    continuousLinearEndomorphism_exp_smul_hasDerivAt A t
  simpa only [fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal, K, A] using hA

/-- The real-time bounded Yosida exponential is continuous in operator norm. -/
theorem fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal_continuous
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) :
    Continuous
      (fun t : ℝ => P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal n t) := by
  let K := P.fixedSlotHilbertDirectLimitRegularSubspace
  letI : CompleteSpace K :=
    P.fixedSlotHilbertDirectLimitRegularSubspace_completeSpace
  let A : K →L[ℝ] K :=
    P.fixedSlotHilbertDirectLimitRegularNegativeDyadicYosidaHamiltonian n
  have hA : Continuous (fun t : ℝ => NormedSpace.exp (t • A)) :=
    continuousLinearEndomorphism_exp_smul_continuous A
  simpa only [fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal, K, A] using hA

/-- Positive-time restriction of the bounded dyadic Yosida exponential. -/
noncomputable def fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) (t : NNReal) :
    P.fixedSlotHilbertDirectLimitRegularSubspace →L[ℝ]
      P.fixedSlotHilbertDirectLimitRegularSubspace :=
  P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal n (t : ℝ)

@[simp] theorem fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential_zero
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) :
    P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n 0 = 1 := by
  exact P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal_zero n

/-- Exact additive semigroup law on nonnegative real time. -/
theorem fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential_add
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) (s t : NNReal) :
    P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n (s + t) =
      P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n s *
        P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n t := by
  simpa [fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential] using
    P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal_add n (s : ℝ) (t : ℝ)

/-- Operator-norm continuity of the positive-time bounded Yosida exponential. -/
theorem fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential_continuous
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) :
    Continuous
      (fun t : NNReal => P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n t) := by
  exact (P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponentialReal_continuous n).comp
    continuous_subtype_val

/-- The positive-time bounded exponential acts as an actual endomorphism semigroup. -/
theorem fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential_add_apply
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) (s t : NNReal)
    (y : P.fixedSlotHilbertDirectLimitRegularSubspace) :
    P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n (s + t) y =
      P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n s
        (P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n t y) := by
  rw [P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential_add n s t]
  rfl

/-- Bounded Yosida exponential package, prior to comparison with the original OS semigroup. -/
theorem fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential_package
    (P : PrimaryScalarFixedSlotOSPreHilbertData
      H N hN beta hbeta
      periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalFactorialLatticeSpacing L)
    (n : ℕ) :
    P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n 0 = 1 ∧
      (∀ s t : NNReal,
        P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n (s + t) =
          P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n s *
            P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n t) ∧
      Continuous
        (fun t : NNReal => P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential n t) := by
  exact ⟨P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential_zero n,
    P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential_add n,
    P.fixedSlotHilbertDirectLimitRegularDyadicYosidaExponential_continuous n⟩

end PrimaryScalarFixedSlotOSPreHilbertData

end
end MathlibAnalytic
end MGAP4D