import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateTargetSourceCommutatorCoefficient

namespace MGAP4D.MathlibAnalytic

#check realHilbertProjectionSweepTargetSourceCommutatorCoefficient

#check
  realHilbertProjectionSweepTargetCrossResidual_projected_norm_le_commutatorCoefficient_mul_norm

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTargetSourceCommutatorCoefficient

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTargetCrossResidual_projected_norm_le_commutatorCoefficient_mul_projectedNorm

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTargetCrossResidual_projected_norm_le_commutatorCoefficient_mul_norm

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTargetSourceCommutatorCoefficient_zero

end MGAP4D.MathlibAnalytic
