import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSweepStageLocalProfileExactResidual

namespace MGAP4D.MathlibAnalytic

#check realHilbertProjectionSweepStageResidualSqProfile_eq_zero_of_not_mem
#check realHilbertProjectionSweepStageResidualSqProfile_append_cons_eq_norm_sq
#check realHilbertProjectionSweepStageResidualAmplitude_append_cons_eq_norm
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageLocalProfile_eq_stageResidual_norm_of_canonicalPrefix
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweepStageLocalProfile_eq_stageResidual_norm_of_canonicalPrefix

end MGAP4D.MathlibAnalytic
