import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourceUpdateBackwardDirectVarianceVacuumResidual

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdate_referenceSourceResidual_currentValue_eq_targetKernelSectionResidualEnergy
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardDirectVarianceEnergy_currentValue_vacuum_lintegral_le_harnackLawFactor_mul_canonicalSourceFiberVariance
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardDirectVarianceEnergy_currentValue_vacuum_lintegral_le_harnackLawFactor_mul_condExpL2_sourceResidual

end MGAP4D.MathlibAnalytic
