import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousGroundStateFiberPosteriorJointAEBridge
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointOneLinkCanonicalMeanCondExpIdentification

/-! Contracts for the explicit posterior action on the genuine joint L2 carrier. -/

open MeasureTheory

#check integral_map_equiv
#check MGAP4D.MathlibAnalytic.GroundStateCanonicalMean.condExpL2_coeFn_eq_canonicalMean
#check MGAP4D.MathlibAnalytic.GroundStatePosteriorJoint.canonicalKernel_map_joint_ae_eq_posterior
#check MGAP4D.MathlibAnalytic.GroundStatePosteriorJoint.canonicalMean_joint_ae_eq_posteriorMean
#check MGAP4D.MathlibAnalytic.GroundStatePosteriorJoint.condExpL2_coeFn_eq_posteriorMean
#check MGAP4D.MathlibAnalytic.GroundStatePosteriorJoint.posteriorMean_memLp_two
#check MGAP4D.MathlibAnalytic.GroundStatePosteriorJoint.posteriorMeanL2_eq_condExpL2
#check MGAP4D.MathlibAnalytic.GroundStatePosteriorJoint.condExpL2_coeFn_eq_posteriorBCF
