import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSweepBlockDefectTerminalProfileRenewal
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSweepBlockDefectCyclicSecondVisit
import Mathlib.Tactic

/-!
# Cyclic target cross-residual telescoping

Let `P target` be one projection and suppose the starting vector `x` is
already fixed by it.  Sweep a list of intervening source projections and write

  R = x - sweep sources x

for the exact residual-vector sum of that source sweep.

Linearity gives the elementary identity

  sweep sources x - P target (sweep sources x)
    = P target R - R.

This file refines the right-hand side into a recursive sum.  Every source stage
residual is passed through the same target cross-residual operator

  r |-> P target r - r.

Thus the residual seen when the target is visited again is exactly the sum of
the target cross-residuals generated by the intervening source stages.

The identity is then specialized to the positive-beta fixed-color cyclic order
from PR #4894.  Combining it with the exact stage-profile theorem identifies
the PR #4896 terminal profile itself with the norm of this cyclic
cross-residual sum.

No norm inequality, response estimate, source reordering, commutativity,
finite-cardinality factor, or factor two is introduced.
-/

namespace MGAP4D.MathlibAnalytic

noncomputable section

/-- Recursive sum of the target cross-residuals of all successive source-stage
residual vectors along an ordered projection sweep. -/
def realHilbertProjectionSweepTargetCrossResidualVectorSum
    {E C : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    (P : C → E →L[ℝ] E)
    (target : C) :
    List C → E → E
  | [], _ => 0
  | source :: sources, x =>
      (P target (x - P source x) - (x - P source x)) +
        realHilbertProjectionSweepTargetCrossResidualVectorSum
          P target sources (P source x)

/-- The recursive cross-residual sum is exactly the target map applied to the
ordinary sweep residual-vector sum, minus that residual-vector sum. -/
theorem realHilbertProjectionSweepTargetCrossResidualVectorSum_eq_map_residualVectorSum_sub
    {E C : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    (P : C → E →L[ℝ] E)
    (target : C)
    (sources : List C)
    (x : E) :
    realHilbertProjectionSweepTargetCrossResidualVectorSum
        P target sources x =
      P target (realHilbertProjectionSweepResidualVectorSum P sources x) -
        realHilbertProjectionSweepResidualVectorSum P sources x := by
  induction sources generalizing x with
  | nil =>
      simp [
        realHilbertProjectionSweepTargetCrossResidualVectorSum,
        realHilbertProjectionSweepResidualVectorSum]
  | cons source sources ih =>
      simp only [
        realHilbertProjectionSweepTargetCrossResidualVectorSum,
        realHilbertProjectionSweepResidualVectorSum]
      rw [map_add, ih]
      abel

/-- If the starting vector is fixed by the target projection, the target
residual after all intervening source updates is exactly their accumulated
target cross-residual sum. -/
theorem realHilbertProjectionSweep_sub_target_eq_targetCrossResidualVectorSum_of_fixed
    {E C : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    (P : C → E →L[ℝ] E)
    (target : C)
    (sources : List C)
    (x : E)
    (hFixed : P target x = x) :
    realHilbertProjectionSweep P sources x -
        P target (realHilbertProjectionSweep P sources x) =
      realHilbertProjectionSweepTargetCrossResidualVectorSum
        P target sources x := by
  rw [
    realHilbertProjectionSweepTargetCrossResidualVectorSum_eq_map_residualVectorSum_sub,
    realHilbertProjectionSweepResidualVectorSum_eq_sub_sweep,
    map_sub,
    hFixed]
  abel

local instance cyclicCrossResidualSpecialUnitaryMeasurableSpace
    (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance cyclicCrossResidualSpatialLinkFintype
    (H : ℕ) :
    Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

/-- Fixed-color specialization: the actual second-sweep residual at `e` is
exactly the target cross-residual sum generated by the cyclic intervening
source order `suffix ++ pre`. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondSweepStageResidual_eq_cyclicTargetCrossResidualVectorSum
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (color : PeriodicHypercubicEvenGroundStateSpatialColor)
    (pre suffix :
      List (PeriodicHypercubicEvenFixedSpatialColorLink H color))
    (e : PeriodicHypercubicEvenFixedSpatialColorLink H color)
    (f :
      PeriodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointL2
        H N hN beta hbeta)
    (hSplit :
      (Finset.univ :
        Finset (PeriodicHypercubicEvenFixedSpatialColorLink H color)).toList =
          pre ++ e :: suffix) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageVector
          H N hN beta hbeta color pre
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkFullSweepVector
            H N hN beta hbeta color f) -
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
          H N hN beta hbeta color e
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageVector
            H N hN beta hbeta color pre
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkFullSweepVector
              H N hN beta hbeta color f)) =
      realHilbertProjectionSweepTargetCrossResidualVectorSum
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
          H N hN beta hbeta color)
        e (suffix ++ pre)
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
          H N hN beta hbeta color e
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageVector
            H N hN beta hbeta color pre f)) := by
  let P :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
      H N hN beta hbeta color
  let x :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageVector
      H N hN beta hbeta color pre f
  let y := P e x
  have hIdem :
      (P e).comp (P e) = P e := by
    simpa [
      P,
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2] using
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSpatialLinkCondExpL2_idempotent
        H N hN beta hbeta e.1
  have hFixed : P e y = y := by
    have hApply := congrArg (fun T => T x) hIdem
    simpa [y, ContinuousLinearMap.comp_apply] using hApply
  have hCyclic :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondSweepStageResidual_eq_cyclicBetweenVisits
      H N hN beta hbeta color pre suffix e f hSplit
  have hCross :=
    realHilbertProjectionSweep_sub_target_eq_targetCrossResidualVectorSum_of_fixed
      P e (suffix ++ pre) y hFixed
  calc
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageVector
          H N hN beta hbeta color pre
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkFullSweepVector
            H N hN beta hbeta color f) -
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
          H N hN beta hbeta color e
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageVector
            H N hN beta hbeta color pre
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkFullSweepVector
              H N hN beta hbeta color f)) =
      realHilbertProjectionSweep P (suffix ++ pre) y -
        P e (realHilbertProjectionSweep P (suffix ++ pre) y) := by
          simpa [P, x, y] using hCyclic
    _ =
      realHilbertProjectionSweepTargetCrossResidualVectorSum
        P e (suffix ++ pre) y :=
      hCross
    _ = _ := by
      rfl

/-- Exact norm carrier for the terminal profile at one target link. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTerminalSweepStageLocalProfile_eq_norm_cyclicTargetCrossResidualVectorSum
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (color : PeriodicHypercubicEvenGroundStateSpatialColor)
    (pre suffix :
      List (PeriodicHypercubicEvenFixedSpatialColorLink H color))
    (e : PeriodicHypercubicEvenFixedSpatialColorLink H color)
    (f :
      PeriodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointL2
        H N hN beta hbeta)
    (hSplit :
      (Finset.univ :
        Finset (PeriodicHypercubicEvenFixedSpatialColorLink H color)).toList =
          pre ++ e :: suffix)
    (hFresh : e ∉ pre) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTerminalSweepStageLocalProfile
        H N hN beta hbeta color f e =
      ‖realHilbertProjectionSweepTargetCrossResidualVectorSum
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
          H N hN beta hbeta color)
        e (suffix ++ pre)
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
          H N hN beta hbeta color e
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageVector
            H N hN beta hbeta color pre f))‖ := by
  let S :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkFullSweepVector
      H N hN beta hbeta color f
  have hProfile :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageLocalProfile_eq_stageResidual_norm_of_canonicalPrefix
      H N hN beta hbeta color pre suffix e S hSplit hFresh
  have hCross :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondSweepStageResidual_eq_cyclicTargetCrossResidualVectorSum
      H N hN beta hbeta color pre suffix e f hSplit
  rw [hCross] at hProfile
  simpa [
    S,
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTerminalSweepStageLocalProfile] using
    hProfile

end

end MGAP4D.MathlibAnalytic
