import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferTopOrthogonalScaleCommonBoundaryDecay

namespace MGAP4D
namespace MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryTopOrthogonalToScaleCommonBoundaryLinearIsometry
#check periodicHypercubicEvenSpecialUnitaryTopOrthogonalScaleCommonBoundaryTransferPower
#check periodicHypercubicEvenSpecialUnitary_topOrthogonalScaleCommonBoundaryTrajectory_norm_le
#check periodicHypercubicEvenSpecialUnitary_topOrthogonalScaleCommonBoundaryTransferPower_norm_le
#check periodicHypercubicEvenSpecialUnitary_topOrthogonalScaleCommonBoundaryDecayPackage

end MathlibAnalytic
end MGAP4D
