import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferenceCanonicalFixedRightHighTemperatureSpatialCovarianceClustering

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabRemoteKernelSectionRestrictedRandomScan_realIntegralCovariance_partial_telescope_abs_le_canonicalHighTemperatureSpatial

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabRemoteKernelSection_realIntegralCovariance_abs_le_canonicalHighTemperatureSpatial

end

end MGAP4D.MathlibAnalytic
