import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferTwoSidedCompleteOrderConstantLineConvergence

namespace MGAP4D
namespace MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_iterates_tendsto_constantProjection_of_completeOrder
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_constantVariance_le_lossRatio_mul_of_completeOrder

end MathlibAnalytic
end MGAP4D
