import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourcePairFixedBackgroundRMSTargetResidual

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_diagonal_one_sub_halfBarrierPinFreeCoefficient_sq_mul_fixedBackgroundSecondMeanRMS_norm_sq_lintegral_le_harnackFactor_add_one_mul_targetKernelSectionResidualEnergy
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairLinkIndexed_diagonal_one_sub_halfBarrierPinFreeCoefficient_sq_mul_fixedBackgroundSecondMeanRMS_norm_sq_lintegral_le_targetResidualEnergy

end MGAP4D.MathlibAnalytic
