import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointOneLinkRetainedCoordinateBridge

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenGroundStateJointSpatialLinkRetainedCoordinateSet
#check periodicHypercubicEvenSpecialUnitaryGroundStateJointSpatialLinkMeasurableSpace_eq_comap_retainedPairData
#check periodicHypercubicEvenSpecialUnitaryGroundStateJointSpatialLinkRetainedPairDataCoordinateMeasurableEquiv
#check periodicHypercubicEvenSpecialUnitaryGroundStateJointSpatialLinkMeasurableSpace_eq_comap_retainedCoordinateRestriction
#check periodicHypercubicEvenSpecialUnitaryGroundStateJointSpatialLinkRetainedCoordinateRestriction_eq_piRestriction_comp
#check periodicHypercubicEvenGroundStateJointSpatialLinkRetainedCoordinateSet_fixedColor_iInter
#check periodicHypercubicEvenGroundStateJointSpatialLinkRetainedCoordinateSet_fixedColor_univList

end MGAP4D.MathlibAnalytic
