import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpatialParityGeneratedSubgroup
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenAllSpatialPlanesZeroMomentumChargeConjugation
import Mathlib.Tactic

/-!
# Group-level discrete symmetry certificate for the all-spatial zero-momentum Wilson observable

The finite-lattice scalar-channel receipts have now been strengthened from separate generator
statements to invariance under the actual configuration-permutation subgroup generated by
`swap12`, `swap23`, and `reflect1`.  Moreover, the independently constructed global spatial parity
has been proved to be an element of that same subgroup.

This file packages the strongest theorem-generated finite-lattice information currently available:

* invariance under every periodic spatial translation (zero spatial momentum);
* invariance under every element of the generated signed-spatial configuration subgroup;
* membership of global spatial parity in that subgroup, hence `P = +` as a corollary of the group
  invariance theorem rather than an independent scalar premise;
* charge-conjugation evenness `C = +`.

The older generator-by-generator certificate remains canonical and untouched.  This stronger
package is additive.  It still deliberately stops short of identifying the generated subgroup with
an abstract cubic/hyperoctahedral group, assigning an `A₁` irreducible-representation label,
identifying continuum spin, or asserting a spectral mass.
-/

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

local instance generatedSymmetrySpecialUnitaryMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

/-- Spatial parity evenness follows from generated-subgroup invariance together with the theorem
that the genuine parity permutation belongs to that subgroup.  This removes parity as an
independent scalar-observable proof obligation at this finite-lattice level. -/
theorem periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace_parityInvariant_of_generatedSubgroup
    (H N : ℕ)
    (A : PeriodicHypercubicEvenEdge H →
      Matrix.specialUnitaryGroup (Fin N) ℂ) :
    periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N
        (periodicHypercubicEvenConfigurationSpatialParity H A) =
      periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N A := by
  let σ : periodicHypercubicEvenGeneratedSignedSpatialPermutationSubgroup H N :=
    ⟨periodicHypercubicEvenConfigurationSpatialParityEquiv H N,
      periodicHypercubicEvenConfigurationSpatialParityEquiv_mem_generated H N⟩
  have h :=
    periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace_generatedPermutationSubgroupInvariant
      H N σ A
  simpa [σ] using h

/-- Audit-visible bundle of the strongest current finite-lattice symmetry receipts for the concrete
equal-weight all-spatial zero-momentum normalized-real-trace Wilson observable. -/
structure PeriodicHypercubicEvenAllSpatialZeroMomentumGeneratedSymmetryCertificate
    (H N : ℕ)
    (A : PeriodicHypercubicEvenEdge H →
      Matrix.specialUnitaryGroup (Fin N) ℂ) : Prop where
  spatialTranslationInvariant :
    ∀ b : PeriodicHypercubicEvenSpatialDisplacement H,
      periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N
          (periodicHypercubicConfigurationTranslationMeasurableEquiv
            (Gauge := Matrix.specialUnitaryGroup (Fin N) ℂ)
            (PeriodicHypercubicEvenSideLength H) b.1 A) =
        periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N A
  generatedSignedSpatialSubgroupInvariant :
    ∀ σ : periodicHypercubicEvenGeneratedSignedSpatialPermutationSubgroup H N,
      periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N
          ((σ : Equiv.Perm
            (PeriodicHypercubicEvenEdge H → Matrix.specialUnitaryGroup (Fin N) ℂ)) A) =
        periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N A
  spatialParityMember :
    periodicHypercubicEvenConfigurationSpatialParityEquiv H N ∈
      periodicHypercubicEvenGeneratedSignedSpatialPermutationSubgroup H N
  parityEven :
    periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N
        (periodicHypercubicEvenConfigurationSpatialParity H A) =
      periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N A
  chargeConjugationEven :
    periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N
        (periodicHypercubicEvenConfigurationChargeConjugation H N A) =
      periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace H N A

/-- The concrete Wilson observable automatically carries the group-level generated-symmetry
certificate; every field is discharged by canonical theorems and no new premise is introduced. -/
theorem periodicHypercubicEvenAllSpatialZeroMomentumGeneratedSymmetryCertificate
    (H N : ℕ)
    (A : PeriodicHypercubicEvenEdge H →
      Matrix.specialUnitaryGroup (Fin N) ℂ) :
    PeriodicHypercubicEvenAllSpatialZeroMomentumGeneratedSymmetryCertificate H N A where
  spatialTranslationInvariant := fun b =>
    periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace_translationInvariant
      H N b A
  generatedSignedSpatialSubgroupInvariant := fun σ =>
    periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace_generatedPermutationSubgroupInvariant
      H N σ A
  spatialParityMember :=
    periodicHypercubicEvenConfigurationSpatialParityEquiv_mem_generated H N
  parityEven :=
    periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace_parityInvariant_of_generatedSubgroup
      H N A
  chargeConjugationEven :=
    periodicHypercubicEvenAllSpatialPlanesZeroMomentumNormalizedTrace_chargeConjugationInvariant
      H N A

end

end MathlibAnalytic
end MGAP4D
