import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourcePairLinkIndexedCanonicalAssembledState

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairLinkIndexedCanonicalAssembledCurrentValueFixedBackgroundL2
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairLinkIndexedCanonicalAssembledCurrentValueFixedBackgroundL2_eq_localPart_add_sum_targetResponse
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairLinkIndexedCanonicalAssembledCurrentValue_aeOuterLIntegralTransposeSchurReceiver_of_offDiagonalSecondMeanRMSMajorant

end MGAP4D.MathlibAnalytic
