import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferPosteriorJointSourceLocalTilt

open MGAP4D.MathlibAnalytic

#check GroundStatePosteriorJoint.sourceWeightedRow_memLp_two
#check GroundStatePosteriorJoint.sourceLinkResponse_eq_coordinate_inner
#check GroundStatePosteriorJoint.sourceLinkResponse_abs_le_coordinateNorm
#check GroundStatePosteriorJoint.sourceLinkResponse_eq_centeredCoordinate
#check GroundStatePosteriorJoint.jointTransferLinkDifference_eq_centeredCoordinate
#check GroundStatePosteriorJoint.jointTransferLinkDifference_abs_le_centeredCoordinate
#check GroundStatePosteriorJoint.fineFrozenInitialEnergy_eq_centeredCoordinate
