import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferCrossBoundaryLeftSourceSupported

namespace MGAP4D.MathlibAnalytic

open MeasureTheory ProbabilityTheory
open scoped ENNReal

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundaryTargetMean_pairwise_sq_eq_zero_of_ne
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundaryCurrentTargetMean_sourceSection_variance_eq_zero_of_ne
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundary_leftLeakage_norm_eq_zero_of_ne
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundary_leftSourceUpdate_leakage_norm_eq_zero_of_ne
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundary_leftSourceUpdate_leakage_norm_le_crossMajorant

#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundaryCurrentTargetMean_sourceSection_variance_eq_zero_of_ne
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundary_leftSourceUpdate_leakage_norm_le_crossMajorant

end

end MGAP4D.MathlibAnalytic
