import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialSweepStageSourceUpdateOrderedDirectBackwardCarrier

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpatialSliceUpdate_comm_of_ne
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSectionSourceUpdateOrderedDirectDifferenceSquare_eq_sourceSquare_after_targetUpdate
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSectionSourceUpdateOrderedDirectAverageEnergyENNReal
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSectionSourceUpdateOrderedDirectAverageEnergy_ofReal_eq_ennreal
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSectionSourceUpdateOrderedDirectAverageEnergyENNReal_eq_forwardHeatBathJoint
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSectionSourceUpdateOrderedDirectAverageEnergy_ofReal_eq_backwardHeatBathJoint

end MGAP4D.MathlibAnalytic
