import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourcePairFixedBackgroundTargetAmplitudeResidualSum

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLawFixedBackgroundSecondMeanRMSTargetMajorantCoefficient
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLawFixedBackgroundSecondMeanRMSTargetAmplitude_sq_ofReal_eq_targetMajorant
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairLinkIndexedFixedBackgroundSecondMeanRMSTargetAmplitude_sq_sum_ofReal_eq_targetMajorant_sum
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairLinkIndexedFixedBackgroundSecondMeanRMSTargetMajorant_sum_eq_coefficient_mul_targetResidualEnergy_sum
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairLinkIndexedFixedBackgroundSecondMeanRMSTargetAmplitude_sq_sum_ofReal_eq_coefficient_mul_targetResidualEnergy_sum

end MGAP4D.MathlibAnalytic
