import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferCrossBoundaryGenuineOneStepL2

namespace MGAP4D.MathlibAnalytic

open MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundaryCurrentTargetMean_sourceSection_variance_ofReal_le_crossCoefficient_sq_mul_lintegral_currentTargetVariance_sourceSection
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundaryCurrentTargetMean_sourceSection_variance_vacuum_lintegral_le_crossCoefficient_sq_mul_sourceUpdateTargetVariance
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundary_leftLeakage_norm_sq_ofReal_le_crossCoefficient_sq_mul_targetResidual
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundary_leftLeakage_norm_sq_le_crossCoefficient_sq_mul_targetResidual

#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundary_leftLeakage_norm_sq_ofReal_le_crossCoefficient_sq_mul_targetResidual
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundary_leftLeakage_norm_sq_le_crossCoefficient_sq_mul_targetResidual

end

end MGAP4D.MathlibAnalytic
