import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourceUpdateBackwardLawResponseCrossResidual

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardLawResponse_currentValue_vacuum_lintegral_eq_transposedVacuumResponseL2Energy_of_bounded
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardLawResponse_currentValue_vacuum_lintegral_le_transposedCanonicalPinFree_sq_mul_crossCondExpResidual

end MGAP4D.MathlibAnalytic
