import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferBetaZeroGroundStateSixSpatialProductHaarRangeInvariant

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check condExp_sharedBase_aestronglyMeasurable_of_measurePreserving_equiv
#check pairHaarPiThreeWay_left_comap_eq_restriction
#check pairHaarPiRestriction_right_comap_le_threeWay_right
#check pairHaarPiThreeWay_base_comap_le_restriction_right
#check pairHaarPi_condExp_restriction_aestronglyMeasurable_right

#check
  periodicHypercubicEvenSpecialUnitaryGroundStatePairHaar_condExp_color_preserves_color

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaarProjection_range_invariant

end

end MGAP4D.MathlibAnalytic
