import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferTwoSidedTwelveSpatialGroupedLinkSweep

namespace MGAP4D.MathlibAnalytic
namespace GroundStateSourceFixedPairEnergy

#check twoSidedTwelveSpatialGroupedLinkList_nodup
#check twoSidedTwelveSpatialGroupedLinkList_complete
#check twoSidedTwelveSpatialColorLinkList_right_sweep_eq
#check twoSidedTwelveSpatialColorLinkList_left_sweep_eq
#check twoSidedTwelveSpatialGroupedLinkList_sweep_eq_groupSweep

#print axioms twoSidedTwelveSpatialGroupedLinkList_nodup
#print axioms twoSidedTwelveSpatialGroupedLinkList_complete

end GroundStateSourceFixedPairEnergy
end MGAP4D.MathlibAnalytic
