import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourceUpdateBackwardLawResponseTransposed

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardLawResponse_currentValue_targetUpdate_eq_neg_transposedCanonicalTargetLawResponse_of_bounded

end MGAP4D.MathlibAnalytic
