import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferBetaZeroGroundStateSixSpatialProductHaarRayleighConstant

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check realHilbertProjectionSweep_idempotent_of_pairwise_commute
#check realHilbertProjectionSweep_symmetric_of_pairwise_commute

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaarFullSweep_idempotent

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaarFullSweep_symmetric

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaarFullSweep_eq_zero_of_mem_fst_orthogonal

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaar_frame_one_six_of_mem_fst_orthogonal

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaarRandomScan_rayleigh_five_six_of_mem_fst_orthogonal

end

end MGAP4D.MathlibAnalytic
