import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferenceCanonicalFixedRightHighTemperatureSpatialRandomScanResolvent
import Mathlib.Tactic

/-!
# Canonical high-temperature spatial covariance clustering

The canonical high-temperature lane now supplies a finite random-scan
resolvent with genuine base-L1 spatial decay at every fixed scale s > 1.

The exact remote kernel-section covariance telescope from #4641 has the form

  |Cov(F,G) - Cov(F,P^M G)|
    <= sum_e deltaF(e) * w_G,M(e),

where w_G,M is the canonical finite random-scan resolvent generated by the
variation profile of G.

If every nonzero F-variation coordinate is base-L1 distance at least D from
every nonzero G-variation coordinate, #4642 gives, uniformly in M,

  w_G,M(e)
    <= (1-q(s,beta))^(-1) * s^(-D) * sum_j deltaG(j)

on every e carrying nonzero deltaF.  Therefore

  |Cov(F,G) - Cov(F,P^M G)|
    <= (1-q)^(-1) * s^(-D)
         * (sum deltaF) * (sum deltaG).

The already-proved complete-block fixed-volume covariance remainder limit then
sends Cov(F,P^M G) to zero and yields the same bound for the full covariance.

At s > 1 this is a volume/rank-independent exponential spatial clustering
estimate for the actual remote fixed-right ground-state kernel-section law.
At s = 1 the theorem remains a uniform covariance bound and is not described
as spatial decay.

No Poincare/coercivity inequality, Hamiltonian spectral gap, thermodynamic
limit, or continuum Yang-Mills construction is asserted here.
-/

namespace MGAP4D.MathlibAnalytic

open MeasureTheory ProbabilityTheory Filter
open scoped BigOperators Topology

noncomputable section

local instance canonicalHighTemperatureSpatialCovarianceClusteringSpatialLinkFintype
    (H : ℕ) : Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

local instance canonicalHighTemperatureSpatialCovarianceClusteringSpecialUnitaryIsTopologicalGroup
    (N : ℕ) : IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance canonicalHighTemperatureSpatialCovarianceClusteringSpecialUnitaryCompactSpace
    (N : ℕ) : CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance canonicalHighTemperatureSpatialCovarianceClusteringSpecialUnitarySecondCountableTopology
    (N : ℕ) : SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance canonicalHighTemperatureSpatialCovarianceClusteringSpecialUnitaryMeasurableSpace
    (N : ℕ) : MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance canonicalHighTemperatureSpatialCovarianceClusteringSpecialUnitaryBorelSpace
    (N : ℕ) : BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- Finite covariance-telescope clustering bound obtained by inserting the
spatial canonical random-scan resolvent into the exact covariance telescope. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabRemoteKernelSectionRestrictedRandomScan_realIntegralCovariance_partial_telescope_abs_le_canonicalHighTemperatureSpatial
    (H N : ℕ)
    (hN : 0 < N)
    (s : ℝ)
    (hs : 1 ≤ s)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (hcut :
      beta ≤
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightHalfBarrierCutoff
          s)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    {target source : PeriodicHypercubicEvenSpatialSliceLink H}
    (hne : target ≠ source)
    (hNoShare :
      ¬ periodicHypercubicEvenSpatialSliceLinksSharePlaquette H target source)
    (g₂ k : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (F G : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N → ℝ)
    (hFStrong : StronglyMeasurable F)
    (hGStrong : StronglyMeasurable G)
    (hF : MemLp F 2
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
        H N hN beta hbeta
        (Function.update (Function.update B source k) target g₂)))
    (hG : MemLp G 2
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
        H N hN beta hbeta
        (Function.update (Function.update B source k) target g₂)))
    (variationF variationG : PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (hVariationFNonneg : ∀ e, 0 ≤ variationF e)
    (hVariationGNonneg : ∀ e, 0 ≤ variationG e)
    (hVariationF :
      ∀ (e : PeriodicHypercubicEvenSpatialSliceLink H)
        (C : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
        (u v : Matrix.specialUnitaryGroup (Fin N) ℂ),
        |F (Function.update C e u) - F (Function.update C e v)| ≤ variationF e)
    (hVariationG :
      ∀ (e : PeriodicHypercubicEvenSpatialSliceLink H)
        (C : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
        (u v : Matrix.specialUnitaryGroup (Fin N) ℂ),
        |G (Function.update C e u) - G (Function.update C e v)| ≤ variationG e)
    (D : ℕ)
    (hSeparated :
      ∀ left right : PeriodicHypercubicEvenSpatialSliceLink H,
        variationF left ≠ 0 →
        variationG right ≠ 0 →
          D ≤
            periodicHypercubicEdgeBaseL1Distance
              (PeriodicHypercubicEvenSideLength H)
              (periodicHypercubicEvenSpatialSliceLinkEmbedding H left)
              (periodicHypercubicEvenSpatialSliceLinkEmbedding H right))
    (M : ℕ) :
    |realIntegralCovariance
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
          H N hN beta hbeta
          (Function.update (Function.update B source k) target g₂))
        F G -
      realIntegralCovariance
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
          H N hN beta hbeta
          (Function.update (Function.update B source k) target g₂))
        F
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberRestrictedRandomScanExpectationIterate
          H N hN beta hbeta B target source g₂ k G M)| ≤
      (1 -
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightHalfBarrierPinFreeCoefficient
          s beta)⁻¹ *
        (s ^ D)⁻¹ *
        (∑ e : PeriodicHypercubicEvenSpatialSliceLink H, variationF e) *
        (∑ e : PeriodicHypercubicEvenSpatialSliceLink H, variationG e) := by
  classical
  let C :=
    (1 -
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightHalfBarrierPinFreeCoefficient
        s beta)⁻¹ *
      (s ^ D)⁻¹ *
      (∑ e : PeriodicHypercubicEvenSpatialSliceLink H, variationG e)
  have hPartial :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabRemoteKernelSectionRestrictedRandomScan_realIntegralCovariance_partial_telescope_abs_le_canonicalHighTemperatureResolvent
      H N hN beta hbeta B hne hNoShare g₂ k F G
      hFStrong hGStrong hF hG variationF variationG
      hVariationFNonneg hVariationGNonneg hVariationF hVariationG M
  calc
    |realIntegralCovariance
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
          H N hN beta hbeta
          (Function.update (Function.update B source k) target g₂))
        F G -
      realIntegralCovariance
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
          H N hN beta hbeta
          (Function.update (Function.update B source k) target g₂))
        F
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberRestrictedRandomScanExpectationIterate
          H N hN beta hbeta B target source g₂ k G M)| ≤
      ∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H,
        variationF fiber *
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightPinFreeRandomScanFiniteResolventProfile
            H N hN beta hbeta variationG M fiber := hPartial
    _ ≤
      ∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H,
        variationF fiber * C := by
      apply Finset.sum_le_sum
      intro fiber _hmem
      by_cases hFZero : variationF fiber = 0
      · simp [hFZero]
      · have hSpatial :=
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightPinFreeRandomScanFiniteResolventProfile_le_spatialResolvent_of_distance
            H N hN s hs beta hbeta hcut
            variationG hVariationGNonneg D fiber
            (fun right hGNonzero =>
              hSeparated fiber right hFZero hGNonzero)
            M
        exact
          mul_le_mul_of_nonneg_left
            (by simpa [C, mul_assoc] using hSpatial)
            (hVariationFNonneg fiber)
    _ =
      (∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H, variationF fiber) * C := by
      rw [Finset.sum_mul]
    _ =
      (1 -
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightHalfBarrierPinFreeCoefficient
          s beta)⁻¹ *
        (s ^ D)⁻¹ *
        (∑ e : PeriodicHypercubicEvenSpatialSliceLink H, variationF e) *
        (∑ e : PeriodicHypercubicEvenSpatialSliceLink H, variationG e) := by
      dsimp [C]
      ring

/-- Full remote kernel-section covariance clustering.  The finite random-scan
terminal covariance is sent to zero along the already-established complete-
block subsequence, while the spatial prefactor is independent of volume and
rank. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabRemoteKernelSection_realIntegralCovariance_abs_le_canonicalHighTemperatureSpatial
    (H N : ℕ)
    (hN : 0 < N)
    (s : ℝ)
    (hs : 1 ≤ s)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (hcut :
      beta ≤
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightHalfBarrierCutoff
          s)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    {target source : PeriodicHypercubicEvenSpatialSliceLink H}
    (hne : target ≠ source)
    (hNoShare :
      ¬ periodicHypercubicEvenSpatialSliceLinksSharePlaquette H target source)
    (g₂ k : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (F G : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N → ℝ)
    (hFStrong : StronglyMeasurable F)
    (hGStrong : StronglyMeasurable G)
    (hF : MemLp F 2
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
        H N hN beta hbeta
        (Function.update (Function.update B source k) target g₂)))
    (hG : MemLp G 2
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
        H N hN beta hbeta
        (Function.update (Function.update B source k) target g₂)))
    (variationF variationG : PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (hVariationFNonneg : ∀ e, 0 ≤ variationF e)
    (hVariationGNonneg : ∀ e, 0 ≤ variationG e)
    (hVariationF :
      ∀ (e : PeriodicHypercubicEvenSpatialSliceLink H)
        (C : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
        (u v : Matrix.specialUnitaryGroup (Fin N) ℂ),
        |F (Function.update C e u) - F (Function.update C e v)| ≤ variationF e)
    (hVariationG :
      ∀ (e : PeriodicHypercubicEvenSpatialSliceLink H)
        (C : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
        (u v : Matrix.specialUnitaryGroup (Fin N) ℂ),
        |G (Function.update C e u) - G (Function.update C e v)| ≤ variationG e)
    (D : ℕ)
    (hSeparated :
      ∀ left right : PeriodicHypercubicEvenSpatialSliceLink H,
        variationF left ≠ 0 →
        variationG right ≠ 0 →
          D ≤
            periodicHypercubicEdgeBaseL1Distance
              (PeriodicHypercubicEvenSideLength H)
              (periodicHypercubicEvenSpatialSliceLinkEmbedding H left)
              (periodicHypercubicEvenSpatialSliceLinkEmbedding H right))
    (R : ℝ)
    (hR : 0 ≤ R)
    (hOsc :
      ∀ X Y : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N,
        |G X - G Y| ≤ R) :
    |realIntegralCovariance
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
        H N hN beta hbeta
        (Function.update (Function.update B source k) target g₂))
      F G| ≤
      (1 -
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightHalfBarrierPinFreeCoefficient
          s beta)⁻¹ *
        (s ^ D)⁻¹ *
        (∑ e : PeriodicHypercubicEvenSpatialSliceLink H, variationF e) *
        (∑ e : PeriodicHypercubicEvenSpatialSliceLink H, variationG e) := by
  let μ :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousProbabilityMeasure
      H N hN beta hbeta
      (Function.update (Function.update B source k) target g₂)
  let L :=
    (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceAllSpatialLinkSchedule
      H).length
  let C :=
    (1 -
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightHalfBarrierPinFreeCoefficient
        s beta)⁻¹ *
      (s ^ D)⁻¹ *
      (∑ e : PeriodicHypercubicEvenSpatialSliceLink H, variationF e) *
      (∑ e : PeriodicHypercubicEvenSpatialSliceLink H, variationG e)
  have hRem :
      Tendsto
        (fun n : ℕ =>
          realIntegralCovariance μ F
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberRestrictedRandomScanExpectationIterate
              H N hN beta hbeta B target source g₂ k G (n * L)))
        atTop (𝓝 0) := by
    dsimp [μ, L]
    exact
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabRemoteKernelSectionRestrictedRandomScan_realIntegralCovariance_mul_scheduleLength_tendsto_zero
        H N hN beta hbeta B hne hNoShare g₂ k F G
        hGStrong hF hG R hR hOsc
  have hDiff :
      Tendsto
        (fun n : ℕ =>
          realIntegralCovariance μ F G -
            realIntegralCovariance μ F
              (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberRestrictedRandomScanExpectationIterate
                H N hN beta hbeta B target source g₂ k G (n * L)))
        atTop (𝓝 (realIntegralCovariance μ F G)) := by
    have hConst :
        Tendsto (fun _ : ℕ => realIntegralCovariance μ F G)
          atTop (𝓝 (realIntegralCovariance μ F G)) :=
      tendsto_const_nhds
    simpa using hConst.sub hRem
  have hAbs :
      Tendsto
        (fun n : ℕ =>
          |realIntegralCovariance μ F G -
            realIntegralCovariance μ F
              (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberRestrictedRandomScanExpectationIterate
                H N hN beta hbeta B target source g₂ k G (n * L))|)
        atTop (𝓝 |realIntegralCovariance μ F G|) := by
    simpa using hDiff.abs
  have hFinite :
      ∀ n : ℕ,
        |realIntegralCovariance μ F G -
          realIntegralCovariance μ F
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberRestrictedRandomScanExpectationIterate
              H N hN beta hbeta B target source g₂ k G (n * L))| ≤ C := by
    intro n
    dsimp [C, L, μ]
    exact
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabRemoteKernelSectionRestrictedRandomScan_realIntegralCovariance_partial_telescope_abs_le_canonicalHighTemperatureSpatial
        H N hN s hs beta hbeta hcut B hne hNoShare g₂ k F G
        hFStrong hGStrong hF hG variationF variationG
        hVariationFNonneg hVariationGNonneg hVariationF hVariationG
        D hSeparated
        (n *
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceAllSpatialLinkSchedule
            H).length)
  change |realIntegralCovariance μ F G| ≤ C
  exact le_of_tendsto' hAbs hFinite

end

end MGAP4D.MathlibAnalytic
