import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialBoundedConcreteCoreClosure

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSixSpatialResidualEnergy

#check continuous_groundStateJointColorNormalizedResidualEnergy

#check
  continuous_periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSixSpatialResidualEnergy

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSixSpatialRelativePoincare_of_boundedConcreteCore

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSixSpatialPoincare_on_sector_of_boundedConcreteCore

end

end MGAP4D.MathlibAnalytic
