import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferBetaZeroPhysicalSixSpatialExactFrameRayleigh

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalPairHaarBoundaryVector

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalPairHaarBoundaryVector_norm

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalPairHaarBoundaryVector_mem_fst_orthogonal

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatialPairHaar_frame_one_six

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatialPairHaarRandomScan_rayleigh_five_six

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatialPairHaar_exact_package

end

end MGAP4D.MathlibAnalytic
