import MGAP4D.MathlibAnalytic.SpatialSignedPermutationGroupGeneration
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpatialAxisSwap12Geometry
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpatialAxisSwap23Geometry
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpatialAxis1ReflectionGeometry
import Mathlib.Tactic

/-!
# Abstract signed spatial permutations acting on periodic lattice vertices

The abstract signed-coordinate group

`SpatialSignedPermutationGroup = (Fin 3 → ℤˣ) ⋊ S₃`

is now canonical, has order `48`, and is generated by the same three labels already realized by the
finite lattice geometry: `swap12`, `swap23`, and reflection of the first spatial axis.

This file gives the first carrier-level bridge from that abstract group back to the actual periodic
four-dimensional lattice.  Euclidean time coordinate `0` is fixed.  On a spatial coordinate `j`, an
abstract element `g = (ε, σ)` acts by

`x_j ↦ ε_j · x_{σ⁻¹(j)}`.

The integer unit `ε_j ∈ {+1,-1}` is cast into the periodic coordinate ring `ZMod n`.  The defining
semidirect-product action is chosen precisely so that this is a genuine left group action.  We
package it as a homomorphism into permutations of periodic vertices and recover the previously
canonical concrete generators exactly.

This layer is vertex geometry only.  It does not yet define the induced positive-edge/configuration
action for an arbitrary signed permutation, transport plaquette holonomies, assign a cubic irrep,
or make a continuum-spin or spectral claim.
-/

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- Cast an abstract integer-unit sign into the periodic coordinate ring. -/
def spatialAxisUnitZMod (n : ℕ) (u : ℤˣ) : ZMod n :=
  ((u : ℤ) : ZMod n)

@[simp]
theorem spatialAxisUnitZMod_one (n : ℕ) :
    spatialAxisUnitZMod n 1 = 1 := by
  simp [spatialAxisUnitZMod]

@[simp]
theorem spatialAxisUnitZMod_neg_one (n : ℕ) :
    spatialAxisUnitZMod n (-1 : ℤˣ) = -1 := by
  simp [spatialAxisUnitZMod]

@[simp]
theorem spatialAxisUnitZMod_mul
    (n : ℕ) (u v : ℤˣ) :
    spatialAxisUnitZMod n (u * v) =
      spatialAxisUnitZMod n u * spatialAxisUnitZMod n v := by
  simp [spatialAxisUnitZMod]

/-- Inverse application reverses the order of permutation multiplication. -/
@[simp]
theorem spatialAxisPermutation_mul_symm_apply
    (σ τ : Equiv.Perm (Fin 3))
    (j : Fin 3) :
    (σ * τ).symm j = τ.symm (σ.symm j) := by
  apply (σ * τ).injective
  simp [Equiv.Perm.mul_apply]

/-- `Fin.cases` at the first spatial coordinate of `Fin 4`. -/
@[simp]
theorem periodicHypercubicFinCases_spatial1
    {α : Type*} (z : α) (f : Fin 3 → α) :
    Fin.cases z f (1 : Fin 4) = f 0 := by
  change Fin.cases z f (Fin.succ (0 : Fin 3)) = f 0
  rfl

/-- `Fin.cases` at the second spatial coordinate of `Fin 4`. -/
@[simp]
theorem periodicHypercubicFinCases_spatial2
    {α : Type*} (z : α) (f : Fin 3 → α) :
    Fin.cases z f (2 : Fin 4) = f 1 := by
  change Fin.cases z f (Fin.succ (1 : Fin 3)) = f 1
  rfl

/-- `Fin.cases` at the third spatial coordinate of `Fin 4`. -/
@[simp]
theorem periodicHypercubicFinCases_spatial3
    {α : Type*} (z : α) (f : Fin 3 → α) :
    Fin.cases z f (3 : Fin 4) = f 2 := by
  change Fin.cases z f (Fin.succ (2 : Fin 3)) = f 2
  rfl

/-- Action of one abstract signed spatial permutation on a periodic four-dimensional vertex.
Time is fixed; the three spatial coordinates are reindexed by `g.right⁻¹` and multiplied by their
corresponding abstract signs. -/
def periodicHypercubicVertexSpatialSignedPermutation
    (n : ℕ)
    (g : SpatialSignedPermutationGroup)
    (x : PeriodicHypercubicVertex n) :
    PeriodicHypercubicVertex n :=
  Fin.cases
    (x 0)
    (fun j : Fin 3 =>
      spatialAxisUnitZMod n (g.left j) *
        x (Fin.succ (g.right.symm j)))

@[simp]
theorem periodicHypercubicVertexSpatialSignedPermutation_zero
    (n : ℕ)
    (g : SpatialSignedPermutationGroup)
    (x : PeriodicHypercubicVertex n) :
    periodicHypercubicVertexSpatialSignedPermutation n g x 0 = x 0 :=
  rfl

@[simp]
theorem periodicHypercubicVertexSpatialSignedPermutation_succ
    (n : ℕ)
    (g : SpatialSignedPermutationGroup)
    (x : PeriodicHypercubicVertex n)
    (j : Fin 3) :
    periodicHypercubicVertexSpatialSignedPermutation n g x (Fin.succ j) =
      spatialAxisUnitZMod n (g.left j) *
        x (Fin.succ (g.right.symm j)) :=
  rfl

/-- The identity signed permutation acts identically on periodic vertices. -/
@[simp]
theorem periodicHypercubicVertexSpatialSignedPermutation_one
    (n : ℕ)
    (x : PeriodicHypercubicVertex n) :
    periodicHypercubicVertexSpatialSignedPermutation n 1 x = x := by
  funext i
  refine Fin.cases ?_ (fun j => ?_) i
  · rfl
  · simp [periodicHypercubicVertexSpatialSignedPermutation]

/-- The semidirect-product multiplication is exactly composition of the corresponding vertex
transformations. -/
theorem periodicHypercubicVertexSpatialSignedPermutation_mul
    (n : ℕ)
    (g h : SpatialSignedPermutationGroup)
    (x : PeriodicHypercubicVertex n) :
    periodicHypercubicVertexSpatialSignedPermutation n (g * h) x =
      periodicHypercubicVertexSpatialSignedPermutation n g
        (periodicHypercubicVertexSpatialSignedPermutation n h x) := by
  funext i
  refine Fin.cases ?_ (fun j => ?_) i
  · rfl
  · simp [periodicHypercubicVertexSpatialSignedPermutation_succ,
      spatialAxisUnitZMod_mul, mul_assoc]

/-- Every abstract signed spatial permutation therefore gives an actual permutation of the periodic
vertex carrier. -/
def periodicHypercubicVertexSpatialSignedPermutationEquiv
    (n : ℕ)
    (g : SpatialSignedPermutationGroup) :
    PeriodicHypercubicVertex n ≃ PeriodicHypercubicVertex n where
  toFun := periodicHypercubicVertexSpatialSignedPermutation n g
  invFun := periodicHypercubicVertexSpatialSignedPermutation n g⁻¹
  left_inv x := by
    rw [← periodicHypercubicVertexSpatialSignedPermutation_mul]
    simp
  right_inv x := by
    rw [← periodicHypercubicVertexSpatialSignedPermutation_mul]
    simp

@[simp]
theorem periodicHypercubicVertexSpatialSignedPermutationEquiv_apply
    (n : ℕ)
    (g : SpatialSignedPermutationGroup)
    (x : PeriodicHypercubicVertex n) :
    periodicHypercubicVertexSpatialSignedPermutationEquiv n g x =
      periodicHypercubicVertexSpatialSignedPermutation n g x :=
  rfl

/-- The vertex permutations form a genuine group action of the abstract signed-coordinate group. -/
def periodicHypercubicVertexSpatialSignedPermutationActionHom
    (n : ℕ) :
    SpatialSignedPermutationGroup →*
      Equiv.Perm (PeriodicHypercubicVertex n) where
  toFun := periodicHypercubicVertexSpatialSignedPermutationEquiv n
  map_one' := by
    apply Equiv.ext
    intro x
    exact periodicHypercubicVertexSpatialSignedPermutation_one n x
  map_mul' g h := by
    apply Equiv.ext
    intro x
    exact periodicHypercubicVertexSpatialSignedPermutation_mul n g h x

@[simp]
theorem periodicHypercubicVertexSpatialSignedPermutationActionHom_apply
    (n : ℕ)
    (g : SpatialSignedPermutationGroup)
    (x : PeriodicHypercubicVertex n) :
    periodicHypercubicVertexSpatialSignedPermutationActionHom n g x =
      periodicHypercubicVertexSpatialSignedPermutation n g x :=
  rfl

/-- The abstract `swap12` generator recovers exactly the previously canonical concrete vertex
reindexing that swaps lattice axes `1` and `2`. -/
theorem periodicHypercubicVertexSpatialSignedPermutation_swap12
    (n : ℕ)
    (x : PeriodicHypercubicVertex n) :
    periodicHypercubicVertexSpatialSignedPermutation n
        spatialSignedPermutationSwap12 x =
      periodicHypercubicVertexSpatialAxisSwap12Equiv n x := by
  funext i
  refine Fin.cases ?_ (fun j => ?_) i
  · rfl
  · fin_cases j <;>
      simp [periodicHypercubicVertexSpatialSignedPermutation,
        spatialSignedPermutationSwap12, spatialAxisPositiveSign,
        spatialAxisUnitZMod,
        periodicHypercubicVertexSpatialAxisSwap12Equiv_apply]

/-- The abstract `swap23` generator recovers exactly the previously canonical concrete vertex
reindexing that swaps lattice axes `2` and `3`. -/
theorem periodicHypercubicVertexSpatialSignedPermutation_swap23
    (n : ℕ)
    (x : PeriodicHypercubicVertex n) :
    periodicHypercubicVertexSpatialSignedPermutation n
        spatialSignedPermutationSwap23 x =
      periodicHypercubicVertexSpatialAxisSwap23Equiv n x := by
  funext i
  refine Fin.cases ?_ (fun j => ?_) i
  · rfl
  · fin_cases j <;>
      simp [periodicHypercubicVertexSpatialSignedPermutation,
        spatialSignedPermutationSwap23, spatialAxisPositiveSign,
        spatialAxisUnitZMod,
        periodicHypercubicVertexSpatialAxisSwap23Equiv_apply]

/-- The abstract first-coordinate sign flip recovers exactly the previously canonical axis-`1`
reflection on the even periodic lattice. -/
theorem periodicHypercubicVertexSpatialSignedPermutation_reflect1
    (H : ℕ)
    (x : PeriodicHypercubicEvenVertex H) :
    periodicHypercubicVertexSpatialSignedPermutation
        (PeriodicHypercubicEvenSideLength H)
        spatialSignedPermutationReflect1 x =
      periodicHypercubicEvenSpatialAxis1Reflection H x := by
  funext i
  refine Fin.cases ?_ (fun j => ?_) i
  · rfl
  · fin_cases j <;>
      simp [periodicHypercubicVertexSpatialSignedPermutation,
        spatialSignedPermutationReflect1, spatialAxisReflect1Sign,
        spatialAxisUnitZMod,
        periodicHypercubicEvenSpatialAxis1Reflection]

end

end MathlibAnalytic
end MGAP4D
