import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenOpenHalfDisjointness
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenWilsonActionSectorDecomposition

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators
noncomputable section

end

end MathlibAnalytic
end MGAP4D
