import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferVacuumFirstCrossGenuineResidual

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_diagonal_referenceUpdatedBackgroundVariance_outer_aemeasurable
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_vacuum_diagonal_firstCrossEnergy_lintegral_le_harnackLawFactor_mul_condExpL2_residual_norm_sq_add_responseL2_norm_sq_lintegral

end MGAP4D.MathlibAnalytic
