import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointCanonicalResidualSweepStageExactLocalProfile

namespace MGAP4D.MathlibAnalytic

#check
  realHilbertProjectionSweepStageResidualSqProfile_eq_norm_sq_append_cons_of_not_mem

#check
  realHilbertProjectionSweepStageResidualAmplitude_sq_eq_norm_sq_append_cons_of_not_mem

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweepStageLocalProfile_sq_eq_stageResidual_of_canonicalSplit

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTerminalSweepStageLocalProfile_sq_eq_stageResidual_of_canonicalSplit

end MGAP4D.MathlibAnalytic
