import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointLeftSixSpatialSwapDisplacement

namespace MGAP4D
namespace MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_rightSpatialColorCondExpL2
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftFixedColor_sweep_displacement_le_one_add_sqrt_lossRatio_mul_colorResidual

end MathlibAnalytic
end MGAP4D
