import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialSweepStageBackgroundUpdateRMSCauchy

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorCanonicalOneLinkSweepPrefix_exists_boundedRepresentative_sharpHaar_and_backgroundUpdate_centeredRMS

end

end MGAP4D.MathlibAnalytic
