import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourcePairOldVarianceHarnackStationarityReturn

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLawOrderedFirstVarianceEnergy_lintegral_le_harnackLawFactor_mul_reference_updatedBackgroundVarianceEnergy_lintegral_of_bounded

end MGAP4D.MathlibAnalytic
