import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferenceCrossBoundaryL2MeanDifference

open MGAP4D.MathlibAnalytic
open MeasureTheory
open ProbabilityTheory

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundary_harnackFactor_le_three_of_beta_lt
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure_L2MeanDifference_sq_le_varianceSum_diagonal
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure_L2MeanDifference_sq_le_varianceSum_supported_on_diagonal

#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundary_harnackFactor_le_three_of_beta_lt
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure_L2MeanDifference_sq_le_varianceSum_diagonal
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure_L2MeanDifference_sq_le_varianceSum_supported_on_diagonal

end
