import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferencePinFreeExponentialWeightedResponseAggregateVariation
import MGAP4D.MathlibAnalytic.FiniteInfluenceKernelRestrictedTargetRandomScanSuperposition
import Mathlib.Tactic

/-!
# Pin-free source-discrepancy superposition

The exponentially weighted target family is useful only if its random-scan
transport and accumulated right-source discrepancy retain exact finite
linearity.

This file proves that the pin-free response-controlled random-scan orbit and
the source-forcing recurrence commute with scalar multiplication and finite
superposition.  As a consequence, the source discrepancy generated by the
weighted aggregate target-ratio variation is exactly the weighted sum of the
singleton target discrepancies:

  D_n(sum_t W(t) V_t)
    = sum_t W(t) D_n(V_t).

These are algebraic identities.  No positivity, contraction, response closure,
covariance decay, coercivity, or mass-gap input is introduced.
-/

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators

noncomputable section

local instance pinFreeSourceDiscrepancySuperpositionSpatialLinkFintype
    (H : ℕ) : Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

/-- One pin-free response-controlled random-scan update commutes with scalar
multiplication of the input variation profile. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanUpdatedVariation_const_mul
    (H : ℕ)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (R :
      PeriodicHypercubicEvenSpatialSliceLink H →
        PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (hRNonneg : ∀ target source, 0 ≤ R target source)
    (a : ℝ)
    (variation : PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (source : PeriodicHypercubicEvenSpatialSliceLink H) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanUpdatedVariation
        H beta hbeta R hRNonneg (fun e => a * variation e) source =
      a *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanUpdatedVariation
          H beta hbeta R hRNonneg variation source := by
  classical
  let K :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledPhysicalLeftKernel
      H beta hbeta R hRNonneg
  have hTarget :
      ∀ target : PeriodicHypercubicEvenSpatialSliceLink H,
        finiteInfluenceKernelUpdatedVariation
            K (fun e => a * variation e) target source =
          a * finiteInfluenceKernelUpdatedVariation K variation target source := by
    intro target
    unfold finiteInfluenceKernelUpdatedVariation
    by_cases hEq : source = target
    · simp [hEq]
    · simp only [hEq, if_false]
      ring
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanUpdatedVariation
    finiteInfluenceKernelRestrictedTargetRandomScanUpdatedVariation
  change
    (Fintype.card (PeriodicHypercubicEvenSpatialSliceLink H) : ℝ)⁻¹ *
        (∑ target : PeriodicHypercubicEvenSpatialSliceLink H,
          finiteInfluenceKernelUpdatedVariation
            K (fun e => a * variation e) target source) =
      a *
        ((Fintype.card (PeriodicHypercubicEvenSpatialSliceLink H) : ℝ)⁻¹ *
          ∑ target : PeriodicHypercubicEvenSpatialSliceLink H,
            finiteInfluenceKernelUpdatedVariation K variation target source)
  simp_rw [hTarget]
  rw [← Finset.mul_sum]
  ring

/-- Every finite pin-free response-controlled random-scan iterate commutes with
scalar multiplication. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate_const_mul
    (H : ℕ)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (R :
      PeriodicHypercubicEvenSpatialSliceLink H →
        PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (hRNonneg : ∀ target source, 0 ≤ R target source)
    (a : ℝ)
    (variation : PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (n : ℕ)
    (source : PeriodicHypercubicEvenSpatialSliceLink H) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
        H beta hbeta R hRNonneg (fun e => a * variation e) n source =
      a *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
          H beta hbeta R hRNonneg variation n source := by
  induction n generalizing source with
  | zero =>
      rfl
  | succ n ih =>
      rw [
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate_succ,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate_succ]
      have hProfile :
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
              H beta hbeta R hRNonneg (fun e => a * variation e) n =
            fun e =>
              a *
                periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
                  H beta hbeta R hRNonneg variation n e := by
        funext e
        exact ih e
      rw [hProfile]
      exact
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanUpdatedVariation_const_mul
          H beta hbeta R hRNonneg a
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
            H beta hbeta R hRNonneg variation n)
          source

/-- A pin-free response-controlled random-scan iterate commutes with every
finite superposition of input variation profiles. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate_finset_sum
    {κ : Type}
    [DecidableEq κ]
    (H : ℕ)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (R :
      PeriodicHypercubicEvenSpatialSliceLink H →
        PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (hRNonneg : ∀ target source, 0 ≤ R target source)
    (indices : Finset κ)
    (family : κ → PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (n : ℕ)
    (source : PeriodicHypercubicEvenSpatialSliceLink H) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
        H beta hbeta R hRNonneg
        (fun e => ∑ k ∈ indices, family k e) n source =
      ∑ k ∈ indices,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
          H beta hbeta R hRNonneg (family k) n source := by
  induction n generalizing source with
  | zero =>
      rfl
  | succ n ih =>
      rw [
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate_succ]
      have hProfile :
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
              H beta hbeta R hRNonneg
              (fun e => ∑ k ∈ indices, family k e) n =
            fun e =>
              ∑ k ∈ indices,
                periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
                  H beta hbeta R hRNonneg (family k) n e := by
        funext e
        exact ih e
      rw [hProfile]
      unfold
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanUpdatedVariation
      rw [
        finiteInfluenceKernelRestrictedTargetRandomScanUpdatedVariation_finset_sum]
      apply Finset.sum_congr rfl
      intro k _hk
      rfl

/-- The isolated one-scan right-source forcing commutes with scalar
multiplication. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing_const_mul
    (H : ℕ)
    (beta : ℝ)
    (source : PeriodicHypercubicEvenSpatialSliceLink H)
    (a : ℝ)
    (variation : PeriodicHypercubicEvenSpatialSliceLink H → ℝ) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing
        H beta source (fun e => a * variation e) =
      a *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing
          H beta source variation := by
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing
  have hSum :
      (∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryBoundedTestMajorant
            beta fiber source *
          (a * variation fiber)) =
        a *
          ∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H,
            periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryBoundedTestMajorant
                beta fiber source *
              variation fiber := by
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro fiber _hFiber
    ring
  rw [hSum]
  ring

/-- The isolated one-scan right-source forcing commutes with finite
superposition. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing_finset_sum
    {κ : Type}
    [DecidableEq κ]
    (H : ℕ)
    (beta : ℝ)
    (source : PeriodicHypercubicEvenSpatialSliceLink H)
    (indices : Finset κ)
    (family : κ → PeriodicHypercubicEvenSpatialSliceLink H → ℝ) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing
        H beta source (fun e => ∑ k ∈ indices, family k e) =
      ∑ k ∈ indices,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing
          H beta source (family k) := by
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing
  have hInside :
      (∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryBoundedTestMajorant
            beta fiber source *
          (∑ k ∈ indices, family k fiber)) =
        ∑ k ∈ indices,
          ∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H,
            periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryBoundedTestMajorant
                beta fiber source *
              family k fiber := by
    calc
      (∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryBoundedTestMajorant
            beta fiber source *
          (∑ k ∈ indices, family k fiber)) =
        ∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H,
          ∑ k ∈ indices,
            periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryBoundedTestMajorant
                beta fiber source *
              family k fiber := by
        apply Finset.sum_congr rfl
        intro fiber _hFiber
        rw [Finset.mul_sum]
      _ =
        ∑ k ∈ indices,
          ∑ fiber : PeriodicHypercubicEvenSpatialSliceLink H,
            periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryBoundedTestMajorant
                beta fiber source *
              family k fiber := by
        rw [Finset.sum_comm]
  rw [hInside, Finset.mul_sum]

/-- The pin-free accumulated source discrepancy commutes with scalar
multiplication of its initial variation profile. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy_const_mul
    (H : ℕ)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (source : PeriodicHypercubicEvenSpatialSliceLink H)
    (R :
      PeriodicHypercubicEvenSpatialSliceLink H →
        PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (hRNonneg : ∀ target source, 0 ≤ R target source)
    (a : ℝ)
    (variation : PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (n : ℕ) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
        H beta hbeta source R hRNonneg (fun e => a * variation e) n =
      a *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
          H beta hbeta source R hRNonneg variation n := by
  induction n with
  | zero =>
      simp
  | succ n ih =>
      rw [
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy_succ_eq_add_sourceForcing,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy_succ_eq_add_sourceForcing,
        ih]
      have hIterate :
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
              H beta hbeta R hRNonneg (fun e => a * variation e) n =
            fun e =>
              a *
                periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
                  H beta hbeta R hRNonneg variation n e := by
        funext e
        exact
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate_const_mul
            H beta hbeta R hRNonneg a variation n e
      rw [hIterate]
      rw [
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing_const_mul]
      ring

/-- The pin-free accumulated source discrepancy commutes with finite
superposition of initial variation profiles. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy_finset_sum
    {κ : Type}
    [DecidableEq κ]
    (H : ℕ)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (source : PeriodicHypercubicEvenSpatialSliceLink H)
    (R :
      PeriodicHypercubicEvenSpatialSliceLink H →
        PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (hRNonneg : ∀ target source, 0 ≤ R target source)
    (indices : Finset κ)
    (family : κ → PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (n : ℕ) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
        H beta hbeta source R hRNonneg
        (fun e => ∑ k ∈ indices, family k e) n =
      ∑ k ∈ indices,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
          H beta hbeta source R hRNonneg (family k) n := by
  induction n with
  | zero =>
      simp
  | succ n ih =>
      rw [
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy_succ_eq_add_sourceForcing]
      have hIterate :
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
              H beta hbeta R hRNonneg
              (fun e => ∑ k ∈ indices, family k e) n =
            fun e =>
              ∑ k ∈ indices,
                periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate
                  H beta hbeta R hRNonneg (family k) n e := by
        funext e
        exact
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledRandomScanVariationIterate_finset_sum
            H beta hbeta R hRNonneg indices family n e
      rw [ih, hIterate]
      rw [
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCrossBoundaryRandomScanSourceForcing_finset_sum]
      rw [← Finset.sum_add_distrib]
      apply Finset.sum_congr rfl
      intro k _hk
      symm
      exact
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy_succ_eq_add_sourceForcing
          H beta hbeta source R hRNonneg (family k) n

/-- The discrepancy generated by the complete exponentially weighted
target-ratio family is exactly the weighted sum of the singleton target
discrepancies. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioExponentialWeightedAggregatePinFreeAccumulatedSourceDiscrepancy_eq_sum
    (H : ℕ)
    (beta s : ℝ)
    (hbeta : 0 ≤ beta)
    (center source : PeriodicHypercubicEvenSpatialSliceLink H)
    (R :
      PeriodicHypercubicEvenSpatialSliceLink H →
        PeriodicHypercubicEvenSpatialSliceLink H → ℝ)
    (hRNonneg : ∀ target source, 0 ≤ R target source)
    (n : ℕ) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
        H beta hbeta source R hRNonneg
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioExponentialWeightedAggregateVariation
          H beta s center)
        n =
      ∑ target : PeriodicHypercubicEvenSpatialSliceLink H,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePhysicalLeftLocalHarnackBaseL1ExponentialWeight
            H s center target *
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
            H beta hbeta source R hRNonneg
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioVariation
              H beta target)
            n := by
  classical
  let W :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePhysicalLeftLocalHarnackBaseL1ExponentialWeight
      H s center
  let V :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioVariation
      H beta
  have hSum :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy_finset_sum
      H beta hbeta source R hRNonneg
      (Finset.univ : Finset (PeriodicHypercubicEvenSpatialSliceLink H))
      (fun target e => W target * V target e)
      n
  calc
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
        H beta hbeta source R hRNonneg
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioExponentialWeightedAggregateVariation
          H beta s center)
        n =
      ∑ target : PeriodicHypercubicEvenSpatialSliceLink H,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
          H beta hbeta source R hRNonneg
          (fun e => W target * V target e)
          n := by
            simpa [
              periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioExponentialWeightedAggregateVariation,
              W, V] using hSum
    _ =
      ∑ target : PeriodicHypercubicEvenSpatialSliceLink H,
        W target *
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
            H beta hbeta source R hRNonneg (V target) n := by
          apply Finset.sum_congr rfl
          intro target _hTarget
          exact
            periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy_const_mul
              H beta hbeta source R hRNonneg
              (W target) (V target) n
    _ =
      ∑ target : PeriodicHypercubicEvenSpatialSliceLink H,
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePhysicalLeftLocalHarnackBaseL1ExponentialWeight
            H s center target *
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledAccumulatedSourceDiscrepancy
            H beta hbeta source R hRNonneg
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioVariation
              H beta target)
            n := by
          rfl

end

end MathlibAnalytic
end MGAP4D
