import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointFixedLeftKernelSectionFactor

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointFixedLeftKernelSectionFactor
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointContinuousKernelSectionFactor_eq_fixedLeft
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointFixedLeftKernelSectionFactor_pos
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointNormalizedWeight_ae_eq_fixedLeftKernelSectionFactor
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointNormalizedENNRealWeight_ae_eq_fixedLeftKernelSectionFactor

end MGAP4D.MathlibAnalytic
