import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferVacuumSecondMeanRMSGenuineResidual

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_vacuum_diagonal_secondMeanRMSAmplitudeL2_norm_sq_lintegral_le_harnackLawFactor_add_one_mul_condExpL2_residual_norm_sq_add_responseL2_norm_sq_lintegral

end MGAP4D.MathlibAnalytic
