import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourceUpdateBackwardDirectFiberEnergyPythagorean

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardDirectVarianceEnergy_nonneg
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardDirectFiberEnergy_eq_variance_add_meanSq_of_bounded

end MGAP4D.MathlibAnalytic
