import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferUniformTopOrthogonalPowerDecay

namespace MGAP4D
namespace MathlibAnalytic

#check GroundStateSourceFixedPairEnergy.twoSidedTwelveSpatialUniformTopOrthogonalContractionFactor_lt_one
#check periodicHypercubicEvenSpecialUnitary_uniformTopOrthogonalTransferOperator_norm_le
#check periodicHypercubicEvenSpecialUnitary_uniformTopOrthogonalTransferOperator_pow_norm_le
#check periodicHypercubicEvenSpecialUnitary_uniformTopOrthogonalTransferOperator_pow_apply_norm_le
#check periodicHypercubicEvenSpecialUnitary_uniformTopOrthogonalPowerDecayPackage

end MathlibAnalytic
end MGAP4D
