import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenBoundaryVacuumMomentRestrictionGaugeTransport
import MGAP4D.MathlibAnalytic.PeriodicHypercubicSpecialUnitaryPhysicalEmbedding
import MGAP4D.MathlibAnalytic.PhysicalYangMillsOrientedGaugeSymmetryLimit
import MGAP4D.MathlibAnalytic.FiniteInvolutiveEdgeBoundaryFiberedPiMeasure

namespace MGAP4D
namespace MathlibAnalytic

open Filter MeasureTheory

noncomputable section

local instance restrictedBoundaryVacuumPhysicalGaugeNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

/-- A scale-wise finite gauge symmetry: at every even periodic lattice scale we
may choose an arbitrary vertex gauge transformation independently.

This is the natural symmetry carrier for a common physical readout whose value
is gauge invariant at each lattice scale. -/
abbrev PeriodicHypercubicEvenScaleGaugeSymmetry
    (H : ℕ → ℕ) (N : ℕ) :=
  ∀ n, PeriodicHypercubicEvenVertex (H n) →
    Matrix.specialUnitaryGroup (Fin N) ℂ

/-- Concrete physical embedding generated by the actual finite Wilson OS
boundary vacuum readout.

The physical carrier is `ℝ`, and the interpolation at scale `n` is not an
arbitrary map: it is exactly the raw full-configuration boundary-vacuum moment
already constructed from the completed-positive Wilson Gram feature.

This is deliberately a gauge-invariant observable/readout embedding, not yet a
claim that `ℝ` is the full continuum gauge-field configuration space. -/
noncomputable def
    periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalEmbedding
    (H : ℕ → ℕ)
    (N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ) (hbeta : ∀ n, 0 ≤ beta n)
    (latticeSpacing : ℕ → ℝ)
    (latticeSpacing_pos : ∀ n, 0 < latticeSpacing n)
    (latticeSpacing_tendsto_zero :
      Tendsto latticeSpacing atTop (nhds 0))
    (physicalVolume : ℕ → ℝ)
    (physicalVolume_tendsto_atTop :
      Tendsto physicalVolume atTop atTop) :
    ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding where
  PhysicalConfiguration := ℝ
  system := fun n =>
    periodicHypercubicSpecialUnitaryWilsonSystem
      (PeriodicHypercubicEvenSideLength (H n)) N hN
      (beta n) (hbeta n)
  interpolate := fun n A =>
    periodicHypercubicEvenRestrictedBoundaryVacuumMoment
      (H n) N hN (beta n) (hbeta n) A
  interpolate_measurable := by
    intro n
    let P := periodicHypercubicEvenEdgeOrbitPartition (H n)
    let Gauge := Matrix.specialUnitaryGroup (Fin N) ℂ
    have hCoordinates :
        Measurable (P.boundaryFiberedCoordinates Gauge) :=
      P.boundaryFiberedCoordinates_measurable Gauge
    have hBoundary : Measurable P.boundaryRestriction := by
      have h := measurable_fst.comp hCoordinates
      simpa [FiniteInvolutiveEdgeOrbitPartition.boundaryFiberedCoordinates] using h
    exact
      (periodicHypercubicEvenBoundaryVacuumMoment_measurable
        (H n) N hN (beta n) (hbeta n)).comp hBoundary
  latticeSpacing := latticeSpacing
  latticeSpacing_pos := latticeSpacing_pos
  latticeSpacing_tendsto_zero := latticeSpacing_tendsto_zero
  physicalVolume := physicalVolume
  physicalVolume_tendsto_atTop := physicalVolume_tendsto_atTop

/-- The actual boundary-vacuum readout embedding carries a fully constructed
physical gauge action.

The physical action on the gauge-invariant scalar readout is the identity.  A
symmetry element stores an arbitrary finite gauge transformation at every
lattice scale, and `interpolate_equivariant` is generated from the proved raw
full-configuration gauge invariance of the boundary vacuum moment.  No
interpolation-equivariance field is supplied as a new hypothesis. -/
noncomputable def
    periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalGaugeAction
    (H : ℕ → ℕ)
    (N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ) (hbeta : ∀ n, 0 ≤ beta n)
    (latticeSpacing : ℕ → ℝ)
    (latticeSpacing_pos : ∀ n, 0 < latticeSpacing n)
    (latticeSpacing_tendsto_zero :
      Tendsto latticeSpacing atTop (nhds 0))
    (physicalVolume : ℕ → ℝ)
    (physicalVolume_tendsto_atTop :
      Tendsto physicalVolume atTop atTop) :
    (periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalEmbedding
      H N hN beta hbeta
      latticeSpacing latticeSpacing_pos latticeSpacing_tendsto_zero
      physicalVolume physicalVolume_tendsto_atTop).PhysicalGaugeAction where
  Symmetry := PeriodicHypercubicEvenScaleGaugeSymmetry H N
  action := fun _ x => x
  action_continuous := fun _ => continuous_id
  latticeGauge := fun n gamma => gamma n
  interpolate_equivariant := by
    intro n gamma A
    change
      periodicHypercubicEvenRestrictedBoundaryVacuumMoment
          (H n) N hN (beta n) (hbeta n)
          ((periodicHypercubicSpecialUnitaryWilsonSystem
            (PeriodicHypercubicEvenSideLength (H n)) N hN
            (beta n) (hbeta n)).base.gaugeTransform
            (gamma n) A) =
        periodicHypercubicEvenRestrictedBoundaryVacuumMoment
          (H n) N hN (beta n) (hbeta n) A
    exact
      periodicHypercubicEvenRestrictedBoundaryVacuumMoment_gaugeInvariant
        (H n) N hN (beta n) (hbeta n) (gamma n) A

/-- Explicit theorem form of the newly discharged interpolation equivariance.
This packages the structure field as a stable rewrite target for downstream
weak-limit and OS-state constructions. -/
theorem
    periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalEmbedding_interpolate_gaugeInvariant
    (H : ℕ → ℕ)
    (N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ) (hbeta : ∀ n, 0 ≤ beta n)
    (latticeSpacing : ℕ → ℝ)
    (latticeSpacing_pos : ∀ n, 0 < latticeSpacing n)
    (latticeSpacing_tendsto_zero :
      Tendsto latticeSpacing atTop (nhds 0))
    (physicalVolume : ℕ → ℝ)
    (physicalVolume_tendsto_atTop :
      Tendsto physicalVolume atTop atTop)
    (n : ℕ)
    (gamma : PeriodicHypercubicEvenScaleGaugeSymmetry H N)
    (A : PeriodicHypercubicEvenEdge (H n) →
      Matrix.specialUnitaryGroup (Fin N) ℂ) :
    let E := periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalEmbedding
      H N hN beta hbeta
      latticeSpacing latticeSpacing_pos latticeSpacing_tendsto_zero
      physicalVolume physicalVolume_tendsto_atTop
    E.interpolate n
        ((E.system n).base.gaugeTransform (gamma n) A) =
      E.interpolate n A := by
  dsimp
  exact
    periodicHypercubicEvenRestrictedBoundaryVacuumMoment_gaugeInvariant
      (H n) N hN (beta n) (hbeta n) (gamma n) A

end

end MathlibAnalytic
end MGAP4D
