import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenRestrictedBoundaryVacuumPhysicalGaugeAction
import MGAP4D.MathlibAnalytic.PhysicalYangMillsOrientedGaugeSymmetryProkhorovLimit

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- Continuum symmetry limit carried by the actual restricted boundary-vacuum
readout along any supplied Prokhorov subsequence limit.

The finite-scale gauge equivariance entering this construction is theorem-
generated by the actual Wilson boundary vacuum moment.  The only remaining
input here is the Prokhorov subsequence limit itself; this definition does not
assert its existence. -/
noncomputable def
    periodicHypercubicEvenRestrictedBoundaryVacuumGaugeSymmetryLimit
    (H : ℕ → ℕ)
    (N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ) (hbeta : ∀ n, 0 ≤ beta n)
    (latticeSpacing : ℕ → ℝ)
    (latticeSpacing_pos : ∀ n, 0 < latticeSpacing n)
    (latticeSpacing_tendsto_zero :
      Filter.Tendsto latticeSpacing Filter.atTop (nhds 0))
    (physicalVolume : ℕ → ℝ)
    (physicalVolume_tendsto_atTop :
      Filter.Tendsto physicalVolume Filter.atTop Filter.atTop)
    (L : PhysicalFourDimensionalYangMillsProkhorovSubsequenceLimit
      (periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalEmbedding
        H N hN beta hbeta
        latticeSpacing latticeSpacing_pos latticeSpacing_tendsto_zero
        physicalVolume physicalVolume_tendsto_atTop).toLatticeEmbedding) :
    PhysicalFourDimensionalYangMillsSymmetryLimit :=
  (periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalGaugeAction
    H N hN beta hbeta
    latticeSpacing latticeSpacing_pos latticeSpacing_tendsto_zero
    physicalVolume physicalVolume_tendsto_atTop).toSymmetryLimit L

/-- The inherited continuum gauge action on the scalar boundary-vacuum readout
is the identity. -/
theorem
    periodicHypercubicEvenRestrictedBoundaryVacuumGaugeSymmetryLimit_action_eq
    (H : ℕ → ℕ)
    (N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ) (hbeta : ∀ n, 0 ≤ beta n)
    (latticeSpacing : ℕ → ℝ)
    (latticeSpacing_pos : ∀ n, 0 < latticeSpacing n)
    (latticeSpacing_tendsto_zero :
      Filter.Tendsto latticeSpacing Filter.atTop (nhds 0))
    (physicalVolume : ℕ → ℝ)
    (physicalVolume_tendsto_atTop :
      Filter.Tendsto physicalVolume Filter.atTop Filter.atTop)
    (L : PhysicalFourDimensionalYangMillsProkhorovSubsequenceLimit
      (periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalEmbedding
        H N hN beta hbeta
        latticeSpacing latticeSpacing_pos latticeSpacing_tendsto_zero
        physicalVolume physicalVolume_tendsto_atTop).toLatticeEmbedding)
    (gamma : PeriodicHypercubicEvenScaleGaugeSymmetry H N)
    (x : ℝ) :
    (periodicHypercubicEvenRestrictedBoundaryVacuumGaugeSymmetryLimit
      H N hN beta hbeta
      latticeSpacing latticeSpacing_pos latticeSpacing_tendsto_zero
      physicalVolume physicalVolume_tendsto_atTop L).action gamma x = x :=
  rfl

/-- Gauge invariance of the continuum probability law of the actual boundary-
vacuum readout along any supplied Prokhorov subsequence limit.

This is the finite-to-continuum closure of the gauge-invariance chain for this
readout: finite Wilson gauge invariance proves interpolation equivariance, and
the generic weak-limit symmetry theorem then preserves that invariance in the
continuum law. -/
theorem
    periodicHypercubicEvenRestrictedBoundaryVacuumGaugeSymmetryLimit_continuumMeasure_map_eq_self
    (H : ℕ → ℕ)
    (N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ) (hbeta : ∀ n, 0 ≤ beta n)
    (latticeSpacing : ℕ → ℝ)
    (latticeSpacing_pos : ∀ n, 0 < latticeSpacing n)
    (latticeSpacing_tendsto_zero :
      Filter.Tendsto latticeSpacing Filter.atTop (nhds 0))
    (physicalVolume : ℕ → ℝ)
    (physicalVolume_tendsto_atTop :
      Filter.Tendsto physicalVolume Filter.atTop Filter.atTop)
    (L : PhysicalFourDimensionalYangMillsProkhorovSubsequenceLimit
      (periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalEmbedding
        H N hN beta hbeta
        latticeSpacing latticeSpacing_pos latticeSpacing_tendsto_zero
        physicalVolume physicalVolume_tendsto_atTop).toLatticeEmbedding)
    (gamma : PeriodicHypercubicEvenScaleGaugeSymmetry H N) :
    let S := periodicHypercubicEvenRestrictedBoundaryVacuumGaugeSymmetryLimit
      H N hN beta hbeta
      latticeSpacing latticeSpacing_pos latticeSpacing_tendsto_zero
      physicalVolume physicalVolume_tendsto_atTop L
    S.continuumMeasure.map
        (S.action_continuous gamma).measurable.aemeasurable =
      S.continuumMeasure := by
  dsimp only
  exact
    (periodicHypercubicEvenRestrictedBoundaryVacuumPhysicalGaugeAction
      H N hN beta hbeta
      latticeSpacing latticeSpacing_pos latticeSpacing_tendsto_zero
      physicalVolume physicalVolume_tendsto_atTop).continuumMeasure_map_eq_self
        L gamma

end

end MathlibAnalytic
end MGAP4D
