import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointTerminalProfileResponseEnergy

namespace MGAP4D.MathlibAnalytic

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointLinkIndexedCanonicalFiberVariance_sum_le_profile_sq_sum_ofReal

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairLinkIndexedFullResponseL2Sum_vacuum_lintegral_le_responseResidualCoefficient_mul_profile_sq_sum_ofReal

#check
  exists_periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSecondSweep_linkIndexedRepresentatives_fullResponseL2Sum_vacuum_lintegral_le_responseResidualCoefficient_mul_sixTerminalSweepPathLoss_ofReal

end MGAP4D.MathlibAnalytic
