import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointCanonicalResidualSweepStageLocalProfile

namespace MGAP4D.MathlibAnalytic

#check realHilbertProjectionSweepStageResidual_norm_le_amplitude_append_cons
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSweep_exists_boundedRepresentative_canonicalResidualL2_norm_le_localProfile
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweep_exists_boundedRepresentative_canonicalResidualL2_norm_le_localProfile

end MGAP4D.MathlibAnalytic
