import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialSweepStageDependentNormedResponseAssembler

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check FiniteDependentNormedTransposeResponseProfile.norm_profile_le_local_add_transpose_matrix
#check FiniteDependentNormedTransposeResponseProfile.norm_profile_transpose_oneSided
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialSweepStage_dependentNormedResponse_global_energy_coercive_uniform

end

end MGAP4D.MathlibAnalytic
