import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSweepBlockDefectCyclicSecondVisit

namespace MGAP4D.MathlibAnalytic

#check realHilbertProjectionSweep_secondVisitPrefix_eq_cyclicBetweenVisits

#check realHilbertProjectionSweep_secondVisitResidual_eq_cyclicBetweenVisits

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondSweepStageVector_eq_cyclicBetweenVisits

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondSweepStageResidual_eq_cyclicBetweenVisits

end MGAP4D.MathlibAnalytic
