import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferenceBackgroundUpdateVarianceComparison

namespace MGAP4D.MathlibAnalytic

#check evariance_le_mul_of_measure_le_smul
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure_backgroundUpdate_pairwise_le_harnackLawFactor
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure_backgroundUpdate_evariance_le_harnackLawFactor_mul

end MGAP4D.MathlibAnalytic
