import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourceUpdateBackwardDirectVarianceDiagonalResidual

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardDirectVarianceEnergy_diagonal_ofReal_eq_referenceSourceResidual_fiberLIntegral_of_bounded
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardDirectVarianceEnergy_diagonal_ofReal_eq_referenceSourceUpdatedBackgroundVarianceEnergy_of_bounded
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardDirectVarianceEnergy_diagonal_reference_lintegral_eq_referenceSourceResidual_sq_lintegral_of_bounded

end MGAP4D.MathlibAnalytic
