import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSweepBlockDefectCyclicSourceUpdateQuantitative

namespace MGAP4D.MathlibAnalytic

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointCyclicSourceUpdateBackwardDirectVarianceEnergy_currentValue_vacuum_lintegral_le_harnackLawFactor_mul_condExpL2_sourceResidual

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointCyclicSourceUpdateBackwardLawResponse_currentValue_vacuum_lintegral_le_transposedCanonicalPinFree_sq_mul_crossCondExpResidual

end MGAP4D.MathlibAnalytic
