import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryOneSlabBetaZeroRankOne
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferNormalization
import Mathlib.Tactic

/-!
# Exact beta-zero physical rank-one transfer

The ambient one-slab Haar-L2 transfer is rank one at beta = 0.  The constant
Haar vector is already the canonical Gauss-law unit vector, so the restriction
to the physical Hilbert space is the same self rank-one operator.

Consequences proved here:

* exact physical action formula at beta = 0;
* exact physical operator identity as a self rank-one projection;
* exact physical operator norm equal to one;
* the canonical physical constant vector is fixed;
* the normalized physical transfer coincides with the same rank-one operator.

No statement about the chosen abstract top eigenvector or the ground-state
joint law is needed in this unit.
-/

namespace MGAP4D.MathlibAnalytic

open MeasureTheory
open scoped InnerProductSpace InnerProduct

noncomputable section

/-- The canonical Haar constant-one vector underlying the physical reference
unit is exactly the beta-zero ambient constant-one vector introduced in the
preceding theorem unit. -/
@[simp] theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector_coe_eq_HaarOneL2
    (H N : ℕ) :
    ((periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N :
        periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) :
      Lp ℝ 2
        (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N)) =
      periodicHypercubicEvenSpecialUnitarySpatialSliceHaarOneL2 H N := by
  rfl

/-- Exact beta-zero action of the physical one-slab transfer. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_apply
    (H N : ℕ)
    (hN : 0 < N)
    (f :
      periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator
        H N hN 0 (by norm_num) f =
      (inner ℝ
        (periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N)
        f) •
      periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N := by
  apply Subtype.ext
  change
    periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabTransferOperator
        H N hN 0 (by norm_num)
        (f :
          Lp ℝ 2
            (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N)) =
      (inner ℝ
        (periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N)
        f) •
      ((periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N :
          periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) :
        Lp ℝ 2
          (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))
  simpa [
    periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector,
    periodicHypercubicEvenSpecialUnitarySpatialSliceHaarOneL2] using
    (periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabTransferOperator_zero_apply
      H N hN
      (f :
        Lp ℝ 2
          (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N)))

/-- Operator form: the physical beta-zero transfer is exactly the self rank-one
projection generated by the canonical constant Gauss-law vector. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_eq_rankOne
    (H N : ℕ)
    (hN : 0 < N) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator
        H N hN 0 (by norm_num) =
      InnerProductSpace.rankOne ℝ
        (periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N)
        (periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N) := by
  apply ContinuousLinearMap.ext
  intro f
  rw [
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_apply
      H N hN f,
    InnerProductSpace.rankOne_apply]

/-- The physical beta-zero one-slab transfer has exact operator norm one. -/
@[simp] theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_norm
    (H N : ℕ)
    (hN : 0 < N) :
    ‖periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator
        H N hN 0 (by norm_num)‖ = 1 := by
  rw [
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_eq_rankOne
      H N hN,
    InnerProductSpace.norm_rankOne,
    periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector_norm]
  norm_num

/-- The canonical constant physical vector is the exact beta-zero top mode. -/
@[simp] theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_constantUnit
    (H N : ℕ)
    (hN : 0 < N) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator
        H N hN 0 (by norm_num)
        (periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N) =
      periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N := by
  rw [
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_apply]
  rw [
    real_inner_self_eq_norm_sq,
    periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector_norm]
  norm_num

/-- Normalization is trivial at beta = 0 because the physical norm is exactly
one. -/
theorem
    periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator_zero_eq
    (H N : ℕ)
    (hN : 0 < N) :
    periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator
        H N hN 0 (by norm_num) =
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator
        H N hN 0 (by norm_num) := by
  unfold
    periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator
  rw [
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_norm
      H N hN]
  norm_num

/-- Hence the normalized physical beta-zero transfer is the same self rank-one
projection. -/
theorem
    periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator_zero_eq_rankOne
    (H N : ℕ)
    (hN : 0 < N) :
    periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator
        H N hN 0 (by norm_num) =
      InnerProductSpace.rankOne ℝ
        (periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N)
        (periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N) := by
  rw [
    periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator_zero_eq
      H N hN,
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_eq_rankOne
      H N hN]

/-- The normalized beta-zero physical transfer fixes the canonical constant
unit vector. -/
@[simp] theorem
    periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator_zero_constantUnit
    (H N : ℕ)
    (hN : 0 < N) :
    periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator
        H N hN 0 (by norm_num)
        (periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N) =
      periodicHypercubicEvenSpecialUnitaryPhysicalConstantUnitVector H N := by
  rw [
    periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator_zero_eq
      H N hN,
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTransferOperator_zero_constantUnit
      H N hN]

end

end MGAP4D.MathlibAnalytic
