import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferVacuumResponseAmplitudeMatrix

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumSecondMeanRMSTargetAmplitude
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumResponseAmplitudeMatrix
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumSecondMeanRMSTargetMajorant_ne_top
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumResponseAmplitudeMatrix_le_canonicalPinFree_mul_targetAmplitude_of_ne
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumResponseAmplitudeMatrix_le_canonicalPinFree_mul_targetAmplitude

end MGAP4D.MathlibAnalytic
