import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferDiagonalUpdatedVarianceGenuineResidual

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_referenceUpdatedBackgroundVarianceEnergy_diagonal_lintegral_eq_kernelSectionFluctuation_sq_lintegral
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_vacuum_diagonal_referenceUpdatedBackgroundVarianceEnergy_lintegral_eq_canonicalFiberVarianceFunctional
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_vacuum_diagonal_referenceUpdatedBackgroundVarianceEnergy_lintegral_le_condExpL2_residual_norm_sq

end MGAP4D.MathlibAnalytic
