import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialSweepStageSourceUpdateCanonicalDirectEnergy

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpatialSliceOffTargetSourceUpdate_offTargetRestriction
#check periodicHypercubicEvenSpatialSliceSourceUpdate_update
#check periodicHypercubicEvenSpatialSliceOffTargetSourceUpdate_offTargetRestriction_eq_after_firstUpdate
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSectionSourceUpdateOrderedDirectDifferenceSquare
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSection_sourceUpdateCanonicalRetained_square_eq_ordered
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSectionSourceUpdateOrderedDirectDifferenceEnergy
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSectionSourceUpdateOrderedDirectDifferenceEnergy_nonneg
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSection_sourceUpdateDirectDifferenceEnergy_canonicalRetained_eq_ordered

end MGAP4D.MathlibAnalytic
