import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferenceOneLinkHeatBathKernelIdempotent
import Mathlib.Probability.Kernel.MeasurableIntegral
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory

noncomputable section

local instance continuousVacuumReferenceOneLinkOffFiberMeasurableSpecialUnitaryIsTopologicalGroup
    (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance continuousVacuumReferenceOneLinkOffFiberMeasurableSpecialUnitaryCompactSpace
    (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance continuousVacuumReferenceOneLinkOffFiberMeasurableSpecialUnitarySecondCountableTopology
    (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance continuousVacuumReferenceOneLinkOffFiberMeasurableSpecialUnitaryMeasurableSpace
    (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance continuousVacuumReferenceOneLinkOffFiberMeasurableSpecialUnitaryBorelSpace
    (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

local instance continuousVacuumReferenceOneLinkOffFiberMeasurableSpatialLinkFintype
    (H : ℕ) :
    Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

/-- Spatial links other than one selected fiber. -/
def PeriodicHypercubicEvenSpatialSliceOffFiberLink
    (H : ℕ)
    (fiber : PeriodicHypercubicEvenSpatialSliceLink H) :=
  {e : PeriodicHypercubicEvenSpatialSliceLink H // e ≠ fiber}

/-- Configuration of all spatial-link coordinates except one selected fiber.
This is an abbreviation rather than an opaque type synonym so that the native
Pi measurable-space instance remains available to typeclass synthesis. -/
abbrev PeriodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberConfiguration
    (H N : ℕ)
    (fiber : PeriodicHypercubicEvenSpatialSliceLink H) :=
  PeriodicHypercubicEvenSpatialSliceOffFiberLink H fiber →
    Matrix.specialUnitaryGroup (Fin N) ℂ

/-- Restrict a spatial-slice configuration to all coordinates away from the
selected fiber. -/
def periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction
    (H N : ℕ)
    (fiber : PeriodicHypercubicEvenSpatialSliceLink H) :
    PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N →
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberConfiguration H N fiber :=
  fun A e => A e.1

/-- Restriction to the off-fiber coordinates is measurable. -/
theorem measurable_periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction
    (H N : ℕ)
    (fiber : PeriodicHypercubicEvenSpatialSliceLink H) :
    Measurable
      (periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction H N fiber) := by
  refine measurable_pi_lambda _ ?_
  intro e
  exact measurable_pi_apply e.1

/-- The sigma algebra generated by all spatial-link coordinates except the
selected fiber. -/
@[reducible] def periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberMeasurableSpace
    (H N : ℕ)
    (fiber : PeriodicHypercubicEvenSpatialSliceLink H) :
    MeasurableSpace
      (PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N) :=
  MeasurableSpace.comap
    (periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction H N fiber)
    inferInstance

/-- The off-fiber sigma algebra is a sub-sigma-algebra of the ambient product
Borel structure. -/
theorem periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberMeasurableSpace_le
    (H N : ℕ)
    (fiber : PeriodicHypercubicEvenSpatialSliceLink H) :
    periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberMeasurableSpace H N fiber ≤
      (inferInstance : MeasurableSpace
        (PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)) := by
  change MeasurableSpace.comap
      (periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction H N fiber)
      inferInstance ≤
    (inferInstance : MeasurableSpace
      (PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N))
  exact
    (measurable_periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction
      H N fiber).comap_le

/-- Assemble a full spatial-slice configuration from a selected fiber value
and an off-fiber configuration. -/
def periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble
    (H N : ℕ)
    (fiber : PeriodicHypercubicEvenSpatialSliceLink H)
    (g : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (Aoff : PeriodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberConfiguration H N fiber) :
    PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N :=
  fun e => if h : e = fiber then g else Aoff ⟨e, h⟩

/-- Assembly with a fixed selected-fiber value is measurable in the off-fiber
configuration. -/
theorem measurable_periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble
    (H N : ℕ)
    (fiber : PeriodicHypercubicEvenSpatialSliceLink H)
    (g : Matrix.specialUnitaryGroup (Fin N) ℂ) :
    Measurable
      (periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble H N fiber g) := by
  refine measurable_pi_lambda _ ?_
  intro e
  by_cases he : e = fiber
  · subst e
    simp [periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble]
  · simpa [periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble, he] using
      (measurable_pi_apply
        (⟨e, he⟩ : PeriodicHypercubicEvenSpatialSliceOffFiberLink H fiber))

/-- Assembling the off-fiber restriction with a chosen fiber value is exactly
ordinary coordinate update. -/
theorem periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble_restriction
    (H N : ℕ)
    (fiber : PeriodicHypercubicEvenSpatialSliceLink H)
    (g : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (A : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N) :
    periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble H N fiber g
        (periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction H N fiber A) =
      Function.update A fiber g := by
  funext e
  by_cases he : e = fiber
  · subst e
    simp [periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble]
  · simp [periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble,
      periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction, he]

/-- Real heat-bath projection associated with the exact measurable reference
one-link Markov kernel. -/
noncomputable def
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source fiber : PeriodicHypercubicEvenSpatialSliceLink H)
    (k g₂ : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (f : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N → ℝ)
    (A : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N) : ℝ :=
  ∫ C, f C
    ∂periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathKernel
      H N hN beta hbeta B target source fiber k g₂ A

/-- The real reference heat-bath projection of a strongly measurable
observable is strongly measurable in the ambient configuration space. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection_stronglyMeasurable
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source fiber : PeriodicHypercubicEvenSpatialSliceLink H)
    (k g₂ : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (f : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N → ℝ)
    (hf : StronglyMeasurable f) :
    StronglyMeasurable
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection
        H N hN beta hbeta B target source fiber k g₂ f) := by
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection
  exact hf.integral_kernel

/-- Canonical off-fiber representative of the real reference heat-bath
projection, obtained by assembling the identity at the selected fiber. -/
noncomputable def
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjectionRepresentative
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source fiber : PeriodicHypercubicEvenSpatialSliceLink H)
    (k g₂ : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (f : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N → ℝ) :
    PeriodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberConfiguration H N fiber → ℝ :=
  fun Aoff =>
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection
      H N hN beta hbeta B target source fiber k g₂ f
      (periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble H N fiber 1 Aoff)

/-- The canonical off-fiber representative is strongly measurable whenever the
original observable is strongly measurable. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjectionRepresentative_stronglyMeasurable
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source fiber : PeriodicHypercubicEvenSpatialSliceLink H)
    (k g₂ : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (f : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N → ℝ)
    (hf : StronglyMeasurable f) :
    StronglyMeasurable
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjectionRepresentative
        H N hN beta hbeta B target source fiber k g₂ f) := by
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjectionRepresentative
  exact
    (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection_stronglyMeasurable
      H N hN beta hbeta B target source fiber k g₂ f hf).comp_measurable
      (measurable_periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble
        H N fiber 1)

/-- The real reference heat-bath projection factors pointwise through
restriction to the off-fiber coordinates. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection_eq_representative_comp_restriction
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source fiber : PeriodicHypercubicEvenSpatialSliceLink H)
    (k g₂ : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (f : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N → ℝ) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection
        H N hN beta hbeta B target source fiber k g₂ f =
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjectionRepresentative
          H N hN beta hbeta B target source fiber k g₂ f ∘
        periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction H N fiber := by
  funext A
  simp only [Function.comp_apply]
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjectionRepresentative
  rw [
    periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberAssemble_restriction
      H N fiber 1 A]
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection
  rw [
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathKernel_update_fiber
      H N hN beta hbeta B target source fiber k g₂ A 1]

/-- The exact real reference one-link heat-bath projection is strongly
measurable with respect to the sigma algebra generated by all coordinates away
from the resampled fiber. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection_offFiberStronglyMeasurable
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source fiber : PeriodicHypercubicEvenSpatialSliceLink H)
    (k g₂ : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (f : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N → ℝ)
    (hf : StronglyMeasurable f) :
    StronglyMeasurable[
      periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberMeasurableSpace H N fiber]
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection
        H N hN beta hbeta B target source fiber k g₂ f) := by
  rw [
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjection_eq_representative_comp_restriction
      H N hN beta hbeta B target source fiber k g₂ f]
  exact
    (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathProjectionRepresentative_stronglyMeasurable
      H N hN beta hbeta B target source fiber k g₂ f hf).comp_measurable
      (comap_measurable
        (periodicHypercubicEvenSpecialUnitarySpatialSliceOffFiberRestriction H N fiber))

end

end MathlibAnalytic
end MGAP4D
