import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointKernelSectionDensityFactorization

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointContinuousKernelSectionFactor
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointContinuousKernelSectionFactor_pos
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointNormalizedWeight_ae_eq_continuousKernelSectionFactor
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointNormalizedENNRealWeight_ae_eq_continuousKernelSectionFactor

end MGAP4D.MathlibAnalytic
