import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointOneLinkCanonicalVarianceVacuumDiagonalSectionL2

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkCanonicalFiberVarianceFunctional_eq_vacuum_diagonalLocalMeanKernelSectionL2_norm_sq_lintegral
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLink_vacuum_diagonalLocalMeanKernelSectionL2_norm_sq_lintegral_le_condExpL2_residual_norm_sq

end MGAP4D.MathlibAnalytic
