import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferTwoSidedRelativePoincare

namespace MGAP4D.MathlibAnalytic

open MeasureTheory Set Filter
open scoped BigOperators Topology InnerProductSpace InnerProduct

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_sourceUpdate_targetResidual_norm_le_add_sourceResidual_allL2
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_pathLoss_controlled_by_initialResidual
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_constantProjection_pythagoras
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_pathLoss_ge_one_sub_lossRatio_mul_constantVariance
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_relativePoincare
#check GroundStateSourceFixedPairEnergy.twoBoundaryOrderedRelativePoincareCoefficient_pos

#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_sourceUpdate_targetResidual_norm_le_add_sourceResidual_allL2
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_relativePoincare

end

end MGAP4D.MathlibAnalytic
