import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenBoundaryMarginalEffectiveMeasureGaugeInvariance
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenWilsonGibbsBoundedContinuousTransport
import Mathlib.MeasureTheory.Integral.Prod

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory Set
open scoped ENNReal

noncomputable section

/-- Marginalizing a density-weighted product measure over the second coordinate
produces the first-coordinate reference measure weighted by the fiber
`lintegral` of the original density.

This is the exact measure-theoretic step needed to pass from the canonical
boundary/open-half/open-half Wilson Gibbs law to its shared-boundary marginal. -/
theorem map_fst_prod_withDensity_eq_withDensity_lintegral
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]
    (μ : Measure α) (ν : Measure β)
    [SFinite μ] [SFinite ν]
    (d : α × β → ℝ≥0∞)
    (hd : Measurable d) :
    Measure.map (Prod.fst : α × β → α) ((μ.prod ν).withDensity d) =
      μ.withDensity (fun x => ∫⁻ y, d (x, y) ∂ν) := by
  ext s hs
  rw [Measure.map_apply measurable_fst hs]
  rw [withDensity_apply _ (hs.preimage measurable_fst)]
  rw [withDensity_apply _ hs]
  have hpre :
      (Prod.fst : α × β → α) ⁻¹' s = s ×ˢ (Set.univ : Set β) := by
    ext z
    simp
  rw [hpre]
  rw [MeasureTheory.setLIntegral_prod d hd.aemeasurable]
  simp

local instance boundaryMarginalPushforwardNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance boundaryMarginalPushforwardTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance boundaryMarginalPushforwardCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance boundaryMarginalPushforwardSecondCountable (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance boundaryMarginalPushforwardMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance boundaryMarginalPushforwardBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- The squared finite Wilson boundary vacuum moment is exactly the ENNReal
marginal density obtained by integrating the canonical boundary-fibered Gibbs
density over both open halves.

The previously proved real-valued identity is lifted back to `ENNReal` using
Mathlib's `ofReal_integral_eq_lintegral_ofReal`. Integrability is not added as a
new hypothesis: it is generated by the existing bounded-continuous transport
with the constant observable `1`. -/
theorem periodicHypercubicEvenBoundaryMarginalEffectiveDensity_eq_lintegral_fiberedGibbsDensity
    (H N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ) (hbeta : 0 ≤ beta)
    (b : PeriodicHypercubicEvenSpecialUnitaryBoundaryConfiguration H N) :
    periodicHypercubicEvenBoundaryMarginalEffectiveDensity
        H N hN beta hbeta b =
      ∫⁻ z,
        periodicHypercubicEvenSpecialUnitaryBoundaryFiberedGibbsDensity
          H N hN beta hbeta (b, z)
        ∂((periodicHypercubicEvenOpenHalfHaarMeasure H N).prod
          (periodicHypercubicEvenOpenHalfHaarMeasure H N)) := by
  letI : SFinite (periodicHypercubicEvenOpenHalfHaarMeasure H N) := by
    dsimp [periodicHypercubicEvenOpenHalfHaarMeasure,
      FiniteInvolutiveEdgeOrbitPartition.openHalfPiMeasure]
    infer_instance
  let one : BoundedContinuousFunction
      (PeriodicHypercubicEvenSpecialUnitaryOpenHalfConfiguration H N) ℝ := 1
  let T :=
    periodicHypercubicEvenWilsonGibbsReflectionTransportData_of_boundedContinuous
      H N hN beta hbeta one
  have hIntWeighted := T.fiberKernelIntegrable b
  have hInt : Integrable
      (fun z :
          PeriodicHypercubicEvenSpecialUnitaryOpenHalfConfiguration H N ×
            PeriodicHypercubicEvenSpecialUnitaryOpenHalfConfiguration H N =>
        (periodicHypercubicEvenSpecialUnitaryBoundaryFiberedGibbsDensity
          H N hN beta hbeta (b, z)).toReal)
      ((periodicHypercubicEvenOpenHalfHaarMeasure H N).prod
        (periodicHypercubicEvenOpenHalfHaarMeasure H N)) := by
    have heq :
        (fun z :
            PeriodicHypercubicEvenSpecialUnitaryOpenHalfConfiguration H N ×
              PeriodicHypercubicEvenSpecialUnitaryOpenHalfConfiguration H N =>
          periodicHypercubicEvenBoundaryWeightedReflectedObservable
            H N hN beta hbeta one (b, z)) =
          fun z =>
            (periodicHypercubicEvenSpecialUnitaryBoundaryFiberedGibbsDensity
              H N hN beta hbeta (b, z)).toReal := by
      funext z
      simp [periodicHypercubicEvenBoundaryWeightedReflectedObservable,
        periodicHypercubicEvenBoundaryReflectedObservable, one]
    rwa [heq] at hIntWeighted
  have hPair :
      (∫ z,
        (periodicHypercubicEvenSpecialUnitaryBoundaryFiberedGibbsDensity
          H N hN beta hbeta (b, z)).toReal
        ∂((periodicHypercubicEvenOpenHalfHaarMeasure H N).prod
          (periodicHypercubicEvenOpenHalfHaarMeasure H N))) =
        ∫ x, ∫ y,
          (periodicHypercubicEvenSpecialUnitaryBoundaryFiberedGibbsDensity
            H N hN beta hbeta (b, (x, y))).toReal
          ∂(periodicHypercubicEvenOpenHalfHaarMeasure H N)
          ∂(periodicHypercubicEvenOpenHalfHaarMeasure H N) :=
    MeasureTheory.integral_prod _ hInt
  unfold periodicHypercubicEvenBoundaryMarginalEffectiveDensity
  rw [← periodicHypercubicEvenBoundaryFiberedGibbsDensity_integral_eq_vacuumMoment_sq
    H N hN beta hbeta b]
  rw [← hPair]
  rw [MeasureTheory.ofReal_integral_eq_lintegral_ofReal hInt
    (Filter.Eventually.of_forall fun _ => ENNReal.toReal_nonneg)]
  apply lintegral_congr
  intro z
  rw [ENNReal.ofReal_toReal]
  simp [periodicHypercubicEvenSpecialUnitaryBoundaryFiberedGibbsDensity,
    ContinuousCompactOrientedGaugeWilsonSystem.boundaryFiberedGibbsDensity]

/-- The canonical boundary restriction of the actual finite-volume periodic
`SU(N)` Wilson Gibbs law is exactly the effective boundary measure generated by
the squared finite OS vacuum moment.

Thus the effective boundary law is not an auxiliary gauge-invariant measure: it
is the literal shared-boundary pushforward of the same normalized Wilson Gibbs
probability measure used by the finite lattice theory. -/
theorem periodicHypercubicEvenBoundaryRestriction_map_gibbsMeasure_eq_effectiveMeasure
    (H N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ) (hbeta : 0 ≤ beta) :
    Measure.map
        (periodicHypercubicEvenEdgeOrbitPartition H).boundaryRestriction
        (periodicHypercubicSpecialUnitaryWilsonSystem
          (PeriodicHypercubicEvenSideLength H) N hN beta hbeta).gibbsMeasure =
      periodicHypercubicEvenBoundaryMarginalEffectiveMeasure
        H N hN beta hbeta := by
  let Gauge := Matrix.specialUnitaryGroup (Fin N) ℂ
  let P := periodicHypercubicEvenEdgeOrbitPartition H
  let C := periodicHypercubicSpecialUnitaryWilsonSystem
    (PeriodicHypercubicEvenSideLength H) N hN beta hbeta
  let μb := periodicHypercubicEvenBoundaryHaarMeasure H N
  let μh := periodicHypercubicEvenOpenHalfHaarMeasure H N
  let d := periodicHypercubicEvenSpecialUnitaryBoundaryFiberedGibbsDensity
    H N hN beta hbeta
  letI : SFinite μb := by
    dsimp [μb, periodicHypercubicEvenBoundaryHaarMeasure,
      FiniteInvolutiveEdgeOrbitPartition.boundaryPiMeasure]
    infer_instance
  letI : SFinite μh := by
    dsimp [μh, periodicHypercubicEvenOpenHalfHaarMeasure,
      FiniteInvolutiveEdgeOrbitPartition.openHalfPiMeasure]
    infer_instance
  have hcoords :
      Measure.map (P.boundaryFiberedCoordinates Gauge) C.gibbsMeasure =
        (μb.prod (μh.prod μh)).withDensity d := by
    simpa [P, C, μb, μh, d,
      periodicHypercubicEvenBoundaryHaarMeasure,
      periodicHypercubicEvenOpenHalfHaarMeasure] using
      (periodicHypercubicEvenSpecialUnitary_map_boundaryFiberedCoordinates_gibbsMeasure
        H N hN beta hbeta)
  have hd : Measurable d := by
    simpa [d] using
      (periodicHypercubicEvenSpecialUnitaryBoundaryFiberedGibbsDensity_measurable
        H N hN beta hbeta)
  have hmarg :
      (fun b => ∫⁻ z, d (b, z) ∂(μh.prod μh)) =
        periodicHypercubicEvenBoundaryMarginalEffectiveDensity
          H N hN beta hbeta := by
    funext b
    symm
    simpa [d, μh] using
      periodicHypercubicEvenBoundaryMarginalEffectiveDensity_eq_lintegral_fiberedGibbsDensity
        H N hN beta hbeta b
  calc
    Measure.map P.boundaryRestriction C.gibbsMeasure =
        Measure.map
          (Prod.fst :
            P.BoundaryConfiguration Gauge ×
              (P.OpenHalfConfiguration Gauge × P.OpenHalfConfiguration Gauge) →
            P.BoundaryConfiguration Gauge)
          (Measure.map (P.boundaryFiberedCoordinates Gauge) C.gibbsMeasure) := by
      simpa [FiniteInvolutiveEdgeOrbitPartition.boundaryFiberedCoordinates] using
        (Measure.map_map
          (μ := C.gibbsMeasure)
          measurable_fst
          (P.boundaryFiberedCoordinates_measurable Gauge)).symm
    _ = Measure.map
        (Prod.fst :
          P.BoundaryConfiguration Gauge ×
            (P.OpenHalfConfiguration Gauge × P.OpenHalfConfiguration Gauge) →
          P.BoundaryConfiguration Gauge)
        ((μb.prod (μh.prod μh)).withDensity d) := by
      rw [hcoords]
    _ = μb.withDensity (fun b => ∫⁻ z, d (b, z) ∂(μh.prod μh)) := by
      exact map_fst_prod_withDensity_eq_withDensity_lintegral
        μb (μh.prod μh) d hd
    _ = μb.withDensity
        (periodicHypercubicEvenBoundaryMarginalEffectiveDensity
          H N hN beta hbeta) := by
      rw [hmarg]
    _ = periodicHypercubicEvenBoundaryMarginalEffectiveMeasure
        H N hN beta hbeta := by
      rfl

end

end MathlibAnalytic
end MGAP4D
