import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryOneSlabBetaZeroRankOne

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabKernel_zero
#check periodicHypercubicEvenSpecialUnitarySpatialSliceHaarOneL2
#check periodicHypercubicEvenSpecialUnitarySpatialSliceHaarOneL2_norm
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabKernelPairL2_zero_eq_externalTensor
#check realL2HilbertSchmidtKernelOperator_externalTensor_apply
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabTransferOperator_zero_apply
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabTransferOperator_zero_eq_rankOne
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabTransferOperator_zero_one

end

end MGAP4D.MathlibAnalytic
