import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferCrossBoundaryKernelSectionL2MeanDifference

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousSpatialLinkNormalizedMeasure_crossBoundary_L2MeanDifference_sq_le_varianceSum_supported_on_diagonal
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousSpatialLinkNormalizedMeasure_crossBoundary_L2MeanDifference_sq_le_varianceSum_diagonal

#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousSpatialLinkNormalizedMeasure_crossBoundary_L2MeanDifference_sq_le_varianceSum_supported_on_diagonal
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftKernelSectionContinuousSpatialLinkNormalizedMeasure_crossBoundary_L2MeanDifference_sq_le_varianceSum_diagonal

end

end MGAP4D.MathlibAnalytic
