import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateTargetResidualCommutatorNonexpansiveStep

namespace MGAP4D.MathlibAnalytic

#check
  realHilbertProjectionSweep_targetResidual_apply_eq_neg_commutator_add_feedback

#check
  realHilbertIdempotentSymmetricProjection_norm_le

#check
  realHilbertIdempotentSymmetricProjection_residual_norm_le

#check
  realHilbertProjectionSweep_targetResidual_feedback_norm_le

#check
  realHilbertProjectionSweep_targetResidual_apply_norm_le_commutatorCoefficient_mul_projectedNorm_add_residual

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLink_targetResidual_apply_norm_le_commutatorCoefficient_mul_norm_add_residual

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLink_targetResidual_apply_norm_le_residual_zero

end MGAP4D.MathlibAnalytic
