import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferVacuumSecondMeanRMSDeweightedMajorant

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLawVacuumSecondMeanRMSAmplitudeEnergy
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_feedbackGap_mul_vacuumSecondMeanRMSAmplitudeEnergy_le_harnackFactor_add_one_mul_condExpL2_residual_norm_sq
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_vacuumSecondMeanRMSAmplitudeEnergy_le_feedbackGap_inv_mul_harnackFactor_add_one_mul_condExpL2_residual_norm_sq

end MGAP4D.MathlibAnalytic
