import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferenceBackgroundUpdateRMSCauchy

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberWeight_measurable
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure_backgroundUpdate_centered_integral_sub_abs_le_harnackInfluence_mul_sqrt_energy

end

end MGAP4D.MathlibAnalytic
