import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferBetaZeroGroundStateSameColorOneLinkSweepEqualsColorBlock

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenFixedSpatialColorLink_nonempty
#check periodicHypercubicEvenFixedSpatialColorLink_univ_toList_ne_nil

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkPairHaar_commonFixed_iff_mem_colorLpMeas

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkPairHaarFullSweep_fixed_iff_color_fixed

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkPairHaarFullSweep_eq_colorProjection

end

end MGAP4D.MathlibAnalytic
