import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferTwoSidedActualOneLinkLeakage

namespace MGAP4D.MathlibAnalytic

open MeasureTheory
open scoped InnerProductSpace

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_leftSpatialLinkCondExpL2
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLinkCondExpL2_mem_boundedConcreteCore
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLinkCondExpL2_idempotent
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLinkCondExpL2_symmetric
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftSourceUpdate_jointLeakage_norm_le_orderedNormCoefficient
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateCrossBoundary_rightSourceUpdate_leakage_norm_le_crossMajorant
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_sourceUpdate_leakage_norm_le_orderedKernel
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_sourceUpdate_targetResidual_norm_le_add_sourceResidual

#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_sourceUpdate_leakage_norm_le_orderedKernel
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_sourceUpdate_targetResidual_norm_le_add_sourceResidual

end

end MGAP4D.MathlibAnalytic
