import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourcePairCanonicalAssembledCurrentValueState

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalAssembledCurrentValueFixedBackgroundL2
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalAssembledCurrentValueFixedBackgroundL2_eq_localPart_add_sum_response
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalAssembledCurrentValue_aeOuterLIntegralTransposeSchurReceiver_of_offDiagonalSecondMeanRMSMajorant

end MGAP4D.MathlibAnalytic
