import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferTwoSidedTwelveSpatialUniformGap

namespace MGAP4D
namespace MathlibAnalytic

#check GroundStateSourceFixedPairEnergy.twoSidedTwelveSpatialUniformGapCutoff_pos
#check GroundStateSourceFixedPairEnergy.twoSidedTwelveSpatialUniformPoincareCoefficient_le_relativeFrameCoefficient
#check periodicHypercubicEvenSpecialUnitary_hasUniformGroundStateTwelveSpatialPoincareOnPhysicalRightLifts_of_uniformGapCutoff
#check periodicHypercubicEvenSpecialUnitary_hasUniformTopEigenspaceTransferGap_of_twoSidedTwelveSpatialUniformGapCutoff
#check periodicHypercubicEvenSpecialUnitary_uniformTopEigenspaceTransferGap_ge_one_div_3072

end MathlibAnalytic
end MGAP4D
