import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferBetaZeroSixSpatialHaarColorSplit

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check PeriodicHypercubicEvenSpatialSliceColorLink

#check periodicHypercubicEvenSpatialSliceColorOffColorMeasurableEquiv

#check periodicHypercubicEvenSpecialUnitarySpatialSliceColorOffColorHaar_measurePreserving

#check periodicHypercubicEvenSpecialUnitaryGroundStateJointColorSplitMeasurableEquiv

#check periodicHypercubicEvenSpecialUnitaryGroundStateJointColorSplitHaar_measurePreserving

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointMeasure_zero_colorSplit_measurePreserving

end

end MGAP4D.MathlibAnalytic
