import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourcePairSecondMeanRMSFirstCrossTransport

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLawFirstVarianceEnergyAtSecondMeanOnCarrier_ofReal_eq_targetFiber_lintegral
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLawFirstVarianceEnergyAtSecondMeanOnCarrier_lintegral_eq_orderedFirstCrossEnergy_lintegral

end MGAP4D.MathlibAnalytic
