import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointTwelveSpatialBoundedConcreteCoreClosure

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check continuous_groundStateJointColorNormalizedResidualEnergy

#check
  continuous_periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwelveSpatialResidualEnergy

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwelveSpatialRelativePoincare_of_boundedConcreteCore

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwelveSpatialPoincare_on_sector_of_boundedConcreteCore

end

end MGAP4D.MathlibAnalytic
