import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialRandomScanRayleigh

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check groundStateJointColorRandomScanOperator
#check groundStateJointColorRandomScanOperator_inner_eq_meanProjectedNormSq
#check groundStateJointColorFrame_iff_randomScanRayleigh_le

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialRandomScanL2

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialRandomScanL2_inner_eq_meanProjectedNormSq

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialFrame_iff_randomScanRayleighContraction

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialRandomScanRayleighContraction_implies_transferGap

#check
  PeriodicHypercubicEvenSpecialUnitaryHasUniformGroundStateSixSpatialRandomScanRayleighContraction

#check
  periodicHypercubicEvenSpecialUnitary_uniformGroundStateSixSpatialRandomScanRayleighContraction_implies_uniformTransferGap

end

end MGAP4D.MathlibAnalytic
