import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferenceRemoteConditionalCrossRatioInfluence
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferenceTargetWorstCaseCrossRatioInfluenceRemoteColumn
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory BigOperators

noncomputable section

local instance remoteBoundedTestInfluenceColumnSpatialLinkFintype
    (H : ℕ) : Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

local instance remoteBoundedTestInfluenceColumnSpecialUnitaryMeasurableSpace
    (N : ℕ) : MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

/-- Sum, over the canonical C5 remote target family, the actual bounded-test
differences of the off-target one-link reference conditional laws generated by
one common source update from u to v.

This is a finite chosen-test column.  It is not a supremum over tests or
background configurations and is not yet declared to be a global Dobrushin
coefficient. -/
noncomputable def
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceRemoteBoundedTestDifferenceColumn
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (source distinguishedTarget distinguishedSource : PeriodicHypercubicEvenSpatialSliceLink H)
    (k g₂ u v : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (A : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (phi : PeriodicHypercubicEvenSpatialSliceLink H →
      Matrix.specialUnitaryGroup (Fin N) ℂ → ℝ) : ℝ :=
  ∑ target ∈
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceC5RemoteTargetFibers
        H source distinguishedTarget,
    |(∫ g, phi target g ∂
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure
          H N hN beta hbeta B distinguishedTarget distinguishedSource target k g₂
          (Function.update A source u)) -
      (∫ g, phi target g ∂
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure
          H N hN beta hbeta B distinguishedTarget distinguishedSource target k g₂
          (Function.update A source v))|

/-- The chosen-test remote conditional-law column is termwise bounded by the
already-canonical targetwise worst-case cross-ratio majorants.  No supremum is
interchanged with the finite target sum. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceRemoteBoundedTestDifferenceColumn_le_worstCaseRemoteCrossRatioInfluenceColumn
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (source distinguishedTarget distinguishedSource : PeriodicHypercubicEvenSpatialSliceLink H)
    (k g₂ u v : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (A : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (phi : PeriodicHypercubicEvenSpatialSliceLink H →
      Matrix.specialUnitaryGroup (Fin N) ℂ → ℝ)
    (hphi : ∀ target, StronglyMeasurable (phi target))
    (hphiBound : ∀ target g, |phi target g| ≤ 1) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceRemoteBoundedTestDifferenceColumn
        H N hN beta hbeta B source distinguishedTarget distinguishedSource k g₂ u v A phi ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioWorstCaseRemoteCrossRatioInfluenceColumn
        H N hN beta hbeta A source distinguishedTarget := by
  classical
  let remote :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceC5RemoteTargetFibers
      H source distinguishedTarget
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceRemoteBoundedTestDifferenceColumn
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioWorstCaseRemoteCrossRatioInfluenceColumn
  apply Finset.sum_le_sum
  intro target hTarget
  have hRemote :
      target ∉
        periodicHypercubicEvenSpatialSliceC5ExceptionalBackgroundFibers
          H source distinguishedTarget := by
    simpa [
      remote,
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceC5RemoteTargetFibers] using
      hTarget
  rcases
    periodicHypercubicEvenSpatialSlice_not_mem_C5ExceptionalBackgroundFibers
      H source distinguishedTarget target hRemote with
    ⟨hSourceTarget, hTargetDistinguished, hNoShare⟩
  simpa using
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkFiberProbabilityMeasure_remote_boundedTest_integral_difference_abs_le_worstCaseCrossRatioInfluenceMajorant
      H N hN beta hbeta B
      distinguishedTarget distinguishedSource target source
      hTargetDistinguished hSourceTarget hNoShare
      k g₂ u v A (phi target) (hphi target) (hphiBound target)

/-- Combining the actual chosen-test conditional-law column with the merged
worst-case remote-column theorem gives the same arbitrary-step aggregate tagged
transport bound.  This is still a finite chosen-test statement; it does not
assert a test-supremum or a volume-independent residual constant rho. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceRemoteBoundedTestDifferenceColumn_le_exp_sixteen_mul_nStepAggregateRight_add_two_mul_leftVariationTotal
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (source distinguishedTarget distinguishedSource : PeriodicHypercubicEvenSpatialSliceLink H)
    (k g₂ u v : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (A : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (phi : PeriodicHypercubicEvenSpatialSliceLink H →
      Matrix.specialUnitaryGroup (Fin N) ℂ → ℝ)
    (hphi : ∀ target, StronglyMeasurable (phi target))
    (hphiBound : ∀ target g, |phi target g| ≤ 1)
    (n : ℕ) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceRemoteBoundedTestDifferenceColumn
        H N hN beta hbeta B source distinguishedTarget distinguishedSource k g₂ u v A phi ≤
      Real.exp (16 * beta) *
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberTaggedRestrictedRandomScanVariationIterate
            H beta hbeta
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioRemoteAggregateVariation
              H beta source distinguishedTarget)
            n (Sum.inr source) +
          2 *
            ∑ e : PeriodicHypercubicEvenSpatialSliceLink H,
              periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberTaggedRestrictedRandomScanVariationIterate
                H beta hbeta
                (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioRemoteAggregateVariation
                  H beta source distinguishedTarget)
                n (Sum.inl e)) := by
  calc
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceRemoteBoundedTestDifferenceColumn
        H N hN beta hbeta B source distinguishedTarget distinguishedSource k g₂ u v A phi ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioWorstCaseRemoteCrossRatioInfluenceColumn
        H N hN beta hbeta A source distinguishedTarget :=
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceRemoteBoundedTestDifferenceColumn_le_worstCaseRemoteCrossRatioInfluenceColumn
        H N hN beta hbeta B source distinguishedTarget distinguishedSource
        k g₂ u v A phi hphi hphiBound
    _ ≤
      Real.exp (16 * beta) *
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberTaggedRestrictedRandomScanVariationIterate
            H beta hbeta
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioRemoteAggregateVariation
              H beta source distinguishedTarget)
            n (Sum.inr source) +
          2 *
            ∑ e : PeriodicHypercubicEvenSpatialSliceLink H,
              periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberTaggedRestrictedRandomScanVariationIterate
                H beta hbeta
                (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioRemoteAggregateVariation
                  H beta source distinguishedTarget)
                n (Sum.inl e)) :=
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioWorstCaseRemoteCrossRatioInfluenceColumn_le_exp_sixteen_mul_nStepAggregateRight_add_two_mul_leftVariationTotal
        H N hN beta hbeta A source distinguishedTarget n

end

end MathlibAnalytic
end MGAP4D
