import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateSixRetainedBoundaryEquality

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundState_fst_lpMeas_le_rightSixRetained

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateRightSixRetainedLpMeas_eq_fst

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundState_snd_lpMeas_le_leftSixRetained

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftSixRetainedLpMeas_eq_snd

end

end MGAP4D.MathlibAnalytic
