import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSweepBlockDefectCyclicSourceUpdateSemantics

namespace MGAP4D.MathlibAnalytic

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointCyclicSourcePairCanonicalTargetLawFullDifferenceL2_eq_directDifferenceL2_add_responseL2

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointCyclicSourceUpdateBackwardLawResponse_currentValue_targetUpdate_eq_neg_transposedCanonicalTargetLawResponse_of_bounded

end MGAP4D.MathlibAnalytic
