import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateTargetCrossResidualCommutatorFeedbackReceiver

namespace MGAP4D.MathlibAnalytic

#check
  realHilbertProjectionSweepTargetCrossResidual_norm_le_commutatorCoefficient_mul_projectedNorm_add_feedback

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTargetCrossResidual_norm_le_commutatorCoefficient_mul_norm_add_feedback

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTargetCrossResidual_zero_eq_feedback

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkTargetCrossResidual_zero_norm_eq_feedback_norm

end MGAP4D.MathlibAnalytic
