import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferTwoSidedCyclicForcingBudget

namespace MGAP4D.MathlibAnalytic

open MeasureTheory

noncomputable section

#check realHilbertProjectionSweep_targetResidual_norm_le_forcingBudget_add_initial_of_preserved
#check realHilbertProjectionSweep_targetResidual_norm_le_forcingBudget_of_fixed_of_preserved
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLinkSweep_mem_boundedConcreteCore
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_targetResidual_norm_le_orderedForcingBudget_of_fixed
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_cyclicTargetResidual_norm_le_orderedForcingBudget

#print axioms realHilbertProjectionSweep_targetResidual_norm_le_forcingBudget_of_fixed_of_preserved
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_targetResidual_norm_le_orderedForcingBudget_of_fixed
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_cyclicTargetResidual_norm_le_orderedForcingBudget

end

end MGAP4D.MathlibAnalytic
