import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferBetaZeroGroundStateSweepBlockDefectZero

namespace MGAP4D.MathlibAnalytic

#check realL2CastOfMeasureEq_injective

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroJointToPairHaarL2_injective

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZero_fixedSpatialColor_fullOneLinkSweep_eq_colorCondExp

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZero_fixedSpatialColorOneLinkSweepBlockDefectVector_eq_zero

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZero_sixSpatialOneLinkSweepBlockDefectMeanNormSq_eq_zero

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZero_sixSpatialOneLinkFullSweepMeanNormSq_eq_meanProjectedNormSq

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatialFullSweepMean_five_six

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatial_sweepBlockDefect_zero_majorant

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatial_zeroSweepBlockDefect_receiver_transferGap

end MGAP4D.MathlibAnalytic
