import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferPosteriorJointResamplingDirichlet

open MGAP4D.MathlibAnalytic

#check GroundStatePosteriorJoint.sourceRightLinkTilt_sub_one_abs_le
#check GroundStatePosteriorJoint.jointTransferKernel_right_update_eq_sourceTilt
#check GroundStatePosteriorJoint.sourceLinkResponse_integrable
#check GroundStatePosteriorJoint.sourceLinkResponse_abs_le_envelope
#check GroundStatePosteriorJoint.jointTransferLinkDifference_eq_sourceTilt
#check GroundStatePosteriorJoint.jointTransferSourceContrast_eq
#check GroundStatePosteriorJoint.fineFrozenInitialEnergy_eq_sourceTilt
