import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialFullSweepMeanProjectionBridge

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweepBlockDefectMeanNormSq_nonneg
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkFullSweepMeanNormSq_eq_meanProjectedNormSq_add_sweepBlockDefectMeanNormSq
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatial_meanProjectedNormSq_le_fullSweepMeanNormSq
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkFullSweepMeanContraction_implies_transferGap
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkFullSweepMeanContraction_positive_transferGap

end MGAP4D.MathlibAnalytic
