import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTopEigenspaceOrthogonalDecomposition
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryOneSlabPairHaarL2TopEigenspaceBlockClosureOrthogonality
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory
open scoped InnerProductSpace InnerProduct

noncomputable section

local instance physicalPairCarrierTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance physicalPairCarrierCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance physicalPairCarrierSecondCountable (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance physicalPairCarrierMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance physicalPairCarrierBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

local instance physicalPairCarrierSpatialLinkFintype (H : ℕ) :
    Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

local instance physicalPairCarrierSpatialSliceHaarSFinite (H N : ℕ) :
    SFinite (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N) := by
  unfold periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure
  infer_instance

/-- An arbitrary decomposable pair vector built from two vectors of the finite-volume
physical one-slice gauge-invariant Hilbert carrier. -/
noncomputable def periodicHypercubicEvenSpecialUnitaryPhysicalPairDecomposableL2
    (H N : ℕ)
    (x y : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) :
    PeriodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarL2 H N :=
  realL2ExternalTensor
    (x : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))
    (y : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))

/-- The decomposable physical-pair generators before taking their real linear span. -/
noncomputable def periodicHypercubicEvenSpecialUnitaryPhysicalPairGeneratorSet
    (H N : ℕ) :
    Set (PeriodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarL2 H N) :=
  Set.range fun p :
      periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N ×
        periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N =>
    periodicHypercubicEvenSpecialUnitaryPhysicalPairDecomposableL2 H N p.1 p.2

/-- Algebraic physical pair sector generated by all decomposable tensors of one-slice
physical vectors. -/
noncomputable def periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan
    (H N : ℕ) :
    Submodule ℝ (PeriodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarL2 H N) :=
  Submodule.span ℝ (periodicHypercubicEvenSpecialUnitaryPhysicalPairGeneratorSet H N)

/-- Hilbert completion of the decomposable physical pair sector.  This is the physical
pair carrier used below; no equality with the full ambient pair Haar `L²` is asserted. -/
noncomputable def periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier
    (H N : ℕ) :
    Submodule ℝ (PeriodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarL2 H N) :=
  (periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan H N).topologicalClosure

/-- Every decomposable physical pair vector expands into the four blocks induced by
`F ⊕ Fᗮ` on the two one-slice factors.  The statement retains the full top eigenspace
and does not assume it is one-dimensional. -/
theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairDecomposableL2_fourBlockExpansion
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta)
    (x y : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) :
    ∃ u : periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTopEigenspace
        H N hN beta hbeta,
      ∃ f : periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTopEigenspaceOrthogonal
          H N hN beta hbeta,
        ∃ v : periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTopEigenspace
            H N hN beta hbeta,
          ∃ g : periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTopEigenspaceOrthogonal
              H N hN beta hbeta,
            x = (u : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) +
                (f : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) ∧
            y = (v : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) +
                (g : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) ∧
            periodicHypercubicEvenSpecialUnitaryPhysicalPairDecomposableL2 H N x y =
              periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopDecomposableL2
                  H N hN beta hbeta u v +
                ((periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalTopDecomposableL2
                    H N hN beta hbeta f v +
                  periodicHypercubicEvenSpecialUnitaryPhysicalPairTopOrthogonalDecomposableL2
                    H N hN beta hbeta u g) +
                  periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalOrthogonalDecomposableL2
                    H N hN beta hbeta f g) := by
  obtain ⟨u0, hu0, f0, hf0, huf⟩ :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlab_exists_top_add_orthogonal
      H N hN beta hbeta x
  obtain ⟨v0, hv0, g0, hg0, hvg⟩ :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlab_exists_top_add_orthogonal
      H N hN beta hbeta y
  let u : periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTopEigenspace
      H N hN beta hbeta := ⟨u0, hu0⟩
  let f : periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTopEigenspaceOrthogonal
      H N hN beta hbeta := ⟨f0, hf0⟩
  let v : periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTopEigenspace
      H N hN beta hbeta := ⟨v0, hv0⟩
  let g : periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabTopEigenspaceOrthogonal
      H N hN beta hbeta := ⟨g0, hg0⟩
  refine ⟨u, f, v, g, ?_, ?_, ?_⟩
  · simpa [u, f] using huf.symm
  · simpa [v, g] using hvg.symm
  · rw [← huf, ← hvg]
    change
      realL2ExternalTensor
          (((u0 + f0 : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) :
            Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N)))
          (((v0 + g0 : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N) :
            Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))) =
        realL2ExternalTensor
            (u0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))
            (v0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N)) +
          ((realL2ExternalTensor
              (f0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))
              (v0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N)) +
            realL2ExternalTensor
              (u0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))
              (g0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))) +
            realL2ExternalTensor
              (f0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))
              (g0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))
    change
      realL2ExternalTensor
          ((u0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N)) +
            (f0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N)))
          ((v0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N)) +
            (g0 : Lp ℝ 2 (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N))) = _
    rw [realL2ExternalTensor_add_right,
      realL2ExternalTensor_add_left,
      realL2ExternalTensor_add_left]
    abel

private theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan_le_physicalPairSpan
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan H N hN beta hbeta ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan H N := by
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan]
  refine Submodule.span_le.2 ?_
  intro z hz
  rcases hz with ⟨⟨u, v⟩, rfl⟩
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan]
  apply Submodule.subset_span
  refine ⟨((u : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N),
    (v : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N)), ?_⟩
  rfl

private theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalTopBlockSpan_le_physicalPairSpan
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalTopBlockSpan H N hN beta hbeta ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan H N := by
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalTopBlockSpan]
  refine Submodule.span_le.2 ?_
  intro z hz
  rcases hz with ⟨⟨f, u⟩, rfl⟩
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan]
  apply Submodule.subset_span
  refine ⟨((f : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N),
    (u : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N)), ?_⟩
  rfl

private theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairTopOrthogonalBlockSpan_le_physicalPairSpan
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairTopOrthogonalBlockSpan H N hN beta hbeta ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan H N := by
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairTopOrthogonalBlockSpan]
  refine Submodule.span_le.2 ?_
  intro z hz
  rcases hz with ⟨⟨u, f⟩, rfl⟩
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan]
  apply Submodule.subset_span
  refine ⟨((u : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N),
    (f : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N)), ?_⟩
  rfl

private theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalOrthogonalBlockSpan_le_physicalPairSpan
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalOrthogonalBlockSpan
        H N hN beta hbeta ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan H N := by
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalOrthogonalBlockSpan]
  refine Submodule.span_le.2 ?_
  intro z hz
  rcases hz with ⟨⟨f, g⟩, rfl⟩
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan]
  apply Submodule.subset_span
  refine ⟨((f : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N),
    (g : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule H N)), ?_⟩
  rfl

/-- The physical decomposable pair span is exactly the algebraic sum of the top-top
block and the three non-top blocks.  This is the algebraic carrier identity that
precedes Hilbert completion. -/
theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan_eq_topTop_sup_nonTop
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan H N =
      periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan H N hN beta hbeta ⊔
        periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockSpan H N hN beta hbeta := by
  apply le_antisymm
  · rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan]
    refine Submodule.span_le.2 ?_
    intro z hz
    rcases hz with ⟨⟨x, y⟩, rfl⟩
    obtain ⟨u, f, v, g, hx, hy, hexpand⟩ :=
      periodicHypercubicEvenSpecialUnitaryPhysicalPairDecomposableL2_fourBlockExpansion
        H N hN beta hbeta x y
    let tt := periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopDecomposableL2
      H N hN beta hbeta u v
    let ot := periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalTopDecomposableL2
      H N hN beta hbeta f v
    let to := periodicHypercubicEvenSpecialUnitaryPhysicalPairTopOrthogonalDecomposableL2
      H N hN beta hbeta u g
    let oo := periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalOrthogonalDecomposableL2
      H N hN beta hbeta f g
    have htt : tt ∈ periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan
        H N hN beta hbeta := by
      rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan]
      apply Submodule.subset_span
      exact ⟨(u, v), rfl⟩
    have hot : ot ∈ periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalTopBlockSpan
        H N hN beta hbeta := by
      rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalTopBlockSpan]
      apply Submodule.subset_span
      exact ⟨(f, v), rfl⟩
    have hto : to ∈ periodicHypercubicEvenSpecialUnitaryPhysicalPairTopOrthogonalBlockSpan
        H N hN beta hbeta := by
      rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairTopOrthogonalBlockSpan]
      apply Submodule.subset_span
      exact ⟨(u, g), rfl⟩
    have hoo : oo ∈ periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalOrthogonalBlockSpan
        H N hN beta hbeta := by
      rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalOrthogonalBlockSpan]
      apply Submodule.subset_span
      exact ⟨(f, g), rfl⟩
    have hnontop : (ot + to) + oo ∈
        periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockSpan H N hN beta hbeta := by
      rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockSpan]
      refine Submodule.mem_sup.2 ⟨ot + to, ?_, oo, hoo, rfl⟩
      exact Submodule.mem_sup.2 ⟨ot, hot, to, hto, rfl⟩
    rw [hexpand]
    exact Submodule.mem_sup.2 ⟨tt, htt, (ot + to) + oo, hnontop, rfl⟩
  · refine sup_le
      (periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan_le_physicalPairSpan
        H N hN beta hbeta) ?_
    rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockSpan]
    exact sup_le
      (sup_le
        (periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalTopBlockSpan_le_physicalPairSpan
          H N hN beta hbeta)
        (periodicHypercubicEvenSpecialUnitaryPhysicalPairTopOrthogonalBlockSpan_le_physicalPairSpan
          H N hN beta hbeta))
      (periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalOrthogonalBlockSpan_le_physicalPairSpan
        H N hN beta hbeta)

/-- The completed physical pair carrier is the closure of the algebraic top-top plus
non-top block sum. -/
theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier_eq_topologicalClosure_topTop_sup_nonTop
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier H N =
      (periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan H N hN beta hbeta ⊔
        periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockSpan
          H N hN beta hbeta).topologicalClosure := by
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier,
    periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan_eq_topTop_sup_nonTop
      H N hN beta hbeta]

/-- The completed top-top block is contained in the completed physical pair carrier. -/
theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure_le_physicalPairCarrier
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure H N hN beta hbeta ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier H N := by
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure,
    periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier]
  exact Submodule.topologicalClosure_mono
    (periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan_le_physicalPairSpan
      H N hN beta hbeta)

/-- The completed non-top block is contained in the completed physical pair carrier. -/
theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockClosure_le_physicalPairCarrier
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockClosure H N hN beta hbeta ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier H N := by
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockClosure,
    periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier]
  apply Submodule.topologicalClosure_mono
  rw [periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockSpan]
  exact sup_le
    (sup_le
      (periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalTopBlockSpan_le_physicalPairSpan
        H N hN beta hbeta)
      (periodicHypercubicEvenSpecialUnitaryPhysicalPairTopOrthogonalBlockSpan_le_physicalPairSpan
        H N hN beta hbeta))
    (periodicHypercubicEvenSpecialUnitaryPhysicalPairOrthogonalOrthogonalBlockSpan_le_physicalPairSpan
      H N hN beta hbeta)

/-- Audit-visible algebraic physical-pair carrier package. -/
structure PeriodicHypercubicEvenSpecialUnitaryPhysicalPairCarrierFourBlockDecompositionPackage
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) : Prop where
  algebraicDecomposition :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan H N =
      periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan H N hN beta hbeta ⊔
        periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockSpan H N hN beta hbeta
  topTopContained :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure H N hN beta hbeta ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier H N
  nonTopContained :
    periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockClosure H N hN beta hbeta ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrier H N

/-- Construct the algebraic physical-pair carrier decomposition package. -/
theorem periodicHypercubicEvenSpecialUnitaryPhysicalPairCarrierFourBlockDecompositionPackage
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    PeriodicHypercubicEvenSpecialUnitaryPhysicalPairCarrierFourBlockDecompositionPackage
      H N hN beta hbeta :=
  { algebraicDecomposition :=
      periodicHypercubicEvenSpecialUnitaryPhysicalPairSpan_eq_topTop_sup_nonTop
        H N hN beta hbeta
    topTopContained :=
      periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure_le_physicalPairCarrier
        H N hN beta hbeta
    nonTopContained :=
      periodicHypercubicEvenSpecialUnitaryPhysicalPairNonTopBlockClosure_le_physicalPairCarrier
        H N hN beta hbeta }

end

end MathlibAnalytic
end MGAP4D
