import MGAP4D.MathlibAnalytic.PeriodicHypercubicSpecialUnitaryUniformImplicitEulerOSResolventDefinitionL2

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

end

end MathlibAnalytic
end MGAP4D
