import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenCyclicFourEdgeNormalizedTraceHilbertPullback
import Mathlib.Analysis.Normed.Module.FiniteDimension

namespace MGAP4D
namespace MathlibAnalytic

open scoped TensorProduct InnerProduct InnerProductSpace

noncomputable section

local instance cyclicFourEdgeSourcePowerMeasurableSpace :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin 2) ℂ) :=
  specialUnitaryGroupMeasurableSpace 2

private theorem cyclicFourEdgeSourcePowerTwoRankPositive : 0 < (2 : ℕ) := by
  norm_num

noncomputable local instance cyclicFourEdgeSourcePowerPairNormedAddCommGroup :
    NormedAddCommGroup SpecialUnitaryTwoNormalizedTracePairTensorSpace :=
  TensorProduct.instNormedAddCommGroup

noncomputable local instance cyclicFourEdgeSourcePowerPairInnerProductSpace :
    InnerProductSpace ℝ SpecialUnitaryTwoNormalizedTracePairTensorSpace :=
  TensorProduct.instInnerProductSpace

noncomputable local instance cyclicFourEdgeSourcePowerFourNormedAddCommGroup :
    NormedAddCommGroup SpecialUnitaryTwoNormalizedTraceFourEdgeHilbertTensorSpace :=
  TensorProduct.instNormedAddCommGroup

noncomputable local instance cyclicFourEdgeSourcePowerFourInnerProductSpace :
    InnerProductSpace ℝ SpecialUnitaryTwoNormalizedTraceFourEdgeHilbertTensorSpace :=
  TensorProduct.instInnerProductSpace

local instance cyclicFourEdgeSourcePowerFourCompleteSpace :
    CompleteSpace SpecialUnitaryTwoNormalizedTraceFourEdgeHilbertTensorSpace := by
  exact FiniteDimensional.complete ℝ _

/-- The edgewise four-leg kernel in the exact cyclic pair order `(2,3)|(0,1)`.
It is deliberately the product of four independent normalized relative-trace
kernels, not the single relative kernel of the cyclic composite holonomy. -/
def specialUnitaryTwoCyclicFourEdgeNormalizedTraceEdgeProductKernel
    (x y : Fin 4 → Matrix.specialUnitaryGroup (Fin 2) ℂ) : ℝ :=
  (specialUnitaryNormalizedTraceRelativeKernel 2 (x 2) (y 2) *
      specialUnitaryNormalizedTraceRelativeKernel 2 (x 3) (y 3)) *
    (specialUnitaryNormalizedTraceRelativeKernel 2 (x 0) (y 0) *
      specialUnitaryNormalizedTraceRelativeKernel 2 (x 1) (y 1))

/-- The pure four-edge normalized feature tensor realizes exactly the product
of the four edgewise normalized relative-trace kernels. -/
theorem specialUnitaryTwoCyclicFourEdgeNormalizedTraceEdgeProductKernel_eq_inner
    (x y : Fin 4 → Matrix.specialUnitaryGroup (Fin 2) ℂ) :
    specialUnitaryTwoCyclicFourEdgeNormalizedTraceEdgeProductKernel x y =
      inner ℝ
        (specialUnitaryTwoCyclicFourEdgeNormalizedTraceFeatureTensor x)
        (specialUnitaryTwoCyclicFourEdgeNormalizedTraceFeatureTensor y) := by
  simp only [specialUnitaryTwoCyclicFourEdgeNormalizedTraceFeatureTensor,
    TensorProduct.inner_tmul,
    specialUnitaryTwoCyclicFourEdgeNormalizedTraceEdgeProductKernel]
  rw [
    (specialUnitaryNormalizedTraceRelativeKernelFeature
      2 cyclicFourEdgeSourcePowerTwoRankPositive).kernel_eq_inner (x 2) (y 2),
    (specialUnitaryNormalizedTraceRelativeKernelFeature
      2 cyclicFourEdgeSourcePowerTwoRankPositive).kernel_eq_inner (x 3) (y 3),
    (specialUnitaryNormalizedTraceRelativeKernelFeature
      2 cyclicFourEdgeSourcePowerTwoRankPositive).kernel_eq_inner (x 0) (y 0),
    (specialUnitaryNormalizedTraceRelativeKernelFeature
      2 cyclicFourEdgeSourcePowerTwoRankPositive).kernel_eq_inner (x 1) (y 1)]
  rw [
    ← specialUnitaryTwoNormalizedTraceFeatureVector_eq_kernelFeature (x 2),
    ← specialUnitaryTwoNormalizedTraceFeatureVector_eq_kernelFeature (y 2),
    ← specialUnitaryTwoNormalizedTraceFeatureVector_eq_kernelFeature (x 3),
    ← specialUnitaryTwoNormalizedTraceFeatureVector_eq_kernelFeature (y 3),
    ← specialUnitaryTwoNormalizedTraceFeatureVector_eq_kernelFeature (x 0),
    ← specialUnitaryTwoNormalizedTraceFeatureVector_eq_kernelFeature (y 0),
    ← specialUnitaryTwoNormalizedTraceFeatureVector_eq_kernelFeature (x 1),
    ← specialUnitaryTwoNormalizedTraceFeatureVector_eq_kernelFeature (y 1)]
  rfl

/-- Exact degree-one edgewise four-leg Hilbert feature. -/
noncomputable def specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFeature :
    RealHilbertKernelFeature
      (Fin 4 → Matrix.specialUnitaryGroup (Fin 2) ℂ)
      specialUnitaryTwoCyclicFourEdgeNormalizedTraceEdgeProductKernel where
  FeatureHilbert := SpecialUnitaryTwoNormalizedTraceFourEdgeHilbertTensorSpace
  feature := specialUnitaryTwoCyclicFourEdgeNormalizedTraceFeatureTensor
  kernel_eq_inner :=
    specialUnitaryTwoCyclicFourEdgeNormalizedTraceEdgeProductKernel_eq_inner

/-- Degree-`n` edgewise four-leg Fock feature generated by Mathlib's completed
Hilbert tensor-product power constructor. -/
noncomputable def specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFockFeature
    (n : ℕ) :
    RealHilbertKernelFeature
      (Fin 4 → Matrix.specialUnitaryGroup (Fin 2) ℂ)
      (fun x y =>
        specialUnitaryTwoCyclicFourEdgeNormalizedTraceEdgeProductKernel x y ^ n) :=
  (specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFeature).pow n

/-- The degree-`n` source Fock feature has exactly the `n`-th power of the
four-edge product kernel as its inner product. -/
theorem specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFockFeature_inner
    (n : ℕ)
    (x y : Fin 4 → Matrix.specialUnitaryGroup (Fin 2) ℂ) :
    inner ℝ
        ((specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFockFeature n).feature x)
        ((specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFockFeature n).feature y) =
      specialUnitaryTwoCyclicFourEdgeNormalizedTraceEdgeProductKernel x y ^ n := by
  exact
    ((specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFockFeature n).kernel_eq_inner
      x y).symm

/-- Expanded edgewise form of the degree-`n` source Fock inner product. -/
theorem specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFockFeature_inner_eq_edgeProduct_pow
    (n : ℕ)
    (x y : Fin 4 → Matrix.specialUnitaryGroup (Fin 2) ℂ) :
    inner ℝ
        ((specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFockFeature n).feature x)
        ((specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFockFeature n).feature y) =
      ((specialUnitaryNormalizedTraceRelativeKernel 2 (x 2) (y 2) *
          specialUnitaryNormalizedTraceRelativeKernel 2 (x 3) (y 3)) *
        (specialUnitaryNormalizedTraceRelativeKernel 2 (x 0) (y 0) *
          specialUnitaryNormalizedTraceRelativeKernel 2 (x 1) (y 1))) ^ n := by
  simpa [specialUnitaryTwoCyclicFourEdgeNormalizedTraceEdgeProductKernel] using
    specialUnitaryTwoCyclicFourEdgeNormalizedTraceSourceFockFeature_inner n x y

/-- Target degree-`n` normalized relative-trace Fock feature on a single `SU(2)`
holonomy.  This names the exact carrier containing the #1655 dual vector. -/
noncomputable def specialUnitaryTwoNormalizedTraceTargetFockFeature
    (n : ℕ) :
    RealHilbertKernelFeature
      (Matrix.specialUnitaryGroup (Fin 2) ℂ)
      (fun g h => specialUnitaryNormalizedTraceRelativeKernel 2 g h ^ n) :=
  (specialUnitaryNormalizedTraceRelativeKernelFeature
    2 cyclicFourEdgeSourcePowerTwoRankPositive).pow n

/-- The target degree-`n` feature evaluated on cyclic composite holonomies has
the expected powered composite relative kernel as its inner product. -/
theorem specialUnitaryTwoNormalizedTraceTargetFockFeature_cyclic_inner
    (n : ℕ)
    (x y : Fin 4 → Matrix.specialUnitaryGroup (Fin 2) ℂ) :
    inner ℝ
        ((specialUnitaryTwoNormalizedTraceTargetFockFeature n).feature
          (haarFinFourCyclicPlaquetteWord x))
        ((specialUnitaryTwoNormalizedTraceTargetFockFeature n).feature
          (haarFinFourCyclicPlaquetteWord y)) =
      specialUnitaryNormalizedTraceRelativeKernel 2
        (haarFinFourCyclicPlaquetteWord x)
        (haarFinFourCyclicPlaquetteWord y) ^ n := by
  exact
    ((specialUnitaryTwoNormalizedTraceTargetFockFeature n).kernel_eq_inner
      (haarFinFourCyclicPlaquetteWord x)
      (haarFinFourCyclicPlaquetteWord y)).symm

end

end MathlibAnalytic
end MGAP4D
