import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferVacuumResponseEnergyMatrix

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumSecondMeanRMSTargetMajorant
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumResponseEnergyMatrix
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumResponseEnergyMatrix_diag
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumResponseEnergyMatrix_eq_responseEnergy_of_ne
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumResponseEnergyMatrix_nonneg
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointVacuumResponseEnergyMatrix_le_canonicalPinFree_sq_ofReal_mul_targetMajorant_of_ne

end MGAP4D.MathlibAnalytic
