import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialSweepStageContextUniformFullEnvelopeRMSCauchy

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSection_fullEnvelopeCenteredRMS_of_bounded
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorCanonicalOneLinkSweepPrefix_exists_boundedRepresentative_sharpHaar_and_contextUniform_fullEnvelope_centeredRMS

end

end MGAP4D.MathlibAnalytic
