import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferBetaZeroGroundStateFullSweepDefectMargin

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatialFullSweepMean_le_fiveSix_norm_sq_add_sweepBlockDefect
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatialFullSweepMean_le_fiveSix_add_delta_of_sweepBlockDefect
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatial_sweepBlockDefectMargin_implies_transferGap
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabBetaZeroPhysicalSixSpatial_sweepBlockDefectMargin_positive_transferGap

end MGAP4D.MathlibAnalytic
