import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumReferenceFixedRightTargetRatioCrossRatioResidual
import MGAP4D.MathlibAnalytic.FinitePositiveWeightCrossRatioInfluenceTransformSum
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory BigOperators

noncomputable section

local instance targetIndexedCrossRatioInfluenceColumnSpatialLinkFintype
    (H : ℕ) : Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

/-- The absolute fixed-right response residual is nonnegative. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs_nonneg
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source : PeriodicHypercubicEvenSpatialSliceLink H)
    (g₁ g₂ h k : Matrix.specialUnitaryGroup (Fin N) ℂ) :
    0 ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs
        H N hN beta hbeta B target source g₁ g₂ h k := by
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs
  exact abs_nonneg _

/-- The model-specific multiplicative remote cross-ratio estimate from the
fixed-right response may be expressed as a nonnegative logarithmic radius.
This is exactly the radius convention consumed by the canonical
cross-ratio-to-influence transform. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative_remote_crossRatio_le_exp_log_one_add_exp_sixteen_mul_fixedRightTargetRatioResponseAbs
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    {target source : PeriodicHypercubicEvenSpatialSliceLink H}
    (hne : target ≠ source)
    (hNoShare :
      ¬ periodicHypercubicEvenSpatialSliceLinksSharePlaquette H target source)
    (h k g₁ g₂ : Matrix.specialUnitaryGroup (Fin N) ℂ) :
    (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative
          H N hN beta hbeta
          (Function.update (Function.update B source h) target g₁) *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative
          H N hN beta hbeta
          (Function.update (Function.update B source k) target g₂)) /
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative
          H N hN beta hbeta
          (Function.update (Function.update B source k) target g₁) *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative
          H N hN beta hbeta
          (Function.update (Function.update B source h) target g₂)) ≤
      Real.exp
        (Real.log
          (1 + Real.exp (16 * beta) *
            periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs
              H N hN beta hbeta B target source g₁ g₂ h k)) := by
  let R : ℝ :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs
      H N hN beta hbeta B target source g₁ g₂ h k
  have hR : 0 ≤ R := by
    exact
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs_nonneg
        H N hN beta hbeta B target source g₁ g₂ h k
  have hPos : 0 < 1 + Real.exp (16 * beta) * R := by
    positivity
  calc
    (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative
          H N hN beta hbeta
          (Function.update (Function.update B source h) target g₁) *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative
          H N hN beta hbeta
          (Function.update (Function.update B source k) target g₂)) /
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative
          H N hN beta hbeta
          (Function.update (Function.update B source k) target g₁) *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative
          H N hN beta hbeta
          (Function.update (Function.update B source h) target g₂)) ≤
      1 + Real.exp (16 * beta) * R := by
        simpa [R] using
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumRepresentative_remote_crossRatio_le_one_add_exp_sixteen_mul_fixedRightTargetRatioResponseAbs
            H N hN beta hbeta B hne hNoShare h k g₁ g₂
    _ = Real.exp (Real.log (1 + Real.exp (16 * beta) * R)) := by
      rw [Real.exp_log hPos]

/-- The logarithmic radius generated by the fixed-right response majorant is
nonnegative. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioCrossRatioRadius_nonneg
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source : PeriodicHypercubicEvenSpatialSliceLink H)
    (g₁ g₂ h k : Matrix.specialUnitaryGroup (Fin N) ℂ) :
    0 ≤
      Real.log
        (1 + Real.exp (16 * beta) *
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs
            H N hN beta hbeta B target source g₁ g₂ h k) := by
  apply Real.log_nonneg
  have hR :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs_nonneg
      H N hN beta hbeta B target source g₁ g₂ h k
  nlinarith [mul_nonneg (Real.exp_pos (16 * beta)).le hR]

/-- For independently chosen targetwise SU(N) values, sum the canonical
full-L1 transform of the actual logarithmic cross-ratio majorant over the same
remote C5 target family as the fixed-right response column. This remains a
chosen-family quantity; no supremum over SU(N) values is taken here. -/
noncomputable def
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceTargetIndexedRemoteCrossRatioInfluenceColumn
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (source distinguishedTarget : PeriodicHypercubicEvenSpatialSliceLink H)
    (g₁ g₂ h k :
      PeriodicHypercubicEvenSpatialSliceLink H →
        Matrix.specialUnitaryGroup (Fin N) ℂ) : ℝ :=
  ∑ target ∈
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceC5RemoteTargetFibers
        H source distinguishedTarget,
    finitePositiveWeightCrossRatioInfluenceTransform
      (Real.log
        (1 + Real.exp (16 * beta) *
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs
            H N hN beta hbeta B target source
            (g₁ target) (g₂ target) (h target) (k target)))

/-- The target-indexed transformed remote cross-ratio column is bounded by the
same fixed-right response column with the single volume-independent multiplier
exp(16 beta). The finite-family logarithmic linearization introduces no
remote-target cardinality factor. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceTargetIndexedRemoteCrossRatioInfluenceColumn_le_exp_sixteen_mul_responseColumn
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (source distinguishedTarget : PeriodicHypercubicEvenSpatialSliceLink H)
    (g₁ g₂ h k :
      PeriodicHypercubicEvenSpatialSliceLink H →
        Matrix.specialUnitaryGroup (Fin N) ℂ) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceTargetIndexedRemoteCrossRatioInfluenceColumn
        H N hN beta hbeta B source distinguishedTarget g₁ g₂ h k ≤
      Real.exp (16 * beta) *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioTargetIndexedRemoteResponseColumn
          H N hN beta hbeta B source distinguishedTarget g₁ g₂ h k := by
  classical
  let remote :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceC5RemoteTargetFibers
      H source distinguishedTarget
  let error : PeriodicHypercubicEvenSpatialSliceLink H → ℝ :=
    fun target =>
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs
        H N hN beta hbeta B target source
        (g₁ target) (g₂ target) (h target) (k target)
  have hError : ∀ target ∈ remote, 0 ≤ error target := by
    intro target _hTarget
    exact
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioResponseAbs_nonneg
        H N hN beta hbeta B target source
        (g₁ target) (g₂ target) (h target) (k target)
  have hLinear :=
    finitePositiveWeightCrossRatioInfluenceTransform_sum_log_one_add_const_mul_le
      remote (Real.exp (16 * beta)) error (Real.exp_pos _).le hError
  simpa [
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceTargetIndexedRemoteCrossRatioInfluenceColumn,
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioTargetIndexedRemoteResponseColumn,
    remote,
    error] using hLinear

/-- Combining the model-specific cross-ratio normalization with the arbitrary
finite-step target-indexed response theorem sends the entire chosen-family
remote cross-ratio influence column to the existing aggregate tagged
transport. This is uniform in independently chosen targetwise SU(N) values,
but still does not assert that a targetwise supremum has been constructed or
attained. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceTargetIndexedRemoteCrossRatioInfluenceColumn_le_exp_sixteen_mul_nStepAggregateRight_add_two_mul_leftVariationTotal
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (source distinguishedTarget : PeriodicHypercubicEvenSpatialSliceLink H)
    (g₁ g₂ h k :
      PeriodicHypercubicEvenSpatialSliceLink H →
        Matrix.specialUnitaryGroup (Fin N) ℂ)
    (n : ℕ) :
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceTargetIndexedRemoteCrossRatioInfluenceColumn
        H N hN beta hbeta B source distinguishedTarget g₁ g₂ h k ≤
      Real.exp (16 * beta) *
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberTaggedRestrictedRandomScanVariationIterate
            H beta hbeta
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioRemoteAggregateVariation
              H beta source distinguishedTarget)
            n (Sum.inr source) +
          2 *
            ∑ e : PeriodicHypercubicEvenSpatialSliceLink H,
              periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberTaggedRestrictedRandomScanVariationIterate
                H beta hbeta
                (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioRemoteAggregateVariation
                  H beta source distinguishedTarget)
                n (Sum.inl e)) := by
  calc
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceTargetIndexedRemoteCrossRatioInfluenceColumn
        H N hN beta hbeta B source distinguishedTarget g₁ g₂ h k ≤
      Real.exp (16 * beta) *
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioTargetIndexedRemoteResponseColumn
          H N hN beta hbeta B source distinguishedTarget g₁ g₂ h k :=
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceTargetIndexedRemoteCrossRatioInfluenceColumn_le_exp_sixteen_mul_responseColumn
        H N hN beta hbeta B source distinguishedTarget g₁ g₂ h k
    _ ≤
      Real.exp (16 * beta) *
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberTaggedRestrictedRandomScanVariationIterate
            H beta hbeta
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioRemoteAggregateVariation
              H beta source distinguishedTarget)
            n (Sum.inr source) +
          2 *
            ∑ e : PeriodicHypercubicEvenSpatialSliceLink H,
              periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceDistinctFiberTaggedRestrictedRandomScanVariationIterate
                H beta hbeta
                (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioRemoteAggregateVariation
                  H beta source distinguishedTarget)
                n (Sum.inl e)) := by
      exact mul_le_mul_of_nonneg_left
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceFixedRightTargetRatioTargetIndexedRemoteResponseColumn_le_nStepAggregateRight_add_two_mul_leftVariationTotal
          H N hN beta hbeta B source distinguishedTarget g₁ g₂ h k n)
        (Real.exp_pos _).le

end

end MathlibAnalytic
end MGAP4D
