import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferContinuousVacuumPosteriorStrictInfiniteResolvent
import Mathlib.Topology.Order.OrderClosed
import Mathlib.Tactic

/-!
# Strict posterior persistent response bootstrap

PRs #5182--#5183 replace the coarse finite Harnack resolvent by the strict
fixed-volume Dobrushin geometric bound

  w_M(s) <= V / (1 - alpha_H(beta)),

uniformly in the random-scan depth M, and close the corresponding infinite
resolvent.  This file feeds that strict bound back into the finite covariance
bootstrap of #5169 and then removes the terminal covariance using the
fixed-volume decay theorem of #5175.

For the exact target-local variation width, define

  epsilon_strict(H,beta)
    = ((width/2) * (width / (1-alpha_H(beta)))) / exp(-8 beta).

Inside the fixed-volume cutoff, the actual posterior target/source expectation
response is bounded by this radius.  Thus the previous coarse M * 2^M * width
term is replaced by the strict geometric denominator (1-alpha_H)^(-1) and
the terminal remainder disappears after passage to the block-depth limit.

All statements remain fixed-volume and the cutoff still depends on H.
No volume-uniform strictness, Euclidean-time identification, continuum
generator bridge, H1-D5 exact descent, or complete Yang--Mills mass-gap claim
is asserted.
-/

namespace MGAP4D
namespace MathlibAnalytic

open Filter

noncomputable section

local instance posteriorStrictPersistentResponseSpatialLinkFintype
    (H : ℕ) :
    Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

/-- The terminal-free response radius generated by the fixed-volume strict
Dobrushin resolvent. -/
noncomputable def
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentResponseRadius
    (H : ℕ)
    (beta : ℝ) : ℝ :=
  let width :=
    periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariationWidth
      beta
  let alpha :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapZeroDepthRefinedTotalCoefficient
      H beta
  ((width / 2) * (width / (1 - alpha))) /
    Real.exp (-8 * beta)

/-- A finite-block upper approximant retaining only the explicit terminal
covariance envelope. -/
noncomputable def
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictResponseApproximant
    (H N : ℕ)
    (beta : ℝ)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (source : PeriodicHypercubicEvenSpatialSliceLink H)
    (sourceValue : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (k : ℕ) : ℝ :=
  let width :=
    periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariationWidth
      beta
  let alpha :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapZeroDepthRefinedTotalCoefficient
      H beta
  (((width / 2) * (width / (1 - alpha))) +
      periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorBlockTerminalCovarianceEnvelope
        H N beta B source sourceValue k) /
    Real.exp (-8 * beta)

/-- The strict persistent response radius is nonnegative inside the
fixed-volume cutoff. -/
theorem
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentResponseRadius_nonneg
    (H : ℕ)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (hbetaPos : 0 < beta)
    (hbetaCutoff :
      beta <
        periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapFixedVolumeDobrushinCutoff
          H) :
    0 ≤
      periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentResponseRadius
        H beta := by
  let width :=
    periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariationWidth
      beta
  let alpha :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapZeroDepthRefinedTotalCoefficient
      H beta
  have hWidth : 0 ≤ width := by
    dsimp [width]
    exact
      periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariationWidth_nonneg
        beta hbeta
  have hAlphaLt : alpha < 1 := by
    dsimp [alpha]
    exact
      periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapFixedVolumeDobrushinCutoff_totalCoefficient_lt_one
        H beta hbetaPos hbetaCutoff
  have hOneSubAlpha : 0 ≤ 1 - alpha :=
    (sub_pos.mpr hAlphaLt).le
  unfold
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentResponseRadius
  dsimp [width, alpha]
  exact
    div_nonneg
      (mul_nonneg
        (div_nonneg hWidth (by norm_num))
        (div_nonneg hWidth hOneSubAlpha))
      (Real.exp_pos _).le

/-- The strict finite resolvent replaces the coarse finite-growth term in
the finite response radius. -/
theorem
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFiniteBootstrapResponseRadius_firstBootstrapStrict_le_approximant
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (hbetaPos : 0 < beta)
    (hbetaCutoff :
      beta <
        periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapFixedVolumeDobrushinCutoff
          H)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source : PeriodicHypercubicEvenSpatialSliceLink H)
    (sourceValue : Matrix.specialUnitaryGroup (Fin N) ℂ)
    (k : ℕ) :
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFiniteBootstrapResponseRadius
        (periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapFixedVolumeDobrushinData
          H N hN beta hbeta hbetaPos hbetaCutoff B).toPeriodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorNonstrictInfluenceData
        target source
        (k *
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceAllSpatialLinkSchedule
            H).length)
        (periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorBlockTerminalCovarianceEnvelope
          H N beta B source sourceValue k) ≤
      periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictResponseApproximant
        H N beta B source sourceValue k := by
  let M :=
    k *
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceAllSpatialLinkSchedule
        H).length
  let width :=
    periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariationWidth
      beta
  let alpha :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapZeroDepthRefinedTotalCoefficient
      H beta
  let terminal :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorBlockTerminalCovarianceEnvelope
      H N beta B source sourceValue k
  let D :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapFixedVolumeDobrushinData
      H N hN beta hbeta hbetaPos hbetaCutoff B
  have hWidth : 0 ≤ width := by
    dsimp [width]
    exact
      periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariationWidth_nonneg
        beta hbeta
  have hVariationNonneg :
      ∀ e : PeriodicHypercubicEvenSpatialSliceLink H,
        0 ≤
          periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariation
            beta target e :=
    periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariation_nonneg
      beta hbeta target
  have hVariationLe :
      ∀ e : PeriodicHypercubicEvenSpatialSliceLink H,
        periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariation
            beta target e ≤ width := by
    intro e
    classical
    unfold
      periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariation
    by_cases he : e = target
    · subst e
      simp [
        periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariation,
        width]
    · simp [
        periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariation,
        he, width, hWidth]
  have hResolvent :
      periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorRandomScanFiniteResolventProfile
          D.toPeriodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorNonstrictInfluenceData
          (periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariation
            beta target)
          M source ≤
        width / (1 - alpha) := by
    simpa [D, M, width, alpha] using
      periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapFixedVolumeRandomScanFiniteResolventProfile_le_one_sub_totalCoefficient
        H N hN beta hbeta hbetaPos hbetaCutoff B
        (periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariation
          beta target)
        hVariationNonneg
        width
        hWidth
        hVariationLe
        (k *
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceAllSpatialLinkSchedule
            H).length)
        source
  unfold
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFiniteBootstrapResponseRadius
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFiniteBootstrapCovarianceRadius
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictResponseApproximant
  dsimp [D, M, width, alpha, terminal]
  rw [div_le_div_iff_of_pos_right (Real.exp_pos (-8 * beta))]
  exact
    add_le_add
      (mul_le_mul_of_nonneg_left hResolvent
        (div_nonneg hWidth (by norm_num)))
      le_rfl

/-- The finite-block strict response approximants converge to the terminal-free
persistent radius because the generated covariance remainder tends to zero. -/
theorem
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictResponseApproximant_tendsto_persistent
    (H N : ℕ)
    (beta : ℝ)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (source : PeriodicHypercubicEvenSpatialSliceLink H)
    (sourceValue : Matrix.specialUnitaryGroup (Fin N) ℂ) :
    Tendsto
      (fun k =>
        periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictResponseApproximant
          H N beta B source sourceValue k)
      atTop
      (𝓝
        (periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentResponseRadius
          H beta)) := by
  let width :=
    periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorVariationWidth
      beta
  let alpha :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapZeroDepthRefinedTotalCoefficient
      H beta
  let main : ℝ :=
    (width / 2) * (width / (1 - alpha))
  have hTerminal :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorBlockTerminalCovarianceEnvelope_tendsto_zero
      H N beta B source sourceValue
  have hAdd :
      Tendsto
        (fun k =>
          main +
            periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorBlockTerminalCovarianceEnvelope
              H N beta B source sourceValue k)
        atTop
        (𝓝 (main + 0)) :=
    tendsto_const_nhds.add hTerminal
  have hMul :=
    hAdd.mul_const (Real.exp (-8 * beta))⁻¹
  simpa [
    div_eq_mul_inv,
    main,
    width,
    alpha,
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictResponseApproximant,
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentResponseRadius
  ] using hMul

/-- The actual fixed-volume posterior target/source expectation response is
bounded by the terminal-free strict geometric radius. -/
theorem
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorTargetExpectationResponseBound_of_firstBootstrapStrictPersistentRadius
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (hbetaPos : 0 < beta)
    (hbetaCutoff :
      beta <
        periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapFixedVolumeDobrushinCutoff
          H)
    (B : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N)
    (target source : PeriodicHypercubicEvenSpatialSliceLink H)
    (sourceValue : Matrix.specialUnitaryGroup (Fin N) ℂ) :
    PeriodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorTargetExpectationResponseBound
      H N hN beta hbeta B target source sourceValue
      (periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentResponseRadius
        H beta) := by
  intro g
  apply ge_of_tendsto'
    (periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictResponseApproximant_tendsto_persistent
      H N beta B source sourceValue)
  intro k
  have hExact :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorTargetExpectationResponseBound_of_blockDoeblinTerminalDecay
      (periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapFixedVolumeDobrushinData
        H N hN beta hbeta hbetaPos hbetaCutoff B).toPeriodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorNonstrictInfluenceData
      target source sourceValue k
  have hRadius :=
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFiniteBootstrapResponseRadius_firstBootstrapStrict_le_approximant
      H N hN beta hbeta hbetaPos hbetaCutoff B target source sourceValue k
  exact (hExact g).trans hRadius

/-- Boundary-independent remote-response matrix generated by the strict
persistent first-bootstrap radius. -/
noncomputable def
    periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentRemoteExpectationResponseMatrixData
    (H N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (hbetaPos : 0 < beta)
    (hbetaCutoff :
      beta <
        periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapFixedVolumeDobrushinCutoff
          H) :
    PeriodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorRemoteExpectationResponseMatrixData
      H N hN beta hbeta := by
  refine
    { epsilon := fun _target _source =>
        periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentResponseRadius
          H beta
      epsilon_nonneg := ?_
      remote_response := ?_ }
  · intro target source
    exact
      periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorFirstBootstrapStrictPersistentResponseRadius_nonneg
        H beta hbeta hbetaPos hbetaCutoff
  · intro A C target source hNe hRemote hAgree
    exact
      periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorTargetExpectationResponseBound_of_firstBootstrapStrictPersistentRadius
        H N hN beta hbeta hbetaPos hbetaCutoff A target source (C source)

end

end MathlibAnalytic
end MGAP4D
