import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferVacuumResponseTargetMajorant

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLawVacuumResponseL2Energy
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_vacuumResponseL2Energy_le_canonicalPinFree_sq_ofReal_mul_vacuumSecondMeanRMSAmplitudeEnergy
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLaw_vacuumResponseL2Energy_le_canonicalPinFree_sq_ofReal_mul_feedbackGap_inv_mul_harnackFactor_add_one_mul_condExpL2_residual_norm_sq

end MGAP4D.MathlibAnalytic
