import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSwapOneLinkConjugacy

namespace MGAP4D.MathlibAnalytic

open MeasureTheory

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryGroundStateJointSpatialLinkMeasurableSpace_comap_swap_eq_left
#check periodicHypercubicEvenSpecialUnitaryGroundStateJointLeftSpatialLinkMeasurableSpace_comap_swap_eq_right
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2LinearIsometry
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2LinearIsometry_involutive
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_apply_apply
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_mem_leftSpatialLink_lpMeas_of_mem_right
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_mem_rightSpatialLink_lpMeas_of_mem_left
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointRightSpatialLinkLpMeas_map_swap_eq_left
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_rightSpatialLink_starProjection
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_rightSpatialLinkCondExpL2
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftSpatialLinkCondExpL2_eq_swap_right_swap
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_rightResidual_norm_eq_left

#print axioms periodicHypercubicEvenSpecialUnitaryGroundStateJointSpatialLinkMeasurableSpace_comap_swap_eq_left
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2LinearIsometry_involutive
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_rightSpatialLinkCondExpL2
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftSpatialLinkCondExpL2_eq_swap_right_swap
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSwapL2Equiv_rightResidual_norm_eq_left

end

end MGAP4D.MathlibAnalytic
