import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialSweepStageSourceUpdateMeanDecomposition

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenSpatialSliceOffTargetSourceUpdate
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSectionSourceUpdatedCenteredMean
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointOneLinkConcreteSection_sourceUpdatedCenteredMean_difference_le_direct_add_envelope_mul_targetProfile

end

end MGAP4D.MathlibAnalytic
