import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferTwoSidedConstantLineConvergence

namespace MGAP4D.MathlibAnalytic

open MeasureTheory Set Filter
open scoped Topology InnerProductSpace InnerProduct

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateLeftSpatialLinkCondExpL2_fixed_iff_mem_lpMeas
#check periodicHypercubicEvenSpecialUnitarySpatialSlicePairHaar_aestronglyMeasurable_snd_of_swap_fst
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_all_fixed_mem_constantLine
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_all_fixed_iff_mem_constantLine
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLinkFullSweep_fixed_iff_mem_constantLine
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointConstantProjection
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointConstantProjection_absorb_twoSidedSpatialLink
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointConstantProjection_absorb_twoSidedFullSweep
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_iterates_tendsto_constantProjection

#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_all_fixed_iff_mem_constantLine
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_iterates_tendsto_constantProjection

end

end MGAP4D.MathlibAnalytic
