import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSourcePairSecondMeanRMSHarnackResponseBound

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourcePairCanonicalTargetLawSecondMeanRMSAmplitudeL2_norm_sq_ofReal_le_harnackLawFactor_add_one_mul_referenceUpdatedVariance_add_responseL2_norm_sq

end MGAP4D.MathlibAnalytic
