import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferPosteriorSourceTiltCovarianceFactorization

/-! Compile contracts for exact posterior source-tilt covariance factorization. -/

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetBoundaryTilt
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetBoundaryTilt_pos
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactor_eq_boundaryTilt_mul_sourceRightLinkTilt
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabSourceRightLinkTiltBCF
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabSourceRightLinkTiltBCF_apply
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactorBCF_eq_boundaryTilt_smul_sourceRightLinkTiltBCF
#check periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorCovariance_localFactor_eq_boundaryTilt_mul_sourceRightLinkTilt

#print axioms periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetLocalFactor_eq_boundaryTilt_mul_sourceRightLinkTilt
#print axioms periodicHypercubicEvenSpecialUnitaryContinuousVacuumPosteriorCovariance_localFactor_eq_boundaryTilt_mul_sourceRightLinkTilt

end

end MGAP4D.MathlibAnalytic
