import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferBetaZeroGroundStateSixSpatialProductHaarOrthogonalCoercivity

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check realHilbertProjectionSweep_absorb_of_mem
#check realHilbertProjectionSweep_apply_fixed_of_mem

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaarFullSweep_apply_mem_fst

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaar_residualSum_ge_norm_sq

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaar_normalizedResidualEnergy_ge_one_sixth

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaarRandomScan

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialPairHaarRandomScan_rayleigh_le_five_sixths

end

end MGAP4D.MathlibAnalytic
