import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferTwoSidedLossContraction

namespace MGAP4D.MathlibAnalytic

open MeasureTheory
open scoped BigOperators

noncomputable section

#check GroundStateSourceFixedPairEnergy.twoBoundaryOrderedLossContractionCutoff
#check GroundStateSourceFixedPairEnergy.twoBoundaryOrderedLossContractionCutoff_pos
#check GroundStateSourceFixedPairEnergy.twoBoundaryOrderedSchurCoefficient_nonneg_lt_half
#check GroundStateSourceFixedPairEnergy.twoBoundaryOrderedLossRatio
#check GroundStateSourceFixedPairEnergy.twoBoundaryOrderedLossRatio_nonneg_lt_one
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLinkTerminalSweepStageLocalProfile_sq_sum_eq_terminalPathLoss
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_pathLoss_le_lossRatio_mul
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_pathLoss_le_lossRatio_mul_allL2
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_iteratedPathLoss_le_geometric

#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_pathLoss_le_lossRatio_mul_allL2
#print axioms periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateTwoSidedSpatialLink_iteratedPathLoss_le_geometric

end

end MGAP4D.MathlibAnalytic
