import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialDiagonalSectionConditionalVarianceEnergy

namespace MGAP4D.MathlibAnalytic

#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateDiagonalOuter_conditionalSquareEnergy_eq_localMeanKernelSectionL2_norm_sq

end MGAP4D.MathlibAnalytic
