import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSixSpatialSweepStageNormedResponseAssembler

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check FiniteNormedResponseOneSidedProfile.norm_profile_le_local_add_matrix
#check FiniteNormedResponseOneSidedProfile.norm_profile_oneSided
#check periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialSweepStage_normedResponse_global_energy_coercive_uniform

end

end MGAP4D.MathlibAnalytic
