import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointFullDirectErrorPathLoss

namespace MGAP4D.MathlibAnalytic

#check exists_periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweep_linkIndexedRepresentatives_fullMinusDirectDifference_vacuum_lintegral_le_responseResidualCoefficient_mul_sixSweepPathLoss_ofReal
#check exists_periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateSixSpatialOneLinkSweep_linkIndexedRepresentatives_fullMinusDirectDifference_vacuum_lintegral_le_sixSweepPathLoss_ofReal

end MGAP4D.MathlibAnalytic
