import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSweepBlockDefectCyclicSourceStepResidual
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSweepBlockDefectCyclicSourceUpdateQuantitative
import Mathlib.Tactic

/-!
# Quantitative cyclic source step on the exact stage-residual carrier

PRs #4906--#4907 identify one actual cyclic between-visits source update with
an exact bounded-concrete Hilbert transition

  x_after = Q_source x_before

and identify its genuine source CondExpL2 residual exactly with the trajectory
stage residual

  x_before - x_after.

PR #4904 already bounds both quantitative pieces generated by that same source
update:

* the centered backward direct variance;
* the transposed backward law-response.

This file composes those statements without weakening coefficients.  Both
quantitative costs are charged directly to the exact stage-residual energy of
the actual cyclic trajectory.  Thus later telescoping no longer needs to
evaluate an arbitrary L2 quotient representative pointwise.

No finite-cardinality Cauchy estimate, factor two, response symmetry,
source/target reversal, or positive-beta commutativity is introduced.
-/

namespace MGAP4D.MathlibAnalytic

open MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory BigOperators

noncomputable section

local instance cyclicSourceStepQuantitativeSpecialUnitaryIsTopologicalGroup
    (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance cyclicSourceStepQuantitativeSpecialUnitaryCompactSpace
    (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance cyclicSourceStepQuantitativeSpecialUnitarySecondCountableTopology
    (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance cyclicSourceStepQuantitativeSpecialUnitaryMeasurableSpace
    (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance cyclicSourceStepQuantitativeSpecialUnitaryBorelSpace
    (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

local instance cyclicSourceStepQuantitativeSpatialLinkFintype
    (H : ℕ) :
    Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

/-- Squared norm of the exact source-stage residual occurring along the cyclic
between-visits trajectory after the first target projection. -/
noncomputable def
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStepResidualEnergy
    (H N : ℕ) (hN : 0 < N)
    (beta : ℝ) (hbeta : 0 ≤ beta)
    (color : PeriodicHypercubicEvenGroundStateSpatialColor)
    (pre before :
      List (PeriodicHypercubicEvenFixedSpatialColorLink H color))
    (target source :
      PeriodicHypercubicEvenFixedSpatialColorLink H color)
    (f :
      PeriodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointL2
        H N hN beta hbeta) : ℝ :=
  ‖realHilbertProjectionSweep
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
        H N hN beta hbeta color)
      before
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
        H N hN beta hbeta color target
        (realHilbertProjectionSweep
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
            H N hN beta hbeta color)
          pre f)) -
    realHilbertProjectionSweep
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
        H N hN beta hbeta color)
      (before ++ [source])
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
        H N hN beta hbeta color target
        (realHilbertProjectionSweep
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
            H N hN beta hbeta color)
          pre f))‖ ^ 2

@[simp] theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStepResidualEnergy_nonneg
    (H N : ℕ) (hN : 0 < N)
    (beta : ℝ) (hbeta : 0 ≤ beta)
    (color : PeriodicHypercubicEvenGroundStateSpatialColor)
    (pre before :
      List (PeriodicHypercubicEvenFixedSpatialColorLink H color))
    (target source :
      PeriodicHypercubicEvenFixedSpatialColorLink H color)
    (f :
      PeriodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointL2
        H N hN beta hbeta) :
    0 ≤
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStepResidualEnergy
        H N hN beta hbeta color pre before target source f := by
  unfold
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStepResidualEnergy
  exact sq_nonneg _

/-- One actual cyclic source step admits a bounded representative whose two
already-proved quantitative source-update costs are both controlled directly
by the exact Hilbert stage-residual energy.

The direct term keeps the normalized Harnack factor.  The response term keeps
the already-certified transposed orientation

  K_pin(source,target)^2.

No coefficient is enlarged in this transport from the bounded-concrete
representative to the trajectory residual. -/
theorem
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStep_exists_boundedRepresentative_quantitative_stageResidual
    (H N : ℕ)
    (hN : 0 < N)
    (s : ℝ) (hs : 1 < s)
    (beta : ℝ) (hbeta : 0 ≤ beta)
    (hcut :
      beta ≤
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightHighTemperatureStrictPhysicalSweepCutoff
          s)
    (color : PeriodicHypercubicEvenGroundStateSpatialColor)
    (pre suffix before after :
      List (PeriodicHypercubicEvenFixedSpatialColorLink H color))
    (target source :
      PeriodicHypercubicEvenFixedSpatialColorLink H color)
    (hCanonicalSplit :
      (Finset.univ :
        Finset (PeriodicHypercubicEvenFixedSpatialColorLink H color)).toList =
          pre ++ target :: suffix)
    (hFresh : target ∉ pre)
    (hCyclicSplit :
      suffix ++ pre = before ++ source :: after)
    (distinguishedSource : PeriodicHypercubicEvenSpatialSliceLink H)
    (f :
      PeriodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointL2
        H N hN beta hbeta)
    (hf :
      f ∈
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointBoundedConcreteCore
          H N hN beta hbeta) :
    ∃
      (Fbefore :
        (PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N ×
          PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N) → ℝ)
      (hFbefore : StronglyMeasurable Fbefore)
      (boundBefore : ℝ)
      (hboundBefore : ∀ z, ‖Fbefore z‖ ≤ boundBefore),
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointBoundedConcreteL2
          H N hN beta hbeta Fbefore hFbefore boundBefore hboundBefore =
        realHilbertProjectionSweep
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
            H N hN beta hbeta color)
          before
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
            H N hN beta hbeta color target
            (realHilbertProjectionSweep
              (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkCondExpL2
                H N hN beta hbeta color)
              pre f)) ∧
      (∫⁻ C,
        ∫⁻ CD,
          ENNReal.ofReal
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardDirectVarianceEnergy
              H N hN beta hbeta source.1 Fbefore C C distinguishedSource
              (C distinguishedSource) (C source.1) CD)
          ∂periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathJointMeasure
            H N hN beta hbeta C source.1 distinguishedSource target.1
            (C distinguishedSource) (C source.1)
        ∂periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabVacuumMeasure
          H N hN beta hbeta) ≤
        ENNReal.ofReal ((Real.exp (32 * beta)) ^ 2) *
          ENNReal.ofReal
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStepResidualEnergy
              H N hN beta hbeta color pre before target source f) ∧
      (∫⁻ C,
        ∫⁻ CD,
          ENNReal.ofReal
            ((periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointSourceUpdateBackwardLawResponse
              H N hN beta hbeta source.1 Fbefore C C distinguishedSource
              (C distinguishedSource) (C source.1) CD) ^ 2)
          ∂periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceOneLinkHeatBathJointMeasure
            H N hN beta hbeta C target.1 distinguishedSource target.1
            (C distinguishedSource) (C target.1)
        ∂periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabVacuumMeasure
          H N hN beta hbeta) ≤
        ENNReal.ofReal
            (((periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferencePinFreeResponseControlledPhysicalLeftKernel
                H beta hbeta
                (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightTargetRatioResponseProfile
                  H N hN beta hbeta)
                (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightTargetRatioResponseProfile_nonneg
                  H N hN beta hbeta)).influence source.1 target.1) ^ 2) *
          ((1 -
              ENNReal.ofReal
                ((periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabContinuousVacuumReferenceCanonicalFixedRightHalfBarrierPinFreeCoefficient
                  s beta) ^ 2))⁻¹ *
            ((ENNReal.ofReal ((Real.exp (32 * beta)) ^ 2) + 1) *
              ENNReal.ofReal
                (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStepResidualEnergy
                  H N hN beta hbeta color pre before target source f))) ∧
      source.1 ≠ target.1 := by
  obtain
    ⟨Fbefore, hFbefore, boundBefore, hboundBefore,
      Fafter, hFafter, boundAfter, hboundAfter,
      hRepBefore, _hRepAfter, _hResidual, hResidualSq, hne⟩ :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStep_exists_boundedRepresentative_sourceResidual_eq_stageResidual
      H N hN beta hbeta color pre suffix before after target source
      hCanonicalSplit hFresh hCyclicSplit f hf
  have hsource : source ∈ suffix ++ pre := by
    rw [hCyclicSplit]
    simp
  have hDirect :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointCyclicSourceUpdateBackwardDirectVarianceEnergy_currentValue_vacuum_lintegral_le_harnackLawFactor_mul_condExpL2_sourceResidual
      H N hN beta hbeta color pre suffix target source
      hCanonicalSplit hFresh hsource distinguishedSource
      Fbefore hFbefore boundBefore hboundBefore
  have hResponse :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateJointCyclicSourceUpdateBackwardLawResponse_currentValue_vacuum_lintegral_le_transposedCanonicalPinFree_sq_mul_crossCondExpResidual
      N hN s hs beta hbeta hcut H color pre suffix target source
      hCanonicalSplit hFresh hsource distinguishedSource
      Fbefore hFbefore boundBefore hboundBefore
  rw [hResidualSq] at hDirect hResponse
  refine
    ⟨Fbefore, hFbefore, boundBefore, hboundBefore,
      hRepBefore, ?_, ?_, hne⟩
  · simpa [
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStepResidualEnergy] using
      hDirect
  · simpa [
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStepResidualEnergy] using
      hResponse

end

end MGAP4D.MathlibAnalytic
