import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryPhysicalTransferGroundStateJointSweepBlockDefectCyclicSourceStepResidual

namespace MGAP4D.MathlibAnalytic

#check
  periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabGroundStateFixedSpatialColorOneLinkSecondVisitCyclicSourceStep_exists_boundedRepresentative_sourceResidual_eq_stageResidual

end MGAP4D.MathlibAnalytic
