import MGAP4D.MathlibAnalytic.PhysicalYangMillsZ2PeriodicCanonicalLatticeEmbedding
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open Filter MeasureTheory

noncomputable section

/-- The real-valued side length of the canonical periodic sequence `k + 3`. -/
def z2PeriodicHypercubicCanonicalSideLengthReal
    (k : ℕ) : ℝ :=
  z2PeriodicHypercubicOrientedPlaquetteLimitVolume k

/-- A simultaneous continuum and thermodynamic scaling schedule.

At side length `n = k + 3`, the lattice spacing is `n⁻¹ᐟ²`.  Hence the physical
linear size is `n¹ᐟ²`, which diverges while the lattice spacing vanishes. -/
def z2PeriodicHypercubicCanonicalLatticeSpacing
    (k : ℕ) : ℝ :=
  (Real.sqrt (z2PeriodicHypercubicCanonicalSideLengthReal k))⁻¹

/-- Physical linear size generated by the canonical side length and spacing. -/
def z2PeriodicHypercubicCanonicalPhysicalLinearSize
    (k : ℕ) : ℝ :=
  z2PeriodicHypercubicCanonicalSideLengthReal k *
    z2PeriodicHypercubicCanonicalLatticeSpacing k

/-- Four-dimensional physical volume of the canonical schedule.

Since the physical linear size is `√n`, this volume is `n²`. -/
def z2PeriodicHypercubicCanonicalPhysicalVolume
    (k : ℕ) : ℝ :=
  z2PeriodicHypercubicCanonicalSideLengthReal k ^ 2

/-- Every real-valued side length in the canonical sequence is positive. -/
theorem z2PeriodicHypercubicCanonicalSideLengthReal_pos
    (k : ℕ) :
    0 < z2PeriodicHypercubicCanonicalSideLengthReal k := by
  unfold z2PeriodicHypercubicCanonicalSideLengthReal
  unfold z2PeriodicHypercubicOrientedPlaquetteLimitVolume
  positivity

/-- The canonical periodic side lengths diverge. -/
theorem z2PeriodicHypercubicCanonicalSideLength_tendsto_atTop :
    Tendsto z2PeriodicHypercubicOrientedPlaquetteLimitVolume
      atTop atTop := by
  refine tendsto_atTop.2 ?_
  intro b
  filter_upwards [eventually_ge_atTop b] with k hk
  unfold z2PeriodicHypercubicOrientedPlaquetteLimitVolume
  omega

/-- The real-valued canonical side lengths diverge. -/
theorem z2PeriodicHypercubicCanonicalSideLengthReal_tendsto_atTop :
    Tendsto z2PeriodicHypercubicCanonicalSideLengthReal
      atTop atTop := by
  have hCast :
      Tendsto (fun n : ℕ => (n : ℝ)) atTop atTop :=
    tendsto_natCast_atTop_atTop
  simpa [z2PeriodicHypercubicCanonicalSideLengthReal] using
    hCast.comp z2PeriodicHypercubicCanonicalSideLength_tendsto_atTop

/-- The square roots of the canonical side lengths diverge. -/
theorem z2PeriodicHypercubicCanonicalSqrtSideLength_tendsto_atTop :
    Tendsto
      (fun k : ℕ =>
        Real.sqrt (z2PeriodicHypercubicCanonicalSideLengthReal k))
      atTop atTop :=
  Real.tendsto_sqrt_atTop.comp
    z2PeriodicHypercubicCanonicalSideLengthReal_tendsto_atTop

/-- Every lattice spacing in the canonical schedule is strictly positive. -/
theorem z2PeriodicHypercubicCanonicalLatticeSpacing_pos
    (k : ℕ) :
    0 < z2PeriodicHypercubicCanonicalLatticeSpacing k := by
  unfold z2PeriodicHypercubicCanonicalLatticeSpacing
  exact inv_pos.mpr
    (Real.sqrt_pos.2
      (z2PeriodicHypercubicCanonicalSideLengthReal_pos k))

/-- The canonical lattice spacing converges to zero. -/
theorem z2PeriodicHypercubicCanonicalLatticeSpacing_tendsto_zero :
    Tendsto z2PeriodicHypercubicCanonicalLatticeSpacing
      atTop (nhds 0) := by
  simpa [z2PeriodicHypercubicCanonicalLatticeSpacing] using
    z2PeriodicHypercubicCanonicalSqrtSideLength_tendsto_atTop.inv_tendsto_atTop

/-- The physical linear size is exactly the square root of the lattice side
length. -/
theorem z2PeriodicHypercubicCanonicalPhysicalLinearSize_eq_sqrt
    (k : ℕ) :
    z2PeriodicHypercubicCanonicalPhysicalLinearSize k =
      Real.sqrt (z2PeriodicHypercubicCanonicalSideLengthReal k) := by
  have hSideNonneg :
      0 ≤ z2PeriodicHypercubicCanonicalSideLengthReal k :=
    (z2PeriodicHypercubicCanonicalSideLengthReal_pos k).le
  have hSqrtNe :
      Real.sqrt (z2PeriodicHypercubicCanonicalSideLengthReal k) ≠ 0 :=
    ne_of_gt
      (Real.sqrt_pos.2
        (z2PeriodicHypercubicCanonicalSideLengthReal_pos k))
  unfold z2PeriodicHypercubicCanonicalPhysicalLinearSize
  unfold z2PeriodicHypercubicCanonicalLatticeSpacing
  rw [← Real.mul_self_sqrt hSideNonneg]
  simp [mul_assoc, hSqrtNe]

/-- The canonical physical linear size diverges. -/
theorem z2PeriodicHypercubicCanonicalPhysicalLinearSize_tendsto_atTop :
    Tendsto z2PeriodicHypercubicCanonicalPhysicalLinearSize
      atTop atTop := by
  simpa only [z2PeriodicHypercubicCanonicalPhysicalLinearSize_eq_sqrt] using
    z2PeriodicHypercubicCanonicalSqrtSideLength_tendsto_atTop

/-- The declared four-volume is exactly the fourth power of the physical linear
size. -/
theorem z2PeriodicHypercubicCanonicalPhysicalVolume_eq_linearSize_pow_four
    (k : ℕ) :
    z2PeriodicHypercubicCanonicalPhysicalVolume k =
      z2PeriodicHypercubicCanonicalPhysicalLinearSize k ^ 4 := by
  rw [z2PeriodicHypercubicCanonicalPhysicalLinearSize_eq_sqrt]
  unfold z2PeriodicHypercubicCanonicalPhysicalVolume
  have hSideNonneg :
      0 ≤ z2PeriodicHypercubicCanonicalSideLengthReal k :=
    (z2PeriodicHypercubicCanonicalSideLengthReal_pos k).le
  calc
    z2PeriodicHypercubicCanonicalSideLengthReal k ^ 2 =
        (Real.sqrt
          (z2PeriodicHypercubicCanonicalSideLengthReal k) ^ 2) ^ 2 := by
      rw [Real.sq_sqrt hSideNonneg]
    _ = Real.sqrt
          (z2PeriodicHypercubicCanonicalSideLengthReal k) ^ 4 := by
      ring

/-- The four-dimensional physical volume diverges along the canonical scaling
schedule. -/
theorem z2PeriodicHypercubicCanonicalPhysicalVolume_tendsto_atTop :
    Tendsto z2PeriodicHypercubicCanonicalPhysicalVolume
      atTop atTop := by
  refine tendsto_atTop.2 ?_
  intro b
  filter_upwards
    [z2PeriodicHypercubicCanonicalSideLengthReal_tendsto_atTop.eventually_ge_atTop
      (max b 1)] with k hk
  have hb :
      b ≤ z2PeriodicHypercubicCanonicalSideLengthReal k :=
    (le_max_left b 1).trans hk
  have hOne :
      1 ≤ z2PeriodicHypercubicCanonicalSideLengthReal k :=
    (le_max_right b 1).trans hk
  have hSquare :
      z2PeriodicHypercubicCanonicalSideLengthReal k ≤
        z2PeriodicHypercubicCanonicalSideLengthReal k ^ 2 := by
    nlinarith
  exact hb.trans hSquare

/-- Model-dependent interpolation into a common physical Polish space, with the
finite periodic `Z₂` systems and all scaling data omitted.

The omitted data are supplied canonically by `toCanonicalLatticeEmbedding`.
Only the genuinely model-dependent interpolation remains in this structure. -/
structure PhysicalYangMillsZ2PeriodicCanonicalInterpolation
    (beta : ℝ)
    (hBeta : 0 < beta) where
  PhysicalConfiguration : Type
  [physicalTopologicalSpace : TopologicalSpace PhysicalConfiguration]
  [physicalMeasurableSpace : MeasurableSpace PhysicalConfiguration]
  [physicalBorelSpace : BorelSpace PhysicalConfiguration]
  [physicalPolishSpace : PolishSpace PhysicalConfiguration]
  interpolate :
    ∀ k : ℕ,
      (z2PeriodicHypercubicOrientedWilsonSystem
        (z2PeriodicHypercubicOrientedPlaquetteLimitVolume k)
        beta hBeta.le).Configuration →
      PhysicalConfiguration
  interpolate_measurable : ∀ k : ℕ, Measurable (interpolate k)

attribute [instance]
  PhysicalYangMillsZ2PeriodicCanonicalInterpolation.physicalTopologicalSpace
  PhysicalYangMillsZ2PeriodicCanonicalInterpolation.physicalMeasurableSpace
  PhysicalYangMillsZ2PeriodicCanonicalInterpolation.physicalBorelSpace
  PhysicalYangMillsZ2PeriodicCanonicalInterpolation.physicalPolishSpace

/-- Supply the periodic finite systems, normalized Gibbs laws, and explicit
simultaneous continuum/thermodynamic scaling schedule to a model-dependent
interpolation family. -/
noncomputable def
    PhysicalYangMillsZ2PeriodicCanonicalInterpolation.toCanonicalLatticeEmbedding
    {beta : ℝ}
    {hBeta : 0 < beta}
    (I : PhysicalYangMillsZ2PeriodicCanonicalInterpolation beta hBeta) :
    PhysicalYangMillsZ2PeriodicCanonicalLatticeEmbedding beta hBeta :=
  { PhysicalConfiguration := I.PhysicalConfiguration
    interpolate := I.interpolate
    interpolate_measurable := I.interpolate_measurable
    latticeSpacing := z2PeriodicHypercubicCanonicalLatticeSpacing
    latticeSpacing_pos :=
      z2PeriodicHypercubicCanonicalLatticeSpacing_pos
    latticeSpacing_tendsto_zero :=
      z2PeriodicHypercubicCanonicalLatticeSpacing_tendsto_zero
    physicalVolume := z2PeriodicHypercubicCanonicalPhysicalVolume
    physicalVolume_tendsto_atTop :=
      z2PeriodicHypercubicCanonicalPhysicalVolume_tendsto_atTop }

/-- The lattice spacing stored by the canonical embedding is the explicit
inverse-square-root schedule. -/
theorem
    PhysicalYangMillsZ2PeriodicCanonicalInterpolation.latticeSpacing_eq
    {beta : ℝ}
    {hBeta : 0 < beta}
    (I : PhysicalYangMillsZ2PeriodicCanonicalInterpolation beta hBeta)
    (k : ℕ) :
    I.toCanonicalLatticeEmbedding.latticeSpacing k =
      z2PeriodicHypercubicCanonicalLatticeSpacing k :=
  rfl

/-- The physical volume stored by the canonical embedding is the explicit
four-volume of its physical linear size. -/
theorem
    PhysicalYangMillsZ2PeriodicCanonicalInterpolation.physicalVolume_eq
    {beta : ℝ}
    {hBeta : 0 < beta}
    (I : PhysicalYangMillsZ2PeriodicCanonicalInterpolation beta hBeta)
    (k : ℕ) :
    I.toCanonicalLatticeEmbedding.physicalVolume k =
      z2PeriodicHypercubicCanonicalPhysicalLinearSize k ^ 4 := by
  exact
    z2PeriodicHypercubicCanonicalPhysicalVolume_eq_linearSize_pow_four k

end

end MathlibAnalytic
end MGAP4D
