import MGAP4D.MathlibAnalytic.InfiniteDimensionalHilbertVacuumOrthogonalSequence
import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonCommonProductVacuumOrthogonalExcitationPhysicalCarrier

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- The remaining common-product kinematic carrier reduced to a single genuine
Hilbert-space statement: the normalized continuum physical OS Hilbert space is
not finite-dimensional.

All source-side cardinality information is already theorem-generated by the
actual interacting Wilson common-product `L²` separability in #1598.  Infinite
dimension of the target now theorem-generates the vacuum-orthogonal countable
orthonormal excitation sequence required there. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSCommonProductInfiniteDimensionalPhysicalCarrierData
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    (halfExtent : ℕ → ℕ)
    (N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ) (hbeta : ∀ n, 0 ≤ beta n)
    (P : D.OSPreHilbertData)
    (hP : P.IsNormalized) where
  physicalHilbert_not_finiteDimensional :
    ¬ FiniteDimensional ℝ P.PhysicalHilbert

namespace PhysicalYangMillsEvenPeriodicWilsonOSCommonProductInfiniteDimensionalPhysicalCarrierData

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {P : D.OSPreHilbertData}
    {hP : P.IsNormalized}

/-- Infinite dimension of the actual continuum physical OS Hilbert space
internally supplies the vacuum-orthogonal orthonormal excitation sequence of
#1598. -/
noncomputable def toVacuumOrthogonalExcitationCarrierData
    (J : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductInfiniteDimensionalPhysicalCarrierData
      halfExtent N hN beta hbeta P hP) :
    PhysicalYangMillsEvenPeriodicWilsonOSCommonProductVacuumOrthogonalExcitationCarrierData
      halfExtent N hN beta hbeta P hP := by
  let E := vacuumOrthogonalOrthonormalSequenceDataOfNotFiniteDimensional
    P.vacuum (P.norm_vacuum hP) J.physicalHilbert_not_finiteDimensional
  exact {
    excitation := E.excitation
    excitation_orthonormal := E.excitation_orthonormal
    vacuum_orthogonal_excitation := E.vacuum_orthogonal_excitation }

/-- Consequently the common-product-to-continuum physical carrier is generated
from target infinite dimension alone. -/
noncomputable def toCommonProductPhysicalCarrier
    (J : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductInfiniteDimensionalPhysicalCarrierData
      halfExtent N hN beta hbeta P hP) :
    PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalCarrier
      halfExtent N hN beta hbeta P :=
  J.toVacuumOrthogonalExcitationCarrierData.toCommonProductPhysicalCarrier

/-- The generated common-product embedding sends the canonical Wilson
common-product vacuum exactly to the normalized continuum physical vacuum. -/
@[simp] theorem toCommonProductPhysicalCarrier_commonEmbed_vacuum
    (J : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductInfiniteDimensionalPhysicalCarrierData
      halfExtent N hN beta hbeta P hP) :
    J.toCommonProductPhysicalCarrier.commonEmbed
        (physicalYangMillsEvenPeriodicWilsonBoundaryScaleMarginalCommonVacuum
          halfExtent N hN beta hbeta) =
      P.vacuum := by
  exact J.toCommonProductPhysicalCarrier.commonEmbed_vacuum

/-- Thus the complete family-valued mass-free finite-to-continuum ambient
carrier is theorem-generated from continuum physical Hilbert infinite
dimension together with the already canonical-sign Wilson pullback. -/
noncomputable def toMassFreeAmbientCarrier
    (J : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductInfiniteDimensionalPhysicalCarrierData
      halfExtent N hN beta hbeta P hP)
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)) :
    PhysicalYangMillsEvenPeriodicWilsonOSMassFreeAmbientCarrier
      (B := Q.vacuumNormalized.toWeakStarBridge)
      (hInvariant := hInvariant) P :=
  J.toVacuumOrthogonalExcitationCarrierData.toMassFreeAmbientCarrier Q hInvariant

end PhysicalYangMillsEvenPeriodicWilsonOSCommonProductInfiniteDimensionalPhysicalCarrierData

end

end MathlibAnalytic
end MGAP4D
