import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSApproximatingQuadraticGapCertificate
import MGAP4D.MathlibAnalytic.FiniteWilsonVacuumPoincareHamiltonianGap
import Mathlib.Tactic

noncomputable section

open Filter Set Topology
open scoped InnerProductSpace

namespace MGAP4D
namespace MathlibAnalytic

namespace PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

variable {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
variable {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
variable {P : D.OSPreHilbertData}

namespace PhysicalSemigroup

/-- A quadratic transfer estimate on vacuum-centered represented observables
extends to every vector orthogonal to the normalized vacuum.

The proof uses only the dense represented-state map and closedness of the
quadratic inequality.  Thus no spectral theorem or basis choice is needed. -/
theorem quadratic_decay_of_observable_core
    (T : P.PhysicalSemigroup)
    (hP : P.IsNormalized)
    (q : ℝ)
    (t : NNReal)
    (hCore : ∀ F : P.Carrier,
      inner ℝ
          (T.operator t
            (finiteVacuumCentered P.vacuum (P.physicalState F)))
          (finiteVacuumCentered P.vacuum (P.physicalState F)) ≤
        q * ‖finiteVacuumCentered P.vacuum (P.physicalState F)‖ ^ 2)
    (phi : P.PhysicalHilbert)
    (hphi : inner ℝ phi P.vacuum = 0) :
    inner ℝ (T.operator t phi) phi ≤ q * ‖phi‖ ^ 2 := by
  have hAll :
      ∀ x : P.PhysicalHilbert,
        inner ℝ
            (T.operator t (finiteVacuumCentered P.vacuum x))
            (finiteVacuumCentered P.vacuum x) ≤
          q * ‖finiteVacuumCentered P.vacuum x‖ ^ 2 := by
    intro x
    refine P.physicalStateLinearMap_denseRange.induction_on x ?_ ?_
    · apply isClosed_le
      · unfold finiteVacuumCentered
        fun_prop
      · unfold finiteVacuumCentered
        fun_prop
    · intro F
      simpa only [P.physicalStateLinearMap_apply] using hCore F
  have hvac : inner ℝ P.vacuum phi = 0 := by
    rw [real_inner_comm]
    exact hphi
  simpa [finiteVacuumCentered, hvac] using hAll phi

end PhysicalSemigroup
end PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

/-- A finite Wilson OS quadratic-gap certificate whose only analytic estimate
is imposed on the dense observable core.

At scale `n`, every carrier observable is represented in the actual Wilson OS
completion and then centered by its normalized finite-volume vacuum.  The
completed quadratic estimate is theorem-generated by density. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSApproximatingObservableQuadraticGapCertificate
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant) where
  mass : ℝ
  mass_pos : 0 < mass
  quadraticDecayFactor : NNReal → ℝ
  quadraticDecayFactor_nonneg :
    ∀ t, 0 ≤ quadraticDecayFactor t
  slope_tendsto :
    Tendsto
      (fun t : NNReal =>
        (t : ℝ)⁻¹ *
          (1 - Real.sqrt (quadraticDecayFactor (t + t))))
      (nhdsWithin 0 (Ioi 0))
      (nhds mass)
  exchange : ∀ n,
    PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
      (C.toPositiveTimeObservableContractionSemigroup n)
  finite_observable_quadratic_decay :
    ∀ (n : ℕ) (t : NNReal),
      let Pn :=
        physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
          S D halfExtent N hN beta hbeta B hInvariant n
      ∀ F : Pn.Carrier,
        inner ℝ
            (C.finiteOperator n t
              (finiteVacuumCentered Pn.vacuum (Pn.physicalState F)))
            (finiteVacuumCentered Pn.vacuum (Pn.physicalState F)) ≤
          quadraticDecayFactor t *
            ‖finiteVacuumCentered Pn.vacuum (Pn.physicalState F)‖ ^ 2

namespace PhysicalYangMillsEvenPeriodicWilsonOSApproximatingObservableQuadraticGapCertificate

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant}

/-- Extend the observable-core estimate to the entire finite Wilson OS Hilbert
space and obtain the quadratic-gap certificate. -/
noncomputable def toApproximatingQuadraticGapCertificate
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingObservableQuadraticGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C) :
    PhysicalYangMillsEvenPeriodicWilsonOSApproximatingQuadraticGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C where
  mass := Q.mass
  mass_pos := Q.mass_pos
  quadraticDecayFactor := Q.quadraticDecayFactor
  quadraticDecayFactor_nonneg := Q.quadraticDecayFactor_nonneg
  slope_tendsto := Q.slope_tendsto
  exchange := Q.exchange
  finite_quadratic_decay := by
    intro n t phi hphi
    let Pn :=
      physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta B hInvariant n
    have hPn : Pn.IsNormalized := by
      exact
        physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData_isNormalized
          S D halfExtent N hN beta hbeta B hInvariant n
    exact
      PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PhysicalSemigroup.quadratic_decay_of_observable_core
        (C.finitePhysicalSemigroup n)
        hPn
        (Q.quadraticDecayFactor t)
        t
        (Q.finite_observable_quadratic_decay n t)
        phi
        hphi

/-- The observable-core certificate therefore gives the norm-decay certificate
used by the common-carrier continuum mass-gap transfer. -/
noncomputable def toApproximatingVacuumGapCertificate
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingObservableQuadraticGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C) :
    PhysicalYangMillsEvenPeriodicWilsonOSApproximatingVacuumGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C :=
  Q.toApproximatingQuadraticGapCertificate.toApproximatingVacuumGapCertificate

end PhysicalYangMillsEvenPeriodicWilsonOSApproximatingObservableQuadraticGapCertificate

end MathlibAnalytic
end MGAP4D

end
