import MGAP4D.MathlibAnalytic.PeriodicHypercubicSpecialUnitaryDiscretePhysicalTemporalAction
import MGAP4D.MathlibAnalytic.PhysicalYangMillsOrientedDenseTemporalApproximation
import MGAP4D.MathlibAnalytic.PhysicalYangMillsOrientedFloorTemporalApproximation
import MGAP4D.MathlibAnalytic.PhysicalYangMillsContinuumEuclideanTimeTranslation
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSContinuumTimeTranslationBridge

namespace MGAP4D
namespace MathlibAnalytic

#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.PhysicalDiscreteTemporalAction
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation.WeakLimitContinuity
#check PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.GaugeDiscreteTemporalCompatibility
#check physicalTemporalFloorStep
#check physicalTemporalFloorStep_tendsto
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation.ofFloor
#check periodicHypercubicPhysicalLatticeTime
#check periodicHypercubicSpecialUnitaryDiscretePhysicalTemporalAction
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.PhysicalDiscreteTemporalAction.embeddedMeasure_map_latticeTime_eq_self
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation.WeakLimitContinuity.continuumMeasure_map_eq_self
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.GaugeDiscreteTemporalCompatibility.toContinuumEuclideanTimeTranslation
#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ConfigurationTimeTranslationCovariance.ofContinuumEuclideanTimeTranslation

end MathlibAnalytic
end MGAP4D
