import MGAP4D.MathlibAnalytic.ContinuousLinearMapIsometricSubmoduleRange
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSApproximatingGapTransfer
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSEmbeddedFiniteWilsonApproximateEigenpairStrongLimitFaithfulness
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

open Filter Set Topology
open scoped InnerProductSpace LinearPMap

namespace PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

variable {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
variable {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
variable {P : D.OSPreHilbertData}

namespace StronglyContinuousPhysicalSemigroup

/-- The canonical continuum vacuum-gap slope generated by an actual finite
Wilson common-carrier transfer bridge. -/
noncomputable def PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierGapTransfer.toVacuumSemigroupGapSlope
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {T : P.StronglyContinuousPhysicalSemigroup}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingVacuumGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C}
    (A : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierGapTransfer
      S D halfExtent N hN beta hbeta B hInvariant P T C Q) :
    T.VacuumSemigroupGapSlope :=
  A.toEmbeddedFiniteVolumeVacuumGapTransfer.toVacuumSemigroupGapSlope

/-- A finite-dimensional Wilson Hamiltonian excitation sector realized
isometrically inside each actual finite-volume Wilson OS Hilbert space.

The realized sector is orthogonal to the finite OS vacuum. The common-carrier
embedding preserves the vacuum, so its image automatically lies in the
continuum vacuum-orthogonal Hilbert space. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {T : P.StronglyContinuousPhysicalSemigroup}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingVacuumGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C}
    (A : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierGapTransfer
      S D halfExtent N hN beta hbeta B hInvariant P T C Q)
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (F : FiniteWilsonOSAutomaticExactGapFiniteDimensionalHamiltonianContractionData W) where
  finiteRealization :
    (n : ℕ) → F.StateSpace →L[ℝ]
      PhysicalYangMillsEvenPeriodicWilsonOSApproximatingHilbert
        S D halfExtent N hN beta hbeta B hInvariant n
  finiteRealization_norm :
    ∀ n phi, ‖finiteRealization n phi‖ = ‖phi‖
  finiteRealization_orthogonal :
    ∀ n phi,
      inner ℝ (finiteRealization n phi)
        (physical_yang_mills_evenPeriodicWilsonOS_approximating_vacuum
          S D halfExtent N hN beta hbeta B hInvariant n) = 0
  embed_vacuum :
    ∀ n,
      A.embed n
          (physical_yang_mills_evenPeriodicWilsonOS_approximating_vacuum
            S D halfExtent N hN beta hbeta B hInvariant n) =
        P.vacuum

namespace PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData

variable
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {T : P.StronglyContinuousPhysicalSemigroup}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingVacuumGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C}
    {A : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierGapTransfer
      S D halfExtent N hN beta hbeta B hInvariant P T C Q}
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {F : FiniteWilsonOSAutomaticExactGapFiniteDimensionalHamiltonianContractionData W}

/-- The ambient common-carrier embedding obtained by first realizing the finite
Hamiltonian excitation sector in the actual Wilson OS Hilbert space. -/
noncomputable def ambientEmbed
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData
      A F)
    (n : ℕ) : F.StateSpace →L[ℝ] P.PhysicalHilbert :=
  (A.embed n).comp (R.finiteRealization n)

/-- Vacuum preservation and finite-volume orthogonality put the complete
realized finite Hamiltonian sector in the continuum excitation subspace. -/
theorem ambientEmbed_mem_vacuumOrthogonal
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData
      A F)
    (n : ℕ) (phi : F.StateSpace) :
    R.ambientEmbed n phi ∈ P.vacuumOrthogonal := by
  rw [P.mem_vacuumOrthogonal_iff]
  calc
    inner ℝ P.vacuum (R.ambientEmbed n phi) =
        inner ℝ
          (A.embed n
            (physical_yang_mills_evenPeriodicWilsonOS_approximating_vacuum
              S D halfExtent N hN beta hbeta B hInvariant n))
          (A.embed n (R.finiteRealization n phi)) := by
      rw [R.embed_vacuum n]
      rfl
    _ = inner ℝ
        (physical_yang_mills_evenPeriodicWilsonOS_approximating_vacuum
          S D halfExtent N hN beta hbeta B hInvariant n)
        (R.finiteRealization n phi) := by
      exact ContinuousLinearMap.inner_map_map_of_norm_map
        (A.embed n) (A.embed_norm n)
        (physical_yang_mills_evenPeriodicWilsonOS_approximating_vacuum
          S D halfExtent N hN beta hbeta B hInvariant n)
        (R.finiteRealization n phi)
    _ = inner ℝ (R.finiteRealization n phi)
        (physical_yang_mills_evenPeriodicWilsonOS_approximating_vacuum
          S D halfExtent N hN beta hbeta B hInvariant n) :=
      real_inner_comm _ _
    _ = 0 := R.finiteRealization_orthogonal n phi

/-- The ambient map together with its excitation-range and norm-preservation
proofs. -/
noncomputable def excitationRangeData
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData
      A F)
    (n : ℕ) :
    ContinuousLinearMap.IsometricSubmoduleRangeData
      (R.ambientEmbed n) P.vacuumOrthogonal where
  map_mem := R.ambientEmbed_mem_vacuumOrthogonal n
  norm_map := by
    intro phi
    calc
      ‖R.ambientEmbed n phi‖ = ‖A.embed n (R.finiteRealization n phi)‖ := rfl
      _ = ‖R.finiteRealization n phi‖ := A.embed_norm n _
      _ = ‖phi‖ := R.finiteRealization_norm n phi

/-- The finite Hamiltonian excitation sector embedded directly in the complete
continuum vacuum-orthogonal carrier. -/
noncomputable def excitationEmbed
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData
      A F)
    (n : ℕ) : F.StateSpace →L[ℝ] P.VacuumOrthogonalHilbert :=
  (R.excitationRangeData n).toSubmodule

@[simp] theorem coe_excitationEmbed
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData
      A F)
    (n : ℕ) (phi : F.StateSpace) :
    ((R.excitationEmbed n phi : P.VacuumOrthogonalHilbert) : P.PhysicalHilbert) =
      A.embed n (R.finiteRealization n phi) :=
  rfl

/-- The concrete continuum excitation embedding is isometric. -/
theorem excitationEmbed_norm
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData
      A F)
    (n : ℕ) (phi : F.StateSpace) :
    ‖R.excitationEmbed n phi‖ = ‖phi‖ :=
  (R.excitationRangeData n).norm_toSubmodule phi

end PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData

/-- Strong-limit spectral transport whose continuum excitation embedding is
constructed from the actual Wilson OS common-carrier bridge rather than supplied
as an independent map. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonApproximateEigenpairStrongLimitData
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {T : P.StronglyContinuousPhysicalSemigroup}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingVacuumGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C}
    (A : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierGapTransfer
      S D halfExtent N hN beta hbeta B hInvariant P T C Q)
    (hSelf : IsSelfAdjoint T.closedRightHamiltonian)
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    (F : FiniteWilsonOSAutomaticExactGapFiniteDimensionalHamiltonianContractionData W)
    [DecidableEq A.toVacuumSemigroupGapSlope.BelowHalfMassShift]
    (nodes : Finset A.toVacuumSemigroupGapSlope.BelowHalfMassShift)
    (orderCap : ℕ) where
  realization :
    PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonExcitationRealizationData
      A F
  finiteWitness :
    (n : ℕ) →
      FiniteWilsonFiniteDimensionalHamiltonianConfluentSpectralWitnessData
        F n
          (fun sigma : A.toVacuumSemigroupGapSlope.BelowHalfMassShift => sigma.1)
          nodes orderCap
  SpectralIndex : Type
  [spectralFintype : Fintype SpectralIndex]
  finiteIndexEquiv :
    ∀ n, SpectralIndex ≃ (finiteWitness n).SpectralIndex
  approximateVector :
    ℕ → SpectralIndex →
      (T.vacuumOrthogonalClosedRightHamiltonianOfSelfAdjoint hSelf).domain
  approximateVector_coe :
    ∀ n k,
      (approximateVector n k : P.VacuumOrthogonalHilbert) =
        realization.excitationEmbed n
          ((finiteWitness n).spectralVector (finiteIndexEquiv n k))
  spectralValue : SpectralIndex → ℝ
  spectralValue_injective : Function.Injective spectralValue
  spectralVector : SpectralIndex → P.VacuumOrthogonalHilbert
  approximateValue_tendsto :
    ∀ k,
      Tendsto
        (fun n => (finiteWitness n).spectralValue (finiteIndexEquiv n k))
        atTop (nhds (spectralValue k))
  approximateVector_tendsto :
    ∀ k,
      Tendsto
        (fun n =>
          (approximateVector n k : P.VacuumOrthogonalHilbert))
        atTop (nhds (spectralVector k))
  operatorCompatibility_tendsto_zero :
    ∀ k,
      Tendsto
        (fun n =>
          T.vacuumOrthogonalClosedRightHamiltonianOfSelfAdjoint hSelf
              (approximateVector n k) -
            realization.excitationEmbed n
              (F.hamiltonian n
                ((finiteWitness n).spectralVector
                  (finiteIndexEquiv n k))))
        atTop (nhds 0)

attribute [instance]
  PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonApproximateEigenpairStrongLimitData.spectralFintype

namespace PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonApproximateEigenpairStrongLimitData

variable
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {T : P.StronglyContinuousPhysicalSemigroup}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingVacuumGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C}
    {A : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierGapTransfer
      S D halfExtent N hN beta hbeta B hInvariant P T C Q}
    {hSelf : IsSelfAdjoint T.closedRightHamiltonian}
    {W : FiniteWilsonOSAutomaticApproximationFamily}
    {F : FiniteWilsonOSAutomaticExactGapFiniteDimensionalHamiltonianContractionData W}
    [DecidableEq A.toVacuumSemigroupGapSlope.BelowHalfMassShift]
    {nodes : Finset A.toVacuumSemigroupGapSlope.BelowHalfMassShift}
    {orderCap : ℕ}

/-- Forget the concrete finite OS realization while retaining the automatically
constructed continuum excitation embedding. -/
noncomputable def toEmbeddedFiniteWilsonApproximateEigenpairStrongLimitData
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonApproximateEigenpairStrongLimitData
      A hSelf F nodes orderCap) :
    A.toVacuumSemigroupGapSlope.EmbeddedFiniteWilsonApproximateEigenpairStrongLimitData
      T hSelf F nodes orderCap :=
  { finiteWitness := R.finiteWitness
    SpectralIndex := R.SpectralIndex
    spectralFintype := R.spectralFintype
    finiteIndexEquiv := R.finiteIndexEquiv
    embed := R.realization.excitationEmbed
    embed_norm := R.realization.excitationEmbed_norm
    approximateVector := R.approximateVector
    approximateVector_coe := R.approximateVector_coe
    spectralValue := R.spectralValue
    spectralValue_injective := R.spectralValue_injective
    spectralVector := R.spectralVector
    approximateValue_tendsto := R.approximateValue_tendsto
    approximateVector_tendsto := R.approximateVector_tendsto
    operatorCompatibility_tendsto_zero := R.operatorCompatibility_tendsto_zero }

/-- The actual common-carrier Wilson realization supplies the continuum closed
approximate-eigenpair transport package. -/
noncomputable def toContinuumResolventApproximateEigenpairStrongLimitData
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonApproximateEigenpairStrongLimitData
      A hSelf F nodes orderCap) :
    A.toVacuumSemigroupGapSlope.ContinuumResolventApproximateEigenpairStrongLimitData
      T hSelf nodes orderCap :=
  R.toEmbeddedFiniteWilsonApproximateEigenpairStrongLimitData
    |>.toContinuumResolventApproximateEigenpairStrongLimitData

/-- Common-carrier finite Wilson realization and graph-compatible strong limits
supply continuum confluent resolvent linear independence. -/
theorem continuumResolventConfluentCauchy_linearIndependent
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonApproximateEigenpairStrongLimitData
      A hSelf F nodes orderCap)
    (hP : P.IsNormalized)
    (hInnerSymmetric : T.toPhysicalSemigroup.IsInnerSymmetric) :
    LinearIndependent ℝ
      (fun p : nodes × Fin orderCap =>
        ContinuousLinearMap.positivePowerJetOperatorFamily
          (fun sigma : A.toVacuumSemigroupGapSlope.BelowHalfMassShift =>
            A.toVacuumSemigroupGapSlope.vacuumOrthogonalContinuumRealResolvent
              T hP hInnerSymmetric hSelf sigma.property)
          (p.1.1, p.2.1)) :=
  R.toEmbeddedFiniteWilsonApproximateEigenpairStrongLimitData
    |>.continuumResolventConfluentCauchy_linearIndependent hP hInnerSymmetric

/-- The same actual common-carrier realization gives support-local continuum
positive-power jet coefficient-map faithfulness. -/
theorem continuumResolventPositivePowerJetCoefficientMapsIndependent
    (R : PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonApproximateEigenpairStrongLimitData
      A hSelf F nodes orderCap)
    (hP : P.IsNormalized)
    (hInnerSymmetric : T.toPhysicalSemigroup.IsInnerSymmetric)
    (left right : ContinuousLinearMap.PositivePowerJetCoefficientMap
      A.toVacuumSemigroupGapSlope.BelowHalfMassShift)
    (hFit : A.toVacuumSemigroupGapSlope.PositivePowerJetCoefficientMapsFitWindow
      nodes orderCap left right) :
    A.toVacuumSemigroupGapSlope.ContinuumResolventPositivePowerJetCoefficientMapsIndependent
      T hP hInnerSymmetric hSelf left right :=
  R.toEmbeddedFiniteWilsonApproximateEigenpairStrongLimitData
    |>.continuumResolventPositivePowerJetCoefficientMapsIndependent
      hP hInnerSymmetric left right hFit

end PhysicalYangMillsEvenPeriodicWilsonOSCommonCarrierFiniteWilsonApproximateEigenpairStrongLimitData

end StronglyContinuousPhysicalSemigroup
end PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

end

end MathlibAnalytic
end MGAP4D
