import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSCanonicalTwoSidedConfluentResolventJetRealFormLimit

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

end

end MathlibAnalytic
end MGAP4D
