import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonCommonProductPhysicalAmbientCarrier
import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonSelectedSlowStateTwoStepRecovery
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

open Filter MeasureTheory Set Topology
open scoped InnerProductSpace

local instance (H : ℕ) : NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- Final selected-sequence reverse-recovery interface after the actual finite
Wilson OS Hilbert spaces have been placed in the interacting boundary-product
common carrier and that single common carrier has been realized isometrically in
the continuum physical OS Hilbert space.

The finite state used here is not recovery data: it is the canonical slow state
`physicalYangMillsSelectedFiniteSlowState C n` theorem-generated by the actual
finite Wilson two-step energy theorem.  The only scale-dependent dynamical data
stored by this structure are therefore the moving-time residual along this one
canonical sequence and its `o(a_n)` excess.

The coherent positive-half square root is first put on the canonical vacuum-sign
branch.  No all-vector moving-time bound is assumed. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSCommonProductSelectedSlowStateRecovery
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S}
    {R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    (C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E R hInvariant)
    (P : D.OSPreHilbertData)
    (T : P.StronglyContinuousPhysicalSemigroup)
    (J : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalCarrier
      halfExtent N hN beta hbeta P) where
  vectorDefectExcess : ℕ → ℝ
  vectorDefectExcess_tendsto_zero : Tendsto vectorDefectExcess atTop (nhds 0)
  selectedTwoStepVectorDefect_le :
    ∀ n,
      let A := J.toMassFreeAmbientCarrier Q hInvariant
      let phi := physicalYangMillsSelectedFiniteSlowState C n
      let K := C.boundedAnalysis.physicalExcitationOneStepOperator n
      let eta := A.excitationEmbed n ((K ∘L K) phi)
      let psi := A.excitationEmbed n phi
      ‖(eta : P.PhysicalHilbert) -
          T.toPhysicalSemigroup.operator
            (physicalYangMillsLatticeSpacingNNReal S n +
              physicalYangMillsLatticeSpacingNNReal S n)
            (psi : P.PhysicalHilbert)‖ ≤
        2 * S.latticeSpacing n * vectorDefectExcess n

namespace PhysicalYangMillsEvenPeriodicWilsonOSCommonProductSelectedSlowStateRecovery

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S}
    {R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E R hInvariant}
    {P : D.OSPreHilbertData}
    {T : P.StronglyContinuousPhysicalSemigroup}
    {J : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalCarrier
      halfExtent N hN beta hbeta P}

/-- The common-product selected-sequence interface canonically supplies #1579's
minimal selected-slow-state two-step recovery package. -/
noncomputable def toSelectedSlowStateTwoStepRecovery
    (V : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductSelectedSlowStateRecovery
      C P T J) :
    PhysicalYangMillsEvenPeriodicWilsonOSSelectedSlowStateTwoStepRecovery
      C P T (J.toMassFreeAmbientCarrier Q hInvariant) where
  vectorDefectExcess := V.vectorDefectExcess
  vectorDefectExcess_tendsto_zero := V.vectorDefectExcess_tendsto_zero
  selectedTwoStepVectorDefect_le := by
    intro n
    simpa only using V.selectedTwoStepVectorDefect_le n

/-- Thus the one selected moving-time `o(a_n)` residual, together with the
single common-product physical realization, yields the reverse variational mass
inequality.  No residual estimate for arbitrary finite excitations is needed. -/
theorem physicalYangMillsMass_le_limit
    (V : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductSelectedSlowStateRecovery
      C P T J)
    (hSymmetric : T.toPhysicalSemigroup.IsInnerSymmetric) :
    T.physicalYangMillsMass ≤ C.limit :=
  V.toSelectedSlowStateTwoStepRecovery.physicalYangMillsMass_le_limit hSymmetric

/-- The same selected moving-time recovery produces a genuine nonzero continuum
vacuum-orthogonal graph-domain excitation witness. -/
theorem excitationDomainWitness_nonempty
    (V : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductSelectedSlowStateRecovery
      C P T J)
    (hSymmetric : T.toPhysicalSemigroup.IsInnerSymmetric) :
    Nonempty T.PhysicalYangMillsExcitationDomainWitness :=
  V.toSelectedSlowStateTwoStepRecovery.excitationDomainWitness_nonempty hSymmetric

/-- With the independent forward intrinsic-rate common-carrier direction, the
selected moving-time sequence identifies the intrinsic Wilson rate limit with
the physical variational mass.

This still contains no numerical evaluation of either side. -/
theorem limit_eq_physicalYangMillsMass
    (V : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductSelectedSlowStateRecovery
      C P T J)
    (G : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E R hInvariant C P T)
    (hP : P.IsNormalized)
    (hSymmetric : T.toPhysicalSemigroup.IsInnerSymmetric) :
    C.limit = T.physicalYangMillsMass :=
  V.toSelectedSlowStateTwoStepRecovery.limit_eq_physicalYangMillsMass
    G hP hSymmetric

end PhysicalYangMillsEvenPeriodicWilsonOSCommonProductSelectedSlowStateRecovery

end

end MathlibAnalytic
end MGAP4D
