import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenWilsonGibbsBoundedContinuousReflectionPositivity
import MGAP4D.MathlibAnalytic.PhysicalYangMillsWeakMeasureLimit
import Mathlib.Topology.Order.OrderClosed

namespace MGAP4D
namespace MathlibAnalytic

open Filter MeasureTheory

noncomputable section

local instance (H : ℕ) : NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- Nonnegativity of expectations of a fixed bounded continuous physical
observable is closed under weak convergence of probability measures. -/
theorem physical_yang_mills_bounded_observable_nonneg_of_approximating
    (S : PhysicalFourDimensionalYangMillsWeakLimit)
    (Q : BoundedContinuousFunction S.Configuration ℝ)
    (hQ : ∀ n,
      0 ≤ ∫ A, Q A
        ∂(S.approximatingMeasure n : Measure S.Configuration)) :
    0 ≤ ∫ A, Q A
      ∂(S.continuumMeasure : Measure S.Configuration) := by
  exact isClosed_Ici.mem_of_tendsto
    (physical_yang_mills_bounded_observable_expectation_converges S Q)
    (.of_forall hQ)

/-- Concrete identification data connecting a fixed bounded continuous physical
Osterwalder--Schrader quadratic observable to the actual finite-volume
even-periodic `SU(N)` Wilson Gibbs reflection forms.

The bridge records only the two model-dependent identifications which weak
convergence cannot construct by itself:

* each physical approximating law is the pushforward of the actual finite
  Wilson Gibbs law;
* the physical quadratic observable pulls back to the finite reflected
  observable generated by a bounded continuous positive-half observable.

All finite-volume nonnegativity is supplied by the theorem-generated Wilson
Gibbs Gram construction. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSWeakLimitBridge
    (S : PhysicalFourDimensionalYangMillsWeakLimit)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : BoundedContinuousFunction S.Configuration ℝ) where
  interpolate :
    ∀ n,
      (PeriodicHypercubicEvenEdge (halfExtent n) →
        Matrix.specialUnitaryGroup (Fin N) ℂ) →
        S.Configuration
  interpolate_measurable : ∀ n, Measurable (interpolate n)
  positiveHalfObservable :
    ∀ n, BoundedContinuousFunction
      (PeriodicHypercubicEvenSpecialUnitaryOpenHalfConfiguration
        (halfExtent n) N) ℝ
  approximatingMeasure_toMeasure_eq :
    ∀ n,
      (S.approximatingMeasure n : Measure S.Configuration) =
        Measure.map (interpolate n)
          (periodicHypercubicSpecialUnitaryWilsonSystem
            (PeriodicHypercubicEvenSideLength (halfExtent n))
            N hN (beta n) (hbeta n)).gibbsMeasure
  quadraticObservable_pullback :
    ∀ n A,
      Q (interpolate n A) =
        periodicHypercubicEvenFullReflectedObservable
          (halfExtent n) (positiveHalfObservable n) A

/-- The actual finite-volume Wilson Gibbs theorem makes every physical
approximating expectation in the bridge nonnegative. -/
theorem physical_yang_mills_evenPeriodicWilsonOS_approximating_nonneg
    (S : PhysicalFourDimensionalYangMillsWeakLimit)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : BoundedContinuousFunction S.Configuration ℝ)
    (B : PhysicalYangMillsEvenPeriodicWilsonOSWeakLimitBridge
      S halfExtent N hN beta hbeta Q)
    (n : ℕ) :
    0 ≤ ∫ A, Q A
      ∂(S.approximatingMeasure n : Measure S.Configuration) := by
  rw [B.approximatingMeasure_toMeasure_eq n]
  rw [MeasureTheory.integral_map
    (B.interpolate_measurable n).aemeasurable
    Q.continuous.aestronglyMeasurable]
  have heq :
      (∫ A, Q (B.interpolate n A)
        ∂(periodicHypercubicSpecialUnitaryWilsonSystem
          (PeriodicHypercubicEvenSideLength (halfExtent n))
          N hN (beta n) (hbeta n)).gibbsMeasure) =
        ∫ A,
          periodicHypercubicEvenFullReflectedObservable
            (halfExtent n) (B.positiveHalfObservable n) A
          ∂(periodicHypercubicSpecialUnitaryWilsonSystem
            (PeriodicHypercubicEvenSideLength (halfExtent n))
            N hN (beta n) (hbeta n)).gibbsMeasure := by
    apply integral_congr_ae
    filter_upwards [] with A
    exact B.quadraticObservable_pullback n A
  rw [heq]
  exact periodicHypercubicEvenWilsonGibbs_reflectionPositive_boundedContinuous
    (halfExtent n) N hN (beta n) (hbeta n)
      (B.positiveHalfObservable n)

/-- The actual finite-volume even-periodic Wilson Gibbs reflection positivity
passes to the physical continuum weak limit for every fixed bounded continuous
physical quadratic observable equipped with the concrete pullback bridge. -/
theorem physical_yang_mills_evenPeriodicWilsonOS_continuum_nonneg
    (S : PhysicalFourDimensionalYangMillsWeakLimit)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : BoundedContinuousFunction S.Configuration ℝ)
    (B : PhysicalYangMillsEvenPeriodicWilsonOSWeakLimitBridge
      S halfExtent N hN beta hbeta Q) :
    0 ≤ ∫ A, Q A
      ∂(S.continuumMeasure : Measure S.Configuration) := by
  exact physical_yang_mills_bounded_observable_nonneg_of_approximating
    S Q
    (fun n =>
      physical_yang_mills_evenPeriodicWilsonOS_approximating_nonneg
        S halfExtent N hN beta hbeta Q B n)

end

end MathlibAnalytic
end MGAP4D
