import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonSUNTwoModeFiniteOSVacuumPairFixedSeam
import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonPositiveHalfCanonicalSign
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenBoundaryVacuumMomentGaugeInvariance
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenBoundaryVacuumL2
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenOSBoundarySpatialHalfWeightFactorization
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenSpecialUnitaryGaussLawTransfer
import Mathlib.Tactic

/-!
# Independent endpoint Gauss invariance of the finite OS vacuum pair

The physical pair carrier is generated by tensors of one-slice Gauss-law
physical vectors.  Therefore the model-specific input needed before a general
Hilbert closure theorem is independent gauge invariance at the two endpoint
slices, not merely simultaneous gauge invariance.

This file proves that input for the canonical sign-normalized finite Wilson OS
vacuum.

The proof has four layers:

1. define independent primary/antipodal pair gauge pullback;
2. extend two independent endpoint gauge transformations to one four-dimensional
   vertex gauge transformation;
3. transport the already-proved full boundary vacuum gauge invariance through
   the exact boundary/two-slice coordinate equivalence;
4. identify the sign-normalized OS vacuum boundary image with the concrete
   finite Wilson boundary vacuum L2 vector.

No transfer-gap, top-mode, decay, or carrier-density input is used.
-/

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory Filter
open scoped InnerProductSpace InnerProduct

noncomputable section

local instance sunVacuumIndependentGaussTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance sunVacuumIndependentGaussCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance sunVacuumIndependentGaussSecondCountable (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance sunVacuumIndependentGaussMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance sunVacuumIndependentGaussBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

local instance sunVacuumIndependentGaussSpatialLinkFintype (H : ℕ) :
    Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

local instance sunVacuumIndependentGaussSpatialSliceHaarSFinite (H N : ℕ) :
    SFinite (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N) := by
  unfold periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure
  infer_instance

/-- The antipodal half-period is nonzero on the even periodic time circle. -/
theorem periodicHypercubicEven_halfPeriod_ne_zero
    (H : ℕ) :
    (((H + 1 : ℕ) : ZMod (PeriodicHypercubicEvenSideLength H))) ≠ 0 := by
  intro hzero
  have hlt : H + 1 < PeriodicHypercubicEvenSideLength H := by
    simp only [PeriodicHypercubicEvenSideLength]
    omega
  have hmod :
      0 % PeriodicHypercubicEvenSideLength H =
        (H + 1) % PeriodicHypercubicEvenSideLength H :=
    (ZMod.natCast_eq_natCast_iff' 0 (H + 1)
      (PeriodicHypercubicEvenSideLength H)).mp hzero.symm
  rw [Nat.zero_mod, Nat.mod_eq_of_lt hlt] at hmod
  omega

/-- Independent gauge action on the primary and antipodal endpoint slices. -/
def periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N) :
    (PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N ×
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N) →
    (PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N ×
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N) :=
  Prod.map
    (periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransform
      H N gammaPrimary)
    (periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransform
      H N gammaAntipodal)

@[simp] theorem
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform_apply
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N)
    (p : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N ×
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N) :
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
        H N gammaPrimary gammaAntipodal p =
      (periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransform
          H N gammaPrimary p.1,
        periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransform
          H N gammaAntipodal p.2) :=
  rfl

/-- Independent endpoint gauge action preserves product Haar probability. -/
theorem
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform_measurePreserving
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N) :
    MeasurePreserving
      (periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
        H N gammaPrimary gammaAntipodal)
      (periodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarMeasure H N)
      (periodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarMeasure H N) := by
  unfold
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
  unfold periodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarMeasure
  exact
    (periodicHypercubicEvenSpecialUnitarySpatialSliceHaar_measurePreserving
      H N gammaPrimary).prod
    (periodicHypercubicEvenSpecialUnitarySpatialSliceHaar_measurePreserving
      H N gammaAntipodal)

/-- L2 pullback by independent endpoint gauge action. -/
noncomputable def
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugePullbackLinearIsometry
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N) :
    PeriodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarL2 H N →ₗᵢ[ℝ]
      PeriodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarL2 H N :=
  MeasureTheory.Lp.compMeasurePreservingₗᵢ ℝ
    (periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
      H N gammaPrimary gammaAntipodal)
    (periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform_measurePreserving
      H N gammaPrimary gammaAntipodal)

theorem
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugePullbackLinearIsometry_coeFn
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N)
    (F : PeriodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarL2 H N) :
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugePullbackLinearIsometry
        H N gammaPrimary gammaAntipodal F =ᵐ[
      periodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarMeasure H N]
      fun p =>
        F
          (periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
            H N gammaPrimary gammaAntipodal p) := by
  simpa [
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugePullbackLinearIsometry,
    Function.comp_def] using
    (MeasureTheory.Lp.coeFn_compMeasurePreserving F
      (periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform_measurePreserving
        H N gammaPrimary gammaAntipodal))

/-- Extend two independent endpoint gauge transformations to the full periodic
vertex set.  Away from the two reflection-fixed time slices the extension is
the identity. -/
def periodicHypercubicEvenIndependentEndpointGaugeExtension
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N)
    (v : PeriodicHypercubicEvenVertex H) :
    Matrix.specialUnitaryGroup (Fin N) ℂ :=
  if v 0 = 0 then
    gammaPrimary (periodicHypercubicEvenSpatialSliceVertexProjection H v)
  else if
      v 0 =
        (((H + 1 : ℕ) : ZMod (PeriodicHypercubicEvenSideLength H))) then
    gammaAntipodal (periodicHypercubicEvenSpatialSliceVertexProjection H v)
  else
    1

@[simp] theorem periodicHypercubicEvenIndependentEndpointGaugeExtension_primary
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N)
    (v : PeriodicHypercubicEvenSpatialSliceVertex H) :
    periodicHypercubicEvenIndependentEndpointGaugeExtension
        H N gammaPrimary gammaAntipodal v.1 =
      gammaPrimary v := by
  have hproj :
      periodicHypercubicEvenSpatialSliceVertexProjection H v.1 = v := by
    apply Subtype.ext
    funext i
    by_cases hi : i = 0
    · subst i
      simp [periodicHypercubicEvenSpatialSliceVertexProjection, v.2]
    · simp [periodicHypercubicEvenSpatialSliceVertexProjection, hi]
  simp [periodicHypercubicEvenIndependentEndpointGaugeExtension, v.2, hproj]

@[simp] theorem periodicHypercubicEvenIndependentEndpointGaugeExtension_antipodal
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N)
    (v : PeriodicHypercubicEvenSpatialSliceVertex H) :
    periodicHypercubicEvenIndependentEndpointGaugeExtension
        H N gammaPrimary gammaAntipodal
        (periodicHypercubicEvenHalfPeriodTimeShift H v.1) =
      gammaAntipodal v := by
  have htime :
      periodicHypercubicEvenHalfPeriodTimeShift H v.1 0 =
        (((H + 1 : ℕ) : ZMod (PeriodicHypercubicEvenSideLength H))) := by
    rw [periodicHypercubicEvenHalfPeriodTimeShift_time, v.2, zero_add]
  have hproj :
      periodicHypercubicEvenSpatialSliceVertexProjection H
          (periodicHypercubicEvenHalfPeriodTimeShift H v.1) = v := by
    apply Subtype.ext
    funext i
    by_cases hi : i = 0
    · subst i
      simp [periodicHypercubicEvenSpatialSliceVertexProjection, v.2]
    · simp [periodicHypercubicEvenSpatialSliceVertexProjection,
        periodicHypercubicEvenHalfPeriodTimeShift, hi]
  simp [periodicHypercubicEvenIndependentEndpointGaugeExtension,
    htime, periodicHypercubicEven_halfPeriod_ne_zero H, hproj]

/-- On the primary fixed slice, the full boundary gauge extension is exactly
the primary one-slice gauge action. -/
theorem
    periodicHypercubicEvenBoundaryPrimarySpatialSliceConfiguration_gaugeTransform_independentExtension
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N)
    (b : PeriodicHypercubicEvenSpecialUnitaryBoundaryConfiguration H N) :
    periodicHypercubicEvenBoundaryPrimarySpatialSliceConfiguration H
        (periodicHypercubicEvenBoundaryGaugeTransform H N
          (periodicHypercubicEvenIndependentEndpointGaugeExtension
            H N gammaPrimary gammaAntipodal) b) =
      periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransform
        H N gammaPrimary
        (periodicHypercubicEvenBoundaryPrimarySpatialSliceConfiguration H b) := by
  funext e
  change
    periodicHypercubicEvenIndependentEndpointGaugeExtension
        H N gammaPrimary gammaAntipodal e.1.1 *
      b (periodicHypercubicEvenPrimarySpatialSliceLinkToFixedEdge H e) *
      (periodicHypercubicEvenIndependentEndpointGaugeExtension
        H N gammaPrimary gammaAntipodal
        (periodicHypercubicEvenSpatialSliceShift H e.1 e.2).1)⁻¹ =
    gammaPrimary e.1 *
      b (periodicHypercubicEvenPrimarySpatialSliceLinkToFixedEdge H e) *
      (gammaPrimary
        (periodicHypercubicEvenSpatialSliceShift H e.1 e.2))⁻¹
  rw [
    periodicHypercubicEvenIndependentEndpointGaugeExtension_primary,
    periodicHypercubicEvenIndependentEndpointGaugeExtension_primary]

/-- On the antipodal fixed slice, the same full extension is exactly the
independent antipodal one-slice gauge action after half-period reindexing. -/
theorem
    periodicHypercubicEvenBoundaryAntipodalSpatialSliceConfiguration_gaugeTransform_independentExtension
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N)
    (b : PeriodicHypercubicEvenSpecialUnitaryBoundaryConfiguration H N) :
    periodicHypercubicEvenBoundaryAntipodalSpatialSliceConfiguration H
        (periodicHypercubicEvenBoundaryGaugeTransform H N
          (periodicHypercubicEvenIndependentEndpointGaugeExtension
            H N gammaPrimary gammaAntipodal) b) =
      periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransform
        H N gammaAntipodal
        (periodicHypercubicEvenBoundaryAntipodalSpatialSliceConfiguration H b) := by
  funext e
  change
    periodicHypercubicEvenIndependentEndpointGaugeExtension
        H N gammaPrimary gammaAntipodal
        (periodicHypercubicEvenHalfPeriodTimeShift H e.1.1) *
      b (periodicHypercubicEvenAntipodalSpatialSliceLinkToFixedEdge H
        (periodicHypercubicEvenPrimaryAntipodalSpatialSliceLinkEquiv H e)) *
      (periodicHypercubicEvenIndependentEndpointGaugeExtension
        H N gammaPrimary gammaAntipodal
        (periodicHypercubicShift
          (PeriodicHypercubicEvenSideLength H)
          (periodicHypercubicEvenHalfPeriodTimeShift H e.1.1)
          e.2.1))⁻¹ =
    gammaAntipodal e.1 *
      b (periodicHypercubicEvenAntipodalSpatialSliceLinkToFixedEdge H
        (periodicHypercubicEvenPrimaryAntipodalSpatialSliceLinkEquiv H e)) *
      (gammaAntipodal
        (periodicHypercubicEvenSpatialSliceShift H e.1 e.2))⁻¹
  rw [periodicHypercubicEvenIndependentEndpointGaugeExtension_antipodal]
  rw [← periodicHypercubicEvenHalfPeriodTimeShift_shift_spatial
    H e.1.1 e.2.1 e.2.2]
  change
    _ *
      _ *
      (periodicHypercubicEvenIndependentEndpointGaugeExtension
        H N gammaPrimary gammaAntipodal
        (periodicHypercubicEvenHalfPeriodTimeShift H
          (periodicHypercubicEvenSpatialSliceShift H e.1 e.2).1))⁻¹ =
      _
  rw [periodicHypercubicEvenIndependentEndpointGaugeExtension_antipodal]

/-- The exact boundary/two-slice coordinate equivalence reads a boundary as its
primary and antipodal spatial-slice restrictions. -/
theorem periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv_apply_eq_slices
    (H N : ℕ)
    (b : PeriodicHypercubicEvenSpecialUnitaryBoundaryConfiguration H N) :
    periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv H
        (Matrix.specialUnitaryGroup (Fin N) ℂ) b =
      (periodicHypercubicEvenBoundaryPrimarySpatialSliceConfiguration H b,
        periodicHypercubicEvenBoundaryAntipodalSpatialSliceConfiguration H b) := by
  rfl

/-- The full boundary gauge extension becomes the independent endpoint pair
gauge action under the exact boundary/two-slice coordinates. -/
theorem
    periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv_gaugeTransform_independentExtension
    (H N : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N)
    (b : PeriodicHypercubicEvenSpecialUnitaryBoundaryConfiguration H N) :
    periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv H
        (Matrix.specialUnitaryGroup (Fin N) ℂ)
        (periodicHypercubicEvenBoundaryGaugeTransform H N
          (periodicHypercubicEvenIndependentEndpointGaugeExtension
            H N gammaPrimary gammaAntipodal) b) =
      periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
        H N gammaPrimary gammaAntipodal
        (periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv H
          (Matrix.specialUnitaryGroup (Fin N) ℂ) b) := by
  rw [
    periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv_apply_eq_slices,
    periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv_apply_eq_slices,
    periodicHypercubicEvenBoundaryPrimarySpatialSliceConfiguration_gaugeTransform_independentExtension,
    periodicHypercubicEvenBoundaryAntipodalSpatialSliceConfiguration_gaugeTransform_independentExtension]
  rfl

/-- Concrete finite Wilson boundary vacuum moment is invariant under independent
primary/antipodal endpoint gauge transformations in pair coordinates. -/
theorem periodicHypercubicEvenBoundaryVacuumMoment_pairCoordinates_independentGaugeInvariant
    (H N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ) (hbeta : 0 ≤ beta)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N)
    (p : PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N ×
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceConfiguration H N) :
    periodicHypercubicEvenBoundaryVacuumMoment H N hN beta hbeta
        ((periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv H
          (Matrix.specialUnitaryGroup (Fin N) ℂ)).symm
          (periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
            H N gammaPrimary gammaAntipodal p)) =
      periodicHypercubicEvenBoundaryVacuumMoment H N hN beta hbeta
        ((periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv H
          (Matrix.specialUnitaryGroup (Fin N) ℂ)).symm p) := by
  let e :=
    periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv H
      (Matrix.specialUnitaryGroup (Fin N) ℂ)
  let gamma :=
    periodicHypercubicEvenIndependentEndpointGaugeExtension
      H N gammaPrimary gammaAntipodal
  have hcoord :
      e (periodicHypercubicEvenBoundaryGaugeTransform H N gamma (e.symm p)) =
        periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
          H N gammaPrimary gammaAntipodal p := by
    simpa [e, gamma] using
      periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv_gaugeTransform_independentExtension
        H N gammaPrimary gammaAntipodal (e.symm p)
  have hboundary :
      periodicHypercubicEvenBoundaryGaugeTransform H N gamma (e.symm p) =
        e.symm
          (periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
            H N gammaPrimary gammaAntipodal p) := by
    apply e.injective
    simpa [hcoord]
  rw [← hboundary]
  exact
    periodicHypercubicEvenBoundaryVacuumMoment_gaugeInvariant
      H N hN beta hbeta gamma (e.symm p)

/-- The generic finite Wilson boundary vacuum L2 vector is independently
Gauss-fixed after transport to endpoint-pair coordinates. -/
theorem periodicHypercubicEvenBoundaryVacuumL2_to_pair_independentGaugeFixed
    (H N : ℕ) (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ) (hbeta : 0 ≤ beta)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation H N) :
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugePullbackLinearIsometry
        H N gammaPrimary gammaAntipodal
        (periodicHypercubicEvenBoundaryHaarL2ToSpatialSlicePairLinearIsometry H N
          (periodicHypercubicEvenBoundaryVacuumL2 H N hN beta hbeta)) =
      periodicHypercubicEvenBoundaryHaarL2ToSpatialSlicePairLinearIsometry H N
        (periodicHypercubicEvenBoundaryVacuumL2 H N hN beta hbeta) := by
  let mu :=
    periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N
  let muPair :=
    periodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarMeasure H N
  let e :=
    periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv H
      (Matrix.specialUnitaryGroup (Fin N) ℂ)
  let V :=
    periodicHypercubicEvenBoundaryHaarL2ToSpatialSlicePairLinearIsometry H N
      (periodicHypercubicEvenBoundaryVacuumL2 H N hN beta hbeta)
  let G :=
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform
      H N gammaPrimary gammaAntipodal
  let U :=
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugePullbackLinearIsometry
      H N gammaPrimary gammaAntipodal
  apply Lp.ext
  have hPull :=
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugePullbackLinearIsometry_coeFn
      H N gammaPrimary gammaAntipodal V
  have hV :=
    periodicHypercubicEvenBoundaryHaarL2ToSpatialSlicePairLinearIsometry_coeFn
      H N (periodicHypercubicEvenBoundaryVacuumL2 H N hN beta hbeta)
  have hVpull :=
    (periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform_measurePreserving
      H N gammaPrimary gammaAntipodal).quasiMeasurePreserving.ae_eq hV
  have hVac :=
    periodicHypercubicEvenBoundaryVacuumL2_coeFn
      H N hN beta hbeta
  have he :
      MeasurePreserving e.symm muPair
        (periodicHypercubicEvenBoundaryHaarMeasure H N) := by
    exact
      (periodicHypercubicEvenBoundarySpatialSlicePairMeasurableEquiv_measurePreserving_specialUnitaryHaar
        H N).symm
  have hVacPair := he.quasiMeasurePreserving.ae_eq hVac
  have hVacPairPull :=
    (periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugeTransform_measurePreserving
      H N gammaPrimary gammaAntipodal).quasiMeasurePreserving.ae_eq hVacPair
  filter_upwards [hPull, hVpull, hV, hVacPairPull, hVacPair]
      with p hpull hvpull hv hvacpull hvac
  change U V p = V p
  rw [hpull]
  change V (G p) = V p
  calc
    V (G p) =
        periodicHypercubicEvenBoundaryVacuumL2 H N hN beta hbeta
          (e.symm (G p)) := by
      simpa [V, G, e, Function.comp_def] using hvpull
    _ = periodicHypercubicEvenBoundaryVacuumMoment H N hN beta hbeta
          (e.symm (G p)) := by
      simpa [G, e, Function.comp_def] using hvacpull
    _ = periodicHypercubicEvenBoundaryVacuumMoment H N hN beta hbeta
          (e.symm p) :=
      periodicHypercubicEvenBoundaryVacuumMoment_pairCoordinates_independentGaugeInvariant
        H N hN beta hbeta gammaPrimary gammaAntipodal p
    _ = periodicHypercubicEvenBoundaryVacuumL2 H N hN beta hbeta
          (e.symm p) := by
      simpa [e, Function.comp_def] using hvac.symm
    _ = V p := by
      simpa [V, e, Function.comp_def] using hv.symm

section VacuumNormalizedOS

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ} {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ} {hbeta : ∀ n, 0 ≤ beta n}

/-- For the canonical sign-normalized coherent pullback, the finite OS vacuum
boundary image is exactly the concrete generic-N Wilson boundary vacuum L2. -/
theorem
    PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback.vacuumNormalized_physicalHilbertBoundaryMoment_vacuum_eq_boundaryVacuumL2
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (n : ℕ) :
    let Pn :=
      physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta
          Q.vacuumNormalized.toWeakStarBridge hInvariant n
    Q.vacuumNormalized.physicalHilbertBoundaryMomentLinearIsometry
        hInvariant n Pn.vacuum =
      periodicHypercubicEvenBoundaryVacuumL2
        (halfExtent n) N hN (beta n) (hbeta n) := by
  dsimp only
  let Pn :=
    physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
      S D halfExtent N hN beta hbeta
        Q.vacuumNormalized.toWeakStarBridge hInvariant n
  change
    Q.vacuumNormalized.physicalHilbertBoundaryMomentLinearIsometry
        hInvariant n
        (Pn.physicalState Pn.vacuumObservable) =
      periodicHypercubicEvenBoundaryVacuumL2
        (halfExtent n) N hN (beta n) (hbeta n)
  rw [
    Q.vacuumNormalized.physicalHilbertBoundaryMomentLinearIsometry_physicalState]
  apply Lp.ext
  exact
    ((Q.vacuumNormalizedUnitCompatibility hInvariant).canonicalBoundaryMomentL2_vacuum_coeFn
      n).trans
      (periodicHypercubicEvenBoundaryVacuumL2_coeFn
        (halfExtent n) N hN (beta n) (hbeta n)).symm

/-- Hence the explicit finite OS vacuum pair for the canonical sign-normalized
coherent pullback is fixed by every independent endpoint gauge pullback. -/
theorem
    PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback.vacuumNormalized_explicitOSVacuumBoundaryPair_independentGaugeFixed
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (n : ℕ)
    (gammaPrimary gammaAntipodal :
      PeriodicHypercubicEvenSpecialUnitarySpatialSliceGaugeTransformation
        (halfExtent n) N) :
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugePullbackLinearIsometry
        (halfExtent n) N gammaPrimary gammaAntipodal
        (physicalYangMillsSUNTwoModeExplicitOSVacuumBoundaryPairL2
          (S := S) (D := D) (halfExtent := halfExtent)
          (N := N) (hN := hN)
          (beta := beta) (hbeta := hbeta)
          (Q := Q.vacuumNormalized) (hInvariant := hInvariant) n) =
      physicalYangMillsSUNTwoModeExplicitOSVacuumBoundaryPairL2
        (S := S) (D := D) (halfExtent := halfExtent)
        (N := N) (hN := hN)
        (beta := beta) (hbeta := hbeta)
        (Q := Q.vacuumNormalized) (hInvariant := hInvariant) n := by
  let Pn :=
    physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
      S D halfExtent N hN beta hbeta
        Q.vacuumNormalized.toWeakStarBridge hInvariant n
  let J :=
    Q.vacuumNormalized.physicalHilbertBoundaryMomentLinearIsometry
      hInvariant n
  let E :=
    periodicHypercubicEvenBoundaryHaarL2ToSpatialSlicePairLinearIsometry
      (halfExtent n) N
  change
    periodicHypercubicEvenSpecialUnitarySpatialSliceIndependentPairGaugePullbackLinearIsometry
        (halfExtent n) N gammaPrimary gammaAntipodal
        (E (J Pn.vacuum)) =
      E (J Pn.vacuum)
  rw [
    Q.vacuumNormalized_physicalHilbertBoundaryMoment_vacuum_eq_boundaryVacuumL2
      hInvariant n]
  exact
    periodicHypercubicEvenBoundaryVacuumL2_to_pair_independentGaugeFixed
      (halfExtent n) N hN (beta n) (hbeta n)
      gammaPrimary gammaAntipodal

end VacuumNormalizedOS

end

end MathlibAnalytic
end MGAP4D
