import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSApproximatingObservableQuadraticGap
import Mathlib.Tactic

noncomputable section

open Filter Set Topology
open scoped InnerProductSpace

namespace MGAP4D
namespace MathlibAnalytic

namespace PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

variable {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
variable {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
variable {P : D.OSPreHilbertData}

/-- Center an OS carrier observable by subtracting its vacuum expectation. -/
def vacuumCenteredCarrier (P : D.OSPreHilbertData) (F : P.Carrier) : P.Carrier :=
  F - P.omega F.toGaugeInvariant • P.vacuumObservable

/-- Carrier centering is exactly Hilbert-space vacuum centering after taking the
represented physical state. -/
theorem physicalState_vacuumCenteredCarrier
    (P : D.OSPreHilbertData) (F : P.Carrier) :
    P.physicalState (P.vacuumCenteredCarrier F) =
      finiteVacuumCentered P.vacuum (P.physicalState F) := by
  unfold vacuumCenteredCarrier finiteVacuumCentered
  rw [P.inner_vacuum_physicalState]
  calc
    P.physicalState
        (F - P.omega F.toGaugeInvariant • P.vacuumObservable) =
      P.physicalStateLinearMap
        (F - P.omega F.toGaugeInvariant • P.vacuumObservable) :=
      (P.physicalStateLinearMap_apply _).symm
    _ = P.physicalStateLinearMap F -
        P.omega F.toGaugeInvariant •
          P.physicalStateLinearMap P.vacuumObservable := by
      rw [map_sub, map_smul]
    _ = P.physicalState F - P.omega F.toGaugeInvariant • P.vacuum := by
      rw [P.physicalStateLinearMap_apply,
        P.physicalStateLinearMap_vacuumObservable]

namespace PositiveTimeObservableContractionSemigroup

/-- On a represented carrier observable, the diagonal completed-transfer
coefficient is exactly the reflected OS bilinear form with translated first
entry. -/
theorem inner_operator_physicalState_eq_osBilinForm
    (T : P.PositiveTimeObservableContractionSemigroup)
    (t : NNReal) (F : P.Carrier) :
    inner ℝ (T.toPhysicalSemigroup.operator t (P.physicalState F))
        (P.physicalState F) =
      D.osBilinForm P.omega
        (P.toPositiveTime (T.carrierTranslation t F))
        (P.toPositiveTime F) := by
  change inner ℝ
      (T.toCarrierSemigroup.physicalOperator t (P.physicalState F))
      (P.physicalState F) = _
  rw [T.toCarrierSemigroup.physicalOperator_on_physicalState,
    P.inner_physicalState_physicalState,
    P.inner_eq_osBilinForm]
  rfl

end PositiveTimeObservableContractionSemigroup
end PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

/-- A finite Wilson OS gap certificate stated directly as a reflected quadratic
integral inequality on centered positive-time carrier observables.

This is the closest current interface to the concrete even-periodic Wilson Gibbs
factorization.  All Hilbert completion, density extension, semigroup squaring,
and norm decay are generated by later constructors. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSApproximatingReflectedQuadraticGapCertificate
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant) where
  mass : ℝ
  mass_pos : 0 < mass
  quadraticDecayFactor : NNReal → ℝ
  quadraticDecayFactor_nonneg :
    ∀ t, 0 ≤ quadraticDecayFactor t
  slope_tendsto :
    Tendsto
      (fun t : NNReal =>
        (t : ℝ)⁻¹ *
          (1 - Real.sqrt (quadraticDecayFactor (t + t))))
      (nhdsWithin 0 (Ioi 0))
      (nhds mass)
  exchange : ∀ n,
    PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
      (C.toPositiveTimeObservableContractionSemigroup n)
  finite_reflected_quadratic_decay :
    ∀ (n : ℕ) (t : NNReal),
      let Pn :=
        physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
          S D halfExtent N hN beta hbeta B hInvariant n
      let Tn := C.toPositiveTimeObservableContractionSemigroup n
      ∀ F : Pn.Carrier,
        D.osBilinForm Pn.omega
            (Pn.toPositiveTime
              (Tn.carrierTranslation t (Pn.vacuumCenteredCarrier F)))
            (Pn.toPositiveTime (Pn.vacuumCenteredCarrier F)) ≤
          quadraticDecayFactor t *
            Pn.osQuadraticValue (Pn.vacuumCenteredCarrier F)

namespace PhysicalYangMillsEvenPeriodicWilsonOSApproximatingReflectedQuadraticGapCertificate

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant}

/-- Convert the reflected finite Wilson integral estimate into the observable-core
quadratic-gap certificate. -/
noncomputable def toApproximatingObservableQuadraticGapCertificate
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingReflectedQuadraticGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C) :
    PhysicalYangMillsEvenPeriodicWilsonOSApproximatingObservableQuadraticGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C where
  mass := Q.mass
  mass_pos := Q.mass_pos
  quadraticDecayFactor := Q.quadraticDecayFactor
  quadraticDecayFactor_nonneg := Q.quadraticDecayFactor_nonneg
  slope_tendsto := Q.slope_tendsto
  exchange := Q.exchange
  finite_observable_quadratic_decay := by
    intro n t F
    let Pn :=
      physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta B hInvariant n
    let Tn := C.toPositiveTimeObservableContractionSemigroup n
    let Fc := Pn.vacuumCenteredCarrier F
    have hcenter :
        Pn.physicalState Fc =
          finiteVacuumCentered Pn.vacuum (Pn.physicalState F) := by
      exact Pn.physicalState_vacuumCenteredCarrier F
    calc
      inner ℝ
          (C.finiteOperator n t
            (finiteVacuumCentered Pn.vacuum (Pn.physicalState F)))
          (finiteVacuumCentered Pn.vacuum (Pn.physicalState F)) =
        D.osBilinForm Pn.omega
          (Pn.toPositiveTime (Tn.carrierTranslation t Fc))
          (Pn.toPositiveTime Fc) := by
        rw [← hcenter]
        exact Tn.inner_operator_physicalState_eq_osBilinForm t Fc
      _ ≤ Q.quadraticDecayFactor t * Pn.osQuadraticValue Fc :=
        Q.finite_reflected_quadratic_decay n t F
      _ = Q.quadraticDecayFactor t *
          ‖finiteVacuumCentered Pn.vacuum (Pn.physicalState F)‖ ^ 2 := by
        rw [← hcenter, Pn.norm_physicalState,
          Pn.osQuadraticValue_eq_norm_sq]

/-- The reflected finite Wilson integral certificate therefore generates the
completed finite-volume norm-decay certificate. -/
noncomputable def toApproximatingVacuumGapCertificate
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingReflectedQuadraticGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C) :
    PhysicalYangMillsEvenPeriodicWilsonOSApproximatingVacuumGapCertificate
      S D halfExtent N hN beta hbeta B hInvariant C :=
  Q.toApproximatingObservableQuadraticGapCertificate
    |>.toApproximatingVacuumGapCertificate

end PhysicalYangMillsEvenPeriodicWilsonOSApproximatingReflectedQuadraticGapCertificate

end MathlibAnalytic
end MGAP4D

end
