import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSBilinearForm
import Mathlib.Analysis.InnerProductSpace.Completion

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- A reflection-invariant, reflection-positive weak-star state, packaged as the
input from which the Osterwalder--Schrader pre-Hilbert space is generated. -/
structure PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S) where
  omega : WeakDual ℝ
    (physicalYangMillsGaugeInvariantObservableSubalgebra S)
  reflectionInvariant : D.WeakStarReflectionInvariant omega
  reflectionPositive : D.WeakStarReflectionPositive omega

/-- An opaque copy of the positive-time observable module.  Opacity is
essential here: bounded continuous observables already carry a supremum norm,
whereas the OS reconstruction requires the different seminorm generated by
`omega (Theta F * F)`. -/
structure PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.Carrier
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    (P : D.OSPreHilbertData) where
  val : D.positiveTimeSubalgebra.toSubmodule

namespace PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

variable {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
variable {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}

instance carrierZero (P : D.OSPreHilbertData) : Zero P.Carrier :=
  ⟨⟨0⟩⟩

instance carrierAdd (P : D.OSPreHilbertData) : Add P.Carrier :=
  ⟨fun F G => ⟨F.val + G.val⟩⟩

instance carrierNeg (P : D.OSPreHilbertData) : Neg P.Carrier :=
  ⟨fun F => ⟨-F.val⟩⟩

instance carrierSub (P : D.OSPreHilbertData) : Sub P.Carrier :=
  ⟨fun F G => ⟨F.val - G.val⟩⟩

instance carrierNatSMul (P : D.OSPreHilbertData) : SMul ℕ P.Carrier :=
  ⟨fun n F => ⟨n • F.val⟩⟩

instance carrierIntSMul (P : D.OSPreHilbertData) : SMul ℤ P.Carrier :=
  ⟨fun n F => ⟨n • F.val⟩⟩

instance carrierRealSMul (P : D.OSPreHilbertData) : SMul ℝ P.Carrier :=
  ⟨fun r F => ⟨r • F.val⟩⟩

@[simp] theorem Carrier.val_zero (P : D.OSPreHilbertData) :
    (0 : P.Carrier).val = 0 := rfl

@[simp] theorem Carrier.val_add (P : D.OSPreHilbertData) (F G : P.Carrier) :
    (F + G).val = F.val + G.val := rfl

@[simp] theorem Carrier.val_neg (P : D.OSPreHilbertData) (F : P.Carrier) :
    (-F).val = -F.val := rfl

@[simp] theorem Carrier.val_sub (P : D.OSPreHilbertData) (F G : P.Carrier) :
    (F - G).val = F.val - G.val := rfl

@[simp] theorem Carrier.val_nsmul (P : D.OSPreHilbertData) (n : ℕ) (F : P.Carrier) :
    (n • F).val = n • F.val := rfl

@[simp] theorem Carrier.val_zsmul (P : D.OSPreHilbertData) (n : ℤ) (F : P.Carrier) :
    (n • F).val = n • F.val := rfl

@[simp] theorem Carrier.val_smul (P : D.OSPreHilbertData) (r : ℝ) (F : P.Carrier) :
    (r • F).val = r • F.val := rfl

theorem Carrier.val_injective (P : D.OSPreHilbertData) :
    Function.Injective (@Carrier.val S D P) := by
  intro F G h
  cases F
  cases G
  cases h
  rfl

instance carrierAddCommGroup (P : D.OSPreHilbertData) : AddCommGroup P.Carrier :=
  Function.Injective.addCommGroup Carrier.val (Carrier.val_injective P)
    (Carrier.val_zero P) (Carrier.val_add P) (Carrier.val_neg P)
    (Carrier.val_sub P) (Carrier.val_nsmul P) (Carrier.val_zsmul P)

instance carrierModule (P : D.OSPreHilbertData) : Module ℝ P.Carrier :=
  Function.Injective.module ℝ
    ⟨⟨Carrier.val, Carrier.val_zero P⟩, Carrier.val_add P⟩
    (Carrier.val_injective P) (Carrier.val_smul P)

/-- The canonical linear identification with the original positive-time
observable module. -/
noncomputable def toPositiveTime (P : D.OSPreHilbertData) :
    P.Carrier ≃ₗ[ℝ] D.positiveTimeSubalgebra.toSubmodule where
  toFun := Carrier.val
  invFun := Carrier.mk
  left_inv F := by cases F; rfl
  right_inv F := rfl
  map_add' F G := Carrier.val_add P F G
  map_smul' r F := Carrier.val_smul P r F

@[simp] theorem toPositiveTime_apply (P : D.OSPreHilbertData) (F : P.Carrier) :
    P.toPositiveTime F = F.val := rfl

@[simp] theorem toPositiveTime_symm_apply
    (P : D.OSPreHilbertData)
    (F : D.positiveTimeSubalgebra.toSubmodule) :
    P.toPositiveTime.symm F = ⟨F⟩ := rfl

/-- The positive semidefinite OS form as a Mathlib pre-inner-product core. -/
@[reducible] noncomputable def core (P : D.OSPreHilbertData) :
    PreInnerProductSpace.Core ℝ P.Carrier where
  inner F G := D.osBilinForm P.omega (P.toPositiveTime F) (P.toPositiveTime G)
  conj_inner_symm F G := by
    change D.osBilinForm P.omega (P.toPositiveTime G) (P.toPositiveTime F) =
      D.osBilinForm P.omega (P.toPositiveTime F) (P.toPositiveTime G)
    exact (D.osBilinForm_isSymm P.omega P.reflectionInvariant).eq
      (P.toPositiveTime G) (P.toPositiveTime F)
  re_inner_nonneg F := by
    change 0 ≤ D.osBilinForm P.omega (P.toPositiveTime F) (P.toPositiveTime F)
    exact (D.osBilinForm_isNonneg P.omega P.reflectionPositive).nonneg
      (P.toPositiveTime F)
  add_left F G H := by
    simp
  smul_left F G r := by
    simp

/-- The OS core induces exactly the seminormed additive structure used in
Mathlib's GNS construction. -/
noncomputable instance carrierSeminormedAddCommGroup
    (P : D.OSPreHilbertData) : SeminormedAddCommGroup P.Carrier :=
  InnerProductSpace.Core.toSeminormedAddCommGroup (c := P.core)

/-- The same OS core supplies the compatible real inner-product-space
structure. -/
noncomputable instance carrierInnerProductSpace
    (P : D.OSPreHilbertData) : InnerProductSpace ℝ P.Carrier :=
  InnerProductSpace.ofCore P.core

/-- The inner product on the opaque carrier is definitionally the reflected
continuum expectation. -/
@[simp] theorem inner_eq_osBilinForm
    (P : D.OSPreHilbertData) (F G : P.Carrier) :
    inner ℝ F G =
      D.osBilinForm P.omega (P.toPositiveTime F) (P.toPositiveTime G) := by
  rfl

/-- The OS null vectors form a real linear subspace. -/
def nullSubmodule (P : D.OSPreHilbertData) : Submodule ℝ P.Carrier where
  carrier := {F | ‖F‖ = 0}
  zero_mem' := norm_zero
  add_mem' := by
    intro F G hF hG
    apply le_antisymm
    · calc
        ‖F + G‖ ≤ ‖F‖ + ‖G‖ := norm_add_le F G
        _ = 0 := by rw [hF, hG]; simp
    · exact norm_nonneg _
  smul_mem' := by
    intro r F hF
    change ‖r • F‖ = 0
    rw [norm_smul, hF, mul_zero]

@[simp] theorem mem_nullSubmodule
    (P : D.OSPreHilbertData) (F : P.Carrier) :
    F ∈ P.nullSubmodule ↔ ‖F‖ = 0 :=
  Iff.rfl

/-- The OS null condition is exactly vanishing of the reflected quadratic
expectation. -/
theorem mem_nullSubmodule_iff_osQuadratic_eq_zero
    (P : D.OSPreHilbertData) (F : P.Carrier) :
    F ∈ P.nullSubmodule ↔
      D.osBilinForm P.omega (P.toPositiveTime F) (P.toPositiveTime F) = 0 := by
  rw [P.mem_nullSubmodule]
  constructor
  · intro hF
    calc
      D.osBilinForm P.omega (P.toPositiveTime F) (P.toPositiveTime F) =
          inner ℝ F F := by rw [P.inner_eq_osBilinForm]
      _ = ‖F‖ ^ 2 := real_inner_self_eq_norm_sq F
      _ = 0 := by rw [hF]; simp
  · intro hF
    have hsq : ‖F‖ ^ 2 = 0 := by
      rw [← real_inner_self_eq_norm_sq F, P.inner_eq_osBilinForm]
      exact hF
    exact sq_eq_zero_iff.mp hsq

/-- The separated OS pre-Hilbert space.  Mathlib's `SeparationQuotient`
identifies precisely the vectors invisible to the OS seminorm. -/
abbrev Separated (P : D.OSPreHilbertData) : Type :=
  SeparationQuotient P.Carrier

/-- The completed physical OS Hilbert carrier. -/
def PhysicalHilbert (P : D.OSPreHilbertData) : Type :=
  UniformSpace.Completion P.Separated

noncomputable instance physicalHilbertNormedAddCommGroup
    (P : D.OSPreHilbertData) : NormedAddCommGroup P.PhysicalHilbert := by
  change NormedAddCommGroup (UniformSpace.Completion P.Separated)
  exact UniformSpace.Completion.instNormedAddCommGroup P.Separated

noncomputable instance physicalHilbertInnerProductSpace
    (P : D.OSPreHilbertData) : InnerProductSpace ℝ P.PhysicalHilbert := by
  change InnerProductSpace ℝ (UniformSpace.Completion P.Separated)
  exact UniformSpace.Completion.innerProductSpace

noncomputable instance physicalHilbertCompleteSpace
    (P : D.OSPreHilbertData) : CompleteSpace P.PhysicalHilbert := by
  change CompleteSpace (UniformSpace.Completion P.Separated)
  exact UniformSpace.Completion.completeSpace P.Separated

/-- The OS class of a positive-time observable before Hilbert completion. -/
def osClass (P : D.OSPreHilbertData) (F : P.Carrier) : P.Separated :=
  SeparationQuotient.mk F

/-- The dense physical vector represented by a positive-time observable. -/
def physicalState (P : D.OSPreHilbertData) (F : P.Carrier) : P.PhysicalHilbert := by
  change UniformSpace.Completion P.Separated
  exact (P.osClass F : UniformSpace.Completion P.Separated)

/-- The separated OS quotient is dense in the completed physical carrier. -/
theorem separated_dense_in_physical (P : D.OSPreHilbertData) :
    DenseRange
      (fun x : P.Separated =>
        (x : UniformSpace.Completion P.Separated)) :=
  UniformSpace.Completion.denseRange_coe

end PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

/-- The actual continuum even-periodic Wilson state supplies all data required
for the OS null quotient and Hilbert completion. -/
noncomputable def physical_yang_mills_evenPeriodicWilsonOS_continuum_preHilbertData
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)) :
    D.OSPreHilbertData :=
  { omega := physicalYangMillsContinuumGaugeInvariantWeakStarState S
    reflectionInvariant :=
      physical_yang_mills_gaugeInvariantWeakStarReflectionInvariance_passes_to_limit
        S D hInvariant
    reflectionPositive :=
      physical_yang_mills_evenPeriodicWilsonOS_continuum_weakStarReflectionPositive
        S D halfExtent N hN beta hbeta B }

/-- The actual continuum Wilson OS state therefore has a complete real Hilbert
space obtained canonically from positive-time gauge-invariant observables. -/
theorem physical_yang_mills_evenPeriodicWilsonOS_continuum_physicalHilbert_complete
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)) :
    CompleteSpace
      (physical_yang_mills_evenPeriodicWilsonOS_continuum_preHilbertData
        S D halfExtent N hN beta hbeta B hInvariant).PhysicalHilbert := by
  infer_instance

end

end MathlibAnalytic
end MGAP4D
