import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSCanonicalBoundaryTransferGlobalNorm
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSApproximatingVacuumOrthogonalSemigroup
import Mathlib.Analysis.Normed.Operator.Basic
import Mathlib.Tactic

noncomputable section

open Filter MeasureTheory Set Topology
open scoped InnerProductSpace InnerProduct

namespace MGAP4D
namespace MathlibAnalytic

local instance canonicalBoundaryVacuumOrthogonalSideLengthNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance canonicalBoundaryVacuumOrthogonalSpecialUnitaryIsTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance canonicalBoundaryVacuumOrthogonalSpecialUnitaryCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance canonicalBoundaryVacuumOrthogonalSpecialUnitarySecondCountableTopology (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance canonicalBoundaryVacuumOrthogonalSpecialUnitaryMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance canonicalBoundaryVacuumOrthogonalSpecialUnitaryBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

namespace PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {B : PhysicalYangMillsEvenPeriodicWilsonOSWeakStarBridge
      S D halfExtent N hN beta hbeta}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant}

/-- The one-dimensional line generated by the normalized canonical boundary
vacuum. -/
def canonicalBoundaryVacuumLine
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (n : ℕ) :
    Submodule ℝ
      (PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N) :=
  ℝ ∙ L.canonicalBoundaryVacuum n

/-- The canonical shared-boundary excitation sector.  This is the orthogonal
complement of the boundary vacuum line, and is the correct carrier for any
strict boundary-transfer estimate. -/
def canonicalBoundaryVacuumOrthogonal
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (n : ℕ) :
    Submodule ℝ
      (PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N) :=
  (L.canonicalBoundaryVacuumLine n)ᗮ

/-- The boundary excitation sector as a Hilbert-space carrier. -/
abbrev CanonicalBoundaryVacuumOrthogonalHilbert
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (n : ℕ) : Type :=
  L.canonicalBoundaryVacuumOrthogonal n

instance canonicalBoundaryVacuumOrthogonalCompleteSpace
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (n : ℕ) :
    CompleteSpace (L.CanonicalBoundaryVacuumOrthogonalHilbert n) := by
  change CompleteSpace ↥(L.canonicalBoundaryVacuumLine n)ᗮ
  exact Submodule.instOrthogonalCompleteSpace (L.canonicalBoundaryVacuumLine n)

/-- Boundary excitation membership is exactly orthogonality to the normalized
canonical boundary vacuum. -/
theorem mem_canonicalBoundaryVacuumOrthogonal_iff
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (n : ℕ)
    (v : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N) :
    v ∈ L.canonicalBoundaryVacuumOrthogonal n ↔
      inner ℝ (L.canonicalBoundaryVacuum n) v = 0 := by
  simpa [canonicalBoundaryVacuumOrthogonal, canonicalBoundaryVacuumLine] using
    (Submodule.mem_orthogonal_singleton_iff_inner_right
      (𝕜 := ℝ) (u := L.canonicalBoundaryVacuum n) (v := v))

/-- The completed physical-to-boundary isometry sends the physical
vacuum-orthogonal sector into the canonical boundary excitation sector. -/
theorem completedLinearIsometry_mem_canonicalBoundaryVacuumOrthogonal
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (n : ℕ)
    (psi : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingHilbert
      S D halfExtent N hN beta hbeta B hInvariant n)
    (hpsi :
      psi ∈
        (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
          S D halfExtent N hN beta hbeta B hInvariant n).vacuumOrthogonal) :
    L.completedLinearIsometry n psi ∈
      L.canonicalBoundaryVacuumOrthogonal n := by
  let Pn :=
    physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
      S D halfExtent N hN beta hbeta B hInvariant n
  rw [L.mem_canonicalBoundaryVacuumOrthogonal_iff]
  rw [canonicalBoundaryVacuum, (L.completedLinearIsometry n).inner_map_map]
  exact (Pn.mem_vacuumOrthogonal_iff psi).mp hpsi

/-- Conversely, the adjoint of the completed boundary isometry sends every
boundary excitation back into the physical vacuum-orthogonal sector. -/
theorem completedLinearIsometry_adjoint_mem_vacuumOrthogonal
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (n : ℕ)
    (v : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N)
    (hv : v ∈ L.canonicalBoundaryVacuumOrthogonal n) :
    (((L.completedLinearIsometry n).toContinuousLinearMap)†) v ∈
      (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta B hInvariant n).vacuumOrthogonal := by
  let Pn :=
    physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
      S D halfExtent N hN beta hbeta B hInvariant n
  rw [Pn.mem_vacuumOrthogonal_iff]
  rw [ContinuousLinearMap.adjoint_inner_right]
  simpa [canonicalBoundaryVacuum] using
    (L.mem_canonicalBoundaryVacuumOrthogonal_iff n v).mp hv

/-- Restriction of the completed physical-to-boundary isometry to the complete
vacuum-orthogonal sectors. -/
noncomputable def completedVacuumOrthogonalLinearIsometry
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (n : ℕ) :
    (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta B hInvariant n).VacuumOrthogonalHilbert →ₗᵢ[ℝ]
      L.CanonicalBoundaryVacuumOrthogonalHilbert n where
  toLinearMap :=
    { toFun := fun psi =>
        ⟨L.completedLinearIsometry n
            (psi : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingHilbert
              S D halfExtent N hN beta hbeta B hInvariant n),
          L.completedLinearIsometry_mem_canonicalBoundaryVacuumOrthogonal
            n psi psi.property⟩
      map_add' := by
        intro x y
        apply Subtype.ext
        simp
      map_smul' := by
        intro c x
        apply Subtype.ext
        simp }
  norm_map' := by
    intro psi
    simpa using
      (L.completedLinearIsometry n).norm_map
        (psi : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingHilbert
          S D halfExtent N hN beta hbeta B hInvariant n)

@[simp] theorem completedVacuumOrthogonalLinearIsometry_coe
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (n : ℕ)
    (psi :
      (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta B hInvariant n).VacuumOrthogonalHilbert) :
    ((L.completedVacuumOrthogonalLinearIsometry n psi :
        L.CanonicalBoundaryVacuumOrthogonalHilbert n) :
      PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N) =
      L.completedLinearIsometry n psi := by
  rfl

/-- Reflection/time exchange makes the canonical boundary transfer preserve the
boundary excitation sector.  No quantitative decay estimate is used here. -/
theorem canonicalBoundaryTransfer_mem_canonicalBoundaryVacuumOrthogonal
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant)
    (hExchange : ∀ n,
      PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
        (C.toPositiveTimeObservableContractionSemigroup n))
    (n : ℕ) (t : NNReal)
    (v : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N)
    (hv : v ∈ L.canonicalBoundaryVacuumOrthogonal n) :
    L.canonicalBoundaryTransfer C n t v ∈
      L.canonicalBoundaryVacuumOrthogonal n := by
  let Pn :=
    physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
      S D halfExtent N hN beta hbeta B hInvariant n
  let J := L.completedLinearIsometry n
  let Jadj :
      PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N →L[ℝ]
        PhysicalYangMillsEvenPeriodicWilsonOSApproximatingHilbert
          S D halfExtent N hN beta hbeta B hInvariant n :=
    (J.toContinuousLinearMap)†
  have hAdj : Jadj v ∈ Pn.vacuumOrthogonal := by
    dsimp [Jadj, J]
    exact L.completedLinearIsometry_adjoint_mem_vacuumOrthogonal n v hv
  have hSymmetric :
      (C.finitePhysicalSemigroup n).IsInnerSymmetric :=
    (hExchange n).toPhysicalSemigroup_isInnerSymmetric
  have hT :
      C.finiteOperator n (t / 2) (Jadj v) ∈ Pn.vacuumOrthogonal := by
    exact
      PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PhysicalSemigroup.operator_mem_vacuumOrthogonal
        (C.finitePhysicalSemigroup n) hSymmetric (t / 2) (Jadj v) hAdj
  change J (C.finiteOperator n (t / 2) (Jadj v)) ∈
    L.canonicalBoundaryVacuumOrthogonal n
  exact
    L.completedLinearIsometry_mem_canonicalBoundaryVacuumOrthogonal
      n (C.finiteOperator n (t / 2) (Jadj v)) hT

/-- Algebraic restriction of the actual canonical boundary transfer to the
vacuum-orthogonal boundary sector. -/
noncomputable def canonicalBoundaryVacuumOrthogonalTransferLinearMap
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant)
    (hExchange : ∀ n,
      PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
        (C.toPositiveTimeObservableContractionSemigroup n))
    (n : ℕ) (t : NNReal) :
    L.CanonicalBoundaryVacuumOrthogonalHilbert n →ₗ[ℝ]
      L.CanonicalBoundaryVacuumOrthogonalHilbert n where
  toFun := fun v =>
    ⟨L.canonicalBoundaryTransfer C n t
        (v : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N),
      L.canonicalBoundaryTransfer_mem_canonicalBoundaryVacuumOrthogonal
        C hExchange n t v v.property⟩
  map_add' := by
    intro x y
    apply Subtype.ext
    simp
  map_smul' := by
    intro c x
    apply Subtype.ext
    simp

/-- The actual canonical boundary transfer restricted to the complete
vacuum-orthogonal boundary sector.  Continuity is obtained from the already
proved ambient contraction, avoiding any dependency on version-specific
continuous-linear-map restriction helpers. -/
noncomputable def canonicalBoundaryVacuumOrthogonalTransfer
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant)
    (hExchange : ∀ n,
      PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
        (C.toPositiveTimeObservableContractionSemigroup n))
    (n : ℕ) (t : NNReal) :
    L.CanonicalBoundaryVacuumOrthogonalHilbert n →L[ℝ]
      L.CanonicalBoundaryVacuumOrthogonalHilbert n :=
  (L.canonicalBoundaryVacuumOrthogonalTransferLinearMap C hExchange n t).mkContinuous
    1
    (by
      intro v
      change
        ‖L.canonicalBoundaryTransfer C n t
            (v : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N)‖ ≤
          1 * ‖(v : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N)‖
      simpa using
        L.canonicalBoundaryTransfer_norm_le C n t
          (v : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N))

@[simp] theorem canonicalBoundaryVacuumOrthogonalTransfer_coe
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant)
    (hExchange : ∀ n,
      PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
        (C.toPositiveTimeObservableContractionSemigroup n))
    (n : ℕ) (t : NNReal)
    (v : L.CanonicalBoundaryVacuumOrthogonalHilbert n) :
    ((L.canonicalBoundaryVacuumOrthogonalTransfer C hExchange n t v :
        L.CanonicalBoundaryVacuumOrthogonalHilbert n) :
      PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N) =
      L.canonicalBoundaryTransfer C n t v := by
  rfl

/-- The restricted canonical boundary transfer remains contractive. -/
theorem canonicalBoundaryVacuumOrthogonalTransfer_norm_le
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant)
    (hExchange : ∀ n,
      PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
        (C.toPositiveTimeObservableContractionSemigroup n))
    (n : ℕ) (t : NNReal)
    (v : L.CanonicalBoundaryVacuumOrthogonalHilbert n) :
    ‖L.canonicalBoundaryVacuumOrthogonalTransfer C hExchange n t v‖ ≤ ‖v‖ := by
  change
    ‖L.canonicalBoundaryTransfer C n t
      (v : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N)‖ ≤
      ‖(v : PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N)‖
  exact L.canonicalBoundaryTransfer_norm_le C n t v

/-- Operator-norm form of the structural contraction on the excitation sector.
Unlike the full boundary operator, this is the carrier on which a future
model-specific strict bound can consistently hold. -/
theorem canonicalBoundaryVacuumOrthogonalTransfer_opNorm_le
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant)
    (hExchange : ∀ n,
      PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
        (C.toPositiveTimeObservableContractionSemigroup n))
    (n : ℕ) (t : NNReal) :
    ‖L.canonicalBoundaryVacuumOrthogonalTransfer C hExchange n t‖ ≤ 1 := by
  refine ContinuousLinearMap.opNorm_le_bound
    (L.canonicalBoundaryVacuumOrthogonalTransfer C hExchange n t)
    zero_le_one ?_
  intro v
  simpa using
    L.canonicalBoundaryVacuumOrthogonalTransfer_norm_le C hExchange n t v

/-- On physical excitation vectors, the restricted boundary transfer exactly
intertwines with the completed finite Wilson OS transfer. -/
theorem canonicalBoundaryVacuumOrthogonalTransfer_intertwining
    (L : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence
      S D halfExtent N hN beta hbeta B hInvariant)
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta B hInvariant)
    (hExchange : ∀ n,
      PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
        (C.toPositiveTimeObservableContractionSemigroup n))
    (n : ℕ) (t : NNReal)
    (psi :
      (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta B hInvariant n).VacuumOrthogonalHilbert) :
    ((L.canonicalBoundaryVacuumOrthogonalTransfer C hExchange n t
        (L.completedVacuumOrthogonalLinearIsometry n psi) :
      L.CanonicalBoundaryVacuumOrthogonalHilbert n) :
      PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N) =
      L.completedLinearIsometry n
        (C.finiteOperator n (t / 2)
          (psi : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingHilbert
            S D halfExtent N hN beta hbeta B hInvariant n)) := by
  change
    L.canonicalBoundaryTransfer C n t
        (L.completedLinearIsometry n
          (psi : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingHilbert
            S D halfExtent N hN beta hbeta B hInvariant n)) = _
  exact
    L.canonicalBoundaryTransfer_completedLinearIsometry C n t
      (psi : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingHilbert
        S D halfExtent N hN beta hbeta B hInvariant n)

end PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMomentLinearCoherence

end MathlibAnalytic
end MGAP4D

end
