import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSDerivedMassExcitationWitness
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSDenseStateMap
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

open scoped InnerProductSpace

namespace PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

variable {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
variable {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
variable {P : D.OSPreHilbertData}

/-- Strict positivity of the Osterwalder--Schrader quadratic form survives both
the separation quotient and Hilbert completion: the represented physical state
cannot vanish.

This is the strict counterpart of reflection positivity.  It uses only the
exact Mathlib completion inner-product identity, so no additional injectivity
assumption on the observable carrier is introduced. -/
theorem physicalState_ne_zero_of_osQuadratic_pos
    (F : P.Carrier)
    (hpos :
      0 < D.osBilinForm P.omega
        (P.toPositiveTime F) (P.toPositiveTime F)) :
    P.physicalState F ≠ 0 := by
  intro hzero
  have hquadZero :
      D.osBilinForm P.omega
          (P.toPositiveTime F) (P.toPositiveTime F) = 0 := by
    calc
      D.osBilinForm P.omega
          (P.toPositiveTime F) (P.toPositiveTime F) =
          inner ℝ F F := by
        symm
        exact P.inner_eq_osBilinForm F F
      _ = inner ℝ (P.physicalState F) (P.physicalState F) := by
        symm
        exact P.inner_physicalState_physicalState F F
      _ = 0 := by
        rw [hzero]
        exact inner_zero_left
  exact (ne_of_gt hpos) hquadZero

/-- Centering against the OS vacuum observable is exactly enough to put the
completed represented state in the physical vacuum-orthogonal Hilbert sector. -/
theorem physicalState_mem_vacuumOrthogonal_of_centered
    (F : P.Carrier)
    (hcenter : inner ℝ P.vacuumObservable F = 0) :
    P.physicalState F ∈ P.vacuumOrthogonal := by
  rw [P.mem_vacuumOrthogonal_iff]
  change inner ℝ
    (P.physicalState P.vacuumObservable) (P.physicalState F) = 0
  rw [P.inner_physicalState_physicalState]
  exact hcenter

/-- A centered observable with strict OS norm therefore gives an explicit
nonzero vector in the complete physical excitation Hilbert space. -/
noncomputable def vacuumOrthogonalPhysicalState_of_centered
    (F : P.Carrier)
    (hcenter : inner ℝ P.vacuumObservable F = 0) :
    P.VacuumOrthogonalHilbert :=
  ⟨P.physicalState F,
    P.physicalState_mem_vacuumOrthogonal_of_centered F hcenter⟩

/-- The preceding vacuum-orthogonal physical vector is nonzero whenever the OS
quadratic form is strictly positive. -/
theorem vacuumOrthogonalPhysicalState_of_centered_ne_zero
    (F : P.Carrier)
    (hcenter : inner ℝ P.vacuumObservable F = 0)
    (hpos :
      0 < D.osBilinForm P.omega
        (P.toPositiveTime F) (P.toPositiveTime F)) :
    P.vacuumOrthogonalPhysicalState_of_centered F hcenter ≠ 0 := by
  intro hzero
  have hambient : P.physicalState F = 0 := by
    have hcoerce := congrArg
      (fun x : P.VacuumOrthogonalHilbert => (x : P.PhysicalHilbert)) hzero
    simpa [vacuumOrthogonalPhysicalState_of_centered] using hcoerce
  exact (P.physicalState_ne_zero_of_osQuadratic_pos F hpos) hambient

namespace StronglyContinuousPhysicalSemigroup

/-- A centered strictly-positive OS observable is already enough to generate
the nonzero vacuum-orthogonal closed-Hamiltonian-domain witness used by the
physical variational mass.

The only additional inputs are the existing normalized-vacuum and
self-adjointness hypotheses.  Hamiltonian-domain membership is generated by
its dense-domain theorem; it is not imposed on the observable. -/
noncomputable def physicalYangMillsExcitationDomainWitness_of_centered_osQuadratic_pos
    (T : P.StronglyContinuousPhysicalSemigroup)
    (hP : P.IsNormalized)
    (hSelf : IsSelfAdjoint T.closedRightHamiltonian)
    (F : P.Carrier)
    (hcenter : inner ℝ P.vacuumObservable F = 0)
    (hpos :
      0 < D.osBilinForm P.omega
        (P.toPositiveTime F) (P.toPositiveTime F)) :
    T.PhysicalYangMillsExcitationDomainWitness := by
  let phi : P.VacuumOrthogonalHilbert :=
    P.vacuumOrthogonalPhysicalState_of_centered F hcenter
  have hphi : phi ≠ 0 := by
    simpa [phi] using
      P.vacuumOrthogonalPhysicalState_of_centered_ne_zero F hcenter hpos
  exact T.physicalYangMillsExcitationDomainWitness_of_nonzeroExcitation
    hP hSelf phi hphi

end StronglyContinuousPhysicalSemigroup

end PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

end

end MathlibAnalytic
end MGAP4D
