import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonVacuumNormalizedProjectedNonTopFixedModeSubsequence
import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonSUNTwoModeFiniteOSPairTopTopScalarCriterion
import Mathlib.Tactic

/-!
# Exact top-factorization and strong-limit reduction for projected non-top modes

After #5069, one fixed projected mode survives on a strictly increasing scale
subsequence inside one common projective-limit L2 carrier.

The remaining scale dependence comes from the physical TopTop projection. Since
#5013 identifies the completed TopTop block with the single line generated by
the normalized pair-top mode, its orthogonal projection has an exact rank-one
formula.

This file records that formula and transports it through the exact projective
isometry. Consequently the projected non-top continuum image is exactly

  centered common image
    - <pair-top common image, centered common image> * pair-top common image.

Therefore strong convergence of the projected sequence follows from strong
convergence of only two common-carrier sequences:

* the unprojected vacuum-centered pair image;
* the physical pair-top image.

The scalar coefficient needs no independent assumption: it converges
automatically by continuity of the inner product.

No continuum dynamics or transfer intertwining is asserted here.
-/

namespace MGAP4D
namespace MathlibAnalytic

open Filter MeasureTheory Set Topology
open scoped InnerProductSpace InnerProduct

noncomputable section

local instance projectedTopFactorizationTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance projectedTopFactorizationCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance projectedTopFactorizationSecondCountable (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance projectedTopFactorizationMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance projectedTopFactorizationBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

local instance projectedTopFactorizationSpatialLinkFintype (H : ℕ) :
    Fintype (PeriodicHypercubicEvenSpatialSliceLink H) :=
  Fintype.ofFinite _

local instance projectedTopFactorizationSpatialHaarSFinite (H N : ℕ) :
    SFinite (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure H N) := by
  unfold periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure
  infer_instance

local instance projectedTopFactorizationTopTopCompleteSpace
    (H N : ℕ) (hN : 0 < N) (beta : ℝ) (hbeta : 0 ≤ beta) :
    CompleteSpace
      (periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure
        H N hN beta hbeta) := by
  let PairE :=
    PeriodicHypercubicEvenSpecialUnitarySpatialSlicePairHaarL2 H N
  let PairT :=
    periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure
      H N hN beta hbeta
  have hclosed : IsClosed (PairT : Set PairE) := by
    change IsClosed
      ((((periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockSpan
        H N hN beta hbeta).topologicalClosure : Submodule ℝ PairE) : Set PairE))
    exact Submodule.isClosed_topologicalClosure _
  exact hclosed.completeSpace_coe

section ProjectedTopFactorization

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ} {hN : 0 < N} {hN2 : 2 ≤ N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ} {hbeta : ∀ n, 0 ≤ beta n}
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    {F : EuclideanYangMillsProjectiveCylinderFamily}
    (R : PhysicalYangMillsEvenPeriodicWilsonOSBoundaryMarginalProjectiveReadout
      Q F)
    (L : EuclideanYangMillsProjectiveLimitMeasure F)

/-- Scalar coefficient of the actual vacuum-normalized centered pair along the
selected physical pair-top line. -/
noncomputable def
    physicalYangMillsVacuumNormalizedSUNTwoModeProjectedTopCoefficient
    (k : Fin 2) (n : ℕ) : ℝ :=
  inner ℝ
    (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
      (halfExtent n) N hN (beta n) (hbeta n))
    (physicalYangMillsSUNTwoModeExplicitCenteredBoundaryPairL2
      (S := S) (D := D) (halfExtent := halfExtent)
      (N := N) (hN := hN) (hN2 := hN2)
      (beta := beta) (hbeta := hbeta)
      (Q := Q.vacuumNormalized) (hInvariant := hInvariant) k n)

/-- Common-carrier image of the unprojected actual vacuum-normalized centered
pair. -/
noncomputable def
    physicalYangMillsVacuumNormalizedSUNTwoModeCenteredPairContinuumImage
    (k : Fin 2) (n : ℕ) :
    Lp ℝ 2 L.continuumMeasure :=
  R.spatialSlicePairHaarProjectiveContinuumL2Isometry L n
    (physicalYangMillsSUNTwoModeExplicitCenteredBoundaryPairL2
      (S := S) (D := D) (halfExtent := halfExtent)
      (N := N) (hN := hN) (hN2 := hN2)
      (beta := beta) (hbeta := hbeta)
      (Q := Q.vacuumNormalized) (hInvariant := hInvariant) k n)

/-- Common-carrier image of the normalized physical pair-top mode. -/
noncomputable def
    physicalYangMillsSUNPhysicalPairTopContinuumImage
    (n : ℕ) :
    Lp ℝ 2 L.continuumMeasure :=
  R.spatialSlicePairHaarProjectiveContinuumL2Isometry L n
    (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
      (halfExtent n) N hN (beta n) (hbeta n))

/-- The finite physical TopTop projection is exactly the rank-one coefficient
against the normalized pair-top mode. -/
theorem
    physicalYangMillsVacuumNormalizedSUNTwoModeExplicitCenteredBoundaryPairTopProjection_eq_smul_pairTop
    (k : Fin 2) (n : ℕ) :
    physicalYangMillsVacuumNormalizedSUNTwoModeExplicitCenteredBoundaryPairTopProjection
        (hN2 := hN2) (Q := Q) (hInvariant := hInvariant) k n =
      physicalYangMillsVacuumNormalizedSUNTwoModeProjectedTopCoefficient
          (hN2 := hN2) Q hInvariant k n •
        periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
          (halfExtent n) N hN (beta n) (hbeta n) := by
  let TT :=
    periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure
      (halfExtent n) N hN (beta n) (hbeta n)
  let top :=
    periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
      (halfExtent n) N hN (beta n) (hbeta n)
  let x :=
    physicalYangMillsSUNTwoModeExplicitCenteredBoundaryPairL2
      (S := S) (D := D) (halfExtent := halfExtent)
      (N := N) (hN := hN) (hN2 := hN2)
      (beta := beta) (hbeta := hbeta)
      (Q := Q.vacuumNormalized) (hInvariant := hInvariant) k n
  let a : ℝ := inner ℝ top x
  have hTT : TT = ℝ ∙ top := by
    simpa [TT, top] using
      periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure_eq_span_pairTopMode
        (halfExtent n) N hN (beta n) (hbeta n)
  have htopMem : a • top ∈ TT := by
    rw [hTT]
    exact
      Submodule.smul_mem (ℝ ∙ top) a
        (Submodule.mem_span_singleton_self top)
  have hresOrth : x - a • top ∈ TTᗮ := by
    rw [
      periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure_orthogonal_mem_iff_pairTopMode_inner_eq_zero
        (halfExtent n) N hN (beta n) (hbeta n)]
    dsimp [a, top]
    rw [inner_sub_right, real_inner_smul_right,
      real_inner_self_eq_norm_sq,
      periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2_norm]
    ring
  have hproj :
      TT.starProjection x = a • top :=
    Submodule.eq_starProjection_of_mem_orthogonal htopMem hresOrth
  simpa [
    TT, top, x, a,
    physicalYangMillsVacuumNormalizedSUNTwoModeExplicitCenteredBoundaryPairTopProjection,
    physicalYangMillsVacuumNormalizedSUNTwoModeProjectedTopCoefficient
  ] using hproj

/-- The finite scalar coefficient is exactly the inner product of the two
corresponding common-carrier images. -/
theorem
    physicalYangMillsVacuumNormalizedSUNTwoModeProjectedTopCoefficient_eq_common_inner
    (k : Fin 2) (n : ℕ) :
    physicalYangMillsVacuumNormalizedSUNTwoModeProjectedTopCoefficient
        (hN2 := hN2) Q hInvariant k n =
      inner ℝ
        (physicalYangMillsSUNPhysicalPairTopContinuumImage
          (Q := Q) R L n)
        (physicalYangMillsVacuumNormalizedSUNTwoModeCenteredPairContinuumImage
          (hN2 := hN2) Q hInvariant R L k n) := by
  symm
  exact
    R.spatialSlicePairHaarProjectiveContinuumL2Isometry_inner L n
      (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
        (halfExtent n) N hN (beta n) (hbeta n))
      (physicalYangMillsSUNTwoModeExplicitCenteredBoundaryPairL2
        (S := S) (D := D) (halfExtent := halfExtent)
        (N := N) (hN := hN) (hN2 := hN2)
        (beta := beta) (hbeta := hbeta)
        (Q := Q.vacuumNormalized) (hInvariant := hInvariant) k n)

/-- Exact common-carrier rank-one factorization of the canonical projected
physical non-top excitation. -/
theorem
    physicalYangMillsVacuumNormalizedSUNTwoModeProjectedNonTopContinuumImage_eq_centered_sub_inner_smul_top
    (k : Fin 2) (n : ℕ) :
    physicalYangMillsVacuumNormalizedSUNTwoModeProjectedNonTopContinuumImage
        (hN2 := hN2) Q hInvariant R L k n =
      physicalYangMillsVacuumNormalizedSUNTwoModeCenteredPairContinuumImage
          (hN2 := hN2) Q hInvariant R L k n -
        inner ℝ
          (physicalYangMillsSUNPhysicalPairTopContinuumImage
            (Q := Q) R L n)
          (physicalYangMillsVacuumNormalizedSUNTwoModeCenteredPairContinuumImage
            (hN2 := hN2) Q hInvariant R L k n) •
          physicalYangMillsSUNPhysicalPairTopContinuumImage
            (Q := Q) R L n := by
  let TT :=
    periodicHypercubicEvenSpecialUnitaryPhysicalPairTopTopBlockClosure
      (halfExtent n) N hN (beta n) (hbeta n)
  let x :=
    physicalYangMillsSUNTwoModeExplicitCenteredBoundaryPairL2
      (S := S) (D := D) (halfExtent := halfExtent)
      (N := N) (hN := hN) (hN2 := hN2)
      (beta := beta) (hbeta := hbeta)
      (Q := Q.vacuumNormalized) (hInvariant := hInvariant) k n
  let I := R.spatialSlicePairHaarProjectiveContinuumL2Isometry L n
  change I ((TTᗮ).starProjection x) =
    I x -
      inner ℝ
        (I
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
            (halfExtent n) N hN (beta n) (hbeta n)))
        (I x) •
      I
        (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
          (halfExtent n) N hN (beta n) (hbeta n))
  rw [Submodule.starProjection_orthogonal_val (K := TT)]
  rw [map_sub]
  have htop :=
    physicalYangMillsVacuumNormalizedSUNTwoModeExplicitCenteredBoundaryPairTopProjection_eq_smul_pairTop
      (hN2 := hN2) Q hInvariant k n
  have htop' :
      TT.starProjection x =
        physicalYangMillsVacuumNormalizedSUNTwoModeProjectedTopCoefficient
            (hN2 := hN2) Q hInvariant k n •
          periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
            (halfExtent n) N hN (beta n) (hbeta n) := by
    simpa [
      TT, x,
      physicalYangMillsVacuumNormalizedSUNTwoModeExplicitCenteredBoundaryPairTopProjection
    ] using htop
  have hcoeff :
      physicalYangMillsVacuumNormalizedSUNTwoModeProjectedTopCoefficient
          (hN2 := hN2) Q hInvariant k n =
        inner ℝ
          (I
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
              (halfExtent n) N hN (beta n) (hbeta n)))
          (I x) := by
    simpa [
      I, x,
      physicalYangMillsSUNPhysicalPairTopContinuumImage,
      physicalYangMillsVacuumNormalizedSUNTwoModeCenteredPairContinuumImage
    ] using
      (physicalYangMillsVacuumNormalizedSUNTwoModeProjectedTopCoefficient_eq_common_inner
        (hN2 := hN2) Q hInvariant R L k n)
  have hprojI :
      I (TT.starProjection x) =
        inner ℝ
          (I
            (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
              (halfExtent n) N hN (beta n) (hbeta n)))
          (I x) •
        I
          (periodicHypercubicEvenSpecialUnitaryPhysicalOneSlabPairTopModeL2
            (halfExtent n) N hN (beta n) (hbeta n)) := by
    rw [htop', map_smul, hcoeff]
  rw [hprojI]

/-- Strong convergence of the two moving common-carrier vectors automatically
gives strong convergence of the canonical projected non-top excitation.

The scalar top coefficient converges by continuity of the inner product, so no
separate scalar convergence hypothesis remains. -/
theorem
    physicalYangMillsVacuumNormalizedSUNTwoModeProjectedNonTopContinuumImage_tendsto_of_centered_top_tendsto
    (k : Fin 2)
    (scale : ℕ → ℕ)
    (centeredLimit topLimit : Lp ℝ 2 L.continuumMeasure)
    (hCentered :
      Tendsto
        (fun j =>
          physicalYangMillsVacuumNormalizedSUNTwoModeCenteredPairContinuumImage
            (hN2 := hN2) Q hInvariant R L k (scale j))
        atTop (𝓝 centeredLimit))
    (hTop :
      Tendsto
        (fun j =>
          physicalYangMillsSUNPhysicalPairTopContinuumImage
            (Q := Q) R L (scale j))
        atTop (𝓝 topLimit)) :
    Tendsto
      (fun j =>
        physicalYangMillsVacuumNormalizedSUNTwoModeProjectedNonTopContinuumImage
          (hN2 := hN2) Q hInvariant R L k (scale j))
      atTop
      (𝓝
        (centeredLimit -
          inner ℝ topLimit centeredLimit • topLimit)) := by
  have hCoeff :
      Tendsto
        (fun j =>
          inner ℝ
            (physicalYangMillsSUNPhysicalPairTopContinuumImage
              (Q := Q) R L (scale j))
            (physicalYangMillsVacuumNormalizedSUNTwoModeCenteredPairContinuumImage
              (hN2 := hN2) Q hInvariant R L k (scale j)))
        atTop
        (𝓝 (inner ℝ topLimit centeredLimit)) :=
    hTop.inner hCentered
  have hTopTerm :
      Tendsto
        (fun j =>
          inner ℝ
              (physicalYangMillsSUNPhysicalPairTopContinuumImage
                (Q := Q) R L (scale j))
              (physicalYangMillsVacuumNormalizedSUNTwoModeCenteredPairContinuumImage
                (hN2 := hN2) Q hInvariant R L k (scale j)) •
            physicalYangMillsSUNPhysicalPairTopContinuumImage
              (Q := Q) R L (scale j))
        atTop
        (𝓝 (inner ℝ topLimit centeredLimit • topLimit)) :=
    hCoeff.smul hTop
  have hSub := hCentered.sub hTopTerm
  apply hSub.congr'
  filter_upwards with j
  exact
    (physicalYangMillsVacuumNormalizedSUNTwoModeProjectedNonTopContinuumImage_eq_centered_sub_inner_smul_top
      (hN2 := hN2) Q hInvariant R L k (scale j)).symm

end ProjectedTopFactorization

end

end MathlibAnalytic
end MGAP4D
