import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSFilterVaryingShiftRhsDefectGraphLimit

namespace MGAP4D
namespace MathlibAnalytic

#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.StronglyContinuousPhysicalSemigroup.VacuumSemigroupGapSlope.approximateShiftedAdmissibleRescaledDefect_varyingShiftRhs_filter_graph_tendsto_continuumResolventGraphPoint

end MathlibAnalytic
end MGAP4D
