import MGAP4D.MathlibAnalytic.PeriodicHypercubicSpecialUnitaryDiscretePhysicalTemporalAction
import MGAP4D.MathlibAnalytic.PhysicalYangMillsOrientedDenseTemporalApproximation

namespace MGAP4D
namespace MathlibAnalytic

#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.PhysicalDiscreteTemporalAction
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation.WeakLimitContinuity
#check periodicHypercubicPhysicalLatticeTime
#check periodicHypercubicSpecialUnitaryDiscretePhysicalTemporalAction
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.PhysicalDiscreteTemporalAction.embeddedMeasure_map_latticeTime_eq_self
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation.WeakLimitContinuity.continuumMeasure_map_eq_self

end MathlibAnalytic
end MGAP4D
