import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSPhysicalTransferModeBoundaryClosure

noncomputable section

open Filter MeasureTheory Set Topology
open scoped InnerProductSpace InnerProduct

namespace MGAP4D
namespace MathlibAnalytic

local instance physicalTransferModePositiveHalfSynthesisClosureSideLengthNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance physicalTransferModePositiveHalfSynthesisClosureSpecialUnitaryIsTopologicalGroup
    (N : ℕ) : IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance physicalTransferModePositiveHalfSynthesisClosureSpecialUnitaryCompactSpace
    (N : ℕ) : CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance physicalTransferModePositiveHalfSynthesisClosureSpecialUnitarySecondCountableTopology
    (N : ℕ) : SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance physicalTransferModePositiveHalfSynthesisClosureSpecialUnitaryMeasurableSpace
    (N : ℕ) : MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance physicalTransferModePositiveHalfSynthesisClosureSpecialUnitaryBorelSpace
    (N : ℕ) : BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

namespace PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}

/-- The completed physical OS boundary image is exactly the closure of the
actual Wilson adjoint-synthesis outputs generated by the coherent positive-half
`L²` pullback.

This rewrites the canonical-moment closure theorem in the physically concrete
factorized form

`range Ĵ_n = closure { A_φ† (U_F) | F in the OS carrier }`.

No surjectivity of either `U` or `A_φ†` onto an ambient `L²` space is asserted. -/
theorem range_physicalHilbertBoundaryMomentLinearIsometry_eq_closure_actualSynthesis_positiveHalf
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (n : ℕ) :
    Set.range (Q.physicalHilbertBoundaryMomentLinearIsometry hInvariant n) =
      closure (Set.range (fun F :
        (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
          S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier =>
        physicalYangMillsEvenPeriodicWilsonOSActualBoundarySynthesisOperator
          halfExtent N hN beta hbeta n
          (Q.positiveHalfL2LinearMap hInvariant n F))) := by
  rw [Q.range_physicalHilbertBoundaryMomentLinearIsometry_eq_closure_canonicalBoundaryMoment]
  congr 1
  ext x
  constructor
  · rintro ⟨F, rfl⟩
    refine ⟨F, ?_⟩
    rw [physicalYangMillsEvenPeriodicWilsonOSCanonicalBoundaryMomentL2_eq_actualSynthesis,
      Q.positiveHalfL2LinearMap_apply]
  · rintro ⟨F, rfl⟩
    refine ⟨F, ?_⟩
    rw [physicalYangMillsEvenPeriodicWilsonOSCanonicalBoundaryMomentL2_eq_actualSynthesis,
      Q.positiveHalfL2LinearMap_apply]

/-- If an open-half `L²` vector lies in the closure of the actual coherent
positive-half pullback range, then applying actual Wilson adjoint synthesis
lands in the completed physical OS boundary image.

The proof uses only continuity of `A_φ†` and the preceding exact range-closure
identity. -/
theorem actualBoundarySynthesis_mem_physicalBoundaryImage_of_mem_closure_positiveHalf
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (n : ℕ)
    (u : PhysicalYangMillsEvenPeriodicWilsonOSOpenHalfFeatureL2 halfExtent N n)
    (hu : u ∈ closure (Set.range (fun F :
      (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier =>
      Q.positiveHalfL2LinearMap hInvariant n F))) :
    physicalYangMillsEvenPeriodicWilsonOSActualBoundarySynthesisOperator
        halfExtent N hN beta hbeta n u ∈
      Set.range (Q.physicalHilbertBoundaryMomentLinearIsometry hInvariant n) := by
  rw [Q.range_physicalHilbertBoundaryMomentLinearIsometry_eq_closure_actualSynthesis_positiveHalf]
  let A := physicalYangMillsEvenPeriodicWilsonOSActualBoundarySynthesisOperator
    halfExtent N hN beta hbeta n
  let R := Set.range (fun F :
    (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier =>
    A (Q.positiveHalfL2LinearMap hInvariant n F))
  have hclosed : IsClosed (A ⁻¹' closure R) :=
    isClosed_closure.preimage A.continuous
  have hsubset : Set.range (fun F :
      (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier =>
      Q.positiveHalfL2LinearMap hInvariant n F) ⊆ A ⁻¹' closure R := by
    rintro v ⟨F, rfl⟩
    exact subset_closure ⟨F, rfl⟩
  exact closure_minimal hsubset hclosed hu

/-- Positive-half realization of a one-sided boundary mode by a common
approximating sequence.

The sequence is required to converge before synthesis, both at time zero and
after one unit of actual observable translation.  The endpoint boundary vectors
are then obtained by the already-constructed actual Wilson adjoint synthesis.
This is strictly upstream of `OneSidedBoundaryClosureAt`: boundary-moment
convergence becomes theorem-generated from continuity of synthesis. -/
structure OneSidedPositiveHalfSynthesisClosureAt
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant)
    (n : ℕ)
    (f omega fOne omegaOne : Lp ℝ 2
      (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure
        (halfExtent n) N)) where
  approximants : ℕ →
    (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier
  positiveHalfLimit : PhysicalYangMillsEvenPeriodicWilsonOSOpenHalfFeatureL2
    halfExtent N n
  translatedPositiveHalfLimit : PhysicalYangMillsEvenPeriodicWilsonOSOpenHalfFeatureL2
    halfExtent N n
  positiveHalfTendsto : Tendsto
    (fun k => Q.positiveHalfL2LinearMap hInvariant n (approximants k))
    atTop (𝓝 positiveHalfLimit)
  translatedPositiveHalfTendsto : Tendsto
    (fun k =>
      Q.positiveHalfL2LinearMap hInvariant n
        ((C.toPositiveTimeObservableContractionSemigroup n).carrierTranslation
          1 (approximants k)))
    atTop (𝓝 translatedPositiveHalfLimit)
  synthesisZero :
    physicalYangMillsEvenPeriodicWilsonOSActualBoundarySynthesisOperator
        halfExtent N hN beta hbeta n positiveHalfLimit =
      periodicHypercubicEvenSpecialUnitaryOneSidedBoundaryL2
        (halfExtent n) N f omega
  synthesisOne :
    physicalYangMillsEvenPeriodicWilsonOSActualBoundarySynthesisOperator
        halfExtent N hN beta hbeta n translatedPositiveHalfLimit =
      periodicHypercubicEvenSpecialUnitaryOneSidedBoundaryOneStepL2
        (halfExtent n) N fOne omegaOne

/-- Actual positive-half `L²` closure realization generates the boundary-moment
closure realization used by the finite OS eigenlift. -/
theorem OneSidedPositiveHalfSynthesisClosureAt.toOneSidedBoundaryClosureAt
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant)
    (n : ℕ)
    (f omega fOne omegaOne : Lp ℝ 2
      (periodicHypercubicEvenSpecialUnitarySpatialSliceHaarMeasure
        (halfExtent n) N))
    (W : OneSidedPositiveHalfSynthesisClosureAt
      Q hInvariant C n f omega fOne omegaOne) :
    OneSidedBoundaryClosureAt Q hInvariant C n f omega fOne omegaOne := by
  refine
    { approximants := W.approximants
      momentZero := ?_
      momentOne := ?_ }
  · have h :=
      (physicalYangMillsEvenPeriodicWilsonOSActualBoundarySynthesisOperator
        halfExtent N hN beta hbeta n).continuous.continuousAt.tendsto.comp
        W.positiveHalfTendsto
    rw [W.synthesisZero] at h
    simpa only [
      physicalYangMillsEvenPeriodicWilsonOSCanonicalBoundaryMomentL2_eq_actualSynthesis,
      Q.positiveHalfL2LinearMap_apply] using h
  · have h :=
      (physicalYangMillsEvenPeriodicWilsonOSActualBoundarySynthesisOperator
        halfExtent N hN beta hbeta n).continuous.continuousAt.tendsto.comp
        W.translatedPositiveHalfTendsto
    rw [W.synthesisOne] at h
    simpa only [
      physicalYangMillsEvenPeriodicWilsonOSCanonicalBoundaryMomentL2_eq_actualSynthesis,
      Q.positiveHalfL2LinearMap_apply] using h

/-- Positive-half synthesis closure specialized to the actual normalized
physical one-slice transfer mode and the fixed top/vacuum companion. -/
abbrev PhysicalTransferModePositiveHalfSynthesisClosureAt
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant)
    (n : ℕ)
    (f : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule
      (halfExtent n) N) :=
  OneSidedPositiveHalfSynthesisClosureAt Q hInvariant C n
    (periodicHypercubicEvenSpecialUnitaryPhysicalModeLp
      (halfExtent n) N f)
    (periodicHypercubicEvenSpecialUnitaryPhysicalTopModeLp
      (halfExtent n) N hN (beta n) (hbeta n))
    (periodicHypercubicEvenSpecialUnitaryPhysicalModeOneStepLp
      (halfExtent n) N hN (beta n) (hbeta n) f)
    (periodicHypercubicEvenSpecialUnitaryPhysicalTopModeOneStepLp
      (halfExtent n) N hN (beta n) (hbeta n))

/-- A normalized physical one-slice transfer eigenmode lifts to an actual finite
Wilson OS Hilbert eigenvector from positive-half `L²` closure realization.

The model-facing condition is now entirely upstream of boundary synthesis: one
common sequence of coherent positive-time observables must approximate the
required open-half `L²` endpoint data before and after one unit of translation.
Exact boundary-observable realization and ambient boundary-`L²` surjectivity are
both absent. -/
theorem exists_finiteOperator_one_eigen_of_normalizedPhysicalTransferModePositiveHalfSynthesisClosure
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant)
    (n : ℕ)
    (f : periodicHypercubicEvenSpecialUnitarySpatialSliceGaugeInvariantL2Submodule
      (halfExtent n) N)
    (mu : ℝ)
    (hf : periodicHypercubicEvenSpecialUnitaryNormalizedPhysicalOneSlabTransferOperator
      (halfExtent n) N hN (beta n) (hbeta n) f = mu • f)
    (W : PhysicalTransferModePositiveHalfSynthesisClosureAt Q hInvariant C n f) :
    ∃ psi :
        (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
          S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).PhysicalHilbert,
      Q.physicalHilbertBoundaryMomentLinearIsometry hInvariant n psi =
          periodicHypercubicEvenSpecialUnitaryOneSidedBoundaryL2
            (halfExtent n) N
            (periodicHypercubicEvenSpecialUnitaryPhysicalModeLp
              (halfExtent n) N f)
            (periodicHypercubicEvenSpecialUnitaryPhysicalTopModeLp
              (halfExtent n) N hN (beta n) (hbeta n)) ∧
      C.finiteOperator n 1 psi = mu • psi := by
  exact
    Q.exists_finiteOperator_one_eigen_of_normalizedPhysicalTransferModeBoundaryClosure
      hInvariant C n f mu hf
      (W.toOneSidedBoundaryClosureAt Q hInvariant C n
        (periodicHypercubicEvenSpecialUnitaryPhysicalModeLp
          (halfExtent n) N f)
        (periodicHypercubicEvenSpecialUnitaryPhysicalTopModeLp
          (halfExtent n) N hN (beta n) (hbeta n))
        (periodicHypercubicEvenSpecialUnitaryPhysicalModeOneStepLp
          (halfExtent n) N hN (beta n) (hbeta n) f)
        (periodicHypercubicEvenSpecialUnitaryPhysicalTopModeOneStepLp
          (halfExtent n) N hN (beta n) (hbeta n)))

end PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback

end MathlibAnalytic
end MGAP4D

end
