import MGAP4D.MathlibAnalytic.PhysicalYangMillsLatticeEmbedding
import MGAP4D.MathlibAnalytic.PhysicalYangMillsWeakLimitObservableNontriviality
import Mathlib.MeasureTheory.Integral.BoundedContinuousFunction

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory

noncomputable section

/-- Variance of a physical bounded continuous observable pulled back to one
lattice configuration space through the interpolation map. -/
def PhysicalFourDimensionalYangMillsLatticeEmbedding.latticePullbackObservableVariance
    (E : PhysicalFourDimensionalYangMillsLatticeEmbedding)
    (n : ℕ)
    (O : BoundedContinuousFunction E.PhysicalConfiguration ℝ) : ℝ :=
  (∫ A, (O * O) (E.interpolate n A)
      ∂(E.latticeMeasure n : Measure (E.LatticeConfiguration n))) -
    (∫ A, O (E.interpolate n A)
      ∂(E.latticeMeasure n : Measure (E.LatticeConfiguration n))) ^ 2

/-- Integration of a bounded continuous observable against an embedded lattice
law equals integration of its pullback against the original lattice law. -/
theorem physical_yang_mills_latticeEmbedding_integral_embeddedMeasure
    (E : PhysicalFourDimensionalYangMillsLatticeEmbedding)
    (n : ℕ)
    (O : BoundedContinuousFunction E.PhysicalConfiguration ℝ) :
    (∫ A, O A ∂(E.embeddedMeasure n : Measure E.PhysicalConfiguration)) =
      ∫ a, O (E.interpolate n a)
        ∂(E.latticeMeasure n : Measure (E.LatticeConfiguration n)) := by
  rw [show (E.embeddedMeasure n : Measure E.PhysicalConfiguration) =
      Measure.map (E.interpolate n)
        (E.latticeMeasure n : Measure (E.LatticeConfiguration n)) by
    simp [PhysicalFourDimensionalYangMillsLatticeEmbedding.embeddedMeasure]]
  exact integral_map_of_stronglyMeasurable
    (E.interpolate_measurable n) O.continuous.stronglyMeasurable

/-- The variance of a bounded continuous observable under an embedded lattice
law is exactly the variance of its lattice pullback. -/
theorem physical_yang_mills_latticeEmbedding_embeddedMeasure_variance_eq_pullback
    (E : PhysicalFourDimensionalYangMillsLatticeEmbedding)
    (n : ℕ)
    (O : BoundedContinuousFunction E.PhysicalConfiguration ℝ) :
    (∫ A, (O * O) A
        ∂(E.embeddedMeasure n : Measure E.PhysicalConfiguration)) -
        (∫ A, O A
          ∂(E.embeddedMeasure n : Measure E.PhysicalConfiguration)) ^ 2 =
      E.latticePullbackObservableVariance n O := by
  unfold PhysicalFourDimensionalYangMillsLatticeEmbedding.latticePullbackObservableVariance
  rw [physical_yang_mills_latticeEmbedding_integral_embeddedMeasure E n (O * O)]
  rw [physical_yang_mills_latticeEmbedding_integral_embeddedMeasure E n O]

/-- For the weak limit generated by a lattice embedding, the generic
approximating observable variance is definitionally the pullback variance on the
original lattice probability space. -/
theorem physical_yang_mills_latticeEmbedding_approximatingObservableVariance_eq_pullback
    (E : PhysicalFourDimensionalYangMillsLatticeEmbedding)
    (continuumMeasure : ProbabilityMeasure E.PhysicalConfiguration)
    (hWeak : Filter.Tendsto E.embeddedMeasure Filter.atTop (nhds continuumMeasure))
    (n : ℕ)
    (O : BoundedContinuousFunction E.PhysicalConfiguration ℝ) :
    (E.toWeakLimit continuumMeasure hWeak).approximatingObservableVariance n O =
      E.latticePullbackObservableVariance n O := by
  unfold PhysicalFourDimensionalYangMillsWeakLimit.approximatingObservableVariance
  change
    (∫ A, (O * O) A
        ∂(E.embeddedMeasure n : Measure E.PhysicalConfiguration)) -
        (∫ A, O A
          ∂(E.embeddedMeasure n : Measure E.PhysicalConfiguration)) ^ 2 =
      E.latticePullbackObservableVariance n O
  exact physical_yang_mills_latticeEmbedding_embeddedMeasure_variance_eq_pullback
    E n O

end

end MathlibAnalytic
end MGAP4D
