import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSFiniteIntegralActualBoundaryGap
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSExponentialGapSlope

noncomputable section

open Filter MeasureTheory Set Topology

namespace MGAP4D
namespace MathlibAnalytic

local instance exact3320FiniteIntegralActualBoundaryGapSideLengthNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance exact3320FiniteIntegralActualBoundaryGapSpecialUnitaryIsTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance exact3320FiniteIntegralActualBoundaryGapSpecialUnitaryCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance exact3320FiniteIntegralActualBoundaryGapSpecialUnitarySecondCountableTopology (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance exact3320FiniteIntegralActualBoundaryGapSpecialUnitaryMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance exact3320FiniteIntegralActualBoundaryGapSpecialUnitaryBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- The exact normalized mass used by the present finite-integral route. -/
def physicalYangMillsExact3320Mass : ℝ := (33 : ℝ) / 20

/-- Exact positivity of the normalized mass. -/
theorem physicalYangMillsExact3320Mass_pos :
    0 < physicalYangMillsExact3320Mass := by
  norm_num [physicalYangMillsExact3320Mass]

/-- The quadratic decay factor whose square-root double-time slope is exactly
`33/20`. -/
def physicalYangMillsExact3320QuadraticDecayFactor (t : NNReal) : ℝ :=
  Real.exp (-physicalYangMillsExact3320Mass * (t : ℝ))

/-- The exact `33/20` quadratic decay factor is nonnegative. -/
theorem physicalYangMillsExact3320QuadraticDecayFactor_nonneg
    (t : NNReal) :
    0 ≤ physicalYangMillsExact3320QuadraticDecayFactor t := by
  exact exponential_quadraticDecayFactor_nonneg
    physicalYangMillsExact3320Mass t

/-- The square-root double-time slope of the fixed exponential factor is
exactly `33/20`. -/
theorem physicalYangMillsExact3320QuadraticDecayFactor_slope_tendsto :
    Tendsto
      (fun t : NNReal =>
        (t : ℝ)⁻¹ *
          (1 - Real.sqrt
            (physicalYangMillsExact3320QuadraticDecayFactor (t + t))))
      (nhdsWithin 0 (Ioi 0))
      (nhds physicalYangMillsExact3320Mass) := by
  simpa [physicalYangMillsExact3320QuadraticDecayFactor] using
    exponential_quadraticDecayFactor_slope_tendsto
      physicalYangMillsExact3320Mass

/-- The exact finite-volume analytic target after all structural OS/boundary
work has been discharged.

The mass and decay factor are no longer free fields: they are fixed to

`m = 33/20`, `q(t) = exp (-(33/20) t)`.

Thus the only model-specific inputs retained here are:

1. reflection/time-translation exchange for the actual OS semigroup;
2. the concrete finite periodic Wilson Gibbs reflected-integral decay at that
   exact exponential rate.

All subsequent Hilbert completion, actual boundary realization, strict
Boundary-`L²` contraction, finite vacuum gap, and continuum gap transfer are
theorem-generated by the existing route. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSExact3320FiniteIntegralGapCertificate
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant) where
  exchange : ∀ n,
    PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ReflectionTimeTranslationExchange
      (C.toPositiveTimeObservableContractionSemigroup n)
  finite_integral_decay_3320 :
    ∀ (n : ℕ) (t : NNReal),
      let Pn :=
        physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
          S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
      let Tn := C.toPositiveTimeObservableContractionSemigroup n
      ∀ F : Pn.Carrier,
        physicalYangMillsEvenPeriodicWilsonOSFiniteReflectedIntegral
            S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
            (Tn.carrierTranslation (t / 2) (Pn.vacuumCenteredCarrier F)) ≤
          physicalYangMillsExact3320QuadraticDecayFactor t *
            physicalYangMillsEvenPeriodicWilsonOSFiniteReflectedIntegral
              S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
              (Pn.vacuumCenteredCarrier F)

namespace PhysicalYangMillsEvenPeriodicWilsonOSExact3320FiniteIntegralGapCertificate

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSApproximatingSemigroupFamily
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant}

/-- Install the exact `33/20` data into the generic finite-integral certificate.
No mass, decay, or small-time-slope choice remains. -/
noncomputable def toApproximatingFiniteIntegralGapCertificate
    (R : PhysicalYangMillsEvenPeriodicWilsonOSExact3320FiniteIntegralGapCertificate
      S D halfExtent N hN beta hbeta Q hInvariant C) :
    PhysicalYangMillsEvenPeriodicWilsonOSApproximatingFiniteIntegralGapCertificate
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant C where
  mass := physicalYangMillsExact3320Mass
  mass_pos := physicalYangMillsExact3320Mass_pos
  quadraticDecayFactor := physicalYangMillsExact3320QuadraticDecayFactor
  quadraticDecayFactor_nonneg :=
    physicalYangMillsExact3320QuadraticDecayFactor_nonneg
  slope_tendsto :=
    physicalYangMillsExact3320QuadraticDecayFactor_slope_tendsto
  exchange := R.exchange
  finite_integral_decay := R.finite_integral_decay_3320

/-- Exact `33/20` finite reflected-integral decay therefore generates the
actual centered boundary-Haar `L²` quadratic-gap certificate. -/
noncomputable def toCompletedVacuumOrthogonalBoundaryL2QuadraticGapCertificate
    (R : PhysicalYangMillsEvenPeriodicWilsonOSExact3320FiniteIntegralGapCertificate
      S D halfExtent N hN beta hbeta Q hInvariant C) :
    PhysicalYangMillsEvenPeriodicWilsonOSApproximatingBoundaryL2QuadraticGapCertificate
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant C :=
  R.toApproximatingFiniteIntegralGapCertificate
    |>.toCompletedVacuumOrthogonalBoundaryL2QuadraticGapCertificate

/-- Exact `33/20` finite reflected-integral decay generates the completed finite
Wilson OS vacuum-gap certificate through the actual boundary realization. -/
noncomputable def toCompletedVacuumOrthogonalApproximatingVacuumGapCertificate
    (R : PhysicalYangMillsEvenPeriodicWilsonOSExact3320FiniteIntegralGapCertificate
      S D halfExtent N hN beta hbeta Q hInvariant C) :
    PhysicalYangMillsEvenPeriodicWilsonOSApproximatingVacuumGapCertificate
      S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant C :=
  R.toApproximatingFiniteIntegralGapCertificate
    |>.toCompletedVacuumOrthogonalApproximatingVacuumGapCertificate

/-- The generated generic finite-integral certificate retains the exact mass
`33/20` definitionally. -/
@[simp] theorem toApproximatingFiniteIntegralGapCertificate_mass
    (R : PhysicalYangMillsEvenPeriodicWilsonOSExact3320FiniteIntegralGapCertificate
      S D halfExtent N hN beta hbeta Q hInvariant C) :
    R.toApproximatingFiniteIntegralGapCertificate.mass = (33 : ℝ) / 20 := by
  rfl

end PhysicalYangMillsEvenPeriodicWilsonOSExact3320FiniteIntegralGapCertificate

end MathlibAnalytic
end MGAP4D

end
