import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenWilsonGibbsBoundaryHilbertSchmidtAnalysis
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSRealizableOneStepExact3320BoundaryL2FactorizedGap
import Mathlib.Tactic

noncomputable section

open MeasureTheory

namespace MGAP4D
namespace MathlibAnalytic

local instance realizableWilsonHilbertSchmidtFactorSideLengthNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance realizableWilsonHilbertSchmidtFactorSpecialUnitaryIsTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance realizableWilsonHilbertSchmidtFactorSpecialUnitaryCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance realizableWilsonHilbertSchmidtFactorSpecialUnitarySecondCountableTopology (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance realizableWilsonHilbertSchmidtFactorSpecialUnitaryMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance realizableWilsonHilbertSchmidtFactorSpecialUnitaryBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- Realizable one-step factorization in which the analysis map is no longer an
abstract field: it is the canonical Hilbert--Schmidt operator generated by the
actual compact-Haar Wilson boundary/open-half product feature.

The only remaining factor map is a synthesis operator from positive-open-half
`L²` back to shared-boundary `L²`.  Quantitatively it is enough to control

`‖synthesisₙ‖ * ‖Φₙ‖_{L²(boundary × open-half)}`

by the exact one-step factor `exp (-(33/20) aₙ)`, because Mathlib already gives
`‖analysisₙ‖ ≤ ‖Φₙ‖₂`.

The exact one-step intertwining remains explicit; static Gram positivity alone
is not silently identified with geometric Euclidean translation. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320WilsonHilbertSchmidtFactorizedGapCertificate
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S)
    (R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)) where
  boundaryMoment_memLp :
    ∀ (n : ℕ)
      (F : (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier),
      MemLp
        (fun b =>
          physicalYangMillsEvenPeriodicWilsonOSBoundaryMoment
            S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n F b)
        2
        (periodicHypercubicEvenBoundaryHaarMeasure (halfExtent n) N)
  synthesis :
    (n : ℕ) →
      PeriodicHypercubicEvenSpecialUnitaryOpenHalfL2 (halfExtent n) N →L[ℝ]
        PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N
  boundaryMoment_hilbertSchmidt_intertwining :
    ∀ (n : ℕ)
      (F : (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier),
      let Pn :=
        physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
          S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
      (synthesis n).comp
          (periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
            (halfExtent n) N hN (beta n) (hbeta n))
          (physicalYangMillsEvenPeriodicWilsonOSBoundaryMomentL2
            S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
            (Pn.vacuumCenteredCarrier F)
            (boundaryMoment_memLp n (Pn.vacuumCenteredCarrier F))) =
        physicalYangMillsEvenPeriodicWilsonOSBoundaryMomentL2
          S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
          (R.realizableCarrierTranslation hInvariant n 1
            (Pn.vacuumCenteredCarrier F))
          (boundaryMoment_memLp n
            (R.realizableCarrierTranslation hInvariant n 1
              (Pn.vacuumCenteredCarrier F)))
  synthesis_kernelNorm_mul_le :
    ∀ n : ℕ,
      ‖synthesis n‖ *
          ‖periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2
            (halfExtent n) N hN (beta n) (hbeta n)‖ ≤
        physicalYangMillsExact3320OneStepNormFactor S n

namespace PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320WilsonHilbertSchmidtFactorizedGapCertificate

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S}
    {R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}

/-- The actual Wilson Hilbert--Schmidt analysis and the remaining synthesis map
satisfy the factor norm product bound required by the abstract factorized
one-step certificate. -/
theorem factor_opNorm_mul_le
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320WilsonHilbertSchmidtFactorizedGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (n : ℕ) :
    ‖A.synthesis n‖ *
        ‖periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
          (halfExtent n) N hN (beta n) (hbeta n)‖ ≤
      physicalYangMillsExact3320OneStepNormFactor S n := by
  calc
    ‖A.synthesis n‖ *
        ‖periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
          (halfExtent n) N hN (beta n) (hbeta n)‖ ≤
      ‖A.synthesis n‖ *
        ‖periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2
          (halfExtent n) N hN (beta n) (hbeta n)‖ := by
        exact mul_le_mul_of_nonneg_left
          (periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis_norm_le
            (halfExtent n) N hN (beta n) (hbeta n))
          (norm_nonneg (A.synthesis n))
    _ ≤ physicalYangMillsExact3320OneStepNormFactor S n :=
      A.synthesis_kernelNorm_mul_le n

/-- The actual Wilson Hilbert--Schmidt analysis package instantiates the generic
one-step analysis/synthesis factorization of #1493. -/
noncomputable def toBoundaryL2FactorizedGapCertificate
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320WilsonHilbertSchmidtFactorizedGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant) :
    PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320BoundaryL2FactorizedGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant where
  boundaryMoment_memLp := A.boundaryMoment_memLp
  FeatureState := fun n =>
    PeriodicHypercubicEvenSpecialUnitaryOpenHalfL2 (halfExtent n) N
  featureNormedAddCommGroup := fun _ => inferInstance
  featureNormedSpace := fun _ => inferInstance
  analysis := fun n =>
    periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
      (halfExtent n) N hN (beta n) (hbeta n)
  synthesis := A.synthesis
  boundaryMoment_factorized_intertwining := by
    intro n F
    exact A.boundaryMoment_hilbertSchmidt_intertwining n F
  factor_opNorm_mul_le := A.factor_opNorm_mul_le

/-- Hence the actual Wilson Hilbert--Schmidt analysis plus the remaining
synthesis/intertwining estimate generates the direct boundary-`L²` transfer
certificate. -/
noncomputable def toBoundaryL2TransferGapCertificate
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320WilsonHilbertSchmidtFactorizedGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant) :
    PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320BoundaryL2TransferGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant :=
  A.toBoundaryL2FactorizedGapCertificate.toBoundaryL2TransferGapCertificate

/-- Therefore it also generates the literal compact-Haar boundary Poincaré
certificate. -/
noncomputable def toBoundaryDirichletGapCertificate
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320WilsonHilbertSchmidtFactorizedGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant) :
    PhysicalYangMillsEvenPeriodicWilsonOSRealizableExact3320BoundaryDirichletGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant :=
  A.toBoundaryL2FactorizedGapCertificate.toBoundaryDirichletGapCertificate

/-- And the exact geometric Euclidean two-step Dirichlet coercivity. -/
noncomputable def toGeometricDirichletGapCertificate
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320WilsonHilbertSchmidtFactorizedGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant) :
    PhysicalYangMillsEvenPeriodicWilsonOSRealizableExact3320GeometricDirichletGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant :=
  A.toBoundaryL2FactorizedGapCertificate.toGeometricDirichletGapCertificate

/-- Finally recover the exact centered one-step OS contraction certificate and
all downstream discrete/floor-continuum mass-gap machinery. -/
noncomputable def toOneStepExact3320GapCertificate
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320WilsonHilbertSchmidtFactorizedGapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant) :
    PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320GapCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant :=
  A.toBoundaryL2FactorizedGapCertificate.toOneStepExact3320GapCertificate

end PhysicalYangMillsEvenPeriodicWilsonOSRealizableOneStepExact3320WilsonHilbertSchmidtFactorizedGapCertificate

end MathlibAnalytic
end MGAP4D

end
