import MGAP4D.MathlibAnalytic.PeriodicHypercubicSpecialUnitaryDiscretePhysicalTemporalAction
import MGAP4D.MathlibAnalytic.PeriodicHypercubicSpecialUnitaryFloorTemporalApproximation
import MGAP4D.MathlibAnalytic.PhysicalYangMillsOrientedDenseTemporalApproximation
import MGAP4D.MathlibAnalytic.PhysicalYangMillsOrientedFloorTemporalApproximation
import MGAP4D.MathlibAnalytic.PhysicalYangMillsOrientedJointTemporalContinuity
import MGAP4D.MathlibAnalytic.PhysicalYangMillsContinuumEuclideanTimeTranslation
import MGAP4D.MathlibAnalytic.PhysicalYangMillsContinuumTimeTranslationFromDiscrete
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSContinuumTimeTranslationBridge
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSConfigurationTimeTranslationFromDiscrete

namespace MGAP4D
namespace MathlibAnalytic

#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.PhysicalDiscreteTemporalAction
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation.WeakLimitContinuity
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.PhysicalDiscreteTemporalAction.JointContinuity
#check PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.GaugeDiscreteTemporalCompatibility
#check physicalTemporalFloorStep
#check physicalTemporalFloorStep_tendsto
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation.ofFloor
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.PhysicalDiscreteTemporalAction.JointContinuity.toWeakLimitContinuity
#check periodicHypercubicPhysicalLatticeTime
#check periodicHypercubicSpecialUnitaryDiscretePhysicalTemporalAction
#check periodicHypercubicSpecialUnitaryFloorDenseTemporalApproximation
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.PhysicalDiscreteTemporalAction.embeddedMeasure_map_latticeTime_eq_self
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.DenseTemporalApproximation.WeakLimitContinuity.continuumMeasure_map_eq_self
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.GaugeDiscreteTemporalCompatibility.toContinuumEuclideanTimeTranslation
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.GaugeDiscreteTemporalCompatibility.toContinuumEuclideanTimeTranslationOfJointContinuity
#check ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding.GaugeDiscreteTemporalCompatibility.toContinuumEuclideanTimeTranslationOfFloor
#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ConfigurationTimeTranslationCovariance.ContinuumCompatibility
#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ConfigurationTimeTranslationCovariance.ofContinuumEuclideanTimeTranslation
#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PositiveTimeObservableContractionSemigroup.ConfigurationTimeTranslationCovariance.ofDiscreteTemporalAction

end MathlibAnalytic
end MGAP4D
