import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSApproximatingGapTransfer

/-!
# Actual finite Wilson OS gap-transfer spine

This aggregate exposes the concrete finite-volume route

```text
embedded even-periodic SU(N) Wilson Gibbs probability laws
→ actual finite-state weak-star reflection positivity
→ scale-dependent OS pre-Hilbert data
→ null-space separation quotient
→ complete real finite-volume OS Hilbert spaces
→ normalized finite-volume vacua
→ completed finite-volume contraction semigroups
→ reflection/time-translation exchange
→ symmetric finite transfer operators
→ invariance of each vacuum-orthogonal excitation sector
→ quantitative finite-volume vacuum decay certificate
→ isometric common-carrier embeddings
→ strong convergence of states and evolved states
→ embedded finite-volume vacuum-gap transfer
→ continuum right-Hamiltonian Rayleigh lower bound
→ graph-closed continuum Hamiltonian lower bound
→ zero-energy space equals the normalized vacuum line
```

The finite Hilbert carriers in this route are not abstract placeholders.  They
are the OS completions generated by the actual approximating Wilson Gibbs
states.  The remaining model-specific inputs are the common positive-time
translation realization, its OS contraction and exchange identities, the
uniform finite-volume vacuum-sector decay estimate, and common-carrier strong
convergence.

Import this file with

```lean
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSApproximatingGapTransferSpine
```
-/
