import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonSU2ThreeModeKrylovAdjacentPosteriorSourceTiltSeedCovarianceDecay

/-! Compile contracts for source-only tilt seed covariance decay. -/

namespace MGAP4D.MathlibAnalytic

noncomputable section

#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetBoundaryIncrement_abs_le_six
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetBoundaryTilt_exp_neg_six_mul_le
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetBoundaryTilt_le_exp_six_mul
#check periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetBoundaryTilt_inv_le_exp_six_mul
#check physicalYangMillsSU2PrimaryPlaquetteSeed_sourceRightLinkTiltCovariance_abs_le_seedDistancePower
#check physicalYangMillsSU2PrimaryPlaquetteFarLinks_two_sourceRightLinkTiltCovariance_abs_le_seedDistancePower

#print axioms periodicHypercubicEvenSpecialUnitaryTemporalGaugeOneSlabRightTargetBoundaryTilt_inv_le_exp_six_mul
#print axioms physicalYangMillsSU2PrimaryPlaquetteSeed_sourceRightLinkTiltCovariance_abs_le_seedDistancePower

end

end MGAP4D.MathlibAnalytic
