import MGAP4D.MathlibAnalytic.PhysicalYangMillsOrientedGaugeSymmetryLimit

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

namespace ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding
namespace PhysicalGaugeAction

/-- Build a physical gauge action directly from pointwise gauge invariance of
an interpolation map.

The physical action is the identity because the chosen physical carrier is a
gauge-invariant readout.  The symmetry type retains an arbitrary lattice gauge
transformation independently at every scale, so this constructor loses no
finite gauge freedom.  Crucially, `interpolate_equivariant` is proved from
`hInvariant`; it is not supplied as a separate physical assumption. -/
noncomputable def ofGaugeInvariantInterpolation
    (E : ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding)
    (hInvariant :
      ∀ n (gamma : (E.system n).base.GaugeTransformation)
        (U : (E.system n).base.Configuration),
        E.interpolate n ((E.system n).base.gaugeTransform gamma U) =
          E.interpolate n U) :
    E.PhysicalGaugeAction where
  Symmetry := ∀ n, (E.system n).base.GaugeTransformation
  action := fun _ x => x
  action_continuous := fun _ => continuous_id
  latticeGauge := fun n gamma => gamma n
  interpolate_equivariant := by
    intro n gamma U
    exact hInvariant n (gamma n) U

/-- The action constructed from a gauge-invariant interpolation is pointwise
trivial on the physical readout carrier. -/
theorem ofGaugeInvariantInterpolation_action_eq
    (E : ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding)
    (hInvariant :
      ∀ n (gamma : (E.system n).base.GaugeTransformation)
        (U : (E.system n).base.Configuration),
        E.interpolate n ((E.system n).base.gaugeTransform gamma U) =
          E.interpolate n U)
    (gamma : (ofGaugeInvariantInterpolation E hInvariant).Symmetry)
    (x : E.PhysicalConfiguration) :
    (ofGaugeInvariantInterpolation E hInvariant).action gamma x = x :=
  rfl

/-- Stable theorem form of the interpolation equivariance generated by
`ofGaugeInvariantInterpolation`. -/
theorem ofGaugeInvariantInterpolation_interpolate_equivariant
    (E : ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding)
    (hInvariant :
      ∀ n (gamma : (E.system n).base.GaugeTransformation)
        (U : (E.system n).base.Configuration),
        E.interpolate n ((E.system n).base.gaugeTransform gamma U) =
          E.interpolate n U)
    (n : ℕ)
    (gamma : (ofGaugeInvariantInterpolation E hInvariant).Symmetry)
    (U : (E.system n).base.Configuration) :
    E.interpolate n
        ((E.system n).base.gaugeTransform
          ((ofGaugeInvariantInterpolation E hInvariant).latticeGauge n gamma) U) =
      (ofGaugeInvariantInterpolation E hInvariant).action gamma
        (E.interpolate n U) :=
  (ofGaugeInvariantInterpolation E hInvariant).interpolate_equivariant n gamma U

end PhysicalGaugeAction
end ContinuousCompactOrientedGaugeWilsonPhysicalEmbedding

end

end MathlibAnalytic
end MGAP4D
