import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSVacuumOperatorState

namespace MGAP4D
namespace MathlibAnalytic

#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.vacuumOperatorState
#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.vacuumOperatorState_normalized
#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.vacuumOperatorState_nonnegative
#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.PhysicalSemigroup.euclideanSandwich
#check PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.vacuumOperatorState_euclideanSandwich_invariant
#check physical_yang_mills_evenPeriodicWilsonOS_continuum_vacuumOperatorState_package

end MathlibAnalytic
end MGAP4D
