import MGAP4D.MathlibAnalytic.PhysicalYangMillsZ2InfiniteLatticePlaquetteSeparationEquivalence
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- A single standard input package for the concrete infinite-lattice `Z₂`
plaquette connected-correlation bound.

The package combines the coupling parameter, two fixed integer-lattice
plaquettes, the all-volume finite-periodic distance hypothesis, and the existing
finite-volume uniform spatial-clustering certificate.

This is only a proof-engineering façade for the compact infinite-lattice binary
carrier.  It does not construct a continuum `ℝ⁴` gauge-field configuration
space, DLR state, reflection-positivity limit, OS reconstruction, Hamiltonian,
Hamiltonian spectral gap, physical mass gap, or an unconditional proof of the
four-dimensional Yang--Mills mass gap problem. -/
structure z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput where
  beta : ℝ
  hBeta : 0 < beta
  distance : ℕ
  sourcePlaquette : IntegerHypercubicPlaquette
  targetPlaquette : IntegerHypercubicPlaquette
  distance_hypothesis :
    z2PeriodicHypercubicInfiniteLatticePlaquetteDistanceHypothesis
      distance sourcePlaquette targetPlaquette
  clustering_certificate :
    Z2PeriodicHypercubicOrientedPlaquetteUniformSpatialClusteringFamilyCertificate
      beta hBeta

namespace z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput

/-- The bundled filter/finite-prefix separation certificate generated by a
standard clustering input package. -/
noncomputable def filterSeparationCertificate
    (I : z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput) :
    z2PeriodicHypercubicInfiniteLatticePlaquetteFilterSeparationCertificate
      I.distance I.sourcePlaquette I.targetPlaquette :=
  z2PeriodicHypercubicInfiniteLatticePlaquetteFilterSeparationCertificateOfDistanceHypothesis
    I.distance_hypothesis

/-- The nonempty certificate package associated to a standard clustering input. -/
theorem filterSeparationCertificate_nonempty
    (I : z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput) :
    Nonempty
      (z2PeriodicHypercubicInfiniteLatticePlaquetteFilterSeparationCertificate
        I.distance I.sourcePlaquette I.targetPlaquette) :=
  z2PeriodicHypercubicInfiniteLatticePlaquetteFilterSeparationCertificate_nonempty_of_distanceHypothesis
    I.distance_hypothesis

/-- Canonical concrete plaquette data extracted from a standard clustering input
package. -/
noncomputable def plaquetteData
    (I : z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput) :
    PhysicalYangMillsZ2PeriodicCanonicalPlaquetteData
      (z2PeriodicHypercubicInfiniteLatticeEmbedding I.beta I.hBeta)
      I.distance :=
  z2PeriodicHypercubicInfiniteLatticePlaquetteDataOfDistanceHypothesisCertificate
    I.beta I.hBeta I.distance I.sourcePlaquette I.targetPlaquette
    I.distance_hypothesis

/-- The selected Prokhorov subsequential weak limit extracted from a standard
clustering input package. -/
noncomputable def prokhorovLimit
    (I : z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput) :
    PhysicalFourDimensionalYangMillsProkhorovSubsequenceLimit
      (z2PeriodicHypercubicInfiniteLatticeEmbedding I.beta I.hBeta).toLatticeEmbedding :=
  z2PeriodicHypercubicInfiniteLatticePlaquetteProkhorovLimitOfDistanceHypothesisCertificate
    I.beta I.hBeta I.distance I.sourcePlaquette I.targetPlaquette
    I.distance_hypothesis

/-- The source bounded continuous local plaquette observable of a standard
clustering input package. -/
noncomputable def sourceObservable
    (I : z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput) :
    BoundedContinuousFunction Z2InfiniteHypercubicBinaryConfiguration ℝ :=
  z2InfiniteHypercubicPlaquetteObservable I.sourcePlaquette

/-- The target bounded continuous local plaquette observable of a standard
clustering input package. -/
noncomputable def targetObservable
    (I : z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput) :
    BoundedContinuousFunction Z2InfiniteHypercubicBinaryConfiguration ℝ :=
  z2InfiniteHypercubicPlaquetteObservable I.targetPlaquette

/-- The concrete connected-correlation bound extracted from one standard input
package. -/
theorem connectedCorrelation_abs_le
    (I : z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput) :
    abs (I.prokhorovLimit.toWeakLimit.continuumConnectedCorrelation
        I.sourceObservable I.targetObservable) ≤
      z2PeriodicHypercubicOrientedExplicitSpatialClusteringPrefactor I.beta *
        Real.exp
          (-z2PeriodicHypercubicOrientedExplicitSpatialClusteringRate I.beta *
            (I.distance : ℝ)) := by
  simpa [prokhorovLimit, sourceObservable, targetObservable] using
    z2PeriodicHypercubicInfiniteLatticePlaquetteConnectedCorrelation_abs_le_of_distanceHypothesisCertificate
      I.beta I.hBeta I.distance I.sourcePlaquette I.targetPlaquette
      I.distance_hypothesis I.clustering_certificate

end z2PeriodicHypercubicInfiniteLatticePlaquetteClusteringInput

end

end MathlibAnalytic
end MGAP4D
