import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonCommonProductPhysicalAmbientCarrier
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

open Filter MeasureTheory Set Topology
open scoped InnerProductSpace

local instance (H : ℕ) : NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- The remaining reverse-mass input after the finite Wilson spaces have been
placed in the theorem-generated interacting boundary common product and that
single common product has been realized isometrically in the continuum
physical OS Hilbert space.

The ambient family and all finite-vacuum compatibility are generated by
`PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalCarrier`.  The only
new scale-dependent analytic datum stored here is the moving-time two-step
vector defect at the required `o(a_n)` rate.

The coherent positive-half bridge is first put on its canonical vacuum-sign
branch.  No mass, gap, decay, coercivity, spectral, or exact-value input occurs
in this owner type. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalTwoStepRecovery
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S}
    {R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    (C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E R hInvariant)
    (P : D.OSPreHilbertData)
    (T : P.StronglyContinuousPhysicalSemigroup)
    (J : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalCarrier
      halfExtent N hN beta hbeta P) where
  vectorDefectExcess : ℕ → ℝ
  vectorDefectExcess_tendsto_zero : Tendsto vectorDefectExcess atTop (nhds 0)
  twoStepVectorDefect_le :
    ∀ n phi, ‖phi‖ = 1 →
      let A := J.toMassFreeAmbientCarrier Q hInvariant
      let K := C.boundedAnalysis.physicalExcitationOneStepOperator n
      let eta := A.excitationEmbed n ((K ∘L K) phi)
      let psi := A.excitationEmbed n phi
      ‖(eta : P.PhysicalHilbert) -
          T.toPhysicalSemigroup.operator
            (physicalYangMillsLatticeSpacingNNReal S n +
              physicalYangMillsLatticeSpacingNNReal S n)
            (psi : P.PhysicalHilbert)‖ ≤
        2 * S.latticeSpacing n * vectorDefectExcess n

namespace PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalTwoStepRecovery

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S}
    {R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E R hInvariant}
    {P : D.OSPreHilbertData}
    {T : P.StronglyContinuousPhysicalSemigroup}
    {J : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalCarrier
      halfExtent N hN beta hbeta P}

/-- The common-product presentation theorem-generates exactly the mass-free
ambient two-step recovery structure of #1578. -/
noncomputable def toMassFreeAmbientTwoStepRecovery
    (V : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalTwoStepRecovery
      C P T J) :
    PhysicalYangMillsEvenPeriodicWilsonOSMassFreeAmbientTwoStepRecovery
      C P T (J.toMassFreeAmbientCarrier Q hInvariant) where
  vectorDefectExcess := V.vectorDefectExcess
  vectorDefectExcess_tendsto_zero := V.vectorDefectExcess_tendsto_zero
  twoStepVectorDefect_le := by
    intro n phi hphi
    simpa only using V.twoStepVectorDefect_le n phi hphi

/-- After the common-product physical realization has been supplied, the
moving-time `o(a_n)` vector defect alone yields the reverse physical variational
mass inequality. -/
theorem physicalYangMillsMass_le_limit
    (V : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalTwoStepRecovery
      C P T J)
    (hSymmetric : T.toPhysicalSemigroup.IsInnerSymmetric) :
    T.physicalYangMillsMass ≤ C.limit :=
  V.toMassFreeAmbientTwoStepRecovery.physicalYangMillsMass_le_limit hSymmetric

/-- The same common-product moving-time recovery data produce a genuine nonzero
continuum vacuum-orthogonal excitation witness. -/
theorem excitationDomainWitness_nonempty
    (V : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalTwoStepRecovery
      C P T J)
    (hSymmetric : T.toPhysicalSemigroup.IsInnerSymmetric) :
    Nonempty T.PhysicalYangMillsExcitationDomainWitness :=
  V.toMassFreeAmbientTwoStepRecovery.excitationDomainWitness_nonempty hSymmetric

/-- Combining the theorem-generated reverse inequality with the existing
continuum-to-finite common-carrier direction identifies the intrinsic Wilson
rate limit with the physical Yang--Mills variational mass.

The statement still requires the independent forward common-carrier transfer;
no exact numerical mass evaluation is introduced here. -/
theorem limit_eq_physicalYangMillsMass
    (V : PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalTwoStepRecovery
      C P T J)
    (G : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer
      S D halfExtent N hN beta hbeta Q.vacuumNormalized E R hInvariant C P T)
    (hP : P.IsNormalized)
    (hSymmetric : T.toPhysicalSemigroup.IsInnerSymmetric) :
    C.limit = T.physicalYangMillsMass :=
  V.toMassFreeAmbientTwoStepRecovery.limit_eq_physicalYangMillsMass
    G hP hSymmetric

end PhysicalYangMillsEvenPeriodicWilsonOSCommonProductPhysicalTwoStepRecovery

end

end MathlibAnalytic
end MGAP4D
