import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSLiteralBoundaryPoincareLowerBound
import Mathlib.Tactic

noncomputable section

open Filter MeasureTheory Set Topology
open scoped InnerProductSpace

namespace MGAP4D
namespace MathlibAnalytic

local instance wilsonBoundaryOptimalMassSideLengthNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance wilsonBoundaryOptimalMassSpecialUnitaryIsTopologicalGroup
    (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance wilsonBoundaryOptimalMassSpecialUnitaryCompactSpace
    (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance wilsonBoundaryOptimalMassSpecialUnitarySecondCountableTopology
    (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance wilsonBoundaryOptimalMassSpecialUnitaryMeasurableSpace
    (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance wilsonBoundaryOptimalMassSpecialUnitaryBorelSpace
    (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- A nonnegative real number is an admissible Wilson boundary Poincare mass
when the literal compact-Haar shared-boundary inequality holds eventually at
all sufficiently fine lattice scales.

The predicate is defined directly from the actual finite Wilson OS boundary
moment and the mass-free boundary Dirichlet energy.  In particular it contains
no exact numerical target and no certificate-selected distinguished mass. -/
def physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareAdmissibleMass
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S)
    (R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (m : ℝ) : Prop :=
  0 ≤ m ∧
    ∀ᶠ n in atTop,
      ∀ F : (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier,
      let Pn :=
        physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
          S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
      let Fc := Pn.vacuumCenteredCarrier F
      (2 * m * S.latticeSpacing n) *
          (∫ b,
            ‖physicalYangMillsEvenPeriodicWilsonOSBoundaryMoment
              S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n Fc b‖ ^ 2
            ∂(periodicHypercubicEvenBoundaryHaarMeasure (halfExtent n) N)) ≤
        physicalYangMillsEvenPeriodicWilsonOSRealizableCenteredBoundaryDirichletEnergyMassFree
          S D halfExtent N hN beta hbeta Q E R hInvariant n F

/-- The intrinsic set of all masses supported by the literal finite Wilson
boundary Poincare form.  This set, rather than a certificate field, is the
model-derived numerical carrier for the exact-mass route. -/
def physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareAdmissibleMassSet
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S)
    (R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)) : Set ℝ :=
  {m | physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareAdmissibleMass
    S D halfExtent N hN beta hbeta Q E R hInvariant m}

/-- The optimal finite-Wilson boundary Poincare mass is the supremum of all
admissible masses generated by the literal compact-Haar boundary form.

No exact value is inserted here.  A future model calculation must identify this
supremum from the Wilson action itself. -/
noncomputable def physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareOptimalMass
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S)
    (R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)) : ℝ :=
  sSup (physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareAdmissibleMassSet
    S D halfExtent N hN beta hbeta Q E R hInvariant)

namespace PhysicalYangMillsEvenPeriodicWilsonOSLiteralBoundaryPoincareLowerBoundCertificate

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S}
    {R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}

/-- Every previously constructed literal boundary Poincare certificate supplies
one element of the intrinsic admissible-mass set.  The certificate no longer
defines the optimal mass; it merely proves admissibility of its value. -/
theorem mass_mem_boundaryPoincareAdmissibleMassSet
    (A : PhysicalYangMillsEvenPeriodicWilsonOSLiteralBoundaryPoincareLowerBoundCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant) :
    A.mass ∈
      physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareAdmissibleMassSet
        S D halfExtent N hN beta hbeta Q E R hInvariant := by
  exact ⟨A.mass_pos.le, A.eventually_boundary_poincare⟩

/-- A literal positive-mass certificate makes the intrinsic Wilson admissible
mass set nonempty. -/
theorem boundaryPoincareAdmissibleMassSet_nonempty
    (A : PhysicalYangMillsEvenPeriodicWilsonOSLiteralBoundaryPoincareLowerBoundCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant) :
    (physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareAdmissibleMassSet
      S D halfExtent N hN beta hbeta Q E R hInvariant).Nonempty :=
  ⟨A.mass, A.mass_mem_boundaryPoincareAdmissibleMassSet⟩

/-- Whenever the model-derived admissible set is bounded above, every certified
Wilson mass lies below its intrinsic optimal value. -/
theorem mass_le_boundaryPoincareOptimalMass
    (A : PhysicalYangMillsEvenPeriodicWilsonOSLiteralBoundaryPoincareLowerBoundCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (hBdd : BddAbove
      (physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareAdmissibleMassSet
        S D halfExtent N hN beta hbeta Q E R hInvariant)) :
    A.mass ≤
      physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareOptimalMass
        S D halfExtent N hN beta hbeta Q E R hInvariant := by
  exact le_csSup hBdd A.mass_mem_boundaryPoincareAdmissibleMassSet

/-- Under the same boundedness hypothesis, the intrinsic Wilson optimal mass is
strictly positive as soon as one positive literal boundary certificate exists. -/
theorem boundaryPoincareOptimalMass_pos
    (A : PhysicalYangMillsEvenPeriodicWilsonOSLiteralBoundaryPoincareLowerBoundCertificate
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (hBdd : BddAbove
      (physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareAdmissibleMassSet
        S D halfExtent N hN beta hbeta Q E R hInvariant)) :
    0 < physicalYangMillsEvenPeriodicWilsonOSBoundaryPoincareOptimalMass
      S D halfExtent N hN beta hbeta Q E R hInvariant :=
  lt_of_lt_of_le A.mass_pos (A.mass_le_boundaryPoincareOptimalMass hBdd)

end PhysicalYangMillsEvenPeriodicWilsonOSLiteralBoundaryPoincareLowerBoundCertificate

end MathlibAnalytic
end MGAP4D

end