import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenWilsonGibbsBoundaryHilbertSchmidtAnalysis
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSRealizableBoundaryL2DerivedTransferRate
import Mathlib.Tactic

noncomputable section

open MeasureTheory
open scoped InnerProductSpace

namespace MGAP4D
namespace MathlibAnalytic

local instance realizableBoundaryHilbertSchmidtFactorizationSideLengthNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance realizableBoundaryHilbertSchmidtFactorizationSpecialUnitaryIsTopologicalGroup
    (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance realizableBoundaryHilbertSchmidtFactorizationSpecialUnitaryCompactSpace
    (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance realizableBoundaryHilbertSchmidtFactorizationSpecialUnitarySecondCountableTopology
    (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance realizableBoundaryHilbertSchmidtFactorizationSpecialUnitaryMeasurableSpace
    (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance realizableBoundaryHilbertSchmidtFactorizationSpecialUnitaryBorelSpace
    (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

/-- A realizable Wilson one-step boundary factorization in which the analysis
map is no longer abstract.

At scale `n`, the feature space is the actual positive open-half Haar `L²`
space and the analysis map is canonically generated by the Wilson product
kernel `Φₙ(b,x) = sqrt ρₙ(b,x,θx)` through the rectangular
Hilbert--Schmidt/Riesz construction.

The remaining model-specific factorization data are exactly:

* the boundary moments belong to boundary `L²`;
* a synthesis operator from the actual open-half `L²` feature space back to
  boundary `L²`;
* exact intertwining of `synthesis ∘ canonicalAnalysis` with one realizable
  integer lattice-time Wilson OS step.

No mass, contraction constant, or exact numerical value is assumed. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2HilbertSchmidtFactorization
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S)
    (R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)) where
  boundaryMoment_memLp :
    ∀ (n : ℕ)
      (F : (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier),
      MemLp
        (fun b =>
          physicalYangMillsEvenPeriodicWilsonOSBoundaryMoment
            S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n F b)
        2
        (periodicHypercubicEvenBoundaryHaarMeasure (halfExtent n) N)
  synthesis :
    (n : ℕ) →
      PeriodicHypercubicEvenSpecialUnitaryOpenHalfL2 (halfExtent n) N →L[ℝ]
        PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N
  boundaryMoment_hilbertSchmidt_intertwining :
    ∀ (n : ℕ)
      (F : (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).Carrier),
      let Pn :=
        physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
          S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
      (synthesis n).comp
          (periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
            (halfExtent n) N hN (beta n) (hbeta n))
          (physicalYangMillsEvenPeriodicWilsonOSBoundaryMomentL2
            S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
            (Pn.vacuumCenteredCarrier F)
            (boundaryMoment_memLp n (Pn.vacuumCenteredCarrier F))) =
        physicalYangMillsEvenPeriodicWilsonOSBoundaryMomentL2
          S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n
          (R.realizableCarrierTranslation hInvariant n 1
            (Pn.vacuumCenteredCarrier F))
          (boundaryMoment_memLp n
            (R.realizableCarrierTranslation hInvariant n 1
              (Pn.vacuumCenteredCarrier F)))

namespace PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2HilbertSchmidtFactorization

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S}
    {R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}

/-- Forget only the fact that the analysis operator was canonically generated.
This produces the mass-free abstract factorization package of #1506 with the
feature space and analysis map fixed to their actual Wilson Hilbert--Schmidt
realizations. -/
noncomputable def toFactorizedTransferFamily
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2HilbertSchmidtFactorization
      S D halfExtent N hN beta hbeta Q E R hInvariant) :
    PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2FactorizedTransferFamily
      S D halfExtent N hN beta hbeta Q E R hInvariant where
  boundaryMoment_memLp := A.boundaryMoment_memLp
  FeatureState := fun n =>
    PeriodicHypercubicEvenSpecialUnitaryOpenHalfL2 (halfExtent n) N
  featureNormedAddCommGroup := fun _ => inferInstance
  featureNormedSpace := fun _ => inferInstance
  analysis := fun n =>
    periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
      (halfExtent n) N hN (beta n) (hbeta n)
  synthesis := A.synthesis
  boundaryMoment_factorized_intertwining := by
    intro n F
    exact A.boundaryMoment_hilbertSchmidt_intertwining n F

/-- The theorem-generated actual shared-boundary transfer is therefore
`synthesisₙ ∘ canonicalWilsonAnalysisₙ`. -/
noncomputable def boundaryTransfer
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2HilbertSchmidtFactorization
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (n : ℕ) :
    PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N →L[ℝ]
      PeriodicHypercubicEvenSpecialUnitaryBoundaryL2 (halfExtent n) N :=
  A.toFactorizedTransferFamily.boundaryTransfer n

/-- The actual transfer norm is bounded by synthesis norm times the canonical
Wilson Hilbert--Schmidt analysis norm. -/
theorem boundaryTransfer_opNorm_le_synthesis_mul_analysis
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2HilbertSchmidtFactorization
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (n : ℕ) :
    ‖A.boundaryTransfer n‖ ≤
      ‖A.synthesis n‖ *
        ‖periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis
          (halfExtent n) N hN (beta n) (hbeta n)‖ := by
  exact A.toFactorizedTransferFamily.transferFactor_le_factorProduct n

/-- Combining factor submultiplicativity with the canonical Hilbert--Schmidt
bound exposes the remaining quantitative target entirely in terms of the
actual synthesis norm and the explicit Wilson product-kernel `L²` norm. -/
theorem boundaryTransfer_opNorm_le_synthesis_mul_kernel
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2HilbertSchmidtFactorization
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (n : ℕ) :
    ‖A.boundaryTransfer n‖ ≤
      ‖A.synthesis n‖ *
        ‖periodicHypercubicEvenBoundaryCompletedPositiveGramFeatureProductL2
          (halfExtent n) N hN (beta n) (hbeta n)‖ := by
  exact
    (A.boundaryTransfer_opNorm_le_synthesis_mul_analysis n).trans
      (mul_le_mul_of_nonneg_left
        (periodicHypercubicEvenWilsonBoundaryHilbertSchmidtAnalysis_norm_le
          (halfExtent n) N hN (beta n) (hbeta n))
        (norm_nonneg (A.synthesis n)))

/-- The Hilbert--Schmidt factorization canonically produces the actual boundary
transfer family, and hence the derived one-step factor is the norm of this
Wilson-kernel-generated transfer. -/
noncomputable def toBoundaryL2TransferFamily
    (A : PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2HilbertSchmidtFactorization
      S D halfExtent N hN beta hbeta Q E R hInvariant) :
    PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2TransferFamily
      S D halfExtent N hN beta hbeta Q E R hInvariant :=
  A.toFactorizedTransferFamily.toBoundaryL2TransferFamily

end PhysicalYangMillsEvenPeriodicWilsonOSRealizableBoundaryL2HilbertSchmidtFactorization

end MathlibAnalytic
end MGAP4D

end
