import MGAP4D.MathlibAnalytic.LinearMarkovCompression
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSFiniteGibbsHeatBathPositiveTimeObservableDilation
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

namespace PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

variable {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
variable {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}

/-- Repackage a positive-time subalgebra element as an element of its explicit
real submodule. -/
def positiveTimeSubmoduleOfSubalgebra
    (F : D.positiveTimeSubalgebra) :
    D.positiveTimeSubalgebra.toSubmodule :=
  ⟨F.1, F.2⟩

@[simp] theorem positiveTimeSubalgebraOfSubmodule_submoduleOfSubalgebra
    (F : D.positiveTimeSubalgebra) :
    positiveTimeSubalgebraOfSubmodule
        (positiveTimeSubmoduleOfSubalgebra F) = F := by
  rfl

@[simp] theorem positiveTimeSubmoduleOfSubalgebra_subalgebraOfSubmodule
    (F : D.positiveTimeSubalgebra.toSubmodule) :
    positiveTimeSubmoduleOfSubalgebra
        (positiveTimeSubalgebraOfSubmodule F) = F := by
  rfl

namespace PositiveTimeObservableContractionSemigroup

variable {P : D.OSPreHilbertData}

/-- The positive-time observable translation acting on the explicit positive-time
real submodule. -/
def translatedPositiveTimeSubmodule
    (O : P.PositiveTimeObservableContractionSemigroup)
    (t : NNReal)
    (F : D.positiveTimeSubalgebra.toSubmodule) :
    D.positiveTimeSubalgebra.toSubmodule :=
  positiveTimeSubmoduleOfSubalgebra
    (O.translate t (positiveTimeSubalgebraOfSubmodule F))

/-- A time-zero Markov compression for the concrete finite Gibbs heat-bath
spectral semigroup.

Unlike an observable-level dilation, this does not assert the generally false
pointwise identity `tau_t (lift f) = lift (S_t f)`. Instead it packages the
standard Markov identities after time-zero conditional expectation:

`E₀ (lift f) = f` and `E₀ (tau_t (lift f)) = S_t f`. -/
structure FiniteGibbsHeatBathPositiveTimeMarkovCompression
    (L : FiniteLatticeWilsonSystem)
    (O : P.PositiveTimeObservableContractionSemigroup) where
  toLinearMarkovCompression :
    LinearMarkovCompression
      (L.Configuration → ℝ)
      D.positiveTimeSubalgebra.toSubmodule
      (O.translatedPositiveTimeSubmodule)
      (fun t f => L.gibbsObservableHeatBathSpectralSemigroup t f)

namespace FiniteGibbsHeatBathPositiveTimeMarkovCompression

variable {L : FiniteLatticeWilsonSystem}
variable {O : P.PositiveTimeObservableContractionSemigroup}

/-- The time-zero positive-time observable lift. -/
abbrev lift
    (K : FiniteGibbsHeatBathPositiveTimeMarkovCompression L O) :=
  K.toLinearMarkovCompression.lift

/-- The time-zero conditional expectation from positive-time observables back to
finite Gibbs observables. -/
abbrev condition
    (K : FiniteGibbsHeatBathPositiveTimeMarkovCompression L O) :=
  K.toLinearMarkovCompression.condition

/-- The OS-carrier realization generated by the time-zero lift. -/
noncomputable def carrierMap
    (K : FiniteGibbsHeatBathPositiveTimeMarkovCompression L O) :
    (L.Configuration → ℝ) →ₗ[ℝ] P.Carrier :=
  P.carrierOfPositiveTimeLinearMap.comp K.lift

@[simp] theorem carrierMap_apply
    (K : FiniteGibbsHeatBathPositiveTimeMarkovCompression L O)
    (f : L.Configuration → ℝ) :
    K.carrierMap f =
      P.carrierOfPositiveTime
        (positiveTimeSubalgebraOfSubmodule (K.lift f)) :=
  rfl

@[simp] theorem positiveTimeElement_carrierMap
    (K : FiniteGibbsHeatBathPositiveTimeMarkovCompression L O)
    (f : L.Configuration → ℝ) :
    P.positiveTimeElement (K.carrierMap f) =
      positiveTimeSubalgebraOfSubmodule (K.lift f) := by
  rw [carrierMap_apply, P.positiveTimeElement_carrierOfPositiveTime]

/-- Factorization of represented positive-time states through the time-zero
conditional expectation generates exact state realization of every lifted
finite observable. -/
theorem physicalState_carrierMap_eq
    (K : FiniteGibbsHeatBathPositiveTimeMarkovCompression L O)
    (embed : (L.Configuration → ℝ) → P.PhysicalHilbert)
    (state_eq_embed_condition : ∀ F,
      P.physicalState
          (P.carrierOfPositiveTime
            (positiveTimeSubalgebraOfSubmodule F)) =
        embed (K.condition F))
    (f : L.Configuration → ℝ) :
    P.physicalState (K.carrierMap f) = embed f := by
  exact K.toLinearMarkovCompression.state_lift_eq
    (state := fun F =>
      P.physicalState
        (P.carrierOfPositiveTime
          (positiveTimeSubalgebraOfSubmodule F)))
    (embed := embed)
    state_eq_embed_condition
    f

/-- The Markov property after time-zero conditioning generates exact translated
OS-state intertwining with the finite Gibbs heat-bath semigroup. -/
theorem physicalState_translate_carrierMap_eq
    (K : FiniteGibbsHeatBathPositiveTimeMarkovCompression L O)
    (embed : (L.Configuration → ℝ) → P.PhysicalHilbert)
    (state_eq_embed_condition : ∀ F,
      P.physicalState
          (P.carrierOfPositiveTime
            (positiveTimeSubalgebraOfSubmodule F)) =
        embed (K.condition F))
    (t : NNReal) (f : L.Configuration → ℝ) :
    P.physicalState
        (P.carrierOfPositiveTime
          (O.translate t (P.positiveTimeElement (K.carrierMap f)))) =
      embed (L.gibbsObservableHeatBathSpectralSemigroup t f) := by
  rw [K.positiveTimeElement_carrierMap]
  simpa [translatedPositiveTimeSubmodule] using
    K.toLinearMarkovCompression.state_translate_lift_eq
      (state := fun F =>
        P.physicalState
          (P.carrierOfPositiveTime
            (positiveTimeSubalgebraOfSubmodule F)))
      (embed := embed)
      state_eq_embed_condition
      t f

end FiniteGibbsHeatBathPositiveTimeMarkovCompression
end PositiveTimeObservableContractionSemigroup
end PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData

end

end MathlibAnalytic
end MGAP4D
