import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonIntrinsicCenteredRateLimit
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSRealizableCenteredPhysicalExcitationFloorDecay
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSExponentialGapSlope
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSClosedMassGapTransfer
import MGAP4D.MathlibAnalytic.PhysicalYangMillsGaugeInvariantOSOptimalRayleighCoercivity
import Mathlib.Tactic

noncomputable section

open Filter Set Topology
open scoped InnerProductSpace

namespace MGAP4D
namespace MathlibAnalytic

local instance intrinsicRatePhysicalSideLengthNeZero (H : ℕ) :
    NeZero (PeriodicHypercubicEvenSideLength H) := ⟨by
  simp [PeriodicHypercubicEvenSideLength]⟩

local instance intrinsicRatePhysicalSpecialUnitaryIsTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance intrinsicRatePhysicalSpecialUnitaryCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance intrinsicRatePhysicalSpecialUnitarySecondCountableTopology (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance intrinsicRatePhysicalSpecialUnitaryMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance intrinsicRatePhysicalSpecialUnitaryBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

namespace PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence

set_option maxHeartbeats 800000

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S}
    {R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}

/-- Each actual centered one-step Wilson factor is exactly the exponential of
its own intrinsic logarithmic rate times the physical lattice spacing. -/
theorem centeredTransferFactor_eq_exp_neg_intrinsicRate_mul_spacing
    (C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (n : ℕ) :
    C.boundedAnalysis.centeredTransferFactor n =
      Real.exp
        (-physicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredMassRate
            C.boundedAnalysis n * S.latticeSpacing n) := by
  symm
  unfold physicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredMassRate
  have hspacing : S.latticeSpacing n ≠ 0 :=
    ne_of_gt (S.latticeSpacing_pos n)
  have harg :
      -(-Real.log (C.boundedAnalysis.centeredTransferFactor n) /
          S.latticeSpacing n) * S.latticeSpacing n =
        Real.log (C.boundedAnalysis.centeredTransferFactor n) := by
    field_simp [hspacing]
  rw [harg, Real.exp_log (C.transferFactor_pos n)]

/-- The genuine floor-selected powers of the actual centered Wilson operator
norm converge to the exponential generated by the rate limit reconstructed from
that same norm sequence.  No selected continuum mass occurs. -/
theorem floorCenteredTransferFactorPow_tendsto
    (C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (t : NNReal) :
    Tendsto
      (fun n =>
        (C.boundedAnalysis.centeredTransferFactor n) ^
          physicalTemporalFloorNatStep S.latticeSpacing t n)
      atTop
      (nhds (Real.exp (-C.limit * (t : ℝ)))) := by
  have htime :=
    physicalTemporalFloorNatStep_tendsto
      S.latticeSpacing S.latticeSpacing_pos S.latticeSpacing_tendsto_zero t
  have harg :
      Tendsto
        (fun n =>
          -physicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredMassRate
              C.boundedAnalysis n *
            ((physicalTemporalFloorNatStep S.latticeSpacing t n : ℝ) *
              S.latticeSpacing n))
        atTop
        (nhds (-C.limit * (t : ℝ))) :=
    C.rate_tendsto_limit.neg.mul htime
  have hexp := harg.rexp
  convert hexp using 1
  funext n
  rw [C.centeredTransferFactor_eq_exp_neg_intrinsicRate_mul_spacing n]
  rw [← Real.exp_nat_mul]
  congr 1
  ring

/-- Equivalent form using the completed finite physical excitation operator.
Completion preserves the centered operator norm exactly. -/
theorem floorPhysicalExcitationOpNormPow_tendsto
    (C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (t : NNReal) :
    Tendsto
      (fun n =>
        ‖C.boundedAnalysis.physicalExcitationOneStepOperator n‖ ^
          physicalTemporalFloorNatStep S.latticeSpacing t n)
      atTop
      (nhds (Real.exp (-C.limit * (t : ℝ)))) := by
  simpa only [
    C.boundedAnalysis.physicalExcitationOneStepOperator_opNorm_eq_centeredTransferFactor]
    using C.floorCenteredTransferFactorPow_tendsto t

/-- Limit transfer for arbitrary varying finite physical-excitation states. -/
theorem floorPhysicalExcitationIterate_limit_norm_le
    (C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (t : NNReal)
    (psi : (n : ℕ) →
      (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).VacuumOrthogonalHilbert)
    {inputNormLimit evolvedNormLimit : ℝ}
    (hInput : Tendsto (fun n => ‖psi n‖) atTop (nhds inputNormLimit))
    (hEvolved :
      Tendsto
        (fun n =>
          ‖(fun phi :
              (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
                S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).VacuumOrthogonalHilbert =>
              C.boundedAnalysis.physicalExcitationOneStepOperator n phi)^[
                physicalTemporalFloorNatStep S.latticeSpacing t n] (psi n)‖)
        atTop (nhds evolvedNormLimit)) :
    evolvedNormLimit ≤ Real.exp (-C.limit * (t : ℝ)) * inputNormLimit := by
  apply le_of_tendsto_of_tendsto hEvolved
    ((C.floorCenteredTransferFactorPow_tendsto t).mul hInput)
  exact Filter.Eventually.of_forall fun n =>
    C.boundedAnalysis.physicalExcitationOneStepOperator_iterate_norm_le
      n (physicalTemporalFloorNatStep S.latticeSpacing t n) (psi n)

end PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence

/-- Mass-free common-carrier convergence for an intrinsic finite Wilson rate
sequence.  The only continuum numerical value used downstream is the unique
limit reconstructed from the actual finite excitation operator norms. -/
structure PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer
    (S : PhysicalFourDimensionalYangMillsSymmetryLimit)
    (D : PhysicalYangMillsGaugeInvariantOSReflectionData S)
    (halfExtent : ℕ → ℕ)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℕ → ℝ)
    (hbeta : ∀ n, 0 ≤ beta n)
    (Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta)
    (E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S)
    (R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E)
    (hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n))
    (C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q E R hInvariant)
    (P : D.OSPreHilbertData)
    (T : P.StronglyContinuousPhysicalSemigroup) where
  approximateExcitation :
    (n : ℕ) → P.VacuumOrthogonalHilbert →L[ℝ]
      (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
        S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).VacuumOrthogonalHilbert
  approximate_norm_tendsto :
    ∀ psi : P.VacuumOrthogonalHilbert,
      Tendsto (fun n => ‖approximateExcitation n psi‖)
        atTop (nhds ‖psi‖)
  evolved_norm_tendsto :
    ∀ (t : NNReal) (psi : P.VacuumOrthogonalHilbert),
      Tendsto
        (fun n =>
          ‖(fun phi :
              (physical_yang_mills_evenPeriodicWilsonOS_approximating_preHilbertData
                S D halfExtent N hN beta hbeta Q.toWeakStarBridge hInvariant n).VacuumOrthogonalHilbert =>
              C.boundedAnalysis.physicalExcitationOneStepOperator n phi)^[
                physicalTemporalFloorNatStep S.latticeSpacing t n]
              (approximateExcitation n psi)‖)
        atTop
        (nhds ‖T.toPhysicalSemigroup.operator t (psi : P.PhysicalHilbert)‖)

namespace PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer

set_option maxHeartbeats 800000

variable
    {S : PhysicalFourDimensionalYangMillsSymmetryLimit}
    {D : PhysicalYangMillsGaugeInvariantOSReflectionData S}
    {halfExtent : ℕ → ℕ}
    {N : ℕ}
    {hN : 0 < N}
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    {beta : ℕ → ℝ}
    {hbeta : ∀ n, 0 ≤ beta n}
    {Q : PhysicalYangMillsEvenPeriodicWilsonOSCoherentPositiveTimePullback
      S D halfExtent N hN beta hbeta}
    {E : PhysicalFourDimensionalYangMillsContinuumEuclideanTimeTranslation S}
    {R : PhysicalYangMillsEvenPeriodicWilsonOSRealizablePositiveTemporalCovariance
      S D halfExtent N hN beta hbeta Q E}
    {hInvariant : ∀ n,
      D.WeakStarReflectionInvariant
        (physicalYangMillsApproximatingGaugeInvariantWeakStarState S n)}
    {C : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicCenteredRateConvergence
      S D halfExtent N hN beta hbeta Q E R hInvariant}
    {P : D.OSPreHilbertData}
    {T : P.StronglyContinuousPhysicalSemigroup}

/-- The intrinsic finite Wilson rate limit controls the actual continuum
vacuum-orthogonal OS semigroup. -/
theorem continuumExcitation_norm_le_exp
    (G : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer
      S D halfExtent N hN beta hbeta Q E R hInvariant C P T)
    (t : NNReal)
    (psi : P.VacuumOrthogonalHilbert) :
    ‖T.toPhysicalSemigroup.operator t (psi : P.PhysicalHilbert)‖ ≤
      Real.exp (-C.limit * (t : ℝ)) * ‖psi‖ := by
  exact
    C.floorPhysicalExcitationIterate_limit_norm_le
      t
      (fun n => G.approximateExcitation n psi)
      (G.approximate_norm_tendsto psi)
      (G.evolved_norm_tendsto t psi)

/-- Once strict positivity of the derived rate limit is established from the
Wilson model, it gives the continuum vacuum-semigroup gap slope.  The mass
value is `C.limit`, reconstructed from the finite operator sequence. -/
noncomputable def toVacuumSemigroupGapSlope
    (G : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer
      S D halfExtent N hN beta hbeta Q E R hInvariant C P T)
    (hlimit_pos : 0 < C.limit) :
    T.VacuumSemigroupGapSlope where
  mass := C.limit
  mass_pos := hlimit_pos
  decayFactor := fun t => Real.exp (-C.limit * (t : ℝ))
  slope_tendsto := tendsto_nnreal_inv_mul_one_sub_exp_neg_mul C.limit
  decay := by
    intro t psi hpsi
    have hmem : psi ∈ P.vacuumOrthogonal := by
      rw [P.mem_vacuumOrthogonal_iff, real_inner_comm]
      exact hpsi
    let psiOrth : P.VacuumOrthogonalHilbert := ⟨psi, hmem⟩
    have h := G.continuumExcitation_norm_le_exp t psiOrth
    simpa [psiOrth] using h

/-- The actual graph-closed physical Hamiltonian has Rayleigh quotient at least
the positive intrinsic Wilson rate limit. -/
theorem closedRightHamiltonian_inner_ge_limit_mul_norm_sq
    (G : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer
      S D halfExtent N hN beta hbeta Q E R hInvariant C P T)
    (hlimit_pos : 0 < C.limit)
    (hP : P.IsNormalized)
    (psi : T.closedRightHamiltonian.domain)
    (hpsi : inner ℝ (psi : P.PhysicalHilbert) P.vacuum = 0) :
    C.limit * ‖(psi : P.PhysicalHilbert)‖ ^ 2 ≤
      inner ℝ (T.closedRightHamiltonian psi) (psi : P.PhysicalHilbert) :=
  PhysicalYangMillsGaugeInvariantOSReflectionData.OSPreHilbertData.StronglyContinuousPhysicalSemigroup.VacuumSemigroupGapSlope.closedRightHamiltonian_inner_ge_mass_mul_norm_sq
    T (G.toVacuumSemigroupGapSlope hlimit_pos) hP psi hpsi

/-- The derived intrinsic Wilson rate limit is therefore an actual physical
Hamiltonian Rayleigh lower bound. -/
theorem limit_mem_physicalYangMillsRayleighLowerBoundSet
    (G : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer
      S D halfExtent N hN beta hbeta Q E R hInvariant C P T)
    (hlimit_pos : 0 < C.limit)
    (hP : P.IsNormalized) :
    C.limit ∈ T.physicalYangMillsRayleighLowerBoundSet := by
  intro psi _hpsiNonzero horthogonal
  exact G.closedRightHamiltonian_inner_ge_limit_mul_norm_sq
    hlimit_pos hP psi horthogonal

/-- Consequently the continuum rate reconstructed from the actual finite Wilson
excitation operator norms lies below the intrinsic variational physical
Yang--Mills mass. -/
theorem limit_le_physicalYangMillsMass
    (G : PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer
      S D halfExtent N hN beta hbeta Q E R hInvariant C P T)
    (hlimit_pos : 0 < C.limit)
    (hP : P.IsNormalized)
    (W : T.PhysicalYangMillsExcitationDomainWitness) :
    C.limit ≤ T.physicalYangMillsMass :=
  T.rayleighLowerBound_le_physicalYangMillsMass
    W (G.limit_mem_physicalYangMillsRayleighLowerBoundSet hlimit_pos hP)

end PhysicalYangMillsEvenPeriodicWilsonOSIntrinsicRateCommonCarrierTransfer

end MathlibAnalytic
end MGAP4D

end