import MGAP4D.MathlibAnalytic.ProbabilityMeasureMutualDominationL2MeanDifference

open MGAP4D.MathlibAnalytic
open MeasureTheory
open ProbabilityTheory
open scoped ENNReal

noncomputable section

#check probabilityMeasure_nonnegative_integral_difference_abs_le_of_pairwise_le_smul
#check probabilityMeasure_integral_difference_abs_le_integral_abs_of_pairwise_le_smul
#check probabilityMeasure_integral_abs_sq_le_integral_sq
#check probabilityMeasure_integral_sq_sub_const_eq_variance_add_mean_sub_sq
#check probabilityMeasure_integral_difference_sq_le_variance_sum_of_pairwise_le_smul

#print axioms probabilityMeasure_nonnegative_integral_difference_abs_le_of_pairwise_le_smul
#print axioms probabilityMeasure_integral_difference_abs_le_integral_abs_of_pairwise_le_smul
#print axioms probabilityMeasure_integral_abs_sq_le_integral_sq
#print axioms probabilityMeasure_integral_sq_sub_const_eq_variance_add_mean_sub_sq
#print axioms probabilityMeasure_integral_difference_sq_le_variance_sum_of_pairwise_le_smul

end
