import MGAP4D.MathlibAnalytic.R4TPReadyAPI

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

namespace EuclideanYangMillsR4HilbertReconstructionQuotient

theorem quotientPairCoordinateRoundTripProp_direct_components_handoff :=
  quotientPairCoordinateRoundTripProp_direct_components_ready

theorem rangePairCoordinateRoundTripProp_direct_components_handoff :=
  rangePairCoordinateRoundTripProp_direct_components_ready

theorem quotientPairCoordinateRoundTripProp_symmetric_components_handoff :=
  quotientPairCoordinateRoundTripProp_symmetric_components_ready

theorem rangePairCoordinateRoundTripProp_symmetric_components_handoff :=
  rangePairCoordinateRoundTripProp_symmetric_components_ready

theorem quotientPairCoordinateRoundTripProp_direct_components_from_symmetric_handoff :=
  quotientPairCoordinateRoundTripProp_direct_components_from_symmetric_ready

theorem rangePairCoordinateRoundTripProp_direct_components_from_symmetric_handoff :=
  rangePairCoordinateRoundTripProp_direct_components_from_symmetric_ready

theorem quotientPairCoordinateRoundTripProp_symmetric_components_from_direct_handoff :=
  quotientPairCoordinateRoundTripProp_symmetric_components_from_direct_ready

theorem rangePairCoordinateRoundTripProp_symmetric_components_from_direct_handoff :=
  rangePairCoordinateRoundTripProp_symmetric_components_from_direct_ready

theorem quotientPairCoordinateRoundTripProp_inverse_handoff :=
  quotientPairCoordinateRoundTripProp_inverse_ready

theorem quotientPairCoordinateRoundTripProp_forward_handoff :=
  quotientPairCoordinateRoundTripProp_forward_ready

theorem rangePairCoordinateRoundTripProp_forward_handoff :=
  rangePairCoordinateRoundTripProp_forward_ready

theorem rangePairCoordinateRoundTripProp_inverse_handoff :=
  rangePairCoordinateRoundTripProp_inverse_ready

theorem quotientPairCoordinateRoundTripProp_symmetric_inverse_handoff :=
  quotientPairCoordinateRoundTripProp_symmetric_inverse_ready

theorem quotientPairCoordinateRoundTripProp_symmetric_forward_handoff :=
  quotientPairCoordinateRoundTripProp_symmetric_forward_ready

theorem rangePairCoordinateRoundTripProp_symmetric_forward_handoff :=
  rangePairCoordinateRoundTripProp_symmetric_forward_ready

theorem rangePairCoordinateRoundTripProp_symmetric_inverse_handoff :=
  rangePairCoordinateRoundTripProp_symmetric_inverse_ready

theorem quotientPairCoordinateRoundTripProp_inverse_symm_handoff :=
  quotientPairCoordinateRoundTripProp_inverse_symm_ready

theorem quotientPairCoordinateRoundTripProp_forward_symm_handoff :=
  quotientPairCoordinateRoundTripProp_forward_symm_ready

theorem rangePairCoordinateRoundTripProp_forward_symm_handoff :=
  rangePairCoordinateRoundTripProp_forward_symm_ready

theorem rangePairCoordinateRoundTripProp_inverse_symm_handoff :=
  rangePairCoordinateRoundTripProp_inverse_symm_ready

theorem quotientPairCoordinateRoundTripProp_inverse_direct_handoff :=
  quotientPairCoordinateRoundTripProp_inverse_direct_ready

theorem quotientPairCoordinateRoundTripProp_forward_direct_handoff :=
  quotientPairCoordinateRoundTripProp_forward_direct_ready

theorem rangePairCoordinateRoundTripProp_forward_direct_handoff :=
  rangePairCoordinateRoundTripProp_forward_direct_ready

theorem rangePairCoordinateRoundTripProp_inverse_direct_handoff :=
  rangePairCoordinateRoundTripProp_inverse_direct_ready

theorem quotientPairCoordinateRoundTripProp_recompose_direct_handoff :=
  quotientPairCoordinateRoundTripProp_recompose_direct_ready

theorem rangePairCoordinateRoundTripProp_recompose_direct_handoff :=
  rangePairCoordinateRoundTripProp_recompose_direct_ready

theorem quotientPairCoordinateRoundTripProp_recompose_symmetric_handoff :=
  quotientPairCoordinateRoundTripProp_recompose_symmetric_ready

theorem rangePairCoordinateRoundTripProp_recompose_symmetric_handoff :=
  rangePairCoordinateRoundTripProp_recompose_symmetric_ready

theorem quotientPairCoordinateRoundTripProp_of_direct_components_handoff :=
  quotientPairCoordinateRoundTripProp_of_direct_components_ready

theorem rangePairCoordinateRoundTripProp_of_direct_components_handoff :=
  rangePairCoordinateRoundTripProp_of_direct_components_ready

end EuclideanYangMillsR4HilbertReconstructionQuotient

end

end MathlibAnalytic
end MGAP4D
