import Mathlib.Analysis.InnerProductSpace.TensorProduct
import Mathlib.Analysis.InnerProductSpace.Completion

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators TensorProduct

noncomputable section

/-- A real Hilbert feature realization of a scalar kernel. -/
structure RealHilbertKernelFeature
    (X : Type)
    (kernel : X → X → ℝ) where
  FeatureHilbert : Type
  [featureNormedAddCommGroup : NormedAddCommGroup FeatureHilbert]
  [featureInnerProductSpace : InnerProductSpace ℝ FeatureHilbert]
  [featureCompleteSpace : CompleteSpace FeatureHilbert]
  feature : X → FeatureHilbert
  kernel_eq_inner :
    ∀ x y, kernel x y = inner ℝ (feature x) (feature y)

attribute [instance]
  RealHilbertKernelFeature.featureNormedAddCommGroup
  RealHilbertKernelFeature.featureInnerProductSpace
  RealHilbertKernelFeature.featureCompleteSpace

/-- The constant-one kernel has the one-dimensional real feature realization. -/
noncomputable def RealHilbertKernelFeature.one
    (X : Type) :
    RealHilbertKernelFeature X (fun _ _ => 1) where
  FeatureHilbert := ℝ
  feature := fun _ => 1
  kernel_eq_inner x y := by simp

/-- The pointwise sum of two Hilbert kernels is realized by the Hilbert product
of their feature spaces. -/
noncomputable def RealHilbertKernelFeature.add
    {X : Type}
    {kernel₁ kernel₂ : X → X → ℝ}
    (C₁ : RealHilbertKernelFeature X kernel₁)
    (C₂ : RealHilbertKernelFeature X kernel₂) :
    RealHilbertKernelFeature X
      (fun x y => kernel₁ x y + kernel₂ x y) where
  FeatureHilbert := C₁.FeatureHilbert × C₂.FeatureHilbert
  feature := fun x => (C₁.feature x, C₂.feature x)
  kernel_eq_inner x y := by
    rw [C₁.kernel_eq_inner, C₂.kernel_eq_inner]
    simp

/-- Multiplication of a Hilbert kernel by a nonnegative scalar is realized by
scaling its feature map by the square root of that scalar. -/
noncomputable def RealHilbertKernelFeature.nonnegSMul
    {X : Type}
    {kernel : X → X → ℝ}
    (c : ℝ)
    (hc : 0 ≤ c)
    (C : RealHilbertKernelFeature X kernel) :
    RealHilbertKernelFeature X (fun x y => c * kernel x y) where
  FeatureHilbert := C.FeatureHilbert
  feature := fun x => Real.sqrt c • C.feature x
  kernel_eq_inner x y := by
    simp only [real_inner_smul_left, real_inner_smul_right]
    rw [← C.kernel_eq_inner]
    nlinarith [Real.sq_sqrt hc]

/-- The pointwise product of two Hilbert kernels is realized by the completed
algebraic tensor product of their feature spaces. -/
noncomputable def RealHilbertKernelFeature.mul
    {X : Type}
    {kernel₁ kernel₂ : X → X → ℝ}
    (C₁ : RealHilbertKernelFeature X kernel₁)
    (C₂ : RealHilbertKernelFeature X kernel₂) :
    RealHilbertKernelFeature X
      (fun x y => kernel₁ x y * kernel₂ x y) where
  FeatureHilbert :=
    UniformSpace.Completion
      (C₁.FeatureHilbert ⊗[ℝ] C₂.FeatureHilbert)
  feature := fun x =>
    ((C₁.feature x ⊗ₜ[ℝ] C₂.feature x :
      C₁.FeatureHilbert ⊗[ℝ] C₂.FeatureHilbert) :
      UniformSpace.Completion
        (C₁.FeatureHilbert ⊗[ℝ] C₂.FeatureHilbert))
  kernel_eq_inner x y := by
    rw [UniformSpace.Completion.inner_coe, TensorProduct.inner_tmul]
    rw [← C₁.kernel_eq_inner, ← C₂.kernel_eq_inner]

/-- Every natural pointwise power of a Hilbert kernel has a Hilbert feature
realization.  The successor step uses the completed tensor-product product
constructor. -/
noncomputable def RealHilbertKernelFeature.pow
    {X : Type}
    {kernel : X → X → ℝ}
    (C : RealHilbertKernelFeature X kernel) :
    ∀ n : ℕ, RealHilbertKernelFeature X (fun x y => kernel x y ^ n) :=
  fun n =>
    match n with
    | 0 => by
        simpa using RealHilbertKernelFeature.one X
    | m + 1 => by
        simpa [pow_succ, mul_comm] using
          RealHilbertKernelFeature.mul C (RealHilbertKernelFeature.pow C m)

/-- The degree-`n` partial exponential series of a scalar kernel, with scale
`c`.  It is defined recursively so its Hilbert feature can be generated by the
same Type-valued recursion as the finite tensor powers. -/
def RealHilbertKernelFeature.exponentialPartialKernel
    {X : Type}
    (kernel : X → X → ℝ)
    (c : ℝ) : ℕ → X → X → ℝ :=
  fun n =>
    match n with
    | 0 => fun _ _ => 1
    | m + 1 => fun x y =>
        RealHilbertKernelFeature.exponentialPartialKernel kernel c m x y +
          (c ^ (m + 1) / (Nat.factorial (m + 1) : ℝ)) *
            kernel x y ^ (m + 1)

/-- A nonnegative-scale finite exponential series of a Hilbert kernel is again
a Hilbert kernel.  This is the finite symmetric-Fock approximation: each power
uses a completed tensor product, each coefficient is inserted by square-root
feature scaling, and successive terms are joined by Hilbert products. -/
noncomputable def RealHilbertKernelFeature.exponentialPartial
    {X : Type}
    {kernel : X → X → ℝ}
    (C : RealHilbertKernelFeature X kernel)
    (c : ℝ)
    (hc : 0 ≤ c) :
    ∀ n : ℕ,
      RealHilbertKernelFeature X
        (RealHilbertKernelFeature.exponentialPartialKernel kernel c n) :=
  fun n =>
    match n with
    | 0 => by
        simpa [RealHilbertKernelFeature.exponentialPartialKernel] using
          RealHilbertKernelFeature.one X
    | m + 1 => by
        have hCoefficient :
            0 ≤ c ^ (m + 1) / (Nat.factorial (m + 1) : ℝ) := by
          exact div_nonneg (pow_nonneg hc _) (by positivity)
        simpa [RealHilbertKernelFeature.exponentialPartialKernel] using
          RealHilbertKernelFeature.add
            (RealHilbertKernelFeature.exponentialPartial C c hc m)
            (RealHilbertKernelFeature.nonnegSMul
              (c ^ (m + 1) / (Nat.factorial (m + 1) : ℝ))
              hCoefficient
              (RealHilbertKernelFeature.pow C (m + 1)))

/-- The recursively generated finite exponential feature has exactly the
partial exponential kernel as its inner product. -/
theorem RealHilbertKernelFeature.exponentialPartial_kernel_eq_inner
    {X : Type}
    {kernel : X → X → ℝ}
    (C : RealHilbertKernelFeature X kernel)
    (c : ℝ)
    (hc : 0 ≤ c)
    (n : ℕ)
    (x y : X) :
    RealHilbertKernelFeature.exponentialPartialKernel kernel c n x y =
      inner ℝ
        ((RealHilbertKernelFeature.exponentialPartial C c hc n).feature x)
        ((RealHilbertKernelFeature.exponentialPartial C c hc n).feature y) :=
  (RealHilbertKernelFeature.exponentialPartial C c hc n).kernel_eq_inner x y

/-- A finite ordered product of Hilbert kernels has a Hilbert feature
realization, constructed recursively by completed tensor products.

A list is used rather than `Finset.induction_on` because the result is
Type-valued: each insertion changes the completed tensor-product feature
space.  In the Wilson application the list is the finite ordered list of
plaquettes crossing the reflection plane. -/
noncomputable def RealHilbertKernelFeature.listProd
    {X ι : Type}
    (indices : List ι)
    (kernel : ι → X → X → ℝ)
    (C : ∀ i, RealHilbertKernelFeature X (kernel i)) :
    RealHilbertKernelFeature X
      (fun x y => (indices.map fun i => kernel i x y).prod) :=
  match indices with
  | [] => by
      simpa using RealHilbertKernelFeature.one X
  | i :: rest => by
      simpa using
        RealHilbertKernelFeature.mul (C i)
          (RealHilbertKernelFeature.listProd rest kernel C)

/-- The feature inner product generated by `listProd` is exactly the original
finite ordered kernel product. -/
theorem RealHilbertKernelFeature.listProd_kernel_eq_inner
    {X ι : Type}
    (indices : List ι)
    (kernel : ι → X → X → ℝ)
    (C : ∀ i, RealHilbertKernelFeature X (kernel i))
    (x y : X) :
    (indices.map fun i => kernel i x y).prod =
      inner ℝ
        ((RealHilbertKernelFeature.listProd indices kernel C).feature x)
        ((RealHilbertKernelFeature.listProd indices kernel C).feature y) :=
  (RealHilbertKernelFeature.listProd indices kernel C).kernel_eq_inner x y

end

end MathlibAnalytic
end MGAP4D
