import MGAP4D.MathlibAnalytic.RealHilbertProjectionSweepTargetCrossResidualTelescoping
import Mathlib.Tactic

/-!
# Linear forcing/feedback decomposition of one target-cross residual

The target-cross residual generated by one source update is

  (I - P_target) (I - P_source) x.

This file packages that expression as a continuous linear map and decomposes
its input into the target-fixed component and the current target residual:

  x = P_target x + (x - P_target x).

Hence

  cross(target, source, x)
    = cross(target, source, P_target x)
      + cross(target, source, x - P_target x).

The first term is the noncommutativity forcing.  It vanishes whenever the
source and target projections commute and the target projection is
idempotent.  The second term is the feedback acting on the already-existing
target residual.

This is purely Hilbert-linear algebra.  No norm estimate, probability input,
cardinality factor, or commutativity assumption is imposed unless explicitly
stated by the vanishing theorem.
-/

namespace MGAP4D.MathlibAnalytic

noncomputable section

/-- Continuous linear operator whose value is the one-step target-cross
residual. -/
noncomputable def realHilbertProjectionSweepTargetCrossResidualLinearMap
    {E C : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    (P : C → E →L[ℝ] E)
    (target source : C) :
    E →L[ℝ] E :=
  (ContinuousLinearMap.id ℝ E - P target).comp
    (ContinuousLinearMap.id ℝ E - P source)

/-- The operator form agrees definitionally with the existing target-cross
residual vector. -/
theorem realHilbertProjectionSweepTargetCrossResidualLinearMap_apply
    {E C : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    (P : C → E →L[ℝ] E)
    (target source : C)
    (x : E) :
    realHilbertProjectionSweepTargetCrossResidualLinearMap
        P target source x =
      realHilbertProjectionSweepTargetCrossResidual
        P target source x := by
  simp [
    realHilbertProjectionSweepTargetCrossResidualLinearMap,
    realHilbertProjectionSweepTargetCrossResidual]

/-- Exact forcing/feedback decomposition with respect to the distinguished
target projection. -/
theorem realHilbertProjectionSweepTargetCrossResidual_eq_projected_add_residual
    {E C : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    (P : C → E →L[ℝ] E)
    (target source : C)
    (x : E) :
    realHilbertProjectionSweepTargetCrossResidual P target source x =
      realHilbertProjectionSweepTargetCrossResidual
          P target source (P target x) +
        realHilbertProjectionSweepTargetCrossResidual
          P target source (x - P target x) := by
  let L :=
    realHilbertProjectionSweepTargetCrossResidualLinearMap
      P target source
  have hx : P target x + (x - P target x) = x := by
    abel
  have hLinear :
      L x =
        L (P target x) +
          L (x - P target x) := by
    rw [← map_add, hx]
  simpa [
    L,
    realHilbertProjectionSweepTargetCrossResidualLinearMap_apply] using
    hLinear

/-- If the source and target projections commute and the target projection is
idempotent, the forcing generated from the target-fixed component vanishes
exactly. -/
theorem realHilbertProjectionSweepTargetCrossResidual_projected_eq_zero_of_commute
    {E C : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    (P : C → E →L[ℝ] E)
    (target source : C)
    (hIdem :
      (P target).comp (P target) = P target)
    (hComm :
      (P target).comp (P source) =
        (P source).comp (P target))
    (x : E) :
    realHilbertProjectionSweepTargetCrossResidual
        P target source (P target x) = 0 := by
  have hIdemApply : P target (P target x) = P target x := by
    have h :=
      congrArg
        (fun T : E →L[ℝ] E => T x)
        hIdem
    simpa using h
  have hCommApply :
      P target (P source (P target x)) =
        P source (P target x) := by
    have h :=
      congrArg
        (fun T : E →L[ℝ] E => T (P target x))
        hComm
    simpa [hIdemApply] using h
  unfold realHilbertProjectionSweepTargetCrossResidual
  rw [map_sub, hIdemApply, hCommApply]
  abel

end

end MGAP4D.MathlibAnalytic
