import MGAP4D.MathlibAnalytic.RealHilbertRangeInvariantProjectionCommute

namespace MGAP4D.MathlibAnalytic

#check realHilbertProjection_commute_of_range_invariant
#check realHilbertProjectionFamily_commute_of_range_invariant

end MGAP4D.MathlibAnalytic
