import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- Powers of a continuous real-linear operator preserve a real eigenvector
and raise its eigenvalue to the matching natural power. -/
theorem realContinuousLinearMap_pow_apply_of_apply_eq_smul
    {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    (T : E →L[ℝ] E)
    (v : E)
    (a : ℝ)
    (hTv : T v = a • v)
    (m : ℕ) :
    (T ^ m) v = (a ^ m) • v := by
  induction m with
  | zero => simp
  | succ m ih =>
      rw [pow_succ]
      change (T ^ m) (T v) = _
      rw [hTv, map_smul, ih]
      simp [pow_succ, smul_smul, mul_comm]

set_option maxHeartbeats 1000000 in
/-- The Banach-algebra exponential of a continuous real-linear operator acts
on a real eigenvector by the scalar real exponential of the eigenvalue. -/
theorem normedSpace_exp_apply_of_real_eigenvector
    {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    [CompleteSpace E]
    (T : E →L[ℝ] E)
    (v : E)
    (a : ℝ)
    (hTv : T v = a • v) :
    NormedSpace.exp T v = Real.exp a • v := by
  have hTmem :
      T ∈ Metric.eball (0 : E →L[ℝ] E)
        (NormedSpace.expSeries ℝ (E →L[ℝ] E)).radius := by
    rw [NormedSpace.expSeries_radius_eq_top]
    exact edist_lt_top _ _
  have hTsum :
      HasSum
        (fun m : ℕ => ((Nat.factorial m : ℝ)⁻¹) • T ^ m)
        (NormedSpace.exp T) :=
    NormedSpace.expSeries_hasSum_exp_of_mem_ball' T hTmem
  have hTsum_apply :
      HasSum
        (fun m : ℕ => (((Nat.factorial m : ℝ)⁻¹) • T ^ m) v)
        (NormedSpace.exp T v) :=
    (ContinuousLinearMap.apply ℝ E v).hasSum hTsum
  have hamem :
      a ∈ Metric.eball (0 : ℝ)
        (NormedSpace.expSeries ℝ ℝ).radius := by
    rw [NormedSpace.expSeries_radius_eq_top]
    exact edist_lt_top _ _
  have hasum :
      HasSum
        (fun m : ℕ => ((Nat.factorial m : ℝ)⁻¹) * a ^ m)
        (NormedSpace.exp a) := by
    simpa [smul_eq_mul] using
      (NormedSpace.expSeries_hasSum_exp_of_mem_ball' a hamem)
  have hasum_smul :
      HasSum
        (fun m : ℕ => (((Nat.factorial m : ℝ)⁻¹) * a ^ m) • v)
        ((NormedSpace.exp a) • v) :=
    hasum.smul_const v
  have hterms :
      (fun m : ℕ => (((Nat.factorial m : ℝ)⁻¹) * a ^ m) • v) =
        (fun m : ℕ => (((Nat.factorial m : ℝ)⁻¹) • T ^ m) v) := by
    funext m
    rw [ContinuousLinearMap.smul_apply,
      realContinuousLinearMap_pow_apply_of_apply_eq_smul T v a hTv]
    simp [smul_smul]
  have hseries :
      NormedSpace.exp T v = (NormedSpace.exp a) • v := by
    apply HasSum.unique hTsum_apply
    rw [← hterms]
    exact hasum_smul
  rw [Real.exp_eq_exp_ℝ]
  exact hseries

/-- The canonical operator-exponential one-parameter family generated by a
bounded continuous real-linear operator. -/
noncomputable def realContinuousLinearOperatorExponentialSemigroup
    {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    [CompleteSpace E]
    (G : E →L[ℝ] E)
    (t : ℝ) : E →L[ℝ] E :=
  NormedSpace.exp (t • G)

@[simp] theorem realContinuousLinearOperatorExponentialSemigroup_zero
    {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    [CompleteSpace E]
    (G : E →L[ℝ] E) :
    realContinuousLinearOperatorExponentialSemigroup G 0 = 1 := by
  simp [realContinuousLinearOperatorExponentialSemigroup]

/-- The bounded exponential family satisfies the exact additive semigroup
law for all real times. -/
theorem realContinuousLinearOperatorExponentialSemigroup_add
    {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    [CompleteSpace E]
    (G : E →L[ℝ] E)
    (s t : ℝ) :
    realContinuousLinearOperatorExponentialSemigroup G (s + t) =
      realContinuousLinearOperatorExponentialSemigroup G s *
        realContinuousLinearOperatorExponentialSemigroup G t := by
  unfold realContinuousLinearOperatorExponentialSemigroup
  rw [add_smul]
  exact NormedSpace.exp_add_of_commute
    (((Commute.refl G).smul_left s).smul_right t)

/-- The exponential family is continuous in operator norm. -/
theorem continuous_realContinuousLinearOperatorExponentialSemigroup
    {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    [CompleteSpace E]
    (G : E →L[ℝ] E) :
    Continuous (realContinuousLinearOperatorExponentialSemigroup G) := by
  unfold realContinuousLinearOperatorExponentialSemigroup
  exact NormedSpace.exp_continuous.comp
    (continuous_id.smul continuous_const)

/-- The operator-norm derivative of the exponential family is multiplication
by its bounded generator. -/
theorem realContinuousLinearOperatorExponentialSemigroup_hasDerivAt
    {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    [CompleteSpace E]
    (G : E →L[ℝ] E)
    (t : ℝ) :
    HasDerivAt
      (realContinuousLinearOperatorExponentialSemigroup G)
      (realContinuousLinearOperatorExponentialSemigroup G t * G) t := by
  simpa [realContinuousLinearOperatorExponentialSemigroup] using
    (NormedSpace.hasDerivAt_exp_smul_const G t)

/-- The strong derivative on every state is the generator action transported
by the exponential time slice. -/
theorem realContinuousLinearOperatorExponentialSemigroup_hasDerivAt_apply
    {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    [CompleteSpace E]
    (G : E →L[ℝ] E)
    (t : ℝ)
    (x : E) :
    HasDerivAt
      (fun u : ℝ => realContinuousLinearOperatorExponentialSemigroup G u x)
      ((realContinuousLinearOperatorExponentialSemigroup G t * G) x) t := by
  have h :=
    (realContinuousLinearOperatorExponentialSemigroup_hasDerivAt G t).clm_apply
      (hasDerivAt_const t x)
  simpa using h

/-- An eigenvector evolves by the scalar exponential of its generator
eigenvalue. -/
theorem realContinuousLinearOperatorExponentialSemigroup_apply_eigenvector
    {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace ℝ E]
    [CompleteSpace E]
    (G : E →L[ℝ] E)
    (v : E)
    (a t : ℝ)
    (hGv : G v = a • v) :
    realContinuousLinearOperatorExponentialSemigroup G t v =
      Real.exp (t * a) • v := by
  unfold realContinuousLinearOperatorExponentialSemigroup
  apply normedSpace_exp_apply_of_real_eigenvector
  rw [ContinuousLinearMap.smul_apply, hGv, smul_smul]
  rfl

end

end MathlibAnalytic
end MGAP4D
