import MGAP4D.MathlibAnalytic.RealHilbertKernelFeatureFiniteDimensionalPower
import Mathlib.LinearAlgebra.TensorProduct.Map

namespace MGAP4D
namespace MathlibAnalytic

open scoped TensorProduct

noncomputable section

/-- Lift a linear map between finite-dimensional degree-one Hilbert feature
carriers to all tensor-power carriers generated by `RealHilbertKernelFeature.pow`.

The pinned Mathlib revision does not yet provide a continuous `TensorProduct.map`.
Here that missing API is unnecessary: every algebraic tensor carrier is finite
dimensional, hence already complete.  At each successor degree we therefore
use the canonical finite-dimensional completion equivalence on both sides,
apply the algebraic `TensorProduct.map` in the middle, and transport back through
the exact successor carrier equivalences of `pow`.

This is the generic map-level mechanism needed by the four-edge Wilson Fock
pullback; no model-specific kernel identity enters here. -/
noncomputable def RealHilbertKernelFeature.powLinearMap
    {X₁ X₂ : Type}
    {kernel₁ : X₁ → X₁ → ℝ}
    {kernel₂ : X₂ → X₂ → ℝ}
    (C₁ : RealHilbertKernelFeature X₁ kernel₁)
    (C₂ : RealHilbertKernelFeature X₂ kernel₂)
    [FiniteDimensional ℝ C₁.FeatureHilbert]
    [FiniteDimensional ℝ C₂.FeatureHilbert]
    (T : C₁.FeatureHilbert →ₗ[ℝ] C₂.FeatureHilbert) :
    ∀ n : ℕ,
      (RealHilbertKernelFeature.pow C₁ n).FeatureHilbert →ₗ[ℝ]
        (RealHilbertKernelFeature.pow C₂ n).FeatureHilbert
  | 0 => by
      change ℝ →ₗ[ℝ] ℝ
      exact LinearMap.id
  | n + 1 => by
      letI : FiniteDimensional ℝ
          ((RealHilbertKernelFeature.pow C₁ n).FeatureHilbert) :=
        RealHilbertKernelFeature.pow_finiteDimensional C₁ n
      letI : FiniteDimensional ℝ
          ((RealHilbertKernelFeature.pow C₂ n).FeatureHilbert) :=
        RealHilbertKernelFeature.pow_finiteDimensional C₂ n
      let Raw₁ :=
        C₁.FeatureHilbert ⊗[ℝ]
          (RealHilbertKernelFeature.pow C₁ n).FeatureHilbert
      let Raw₂ :=
        C₂.FeatureHilbert ⊗[ℝ]
          (RealHilbertKernelFeature.pow C₂ n).FeatureHilbert
      letI : FiniteDimensional ℝ Raw₁ := by
        dsimp [Raw₁]
        infer_instance
      letI : FiniteDimensional ℝ Raw₂ := by
        dsimp [Raw₂]
        infer_instance
      let completionEquiv₁ : UniformSpace.Completion Raw₁ ≃ₗᵢ[ℝ] Raw₁ :=
        finiteDimensionalRealHilbertCompletionLinearIsometryEquiv Raw₁
      let completionEquiv₂ : UniformSpace.Completion Raw₂ ≃ₗᵢ[ℝ] Raw₂ :=
        finiteDimensionalRealHilbertCompletionLinearIsometryEquiv Raw₂
      let successorEquiv₁ :=
        RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C₁ n
      let successorEquiv₂ :=
        RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C₂ n
      let tensorMap : Raw₁ →ₗ[ℝ] Raw₂ :=
        TensorProduct.map T
          (RealHilbertKernelFeature.powLinearMap C₁ C₂ T n)
      exact
        successorEquiv₂.toLinearMap.comp
          (completionEquiv₂.symm.toLinearMap.comp
            (tensorMap.comp
              (completionEquiv₁.toLinearMap.comp
                successorEquiv₁.symm.toLinearMap)))

/-- Naturality of the finite-dimensional power lift on pure Hilbert features.
If the degree-one map sends `C₁.feature x` to `C₂.feature (f x)`, then every
power lift sends the recursively completed degree-`n` pure feature of `x` to
the degree-`n` pure feature of `f x`.

The successor proof follows the construction literally: move the exact power
feature back to the raw product feature, remove the finite-dimensional
completion, apply `TensorProduct.map` to the pure tensor, use the degree-one
hypothesis and induction hypothesis, then restore completion and the exact
successor carrier. -/
theorem RealHilbertKernelFeature.powLinearMap_feature
    {X₁ X₂ : Type}
    {kernel₁ : X₁ → X₁ → ℝ}
    {kernel₂ : X₂ → X₂ → ℝ}
    (C₁ : RealHilbertKernelFeature X₁ kernel₁)
    (C₂ : RealHilbertKernelFeature X₂ kernel₂)
    [FiniteDimensional ℝ C₁.FeatureHilbert]
    [FiniteDimensional ℝ C₂.FeatureHilbert]
    (T : C₁.FeatureHilbert →ₗ[ℝ] C₂.FeatureHilbert)
    (f : X₁ → X₂)
    (hT : ∀ x, T (C₁.feature x) = C₂.feature (f x))
    (n : ℕ)
    (x : X₁) :
    RealHilbertKernelFeature.powLinearMap C₁ C₂ T n
        ((RealHilbertKernelFeature.pow C₁ n).feature x) =
      (RealHilbertKernelFeature.pow C₂ n).feature (f x) := by
  induction n with
  | zero =>
      rfl
  | succ n ih =>
      letI : FiniteDimensional ℝ
          ((RealHilbertKernelFeature.pow C₁ n).FeatureHilbert) :=
        RealHilbertKernelFeature.pow_finiteDimensional C₁ n
      letI : FiniteDimensional ℝ
          ((RealHilbertKernelFeature.pow C₂ n).FeatureHilbert) :=
        RealHilbertKernelFeature.pow_finiteDimensional C₂ n
      let Raw₁ :=
        C₁.FeatureHilbert ⊗[ℝ]
          (RealHilbertKernelFeature.pow C₁ n).FeatureHilbert
      let Raw₂ :=
        C₂.FeatureHilbert ⊗[ℝ]
          (RealHilbertKernelFeature.pow C₂ n).FeatureHilbert
      letI : FiniteDimensional ℝ Raw₁ := by
        dsimp [Raw₁]
        infer_instance
      letI : FiniteDimensional ℝ Raw₂ := by
        dsimp [Raw₂]
        infer_instance
      let completionEquiv₁ : UniformSpace.Completion Raw₁ ≃ₗᵢ[ℝ] Raw₁ :=
        finiteDimensionalRealHilbertCompletionLinearIsometryEquiv Raw₁
      let completionEquiv₂ : UniformSpace.Completion Raw₂ ≃ₗᵢ[ℝ] Raw₂ :=
        finiteDimensionalRealHilbertCompletionLinearIsometryEquiv Raw₂
      let successorEquiv₁ :=
        RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C₁ n
      let successorEquiv₂ :=
        RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C₂ n
      let tensorMap : Raw₁ →ₗ[ℝ] Raw₂ :=
        TensorProduct.map T
          (RealHilbertKernelFeature.powLinearMap C₁ C₂ T n)
      change
        successorEquiv₂
            (completionEquiv₂.symm
              (tensorMap
                (completionEquiv₁
                  (successorEquiv₁.symm
                    ((RealHilbertKernelFeature.pow C₁ (n + 1)).feature x))))) =
          (RealHilbertKernelFeature.pow C₂ (n + 1)).feature (f x)
      have hSource :
          successorEquiv₁.symm
              ((RealHilbertKernelFeature.pow C₁ (n + 1)).feature x) =
            (RealHilbertKernelFeature.mul C₁
              (RealHilbertKernelFeature.pow C₁ n)).feature x := by
        simpa [successorEquiv₁] using
          (RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv_symm_feature
            C₁ n x)
      rw [hSource]
      have hCompletionSource :
          completionEquiv₁
              ((RealHilbertKernelFeature.mul C₁
                (RealHilbertKernelFeature.pow C₁ n)).feature x) =
            (C₁.feature x ⊗ₜ[ℝ]
              (RealHilbertKernelFeature.pow C₁ n).feature x : Raw₁) := by
        simp [completionEquiv₁, RealHilbertKernelFeature.mul, Raw₁]
      rw [hCompletionSource]
      dsimp [tensorMap]
      rw [TensorProduct.map_tmul]
      rw [hT x, ih]
      have hCompletionTarget :
          completionEquiv₂.symm
              (C₂.feature (f x) ⊗ₜ[ℝ]
                (RealHilbertKernelFeature.pow C₂ n).feature (f x) : Raw₂) =
            (((C₂.feature (f x) ⊗ₜ[ℝ]
                (RealHilbertKernelFeature.pow C₂ n).feature (f x) : Raw₂) :
              UniformSpace.Completion Raw₂)) := by
        simp [completionEquiv₂]
      rw [hCompletionTarget]
      simpa [successorEquiv₂, RealHilbertKernelFeature.mul, Raw₂] using
        (RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv_feature
          C₂ n (f x))

end

end MathlibAnalytic
end MGAP4D
