import Mathlib.Analysis.InnerProductSpace.TensorProduct
import Mathlib.Analysis.InnerProductSpace.Completion

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators TensorProduct

noncomputable section

/-- A real Hilbert feature realization of a scalar kernel. -/
structure RealHilbertKernelFeature
    (X : Type)
    (kernel : X → X → ℝ) where
  FeatureHilbert : Type
  [featureNormedAddCommGroup : NormedAddCommGroup FeatureHilbert]
  [featureInnerProductSpace : InnerProductSpace ℝ FeatureHilbert]
  [featureCompleteSpace : CompleteSpace FeatureHilbert]
  feature : X → FeatureHilbert
  kernel_eq_inner :
    ∀ x y, kernel x y = inner ℝ (feature x) (feature y)

attribute [instance]
  RealHilbertKernelFeature.featureNormedAddCommGroup
  RealHilbertKernelFeature.featureInnerProductSpace
  RealHilbertKernelFeature.featureCompleteSpace

/-- The constant-one kernel has the one-dimensional real feature realization. -/
noncomputable def RealHilbertKernelFeature.one
    (X : Type) :
    RealHilbertKernelFeature X (fun _ _ => 1) where
  FeatureHilbert := ℝ
  feature := fun _ => 1
  kernel_eq_inner x y := by simp

/-- The pointwise sum of two Hilbert kernels is realized by the Hilbert product
of their feature spaces. -/
noncomputable def RealHilbertKernelFeature.add
    {X : Type}
    {kernel₁ kernel₂ : X → X → ℝ}
    (C₁ : RealHilbertKernelFeature X kernel₁)
    (C₂ : RealHilbertKernelFeature X kernel₂) :
    RealHilbertKernelFeature X
      (fun x y => kernel₁ x y + kernel₂ x y) where
  FeatureHilbert := C₁.FeatureHilbert × C₂.FeatureHilbert
  feature := fun x => (C₁.feature x, C₂.feature x)
  kernel_eq_inner x y := by
    rw [C₁.kernel_eq_inner, C₂.kernel_eq_inner]
    simp

/-- Multiplication of a Hilbert kernel by a nonnegative scalar is realized by
scaling its feature map by the square root of that scalar. -/
noncomputable def RealHilbertKernelFeature.nonnegSMul
    {X : Type}
    {kernel : X → X → ℝ}
    (c : ℝ)
    (hc : 0 ≤ c)
    (C : RealHilbertKernelFeature X kernel) :
    RealHilbertKernelFeature X (fun x y => c * kernel x y) where
  FeatureHilbert := C.FeatureHilbert
  feature := fun x => Real.sqrt c • C.feature x
  kernel_eq_inner x y := by
    simp only [real_inner_smul_left, real_inner_smul_right]
    rw [← C.kernel_eq_inner]
    nlinarith [Real.sq_sqrt hc]

/-- The pointwise product of two Hilbert kernels is realized by the completed
algebraic tensor product of their feature spaces. -/
noncomputable def RealHilbertKernelFeature.mul
    {X : Type}
    {kernel₁ kernel₂ : X → X → ℝ}
    (C₁ : RealHilbertKernelFeature X kernel₁)
    (C₂ : RealHilbertKernelFeature X kernel₂) :
    RealHilbertKernelFeature X
      (fun x y => kernel₁ x y * kernel₂ x y) where
  FeatureHilbert :=
    UniformSpace.Completion
      (C₁.FeatureHilbert ⊗[ℝ] C₂.FeatureHilbert)
  feature := fun x =>
    ((C₁.feature x ⊗ₜ[ℝ] C₂.feature x :
      C₁.FeatureHilbert ⊗[ℝ] C₂.FeatureHilbert) :
      UniformSpace.Completion
        (C₁.FeatureHilbert ⊗[ℝ] C₂.FeatureHilbert))
  kernel_eq_inner x y := by
    rw [UniformSpace.Completion.inner_coe, TensorProduct.inner_tmul]
    rw [← C₁.kernel_eq_inner, ← C₂.kernel_eq_inner]

/-- Every natural pointwise power of a Hilbert kernel has a Hilbert feature
realization.  The successor step uses the completed tensor-product product
constructor. -/
noncomputable def RealHilbertKernelFeature.pow
    {X : Type}
    {kernel : X → X → ℝ}
    (C : RealHilbertKernelFeature X kernel) :
    ∀ n : ℕ, RealHilbertKernelFeature X (fun x y => kernel x y ^ n)
  | 0 => by
      simpa using RealHilbertKernelFeature.one X
  | n + 1 => by
      simpa [pow_succ, mul_comm] using
        RealHilbertKernelFeature.mul C (RealHilbertKernelFeature.pow C n)

/-- A finite ordered product of Hilbert kernels has a Hilbert feature
realization, constructed recursively by completed tensor products.

A list is used rather than `Finset.induction_on` because the result is
Type-valued: each insertion changes the completed tensor-product feature
space.  In the Wilson application the list is the finite ordered list of
plaquettes crossing the reflection plane. -/
noncomputable def RealHilbertKernelFeature.listProd
    {X ι : Type}
    (indices : List ι)
    (kernel : ι → X → X → ℝ)
    (C : ∀ i, RealHilbertKernelFeature X (kernel i)) :
    RealHilbertKernelFeature X
      (fun x y => (indices.map fun i => kernel i x y).prod) :=
  match indices with
  | [] => by
      simpa using RealHilbertKernelFeature.one X
  | i :: rest => by
      simpa using
        RealHilbertKernelFeature.mul (C i)
          (RealHilbertKernelFeature.listProd rest kernel C)

/-- The feature inner product generated by `listProd` is exactly the original
finite ordered kernel product. -/
theorem RealHilbertKernelFeature.listProd_kernel_eq_inner
    {X ι : Type}
    (indices : List ι)
    (kernel : ι → X → X → ℝ)
    (C : ∀ i, RealHilbertKernelFeature X (kernel i))
    (x y : X) :
    (indices.map fun i => kernel i x y).prod =
      inner ℝ
        ((RealHilbertKernelFeature.listProd indices kernel C).feature x)
        ((RealHilbertKernelFeature.listProd indices kernel C).feature y) :=
  (RealHilbertKernelFeature.listProd indices kernel C).kernel_eq_inner x y

end

end MathlibAnalytic
end MGAP4D
