import MGAP4D.MathlibAnalytic.RealHilbertKernelFeatureFiniteDimensionalPower
import Mathlib.LinearAlgebra.TensorProduct.Map

namespace MGAP4D
namespace MathlibAnalytic

open scoped TensorProduct

noncomputable section

/-- Lift a linear map between finite-dimensional degree-one Hilbert feature
carriers to all tensor-power carriers generated by `RealHilbertKernelFeature.pow`.

The pinned Mathlib revision does not yet provide a continuous `TensorProduct.map`.
Here that missing API is unnecessary: every algebraic tensor carrier is finite
dimensional, hence already complete.  At each successor degree we therefore
use the canonical finite-dimensional completion equivalence on both sides,
apply the algebraic `TensorProduct.map` in the middle, and transport back through
the exact successor carrier equivalences of `pow`.

This is the generic map-level mechanism needed by the four-edge Wilson Fock
pullback; no model-specific kernel identity enters here. -/
noncomputable def RealHilbertKernelFeature.powLinearMap
    {X₁ X₂ : Type}
    {kernel₁ : X₁ → X₁ → ℝ}
    {kernel₂ : X₂ → X₂ → ℝ}
    (C₁ : RealHilbertKernelFeature X₁ kernel₁)
    (C₂ : RealHilbertKernelFeature X₂ kernel₂)
    [FiniteDimensional ℝ C₁.FeatureHilbert]
    [FiniteDimensional ℝ C₂.FeatureHilbert]
    (T : C₁.FeatureHilbert →ₗ[ℝ] C₂.FeatureHilbert) :
    ∀ n : ℕ,
      (RealHilbertKernelFeature.pow C₁ n).FeatureHilbert →ₗ[ℝ]
        (RealHilbertKernelFeature.pow C₂ n).FeatureHilbert
  | 0 => by
      change ℝ →ₗ[ℝ] ℝ
      exact LinearMap.id
  | n + 1 => by
      letI : FiniteDimensional ℝ
          ((RealHilbertKernelFeature.pow C₁ n).FeatureHilbert) :=
        RealHilbertKernelFeature.pow_finiteDimensional C₁ n
      letI : FiniteDimensional ℝ
          ((RealHilbertKernelFeature.pow C₂ n).FeatureHilbert) :=
        RealHilbertKernelFeature.pow_finiteDimensional C₂ n
      let Raw₁ :=
        C₁.FeatureHilbert ⊗[ℝ]
          (RealHilbertKernelFeature.pow C₁ n).FeatureHilbert
      let Raw₂ :=
        C₂.FeatureHilbert ⊗[ℝ]
          (RealHilbertKernelFeature.pow C₂ n).FeatureHilbert
      letI : FiniteDimensional ℝ Raw₁ := by
        dsimp [Raw₁]
        infer_instance
      letI : FiniteDimensional ℝ Raw₂ := by
        dsimp [Raw₂]
        infer_instance
      let completionEquiv₁ : UniformSpace.Completion Raw₁ ≃ₗᵢ[ℝ] Raw₁ :=
        finiteDimensionalRealHilbertCompletionLinearIsometryEquiv Raw₁
      let completionEquiv₂ : UniformSpace.Completion Raw₂ ≃ₗᵢ[ℝ] Raw₂ :=
        finiteDimensionalRealHilbertCompletionLinearIsometryEquiv Raw₂
      let successorEquiv₁ :=
        RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C₁ n
      let successorEquiv₂ :=
        RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C₂ n
      let tensorMap : Raw₁ →ₗ[ℝ] Raw₂ :=
        TensorProduct.map T
          (RealHilbertKernelFeature.powLinearMap C₁ C₂ T n)
      exact
        successorEquiv₂.toLinearMap.comp
          (completionEquiv₂.symm.toLinearMap.comp
            (tensorMap.comp
              (completionEquiv₁.toLinearMap.comp
                successorEquiv₁.symm.toLinearMap)))

end

end MathlibAnalytic
end MGAP4D
