import MGAP4D.MathlibAnalytic.FiniteDimensionalRealHilbertCompletion
import MGAP4D.MathlibAnalytic.RealHilbertKernelFeatureProduct
import Mathlib.RingTheory.TensorProduct.Finite

namespace MGAP4D
namespace MathlibAnalytic

open scoped TensorProduct

noncomputable section

/-- Reindexing a Hilbert-kernel feature along an equality of scalar kernels does
not change its feature vector space.  This version follows the forward
transport generated by ordinary substitution. -/
noncomputable def RealHilbertKernelFeature.kernelCastFeatureHilbertLinearEquiv
    {X : Type}
    {kernel₁ kernel₂ : X → X → ℝ}
    (h : kernel₁ = kernel₂)
    (C : RealHilbertKernelFeature X kernel₁) :
    C.FeatureHilbert ≃ₗ[ℝ]
      (h ▸ C : RealHilbertKernelFeature X kernel₂).FeatureHilbert := by
  subst h
  exact LinearEquiv.refl ℝ C.FeatureHilbert

/-- Equality transport in the reverse `Eq.mpr` direction likewise leaves the
feature carrier unchanged.  `RealHilbertKernelFeature.pow` uses this orientation
internally in its successor `simpa`. -/
noncomputable def RealHilbertKernelFeature.kernelCastFeatureHilbertLinearEquivMpr
    {X : Type}
    {kernel₁ kernel₂ : X → X → ℝ}
    (h : kernel₁ = kernel₂)
    (C : RealHilbertKernelFeature X kernel₂) :
    C.FeatureHilbert ≃ₗ[ℝ]
      (Eq.mpr (congrArg (RealHilbertKernelFeature X) h) C).FeatureHilbert := by
  subst h
  exact LinearEquiv.refl ℝ C.FeatureHilbert

/-- The reverse kernel-cast equivalence transports feature vectors pointwise. -/
@[simp] theorem RealHilbertKernelFeature.kernelCastFeatureHilbertLinearEquivMpr_feature
    {X : Type}
    {kernel₁ kernel₂ : X → X → ℝ}
    (h : kernel₁ = kernel₂)
    (C : RealHilbertKernelFeature X kernel₂)
    (x : X) :
    RealHilbertKernelFeature.kernelCastFeatureHilbertLinearEquivMpr h C
        (C.feature x) =
      (Eq.mpr (congrArg (RealHilbertKernelFeature X) h) C).feature x := by
  subst h
  rfl

/-- Equality of two Hilbert-feature structures over the same scalar kernel
induces the identity linear equivalence between their dependent feature
carriers.  This isolates proof-irrelevant structure equality from vector-level
casts. -/
noncomputable def RealHilbertKernelFeature.featureHilbertLinearEquivOfEq
    {X : Type}
    {kernel : X → X → ℝ}
    {C D : RealHilbertKernelFeature X kernel}
    (h : C = D) :
    C.FeatureHilbert ≃ₗ[ℝ] D.FeatureHilbert := by
  subst h
  exact LinearEquiv.refl ℝ C.FeatureHilbert

/-- The structure-equality carrier equivalence transports feature vectors
pointwise. -/
@[simp] theorem RealHilbertKernelFeature.featureHilbertLinearEquivOfEq_feature
    {X : Type}
    {kernel : X → X → ℝ}
    {C D : RealHilbertKernelFeature X kernel}
    (h : C = D)
    (x : X) :
    RealHilbertKernelFeature.featureHilbertLinearEquivOfEq h (C.feature x) =
      D.feature x := by
  subst h
  rfl

/-- The successor carrier used by `RealHilbertKernelFeature.pow` is linearly
equivalent to the raw completed tensor carrier produced by `mul`.

There are two conceptually separate transports: first reindex the `mul`
feature from the product kernel to the power kernel, then identify that
transported structure with the exact structure chosen by the defining `simpa`
of `pow`.  Keeping the second step at structure level makes the construction
independent of the particular equality proof generated by simplification. -/
noncomputable def RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv
    {X : Type}
    {kernel : X → X → ℝ}
    (C : RealHilbertKernelFeature X kernel)
    (n : ℕ) :
    (RealHilbertKernelFeature.mul C
      (RealHilbertKernelFeature.pow C n)).FeatureHilbert ≃ₗ[ℝ]
      (RealHilbertKernelFeature.pow C (n + 1)).FeatureHilbert := by
  let D :=
    RealHilbertKernelFeature.mul C
      (RealHilbertKernelFeature.pow C n)
  have hKernel :
      (fun x y => kernel x y ^ (n + 1)) =
        (fun x y => kernel x y * kernel x y ^ n) := by
    funext x y
    rw [pow_succ]
    exact mul_comm _ _
  let Dcast : RealHilbertKernelFeature X (fun x y => kernel x y ^ (n + 1)) :=
    Eq.mpr (congrArg (RealHilbertKernelFeature X) hKernel) D
  have hPow : Dcast = RealHilbertKernelFeature.pow C (n + 1) := by
    dsimp [Dcast, D]
    simp only [RealHilbertKernelFeature.pow]
    rfl
  exact
    (RealHilbertKernelFeature.kernelCastFeatureHilbertLinearEquivMpr hKernel D).trans
      (RealHilbertKernelFeature.featureHilbertLinearEquivOfEq hPow)

/-- The successor carrier equivalence sends the raw product feature to the
exact feature vector selected by `RealHilbertKernelFeature.pow`. -/
@[simp] theorem RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv_feature
    {X : Type}
    {kernel : X → X → ℝ}
    (C : RealHilbertKernelFeature X kernel)
    (n : ℕ)
    (x : X) :
    RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C n
        ((RealHilbertKernelFeature.mul C
          (RealHilbertKernelFeature.pow C n)).feature x) =
      (RealHilbertKernelFeature.pow C (n + 1)).feature x := by
  unfold RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv
  simp

/-- The inverse successor carrier equivalence sends the exact power feature
back to the raw product feature. -/
@[simp] theorem RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv_symm_feature
    {X : Type}
    {kernel : X → X → ℝ}
    (C : RealHilbertKernelFeature X kernel)
    (n : ℕ)
    (x : X) :
    (RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C n).symm
        ((RealHilbertKernelFeature.pow C (n + 1)).feature x) =
      (RealHilbertKernelFeature.mul C
        (RealHilbertKernelFeature.pow C n)).feature x := by
  apply (RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C n).injective
  simp

/-- If the degree-one carrier of a real Hilbert-kernel feature is finite
dimensional, then every recursively completed tensor-power carrier produced by
`RealHilbertKernelFeature.pow` is finite dimensional.

The successor step follows the implementation of `pow`: finite-dimensional
base carrier tensor finite-dimensional preceding power carrier, completion,
then the kernel-index cast.  The last step is transported through
`powSuccFeatureHilbertLinearEquiv`. -/
theorem RealHilbertKernelFeature.pow_finiteDimensional
    {X : Type}
    {kernel : X → X → ℝ}
    (C : RealHilbertKernelFeature X kernel)
    [FiniteDimensional ℝ C.FeatureHilbert]
    (n : ℕ) :
    FiniteDimensional ℝ
      ((RealHilbertKernelFeature.pow C n).FeatureHilbert) := by
  induction n with
  | zero =>
      change FiniteDimensional ℝ ℝ
      infer_instance
  | succ n ih =>
      letI : FiniteDimensional ℝ
          ((RealHilbertKernelFeature.pow C n).FeatureHilbert) := ih
      letI : FiniteDimensional ℝ
          (C.FeatureHilbert ⊗[ℝ]
            (RealHilbertKernelFeature.pow C n).FeatureHilbert) := by
        infer_instance
      let D :=
        RealHilbertKernelFeature.mul C
          (RealHilbertKernelFeature.pow C n)
      letI : FiniteDimensional ℝ D.FeatureHilbert := by
        change FiniteDimensional ℝ
          (UniformSpace.Completion
            (C.FeatureHilbert ⊗[ℝ]
              (RealHilbertKernelFeature.pow C n).FeatureHilbert))
        exact finiteDimensional_realHilbert_completion
          (C.FeatureHilbert ⊗[ℝ]
            (RealHilbertKernelFeature.pow C n).FeatureHilbert)
      exact
        (RealHilbertKernelFeature.powSuccFeatureHilbertLinearEquiv C n).finiteDimensional

end

end MathlibAnalytic
end MGAP4D
