import MGAP4D.MathlibAnalytic.RealHilbertKernelFeatureProduct
import Mathlib.MeasureTheory.Function.StronglyMeasurable.Lemmas

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory
open scoped TensorProduct

noncomputable section

/-- The canonical real tensor map, bundled as a continuous bilinear map.

The Hilbert tensor-product norm identity gives operator norm at most one. -/
noncomputable def realHilbertTensorProductContinuousBilinearMap
    {E F : Type}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup F] [InnerProductSpace ℝ F] :
    E →L[ℝ] F →L[ℝ] E ⊗[ℝ] F :=
  LinearMap.mkContinuous₂
    (TensorProduct.mk ℝ E F)
    1
    (by
      intro x y
      simp)

/-- Almost-everywhere strong measurability is preserved by the canonical real
Hilbert tensor product. -/
theorem aestronglyMeasurable_realHilbert_tmul
    {X E F : Type}
    [MeasurableSpace X]
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup F] [InnerProductSpace ℝ F]
    {μ : Measure X}
    {f : X → E}
    {g : X → F}
    (hf : AEStronglyMeasurable f μ)
    (hg : AEStronglyMeasurable g μ) :
    AEStronglyMeasurable (fun x => f x ⊗ₜ[ℝ] g x) μ := by
  exact
    (realHilbertTensorProductContinuousBilinearMap
      (E := E) (F := F)).aestronglyMeasurable_comp₂ hf hg

/-- Almost-everywhere strong measurability is preserved by the completed real
Hilbert tensor product used in `RealHilbertKernelFeature.mul`. -/
theorem aestronglyMeasurable_realHilbert_completion_tmul
    {X E F : Type}
    [MeasurableSpace X]
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup F] [InnerProductSpace ℝ F]
    {μ : Measure X}
    {f : X → E}
    {g : X → F}
    (hf : AEStronglyMeasurable f μ)
    (hg : AEStronglyMeasurable g μ) :
    AEStronglyMeasurable
      (fun x =>
        ((f x ⊗ₜ[ℝ] g x : E ⊗[ℝ] F) :
          UniformSpace.Completion (E ⊗[ℝ] F)))
      μ := by
  exact
    (UniformSpace.Completion.continuous_coe
      (α := E ⊗[ℝ] F)).comp_aestronglyMeasurable
      (aestronglyMeasurable_realHilbert_tmul hf hg)

/-- If every local feature is almost-everywhere strongly measurable, then the
finite completed-tensor-product feature generated by `listProd` is also
almost-everywhere strongly measurable. -/
theorem RealHilbertKernelFeature.listProd_feature_aestronglyMeasurable
    {X ι : Type}
    [MeasurableSpace X]
    {μ : Measure X}
    (indices : List ι)
    (kernel : ι → X → X → ℝ)
    (C : ∀ i, RealHilbertKernelFeature X (kernel i))
    (hC : ∀ i, AEStronglyMeasurable (C i).feature μ) :
    AEStronglyMeasurable
      (RealHilbertKernelFeature.listProd indices kernel C).feature
      μ := by
  induction indices with
  | nil =>
      simpa [RealHilbertKernelFeature.listProd,
        RealHilbertKernelFeature.one] using
        (aestronglyMeasurable_const
          (μ := μ) (b := (1 : ℝ)))
  | cons i rest ih =>
      simpa [RealHilbertKernelFeature.listProd,
        RealHilbertKernelFeature.mul] using
        aestronglyMeasurable_realHilbert_completion_tmul
          (hC i) ih

end

end MathlibAnalytic
end MGAP4D
