import Mathlib.Analysis.InnerProductSpace.TensorProduct
import Mathlib.Analysis.InnerProductSpace.Completion

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators TensorProduct

noncomputable section

/-- A real Hilbert feature realization of a scalar kernel. -/
structure RealHilbertKernelFeature
    (X : Type)
    (kernel : X → X → ℝ) where
  FeatureHilbert : Type
  [featureNormedAddCommGroup : NormedAddCommGroup FeatureHilbert]
  [featureInnerProductSpace : InnerProductSpace ℝ FeatureHilbert]
  [featureCompleteSpace : CompleteSpace FeatureHilbert]
  feature : X → FeatureHilbert
  kernel_eq_inner :
    ∀ x y, kernel x y = inner ℝ (feature x) (feature y)

attribute [instance]
  RealHilbertKernelFeature.featureNormedAddCommGroup
  RealHilbertKernelFeature.featureInnerProductSpace
  RealHilbertKernelFeature.featureCompleteSpace

/-- The constant-one kernel has the one-dimensional real feature realization. -/
noncomputable def RealHilbertKernelFeature.one
    (X : Type) :
    RealHilbertKernelFeature X (fun _ _ => 1) where
  FeatureHilbert := ℝ
  feature := fun _ => 1
  kernel_eq_inner x y := by simp

/-- The pointwise product of two Hilbert kernels is realized by the completed
algebraic tensor product of their feature spaces. -/
noncomputable def RealHilbertKernelFeature.mul
    {X : Type}
    {kernel₁ kernel₂ : X → X → ℝ}
    (C₁ : RealHilbertKernelFeature X kernel₁)
    (C₂ : RealHilbertKernelFeature X kernel₂) :
    RealHilbertKernelFeature X
      (fun x y => kernel₁ x y * kernel₂ x y) where
  FeatureHilbert :=
    UniformSpace.Completion
      (C₁.FeatureHilbert ⊗[ℝ] C₂.FeatureHilbert)
  feature := fun x =>
    ((C₁.feature x ⊗ₜ[ℝ] C₂.feature x :
      C₁.FeatureHilbert ⊗[ℝ] C₂.FeatureHilbert) :
      UniformSpace.Completion
        (C₁.FeatureHilbert ⊗[ℝ] C₂.FeatureHilbert))
  kernel_eq_inner x y := by
    rw [UniformSpace.Completion.inner_coe, TensorProduct.inner_tmul]
    rw [← C₁.kernel_eq_inner, ← C₂.kernel_eq_inner]

/-- A finite ordered product of Hilbert kernels has a Hilbert feature
realization, constructed recursively by completed tensor products.

A list is used rather than `Finset.induction_on` because the result is
Type-valued: each insertion changes the completed tensor-product feature
space.  In the Wilson application the list is the finite ordered list of
plaquettes crossing the reflection plane. -/
noncomputable def RealHilbertKernelFeature.listProd
    {X ι : Type}
    (indices : List ι)
    (kernel : ι → X → X → ℝ)
    (C : ∀ i, RealHilbertKernelFeature X (kernel i)) :
    RealHilbertKernelFeature X
      (fun x y => (indices.map fun i => kernel i x y).prod) :=
  match indices with
  | [] => by
      simpa using RealHilbertKernelFeature.one X
  | i :: rest => by
      simpa using
        RealHilbertKernelFeature.mul (C i)
          (RealHilbertKernelFeature.listProd rest kernel C)

/-- The feature inner product generated by `listProd` is exactly the original
finite ordered kernel product. -/
theorem RealHilbertKernelFeature.listProd_kernel_eq_inner
    {X ι : Type}
    (indices : List ι)
    (kernel : ι → X → X → ℝ)
    (C : ∀ i, RealHilbertKernelFeature X (kernel i))
    (x y : X) :
    (indices.map fun i => kernel i x y).prod =
      inner ℝ
        ((RealHilbertKernelFeature.listProd indices kernel C).feature x)
        ((RealHilbertKernelFeature.listProd indices kernel C).feature y) :=
  (RealHilbertKernelFeature.listProd indices kernel C).kernel_eq_inner x y

end

end MathlibAnalytic
end MGAP4D
