import Mathlib.GroupTheory.SemidirectProduct
import Mathlib.GroupTheory.Perm.Finite
import Mathlib.Algebra.Ring.Int.Units
import Mathlib.Tactic

/-!
# Abstract signed permutation group of the three spatial coordinate axes

The concrete finite-lattice `SU(N)` configuration action already carries a subgroup generated by
the two adjacent spatial-axis swaps and one independent axis reflection.  To separate the geometric
symmetry itself from any gauge carrier, lattice size, or possible non-faithfulness of a particular
configuration action, this file defines the corresponding abstract signed-coordinate group.

The sign group is

`SpatialSign = Fin 3 → ℤˣ`,

where `ℤˣ = {+1,-1}`.  A permutation of the three spatial axes acts on sign functions by pullback.
The abstract signed permutation group is the resulting semidirect product

`SpatialSign ⋊ S₃`.

This is the standard three-dimensional signed-permutation construction, but this layer only defines
the group and four distinguished elements (`swap12`, `swap23`, `reflect1`, and global parity).
Cardinality `48`, generation, the homomorphism to the concrete configuration-permutation subgroup,
and cubic/continuum representation labels are deliberately left to later additive layers.
-/

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- Multiplicative sign assignments on the three abstract spatial coordinate axes. -/
abbrev SpatialAxisSign := Fin 3 → ℤˣ

/-- Reindex a spatial sign assignment by an axis permutation.  Pullback by `σ.symm` gives the
left action compatible with multiplication in `Equiv.Perm (Fin 3)`. -/
def spatialAxisSignReindexMulAut
    (σ : Equiv.Perm (Fin 3)) : MulAut SpatialAxisSign where
  toFun ε := fun i => ε (σ.symm i)
  invFun ε := fun i => ε (σ i)
  left_inv ε := by
    funext i
    simp
  right_inv ε := by
    funext i
    simp
  map_mul' ε δ := by
    funext i
    rfl

@[simp]
theorem spatialAxisSignReindexMulAut_apply
    (σ : Equiv.Perm (Fin 3))
    (ε : SpatialAxisSign)
    (i : Fin 3) :
    spatialAxisSignReindexMulAut σ ε i = ε (σ.symm i) :=
  rfl

@[simp]
theorem spatialAxisSignReindexMulAut_one :
    spatialAxisSignReindexMulAut (1 : Equiv.Perm (Fin 3)) = 1 := by
  ext ε i
  rfl

@[simp]
theorem spatialAxisSignReindexMulAut_mul
    (σ τ : Equiv.Perm (Fin 3)) :
    spatialAxisSignReindexMulAut (σ * τ) =
      spatialAxisSignReindexMulAut σ * spatialAxisSignReindexMulAut τ := by
  ext ε i
  rfl

/-- The canonical action homomorphism of the spatial-axis permutation group on the sign group. -/
def spatialAxisPermutationSignAction :
    Equiv.Perm (Fin 3) →* MulAut SpatialAxisSign where
  toFun := spatialAxisSignReindexMulAut
  map_one' := spatialAxisSignReindexMulAut_one
  map_mul' := spatialAxisSignReindexMulAut_mul

@[simp]
theorem spatialAxisPermutationSignAction_apply
    (σ : Equiv.Perm (Fin 3))
    (ε : SpatialAxisSign)
    (i : Fin 3) :
    spatialAxisPermutationSignAction σ ε i = ε (σ.symm i) :=
  rfl

/-- Abstract signed permutation group of the three spatial coordinate axes.  The construction is
independent of lattice size and gauge carrier. -/
abbrev SpatialSignedPermutationGroup :=
  SpatialAxisSign ⋊[spatialAxisPermutationSignAction] Equiv.Perm (Fin 3)

/-- Identity sign assignment on all three spatial axes. -/
def spatialAxisPositiveSign : SpatialAxisSign :=
  fun _ => 1

/-- Sign assignment which reverses abstract spatial axis `1` (represented by `0 : Fin 3`) only. -/
def spatialAxisReflect1Sign : SpatialAxisSign :=
  fun i => if i = 0 then -1 else 1

/-- Sign assignment reversing all three spatial axes. -/
def spatialAxisParitySign : SpatialAxisSign :=
  fun _ => -1

@[simp]
theorem spatialAxisPositiveSign_apply (i : Fin 3) :
    spatialAxisPositiveSign i = 1 :=
  rfl

@[simp]
theorem spatialAxisReflect1Sign_axis1 :
    spatialAxisReflect1Sign 0 = -1 := by
  simp [spatialAxisReflect1Sign]

@[simp]
theorem spatialAxisReflect1Sign_other
    {i : Fin 3} (hi : i ≠ 0) :
    spatialAxisReflect1Sign i = 1 := by
  simp [spatialAxisReflect1Sign, hi]

@[simp]
theorem spatialAxisParitySign_apply (i : Fin 3) :
    spatialAxisParitySign i = -1 :=
  rfl

/-- Abstract adjacent swap of spatial axes `1` and `2`. -/
def spatialSignedPermutationSwap12 : SpatialSignedPermutationGroup :=
  ⟨spatialAxisPositiveSign, Equiv.swap (0 : Fin 3) 1⟩

/-- Abstract adjacent swap of spatial axes `2` and `3`. -/
def spatialSignedPermutationSwap23 : SpatialSignedPermutationGroup :=
  ⟨spatialAxisPositiveSign, Equiv.swap (1 : Fin 3) 2⟩

/-- Abstract reflection of spatial axis `1`. -/
def spatialSignedPermutationReflect1 : SpatialSignedPermutationGroup :=
  ⟨spatialAxisReflect1Sign, 1⟩

/-- Abstract global spatial parity: reverse all three spatial coordinate axes. -/
def spatialSignedPermutationParity : SpatialSignedPermutationGroup :=
  ⟨spatialAxisParitySign, 1⟩

@[simp]
theorem spatialSignedPermutationSwap12_left :
    spatialSignedPermutationSwap12.left = spatialAxisPositiveSign :=
  rfl

@[simp]
theorem spatialSignedPermutationSwap12_right :
    spatialSignedPermutationSwap12.right = Equiv.swap (0 : Fin 3) 1 :=
  rfl

@[simp]
theorem spatialSignedPermutationSwap23_left :
    spatialSignedPermutationSwap23.left = spatialAxisPositiveSign :=
  rfl

@[simp]
theorem spatialSignedPermutationSwap23_right :
    spatialSignedPermutationSwap23.right = Equiv.swap (1 : Fin 3) 2 :=
  rfl

@[simp]
theorem spatialSignedPermutationReflect1_left :
    spatialSignedPermutationReflect1.left = spatialAxisReflect1Sign :=
  rfl

@[simp]
theorem spatialSignedPermutationReflect1_right :
    spatialSignedPermutationReflect1.right = 1 :=
  rfl

@[simp]
theorem spatialSignedPermutationParity_left :
    spatialSignedPermutationParity.left = spatialAxisParitySign :=
  rfl

@[simp]
theorem spatialSignedPermutationParity_right :
    spatialSignedPermutationParity.right = 1 :=
  rfl

end

end MathlibAnalytic
end MGAP4D
