import MGAP4D.MathlibAnalytic.SpecialUnitaryCompactOrientedConditionalDensityRatio
import MGAP4D.MathlibAnalytic.ContinuousCompactOrientedGaugeWilsonDobrushinMatrixL2
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open MeasureTheory

noncomputable section

namespace HaarLikelihoodRatioInfluence

/-- The sharp total-variation coefficient associated with a mutual density
ratio bound by `K`. -/
def coefficient (K : ℝ) : ℝ :=
  (K - 1) / (K + 1)

/-- Mutual pointwise domination `p ≤ Kq` and `q ≤ Kp` implies the sharp
pointwise variation estimate. -/
theorem abs_sub_le_coefficient_mul_add
    (K p q : ℝ)
    (hK : 1 ≤ K)
    (hpq : p ≤ K * q)
    (hqp : q ≤ K * p) :
    |p - q| ≤ coefficient K * (p + q) := by
  have hden : 0 < K + 1 := by linarith
  have hUpper : p - q ≤ coefficient K * (p + q) := by
    unfold coefficient
    rw [div_mul_eq_mul_div]
    apply (le_div_iff₀ hden).2
    nlinarith
  have hUpperSwap : q - p ≤ coefficient K * (p + q) := by
    unfold coefficient
    rw [div_mul_eq_mul_div]
    apply (le_div_iff₀ hden).2
    nlinarith
  exact abs_le.mpr ⟨by linarith, hUpper⟩

/-- The sharp bounded-test consequence of mutual density domination for two
probability densities over one base measure. -/
theorem boundedTest_integral_difference_abs_le
    {α : Type*}
    [MeasurableSpace α]
    (μ : Measure α)
    (p q phi : α → ℝ)
    (hpInt : Integrable p μ)
    (hqInt : Integrable q μ)
    (hp0 : ∀ x, 0 ≤ p x)
    (hq0 : ∀ x, 0 ≤ q x)
    (hpOne : ∫ x, p x ∂μ = 1)
    (hqOne : ∫ x, q x ∂μ = 1)
    (K : ℝ)
    (hK : 1 ≤ K)
    (hRatio : ∀ x, p x ≤ K * q x ∧ q x ≤ K * p x)
    (hphi : StronglyMeasurable phi)
    (hphiBound : ∀ x, |phi x| ≤ 1) :
    |(∫ x, phi x * p x ∂μ) - (∫ x, phi x * q x ∂μ)| ≤
      2 * coefficient K := by
  have hphiPInt : Integrable (fun x => phi x * p x) μ := by
    apply hpInt.mono
    · exact hphi.aestronglyMeasurable.mul hpInt.aestronglyMeasurable
    · filter_upwards [] with x
      simpa [Real.norm_eq_abs, abs_mul, abs_of_nonneg (hp0 x)] using
        mul_le_mul_of_nonneg_right (hphiBound x) (hp0 x)
  have hphiQInt : Integrable (fun x => phi x * q x) μ := by
    apply hqInt.mono
    · exact hphi.aestronglyMeasurable.mul hqInt.aestronglyMeasurable
    · filter_upwards [] with x
      simpa [Real.norm_eq_abs, abs_mul, abs_of_nonneg (hq0 x)] using
        mul_le_mul_of_nonneg_right (hphiBound x) (hq0 x)
  have hDiffInt : Integrable (fun x =>
      phi x * p x - phi x * q x) μ :=
    hphiPInt.sub' hphiQInt
  have hAbsDiffInt : Integrable (fun x =>
      |phi x * p x - phi x * q x|) μ :=
    hDiffInt.abs
  have hSumInt : Integrable (fun x => p x + q x) μ := by
    simpa only [Pi.add_apply] using hpInt.add hqInt
  have hRightInt : Integrable (fun x =>
      coefficient K * (p x + q x)) μ :=
    hSumInt.const_mul (coefficient K)
  calc
    |(∫ x, phi x * p x ∂μ) - (∫ x, phi x * q x ∂μ)| =
        |∫ x, (phi x * p x - phi x * q x) ∂μ| := by
          rw [integral_sub hphiPInt hphiQInt]
    _ ≤ ∫ x, |phi x * p x - phi x * q x| ∂μ := by
      simpa [Real.norm_eq_abs] using
        (norm_integral_le_integral_norm
          (μ := μ) (f := fun x => phi x * p x - phi x * q x))
    _ ≤ ∫ x, coefficient K * (p x + q x) ∂μ := by
      apply integral_mono_ae hAbsDiffInt hRightInt
      filter_upwards [] with x
      calc
        |phi x * p x - phi x * q x| =
            |phi x| * |p x - q x| := by
              rw [← mul_sub, abs_mul]
        _ ≤ 1 * |p x - q x| :=
          mul_le_mul_of_nonneg_right (hphiBound x) (abs_nonneg _)
        _ = |p x - q x| := one_mul _
        _ ≤ coefficient K * (p x + q x) :=
          abs_sub_le_coefficient_mul_add K (p x) (q x) hK
            (hRatio x).1 (hRatio x).2
    _ = coefficient K * ((∫ x, p x ∂μ) + ∫ x, q x ∂μ) := by
      rw [integral_const_mul, integral_add hpInt hqInt]
    _ = 2 * coefficient K := by rw [hpOne, hqOne]; ring

end HaarLikelihoodRatioInfluence

/-- The sharp influence generated by a log-density oscillation radius. -/
def compactHaarOscillationInfluence (R : ℝ) : ℝ :=
  HaarLikelihoodRatioInfluence.coefficient (Real.exp R)

/-- A nonnegative oscillation radius gives a nonnegative influence. -/
theorem compactHaarOscillationInfluence_nonneg
    {R : ℝ}
    (hR : 0 ≤ R) :
    0 ≤ compactHaarOscillationInfluence R := by
  unfold compactHaarOscillationInfluence
    HaarLikelihoodRatioInfluence.coefficient
  exact div_nonneg
    (sub_nonneg.mpr (Real.one_le_exp hR))
    (by positivity)

/-- Every finite oscillation radius gives an influence strictly below one. -/
theorem compactHaarOscillationInfluence_lt_one
    (R : ℝ) :
    compactHaarOscillationInfluence R < 1 := by
  unfold compactHaarOscillationInfluence
    HaarLikelihoodRatioInfluence.coefficient
  have hden : 0 < Real.exp R + 1 := by positivity
  apply (div_lt_iff₀ hden).2
  linarith

/-- A mutual exact-Haar conditional-density ratio bound gives the corresponding
sharp bounded-test conditional-law influence. -/
theorem continuous_compact_oriented_conditionalIntegral_difference_abs_le_of_densityRatio
    (C : ContinuousCompactOrientedGaugeWilsonSystem)
    (A B : C.base.Configuration)
    (target : C.base.geometry.Edge)
    (R : ℝ)
    (hR : 0 ≤ R)
    (hRatio : ∀ u : C.base.Gauge,
      C.singleLinkConditionalDensityReal A target u ≤
          Real.exp R * C.singleLinkConditionalDensityReal B target u ∧
        C.singleLinkConditionalDensityReal B target u ≤
          Real.exp R * C.singleLinkConditionalDensityReal A target u)
    (phi : C.base.Gauge → ℝ)
    (hphi : StronglyMeasurable phi)
    (hphiBound : ∀ u, |phi u| ≤ 1) :
    |(∫ u, phi u ∂C.singleLinkConditionalMeasure A target) -
      (∫ u, phi u ∂C.singleLinkConditionalMeasure B target)| ≤
        2 * compactHaarOscillationInfluence R := by
  let μ := normalizedCompactHaar C.base.Gauge
  let p := C.singleLinkConditionalDensityReal A target
  let q := C.singleLinkConditionalDensityReal B target
  have hpInt : Integrable p μ := by
    simpa [μ, p,
      ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalDensityReal] using
      (continuous_compact_oriented_singleLinkBoltzmannIntegrable C A target).div_const
        (C.singleLinkPartitionFunction A target)
  have hqInt : Integrable q μ := by
    simpa [μ, q,
      ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalDensityReal] using
      (continuous_compact_oriented_singleLinkBoltzmannIntegrable C B target).div_const
        (C.singleLinkPartitionFunction B target)
  have hp0 : ∀ u, 0 ≤ p u := by
    intro u
    unfold p ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalDensityReal
    exact div_nonneg (Real.exp_pos _).le
      (continuous_compact_oriented_singleLinkPartitionFunction_pos C A target).le
  have hq0 : ∀ u, 0 ≤ q u := by
    intro u
    unfold q ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalDensityReal
    exact div_nonneg (Real.exp_pos _).le
      (continuous_compact_oriented_singleLinkPartitionFunction_pos C B target).le
  have hpOne : ∫ u, p u ∂μ = 1 := by
    unfold p μ ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalDensityReal
    rw [integral_div]
    unfold ContinuousCompactOrientedGaugeWilsonSystem.singleLinkPartitionFunction
    exact div_self
      (ne_of_gt (continuous_compact_oriented_singleLinkPartitionFunction_pos C A target))
  have hqOne : ∫ u, q u ∂μ = 1 := by
    unfold q μ ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalDensityReal
    rw [integral_div]
    unfold ContinuousCompactOrientedGaugeWilsonSystem.singleLinkPartitionFunction
    exact div_self
      (ne_of_gt (continuous_compact_oriented_singleLinkPartitionFunction_pos C B target))
  have hA :
      (∫ u, phi u ∂C.singleLinkConditionalMeasure A target) =
        ∫ u, phi u * p u ∂μ := by
    unfold ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalMeasure
    rw [integral_tilted]
    simp [μ, p,
      ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalDensityReal,
      ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoltzmannFactor,
      ContinuousCompactOrientedGaugeWilsonSystem.singleLinkPartitionFunction,
      smul_eq_mul, mul_comm]
  have hB :
      (∫ u, phi u ∂C.singleLinkConditionalMeasure B target) =
        ∫ u, phi u * q u ∂μ := by
    unfold ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalMeasure
    rw [integral_tilted]
    simp [μ, q,
      ContinuousCompactOrientedGaugeWilsonSystem.singleLinkConditionalDensityReal,
      ContinuousCompactOrientedGaugeWilsonSystem.singleLinkBoltzmannFactor,
      ContinuousCompactOrientedGaugeWilsonSystem.singleLinkPartitionFunction,
      smul_eq_mul, mul_comm]
  rw [hA, hB]
  exact HaarLikelihoodRatioInfluence.boundedTest_integral_difference_abs_le
    μ p q phi hpInt hqInt hp0 hq0 hpOne hqOne (Real.exp R)
    (Real.one_le_exp hR) hRatio hphi hphiBound

/-- The explicit off-diagonal `SU(N)` compact-Haar Dobrushin influence obtained
from shared plaquettes. -/
noncomputable def specialUnitaryCompactOrientedSharedPlaquetteInfluence
    (geometry : FiniteOrientedFourDimensionalPlaquetteGeometry)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ)
    (beta_nonneg : 0 ≤ beta)
    (target source : geometry.Edge) : ℝ := by
  classical
  exact if target = source then 0 else
    compactHaarOscillationInfluence
      (beta * (4 * (((specialUnitaryContinuousCompactOrientedDensityRatioSystem
        geometry N hN beta beta_nonneg).base.sharedPlaquettes
          target source).card : ℝ)))

/-- The explicit `SU(N)` influence is nonnegative. -/
theorem specialUnitaryCompactOrientedSharedPlaquetteInfluence_nonneg
    (geometry : FiniteOrientedFourDimensionalPlaquetteGeometry)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ)
    (beta_nonneg : 0 ≤ beta)
    (target source : geometry.Edge) :
    0 ≤ specialUnitaryCompactOrientedSharedPlaquetteInfluence
      geometry N hN beta beta_nonneg target source := by
  classical
  unfold specialUnitaryCompactOrientedSharedPlaquetteInfluence
  split_ifs
  · exact le_rfl
  · apply compactHaarOscillationInfluence_nonneg
    positivity

/-- The explicit `SU(N)` influence has zero diagonal. -/
theorem specialUnitaryCompactOrientedSharedPlaquetteInfluence_diagonal_zero
    (geometry : FiniteOrientedFourDimensionalPlaquetteGeometry)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ)
    (beta_nonneg : 0 ≤ beta)
    (target : geometry.Edge) :
    specialUnitaryCompactOrientedSharedPlaquetteInfluence
      geometry N hN beta beta_nonneg target target = 0 := by
  classical
  simp [specialUnitaryCompactOrientedSharedPlaquetteInfluence]

/-- The shared-plaquette formula controls every bounded test of the exact
canonical `SU(N)` one-link Haar conditional laws. -/
theorem specialUnitaryContinuousCompactOriented_conditionalIntegral_difference_abs_le
    (geometry : FiniteOrientedFourDimensionalPlaquetteGeometry)
    (N : ℕ)
    (hN : 0 < N)
    [Nontrivial (Matrix.specialUnitaryGroup (Fin N) ℂ)]
    (beta : ℝ)
    (beta_nonneg : 0 ≤ beta)
    (A B : (specialUnitaryContinuousCompactOrientedDensityRatioSystem
      geometry N hN beta beta_nonneg).base.Configuration)
    (target source : geometry.Edge)
    (hAgree : (specialUnitaryContinuousCompactOrientedDensityRatioSystem
      geometry N hN beta beta_nonneg).base.AgreeOffLink A B source)
    (phi : (specialUnitaryContinuousCompactOrientedDensityRatioSystem
      geometry N hN beta beta_nonneg).base.Gauge → ℝ)
    (hphi : StronglyMeasurable phi)
    (hphiBound : ∀ u, |phi u| ≤ 1) :
    let C := specialUnitaryContinuousCompactOrientedDensityRatioSystem
      geometry N hN beta beta_nonneg
    |(∫ u, phi u ∂C.singleLinkConditionalMeasure A target) -
      (∫ u, phi u ∂C.singleLinkConditionalMeasure B target)| ≤
        2 * specialUnitaryCompactOrientedSharedPlaquetteInfluence
          geometry N hN beta beta_nonneg target source := by
  dsimp only
  classical
  let C := specialUnitaryContinuousCompactOrientedDensityRatioSystem
    geometry N hN beta beta_nonneg
  change C.base.AgreeOffLink A B source at hAgree
  change |(∫ u, phi u ∂C.singleLinkConditionalMeasure A target) -
      (∫ u, phi u ∂C.singleLinkConditionalMeasure B target)| ≤
        2 * specialUnitaryCompactOrientedSharedPlaquetteInfluence
          geometry N hN beta beta_nonneg target source
  by_cases hEq : target = source
  · subst source
    have hIntEq :
        (∫ u, phi u ∂C.singleLinkConditionalMeasure A target) =
          ∫ u, phi u ∂C.singleLinkConditionalMeasure B target :=
      continuous_compact_oriented_conditionalIntegral_eq_of_agreeOffLink
        C target A B hAgree phi
    rw [hIntEq]
    simp [specialUnitaryCompactOrientedSharedPlaquetteInfluence]
  · let R := beta * (4 * ((C.base.sharedPlaquettes target source).card : ℝ))
    have hR : 0 ≤ R := by positivity
    have hRatio : ∀ u : C.base.Gauge,
        C.singleLinkConditionalDensityReal A target u ≤
            Real.exp R * C.singleLinkConditionalDensityReal B target u ∧
          C.singleLinkConditionalDensityReal B target u ≤
            Real.exp R * C.singleLinkConditionalDensityReal A target u := by
      intro u
      simpa [C, R] using
        specialUnitaryContinuousCompactOriented_singleLinkConditionalDensityReal_mutual_le
          geometry N hN beta beta_nonneg A B target source hAgree u
    have hBound :=
      continuous_compact_oriented_conditionalIntegral_difference_abs_le_of_densityRatio
        C A B target R hR hRatio phi hphi hphiBound
    simpa [specialUnitaryCompactOrientedSharedPlaquetteInfluence, hEq, C, R] using hBound

end

end MathlibAnalytic
end MGAP4D
