import MGAP4D.MathlibAnalytic.PhysicalYangMillsWilsonSUNPrimaryPlaquetteTwoModeProjectiveStrongLimit
import MGAP4D.MathlibAnalytic.PeriodicHypercubicEvenPrimarySpatialPlaquetteWilsonClassFunction
import Mathlib.MeasureTheory.Function.LpSpace.ContinuousFunctions
import Mathlib.Tactic

/-!
# Continuous boundary representatives of the arbitrary-rank Wilson two-mode family

PR #5000 constructs, for every N >= 2, the normalized-Haar orthonormal Fin 2
family obtained by Gram--Schmidt from the concrete Wilson-energy seed modes
1 and E_W.

This file proves that each of those two L2 modes has a canonical continuous
class-function representative.  The argument does not choose an arbitrary
continuous preimage: Gram--Schmidt triangularity places each L2 mode in the
image of the continuous class-function submodule generated by the two concrete
continuous seed functions.

The chosen continuous representative is then pulled back along the canonical
primary-plaquette cyclic boundary holonomy.  Its pointwise pullback is proved
to be an a.e. representative of the theorem-generated boundary-Haar L2 mode.

This is the exact bridge needed to state the remaining physical readout as a
pointwise boundary-moment identity rather than equality to an opaque L2 class.
-/

namespace MGAP4D
namespace MathlibAnalytic

open Filter MeasureTheory
open scoped ENNReal

noncomputable section

local instance sunTwoModeContinuousTopologicalGroup (N : ℕ) :
    IsTopologicalGroup (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupIsTopologicalGroup N

local instance sunTwoModeContinuousCompactSpace (N : ℕ) :
    CompactSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupCompactSpace N

local instance sunTwoModeContinuousSecondCountable (N : ℕ) :
    SecondCountableTopology (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupSecondCountableTopology N

local instance sunTwoModeContinuousMeasurableSpace (N : ℕ) :
    MeasurableSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupMeasurableSpace N

local instance sunTwoModeContinuousBorelSpace (N : ℕ) :
    BorelSpace (Matrix.specialUnitaryGroup (Fin N) ℂ) :=
  specialUnitaryGroupBorelSpace N

local instance sunTwoModeContinuousHaarMeasure (N : ℕ) :
    Measure.IsHaarMeasure
      (normalizedCompactHaar (Matrix.specialUnitaryGroup (Fin N) ℂ)) := by
  dsimp [normalizedCompactHaar]
  infer_instance

/-- Real continuous class functions on SU(N). -/
def specialUnitaryContinuousRealClassFunctionSubmodule
    (N : ℕ) :
    Submodule ℝ C(Matrix.specialUnitaryGroup (Fin N) ℂ, ℝ) where
  carrier :=
    {f | ∀ h g : Matrix.specialUnitaryGroup (Fin N) ℂ,
      f (h * g * h⁻¹) = f g}
  zero_mem' := by
    intro h g
    rfl
  add_mem' := by
    intro f g hf hg h x
    change f (h * x * h⁻¹) + g (h * x * h⁻¹) = f x + g x
    rw [hf h x, hg h x]
  smul_mem' := by
    intro c f hf h x
    change c * f (h * x * h⁻¹) = c * f x
    rw [hf h x]

/-- Continuous seed functions corresponding to E_W^0 = 1 and E_W^1 = E_W. -/
noncomputable def specialUnitaryWilsonContinuousTwoModeSeed
    (N : ℕ) :
    Fin 2 → C(Matrix.specialUnitaryGroup (Fin N) ℂ, ℝ) :=
  ![(1 : C(Matrix.specialUnitaryGroup (Fin N) ℂ, ℝ)),
    specialUnitaryWilsonPlaquetteEnergyContinuous N]

/-- Both continuous seed functions are class functions. -/
theorem specialUnitaryWilsonContinuousTwoModeSeed_mem_classFunction
    (N : ℕ)
    (k : Fin 2) :
    specialUnitaryWilsonContinuousTwoModeSeed N k ∈
      specialUnitaryContinuousRealClassFunctionSubmodule N := by
  fin_cases k
  · intro h g
    rfl
  · intro h g
    change specialUnitaryWilsonPlaquetteEnergy N (h * g * h⁻¹) =
      specialUnitaryWilsonPlaquetteEnergy N g
    exact specialUnitaryWilsonPlaquetteEnergy_conjInvariant h g

/-- The continuous seed and concrete normalized-Haar L2 seed agree under the
canonical ContinuousMap.toLp map. -/
theorem specialUnitaryWilsonContinuousTwoModeSeed_toLp
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2) :
    ContinuousMap.toLp
        (E := ℝ) 2
        (normalizedCompactHaar (Matrix.specialUnitaryGroup (Fin N) ℂ)) ℝ
        (specialUnitaryWilsonContinuousTwoModeSeed N k) =
      specialUnitaryWilsonPlaquetteEnergyHaarTwoModeSeed
        (lt_of_lt_of_le (by norm_num) hN2) k := by
  fin_cases k
  · simpa [specialUnitaryWilsonContinuousTwoModeSeed,
      specialUnitaryWilsonPlaquetteEnergyHaarTwoModeSeed] using
      (specialUnitaryWilsonPlaquetteEnergyPowerHaarL2_eq_continuousMap_toLp
        (lt_of_lt_of_le (by norm_num) hN2) 0).symm
  · simpa [specialUnitaryWilsonContinuousTwoModeSeed,
      specialUnitaryWilsonPlaquetteEnergyHaarTwoModeSeed] using
      (specialUnitaryWilsonPlaquetteEnergyPowerHaarL2_eq_continuousMap_toLp
        (lt_of_lt_of_le (by norm_num) hN2) 1).symm

/-- Each arbitrary-rank Wilson Gram--Schmidt L2 mode lies in the image of the
continuous class-function submodule. -/
theorem specialUnitaryWilsonHaarTwoMode_mem_continuousClassFunction_toLp_map
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2) :
    specialUnitaryWilsonHaarTwoMode hN2 k ∈
      Submodule.map
        (ContinuousMap.toLp
          (E := ℝ) 2
          (normalizedCompactHaar (Matrix.specialUnitaryGroup (Fin N) ℂ)) ℝ).toLinearMap
        (specialUnitaryContinuousRealClassFunctionSubmodule N) := by
  let seed :
      Fin 2 → SpecialUnitaryNormalizedHaarL2 N :=
    specialUnitaryWilsonPlaquetteEnergyHaarTwoModeSeed
      (lt_of_lt_of_le (by norm_num) hN2)
  let T :
      C(Matrix.specialUnitaryGroup (Fin N) ℂ, ℝ) →L[ℝ]
        SpecialUnitaryNormalizedHaarL2 N :=
    ContinuousMap.toLp
      (E := ℝ) 2
      (normalizedCompactHaar (Matrix.specialUnitaryGroup (Fin N) ℂ)) ℝ
  let M : Submodule ℝ (SpecialUnitaryNormalizedHaarL2 N) :=
    Submodule.map T.toLinearMap
      (specialUnitaryContinuousRealClassFunctionSubmodule N)
  have hSeed :
      seed '' Set.Iic k ⊆ M := by
    rintro v ⟨j, hj, rfl⟩
    refine ⟨specialUnitaryWilsonContinuousTwoModeSeed N j,
      specialUnitaryWilsonContinuousTwoModeSeed_mem_classFunction N j, ?_⟩
    simpa [T, seed] using
      specialUnitaryWilsonContinuousTwoModeSeed_toLp hN2 j
  have hGram :
      InnerProductSpace.gramSchmidt ℝ seed k ∈ M := by
    exact
      (Submodule.span_le.2 hSeed)
        (InnerProductSpace.gramSchmidt_mem_span ℝ seed (le_refl k))
  change InnerProductSpace.gramSchmidtNormed ℝ seed k ∈ M
  rw [InnerProductSpace.gramSchmidtNormed]
  exact M.smul_mem _ hGram

/-- Canonical continuous class-function representative of the k-th arbitrary-
rank Wilson two-mode Gram--Schmidt L2 vector. -/
noncomputable def specialUnitaryWilsonContinuousTwoMode
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2) :
    C(Matrix.specialUnitaryGroup (Fin N) ℂ, ℝ) :=
  (specialUnitaryWilsonHaarTwoMode_mem_continuousClassFunction_toLp_map
    hN2 k).choose

/-- The chosen representative is genuinely a class function. -/
theorem specialUnitaryWilsonContinuousTwoMode_mem_classFunction
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2) :
    specialUnitaryWilsonContinuousTwoMode hN2 k ∈
      specialUnitaryContinuousRealClassFunctionSubmodule N :=
  (specialUnitaryWilsonHaarTwoMode_mem_continuousClassFunction_toLp_map
    hN2 k).choose_spec.1

/-- The chosen continuous representative maps exactly to the theorem-generated
normalized-Haar L2 mode. -/
theorem specialUnitaryWilsonContinuousTwoMode_toLp
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2) :
    ContinuousMap.toLp
        (E := ℝ) 2
        (normalizedCompactHaar (Matrix.specialUnitaryGroup (Fin N) ℂ)) ℝ
        (specialUnitaryWilsonContinuousTwoMode hN2 k) =
      specialUnitaryWilsonHaarTwoMode hN2 k :=
  (specialUnitaryWilsonHaarTwoMode_mem_continuousClassFunction_toLp_map
    hN2 k).choose_spec.2

/-- Audit-visible conjugation invariance of the chosen continuous mode. -/
theorem specialUnitaryWilsonContinuousTwoMode_conjInvariant
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2)
    (h g : Matrix.specialUnitaryGroup (Fin N) ℂ) :
    specialUnitaryWilsonContinuousTwoMode hN2 k (h * g * h⁻¹) =
      specialUnitaryWilsonContinuousTwoMode hN2 k g :=
  specialUnitaryWilsonContinuousTwoMode_mem_classFunction hN2 k h g

/-- Boundary-Haar L2 realization of the k-th arbitrary-rank Wilson two-mode
conjugation-invariant mode on the canonical primary spatial plaquette. -/
noncomputable def periodicHypercubicEvenPrimarySpatialPlaquetteWilsonTwoModeBoundaryHaarL2
    (H : ℕ)
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2) :
    PeriodicHypercubicEvenBoundaryHaarL2 H N :=
  periodicHypercubicEvenPrimarySpatialPlaquetteHolonomyBoundaryL2Pullback H N
    (specialUnitaryWilsonHaarTwoMode hN2 k)

/-- Pointwise boundary representative obtained by evaluating the continuous
conjugation-invariant mode on the canonical cyclic primary-plaquette holonomy. -/
noncomputable def periodicHypercubicEvenPrimarySpatialPlaquetteWilsonTwoModeBoundaryObservable
    (H : ℕ)
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2)
    (b : (periodicHypercubicEvenEdgeOrbitPartition H).BoundaryConfiguration
      (Matrix.specialUnitaryGroup (Fin N) ℂ)) :
    ℝ :=
  specialUnitaryWilsonContinuousTwoMode hN2 k
    (periodicHypercubicEvenPrimarySpatialPlaquetteBoundaryCyclicHolonomy H N b)

/-- Boundary-Haar mode equals the measure-preserving pullback of the canonical
continuous representative before passing to its L2 class. -/
theorem periodicHypercubicEvenPrimarySpatialPlaquetteWilsonTwoModeBoundaryHaarL2_eq_continuousModePullback
    (H : ℕ)
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2) :
    periodicHypercubicEvenPrimarySpatialPlaquetteWilsonTwoModeBoundaryHaarL2
        H hN2 k =
      periodicHypercubicEvenPrimarySpatialPlaquetteHolonomyBoundaryL2Pullback H N
        (ContinuousMap.toLp
          (E := ℝ) 2
          (normalizedCompactHaar (Matrix.specialUnitaryGroup (Fin N) ℂ)) ℝ
          (specialUnitaryWilsonContinuousTwoMode hN2 k)) := by
  rw [specialUnitaryWilsonContinuousTwoMode_toLp]
  rfl

/-- The explicit continuous boundary observable is an a.e. representative of
the theorem-generated boundary-Haar L2 mode. -/
theorem periodicHypercubicEvenPrimarySpatialPlaquetteWilsonTwoModeBoundaryHaarL2_coeFn
    (H : ℕ)
    {N : ℕ}
    (hN2 : 2 ≤ N)
    (k : Fin 2) :
    periodicHypercubicEvenPrimarySpatialPlaquetteWilsonTwoModeBoundaryHaarL2
        H hN2 k =ᵐ[periodicHypercubicEvenBoundaryHaarMeasure H N]
      periodicHypercubicEvenPrimarySpatialPlaquetteWilsonTwoModeBoundaryObservable
        H hN2 k := by
  rw [periodicHypercubicEvenPrimarySpatialPlaquetteWilsonTwoModeBoundaryHaarL2_eq_continuousModePullback]
  let hMP :=
    measurePreserving_periodicHypercubicEvenPrimarySpatialPlaquetteBoundaryCyclicHolonomy
      H N
  let f : SpecialUnitaryNormalizedHaarL2 N :=
    ContinuousMap.toLp
      (E := ℝ) 2
      (normalizedCompactHaar (Matrix.specialUnitaryGroup (Fin N) ℂ)) ℝ
      (specialUnitaryWilsonContinuousTwoMode hN2 k)
  have hComp :
      periodicHypercubicEvenPrimarySpatialPlaquetteHolonomyBoundaryL2Pullback H N f
          =ᵐ[periodicHypercubicEvenBoundaryHaarMeasure H N]
        f ∘ periodicHypercubicEvenPrimarySpatialPlaquetteBoundaryCyclicHolonomy H N := by
    exact Lp.coeFn_compMeasurePreserving f hMP
  have hSource :
      f =ᵐ[normalizedCompactHaar (Matrix.specialUnitaryGroup (Fin N) ℂ)]
        specialUnitaryWilsonContinuousTwoMode hN2 k := by
    exact ContinuousMap.coeFn_toLp
      (𝕜 := ℝ) (p := (2 : ℝ≥0∞))
      (μ := normalizedCompactHaar (Matrix.specialUnitaryGroup (Fin N) ℂ))
      (specialUnitaryWilsonContinuousTwoMode hN2 k)
  have hPulled :
      f ∘ periodicHypercubicEvenPrimarySpatialPlaquetteBoundaryCyclicHolonomy H N
          =ᵐ[periodicHypercubicEvenBoundaryHaarMeasure H N]
        (specialUnitaryWilsonContinuousTwoMode hN2 k) ∘
          periodicHypercubicEvenPrimarySpatialPlaquetteBoundaryCyclicHolonomy H N :=
    hMP.quasiMeasurePreserving.ae_eq hSource
  exact hComp.trans (by
    simpa [periodicHypercubicEvenPrimarySpatialPlaquetteWilsonTwoModeBoundaryObservable,
      Function.comp_def] using hPulled)

end

end MathlibAnalytic
end MGAP4D
