import MGAP4D.MathlibAnalytic.SpecialUnitaryWilsonKernelRKHSFeature
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- The normalized real trace of the identity special-unitary matrix is one. -/
theorem normalizedSpecialUnitaryRealTrace_one
    (N : ℕ)
    (hN : 0 < N) :
    normalizedSpecialUnitaryRealTrace N
      (1 : Matrix.specialUnitaryGroup (Fin N) ℂ) = 1 := by
  unfold normalizedSpecialUnitaryRealTrace normalizedUnitaryRealTrace
  simp [specialUnitaryToUnitary, hN.ne']

/-- The conventional Wilson plaquette energy vanishes at the identity. -/
theorem specialUnitaryWilsonPlaquetteEnergy_one
    (N : ℕ)
    (hN : 0 < N) :
    specialUnitaryWilsonPlaquetteEnergy N
      (1 : Matrix.specialUnitaryGroup (Fin N) ℂ) = 0 := by
  rw [specialUnitaryWilsonPlaquetteEnergy_eq,
    normalizedSpecialUnitaryRealTrace_one N hN]
  ring

/-- The relative Wilson kernel has unit diagonal. -/
theorem specialUnitaryWilsonRelativeKernel_self
    (N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (g : Matrix.specialUnitaryGroup (Fin N) ℂ) :
    specialUnitaryWilsonRelativeKernel N beta g g = 1 := by
  unfold specialUnitaryWilsonRelativeKernel
  rw [show g⁻¹ * g = (1 : Matrix.specialUnitaryGroup (Fin N) ℂ) by group]
  unfold specialUnitaryWilsonBoltzmannCentralFunction
  rw [specialUnitaryWilsonPlaquetteEnergy_one N hN]
  simp

/-- Any real Hilbert feature whose kernel has unit diagonal has unit feature
norm. -/
theorem RealHilbertKernelFeature.feature_norm_eq_one
    {X : Type}
    {kernel : X → X → ℝ}
    (C : RealHilbertKernelFeature X kernel)
    (hDiagonal : ∀ x, kernel x x = 1)
    (x : X) :
    ‖C.feature x‖ = 1 := by
  have hsq : ‖C.feature x‖ ^ 2 = 1 := by
    calc
      ‖C.feature x‖ ^ 2 = inner ℝ (C.feature x) (C.feature x) :=
        (inner_self_eq_norm_sq_to_K (C.feature x)).symm
      _ = kernel x x := (C.kernel_eq_inner x x).symm
      _ = 1 := hDiagonal x
  nlinarith [norm_nonneg (C.feature x)]

/-- The exact one-plaquette Wilson RKHS feature has unit norm. -/
theorem specialUnitaryWilsonRelativeKernelFeature_norm_eq_one
    (N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (g : Matrix.specialUnitaryGroup (Fin N) ℂ) :
    ‖(specialUnitaryWilsonRelativeKernelFeature
        N hN beta hbeta).feature g‖ = 1 :=
  RealHilbertKernelFeature.feature_norm_eq_one
    (specialUnitaryWilsonRelativeKernelFeature N hN beta hbeta)
    (specialUnitaryWilsonRelativeKernel_self N hN beta) g

/-- Every pulled-back one-crossing-plaquette Wilson feature has unit norm. -/
theorem localCrossingWilsonKernelConcreteFeature_norm_eq_one
    {X : Type}
    (N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (positiveHalfHolonomy : X → Matrix.specialUnitaryGroup (Fin N) ℂ)
    (x : X) :
    ‖(localCrossingWilsonKernelConcreteFeature
        N hN beta hbeta positiveHalfHolonomy).feature x‖ = 1 :=
  RealHilbertKernelFeature.feature_norm_eq_one
    (localCrossingWilsonKernelConcreteFeature
      N hN beta hbeta positiveHalfHolonomy)
    (fun y => specialUnitaryWilsonRelativeKernel_self
      N hN beta (positiveHalfHolonomy y)) x

/-- A finite ordered product of unit-diagonal Hilbert kernels has a unit-norm
global completed-tensor-product feature. -/
theorem RealHilbertKernelFeature.listProd_feature_norm_eq_one
    {X ι : Type}
    (indices : List ι)
    (kernel : ι → X → X → ℝ)
    (C : ∀ i, RealHilbertKernelFeature X (kernel i))
    (hDiagonal : ∀ i x, kernel i x x = 1)
    (x : X) :
    ‖(RealHilbertKernelFeature.listProd indices kernel C).feature x‖ = 1 :=
  RealHilbertKernelFeature.feature_norm_eq_one
    (RealHilbertKernelFeature.listProd indices kernel C)
    (fun y => by simp [hDiagonal]) x

/-- The concrete global feature generated by any finite list of crossing
plaquette holonomies has unit norm. -/
theorem localCrossingWilsonKernelConcreteFeature_listProd_norm_eq_one
    {X ι : Type}
    (N : ℕ)
    (hN : 0 < N)
    (beta : ℝ)
    (hbeta : 0 ≤ beta)
    (indices : List ι)
    (positiveHalfHolonomy :
      ι → X → Matrix.specialUnitaryGroup (Fin N) ℂ)
    (x : X) :
    ‖(RealHilbertKernelFeature.listProd
        indices
        (fun i =>
          localCrossingWilsonKernel N beta (positiveHalfHolonomy i))
        (fun i =>
          localCrossingWilsonKernelConcreteFeature
            N hN beta hbeta (positiveHalfHolonomy i))).feature x‖ = 1 :=
  RealHilbertKernelFeature.listProd_feature_norm_eq_one
    indices
    (fun i => localCrossingWilsonKernel N beta (positiveHalfHolonomy i))
    (fun i => localCrossingWilsonKernelConcreteFeature
      N hN beta hbeta (positiveHalfHolonomy i))
    (fun i y => specialUnitaryWilsonRelativeKernel_self
      N hN beta (positiveHalfHolonomy i y)) x

end

end MathlibAnalytic
end MGAP4D
