import MGAP4D.MathlibAnalytic.Z2FiniteLatticeWilsonPlaquetteIndexPartition

namespace MGAP4D
namespace MathlibAnalytic

noncomputable section

/-- The three geometric locations of a plaquette relative to the reflection
plane. -/
inductive ReflectionPlaquetteSide
  | positive
  | crossing
  | negative
  deriving DecidableEq

/-- Move one element through a prefix, preserving permutation. -/
theorem list_perm_cons_append
    {α : Type} (a : α) (l₁ l₂ : List α) :
    a :: (l₁ ++ l₂) ~ l₁ ++ a :: l₂ := by
  induction l₁ with
  | nil => simp
  | cons b bs ih =>
      exact (List.Perm.swap a b (bs ++ l₂)).trans (List.Perm.cons b ih)

/-- Every list is a permutation of the concatenation of its three classifier
fibres. -/
theorem list_perm_three_side_partition
    {α : Type}
    (side : α → ReflectionPlaquetteSide)
    (l : List α) :
    l ~
      l.filter (fun a => side a = .positive) ++
      l.filter (fun a => side a = .crossing) ++
      l.filter (fun a => side a = .negative) := by
  induction l with
  | nil => simp
  | cons a as ih =>
      cases h : side a with
      | positive =>
          simpa [h, List.append_assoc] using List.Perm.cons a ih
      | crossing =>
          have hmove := list_perm_cons_append a
            (as.filter (fun b => side b = .positive))
            (as.filter (fun b => side b = .crossing) ++
              as.filter (fun b => side b = .negative))
          exact (List.Perm.cons a ih).trans (by
            simpa [h, List.append_assoc] using hmove)
      | negative =>
          have hmove := list_perm_cons_append a
            (as.filter (fun b => side b = .positive) ++
              as.filter (fun b => side b = .crossing))
            (as.filter (fun b => side b = .negative))
          exact (List.Perm.cons a ih).trans (by
            simpa [h, List.append_assoc] using hmove)

/-- A reflection-side classifier for every plaquette, together with the local
energy identities required on the three classifier fibres. -/
structure Z2FiniteLatticeWilsonPlaquetteSideClassification
    (L : FiniteLatticeWilsonSystem) where
  PositiveConfiguration : Type
  [positiveFintype : Fintype PositiveConfiguration]
  [positiveInhabited : Inhabited PositiveConfiguration]
  assemble : PositiveConfiguration → PositiveConfiguration → L.Configuration
  reflection : L.Configuration → L.Configuration
  reflection_involutive : Function.Involutive reflection
  reflection_assemble :
    ∀ x y, reflection (assemble x y) = assemble y x
  energyIdentity : ℝ
  energyNontrivial : ℝ
  energy_order : energyIdentity ≤ energyNontrivial
  crossingVariables : List (PositiveConfiguration → Z2Gauge)
  side : L.Plaquette → ReflectionPlaquetteSide
  positiveEnergyTerms : PositiveConfiguration → List ℝ
  positive_terms_eq :
    ∀ x y,
      ((Finset.univ.toList.filter fun p => side p = .positive).map fun p =>
        L.plaquetteEnergy (L.plaquetteHolonomy (assemble x y) p)) =
        positiveEnergyTerms x
  crossing_terms_eq :
    ∀ x y,
      ((Finset.univ.toList.filter fun p => side p = .crossing).map fun p =>
        L.plaquetteEnergy (L.plaquetteHolonomy (assemble x y) p)) =
        z2CrossingEnergyTerms crossingVariables
          energyIdentity energyNontrivial x y
  negative_terms_eq :
    ∀ x y,
      ((Finset.univ.toList.filter fun p => side p = .negative).map fun p =>
        L.plaquetteEnergy (L.plaquetteHolonomy (assemble x y) p)) =
        positiveEnergyTerms y

attribute [instance]
  Z2FiniteLatticeWilsonPlaquetteSideClassification.positiveFintype
  Z2FiniteLatticeWilsonPlaquetteSideClassification.positiveInhabited

/-- The positive-side plaquette list generated by the classifier. -/
def Z2FiniteLatticeWilsonPlaquetteSideClassification.positivePlaquettes
    {L : FiniteLatticeWilsonSystem}
    (C : Z2FiniteLatticeWilsonPlaquetteSideClassification L) :
    List L.Plaquette :=
  Finset.univ.toList.filter fun p => C.side p = .positive

/-- The crossing-plane plaquette list generated by the classifier. -/
def Z2FiniteLatticeWilsonPlaquetteSideClassification.crossingPlaquettes
    {L : FiniteLatticeWilsonSystem}
    (C : Z2FiniteLatticeWilsonPlaquetteSideClassification L) :
    List L.Plaquette :=
  Finset.univ.toList.filter fun p => C.side p = .crossing

/-- The negative-side plaquette list generated by the classifier. -/
def Z2FiniteLatticeWilsonPlaquetteSideClassification.negativePlaquettes
    {L : FiniteLatticeWilsonSystem}
    (C : Z2FiniteLatticeWilsonPlaquetteSideClassification L) :
    List L.Plaquette :=
  Finset.univ.toList.filter fun p => C.side p = .negative

/-- A classifier automatically supplies the combinatorial plaquette-index
partition. -/
def Z2FiniteLatticeWilsonPlaquetteSideClassification.toIndexPartition
    {L : FiniteLatticeWilsonSystem}
    (C : Z2FiniteLatticeWilsonPlaquetteSideClassification L) :
    Z2FiniteLatticeWilsonPlaquetteIndexPartition L :=
  { PositiveConfiguration := C.PositiveConfiguration
    assemble := C.assemble
    reflection := C.reflection
    reflection_involutive := C.reflection_involutive
    reflection_assemble := C.reflection_assemble
    energyIdentity := C.energyIdentity
    energyNontrivial := C.energyNontrivial
    energy_order := C.energy_order
    crossingVariables := C.crossingVariables
    positivePlaquettes := C.positivePlaquettes
    crossingPlaquettes := C.crossingPlaquettes
    negativePlaquettes := C.negativePlaquettes
    plaquette_index_perm := by
      simpa [Z2FiniteLatticeWilsonPlaquetteSideClassification.positivePlaquettes,
        Z2FiniteLatticeWilsonPlaquetteSideClassification.crossingPlaquettes,
        Z2FiniteLatticeWilsonPlaquetteSideClassification.negativePlaquettes]
        using list_perm_three_side_partition C.side Finset.univ.toList
    positiveEnergyTerms := C.positiveEnergyTerms
    positive_terms_eq := C.positive_terms_eq
    crossing_terms_eq := C.crossing_terms_eq
    negative_terms_eq := C.negative_terms_eq }

/-- A side classifier yields the complete finite-volume OS theorem. -/
theorem z2_finite_lattice_wilson_reflectionPositive_of_sideClassification
    {L : FiniteLatticeWilsonSystem}
    (C : Z2FiniteLatticeWilsonPlaquetteSideClassification L) :
    FiniteLatticeWilsonOSReflectionPositive
      C.toIndexPartition.toTermPartition.toActionDecomposition.toFactorization.toReflectionCertificate :=
  z2_finite_lattice_wilson_reflectionPositive_of_plaquetteIndexPartition
    C.toIndexPartition

/-- Audit-visible finite-volume OS certificate generated from the side
classifier. -/
def z2FiniteLatticeWilsonOSCertificateOfSideClassification
    (L : FiniteLatticeWilsonSystem)
    (C : Z2FiniteLatticeWilsonPlaquetteSideClassification L) :
    FiniteWilsonOSReflectionPositivityCertificate L :=
  z2FiniteLatticeWilsonOSCertificateOfPlaquetteIndexPartition
    L C.toIndexPartition

end

end MathlibAnalytic
end MGAP4D
