import MGAP4D.MathlibAnalytic.FiniteWilsonOSPositiveConfigurationShiftSemigroup
import MGAP4D.MathlibAnalytic.Z2FiniteEvenFourTorusWilsonGeometricClassification
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped InnerProduct

noncomputable section

/-- Exact geometric/analytic data turning a concrete permutation of the even
four-torus positive-half `Z₂` configurations into a Wilson OS time step.  The
reflection certificate and Wilson Boltzmann kernel are generated by the
existing concrete even-torus construction; only the three shift conditions
needed for symmetry, positivity, and contraction remain visible. -/
structure FiniteEvenFourTorusZ2PositiveShiftData
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 ≤ β)
    (hEnergyIdentity : 0 ≤ energyIdentity)
    (hEnergyNontrivial : 0 ≤ energyNontrivial)
    (D : FiniteEvenFourTorusWilsonGeometricEnergyData H β energyIdentity
      energyNontrivial hβ hEnergyIdentity hEnergyNontrivial) where
  shift :
    (finiteEvenFourTorusEdgeOrbitPartition H).PositiveConfiguration ≃
      (finiteEvenFourTorusEdgeOrbitPartition H).PositiveConfiguration
  kernel_shift_adjoint :
    ∀ x y,
      (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
          H β energyIdentity energyNontrivial hβ hEnergyIdentity
            hEnergyNontrivial D).reflectionData.kernel (shift x) y =
        (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
          H β energyIdentity energyNontrivial hβ hEnergyIdentity
            hEnergyNontrivial D).reflectionData.kernel x (shift y)
  shiftedKernel_quadratic_nonneg :
    ∀ F,
      0 ≤ FiniteWilsonOSReflectionPositivityCertificate.finiteWilsonOSShiftedKernelForm
        (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
          H β energyIdentity energyNontrivial hβ hEnergyIdentity
            hEnergyNontrivial D)
        (FiniteWilsonOSReflectionPositivityCertificate.positiveConfigurationShiftedKernel
          (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
            H β energyIdentity energyNontrivial hβ hEnergyIdentity
              hEnergyNontrivial D) shift) F F
  shiftedObservable_quadratic_le :
    ∀ F,
      (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
          H β energyIdentity energyNontrivial hβ hEnergyIdentity
            hEnergyNontrivial D).reflectionData.wilsonOneLayerTransferForm
          (FiniteWilsonOSReflectionPositivityCertificate.positiveConfigurationObservableShift
            shift F)
          (FiniteWilsonOSReflectionPositivityCertificate.positiveConfigurationObservableShift
            shift F) ≤
        (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
          H β energyIdentity energyNontrivial hβ hEnergyIdentity
            hEnergyNontrivial D).reflectionData.wilsonOneLayerTransferForm F F

namespace FiniteEvenFourTorusZ2PositiveShiftData

variable
    {H : ℕ}
    {β energyIdentity energyNontrivial : ℝ}
    {hβ : 0 ≤ β}
    {hEnergyIdentity : 0 ≤ energyIdentity}
    {hEnergyNontrivial : 0 ≤ energyNontrivial}
    {D : FiniteEvenFourTorusWilsonGeometricEnergyData H β energyIdentity
      energyNontrivial hβ hEnergyIdentity hEnergyNontrivial}

/-- The concrete positive-shift data as the generic kernel-level certificate. -/
def toPositiveConfigurationShiftCertificate
    (S : FiniteEvenFourTorusZ2PositiveShiftData H β energyIdentity
      energyNontrivial hβ hEnergyIdentity hEnergyNontrivial D) :
    (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
      H β energyIdentity energyNontrivial hβ hEnergyIdentity
        hEnergyNontrivial D).PositiveConfigurationShiftCertificate where
  shift := S.shift
  kernel_shift_adjoint := S.kernel_shift_adjoint
  shiftedKernel_quadratic_nonneg := S.shiftedKernel_quadratic_nonneg
  shiftedObservable_quadratic_le := S.shiftedObservable_quadratic_le

@[simp] theorem toPositiveConfigurationShiftCertificate_shift
    (S : FiniteEvenFourTorusZ2PositiveShiftData H β energyIdentity
      energyNontrivial hβ hEnergyIdentity hEnergyNontrivial D) :
    S.toPositiveConfigurationShiftCertificate.shift = S.shift :=
  rfl

/-- The concrete one-step shifted kernel is exactly the even-four-torus Wilson
Boltzmann weight with the first assembled half translated. -/
theorem shiftedKernel_eq_evenFourTorus_wilsonWeight
    (S : FiniteEvenFourTorusZ2PositiveShiftData H β energyIdentity
      energyNontrivial hβ hEnergyIdentity hEnergyNontrivial D)
    (x y : (finiteEvenFourTorusEdgeOrbitPartition H).PositiveConfiguration) :
    FiniteWilsonOSReflectionPositivityCertificate.positiveConfigurationShiftedKernel
        (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
          H β energyIdentity energyNontrivial hβ hEnergyIdentity
            hEnergyNontrivial D) S.shift x y =
      Real.exp
        (-β *
          (finiteEvenFourTorusZ2WilsonSystem H β energyIdentity energyNontrivial
            hβ hEnergyIdentity hEnergyNontrivial).wilsonAction
            (finiteEvenFourTorusAssemble H (S.shift x) y)) := by
  exact
    FiniteWilsonOSReflectionPositivityCertificate.positiveConfigurationShiftedKernel_eq_wilsonWeight
      (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
        H β energyIdentity energyNontrivial hβ hEnergyIdentity
          hEnergyNontrivial D) S.shift x y

/-- Every natural-time kernel is the concrete even-four-torus Wilson Boltzmann
weight with the first half shifted by the corresponding permutation power. -/
theorem iteratedShiftedKernel_eq_evenFourTorus_wilsonWeight
    (S : FiniteEvenFourTorusZ2PositiveShiftData H β energyIdentity
      energyNontrivial hβ hEnergyIdentity hEnergyNontrivial D)
    (n : ℕ)
    (x y : (finiteEvenFourTorusEdgeOrbitPartition H).PositiveConfiguration) :
    S.toPositiveConfigurationShiftCertificate.iteratedShiftedKernel n x y =
      Real.exp
        (-β *
          (finiteEvenFourTorusZ2WilsonSystem H β energyIdentity energyNontrivial
            hβ hEnergyIdentity hEnergyNontrivial).wilsonAction
            (finiteEvenFourTorusAssemble H
              (S.toPositiveConfigurationShiftCertificate.shiftIterate n x) y)) := by
  exact
    S.toPositiveConfigurationShiftCertificate.iteratedShiftedKernel_eq_wilsonWeight
      n x y

/-- A concrete nonzero-coupling action witness forces the completed geometric
shift operator on the even-four-torus OS Hilbert space to be nonidentity. -/
theorem hilbertShift_ne_identity_of_evenFourTorus_action_ne
    (S : FiniteEvenFourTorusZ2PositiveShiftData H β energyIdentity
      energyNontrivial hβ hEnergyIdentity hEnergyNontrivial D)
    (x y : (finiteEvenFourTorusEdgeOrbitPartition H).PositiveConfiguration)
    (hBeta : β ≠ 0)
    (hAction :
      (finiteEvenFourTorusZ2WilsonSystem H β energyIdentity energyNontrivial
        hβ hEnergyIdentity hEnergyNontrivial).wilsonAction
          (finiteEvenFourTorusAssemble H (S.shift x) y) ≠
        (finiteEvenFourTorusZ2WilsonSystem H β energyIdentity energyNontrivial
          hβ hEnergyIdentity hEnergyNontrivial).wilsonAction
          (finiteEvenFourTorusAssemble H x y)) :
    S.toPositiveConfigurationShiftCertificate.toOneLayerShiftedKernelCertificate.hilbertShiftContinuousLinearMap ≠
      (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
        H β energyIdentity energyNontrivial hβ hEnergyIdentity
          hEnergyNontrivial D).oneLayerIdentityTransfer := by
  exact
    S.toPositiveConfigurationShiftCertificate.hilbertShiftContinuousLinearMap_ne_identity_of_wilsonAction_ne
      x y hBeta hAction

/-- Public concrete even-four-torus package. -/
theorem finiteEvenFourTorusZ2PositiveShiftKernelPackage
    (S : FiniteEvenFourTorusZ2PositiveShiftData H β energyIdentity
      energyNontrivial hβ hEnergyIdentity hEnergyNontrivial D) :
    (∀ n : ℕ, ∀ F G,
      inner ℝ
          (S.toPositiveConfigurationShiftCertificate.toOneLayerShiftedKernelCertificate.hilbertShiftSemigroup n
            ((finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
              H β energyIdentity energyNontrivial hβ hEnergyIdentity
                hEnergyNontrivial D).oneLayerObservableEmbedding F))
          ((finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
            H β energyIdentity energyNontrivial hβ hEnergyIdentity
              hEnergyNontrivial D).oneLayerObservableEmbedding G) =
        FiniteWilsonOSReflectionPositivityCertificate.finiteWilsonOSShiftedKernelForm
          (finiteEvenFourTorusZ2WilsonOSCertificateOfGeometricEnergyData
            H β energyIdentity energyNontrivial hβ hEnergyIdentity
              hEnergyNontrivial D)
          (S.toPositiveConfigurationShiftCertificate.iteratedShiftedKernel n)
          F G) ∧
    (∀ m n : ℕ,
      S.toPositiveConfigurationShiftCertificate.toOneLayerShiftedKernelCertificate.hilbertShiftSemigroup (m + n) =
        (S.toPositiveConfigurationShiftCertificate.toOneLayerShiftedKernelCertificate.hilbertShiftSemigroup m).comp
          (S.toPositiveConfigurationShiftCertificate.toOneLayerShiftedKernelCertificate.hilbertShiftSemigroup n)) := by
  exact ⟨
    S.toPositiveConfigurationShiftCertificate.hilbertShiftSemigroup_matrixElement_eq_iteratedShiftedKernelForm,
    S.toPositiveConfigurationShiftCertificate.toOneLayerShiftedKernelCertificate.hilbertShiftSemigroup_add⟩

end FiniteEvenFourTorusZ2PositiveShiftData

end

end MathlibAnalytic
end MGAP4D
