import MGAP4D.MathlibAnalytic.Z2FiniteEvenFourTorusPerronPosteriorNonstrictKernelResponse
import MGAP4D.MathlibAnalytic.Z2FiniteEvenFourTorusUnfixedGaugePerronSmoothedPosteriorRecursiveInfluenceRows
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators

noncomputable section

/-- The finite non-strict kernel response controls the smoothed-residual
four-point cross ratio. -/
theorem finiteEvenFourTorusZ2PerronSmoothedResidual_crossRatio_of_kernelResponse
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (A C : FiniteEvenFourTorusZ2SliceConfiguration H)
    (target source : FiniteEvenFourTorusSpatialLink H)
    (hNe : target ≠ source)
    (hAgree : FiniteProductAgreeOff A C source)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ)
    (hDomination :
      FiniteEvenFourTorusZ2PerronPosteriorCanonicalDominatedBy
        H β energyIdentity energyNontrivial hβ hEnergy kernel) :
    FinitePositiveWeightSingleSiteCrossRatioBound
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidual
        H β energyIdentity energyNontrivial hβ.le hEnergy.le)
      A C target
      (1 + finiteZ2CrossingLikelihoodRatio
        (z2WilsonTemporalCrossingRate
          β energyIdentity energyNontrivial) *
        finiteEvenFourTorusZ2PerronPosteriorKernelResponseError
          H β energyIdentity energyNontrivial
          kernel iterations target source) := by
  apply
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidual_crossRatio_of_sourceTiltExpectation
      H β energyIdentity energyNontrivial hβ hEnergy
      A C target source hNe hAgree
  intro g h
  let rightWeight :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
      H β energyIdentity energyNontrivial hβ.le hEnergy.le
      (Function.update A target g)
  let sourceTilt :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTilt
      H β energyIdentity energyNontrivial A source (C source)
  let error :=
    finiteEvenFourTorusZ2PerronPosteriorKernelResponseError
      H β energyIdentity energyNontrivial kernel iterations target source
  have hDiscrepancy :=
    finiteEvenFourTorusZ2PerronResidualExpectation_difference_abs_le_kernelResponse
      H β energyIdentity energyNontrivial hβ hEnergy
      A target source g h (C source) kernel iterations hDomination
  have hDiscrepancyBound :
      |finitePositiveWeightGlobalExpectation
            (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
              H β energyIdentity energyNontrivial hβ.le hEnergy.le
              (Function.update A target h)) sourceTilt -
          finitePositiveWeightGlobalExpectation rightWeight sourceTilt| ≤
        error := by
    rw [←
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTiltExpectation_eq_globalExpectation,
      ←
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTiltExpectation_eq_globalExpectation]
    exact hDiscrepancy
  have hOneSided :=
    finitePositiveWeightGlobalExpectation_le_one_add_error_div_lower_mul
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
        H β energyIdentity energyNontrivial hβ.le hEnergy.le
        (Function.update A target h))
      rightWeight
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight_pos
        H β energyIdentity energyNontrivial hβ hEnergy
        (Function.update A target g))
      sourceTilt
      (finiteZ2CrossingLikelihoodRatio
        (z2WilsonTemporalCrossingRate
          β energyIdentity energyNontrivial))⁻¹
      error
      (inv_pos.mpr (finiteZ2CrossingLikelihoodRatio_pos
        (z2WilsonTemporalCrossingRate_pos hβ hEnergy).le
        (z2WilsonTemporalCrossingRate_lt_one hβ hEnergy)))
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTilt_ratio_inv_le
        H β energyIdentity energyNontrivial hβ hEnergy
        A source (C source))
      (finiteEvenFourTorusZ2PerronPosteriorKernelResponseError_nonneg
        H β energyIdentity energyNontrivial hβ hEnergy
        kernel iterations target source)
      hDiscrepancyBound
  rw [
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTiltExpectation_eq_globalExpectation,
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTiltExpectation_eq_globalExpectation]
  simpa [rightWeight, sourceTilt, error, div_eq_mul_inv,
    mul_comm, mul_left_comm, mul_assoc] using hOneSided

/-- Radius generated by one finite non-strict kernel bootstrap step. -/
noncomputable def finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ)
    (target source : FiniteEvenFourTorusSpatialLink H) : ℝ :=
  if target = source then 0 else
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorRecursiveCrossRatioRadius
      H β energyIdentity energyNontrivial target source
      (finiteEvenFourTorusZ2PerronPosteriorKernelResponseError
        H β energyIdentity energyNontrivial
        kernel iterations target source)

/-- The bootstrap radius is nonnegative. -/
theorem finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius_nonneg
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ)
    (target source : FiniteEvenFourTorusSpatialLink H) :
    0 ≤ finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius
      H β energyIdentity energyNontrivial
      kernel iterations target source := by
  by_cases hEq : target = source
  · simp [finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius, hEq]
  · rw [finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius, if_neg hEq]
    exact
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorRecursiveCrossRatioRadius_nonneg
        H β energyIdentity energyNontrivial hβ hEnergy target source
        (finiteEvenFourTorusZ2PerronPosteriorKernelResponseError
          H β energyIdentity energyNontrivial
          kernel iterations target source)
        (finiteEvenFourTorusZ2PerronPosteriorKernelResponseError_nonneg
          H β energyIdentity energyNontrivial hβ hEnergy
          kernel iterations target source)

/-- The full posterior cross ratio produced by a finite kernel response. -/
theorem finiteEvenFourTorusZ2PerronPosterior_crossRatio_of_kernelResponse
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (environment A C : FiniteEvenFourTorusZ2SliceConfiguration H)
    (target source : FiniteEvenFourTorusSpatialLink H)
    (hNe : target ≠ source)
    (hAgree : FiniteProductAgreeOff A C source)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ)
    (hDomination :
      FiniteEvenFourTorusZ2PerronPosteriorCanonicalDominatedBy
        H β energyIdentity energyNontrivial hβ hEnergy kernel) :
    FinitePositiveWeightSingleSiteCrossRatioBound
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
        H β energyIdentity energyNontrivial hβ.le hEnergy.le environment)
      A C target
      (Real.exp
        (finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius
          H β energyIdentity energyNontrivial
          kernel iterations target source)) := by
  have hResidualRaw :=
    finiteEvenFourTorusZ2PerronSmoothedResidual_crossRatio_of_kernelResponse
      H β energyIdentity energyNontrivial hβ hEnergy
      A C target source hNe hAgree kernel iterations hDomination
  let error :=
    finiteEvenFourTorusZ2PerronPosteriorKernelResponseError
      H β energyIdentity energyNontrivial kernel iterations target source
  have hResidual :
      FinitePositiveWeightSingleSiteCrossRatioBound
        (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidual
          H β energyIdentity energyNontrivial hβ.le hEnergy.le)
        A C target
        (Real.exp
          (Real.log
            (1 + finiteZ2CrossingLikelihoodRatio
              (z2WilsonTemporalCrossingRate
                β energyIdentity energyNontrivial) * error))) := by
    rw [←
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedRecursiveResidualCoefficient_eq_exp_log
        H β energyIdentity energyNontrivial hβ hEnergy error
        (finiteEvenFourTorusZ2PerronPosteriorKernelResponseError_nonneg
          H β energyIdentity energyNontrivial hβ hEnergy
          kernel iterations target source)]
    exact hResidualRaw
  have hCombined :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight_crossRatio_of_residual
      H β energyIdentity energyNontrivial hβ hEnergy
      environment A C target source hNe hAgree
      (Real.exp
        (Real.log
          (1 + finiteZ2CrossingLikelihoodRatio
            (z2WilsonTemporalCrossingRate
              β energyIdentity energyNontrivial) * error)))
      (le_of_lt (Real.exp_pos _)) hResidual
  let localRadius :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSandwichLocalCrossRatioRadius
      H β energyIdentity energyNontrivial target source
  let residualRadius :=
    Real.log
      (1 + finiteZ2CrossingLikelihoodRatio
        (z2WilsonTemporalCrossingRate
          β energyIdentity energyNontrivial) * error)
  have hExp :
      Real.exp
          (finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius
            H β energyIdentity energyNontrivial
            kernel iterations target source) =
        Real.exp localRadius *
          (Real.exp localRadius * Real.exp residualRadius) := by
    rw [finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius,
      if_neg hNe]
    unfold
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorRecursiveCrossRatioRadius
    change Real.exp (2 * localRadius + residualRadius) = _
    rw [show 2 * localRadius + residualRadius =
      localRadius + (localRadius + residualRadius) by ring]
    simp only [Real.exp_add]
  rw [hExp]
  simpa [localRadius, residualRadius, error] using hCombined

/-- Cross-ratio entry data generated by a finite non-strict bootstrap step. -/
noncomputable def finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapEntryData
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (environment : FiniteEvenFourTorusZ2SliceConfiguration H)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ)
    (hDomination :
      FiniteEvenFourTorusZ2PerronPosteriorCanonicalDominatedBy
        H β energyIdentity energyNontrivial hβ hEnergy kernel) :
    FinitePositiveWeightCrossRatioInfluenceEntryData
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
        H β energyIdentity energyNontrivial hβ.le hEnergy.le environment) :=
  { radius :=
      finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius
        H β energyIdentity energyNontrivial kernel iterations
    radius_nonneg :=
      finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius_nonneg
        H β energyIdentity energyNontrivial hβ hEnergy kernel iterations
    crossRatioBound := by
      intro target source A B hNe hAgree
      exact
        finiteEvenFourTorusZ2PerronPosterior_crossRatio_of_kernelResponse
          H β energyIdentity energyNontrivial hβ hEnergy
          environment A B target source hNe hAgree
          kernel iterations hDomination }

/-- Conditional influence entry generated by a finite bootstrap step. -/
noncomputable def finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapInfluence
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (environment : FiniteEvenFourTorusZ2SliceConfiguration H)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ)
    (hDomination :
      FiniteEvenFourTorusZ2PerronPosteriorCanonicalDominatedBy
        H β energyIdentity energyNontrivial hβ hEnergy kernel)
    (target source : FiniteEvenFourTorusSpatialLink H) : ℝ :=
  finitePositiveWeightCrossRatioEntryInfluence
    (finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapEntryData
      H β energyIdentity energyNontrivial hβ hEnergy
      environment kernel iterations hDomination)
    target source

/-- Conditional changes are controlled by the bootstrap influence. -/
theorem finiteEvenFourTorusZ2PerronPosteriorConditionalL1_le_bootstrapInfluence
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (environment A B : FiniteEvenFourTorusZ2SliceConfiguration H)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ)
    (hDomination :
      FiniteEvenFourTorusZ2PerronPosteriorCanonicalDominatedBy
        H β energyIdentity energyNontrivial hβ hEnergy kernel)
    (target source : FiniteEvenFourTorusSpatialLink H)
    (hAgree : FiniteProductAgreeOff A B source) :
    finitePositiveWeightSingleSiteConditionalL1
        (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
          H β energyIdentity energyNontrivial hβ.le hEnergy.le environment)
        A B target ≤
      finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapInfluence
        H β energyIdentity energyNontrivial hβ hEnergy
        environment kernel iterations hDomination target source := by
  exact
    finitePositiveWeightSingleSiteConditionalL1_le_crossRatioEntryInfluence
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
        H β energyIdentity energyNontrivial hβ.le hEnergy.le environment)
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight_pos
        H β energyIdentity energyNontrivial hβ hEnergy environment)
      (finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapEntryData
        H β energyIdentity energyNontrivial hβ hEnergy
        environment kernel iterations hDomination)
      target source A B hAgree

/-- Weight-independent kernel produced by one finite bootstrap step. -/
noncomputable def finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapNext
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ) :
    FiniteNonnegativeInfluenceKernelData
      (FiniteEvenFourTorusSpatialLink H) :=
  { influence := fun target source =>
      if target = source then 0 else
        2 *
            finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorLocalInfluence
              H β energyIdentity energyNontrivial target source +
          finiteZ2CrossingLikelihoodRatio
              (z2WilsonTemporalCrossingRate
                β energyIdentity energyNontrivial) *
            finiteEvenFourTorusZ2PerronPosteriorKernelResponseError
              H β energyIdentity energyNontrivial
              kernel iterations target source
    influence_nonneg := by
      intro target source
      split
      · exact le_rfl
      · exact add_nonneg
          (mul_nonneg (by norm_num)
            (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorLocalInfluence_nonneg
              H β energyIdentity energyNontrivial hβ.le hEnergy.le target source))
          (mul_nonneg
            (le_of_lt
              (finiteZ2CrossingLikelihoodRatio_pos
                (z2WilsonTemporalCrossingRate_pos hβ hEnergy).le
                (z2WilsonTemporalCrossingRate_lt_one hβ hEnergy)))
            (finiteEvenFourTorusZ2PerronPosteriorKernelResponseError_nonneg
              H β energyIdentity energyNontrivial hβ hEnergy
              kernel iterations target source))
    influence_diagonal_zero := by
      intro target
      simp }

/-- One generated influence entry is bounded by the next kernel. -/
theorem finiteEvenFourTorusZ2PerronPosteriorBootstrapInfluence_le_next
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (environment : FiniteEvenFourTorusZ2SliceConfiguration H)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ)
    (hDomination :
      FiniteEvenFourTorusZ2PerronPosteriorCanonicalDominatedBy
        H β energyIdentity energyNontrivial hβ hEnergy kernel)
    (target source : FiniteEvenFourTorusSpatialLink H) :
    finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapInfluence
        H β energyIdentity energyNontrivial hβ hEnergy
        environment kernel iterations hDomination target source ≤
      (finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapNext
        H β energyIdentity energyNontrivial hβ hEnergy
        kernel iterations).influence target source := by
  by_cases hEq : target = source
  · subst source
    simp [
      finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapInfluence,
      finitePositiveWeightCrossRatioEntryInfluence_diagonal,
      finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapNext]
  · let localRadius :=
      finiteEvenFourTorusZ2UnfixedGaugePerronSandwichLocalCrossRatioRadius
        H β energyIdentity energyNontrivial target source
    let ratio :=
      finiteZ2CrossingLikelihoodRatio
        (z2WilsonTemporalCrossingRate
          β energyIdentity energyNontrivial)
    let error :=
      finiteEvenFourTorusZ2PerronPosteriorKernelResponseError
        H β energyIdentity energyNontrivial kernel iterations target source
    have hLocal : 0 ≤ localRadius :=
      finiteEvenFourTorusZ2UnfixedGaugePerronSandwichLocalCrossRatioRadius_nonneg
        H β energyIdentity energyNontrivial hβ.le hEnergy.le target source
    have hRatio : 0 ≤ ratio :=
      le_of_lt
        (finiteZ2CrossingLikelihoodRatio_pos
          (z2WilsonTemporalCrossingRate_pos hβ hEnergy).le
          (z2WilsonTemporalCrossingRate_lt_one hβ hEnergy))
    have hError : 0 ≤ error :=
      finiteEvenFourTorusZ2PerronPosteriorKernelResponseError_nonneg
        H β energyIdentity energyNontrivial hβ hEnergy
        kernel iterations target source
    have hProduct : 0 ≤ ratio * error := mul_nonneg hRatio hError
    have hResidualRadius : 0 ≤ Real.log (1 + ratio * error) :=
      Real.log_nonneg (by nlinarith)
    unfold finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapInfluence
    rw [finitePositiveWeightCrossRatioEntryInfluence_eq_transform]
    simp only [
      finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapEntryData,
      finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapRadius,
      finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapNext,
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorLocalInfluence,
      hEq, if_false]
    unfold
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorRecursiveCrossRatioRadius
    change
      finitePositiveWeightCrossRatioInfluenceTransform
          (2 * localRadius + Real.log (1 + ratio * error)) ≤
        2 * finitePositiveWeightCrossRatioInfluenceTransform localRadius +
          ratio * error
    calc
      finitePositiveWeightCrossRatioInfluenceTransform
          (2 * localRadius + Real.log (1 + ratio * error)) ≤
        finitePositiveWeightCrossRatioInfluenceTransform (2 * localRadius) +
          finitePositiveWeightCrossRatioInfluenceTransform
            (Real.log (1 + ratio * error)) :=
        finitePositiveWeightCrossRatioInfluenceTransform_add_le
          (2 * localRadius) (Real.log (1 + ratio * error))
          (mul_nonneg (by norm_num) hLocal) hResidualRadius
      _ ≤
        2 * finitePositiveWeightCrossRatioInfluenceTransform localRadius +
          finitePositiveWeightCrossRatioInfluenceTransform
            (Real.log (1 + ratio * error)) := by
        exact add_le_add
          (finitePositiveWeightCrossRatioInfluenceTransform_two_mul_le
            localRadius hLocal)
          (le_refl _)
      _ ≤
        2 * finitePositiveWeightCrossRatioInfluenceTransform localRadius +
          ratio * error := by
        exact add_le_add (le_refl _)
          (finitePositiveWeightCrossRatioInfluenceTransform_log_one_add_le
            (ratio * error) hProduct)

/-- If a kernel dominates every canonical target-fiber matrix, its bootstrap
successor does so as well. -/
theorem finiteEvenFourTorusZ2PerronPosteriorCanonicalDominatedBy_next
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (kernel :
      FiniteNonnegativeInfluenceKernelData
        (FiniteEvenFourTorusSpatialLink H))
    (iterations : ℕ)
    (hDomination :
      FiniteEvenFourTorusZ2PerronPosteriorCanonicalDominatedBy
        H β energyIdentity energyNontrivial hβ hEnergy kernel) :
    FiniteEvenFourTorusZ2PerronPosteriorCanonicalDominatedBy
      H β energyIdentity energyNontrivial hβ hEnergy
      (finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapNext
        H β energyIdentity energyNontrivial hβ hEnergy
        kernel iterations) := by
  intro environment boundaryTarget g target source
  let weight :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
      H β energyIdentity energyNontrivial hβ.le hEnergy.le
      (Function.update environment boundaryTarget g)
  by_cases hEq : target = source
  · subst source
    simp [weight,
      finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapNext]
  · rw [finitePositiveWeightCanonicalNonstrictInfluence, if_neg hEq]
    rw [Finset.max'_le_iff]
    intro value hValue
    rcases Finset.mem_image.mp hValue with ⟨pair, _hPair, rfl⟩
    by_cases hAgree : FiniteProductAgreeOff pair.1 pair.2 source
    · simp only [hAgree, if_true]
      exact
        (finiteEvenFourTorusZ2PerronPosteriorConditionalL1_le_bootstrapInfluence
          H β energyIdentity energyNontrivial hβ hEnergy
          (Function.update environment boundaryTarget g)
          pair.1 pair.2 kernel iterations hDomination
          target source hAgree).trans
          (finiteEvenFourTorusZ2PerronPosteriorBootstrapInfluence_le_next
            H β energyIdentity energyNontrivial hβ hEnergy
            (Function.update environment boundaryTarget g)
            kernel iterations hDomination target source)
    · simp only [hAgree, if_false]
      exact
        (finiteEvenFourTorusZ2PerronPosteriorKernelBootstrapNext
          H β energyIdentity energyNontrivial hβ hEnergy
          kernel iterations).influence_nonneg target source

end

end MathlibAnalytic
end MGAP4D
