import MGAP4D.MathlibAnalytic.FinitePositiveWeightReciprocalInfluenceKernelResponse
import MGAP4D.MathlibAnalytic.Z2FiniteEvenFourTorusUnfixedGaugePerronSmoothedResidualRecursiveResponse
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped BigOperators

noncomputable section

/-- Exact singleton cross-weight source envelope generated by a target-local
change of the observed boundary. -/
def finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (target coordinate : FiniteEvenFourTorusSpatialLink H) : ℝ :=
  finitePositiveWeightLocalTiltConditionalSourceBound
    ({target} : Finset (FiniteEvenFourTorusSpatialLink H))
    (finiteZ2CrossingLikelihoodRatio
      (z2WilsonTemporalCrossingRate
        β energyIdentity energyNontrivial))⁻¹
    (finiteZ2CrossingLikelihoodRatio
      (z2WilsonTemporalCrossingRate
        β energyIdentity energyNontrivial))
    coordinate

/-- Total target-tilt source amplitude. -/
def finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceAmplitude
    (β energyIdentity energyNontrivial : ℝ) : ℝ :=
  let ratio := finiteZ2CrossingLikelihoodRatio
    (z2WilsonTemporalCrossingRate
      β energyIdentity energyNontrivial)
  2 * (1 - (ratio / ratio⁻¹)⁻¹)

/-- The target-local source envelope is nonnegative. -/
theorem finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope_nonneg
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (target coordinate : FiniteEvenFourTorusSpatialLink H) :
    0 ≤ finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
      H β energyIdentity energyNontrivial target coordinate := by
  let ratio := finiteZ2CrossingLikelihoodRatio
    (z2WilsonTemporalCrossingRate
      β energyIdentity energyNontrivial)
  have hRatioPos : 0 < ratio :=
    finiteZ2CrossingLikelihoodRatio_pos
      (z2WilsonTemporalCrossingRate_pos hβ hEnergy).le
      (z2WilsonTemporalCrossingRate_lt_one hβ hEnergy)
  have hRatioOne : 1 ≤ ratio :=
    one_le_finiteZ2CrossingLikelihoodRatio
      (z2WilsonTemporalCrossingRate_pos hβ hEnergy).le
      (z2WilsonTemporalCrossingRate_lt_one hβ hEnergy)
  have hInvLeOne : ratio⁻¹ ≤ 1 :=
    (inv_le_one₀ hRatioPos).2 hRatioOne
  have hLowerUpper : ratio⁻¹ ≤ ratio :=
    le_trans hInvLeOne hRatioOne
  have hQuotientOne : 1 ≤ ratio / ratio⁻¹ := by
    exact (le_div_iff₀ (inv_pos.mpr hRatioPos)).2 hLowerUpper
  have hQuotientPos : 0 < ratio / ratio⁻¹ :=
    div_pos hRatioPos (inv_pos.mpr hRatioPos)
  have hInverseLeOne : (ratio / ratio⁻¹)⁻¹ ≤ 1 :=
    (inv_le_one₀ hQuotientPos).2 hQuotientOne
  unfold
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
    finitePositiveWeightLocalTiltConditionalSourceBound
  split
  · dsimp [ratio]
    nlinarith
  · exact le_rfl

/-- The total mass of the target-local source envelope is exactly its one-site
amplitude. -/
theorem finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope_total
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (target : FiniteEvenFourTorusSpatialLink H) :
    finiteProductVariationTotal
        (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
          H β energyIdentity energyNontrivial target) =
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceAmplitude
        β energyIdentity energyNontrivial := by
  classical
  unfold finiteProductVariationTotal
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceAmplitude
    finitePositiveWeightLocalTiltConditionalSourceBound
  rw [Finset.sum_eq_single target]
  · simp
  · intro coordinate _hCoordinate hCoordinate
    simp [hCoordinate]
  · intro hTarget
    exact False.elim (hTarget (Finset.mem_univ target))

/-- The existing exact source-tilt variation profile is the generic singleton
profile of amplitude `R - R⁻¹`. -/
theorem finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation_eq_singleton
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (source : FiniteEvenFourTorusSpatialLink H) :
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation
        H β energyIdentity energyNontrivial source =
      finiteInfluenceKernelSingletonVariation
        (finiteZ2CrossingLikelihoodRatio
            (z2WilsonTemporalCrossingRate
              β energyIdentity energyNontrivial) -
          (finiteZ2CrossingLikelihoodRatio
            (z2WilsonTemporalCrossingRate
              β energyIdentity energyNontrivial))⁻¹)
        source := by
  funext coordinate
  rfl

/-- The singleton source-tilt amplitude is nonnegative. -/
theorem finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltAmplitude_nonneg
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial) :
    0 ≤ finiteZ2CrossingLikelihoodRatio
          (z2WilsonTemporalCrossingRate
            β energyIdentity energyNontrivial) -
        (finiteZ2CrossingLikelihoodRatio
          (z2WilsonTemporalCrossingRate
            β energyIdentity energyNontrivial))⁻¹ := by
  let ratio := finiteZ2CrossingLikelihoodRatio
    (z2WilsonTemporalCrossingRate
      β energyIdentity energyNontrivial)
  have hRatioPos : 0 < ratio :=
    finiteZ2CrossingLikelihoodRatio_pos
      (z2WilsonTemporalCrossingRate_pos hβ hEnergy).le
      (z2WilsonTemporalCrossingRate_lt_one hβ hEnergy)
  have hRatioOne : 1 ≤ ratio :=
    one_le_finiteZ2CrossingLikelihoodRatio
      (z2WilsonTemporalCrossingRate_pos hβ hEnergy).le
      (z2WilsonTemporalCrossingRate_lt_one hβ hEnergy)
  have hInvLeOne : ratio⁻¹ ≤ 1 :=
    (inv_le_one₀ hRatioPos).2 hRatioOne
  dsimp [ratio]
  linarith

/-- Canonical non-strict influence matrix of one fixed hidden posterior. -/
noncomputable def
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorCanonicalNonstrictData
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (environment : FiniteEvenFourTorusZ2SliceConfiguration H) :
    FinitePositiveWeightNonstrictL1MatrixData
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
        H β energyIdentity energyNontrivial hβ.le hEnergy.le environment) :=
  finitePositiveWeightCanonicalNonstrictL1MatrixData
    (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
      H β energyIdentity energyNontrivial hβ.le hEnergy.le environment)

/-- Non-strict stationary comparison data between two target fibers of one
hidden posterior. -/
noncomputable def
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetFiberNonstrictComparisonData
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (environment : FiniteEvenFourTorusZ2SliceConfiguration H)
    (target : FiniteEvenFourTorusSpatialLink H)
    (g h : Z2Gauge) :
    FinitePositiveWeightStationaryNonstrictComparisonData
      (finitePositiveWeightMultiplicativeTilt
        (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
          H β energyIdentity energyNontrivial hβ.le hEnergy.le
          (Function.update environment target g))
        (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTilt
          H β energyIdentity energyNontrivial
          (Function.update environment target g) target h))
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
        H β energyIdentity energyNontrivial hβ.le hEnergy.le
        (Function.update environment target g)) := by
  let ratio := finiteZ2CrossingLikelihoodRatio
    (z2WilsonTemporalCrossingRate
      β energyIdentity energyNontrivial)
  have hRatioPos : 0 < ratio :=
    finiteZ2CrossingLikelihoodRatio_pos
      (z2WilsonTemporalCrossingRate_pos hβ hEnergy).le
      (z2WilsonTemporalCrossingRate_lt_one hβ hEnergy)
  have hRatioOne : 1 ≤ ratio :=
    one_le_finiteZ2CrossingLikelihoodRatio
      (z2WilsonTemporalCrossingRate_pos hβ hEnergy).le
      (z2WilsonTemporalCrossingRate_lt_one hβ hEnergy)
  have hLowerUpper : ratio⁻¹ ≤ ratio :=
    le_trans ((inv_le_one₀ hRatioPos).2 hRatioOne) hRatioOne
  exact
    finitePositiveWeightLocalTiltStationaryNonstrictComparisonData
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
        H β energyIdentity energyNontrivial hβ.le hEnergy.le
        (Function.update environment target g))
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTilt
        H β energyIdentity energyNontrivial
        (Function.update environment target g) target h)
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight_pos
        H β energyIdentity energyNontrivial hβ hEnergy
        (Function.update environment target g))
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTilt_pos
        H β energyIdentity energyNontrivial hβ hEnergy
        (Function.update environment target g) target h)
      ({target} : Finset (FiniteEvenFourTorusSpatialLink H))
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTilt_supportedOn_target
        H β energyIdentity energyNontrivial
        (Function.update environment target g) target h)
      ratio⁻¹ ratio
      (inv_pos.mpr hRatioPos) hRatioPos hLowerUpper
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTilt_ratio_inv_le
        H β energyIdentity energyNontrivial hβ hEnergy
        (Function.update environment target g) target h)
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTilt_le_ratio
        H β energyIdentity energyNontrivial hβ hEnergy
        (Function.update environment target g) target h)
      (Fintype.card_pos_iff.mpr ⟨target⟩)
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorCanonicalNonstrictData
        H β energyIdentity energyNontrivial hβ hEnergy
        (Function.update environment target g))

/-- Uniform reciprocal-kernel certificate for all target fibers.  It bounds the
concrete canonical non-strict matrices, not an assumed strict Dobrushin matrix,
so its logical use is non-circular. -/
structure
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial) where
  iterations : ℕ
  kernel :
    FiniteNonnegativeInfluenceKernelData
      (FiniteEvenFourTorusSpatialLink H)
  columnCoefficient : ℝ
  columnCoefficient_nonneg : 0 ≤ columnCoefficient
  columnCoefficient_lt_one : columnCoefficient < 1
  columnSum_le :
    ∀ source : FiniteEvenFourTorusSpatialLink H,
      finiteInfluenceKernelColumnSum kernel source ≤ columnCoefficient
  canonicalInfluence_le :
    ∀ (environment : FiniteEvenFourTorusZ2SliceConfiguration H)
      (boundaryTarget : FiniteEvenFourTorusSpatialLink H)
      (g : Z2Gauge)
      (target source : FiniteEvenFourTorusSpatialLink H),
      finitePositiveWeightCanonicalNonstrictInfluence
          (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
            H β energyIdentity energyNontrivial hβ.le hEnergy.le
            (Function.update environment boundaryTarget g))
          target source ≤
        kernel.influence target source

/-- Kernel response error for one target/source pair. -/
noncomputable def
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseError
    {H : ℕ}
    {β energyIdentity energyNontrivial : ℝ}
    {hβ : 0 < β}
    {hEnergy : energyIdentity < energyNontrivial}
    (C :
      FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate
        H β energyIdentity energyNontrivial hβ hEnergy)
    (target source : FiniteEvenFourTorusSpatialLink H) : ℝ :=
  finiteInfluenceKernelPartialSource
      C.kernel
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
        H β energyIdentity energyNontrivial target)
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation
        H β energyIdentity energyNontrivial source)
      C.iterations +
    2 * finiteProductVariationTotal
      (finiteInfluenceKernelRandomScanVariationIterate
        C.kernel
        (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation
          H β energyIdentity energyNontrivial source)
        C.iterations)

/-- Kernel partial source response is nonnegative for the actual nonnegative
source and target envelopes. -/
theorem
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.partialSource_nonneg
    {H : ℕ}
    {β energyIdentity energyNontrivial : ℝ}
    {hβ : 0 < β}
    {hEnergy : energyIdentity < energyNontrivial}
    (C :
      FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate
        H β energyIdentity energyNontrivial hβ hEnergy)
    (target source : FiniteEvenFourTorusSpatialLink H) :
    0 ≤ finiteInfluenceKernelPartialSource
      C.kernel
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
        H β energyIdentity energyNontrivial target)
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation
        H β energyIdentity energyNontrivial source)
      C.iterations := by
  let envelope :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
      H β energyIdentity energyNontrivial target
  let variation :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation
      H β energyIdentity energyNontrivial source
  have hEnvelope : ∀ e, 0 ≤ envelope e :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope_nonneg
      H β energyIdentity energyNontrivial hβ hEnergy target
  have hVariation : ∀ e, 0 ≤ variation e :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation_nonneg
      H β energyIdentity energyNontrivial hβ hEnergy source
  induction C.iterations with
  | zero => exact le_rfl
  | succ n ih =>
      unfold finiteInfluenceKernelPartialSource
      exact add_nonneg ih
        (mul_nonneg (inv_nonneg.mpr (Nat.cast_nonneg _))
          (Finset.sum_nonneg fun e _he =>
            mul_nonneg (hEnvelope e)
              (finiteInfluenceKernelRandomScanVariationIterate_nonneg
                C.kernel variation hVariation n e)))

/-- The actual kernel response error is nonnegative. -/
theorem
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseError_nonneg
    {H : ℕ}
    {β energyIdentity energyNontrivial : ℝ}
    {hβ : 0 < β}
    {hEnergy : energyIdentity < energyNontrivial}
    (C :
      FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate
        H β energyIdentity energyNontrivial hβ hEnergy)
    (target source : FiniteEvenFourTorusSpatialLink H) :
    0 ≤ C.responseError target source := by
  unfold
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseError
  exact add_nonneg (C.partialSource_nonneg target source)
    (mul_nonneg (by norm_num)
      (Finset.sum_nonneg fun e _he =>
        finiteInfluenceKernelRandomScanVariationIterate_nonneg
          C.kernel
          (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation
            H β energyIdentity energyNontrivial source)
          (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation_nonneg
            H β energyIdentity energyNontrivial hβ hEnergy source)
          C.iterations e))

/-- The finite non-strict stationary comparison is controlled by the uniform
reciprocal kernel response error. -/
theorem finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTiltExpectation_difference_abs_le_reciprocalKernel
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 < β)
    (hEnergy : energyIdentity < energyNontrivial)
    (environment : FiniteEvenFourTorusZ2SliceConfiguration H)
    (target source : FiniteEvenFourTorusSpatialLink H)
    (g h replacement : Z2Gauge)
    (C :
      FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate
        H β energyIdentity energyNontrivial hβ hEnergy) :
    |finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTiltExpectation
          H β energyIdentity energyNontrivial hβ.le hEnergy.le
          environment (Function.update environment target h)
          source replacement -
        finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTiltExpectation
          H β energyIdentity energyNontrivial hβ.le hEnergy.le
          environment (Function.update environment target g)
          source replacement| ≤
      C.responseError target source := by
  let rightWeight :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight
      H β energyIdentity energyNontrivial hβ.le hEnergy.le
      (Function.update environment target g)
  let targetTilt :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTilt
      H β energyIdentity energyNontrivial
      (Function.update environment target g) target h
  let observable :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTilt
      H β energyIdentity energyNontrivial environment source replacement
  let P :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariationBound
      H β energyIdentity energyNontrivial hβ hEnergy
      environment source replacement
  let comparison :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetFiberNonstrictComparisonData
      H β energyIdentity energyNontrivial hβ hEnergy
      environment target g h
  have hDomination :
      FinitePositiveWeightNonstrictInfluenceDominatedBy
        comparison.rightInfluence C.kernel.influence := by
    intro responseTarget responseSource
    simpa [comparison,
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetFiberNonstrictComparisonData,
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorCanonicalNonstrictData]
      using C.canonicalInfluence_le
        environment target g responseTarget responseSource
  have hEnvelopeNonneg :
      ∀ e : FiniteEvenFourTorusSpatialLink H,
        0 ≤ finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
          H β energyIdentity energyNontrivial target e :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope_nonneg
      H β energyIdentity energyNontrivial hβ hEnergy target
  have hEnvelope :
      ∀ e : FiniteEvenFourTorusSpatialLink H,
        comparison.sourceBound e ≤
          finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
            H β energyIdentity energyNontrivial target e := by
    intro e
    exact le_rfl
  have hPartial :=
    comparison.partialStationarySource_le_kernel
      P comparison C.kernel hDomination
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
        H β energyIdentity energyNontrivial target)
      hEnvelopeNonneg hEnvelope C.iterations
  have hTerminal :
      finiteProductVariationTotal
          (comparison.rightRandomScanIterateVariationBound
            P C.iterations).variation ≤
        finiteProductVariationTotal
          (finiteInfluenceKernelRandomScanVariationIterate
            C.kernel P.variation C.iterations) := by
    unfold finiteProductVariationTotal
    apply Finset.sum_le_sum
    intro e _he
    rw [comparison.rightRandomScanIterateVariation_eq P C.iterations]
    exact
      finitePositiveWeightNonstrictRandomScanVariationIterate_le_kernel
        comparison.rightInfluence C.kernel hDomination P.variation
        P.variation_nonneg C.iterations e
  have hFinite :=
    comparison.expectationDiscrepancy_le_partialSource_add_two_mul_terminalVariation
      P C.iterations
  have hBound :
      comparison.expectationDiscrepancy observable ≤
        C.responseError target source := by
    apply hFinite.trans
    unfold
      FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseError
    exact add_le_add hPartial
      (mul_le_mul_of_nonneg_left hTerminal (by norm_num))
  rw [
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTiltExpectation_eq_globalExpectation,
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedResidualSourceTiltExpectation_eq_globalExpectation,
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorWeight_update_target_eq_tilt
      H β energyIdentity energyNontrivial hβ hEnergy environment target g h]
  simpa [comparison, observable,
    FinitePositiveWeightStationaryNonstrictComparisonData.expectationDiscrepancy]
    using hBound

/-- Uniform source-summed reciprocal response coefficient.  The accumulated
part is volume independent; the explicit finite terminal is retained as
`2 |I| q_col^n`. -/
noncomputable def
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseRowCoefficient
    {H : ℕ}
    {β energyIdentity energyNontrivial : ℝ}
    {hβ : 0 < β}
    {hEnergy : energyIdentity < energyNontrivial}
    (C :
      FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate
        H β energyIdentity energyNontrivial hβ hEnergy) : ℝ :=
  let sourceMagnitude :=
    finiteZ2CrossingLikelihoodRatio
        (z2WilsonTemporalCrossingRate
          β energyIdentity energyNontrivial) -
      (finiteZ2CrossingLikelihoodRatio
        (z2WilsonTemporalCrossingRate
          β energyIdentity energyNontrivial))⁻¹
  finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceAmplitude
      β energyIdentity energyNontrivial *
      sourceMagnitude * (1 - C.columnCoefficient)⁻¹ +
    2 * (Fintype.card (FiniteEvenFourTorusSpatialLink H) : ℝ) *
      (finiteInfluenceKernelReciprocalRandomScanRate
        (FiniteEvenFourTorusSpatialLink H) C.columnCoefficient ^
          C.iterations * sourceMagnitude)

/-- The reciprocal response coefficient is nonnegative. -/
theorem
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseRowCoefficient_nonneg
    {H : ℕ}
    {β energyIdentity energyNontrivial : ℝ}
    {hβ : 0 < β}
    {hEnergy : energyIdentity < energyNontrivial}
    (C :
      FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate
        H β energyIdentity energyNontrivial hβ hEnergy) :
    0 ≤ C.responseRowCoefficient := by
  have hSourceMagnitude :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltAmplitude_nonneg
      β energyIdentity energyNontrivial hβ hEnergy
  have hTargetAmplitude :
      0 ≤ finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceAmplitude
        β energyIdentity energyNontrivial := by
    let target := Classical.choice
      (Fintype.card_pos_iff.mp
        (Fintype.card_pos_iff.mpr
          ⟨Classical.choice
            (inferInstance : Nonempty (FiniteEvenFourTorusSpatialLink H))⟩)) :
        Nonempty (FiniteEvenFourTorusSpatialLink H))
    rw [←
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope_total
        H β energyIdentity energyNontrivial target]
    exact Finset.sum_nonneg fun e _he =>
      finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope_nonneg
        H β energyIdentity energyNontrivial hβ hEnergy target e
  have hGapInv : 0 ≤ (1 - C.columnCoefficient)⁻¹ :=
    le_of_lt (inv_pos.mpr (sub_pos.mpr C.columnCoefficient_lt_one))
  have hRate :
      0 ≤ finiteInfluenceKernelReciprocalRandomScanRate
        (FiniteEvenFourTorusSpatialLink H) C.columnCoefficient :=
    finiteInfluenceKernelReciprocalRandomScanRate_nonneg
      (Fintype.card_pos_iff.mpr
        ⟨Classical.choice
          (inferInstance : Nonempty (FiniteEvenFourTorusSpatialLink H))⟩)
      C.columnCoefficient C.columnCoefficient_nonneg
  unfold
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseRowCoefficient
  exact add_nonneg
    (mul_nonneg
      (mul_nonneg hTargetAmplitude hSourceMagnitude) hGapInv)
    (mul_nonneg
      (mul_nonneg (by norm_num) (Nat.cast_nonneg _))
      (mul_nonneg (pow_nonneg hRate C.iterations) hSourceMagnitude))

/-- Source-summed actual reciprocal response error is bounded uniformly by the
explicit reciprocal row coefficient. -/
theorem
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseErrorRowSum_le
    {H : ℕ}
    {β energyIdentity energyNontrivial : ℝ}
    {hβ : 0 < β}
    {hEnergy : energyIdentity < energyNontrivial}
    (C :
      FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate
        H β energyIdentity energyNontrivial hβ hEnergy)
    (target : FiniteEvenFourTorusSpatialLink H) :
    (∑ source : FiniteEvenFourTorusSpatialLink H,
      C.responseError target source) ≤ C.responseRowCoefficient := by
  let sourceMagnitude :=
    finiteZ2CrossingLikelihoodRatio
        (z2WilsonTemporalCrossingRate
          β energyIdentity energyNontrivial) -
      (finiteZ2CrossingLikelihoodRatio
        (z2WilsonTemporalCrossingRate
          β energyIdentity energyNontrivial))⁻¹
  have hMagnitude : 0 ≤ sourceMagnitude :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltAmplitude_nonneg
      β energyIdentity energyNontrivial hβ hEnergy
  have hCard :
      0 < Fintype.card (FiniteEvenFourTorusSpatialLink H) :=
    Fintype.card_pos_iff.mpr ⟨target⟩
  have hEnvelopeNonneg :
      ∀ e : FiniteEvenFourTorusSpatialLink H,
        0 ≤ finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
          H β energyIdentity energyNontrivial target e :=
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope_nonneg
      H β energyIdentity energyNontrivial hβ hEnergy target
  have hPartial :=
    finiteInfluenceKernelPartialSource_singleton_sum_source_le_resolvent
      C.kernel hCard C.columnCoefficient C.columnCoefficient_nonneg
      C.columnCoefficient_lt_one C.columnSum_le
      (finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope
        H β energyIdentity energyNontrivial target)
      hEnvelopeNonneg sourceMagnitude hMagnitude C.iterations
  have hTerminal :=
    finiteInfluenceKernelSingletonVariation_iterate_total_sum_source_le
      C.kernel hCard C.columnCoefficient C.columnCoefficient_nonneg
      C.columnSum_le sourceMagnitude hMagnitude C.iterations
  rw [←
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedTargetTiltSourceEnvelope_total
      H β energyIdentity energyNontrivial target] at hPartial
  unfold
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseError
  simp_rw [
    finiteEvenFourTorusZ2UnfixedGaugePerronSmoothedSourceTiltVariation_eq_singleton]
  rw [Finset.sum_add_distrib, ← Finset.mul_sum]
  unfold
    FiniteEvenFourTorusZ2UnfixedGaugePerronSmoothedPosteriorReciprocalKernelCertificate.responseRowCoefficient
  exact add_le_add hPartial
    (mul_le_mul_of_nonneg_left hTerminal (by norm_num))

end

end MathlibAnalytic
end MGAP4D
