import MGAP4D.MathlibAnalytic.FiniteOneDimensionalGroundSpectralProjectorRankOne
import MGAP4D.MathlibAnalytic.Z2FiniteEvenFourTorusCanonicalGroundRankOneProjectorQuadratic
import MGAP4D.MathlibAnalytic.Z2FiniteEvenFourTorusUnfixedGaugePerronGroundSimplicity
import Mathlib.Tactic

namespace MGAP4D
namespace MathlibAnalytic

open scoped InnerProduct

noncomputable section

/-- The actual finite-volume ambient ground spectral projector is the normalized
rank-one projector generated by the continuous canonical Perron ground.  This
is a basis-free identification: no differentiability of the canonical
Mathlib eigenbasis is involved. -/
theorem finiteEvenFourTorusZ2UnfixedGaugeAmbientGroundSpectralProjector_eq_canonicalPerronRankOne
    (H : ℕ)
    (β energyIdentity energyNontrivial : ℝ)
    (hβ : 0 ≤ β)
    (hEnergy : energyIdentity ≤ energyNontrivial) :
    let D :=
      finiteEvenFourTorusZ2UnfixedGaugeAmbientSpectralData
        H β energyIdentity energyNontrivial hβ hEnergy
    let p :=
      finiteEvenFourTorusZ2UnfixedGaugeCanonicalPerronGround
        H energyIdentity energyNontrivial ⟨β, hβ⟩
    D.groundSpectralProjector =
      (inner ℝ p p)⁻¹ • InnerProductSpace.rankOne ℝ p p := by
  let D :=
    finiteEvenFourTorusZ2UnfixedGaugeAmbientSpectralData
      H β energyIdentity energyNontrivial hβ hEnergy
  let βp : Set.Ici (0 : ℝ) := ⟨β, hβ⟩
  let p :=
    finiteEvenFourTorusZ2UnfixedGaugeCanonicalPerronGround
      H energyIdentity energyNontrivial βp
  have hspec :=
    finiteEvenFourTorusZ2UnfixedGaugeCanonicalPerronGround_spec
      H energyIdentity energyNontrivial hEnergy βp
  have hpne : p ≠ 0 := by
    intro hpzero
    let A : FiniteEvenFourTorusZ2SliceConfiguration H := fun _ => 1
    have hpos : 0 < p A := by
      simpa [p] using hspec.2.1 A
    rw [hpzero] at hpos
    simp at hpos
  have hpfix : D.operator p = p := by
    change
      finiteEvenFourTorusZ2UnfixedGaugeOneSlabTransfer
          H β energyIdentity energyNontrivial hβ hEnergy p = p
    rw [← finiteEvenFourTorusZ2UnfixedGaugeOneSlabTransferCouplingFamily_eq_actual
      H β energyIdentity energyNontrivial hβ hEnergy]
    exact hspec.2.2
  have hline : ∀ g : FiniteEvenFourTorusZ2SliceHilbert H,
      D.operator g = g → ∃ c : ℝ, g = c • p := by
    intro g hg
    have hgCF :
        finiteKernelNormalizedOperator
            (finiteEvenFourTorusZ2UnfixedGaugeOneSlabKernelCouplingFamily
              H energyIdentity energyNontrivial β) g = g := by
      change
        finiteEvenFourTorusZ2UnfixedGaugeOneSlabTransfer
            H β energyIdentity energyNontrivial hβ hEnergy g = g at hg
      rw [← finiteEvenFourTorusZ2UnfixedGaugeOneSlabTransferCouplingFamily_eq_actual
        H β energyIdentity energyNontrivial hβ hEnergy] at hg
      exact hg
    obtain ⟨a, ha⟩ :=
      finiteEvenFourTorusZ2UnfixedGaugeCouplingFamily_fixed_eq_smul_chosenGround
        H energyIdentity energyNontrivial hEnergy βp g hgCF
    obtain ⟨c, hcpos, hpchosen⟩ :=
      finiteEvenFourTorusZ2UnfixedGaugeCanonicalPerronGround_eq_pos_smul_chosenGround
        H energyIdentity energyNontrivial hEnergy βp
    refine ⟨a / c, ?_⟩
    rw [ha]
    have hscaled :=
      congrArg
        (fun v : FiniteEvenFourTorusZ2SliceHilbert H => (a / c) • v)
        hpchosen
    symm
    simpa [p, smul_smul, div_mul_cancel₀ a (ne_of_gt hcpos)] using hscaled
  change D.groundSpectralProjector =
    (inner ℝ p p)⁻¹ • InnerProductSpace.rankOne ℝ p p
  exact D.groundSpectralProjector_eq_normalized_rankOne p hpne hpfix hline

end

end MathlibAnalytic
end MGAP4D
