import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelTheoremSurfaceAggregateFinalReceipt

namespace MGAP4D
namespace R4
namespace Theorem

open scoped BigOperators ENNReal lp

noncomputable section

/-- Chain index for the actual-Borel theorem-surface aggregate route.

This records the ordered external route from the aggregate-safe sigma-carrier
receipt, through the theorem-surface aggregate receipt, to the final receipt.
It remains outside `TheoremSurface`, so the aggregate surface never imports a
file that imports it back. -/
def SpectralMeasurePVMActualBorelTheoremSurfaceAggregateChainIndexReady : Prop :=
  SpectralMeasurePVMActualBorelSigmaCarrierHandoffAggregateSafeReceiptReady ∧
  SpectralMeasurePVMActualBorelSigmaCarrierHandoffAggregateSafeReceiptPublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelTheoremSurfaceAggregateReceiptReady ∧
  SpectralMeasurePVMActualBorelTheoremSurfaceAggregateReceiptPublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelTheoremSurfaceAggregateFinalReceiptReady ∧
  SpectralMeasurePVMActualBorelTheoremSurfaceAggregateFinalReceiptPublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelSigmaCarrierHandoffRootFacingFinalExportIndexReady ∧
  SpectralMeasurePVMOperatorValuedR4CompletionBoundaryHeld ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The actual-Borel theorem-surface aggregate chain index is ready. -/
theorem spectral_measure_pvm_actual_borel_theorem_surface_aggregate_chain_index_ready :
    SpectralMeasurePVMActualBorelTheoremSurfaceAggregateChainIndexReady := by
  exact ⟨
    spectral_measure_pvm_actual_borel_sigma_carrier_handoff_aggregate_safe_receipt_ready,
    spectral_measure_pvm_actual_borel_sigma_carrier_handoff_aggregate_safe_receipt_public_boundary_held,
    spectral_measure_pvm_actual_borel_theorem_surface_aggregate_receipt_ready,
    spectral_measure_pvm_actual_borel_theorem_surface_aggregate_receipt_public_boundary_held,
    spectral_measure_pvm_actual_borel_theorem_surface_aggregate_final_receipt_ready,
    spectral_measure_pvm_actual_borel_theorem_surface_aggregate_final_receipt_public_boundary_held,
    spectral_measure_pvm_actual_borel_sigma_carrier_handoff_root_facing_final_export_index_ready,
    spectral_measure_pvm_operator_valued_r4_completion_boundary_held,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

/-- Public boundary for the actual-Borel theorem-surface aggregate chain index. -/
def SpectralMeasurePVMActualBorelTheoremSurfaceAggregateChainIndexPublicBoundaryHeld : Prop :=
  SpectralMeasurePVMActualBorelTheoremSurfaceAggregateChainIndexReady ∧
  SpectralMeasurePVMActualBorelTheoremSurfaceAggregateFinalReceiptPublicBoundaryHeld ∧
  SpectralMeasurePVMOperatorValuedR4CompletionBoundaryHeld ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The public boundary for the actual-Borel theorem-surface aggregate chain
index is held. -/
theorem spectral_measure_pvm_actual_borel_theorem_surface_aggregate_chain_index_public_boundary_held :
    SpectralMeasurePVMActualBorelTheoremSurfaceAggregateChainIndexPublicBoundaryHeld := by
  exact ⟨
    spectral_measure_pvm_actual_borel_theorem_surface_aggregate_chain_index_ready,
    spectral_measure_pvm_actual_borel_theorem_surface_aggregate_final_receipt_public_boundary_held,
    spectral_measure_pvm_operator_valued_r4_completion_boundary_held,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

end

end Theorem
end R4
end MGAP4D
