import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelProjectionMapExtensionalGuardPhaseSurface
import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelCountableFamilyDisjointnessSkeleton

namespace MGAP4D
namespace R4
namespace Theorem

open scoped BigOperators ENNReal lp

noncomputable section

/-- Surface bundle for the actual-Borel countable-family disjointness skeleton phase. -/
def SpectralMeasurePVMActualBorelCountableFamilyDisjointnessSkeletonPhaseSurfaceReady : Prop :=
  SpectralMeasurePVMActualBorelProjectionMapExtensionalGuardPhaseSurfaceReady ∧
  SpectralMeasurePVMActualBorelCountableFamilyDisjointnessSkeletonPublicBoundaryHeld ∧
  SpectralMeasurePVMGenuineOperatorTopologyCountableAdditivityStillOpen ∧
  SpectralMeasurePVMGenuineSelfAdjointSpectralTheoremStillOpen ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The actual-Borel countable-family disjointness skeleton phase surface is ready. -/
theorem spectral_measure_pvm_actual_borel_countable_family_disjointness_skeleton_phase_surface_ready :
    SpectralMeasurePVMActualBorelCountableFamilyDisjointnessSkeletonPhaseSurfaceReady := by
  exact ⟨
    spectral_measure_pvm_actual_borel_projection_map_extensional_guard_phase_surface_ready,
    spectral_measure_pvm_actual_borel_countable_family_disjointness_skeleton_public_boundary_held,
    spectral_measure_pvm_genuine_operator_topology_countable_additivity_still_open_ready,
    spectral_measure_pvm_genuine_self_adjoint_spectral_theorem_still_open_ready,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

end

end Theorem
end R4
end MGAP4D
