import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelDiracZeroOperatorTopologyCountableAdditivityHandoff

namespace MGAP4D
namespace R4
namespace Theorem

open scoped BigOperators ENNReal lp

noncomputable section

/-- Abstract `tsum` candidate for Dirac-zero actual-Borel projection families.

A later analytic file may instantiate this by Mathlib `tsum` / `HasSum` in the
chosen operator topology.  Here it is only an abstract evaluator of countable
operator families. -/
abbrev SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidate :=
  (ℕ → SpectralMeasurePVMActualBorelProjectionOperator) →
    SpectralMeasurePVMActualBorelProjectionOperator

/-- The countable family of summand projections generated by the Dirac-zero
kernel. -/
def spectralMeasurePVMActualBorelDiracZeroSummandFamily
    (F : SpectralMeasurePVMActualBorelCountableFamily) :
    ℕ → SpectralMeasurePVMActualBorelProjectionOperator :=
  fun n => spectralMeasurePVMActualBorelDiracZeroProjectionMap (F n)

/-- The projection of the countable union generated by the Dirac-zero kernel. -/
def spectralMeasurePVMActualBorelDiracZeroUnionProjection
    (F : SpectralMeasurePVMActualBorelCountableFamily) :
    SpectralMeasurePVMActualBorelProjectionOperator :=
  spectralMeasurePVMActualBorelDiracZeroProjectionMap
    (spectralMeasurePVMActualBorelCarrierSetIUnion F)

/-- Compatibility conditions required from an abstract `tsum` candidate on the
reduced Dirac-zero inputs.

The candidate must read a zero-series as zero and a one-hit-series as its unique
nonzero summand. -/
structure SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateCompatible
    (TsumCandidate : SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidate) : Prop where
  zeroSeries :
    ∀ F : SpectralMeasurePVMActualBorelCountableFamily,
      SpectralMeasurePVMActualBorelDiracZeroTsumZeroSeriesInput F →
        TsumCandidate (spectralMeasurePVMActualBorelDiracZeroSummandFamily F) = 0
  oneHitSeries :
    ∀ (F : SpectralMeasurePVMActualBorelCountableFamily) (k : ℕ),
      SpectralMeasurePVMActualBorelDiracZeroTsumOneHitSeriesInput F k →
        TsumCandidate (spectralMeasurePVMActualBorelDiracZeroSummandFamily F) =
          spectralMeasurePVMActualBorelDiracZeroProjectionMap (F k)

/-- A compatible abstract `tsum` candidate realizes countable additivity on any
Dirac-zero `tsum` input surface. -/
theorem spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_realizes_input_surface
    (TsumCandidate : SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidate)
    (hcompat : SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateCompatible TsumCandidate)
    (F : SpectralMeasurePVMActualBorelCountableFamily)
    (hinput : SpectralMeasurePVMActualBorelDiracZeroTsumInputSurface F) :
    TsumCandidate (spectralMeasurePVMActualBorelDiracZeroSummandFamily F) =
      spectralMeasurePVMActualBorelDiracZeroUnionProjection F := by
  rcases hinput with hzero | hone
  · exact (hcompat.zeroSeries F hzero).trans hzero.1.symm
  · rcases hone with ⟨k, _hk, hhit⟩
    exact (hcompat.oneHitSeries F k hhit).trans hhit.1.symm

/-- Pairwise-disjoint actual-Borel families are realized by any compatible
abstract `tsum` candidate. -/
theorem spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_realizes_pairwise_disjoint_family
    (TsumCandidate : SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidate)
    (hcompat : SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateCompatible TsumCandidate)
    (F : SpectralMeasurePVMActualBorelCountableFamily)
    (hdis : SpectralMeasurePVMActualBorelCountableFamilyPairwiseDisjoint F) :
    TsumCandidate (spectralMeasurePVMActualBorelDiracZeroSummandFamily F) =
      spectralMeasurePVMActualBorelDiracZeroUnionProjection F := by
  exact spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_realizes_input_surface
    TsumCandidate hcompat F
    (spectral_measure_pvm_actual_borel_dirac_zero_pairwise_disjoint_tsum_input_surface F hdis)

/-- Abstract `tsum` candidate bridge target for Dirac-zero actual-Borel countable
additivity. -/
def SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateBridgeTarget : Prop :=
  SpectralMeasurePVMActualBorelDiracZeroOperatorTopologyCountableAdditivityHandoffTarget ∧
  (∀ TsumCandidate : SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidate,
    SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateCompatible TsumCandidate →
      ∀ F : SpectralMeasurePVMActualBorelCountableFamily,
        SpectralMeasurePVMActualBorelCountableFamilyPairwiseDisjoint F →
          TsumCandidate (spectralMeasurePVMActualBorelDiracZeroSummandFamily F) =
            spectralMeasurePVMActualBorelDiracZeroUnionProjection F)

/-- The abstract `tsum` candidate bridge target is ready. -/
theorem spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_bridge_target_ready :
    SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateBridgeTarget := by
  exact ⟨
    spectral_measure_pvm_actual_borel_dirac_zero_operator_topology_countable_additivity_handoff_target_ready,
    spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_realizes_pairwise_disjoint_family⟩

/-- Bridge after the Dirac-zero abstract `tsum` candidate step.

The remaining analytic residual is now sharply isolated: instantiate a compatible
candidate by the concrete Mathlib `tsum` / `HasSum` operator-topology machinery. -/
def SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateBridgeReady : Prop :=
  SpectralMeasurePVMActualBorelDiracZeroOperatorTopologyCountableAdditivityHandoffPublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateBridgeTarget ∧
  SpectralMeasurePVMGenuineOperatorTopologyCountableAdditivityStillOpen ∧
  SpectralMeasurePVMGenuineSelfAdjointSpectralTheoremStillOpen ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The bridge after the Dirac-zero abstract `tsum` candidate step is ready. -/
theorem spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_bridge_ready :
    SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateBridgeReady := by
  exact ⟨
    spectral_measure_pvm_actual_borel_dirac_zero_operator_topology_countable_additivity_handoff_public_boundary_held,
    spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_bridge_target_ready,
    spectral_measure_pvm_genuine_operator_topology_countable_additivity_still_open_ready,
    spectral_measure_pvm_genuine_self_adjoint_spectral_theorem_still_open_ready,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

/-- Public boundary after the Dirac-zero abstract `tsum` candidate step. -/
def SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidatePublicBoundaryHeld : Prop :=
  SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateBridgeReady ∧
  SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidateBridgeTarget ∧
  SpectralMeasurePVMGenuineOperatorTopologyCountableAdditivityStillOpen ∧
  SpectralMeasurePVMGenuineSelfAdjointSpectralTheoremStillOpen ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The public boundary after the Dirac-zero abstract `tsum` candidate step is
held. -/
theorem spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_public_boundary_held :
    SpectralMeasurePVMActualBorelDiracZeroAbstractTsumCandidatePublicBoundaryHeld := by
  exact ⟨
    spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_bridge_ready,
    spectral_measure_pvm_actual_borel_dirac_zero_abstract_tsum_candidate_bridge_target_ready,
    spectral_measure_pvm_genuine_operator_topology_countable_additivity_still_open_ready,
    spectral_measure_pvm_genuine_self_adjoint_spectral_theorem_still_open_ready,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

end

end Theorem
end R4
end MGAP4D
