import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelMeasurableSetClosurePackage
import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelProjectionValuedMapInterface

namespace MGAP4D
namespace R4
namespace Theorem

open scoped BigOperators ENNReal lp

noncomputable section

/-- Surface bundle for the actual-Borel projection-map interface phase. -/
def SpectralMeasurePVMActualBorelProjectionMapPhaseSurfaceReady : Prop :=
  SpectralMeasurePVMActualBorelMeasurableSetClosurePackagePublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelProjectionValuedMapInterfacePublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelSetAlgebraRealizationStillOpen ∧
  SpectralMeasurePVMGenuineBorelCarrierRealizationStillOpen ∧
  SpectralMeasurePVMGenuineOperatorTopologyCountableAdditivityStillOpen ∧
  SpectralMeasurePVMGenuineSelfAdjointSpectralTheoremStillOpen ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The actual-Borel projection-map interface phase surface is ready. -/
theorem spectral_measure_pvm_actual_borel_projection_map_phase_surface_ready :
    SpectralMeasurePVMActualBorelProjectionMapPhaseSurfaceReady := by
  exact ⟨
    spectral_measure_pvm_actual_borel_measurable_set_closure_package_public_boundary_held,
    spectral_measure_pvm_actual_borel_projection_valued_map_interface_public_boundary_held,
    spectral_measure_pvm_actual_borel_set_algebra_realization_still_open_ready,
    spectral_measure_pvm_genuine_borel_carrier_realization_still_open_ready,
    spectral_measure_pvm_genuine_operator_topology_countable_additivity_still_open_ready,
    spectral_measure_pvm_genuine_self_adjoint_spectral_theorem_still_open_ready,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

end

end Theorem
end R4
end MGAP4D
