import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelDenseDiagonalPVMSourcedAggregateChainIndex

namespace MGAP4D
namespace R4
namespace Theorem

open scoped BigOperators ENNReal lp

noncomputable section

/-- Final receipt for the dense-diagonal PVM-sourced aggregate chain index. -/
def SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateChainIndexFinalReceiptReady : Prop :=
  SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateChainIndexReady ∧
  SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateChainIndexPublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateSafeExtensionReady ∧
  SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateSafeExtensionPublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedFinalClosureReady ∧
  SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedFinalClosurePublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelTheoremSurfaceAggregateChainIndexFinalReceiptReady ∧
  SpectralMeasurePVMActualBorelTheoremSurfaceAggregateChainIndexFinalReceiptPublicBoundaryHeld ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The final receipt for the dense-diagonal PVM-sourced aggregate chain index is ready. -/
theorem spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_aggregate_chain_index_final_receipt_ready :
    SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateChainIndexFinalReceiptReady := by
  exact ⟨
    spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_aggregate_chain_index_ready,
    spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_aggregate_chain_index_public_boundary_held,
    spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_aggregate_safe_extension_ready,
    spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_aggregate_safe_extension_public_boundary_held,
    spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_final_closure_ready,
    spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_final_closure_public_boundary_held,
    spectral_measure_pvm_actual_borel_theorem_surface_aggregate_chain_index_final_receipt_ready,
    spectral_measure_pvm_actual_borel_theorem_surface_aggregate_chain_index_final_receipt_public_boundary_held,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

/-- Public boundary for the final receipt of the dense-diagonal PVM-sourced
aggregate chain index. -/
def SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateChainIndexFinalReceiptPublicBoundaryHeld : Prop :=
  SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateChainIndexFinalReceiptReady ∧
  SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateChainIndexPublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateSafeExtensionPublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelTheoremSurfaceAggregateChainIndexFinalReceiptPublicBoundaryHeld ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The public boundary for the final receipt of the dense-diagonal PVM-sourced
aggregate chain index is held. -/
theorem spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_aggregate_chain_index_final_receipt_public_boundary_held :
    SpectralMeasurePVMActualBorelDenseDiagonalPVMSourcedAggregateChainIndexFinalReceiptPublicBoundaryHeld := by
  exact ⟨
    spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_aggregate_chain_index_final_receipt_ready,
    spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_aggregate_chain_index_public_boundary_held,
    spectral_measure_pvm_actual_borel_dense_diagonal_pvm_sourced_aggregate_safe_extension_public_boundary_held,
    spectral_measure_pvm_actual_borel_theorem_surface_aggregate_chain_index_final_receipt_public_boundary_held,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

end

end Theorem
end R4
end MGAP4D
