import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelCountableFamilyDisjointnessSkeletonPhaseSurface
import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelRecursiveFinitePartialUnion

namespace MGAP4D
namespace R4
namespace Theorem

open scoped BigOperators ENNReal lp

noncomputable section

/-- Surface bundle for the actual-Borel recursive finite-partial-union phase. -/
def SpectralMeasurePVMActualBorelRecursiveFinitePartialUnionPhaseSurfaceReady : Prop :=
  SpectralMeasurePVMActualBorelCountableFamilyDisjointnessSkeletonPhaseSurfaceReady ∧
  SpectralMeasurePVMActualBorelRecursiveFinitePartialUnionPublicBoundaryHeld ∧
  SpectralMeasurePVMGenuineOperatorTopologyCountableAdditivityStillOpen ∧
  SpectralMeasurePVMGenuineSelfAdjointSpectralTheoremStillOpen ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The actual-Borel recursive finite-partial-union phase surface is ready. -/
theorem spectral_measure_pvm_actual_borel_recursive_finite_partial_union_phase_surface_ready :
    SpectralMeasurePVMActualBorelRecursiveFinitePartialUnionPhaseSurfaceReady := by
  exact ⟨
    spectral_measure_pvm_actual_borel_countable_family_disjointness_skeleton_phase_surface_ready,
    spectral_measure_pvm_actual_borel_recursive_finite_partial_union_public_boundary_held,
    spectral_measure_pvm_genuine_operator_topology_countable_additivity_still_open_ready,
    spectral_measure_pvm_genuine_self_adjoint_spectral_theorem_still_open_ready,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

end

end Theorem
end R4
end MGAP4D
