import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelProjectionMapPhaseSurface
import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelEndpointProjectionMap

namespace MGAP4D
namespace R4
namespace Theorem

open scoped BigOperators ENNReal lp

noncomputable section

/-- Surface bundle for the actual-Borel endpoint projection-map phase. -/
def SpectralMeasurePVMActualBorelEndpointProjectionMapPhaseSurfaceReady : Prop :=
  SpectralMeasurePVMActualBorelProjectionMapPhaseSurfaceReady ∧
  SpectralMeasurePVMActualBorelEndpointProjectionMapPublicBoundaryHeld ∧
  SpectralMeasurePVMActualBorelSetAlgebraRealizationStillOpen ∧
  SpectralMeasurePVMGenuineBorelCarrierRealizationStillOpen ∧
  SpectralMeasurePVMGenuineOperatorTopologyCountableAdditivityStillOpen ∧
  SpectralMeasurePVMGenuineSelfAdjointSpectralTheoremStillOpen ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The actual-Borel endpoint projection-map phase surface is ready. -/
theorem spectral_measure_pvm_actual_borel_endpoint_projection_map_phase_surface_ready :
    SpectralMeasurePVMActualBorelEndpointProjectionMapPhaseSurfaceReady := by
  exact ⟨
    spectral_measure_pvm_actual_borel_projection_map_phase_surface_ready,
    spectral_measure_pvm_actual_borel_endpoint_projection_map_public_boundary_held,
    spectral_measure_pvm_actual_borel_set_algebra_realization_still_open_ready,
    spectral_measure_pvm_genuine_borel_carrier_realization_still_open_ready,
    spectral_measure_pvm_genuine_operator_topology_countable_additivity_still_open_ready,
    spectral_measure_pvm_genuine_self_adjoint_spectral_theorem_still_open_ready,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

end

end Theorem
end R4
end MGAP4D
