import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelFiniteStageAdditivityObligationPhaseSurface
import MGAP4D.R4.Theorem.SpectralMeasurePVMOperatorValuedActualBorelLimitObligationPacket

namespace MGAP4D
namespace R4
namespace Theorem

open scoped BigOperators ENNReal lp

noncomputable section

/-- Surface bundle for the actual-Borel limit-obligation packet phase. -/
def SpectralMeasurePVMActualBorelLimitObligationPacketPhaseSurfaceReady : Prop :=
  SpectralMeasurePVMActualBorelFiniteStageAdditivityObligationPhaseSurfaceReady ∧
  SpectralMeasurePVMActualBorelLimitObligationPacketPublicBoundaryHeld ∧
  SpectralMeasurePVMGenuineOperatorTopologyCountableAdditivityStillOpen ∧
  SpectralMeasurePVMGenuineSelfAdjointSpectralTheoremStillOpen ∧
  SpectralMeasurePVMGenuineSpectralMeasureConstructionStillOpen ∧
  SpectralMeasurePVMNoShellToFullCollapseBoundary

/-- The actual-Borel limit-obligation packet phase surface is ready. -/
theorem spectral_measure_pvm_actual_borel_limit_obligation_packet_phase_surface_ready :
    SpectralMeasurePVMActualBorelLimitObligationPacketPhaseSurfaceReady := by
  exact ⟨
    spectral_measure_pvm_actual_borel_finite_stage_additivity_obligation_phase_surface_ready,
    spectral_measure_pvm_actual_borel_limit_obligation_packet_public_boundary_held,
    spectral_measure_pvm_genuine_operator_topology_countable_additivity_still_open_ready,
    spectral_measure_pvm_genuine_self_adjoint_spectral_theorem_still_open_ready,
    spectral_measure_pvm_genuine_spectral_measure_construction_still_open_ready,
    spectral_measure_pvm_no_shell_to_full_collapse_boundary_ready⟩

end

end Theorem
end R4
end MGAP4D
