import MGAP4D.OperatorAPI.TheoremSurface.CandidateSurface
import MGAP4D.OperatorAPI.TheoremSurface.DependencySurface
import MGAP4D.OperatorAPI.TheoremSurface.ExecutionSurface
import MGAP4D.OperatorAPI.TheoremSurface.ReviewGateSurface
